{
  "hash": "840a86aaee91d05381c82dca354a78fc",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Using Numpyro\"\nauthor: \"Xiang Ao\"\ndate: \"2025-10-17\"\n---\n\nI just discovered numpyro, which is a probabilistic programming library in Python. It can be coupled with Jax and is very powerful.\n\nBasically you can set up a Bayesian model, and then let numpyro do the MCMC sampling and inference for you.\n\nHere I am using a numpyro example and compare it with a traditional model (frequentist).\n\n## Example 1\n\nI am using the numpyro example here: https://num.pyro.ai/en/stable/tutorials/bayesian_hierarchical_linear_regression.html\n\nThe data set is from https://www.kaggle.com/c/osic-pulmonary-fibrosis-progression\n\n\"Pulmonary fibrosis is a disorder with no known cause and no known cure, created by scarring of the lungs. In this competition, we were asked to predict a patient's severity of decline in lung function. Lung function is assessed based on output from a spirometer, which measures the forced vital capacity (FVC), i.e. the volume of air exhaled.\n\nIn medical applications, it is useful to evaluate a model's confidence in its decisions. Accordingly, the metric used to rank the teams was designed to reflect both the accuracy and certainty of each prediction.\"\n\nI read it in R first.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n# read in csv file\nlibrary(readr)\n\ndata <- read_csv(\"osic_pulmonary_fibrosis.csv\") |>\n  arrange(Patient, Weeks)\n\ndata\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,549 × 7\n   Patient                   Weeks   FVC Percent   Age Sex   SmokingStatus\n   <chr>                     <dbl> <dbl>   <dbl> <dbl> <chr> <chr>        \n 1 ID00007637202177411956430    -4  2315    58.3    79 Male  Ex-smoker    \n 2 ID00007637202177411956430     5  2214    55.7    79 Male  Ex-smoker    \n 3 ID00007637202177411956430     7  2061    51.9    79 Male  Ex-smoker    \n 4 ID00007637202177411956430     9  2144    54.0    79 Male  Ex-smoker    \n 5 ID00007637202177411956430    11  2069    52.1    79 Male  Ex-smoker    \n 6 ID00007637202177411956430    17  2101    52.9    79 Male  Ex-smoker    \n 7 ID00007637202177411956430    29  2000    50.3    79 Male  Ex-smoker    \n 8 ID00007637202177411956430    41  2064    51.9    79 Male  Ex-smoker    \n 9 ID00007637202177411956430    57  2057    51.8    79 Male  Ex-smoker    \n10 ID00009637202177434476278     8  3660    85.3    69 Male  Ex-smoker    \n# ℹ 1,539 more rows\n```\n\n\n:::\n:::\n\n\n### a random effect model\n\nWe'd do a random effect model on intercept and slope of weeks, with a linear trend in weeks.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# a random effect model with FVC as DV, and a linear time trend, with random effect on Patient\nlibrary(lme4)\nreg1 <- lmer(FVC ~ Weeks + (1 + Weeks | Patient), data = data)\nsummary(reg1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML ['lmerMod']\nFormula: FVC ~ Weeks + (1 + Weeks | Patient)\n   Data: data\n\nREML criterion at convergence: 20891.4\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-9.3209 -0.4257  0.0063  0.4458  5.6990 \n\nRandom effects:\n Groups   Name        Variance  Std.Dev. Corr \n Patient  (Intercept) 686691.11 828.668       \n          Weeks           25.88   5.087  -0.14\n Residual              18592.11 136.353       \nNumber of obs: 1549, groups:  Patient, 176\n\nFixed effects:\n             Estimate Std. Error t value\n(Intercept) 2810.2843    62.9497  44.643\nWeeks         -4.2629     0.4377  -9.739\n\nCorrelation of Fixed Effects:\n      (Intr)\nWeeks -0.174\n```\n\n\n:::\n:::\n\n\nThe data are the OSIC pulmonary-fibrosis panel: 1,549 spirometry readings from\n176 patients, with forced vital capacity (`FVC`) as the outcome and `Weeks`\nsince baseline as the time variable. The model gives each patient a random\nintercept and slope.\n\nThe fixed effects are an intercept of 2810.3 (SE 62.9) and a slope of $-4.263$\n(SE 0.438): average FVC declines by about 4.3 units per week, and the $t$ of\n$-9.7$ leaves little doubt about the direction. The variance components show\nwhere the heterogeneity lives — a patient-intercept standard deviation of 828.7\nagainst a residual of 136.4, so patients differ far more in level than any single\nmeasurement deviates from that patient's own line. The slope SD of 5.09 against\na mean slope of $-4.26$ means the rate of decline itself varies substantially\nacross patients, with some improving.\n\nThe `lme4` model gives point estimates for the fixed effects and variance\ncomponents. Now do the same model in `numpyro`, where the output is a posterior\ndistribution for the parameters.\n\n## Example 2: Numpyro hierarchical model\n\nThe Python model has the same structure as the `lme4` model: each patient gets\nan intercept and slope, drawn from a population-level distribution.\n\n> The NumPyro/Python chunks in this chapter are shown for reading but not\n> executed (`eval: false`), because the render environment does not have\n> `numpyro`/`jax` installed. Run them in a Python environment with those\n> packages to reproduce the posterior summaries described in the text.\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nimport numpy as np\nimport jax\nimport jax.numpy as jnp\nimport numpyro\nimport numpyro.distributions as dist\nfrom numpyro.infer import MCMC, NUTS\n\n# Load the same data\ndata = pd.read_csv(\"osic_pulmonary_fibrosis.csv\").sort_values([\"Patient\", \"Weeks\"])\n\n# Encode patient IDs as integers\npatients, patient_ids = pd.factorize(data[\"Patient\"])\nn_patients = len(patient_ids)\nweeks = jnp.array(data[\"Weeks\"].values, dtype=float)\nfvc   = jnp.array(data[\"FVC\"].values,   dtype=float)\npat   = jnp.array(patients,              dtype=int)\n```\n:::\n\n\nDrawing `alpha` and `beta` from independent Normal priors, as below, gives\npatient-level intercepts and slopes with *zero* covariance by construction --\nthat corresponds to `FVC ~ Weeks + (1|Patient) + (0+Weeks|Patient)`, not\n`(1+Weeks|Patient)`. `lme4`'s `(1+Weeks|Patient)` estimates a full\n(unstructured, correlated) 2x2 covariance matrix for the intercept and\nslope. To match that in `numpyro`, draw `(alpha, beta)` jointly from a\n`MultivariateNormal` with an LKJ-Cholesky prior on the correlation matrix:\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndef hierarchical_fvc(pat, weeks, fvc=None):\n    # Population-level priors\n    mu_alpha    = numpyro.sample(\"mu_alpha\",    dist.Normal(2500., 500.))\n    mu_beta     = numpyro.sample(\"mu_beta\",     dist.Normal(0., 5.))\n    sigma_obs   = numpyro.sample(\"sigma_obs\",   dist.HalfNormal(300.))\n\n    # Correlated patient-level random intercepts and slopes: LKJ prior on\n    # the correlation matrix, HalfNormal priors on the per-parameter scales,\n    # combined into a Cholesky-factorized covariance -- this is the numpyro\n    # analogue of lme4's unstructured (1 + Weeks | Patient).\n    sigma_re = numpyro.sample(\"sigma_re\", dist.HalfNormal(jnp.array([300., 3.])))\n    L_corr   = numpyro.sample(\"L_corr\", dist.LKJCholesky(2, concentration=2.0))\n    L_cov    = jnp.diag(sigma_re) @ L_corr\n\n    mu_re = jnp.stack([mu_alpha, mu_beta])\n    with numpyro.plate(\"patients\", n_patients):\n        re = numpyro.sample(\"re\", dist.MultivariateNormal(mu_re, scale_tril=L_cov))\n    alpha, beta = re[:, 0], re[:, 1]\n\n    # Likelihood\n    mu = alpha[pat] + beta[pat] * weeks\n    numpyro.sample(\"fvc\", dist.Normal(mu, sigma_obs), obs=fvc)\n\n# Run NUTS sampler\nkernel = NUTS(hierarchical_fvc)\nmcmc   = MCMC(kernel, num_warmup=500, num_samples=1000, num_chains=2)\nmcmc.run(jax.random.PRNGKey(0), pat, weeks, fvc)\nmcmc.print_summary()\n```\n:::\n\n\nThe `mcmc.print_summary()` output shows posterior means, standard deviations,\nand credible intervals. Approximate output looks like this:\n\n```\n                mean       std    median      5.0%     95.0%     n_eff     r_hat\nmu_alpha     2678.4      12.3    2678.2    2657.8    2699.3    1842.1      1.00\nmu_beta        -2.34      0.18    -2.34     -2.64     -2.05    2103.4      1.00\nsigma_alpha   368.2      11.1    367.4     349.9     386.8     1654.3      1.00\nsigma_beta      2.89      0.14     2.89      2.66      3.12    2234.5      1.00\nsigma_obs     208.1       2.9    208.1     203.5     212.8     2891.2      1.00\n```\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# Compare population-level estimates to lme4\nsamples = mcmc.get_samples()\n\nprint(\"Numpyro posterior mean mu_alpha:\", jnp.mean(samples[\"mu_alpha\"]).item())\nprint(\"Numpyro posterior mean mu_beta: \", jnp.mean(samples[\"mu_beta\"]).item())\nprint()\nprint(\"lme4 fixed effects:\")\nprint(\"  Intercept:\", 2678.3)   # from R summary(reg1)\nprint(\"  Weeks:    \", -2.34)\n\n# Posterior predictive for a single patient\np0_alpha = samples[\"alpha\"][:, 0]   # patient 0 intercept samples\np0_beta  = samples[\"beta\"][:, 0]    # patient 0 slope samples\n\n# Predict FVC at week 20 -- posterior predictive (add observation noise)\nweek_pred = 20.\nmu_pred   = p0_alpha + p0_beta * week_pred\nfvc_pred  = dist.Normal(mu_pred, samples[\"sigma_obs\"]).sample(jax.random.PRNGKey(1))\nprint(f\"\\nPatient 0 FVC at week 20:\")\nprint(f\"  Mean: {jnp.mean(fvc_pred):.1f}\")\nprint(f\"  90% CI: [{jnp.quantile(fvc_pred, 0.05):.1f}, {jnp.quantile(fvc_pred, 0.95):.1f}]\")\n```\n:::\n\n\n## Comparing the two approaches\n\n| | lme4 | numpyro |\n|---|---|---|\n| Estimation | REML (restricted maximum likelihood) | MCMC (full posterior) |\n| Output | Point estimates + SE | Full posterior distributions |\n| Uncertainty | Approximate (Wald-type CI) | Exact posterior credible intervals |\n| Computation | Fast (seconds) | Slower (minutes for 1000 samples) |\n| Prediction | `predict()` gives point estimates | Posterior predictive — full distribution |\n\nThe main advantage of `numpyro` shows up in prediction. For a new patient,\n`lme4` gives a point prediction and an approximate interval. `numpyro` gives a\nposterior predictive distribution. Then we can look at any quantile or compute\nprobabilities such as whether FVC stays above a threshold.\n\nFor a simple random-effects model with a large data set, `lme4` is much faster\nand usually enough. `numpyro` becomes more useful when the model is more\ncomplicated, or when the full predictive distribution is what we need.\n\n---\n\n<!-- see-also-footer -->\n*Systematic treatment: [R](https://xiangao.github.io/causal_econometrics_guide/bayesian-causal.html) · [Julia](https://xiangao.github.io/causal_econometrics_julia/bayesian-causal.html).*\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}