{
  "hash": "2062eb29a5000518264dbb0605fe4b1d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Simulation on proximal causal inference with panel data\"\ndate: \"2025-08-01\"\n---\n\n\nThis chapter extends [proximal causal inference](proximal-intro.qmd) to a panel-data setting. The question is whether lagged treatment and lagged outcome can serve as negative control exposure (NCE) and negative control outcome (NCO), respectively, to account for unobserved confounders.\n\nConsider a two-period DAG:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](proximal-simulation_files/figure-pdf/dag1-1.pdf)\n:::\n:::\n\n\nSuppose that's the case for the causal structure, then I can reasonably combine U1 and U2 into a single unobserved confounder $U$:\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](proximal-simulation_files/figure-pdf/dag2-1.pdf)\n:::\n:::\n\n\nThat would fit into the double negative control framework.  The problem is that we have to assume there is no link from A1 to Y1, which is odd.  Can we assume in period 1 there is no effect, but in period 2, there is an effect?\n\n\n\n## A simulation with panel data\n\nI generate two period data based on the DAG above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(rootSolve)\nlibrary(tidyverse)\n\ngen_data <- function(seed, n){\n  set.seed(seed)\n  u <- rnorm(n, mean = 0, sd = 1)  # unobserved confounder\n  x1 <- rnorm(n, mean = 0, sd = 1)  # observed confounder\n  x2 <- rnorm(n, mean = 0, sd = 1)  # observed confounder\n  a1 <- rbinom(n, 1, plogis(2*u + 1.5*x1))  # treatment at time 1\n  a2 <- rbinom(n, 1, plogis(u + a1 +  x1))  # treatment at time 2\n  y1 <-  1.5*u + .5*x1  +  rnorm(n, mean = 0, sd = 1)  # outcome at time 1\n  y2 <-  y1 + 2.5*u + 2.5*x1 + 3*a2 + rnorm(n, mean = 0, sd = 1)  # outcome at time 2\n  data <- data.frame(u=u, x1=x1, x2=x2, a1=a1, a2=a2, y1=y1, y2=y2)\n  return(data)\n}\ndata <- gen_data(333, 100000)\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_sim <- data |>\n  select(a1, a2, y2,  x1, x2, y1) |>\n  rename(a = a2, y = y2,  x = x1, w = y1, z=a1)\n```\n:::\n\n\nThe simulation draws $n = 100{,}000$ two-period observations. There is an\nunobserved confounder $u \\sim N(0,1)$ and two observed covariates\n$x_1, x_2 \\sim N(0,1)$. Treatment at time 1 is\n$a_1 \\sim \\text{Bernoulli}(\\Lambda(2u + 1.5x_1))$ and at time 2 is\n$a_2 \\sim \\text{Bernoulli}(\\Lambda(u + a_1 + x_1))$. The outcomes are\n$y_1 = 1.5u + 0.5x_1 + \\varepsilon_1$ and\n$y_2 = y_1 + 2.5u + 2.5x_1 + 3a_2 + \\varepsilon_2$.\n\nSo the effect of interest is the 3 on $a_2$. The construction then relabels\n$a_1$ as the negative control exposure $z$ and $y_1$ as the negative control\noutcome $w$ — note that $y_1$ does not depend on $a_1$, which is exactly the\nassumption discussed at the end of this chapter.\n\nWe can use the simple 2sls:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm1 <- lm(w ~ a + x + z, data = data_sim)\ndata_sim$what <- lm1$fitted.values\nlm2 <- lm(y ~ a + x +  what, data = data_sim)\nsummary(lm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = y ~ a + x + what, data = data_sim)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-16.4284  -2.3083   0.0071   2.3020  20.7590 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -0.01293    0.02315  -0.558    0.577    \na            3.02113    0.03528  85.625   <2e-16 ***\nx            1.67203    0.01245 134.327   <2e-16 ***\nwhat         2.66578    0.01747 152.631   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.456 on 99996 degrees of freedom\nMultiple R-squared:  0.6822,\tAdjusted R-squared:  0.6822 \nF-statistic: 7.155e+04 on 3 and 99996 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe 2SLS coefficient on $a$ is 3.021 with a standard error of 0.035, against the\ntrue 3. The coefficient on the fitted proxy `what` is 2.666, which is the ratio\nof the confounder's loading on the outcome to its loading on the proxy, not an\neffect of interest.\n\nOr we can use more sophisticated methods.  Here I use the m-estimation code by Paul Zivich:  https://github.com/pzivich/publications-code/blob/master/ProximalCI/proximal_sims_r.R.  This code is to construct estimating equations, then use root finding to find the parameter estimates.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npcl_m2 <- function(theta, mydata, out = \"ef\"){\n  # read in variables\n  a <- mydata$a\n  x <- mydata$x\n  w <- mydata$w\n  z <- mydata$z\n  y <- mydata$y\n  # model for what\n  what <- theta[1] + theta[2] * a + theta[3] * x + theta[4] * z\n\n  # matrix of covars in model for what\n  wmat <- as.matrix(cbind(rep(1, nrow(mydata)), a, x, z), ncol = 4,\n                    nrow = nrow(mydata))\n\n  # estimating function for what\n  ef1 <- (t(wmat)  %*% (w - what))            # gives px1 vector (summed over units)\n  ef1_b <- wmat * (w - what)                  # gives nxp matrix (rows are units)\n\n  # model for yhat\n  yhat <- theta[5] + theta[6]*a + theta[7]*x + theta[8] * what\n\n  # matrix of covars in model for yhat\n  ymat <- as.matrix(cbind(rep(1, nrow(mydata)), a, x, what), ncol = 4,\n                    nrow = nrow(mydata))\n\n  #estimating function for yhat\n  ef2 <- t(ymat) %*% (y - yhat)               # px1 vector, summed over units\n  ef2_b <- (ymat) * (y - yhat)                # nxp matrix (rows are units)\n  f <- c(ef1, ef2)                            # p-dimensional vector\n  if(out == \"full\") return(cbind(ef1_b, ef2_b)) else return(f) # full used in var calculation only\n}\n\n# call m-estimator for PCL\nmpcl_mest <- function(dat){\n  theta_start <- rep(.05, 8)\n  results <- mestimator(pcl_m2, init = theta_start, dat, mydata = dat)\n  return(results)\n}\n\n##' M-estimation engine\nmestimator <- function(ef, init, dat, ...){\n  # get estimated coefficients\n  fit <- multiroot(ef, start = init, out = \"ef\",\n                   rtol = 1e-9, atol = 1e-12, ctol = 1e-12, ...  )\n  betahat <- fit$root\n  n <- nrow(dat)\n\n  # bread\n  # derivative of estimating function at betahat\n  pd <- gradient(ef, betahat, out = \"ef\", ...)\n  pd <- as.matrix(pd)\n  bread <- -pd/n\n  se_mod <- sqrt(abs(diag(-solve(pd))))\n\n  # meat1\n  efhat <- ef(betahat, out = \"full\", ...)\n  meat <- list()\n  meat1 <- (t(efhat) %*% efhat)/n\n\n  # sandwich\n  sandwich1 <- (solve(bread) %*% meat1 %*% t(solve(bread)))/n\n  se_sandwich1 <- sqrt(diag(sandwich1))\n\n  results <- data.frame(betahat, se_sandwich1, se_mod)\n  return(results)\n}\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrmpcl <- unname(mpcl_mest(data_sim)[6, c(1:2)])\nrmpcl\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    \n6 3.021126 0.0198433\n```\n\n\n:::\n\n```{.r .cell-code}\n#mpcl_mest(data_sim)\n```\n:::\n\n\nThe m-estimator gives 3.0211 with a standard error of 0.0198.\n\nBoth the 2sls and the m-estimation give us the same estimate of the causal effect of treatment on outcome, which is 3 — identical to four decimal places, 3.021126 either way. The standard errors differ, 0.0198 against 0.0353, and the m-estimator's is the one to use: it accounts for the estimation of the first stage, which the plug-in 2SLS standard error does not.  The m estimator can be more general.  2sls is good for the linear case.\n\nHowever, the main issue is the assumption that there is no link from A1 to Y1.\n\nTo think about it from a different angle: this is similar to DiD setting.  Basically we need A1 to be 0.  There is no effect in period 1.  If we only have A1 as 0, then it makes sense to have no link from A1 to Y1 (no anticipation assumption).\n\n**This is a restrictive identifying assumption, not a technical footnote.** Using $A_{t-1}$ as the negative control exposure and $Y_{t-1}$ as the negative control outcome only identifies the effect if two separate exclusions hold: $A_1$ must have no direct effect on $Y_1$, so that $Y_1$ is a clean proxy for $U$ rather than a partly post-treatment quantity; and $A_1$ must have no direct effect on $Y_2$ except through $U$, which is the exclusion restriction that makes $A_1$ admissible as a negative control exposure in the first place. If either link is actually present — for example, if treatment has an immediate effect in the same period it starts, which is the empirically common case — this proximal construction is misspecified and the estimate above should not be trusted. Before applying this approach, researchers should have a substantive reason to believe treatment effects only appear with a lag.\n\n---\n\n<!-- see-also-footer -->\n*Systematic treatment: [R](https://xiangao.github.io/causal_econometrics_guide/graphs-identification-estimation.html) · [Julia](https://xiangao.github.io/causal_econometrics_julia/graphs-identification-estimation.html).*\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}