{
  "hash": "7beb73c224b4c93da24eb60232699ad4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Modeling variation, not just the mean, in Likert-scale data\"\ndate: \"2026-07-16\"\n---\n\n\n\n## When you model the variance of a Likert item\n\nMost of the time, when we regress a Likert-scale outcome (a 1--7 satisfaction\nitem, a 1--5 agreement item, a peer-evaluation rating) on some covariates, we\nonly model the mean. But plenty of real questions are about the *spread*, not\nthe average: do evaluators agree more about some employees than others? Does\none group of raters show more disagreement than another? Is a training\nprogram tightening or loosening the distribution of responses, not just\nshifting its center?\n\nThe natural instinct is to compute an SD (or variance) for each unit --- each\nsubject's ratings across raters, each respondent's answers across items --- and\nregress *that* on your covariates, the same way you'd regress a mean. This\nchapter is about why that instinct runs into a specific, avoidable problem on\na bounded scale, and what to do about it instead.\n\n## The problem: on a bounded scale, variance is mechanically tied to the mean\n\nHere is the part that is easy to miss: on a scale with a hard floor and\nceiling, the *maximum possible* variance a set of responses can depend\non where their mean sits. This isn't a tendency in typical data -- it's a\nmathematical fact, true for any distribution on a bounded interval.\n\nFor any random variable $X$ confined to $[a,b]$, both $(X-a)$ and $(b-X)$ are\nnon-negative for every draw, so their product is too:\n\n$$(X-a)(b-X) \\geq 0 \\quad \\text{for every } X \\in [a,b]$$\n\nTaking expectations preserves the inequality, and expanding the left side\ngives $E[X^2] \\leq (a+b)\\mu - ab$ where $\\mu = E[X]$. Substituting into\n$\\text{Var}(X) = E[X^2] - \\mu^2$:\n\n$$\\text{Var}(X) \\leq (a+b)\\mu - ab - \\mu^2 = (\\mu - a)(b - \\mu)$$\n\nThis is the **Bhatia--Davis inequality** (Bhatia and Davis 2000). Equality is\nachieved, not just approached: put all the mass at the two endpoints, with\n$P(X=a) = (b-\\mu)/(b-a)$ and $P(X=b) = (\\mu-a)/(b-a)$, and you get variance\nexactly $(\\mu-a)(b-\\mu)$ -- the most polarized a set of responses can possibly\nbe, given that mean.\n\nOn a 1--7 Likert item, that's\n\n$$\\text{SD}_{\\max}(\\mu) = \\sqrt{(\\mu-1)(7-\\mu)}$$\n\na downward parabola, widest at the scale's midpoint ($\\mu=4$, where\n$\\text{SD}_{\\max}=3$) and pinched to exactly zero at both ends. A respondent\nwhose raters all pick 7 has, by definition, zero disagreement -- there's\nnowhere else for a rating to go.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu_grid <- seq(1, 7, length.out = 200)\nsd_max  <- sqrt(pmax((mu_grid - 1) * (7 - mu_grid), 0))\n\nggplot(data.frame(mu = mu_grid, sd_max = sd_max), aes(mu, sd_max)) +\n  geom_line(linewidth = 1, color = \"#2d5fa3\") +\n  labs(x = \"mean rating (μ)\", y = expression(SD[max](mu)),\n       title = \"Maximum possible SD, as a function of the mean\") +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![The mechanical ceiling on SD, given the mean, for a 1--7 scale.](likert-scale-variance_files/figure-html/bound-curve-1.png){width=672}\n:::\n:::\n\n\nThe consequence: any two groups whose *means* differ will have different\n*ceilings* on their SD, whether or not anything about their true dispersion\ndiffers. If most of your respondents already sit near one end of the scale\n(a very common situation -- satisfaction items, performance ratings, and\nhealth scales are all typically skewed toward one end), this isn't a\ncorner case. It's the region where the curve above is steepest, and where\nraw SD comparisons are most likely to mislead.\n\n::: {.callout-note}\n## A finite-sample refinement\n\nThe curve above is the *population* bound. For a genuinely finite sample of\n$n$ real numbers with mean $\\mu$, the true maximum is strictly tighter still:\nEllis (2025) gives it exactly as $\\text{Var}_{\\max}(n,\\mu) = (\\mu-1)(7-\\mu) -\n\\tfrac{36}{n}a(1-a)$, where $a$ is the fractional part of $n(\\mu-1)/6$, which\nsimplifies to $(\\mu-1)(7-\\mu) - 9/n \\leq \\text{Var}_{\\max}(n,\\mu) \\leq\n(\\mu-1)(7-\\mu)$. At $n=5$ raters, that's up to 1.8 points$^2$ of extra\nslack -- worth knowing if your groups are rated by only a handful of people\neach, since the population curve above then understates how tight the true\nceiling is.\n:::\n\nA natural first fix is to divide the SD (or variance) by the mean, the way\nyou would for a coefficient of variation. This doesn't work here, because\nthat correction is designed for a *different* mechanism -- variance scaling\nproportionally with the mean, as in count data -- not a ceiling that pinches\ntoward zero at *both* ends. $\\text{SD}_{\\max}(\\mu)/\\mu$ is still a curve\n(zero at $\\mu=1$, a peak of $0.75$ at $\\mu=4$, back to zero at $\\mu=7$), just\na differently-shaped one. Dividing by the mean doesn't remove the\nmean-dependence; it just relabels it.\n\n## Three ways to actually model it\n\n### Gaussian location-scale model (MELSM)\n\nThe simplest fix that people reach for is a mixed-effects location-scale\nmodel: model the mean as usual, and *also* model the residual SD as a\nfunction of covariates.\n\n```r\nlibrary(brms)\n\nfit_gaussian <- brm(\n  bf(rating ~ group + (1 | subject),\n     sigma ~ group),                 # model the SD, not just the mean\n  data = df, family = gaussian()\n)\n```\n\n`brms` puts a log link on `sigma` by default, so the `group` coefficient on\nthe `sigma` part is a difference in *log*-SD; exponentiate it to get an\nSD ratio between groups.\n\n**The catch:** a Gaussian model has no boundary in it. It doesn't know the\nscale stops at 1 and 7, so it has no way to distinguish \"this group's raters\ngenuinely agree more\" from \"this group's mean happens to sit closer to the\nceiling.\" Both produce the identical signature in the fitted `sigma`.\n\n### What belongs in the dispersion submodel?\n\nA natural worry at this point: why does `sigma ~ group` (or, further below,\n`disc ~ group` and $\\varphi \\sim \\text{group}$) only include `group`, when\nthe *mean* model might include other covariates too -- shouldn't the\ndispersion submodel be \"whatever is in the model for the mean\"? Not\nnecessarily. There is no requirement that the two submodels share a\nright-hand side, and in general they *shouldn't* automatically, because they\nanswer different questions. The mean model asks what predicts the average\nrating; the dispersion model asks what predicts how spread out the ratings\nare. In this chapter's simulation `group` is the only variable in the\ndata-generating process at all -- there is nothing else *to* include, on\neither side.\n\nIn a real dataset, though, this is a substantive modeling choice, not a\nmechanical one, and getting it wrong has a real cost -- symmetric to the\nfamiliar one for the mean. If some covariate $Z$ (rater experience, item\nwording, subject-level traits) genuinely affects dispersion and happens to be\ncorrelated with `group`, but $Z$ is left out of the dispersion submodel, its\neffect is absorbed into the `group` coefficient on `sigma` (or `disc`, or\n$\\varphi$) -- an omitted-variable problem for the *variance*, exactly\nanalogous to the ordinary one for the mean. The fix is the same one you'd\nalready apply on the mean side: include, in the dispersion submodel,\nwhichever covariates you have a substantive reason to think shift dispersion,\nand give that specification the same scrutiny you'd give the mean model --\nneither reflexively copying its formula nor stripping the dispersion\nsubmodel down to only the one comparison you happen to be interested in.\n\n### Beta regression: model precision instead of variance directly\n\nIf your outcome can be rescaled to $(0,1)$ (e.g. $(y-1)/6$ for a 1--7 item),\nBeta regression gives you a mean/precision parameterization built exactly for\nbounded outcomes (Ferrari and Cribari-Neto 2004; R implementation in\nCribari-Neto and Zeileis 2010's `betareg` package). With mean $\\mu$ and\nprecision $\\varphi$:\n\n$$\\text{Var}(Y) = \\frac{(\\mu-1)(7-\\mu)}{1+\\varphi} \\qquad \\Longrightarrow\n\\qquad \\varphi = \\frac{(\\mu-1)(7-\\mu)}{\\text{Var}(Y)} - 1$$\n\nSet $\\varphi = 0$ and this *is* the Bhatia--Davis bound -- the maximum\npossible variance given $\\mu$. So $\\varphi$ is dispersion measured *after*\nthe boundary effect is divided out, and $\\varphi \\sim \\text{group}$ is a\ncomparison that doesn't inherit the ceiling confound the way raw SD does.\n\nThe catch here is smaller but real: it's a continuous distributional\nassumption grafted onto what is usually genuinely discrete, ordinal data\n(a 1--7 Likert response isn't a continuous proportion), and dividing by a\nsmall-sample variance estimate can behave badly when a handful of raters\nhappen to agree by chance.\n\n$\\varphi$ itself is awkward to report -- it lives on $(0,\\infty)$ with no\nnatural reference point. Its bounded, more interpretable twin is\n\n$$R := \\frac{\\text{Var}(Y)}{\\text{Var}_{\\max}(\\mu)} = \\frac{1}{1+\\varphi}$$\n\nBy Bhatia--Davis, $\\text{Var}(Y) \\leq \\text{Var}_{\\max}(\\mu)$ for *any*\ndistribution on $[1,7]$ -- not just Beta ones -- so $R \\in [0,1]$ always,\nwith no distributional assumption required. $R=1$ means a subject's raters\nare as polarized as the ceiling allows, given their mean; $R=0$ means\nperfect consensus. It's just $(\\mu, \\text{Var}(Y))$ re-expressed in\nmean-neutral units. We'll come back to $R$ in the worked example below,\nbecause it turns out to illustrate the small-sample catch *very* concretely.\n\n### Ordinal cumulative-probit MELSM: put the boundary inside the model\n\nThe cleanest fix treats the 1--7 response as what it is: a discretized slice\nof a latent continuous trait, cut by six ordered thresholds.\n\n**The latent-variable model.** Posit an unobserved continuous $Y_i^*$ behind\neach rating,\n\n$$Y_i^* = \\eta_i + \\sigma_i \\epsilon_i, \\qquad \\epsilon_i \\sim N(0,1),$$\n\nwhere $\\eta_i$ is the usual linear predictor for *location* (`group` plus a\nsubject random intercept, say) and $\\sigma_i$ is the latent residual SD,\nwhich we will also let depend on covariates. The observed 1--7 rating is a\ncoarsened version of $Y_i^*$, cut at six fixed thresholds $\\theta_1 < \\cdots\n< \\theta_6$ (with $\\theta_0=-\\infty$, $\\theta_7=\\infty$):\n\n$$Y_i = k \\iff \\theta_{k-1} < Y_i^* \\leq \\theta_k.$$\n\nThe probability of falling at or below category $k$ is then\n\n$$P(Y_i \\leq k) = P(Y_i^* \\leq \\theta_k) = P\\!\\left(\\epsilon_i \\leq\n\\frac{\\theta_k - \\eta_i}{\\sigma_i}\\right) = \\Phi\\!\\left(\\frac{\\theta_k -\n\\eta_i}{\\sigma_i}\\right),$$\n\nusing $\\Phi$, the standard normal CDF, for the probit link. Writing\n$\\text{disc}_i := 1/\\sigma_i$ turns this into `brms`'s parameterization\nexactly:\n\n$$P(Y_i \\leq k) = \\Phi\\bigl(\\text{disc}_i\\,(\\theta_k - \\eta_i)\\bigr).$$\n\nSo \"discrimination\" is *literally* the reciprocal of the latent residual SD\n-- not an analogy, an algebraic identity -- reached by rescaling the argument\nof $\\Phi$ rather than dividing by $\\sigma_i$ directly. Letting $\\text{disc}$\ndepend on covariates is the ordinal-probit analogue of `sigma ~ group` in the\nGaussian model above, just written in reciprocal form: a positivity-friendly\nway to let dispersion vary ($\\text{disc} > 0$ everywhere, with no constraint\nneeded on $\\sigma_i$ itself). `brms` puts a log link on `disc`, exactly as it\ndoes on Gaussian `sigma`, so a `disc ~ 0 + group` submodel really means\n$\\log(\\text{disc}_i) = \\gamma_{\\text{group}[i]}$: a group difference in\n*log*-discrimination, parallel to the Gaussian model's log-SD coefficients\n(Bürkner and Vuorre 2019).\n\n```r\nfit_ordinal <- brm(\n  bf(rating ~ group + (1 | subject),\n     disc ~ 0 + group),           # log(disc) = 0 + group; disc = 1 / latent SD\n  data = df, family = cumulative(\"probit\"), init = 0,\n  prior = c(\n    prior(constant(0), class = \"b\", coef = \"groupA\", dpar = \"disc\"),\n    prior(normal(0, 1), class = \"b\", coef = \"groupB\", dpar = \"disc\")\n  )\n)\n```\n\nThe `constant(0)` prior pins the reference group's **log**-discrimination --\nthe linear predictor $\\gamma_A$, not $\\text{disc}$ itself -- at zero, so\n$\\text{disc}_A = \\exp(0) = 1$ and the reference group's latent SD is\n$1/\\text{disc}_A = 1$. (Fixing $\\gamma_A=0$ is what makes `disc = 1` and\n`SD = 1` coincide for the reference group; it is not a claim that\ndiscrimination itself is zero, which would instead mean an infinite latent\nSD.) Only $\\gamma_B$, the comparison group's log-discrimination, is estimated\nfreely: $\\text{disc}_B = \\exp(\\gamma_B)$, so $\\gamma_B=0$ means identical\ndispersion, $\\gamma_B>0$ means Group B is *more* discriminating (a\n*smaller* latent SD), and $\\gamma_B<0$ the reverse. Because the boundary is\nnow an explicit part of the model -- six estimated cutpoints on an\n*unbounded* latent scale -- a group whose mean sits near 7 doesn't\nmechanically show a tighter latent SD the way its raw SD is forced to.\n\n## Worked example: two groups, identical true dispersion, different means\n\nTo see the confound in action, simulate two groups of 100 subjects each,\n6 raters per subject. Both groups' raters draw from a **latent** continuous\nopinion with the *same* true SD ($\\sigma = 1$) -- there is no real\ndisagreement difference to find. Group A's latent mean sits high (near the\nceiling once discretized); Group B's sits in the middle of the range.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\n\nn_per_group <- 100\nn_raters    <- 6\nsigma_true  <- 1.0   # SAME latent SD in both groups -- no real difference\nmu_A <- 2.4          # group A's latent mean sits near the ceiling\nmu_B <- 0.6          # group B's sits mid-range\n\nsubjects <- data.frame(\n  subject = 1:(2 * n_per_group),\n  group   = rep(c(\"A\", \"B\"), each = n_per_group),\n  mu      = rep(c(mu_A, mu_B), each = n_per_group)\n)\n\ndf <- subjects[rep(seq_len(nrow(subjects)), each = n_raters), ]\ndf$latent <- rnorm(nrow(df), mean = df$mu, sd = sigma_true)\n\n# six fixed cutpoints -> seven observed categories, 1 through 7\ncuts <- c(-2, -1.2, -0.5, 0.2, 1.0, 1.8)\ndf$rating     <- as.integer(cut(df$latent, breaks = c(-Inf, cuts, Inf), labels = 1:7))\ndf$rating_ord <- factor(df$rating, ordered = TRUE, levels = 1:7)\n```\n:::\n\n\nBefore looking at the raw summary, it is worth seeing exactly where the\ngroup difference enters the code, because it is easy to miss: `rnorm(...,\nsd = sigma_true)` uses one `sigma_true` for every row, in both groups --\n`group` never touches the standard deviation, only the mean, via `df$mu`.\nThe two groups differ *only* in where their latent mean sits relative to\nthe six fixed cutpoints, which are the same `cuts` object for both groups.\nThat is enough, on its own, to produce very different observed spreads:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nedges <- c(-Inf, cuts, Inf)\ntibble(\n  category = 1:7,\n  prob_A = round(diff(pnorm(edges, mean = mu_A, sd = sigma_true)), 3),\n  prob_B = round(diff(pnorm(edges, mean = mu_B, sd = sigma_true)), 3)\n) |>\n  knitr::kable(caption = \"Category probabilities implied by each group's latent mean, with the same cutpoints and the same sigma.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Category probabilities implied by each group's latent mean, with the same cutpoints and the same sigma.\n\n| category| prob_A| prob_B|\n|--------:|------:|------:|\n|        1|  0.000|  0.005|\n|        2|  0.000|  0.031|\n|        3|  0.002|  0.100|\n|        4|  0.012|  0.209|\n|        5|  0.067|  0.311|\n|        6|  0.193|  0.230|\n|        7|  0.726|  0.115|\n\n\n:::\n:::\n\n\nGroup A's latent mean (2.4) sits 0.6 SDs above the highest cutpoint (1.8),\nso `pnorm(0.6)` $\\approx 0.73$: nearly three-quarters of Group A's\nindividual ratings are collapsed into the single top category, and fewer\nthan 2% fall below category 5. Group B's latent mean (0.6) sits close to\nthe middle of the cutpoint range, so its ratings spread across all seven\ncategories, with no single category exceeding about 30%.\n\nThat imbalance -- not a difference in $\\sigma$ -- is what shrinks Group A's\nraw SD. When roughly three-quarters of a subject's six ratings are forced\ninto the same top bin by `cut()`, the *discrete* variance across those six\nratings is mechanically small, even though the *continuous* latent draws\nbehind them are exactly as dispersed as Group B's ($\\sigma=1$ for both,\nby construction). It is the same Bhatia--Davis mechanism from the\nintroduction, now visible subject-by-subject through `cut()`'s fixed\nboundaries rather than through the population-level $\\text{SD}_{\\max}(\\mu)$\ncurve directly.\n\nThe raw, per-subject summary already shows exactly the pattern that tempts\npeople into thinking there's a real disagreement difference:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsubj_summary <- df |>\n  group_by(subject, group) |>\n  summarise(mean_rating = mean(rating), sd_rating = sd(rating), .groups = \"drop\")\n\nknitr::kable(\n  subj_summary |> group_by(group) |>\n    summarise(mean_of_means = round(mean(mean_rating), 2),\n              mean_of_sds   = round(mean(sd_rating), 2)),\n  caption = \"Raw per-subject summary by group -- true latent SD is IDENTICAL in both.\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Raw per-subject summary by group -- true latent SD is IDENTICAL in both.\n\n|group | mean_of_means| mean_of_sds|\n|:-----|-------------:|-----------:|\n|A     |          6.64|        0.58|\n|B     |          4.89|        1.22|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(subj_summary, aes(mean_rating, sd_rating, color = group)) +\n  geom_jitter(width = 0.05, height = 0, alpha = 0.5) +\n  geom_line(data = data.frame(mean_rating = mu_grid, sd_rating = sd_max),\n            aes(mean_rating, sd_rating), color = \"grey40\", inherit.aes = FALSE) +\n  labs(x = \"subject mean rating\", y = \"subject SD\",\n       title = \"Group A's raw SD looks smaller -- purely because its mean sits\\nnear the grey ceiling curve, not because raters agree more\") +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Subject-level mean vs. SD, with the theoretical ceiling overlaid.](likert-scale-variance_files/figure-html/scatter-1.png){width=672}\n:::\n:::\n\n\nNow fit both a Gaussian MELSM and the ordinal cumulative-probit MELSM to the\nsame data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_gaussian <- brm(\n  bf(rating ~ group + (1 | subject), sigma ~ group),\n  data = df, family = gaussian(),\n  chains = 2, iter = 2000, warmup = 1000, cores = 2, seed = 1,\n  refresh = 0, silent = 2\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_ordinal <- brm(\n  bf(rating_ord ~ group + (1 | subject), disc ~ 0 + group),\n  data = df, family = cumulative(\"probit\"), init = 0,\n  prior = c(\n    prior(constant(0), class = \"b\", coef = \"groupA\", dpar = \"disc\"),\n    prior(normal(0, 1), class = \"b\", coef = \"groupB\", dpar = \"disc\")\n  ),\n  chains = 2, iter = 2000, warmup = 1000, cores = 2, seed = 1,\n  refresh = 0, silent = 2\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::kable(round(fixef(fit_gaussian), 2), caption = \"Gaussian MELSM fixed effects (sigma part is on the log-SD scale)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Gaussian MELSM fixed effects (sigma part is on the log-SD scale)\n\n|                | Estimate| Est.Error|  Q2.5| Q97.5|\n|:---------------|--------:|---------:|-----:|-----:|\n|Intercept       |     6.64|      0.03|  6.58|  6.69|\n|sigma_Intercept |    -0.41|      0.03| -0.46| -0.35|\n|groupB          |    -1.75|      0.06| -1.86| -1.63|\n|sigma_groupB    |     0.68|      0.04|  0.60|  0.76|\n\n\n:::\n\n```{.r .cell-code}\nknitr::kable(round(fixef(fit_ordinal), 2), caption = \"Ordinal MELSM fixed effects (disc part is on the log scale: 0 = same latent SD as the reference group)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Ordinal MELSM fixed effects (disc part is on the log scale: 0 = same latent SD as the reference group)\n\n|             | Estimate| Est.Error|  Q2.5| Q97.5|\n|:------------|--------:|---------:|-----:|-----:|\n|Intercept[1] |    -4.39|      0.32| -5.06| -3.81|\n|Intercept[2] |    -3.65|      0.23| -4.12| -3.22|\n|Intercept[3] |    -2.98|      0.17| -3.34| -2.66|\n|Intercept[4] |    -2.27|      0.12| -2.52| -2.04|\n|Intercept[5] |    -1.44|      0.07| -1.59| -1.30|\n|Intercept[6] |    -0.63|      0.06| -0.74| -0.52|\n|groupB       |    -1.89|      0.10| -2.11| -1.69|\n|disc_groupA  |     0.00|      0.00|  0.00|  0.00|\n|disc_groupB  |    -0.01|      0.08| -0.17|  0.15|\n\n\n:::\n:::\n\n\nOn the raw scale, Group A averages 6.64 with an SD of 0.58; Group B averages\n4.89 with an SD of 1.22 -- the pooled correlation between subject-level mean\nand SD is $-0.74$. That pattern looks like a real, sizable disagreement gap,\nand the Gaussian MELSM agrees with it: the fitted `sigma_groupB` coefficient\nof 0.68 (on the log-SD scale) implies Group B's SD is **1.97 times** Group\nA's (95% CI: 1.82--2.14) -- a difference whose credible interval is nowhere\nnear zero.\n\nBut there is no true difference. Both groups' raters were drawn from a\nlatent distribution with the *same* SD ($\\sigma=1$) by construction --\nthe only thing that differs between the groups is where their mean sits\nrelative to the ceiling. The ordinal cumulative-probit model's\n`disc_groupB` estimate -- $\\gamma_B = -0.015$ on the log scale (95% CI:\n$-0.171$ to $0.146$) -- is indistinguishable from zero, i.e.\n$\\text{disc}_B = e^{-0.015} \\approx 0.985$, a latent SD of $\\approx 1.015$\nagainst the reference group's $1$: correctly recovering the fact that the\ntwo groups' underlying dispersion is identical. The Gaussian model's \"Group B\ndisagrees twice as much\" is not a finding about the raters; it's the\nmechanical ceiling effect from the previous section, expressed as a\nregression coefficient.\n\n### What about R, on this same data?\n\n$R$ was introduced above as mean-independent by construction -- so it should\nland on the same answer as the ordinal model: no real group difference.\nCompute it per subject, using the exact finite-sample bound from the earlier\ncallout ($n=6$ raters):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar_max_finite <- function(n, mu) {\n  c <- (mu - 1) / 6\n  a <- (n * c) %% 1\n  36 * (c * (1 - c) - (1 / n) * a * (1 - a))\n}\n\nsubj_R <- df |>\n  group_by(subject, group) |>\n  summarise(mean_rating = mean(rating),\n            var_pop = mean((rating - mean(rating))^2),   # population (1/n) convention\n            .groups = \"drop\") |>\n  mutate(var_max = var_max_finite(n_raters, mean_rating),\n         R = ifelse(var_max > 1e-8, var_pop / var_max, NA_real_))\n\nknitr::kable(\n  subj_R |> group_by(group) |>\n    summarise(n_undefined = sum(is.na(R)), mean_R = round(mean(R, na.rm = TRUE), 3)),\n  caption = \"Per-subject R, using each subject's own 6 ratings for both mean and variance.\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Per-subject R, using each subject's own 6 ratings for both mean and variance.\n\n|group | n_undefined| mean_R|\n|:-----|-----------:|------:|\n|A     |          14|  0.626|\n|B     |           0|  0.200|\n\n\n:::\n:::\n\n\nThis is worse than the raw SD comparison, not better: Group A's per-subject\n$R$ averages 0.63, Group B's 0.20 -- an even larger apparent gap, and in the\nopposite direction from what the ceiling artifact would predict. Fourteen\nGroup A subjects even have an *undefined* $R$ (all six raters happened to\npick 7, so both the observed variance and the mechanical ceiling are\nsimultaneously zero). Has $R$ failed?\n\nNo -- the theoretical guarantee ($R\\in[0,1]$ at every $\\mu$, no forced\nrelationship to the mean) is about the *population* quantity. Plugging in a\nmean estimated from only 6 raters breaks it, because the finite-sample bound\nin the denominator is itself estimated from that same noisy mean, and it is\nfar more sensitive near the ceiling than in the middle of the scale:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::kable(\n  subj_R |> group_by(group) |>\n    summarise(mean_var_pop = round(mean(var_pop), 3),\n              mean_var_max = round(mean(var_max, na.rm = TRUE), 3)),\n  caption = \"The denominator (mean_var_max) is nearly 7x smaller for Group A -- not because Group A's true ceiling is that much tighter, but because a 6-rater sample mean near 7 makes the *estimated* ceiling collapse.\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: The denominator (mean_var_max) is nearly 7x smaller for Group A -- not because Group A's true ceiling is that much tighter, but because a 6-rater sample mean near 7 makes the *estimated* ceiling collapse.\n\n|group | mean_var_pop| mean_var_max|\n|:-----|------------:|------------:|\n|A     |        0.374|        0.984|\n|B     |        1.366|        6.903|\n\n\n:::\n:::\n\n\nA Group A subject's 6 raters average close to 7 purely because that's where\ntheir true mean sits -- but exactly *how* close is noisy, and the\nfinite-sample bound shrinks fast as the sample mean approaches the boundary.\nA modest, unremarkable observed variance divided by an unluckily tiny\ndenominator produces a large $R$, for no reason connected to real\ndisagreement. Swapping in the simpler continuous bound (no finite-sample\ncorrection) shrinks the gap a great deal -- 0.181 vs. 0.173 -- but each\nvalue is still an average of 100 individually noisy single-subject\nestimates. Only pooling each group's full 600 ratings into one mean and one\nvariance before computing $R$ removes the small-sample noise entirely:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npooled <- df |> group_by(group) |>\n  summarise(mean_rating = mean(rating), var_pop = mean((rating - mean(rating))^2)) |>\n  mutate(var_max_cont = (mean_rating - 1) * (7 - mean_rating),\n         R_pooled = round(var_pop / var_max_cont, 3))\n\nknitr::kable(pooled |> select(group, mean_rating, R_pooled),\n             caption = \"R computed once per group, from all 600 ratings pooled.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: R computed once per group, from all 600 ratings pooled.\n\n|group | mean_rating| R_pooled|\n|:-----|-----------:|--------:|\n|A     |    6.638333|    0.219|\n|B     |    4.893333|    0.211|\n\n\n:::\n:::\n\n\nPooled, $R$ is 0.22 for Group A and 0.21 for Group B -- essentially\nidentical, agreeing with the ordinal model's null finding. The lesson isn't\n\"don't use $R$\" -- it's that $R$, like $\\varphi$, is only as trustworthy as\nthe sample size behind the mean and variance plugged into it. A hand-computed\nper-subject $R$ with 6 raters can manufacture a *larger* spurious gap than\nraw SD, in the opposite direction. The ordinal model never has this problem\nin the first place, because it never computes a per-subject summary\nstatistic at all -- `disc_groupB` is estimated directly from the full,\npooled 600-observation likelihood per group, with the same effect as the\n\"pooled\" calculation above but done coherently, and with a proper posterior\ninterval instead of an average of point estimates.\n\n## Takeaways\n\n::: {.callout-note}\n## Summary\n\n- On any bounded scale, the *maximum possible* variance is a function of the\n  mean -- the Bhatia--Davis inequality, $\\text{Var}(X) \\leq (\\mu-a)(b-\\mu)$ --\n  not a tendency to check for, a fact to design around.\n- Dividing SD (or variance) by the mean does not remove this confound; the\n  mechanism isn't proportional scaling, it's a ceiling that pinches at both\n  ends.\n- A Gaussian location-scale model can estimate `sigma ~ x`, but inherits the\n  confound, because it has no boundary in it.\n- Beta regression's precision parameter $\\varphi$ (and its bounded twin $R$)\n  remove the confound algebraically, at the cost of a continuous\n  approximation to discrete data -- and $R$ is only as trustworthy as the\n  sample size behind the numbers plugged into it. With few raters per\n  subject, a hand-computed per-subject $R$ can manufacture a *larger*\n  spurious group gap than raw SD, in the opposite direction.\n- An ordinal cumulative-link mixed model puts the boundary where it belongs\n  -- as estimated thresholds on a latent scale -- and is the cleanest way to\n  ask \"is this dispersion difference real?\" on Likert data, because it never\n  needs a per-unit summary statistic at all.\n:::\n\n## References\n\n- Bhatia, R., and Davis, C. (2000). \"A Better Bound on the Variance.\"\n  *American Mathematical Monthly* 107(4): 353--357.\n\n- Bürkner, P.-C., and Vuorre, M. (2019). \"Ordinal Regression Models in\n  Psychology: A Tutorial.\" *Advances in Methods and Practices in\n  Psychological Science* 2(1): 77--101.\n\n- Cribari-Neto, F., and Zeileis, A. (2010). \"Beta Regression in R.\" *Journal\n  of Statistical Software* 34(2): 1--24.\n\n- Ellis, J. L. (2025). \"The maximum variance of a finite dataset, given its\n  mean, minimum, and maximum.\"\n  [arXiv:2508.17525](https://arxiv.org/abs/2508.17525).\n\n- Ferrari, S. L. P., and Cribari-Neto, F. (2004). \"Beta Regression for\n  Modelling Rates and Proportions.\" *Journal of Applied Statistics* 31(7):\n  799--815.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}