{
  "hash": "0b653f2fff863367272197a15c31cfc3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Equivalence testing and two one-sided tests (TOST)\"\ndate: \"2026-07-24\"\n---\n\n## Why non-significance is not evidence of no effect\n\nSuppose we use the usual null hypothesis significance test:\n\n$$H_0: \\theta = 0 \\quad \\text{vs.} \\quad H_1: \\theta \\neq 0$$\n\nFailing to reject $H_0$ ($p > 0.05$) does not show that $\\theta = 0$. We can get a large $p$-value because the true effect is small, but we can also get one because the sample is small or the outcome is noisy.\n\nThe usual test cannot tell these cases apart. If we want evidence that an effect is small enough to ignore, we need an equivalence test.\n\n## Two one-sided tests\n\nWe first choose a smallest effect size of interest. I write the resulting equivalence interval as $[-\\Delta, +\\Delta]$. An effect inside this interval is small enough to be negligible for the application.\n\nThe two one-sided tests (TOST) procedure (Schuirmann, 1987; Lakens, 2017) uses two null hypotheses:\n\n$$\nH_{01}: \\theta \\le -\\Delta \\quad \\text{and} \\quad H_{02}: \\theta \\ge +\\Delta\n$$\n\nIf we reject both null hypotheses at level $\\alpha$, we conclude that $-\\Delta < \\theta < +\\Delta$ with $(1 - 2\\alpha)$ confidence.\n\nAn equivalent way to do the test is to check whether the $(1 - 2\\alpha)$ confidence interval falls entirely inside $[-\\Delta, +\\Delta]$. When $\\alpha = 0.05$, we use the 90% confidence interval.\n\n## Using `TOSTER` in R\n\nLet's use the 1974 Motor Trend data in `mtcars`. We compare quarter-mile acceleration time (`qsec`) between automatic ($n = 19$) and manual ($n = 13$) transmissions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(TOSTER)\ndata(mtcars)\nmtcars$am <- factor(mtcars$am, labels = c(\"automatic\", \"manual\"))\n\n# Standard two-sample t-test\nt.test(qsec ~ am, data = mtcars)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  qsec by am\nt = 1.2878, df = 25.534, p-value = 0.2093\nalternative hypothesis: true difference in means between group automatic and group manual is not equal to 0\n95 percent confidence interval:\n -0.4918522  2.1381679\nsample estimates:\nmean in group automatic    mean in group manual \n               18.18316                17.36000 \n```\n\n\n:::\n:::\n\n\nThe usual two-sample $t$-test gives $p = 0.21$. This tells us that the data do not clearly distinguish the groups, but it is not evidence that they are equivalent.\n\n### TOST with $\\Delta = 1$ second\n\nSuppose we pre-specify that a difference of less than 1 second ($\\Delta = 1$) is negligible:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_TOST(formula = qsec ~ am, data = mtcars, eqb = 1, var.equal = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nWelch Two Sample t-test\n\nThe equivalence test was non-significant, t(25.53) = -0.28, p = 0.39\nThe null hypothesis test was non-significant, t(25.53) = 1.288, p = 0.21\nNHST: don't reject null significance hypothesis that the effect is equal to zero \nTOST: don't reject null equivalence hypothesis\n\nTOST Results \n                 t    df p.value\nt-test      1.2878 25.53   0.209\nTOST Lower  2.8524 25.53   0.004\nTOST Upper -0.2767 25.53   0.392\n\nEffect Sizes \n               Estimate     SE              C.I. Conf. Level\nRaw              0.8232 0.6392 [-0.2678, 1.9141]         0.9\nHedges's g(av)   0.4522 0.3783 [-0.1375, 1.0342]         0.9\nNote: SMD confidence intervals are an approximation. See vignette(\"SMD_calcs\").\n```\n\n\n:::\n:::\n\n\nThe 90% confidence interval is $[-0.27, 1.91]$, so it extends beyond $+1.0$. We fail to reject $H_{02}$ and cannot claim equivalence within $\\pm 1$ second.\n\n### TOST with $\\Delta = 2$ seconds\n\nIf the substantive tolerance is instead $\\Delta = 2$ seconds:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_TOST(formula = qsec ~ am, data = mtcars, eqb = 2, var.equal = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nWelch Two Sample t-test\n\nThe equivalence test was significant, t(25.53) = -1.8, p = 0.04\nThe null hypothesis test was non-significant, t(25.53) = 1.288, p = 0.21\nNHST: don't reject null significance hypothesis that the effect is equal to zero \nTOST: reject null equivalence hypothesis\n\nTOST Results \n                t    df p.value\nt-test      1.288 25.53   0.209\nTOST Lower  4.417 25.53 < 0.001\nTOST Upper -1.841 25.53   0.039\n\nEffect Sizes \n               Estimate     SE              C.I. Conf. Level\nRaw              0.8232 0.6392 [-0.2678, 1.9141]         0.9\nHedges's g(av)   0.4522 0.3783 [-0.1375, 1.0342]         0.9\nNote: SMD confidence intervals are an approximation. See vignette(\"SMD_calcs\").\n```\n\n\n:::\n:::\n\n\nNow the 90% confidence interval $[-0.27, 1.91]$ lies completely inside $[-2, 2]$. Both one-sided tests reject ($p_1 < 0.001$, $p_2 = 0.039$), so the groups are statistically equivalent within $\\pm 2$ seconds at $\\alpha = 0.05$.\n\n## Bayesian equivalence testing and units\n\nWe can also evaluate a Bayes factor for an interval null:\n\n$$\\text{BF}_{\\text{in/out}} = \\frac{p(\\text{data} \\mid \\theta \\in [-\\Delta, +\\Delta])}{p(\\text{data} \\mid \\theta \\notin [-\\Delta, +\\Delta])}$$\n\nThe two R packages use different units. `TOSTER::t_TOST(eqb = ...)` takes the bound in the original outcome units, which are seconds here. `BayesFactor::ttestBF(nullInterval = ...)` expects a standardized effect size in Cohen's $d$.\n\nWe therefore need to divide the raw bound by the pooled standard deviation before passing it to `ttestBF`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(BayesFactor)\n\n# Compute pooled SD to standardize the 2-second bound\ngrp <- split(mtcars$qsec, mtcars$am)\nn1 <- length(grp[[1]])\nn2 <- length(grp[[2]])\nsd_pooled <- sqrt(((n1 - 1) * var(grp[[1]]) + (n2 - 1) * var(grp[[2]])) / (n1 + n2 - 2))\n\ndelta_d <- 2 / sd_pooled  # convert +/- 2 seconds to Cohen's d\nc(sd_pooled = sd_pooled, delta_d = delta_d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsd_pooled   delta_d \n 1.767842  1.131323 \n```\n\n\n:::\n:::\n\n\nWith $s_{\\text{pooled}} \\approx 1.77$, $\\Delta = 2$ corresponds to $d \\approx 1.13$. We can now test the interval null:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nttestBF(formula = qsec ~ am, data = mtcars, nullInterval = c(-delta_d, delta_d))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBayes factor analysis\n--------------\n[1] Alt., r=0.707 -1.1313225176573<d<1.1313225176573    : 0.9813314  ±0%\n[2] Alt., r=0.707 !(-1.1313225176573<d<1.1313225176573) : 0.02203644 ±0.03%\n\nAgainst denominator:\n  Null, mu1-mu2 = 0 \n---\nBayes factor type: BFindepSample, JZS\n```\n\n\n:::\n:::\n\n\nThe Bayes factor is 0.98 for an effect inside $[-\\Delta, +\\Delta]$ relative to the point null and 0.022 for an effect outside it. Their ratio is about $45:1$ ($0.98 / 0.022 \\approx 44.5$) in favor of the equivalence interval. This agrees with the TOST result.\n\n## Choosing the equivalence bound\n\nThe data cannot choose $\\Delta$ for us. It has to come from the application. We might use the smallest effect with a meaningful practical or economic consequence, or the smallest effect that would justify the cost of an intervention. Another option is Simonsohn's (2015) \"small telescopes\" benchmark: use the effect size that an earlier study had only 33% power to detect, denoted by $d_{33\\%}$. The 33% refers to power, not to 33% of the original estimate; $d_{33\\%}$ is a little more than half of $d_{80\\%}$.\n\n## What to report\n\nA large $p$-value is not evidence of no effect. For TOST, report the point estimate, the pre-specified equivalence bound, the $(1 - 2\\alpha)$ confidence interval, and the two test decisions. This gives readers enough information to see whether another reasonable choice of $\\Delta$ would change the conclusion. For a Bayesian interval test, also check whether the software expects the bound in the original units or in standardized units.\n",
    "supporting": [
      "equivalence-testing_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}