{
  "hash": "d8d12bde2db5d60ba4fd1cacdf294828",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Interaction term in a non-linear model\"\ndate: \"2017-12-07\"\n---\n\n\n\n## The issue\n\nIn a linear model with interaction,\n\n$$ E(y) = \\beta_1 x_1 + \\beta_2 x_2 + \\beta_{12} x_1 x_2, $$ {#eq-interaction-nonlinear-1}\n\nthe cross partial derivative is simply the coefficient:\n\n$$ \\frac{\\partial^2 E(y)}{\\partial x_1 \\partial x_2} = \\beta_{12}. $$ {#eq-interaction-nonlinear-2}\n\nIn a nonlinear model — logit, Poisson, or any link function $F$ — the same coefficient $\\beta_{12}$ sits on the *link* scale:\n\n$$ F(E(y)) = \\beta_1 x_1 + \\beta_2 x_2 + \\beta_{12} x_1 x_2. $$ {#eq-interaction-nonlinear-3}\n\nThe cross partial of $F(E(y))$ is still $\\beta_{12}$. But the cross partial of $E(y)$ itself — the quantity most researchers want — is not:\n\n$$ \\frac{\\partial^2 E(y)}{\\partial x_1 \\partial x_2} = \\beta_{12} G'(\\eta) + (\\beta_{1} + \\beta_{12} x_2)(\\beta_2 + \\beta_{12} x_1) G''(\\eta), $$ {#eq-interaction-nonlinear-5}\n\nwhere $G = F^{-1}$ and $\\eta$ is the linear predictor. This is the point of [Ai and Norton (2003)](https://pdfs.semanticscholar.org/6285/8e64d9a337504d72cb862c4cc1e7fd27a7a0.pdf): the probability-scale interaction effect depends on every coefficient, varies across the covariate space, and can differ in sign and significance from $\\beta_{12}$.\n\nThe deeper issue is that nonlinearity alone generates a nonzero cross partial — even without an interaction term. Drop $\\beta_{12}$ and the cross partial on $E(y)$ is still $\\beta_1 \\beta_2 G''(\\eta) \\ne 0$ whenever the link is curved. The marginal effect of $x_1$ depends on $x_2$ in any nonlinear model, interaction or not.\n\nGreene (*Econometric Analysis*, 8th ed., sec. 17.3) and [Buis (2010)](http://www.stata-journal.com/sjpdf.html?articlenum=st0194) draw the same conclusion: the model is specified on the link scale, and that is where coefficients and their tests are interpretable. In a logit, $\\beta_{12}$ is the interaction on log-odds; exponentiating gives an odds-ratio interaction that is multiplicative. Partial effects on the probability scale are *implications* of the model, not parameters of it — they should be computed from the fitted model (via `margins` or `marginaleffects`), not read off the coefficient table.\n\n## A worked example\n\nLet's illustrate the Ai-Norton point directly: in a logit model with an interaction term, the cross partial derivative $\\frac{\\partial^2 E(y)}{\\partial x_1 \\partial x_2}$ (what we actually care about) is not the same object as the estimated coefficient $\\beta_{12}$ on $x_1 x_2$ in the linear index. We simulate data with a true interaction effect on the log-odds scale, fit a logit model, and then use the `marginaleffects` package for two distinct things: first the marginal effect of $x_1$ on the probability scale at several values of $x_2$, and then the cross partial derivative itself.\n\nWe draw $n = 2000$ observations with $x_1, x_2 \\sim N(0,1)$, independent of each\nother. The linear index is\n$\\eta = -0.3 + 0.8x_1 + 0.5x_2 + 0.6\\,x_1x_2$, the success probability is\n$p = \\Lambda(\\eta)$, and $y \\sim \\text{Bernoulli}(p)$. So the true interaction on\nthe log-odds scale is $\\beta_{12} = 0.6$, a single constant — which is exactly\nthe object the coefficient table estimates, and exactly the object that does\n*not* transfer to the probability scale.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(marginaleffects)\n\nset.seed(42)\nn <- 2000\nx1 <- rnorm(n)\nx2 <- rnorm(n)\neta <- -0.3 + 0.8 * x1 + 0.5 * x2 + 0.6 * x1 * x2\np <- plogis(eta)\ny <- rbinom(n, 1, p)\ndat <- data.frame(y, x1, x2)\n\nm <- glm(y ~ x1 * x2, data = dat, family = binomial)\nsummary(m)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Estimate Std. Error   z value     Pr(>|z|)\n(Intercept) -0.2348658 0.05017155 -4.681255 2.851237e-06\nx1           0.7792602 0.05930028 13.140920 1.918795e-39\nx2           0.5296149 0.05537644  9.563903 1.133977e-21\nx1:x2        0.6624955 0.06403580 10.345705 4.376826e-25\n```\n\n\n:::\n:::\n\n\nThe coefficient on `x1:x2` is 0.662 with a standard error of 0.064, against a\ntrue 0.6 — recovered to within one standard error, as it should be, since the\nlogit is correctly specified. The other three are 0.779, 0.530 and $-0.235$\nagainst true values of 0.8, 0.5 and $-0.3$.\n\nThat coefficient is $\\hat\\beta_{12}$, the interaction effect on the log-odds (linear index) scale — constant by construction. On the *probability* scale nothing is constant. Start with the marginal effect of $x_1$ itself, evaluated at three values of $x_2$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nslopes(m, variables = \"x1\", by = \"x2\", newdata = datagrid(x2 = c(-1, 0, 1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n x2 Estimate Std. Error     z Pr(>|z|)     S    2.5 % 97.5 %\n -1   0.0253     0.0159  1.59    0.112   3.2 -0.00591 0.0565\n  0   0.1919     0.0147 13.09   <0.001 127.6  0.16314 0.2206\n  1   0.3538     0.0243 14.59   <0.001 157.7  0.30630 0.4014\n\nTerm: x1\nType: response\nComparison: dY/dX\n```\n\n\n:::\n:::\n\n\nThe marginal effect of $x_1$ on $P(y=1)$ is 0.025 at $x_2=-1$, 0.192 at\n$x_2=0$, and 0.354 at $x_2=1$ — a fourteen-fold change across the three values,\nwhere the log-odds interaction is one fixed number. Notice too that at\n$x_2=-1$ the effect is not significant ($p = 0.112$) even though\n$\\hat\\beta_{12}$ is significant at better than $10^{-24}$. Already the\nprobability-scale answer and the coefficient tell different stories.\n\nThe cross partial derivative is a *further* step: not the effect of $x_1$ at a\ngiven $x_2$, but how much that effect changes as $x_2$ moves. That is a\ndifference of slopes, so it needs a hypothesis test on top of the `by` argument\nrather than a second call to `slopes()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nslopes(m, variables = \"x1\", by = \"x2\",\n       newdata = datagrid(x2 = c(-1, 1)),\n       hypothesis = \"b2 - b1 = 0\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Hypothesis Estimate Std. Error  z Pr(>|z|)    S 2.5 % 97.5 %\n    b2-b1=0    0.329     0.0299 11   <0.001 90.7  0.27  0.387\n\nType: response\n```\n\n\n:::\n:::\n\n\nThe cross partial is 0.329 with a standard error of 0.030, $z = 11$ — that is\nthe difference between the slope at $x_2=1$ and the slope at $x_2=-1$,\n$0.354 - 0.025$, with a proper standard error attached. It is large and highly\nsignificant, which is worth being honest about: in *this* example it agrees with\n$\\hat\\beta_{12}$ in significance, differing only in scale and magnitude. Note\nthat it is nowhere near 0.662; the two numbers live on different scales and\nthere is no reason to expect them to match. Ai and Norton's warning is\nthat the two quantities *need not* agree — not that they never do. The\ndependable lesson is the one visible in the table above: on the probability\nscale the answer depends on where you evaluate it, so a single coefficient\ncannot summarise it.\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}