{
  "hash": "3b268a416f19d9152d951d0992c7139a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"What model to use for rare events\"\ndate: \"2017-10-26\"\n---\n\n\n## Introduction\n\nIn empirical studies, people are worried about rare event situation.  That is, when you have, for example, lots of 0's and only a few 1's, or vice versa.  Do you run a logit model, or do you use a \"rare event logit\"?  When should you use either approach?  Or there is a third approach?\n\nPaul Allison said in his blog (https://statisticalhorizons.com/logistic-regression-for-rare-events):\n\n\"Prompted by a 2001 article by King and Zeng, many researchers worry about whether they can legitimately use conventional logistic regression for data in which events are rare. Although King and Zeng accurately described the problem and proposed an appropriate solution, there are still a lot of misconceptions about this issue.\n\nThe problem is not specifically the rarity of events, but rather the possibility of a small number of cases on the rarer of the two outcomes.  If you have a sample size of 1000 but only 20 events, you have a problem. If you have a sample size of 10,000 with 200 events, you may be OK. If your sample has 100,000 cases with 2000 events, you're golden.\"\n\nIn general I agree with him.  However, when exactly should we use King and Zeng's \"relogit\"?\n\nAllison also mentioned two other methods.  One is called the Firth method, a penalized likelihood approach.  The other one is the exact logistic regression, which is for small samples.\n\nIn this simulation exercise, I compare logit against bias-reduced logistic\nregression (`brglm2` with `method=\"brglmFit\"`, `type=\"AS_mean\"`) and the Firth\nmodel (`logistf`).\n\nOne thing to be clear about before reading any comparison of the latter two: for a\nlogistic regression **they are the same estimator.** Firth's penalized likelihood\n(penalizing by the Jeffreys prior) coincides with mean bias reduction for GLMs\nwith a canonical link, and logit is canonical for the binomial. So `brglm2`'s\n`AS_mean` and `logistf` solve the same estimating equations and differ only in\nnumerical tolerance and in how each package builds standard errors and intervals\n(`logistf` uses penalized profile likelihood). A demonstration, on a\ndeliberately rare-event DGP: $n = 500$, $x \\sim N(0,1)$, and\n$y \\sim \\text{Bernoulli}(\\Lambda(-3.5 + 0.8x))$, which puts the event rate\naround 3% — roughly fifteen events in the whole sample.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(brglm2); library(logistf)\nset.seed(11)\nn <- 500; x <- rnorm(n); y <- rbinom(n, 1, plogis(-3.5 + 0.8 * x))\nd <- data.frame(y, x)\n\nrbind(\n  `plain logit`     = coef(glm(y ~ x, data = d, family = binomial)),\n  `brglm2 AS_mean`  = coef(glm(y ~ x, data = d, family = binomial,\n                               method = \"brglmFit\", type = \"AS_mean\")),\n  `logistf (Firth)` = coef(logistf(y ~ x, data = d))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                (Intercept)         x\nplain logit       -3.176125 0.7378324\nbrglm2 AS_mean    -3.134453 0.7277674\nlogistf (Firth)   -3.134453 0.7277675\n```\n\n\n:::\n:::\n\n\nThe two bias-reduced fits give $-3.134453$ and $0.7277674$ against\n$-3.134453$ and $0.7277675$: they agree to about $10^{-7}$, which is numerical\ntolerance rather than any statistical difference. Plain logit gives $-3.176$ and\n$0.738$, so on this draw the bias correction moves the slope by about 0.010 and\nthe intercept by 0.042 — both estimators sitting below the true $0.8$ and above\nthe true $-3.5$, which is what fifteen events buys you. This matters for reading the findings below: what\nthe simulation can tell us is how **logit** compares with **Firth-type bias\nreduction**, not which of two implementations of the same estimator is better. If\na genuinely distinct third method is wanted, `brglm2`'s `type = \"AS_median\"`\n(median bias reduction) is one, and King and Zeng's `relogit` correction is\nanother.\n\n## Simulation\n\nHere I have some code for using multiple cores to run these three models.  The bias-reduced logistic regression is implemented in R via the `brglm2` package, the Firth method is implemented in `logistf`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(brglm2)\nlibrary(logistf)\nrequire(snowfall)\nset.seed(666)\n\n# initialize parallel cores.\nsfInit(parallel=TRUE, cpus=16)\n\ngen.sim <- function(df){\n  x <- rnorm(df['nobs'], 0, 1)\n\n  # generate binary data\n  p <- df['p']\n  # NB: alpha = qlogis(p) makes p the event probability at x = 0, not the\n  # marginal event probability. Because the slope on x is 2 and x ~ N(0,1),\n  # the marginal rate is much higher than p: integrating plogis(alpha + 2x)\n  # over x gives 0.044, 0.134 and 0.203 for p = 0.01, 0.05 and 0.10.\n  alpha <- -log((1-p)/p)\n  z = alpha + 2*x\n  pr = 1/(1+exp(-z))\n  y = rbinom(df['nobs'], 1, pr)\n  df = data.frame(y=y, x=x)\n\n  # With small nobs and small p (e.g. nobs=10, p=.01), y can easily come out\n  # all-zero (>90% chance in that cell), which makes glm/logistf unable to\n  # estimate a coefficient on x. Guard against that rather than letting a\n  # single degenerate draw crash the whole parallel simulation loop.\n  if (var(y) == 0) {\n    return(c(logit=NA, brglm2=NA, logistf=NA))\n  }\n\n  # logit\n  m1 <- tryCatch(glm(y ~ x, family='binomial'), error = function(e) NULL)\n  m1.x <- if (!is.null(m1)) summary(m1)$coefficients['x','Estimate'] - 2 else NA\n\n  # bias-reduced logistic regression (brglm2)\n  m2 <- tryCatch(\n    glm(y ~ x, family = binomial(link = \"logit\"), data = df,\n        method = \"brglmFit\", type = \"AS_mean\"),\n    error = function(e) NULL\n  )\n  m2.x <- if (!is.null(m2)) coef(m2)['x'] - 2 else NA\n\n  # logistf (Firth)\n  m3 <- tryCatch(logistf(y ~ x, data=df), error = function(e) NULL)\n  m3.x <- if (!is.null(m3)) coef(m3)['x'] - 2 else NA\n\n  return(c(logit=m1.x, brglm2=m2.x, logistf=m3.x))\n}\n\n# set parameter space\nsim.grid = seq(1, 100, 1)\np.grid = c(.01, .05, .1)\nnobs.grid = c(10, 30, 50, 100, 200, 500, 1000, 10000)\n\ndata.grid <- expand.grid(nobs.grid, sim.grid, p.grid)\nnames(data.grid) <- c('nobs', 'nsim', 'p')\n\n# export functions and libraries to parallel workers\nsfExport(list=list(\"gen.sim\"))\nsfLibrary(brglm2)\nsfLibrary(logistf)\n\nresults <- data.frame(t(sfApply(data.grid, 1, gen.sim)))\n\n# stop the cluster\nsfStop()\n\nforshiny <- cbind(data.grid, results)\nwrite.csv(forshiny, 'results.csv')\n```\n:::\n\n\nWe simulate 100 times with sample size from 10 to 10000, event probability .01, .05, and .1.\n\nSince there are many simulations, we used the `snowfall` library to speed things up.\n\n(The original post plotted bias and MSE by sample size and event probability from the `results.csv` output above; those figures are not reproduced here — the findings are summarized in prose below.)\n\nA caveat on how to read the grid before the findings. The parameter `p` is the\nevent probability at $x=0$, not the marginal event probability: with a slope of 2\non $x \\sim N(0,1)$, the marginal rate is roughly 0.044, 0.134 and 0.203 for\n`p` = 0.01, 0.05 and 0.10. So the expected number of events in a cell is closer\nto $n$ times those numbers than to $n p$, by a factor of about four at the rare\nend. What follows is stated in terms of the realized event count, which is the\nquantity that actually governs the behaviour.\n\nWhen the rarer of the two outcomes has only a handful of observations -- fewer\nthan about five events in the sample -- none of these three models performs well.\nThis is understandable: there is almost nothing in the data to identify the slope.\nOnce the rarer group has more than about fifty events, there is not much\ndifference between the three. In between, we found that Firth-type bias reduction\n--- whether computed by `brglm2` or by `logistf` --- performs better than plain\nlogit.  Any apparent ranking *between* those two should be discounted, since as shown above they are the same estimator; differences at that level reflect numerical tolerance or differing standard-error conventions, not a substantive advantage.\n\nIn the small sample situation, maybe it's better to use the exact logistic regression.\n",
    "supporting": [
      "rare-events_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}