{
  "hash": "d882c60c19e5daa36f9925799cbd9b22",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Frengression and Engression\"\ndate: \"2026-03-21\"\n---\n\nIn the [causal simulation chapter](causal-simulation.qmd), I used Evans and Didelez (2024)'s decomposition of the joint distribution $p(x,a,y)$ into three pieces:\n\n$$ p(x,a,y) = p(x,a) \\cdot p_a(y) \\cdot c(x,y|a) $$ {#eq-frengression-1}\n\nwhere $p(x,a)$ is the \"past\" distribution of covariates and treatment, $p_a(y)$ is the causal margin, and $c(x,y|a)$ is the copula linking covariates and outcome given treatment. The `causl` package implements this with parametric families. We specify Gaussian, binomial, and so on for each piece.\n\nBut real data can be hard to specify parametrically. We may not know the right copula family. The marginal distributions may have mass points, skewness, or other features that are annoying to write down.\n\nFrengression (Yang, Evans and Shen, 2025) keeps the same decomposition but learns the pieces with neural networks.\n\nThere are two uses: causal simulation with a learned generative model, and interventional prediction using learned confounding structure. The second part uses engression, so I start there.\n\n## Engression\n\nEngression (Shen and Meinshausen, 2024) stands for energy regression. Standard regression estimates $E[Y|X]$. Engression tries to learn the whole conditional distribution $P(Y|X)$ using neural networks trained with the energy score.\n\n### The Energy Score\n\nThe energy score is a proper scoring rule for distributions. Given observations $Y$ and samples $\\hat Y, \\hat Y'$ from the model:\n\n$$ S(Y, \\hat Y, \\hat Y') = E\\|Y - \\hat Y\\| - \\frac{1}{2}E\\|\\hat Y - \\hat Y'\\| $$ {#eq-frengression-2}\n\nThe first term rewards samples close to the truth. The second term keeps the simulated distribution from collapsing to one point. This is why the method targets the full distribution rather than only the mean.\n\n### The Stochastic Network (StoNet)\n\nThe building block is a `StoNet`, a neural network that adds random noise $\\epsilon \\sim N(0,I)$ to the input at each layer:\n\n$$\\text{StoNet}(x) = f(x, \\epsilon), \\quad \\epsilon \\sim N(0,I)$$ {#eq-frengression-3}\n\nDifferent noise draws produce different outputs. Each output is a sample from the learned conditional distribution. So we can:\n\n- **Predict the mean**: average over many noise draws → $E[Y|X=x]$\n- **Predict quantiles**: take quantiles of the noise draws → conditional quantile regression\n- **Sample**: each forward pass with fresh noise is a sample from $P(Y|X=x)$\n\n### Why Engression?\n\nCompared with quantile regression or mixture density networks, engression is useful because:\n\n1. it handles multivariate responses directly;\n2. it does not require us to specify a Gaussian mixture or a list of quantiles;\n3. it gives samples from the conditional distribution, which is convenient for simulation.\n\n### Quick Example\n\nThe `engression` R package, separate from `Rfrengression`, provides the\nstandalone estimator. The code below shows the API. The `Rfrengression`\nexamples later are the ones I actually run here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(engression)\n\n# Nonlinear DGP with heteroskedastic noise\nn <- 1000\nX <- matrix(rnorm(n * 2), ncol = 2)\nY <- (X[,1])^2 + X[,2] + rnorm(n) * (0.5 + abs(X[,1]))\n\n# Fit engression; it learns the full conditional distribution\nengr <- engression(X, Y)\n\n# Predict conditional mean (like lm, but nonlinear)\nYhat_mean <- predict(engr, X, type = \"mean\")\n\n# Predict conditional quantiles (like quantile regression, but joint)\nYhat_quant <- predict(engr, X, type = \"quantiles\")\n\n# Sample from the learned distribution (generative)\nYsample <- predict(engr, X, type = \"sample\", nsample = 1)\n```\n:::\n\n\nThe point is that engression gives a distributional model of $Y|X$, not just a fitted mean.\n\n## From Engression to Frengression\n\nFrengression is frugal simulation plus engression. It uses three engression models to represent the decomposition of $P(X,A,Y)$. Each sub-network is trained with the energy score.\n\n## The Architecture\n\nFrengression has three sub-networks, matching the three pieces of the decomposition:\n\n| Decomposition | causl (parametric) | Frengression (neural net) |\n|---|---|---|\n| $P(X,A)$ — the past | Specified by family + params | `model_xz`: noise-only generator |\n| $P_a(Y)$ — causal margin | Specified by family + params | `model_y`: takes $(x, \\text{eta})$, outputs $y$ |\n| $c(X,Y \\mid A)$ — copula | Gaussian/Frank/etc. copula | `model_eta`: takes $(x,z)$, outputs eta |\n\nThe important part is `model_eta`. It takes $(x,z)$ and outputs a latent variable `eta` that carries the dependence between confounders and outcome. During training, a Z-permutation trick forces `eta` to be marginally $N(0,I)$. This means:\n\n- When `eta` comes from `model_eta(x,z)`, it carries the observational confounding information.\n- When `eta` is sampled independently from $N(0,1)$, it gives the interventional prediction.\n\nSame network, different source of `eta`. That is the trick.\n\n## Using Rfrengression\n\nThe `Rfrengression` package is a native R implementation using `torch`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(Rfrengression)\n```\n:::\n\n\n### Example: Binary Treatment DGP\n\nUse a DGP with binary treatment, binary outcome, and four confounders. We draw\n$n = 2000$ observations with $w_1, w_2 \\sim \\text{Bernoulli}(0.5)$,\n$w_3 \\sim U(0,4)$ and $w_4 \\sim U(0,5)$; treatment is\n$A \\sim \\text{Bernoulli}(\\Lambda(-0.4 + 0.2w_2 + 0.15w_3 + 0.2w_4 + 0.15w_2w_4))$;\nand both potential outcomes are Bernoulli with the same logit index shifted by\nthe treatment. Since both are simulated, the realized ATE is known:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\nn <- 2000\n\nw1 <- rbinom(n, 1, 0.5)\nw2 <- rbinom(n, 1, 0.5)\nw3 <- round(runif(n, 0, 4), 3)\nw4 <- round(runif(n, 0, 5), 3)\n\nA <- rbinom(n, 1, plogis(-0.4 + 0.2*w2 + 0.15*w3 + 0.2*w4 + 0.15*w2*w4))\nY.1 <- rbinom(n, 1, plogis(-1 + 1 - 0.1*w1 + 0.3*w2 + 0.25*w3 + 0.2*w4 + 0.15*w2*w4))\nY.0 <- rbinom(n, 1, plogis(-1 + 0 - 0.1*w1 + 0.3*w2 + 0.25*w3 + 0.2*w4 + 0.15*w2*w4))\nY <- Y.1 * A + Y.0 * (1 - A)\n\ntrue_ate <- mean(Y.1 - Y.0)\ncat(\"True ATE:\", round(true_ate, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue ATE: 0.1935 \n```\n\n\n:::\n:::\n\n\n### Train Frengression\n\nTraining has two stages: first the outcome model (`model_y` + `model_eta`), then the marginal model (`model_xz`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# torch keeps its own generator; R's set.seed() does not reach it.\ntorch::torch_manual_seed(1)\n\nx_mat <- matrix(A, ncol = 1)\nz_mat <- as.matrix(data.frame(w1, w2, w3, w4))\ny_mat <- matrix(Y, ncol = 1)\n\nmodel <- frengression(x_dim = 1, y_dim = 1, z_dim = 4,\n                      x_binary = TRUE, y_binary = TRUE,\n                      z_binary_dims = 2, noise_dim = 10)\n\nmodel <- train_y(model, x_mat, z_mat, y_mat,\n                 num_iters = 1000, lr = 1e-3, print_every = 500)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEpoch 1: loss 1.2606, loss_y 0.4787 (0.4977, 0.0380), loss_eta 0.7818 (0.8583, 0.1528)\nStopping at iter 67 \n```\n\n\n:::\n\n```{.r .cell-code}\nmodel <- train_xz(model, x_mat, z_mat,\n                   num_iters = 1000, lr = 1e-4, print_every = 500)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEpoch 1: loss 3.4470, loss1 3.6066, loss2 0.3192\nEpoch 500: loss 1.3948, loss1 2.7241, loss2 2.6587\nEpoch 1000: loss 1.3395, loss1 2.7058, loss2 2.7327\n```\n\n\n:::\n:::\n\n\n### Estimate ATE\n\nFor interventional prediction, `eta` is sampled from $N(0,1)$ instead of being generated from the observed confounding structure:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntorch::torch_manual_seed(1)\n\ny1 <- predict(model, matrix(1, ncol = 1), type = \"mean\", nsample = 2000)\ny0 <- predict(model, matrix(0, ncol = 1), type = \"mean\", nsample = 2000)\n\ncat(\"Frengression ATE:\", round(y1 - y0, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFrengression ATE: 0.165 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"True ATE:\", round(true_ate, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue ATE: 0.1935 \n```\n\n\n:::\n:::\n\n\nThe realized ATE is 0.1935 and frengression lands a few hundredths below it.\n\nThe training chunks carry `cache: false`, so they re-run on every render, and\ntorch keeps a generator of its own that R's `set.seed()` does not reach. Seeding\nit with `torch_manual_seed()` fixes the weight initialisation, the training\ndraws, and the sampling inside `predict()`, so the figure above is reproducible\nfrom one render to the next. On a CUDA device some nondeterminism can survive\nthe seed, from cuDNN algorithm selection and atomic accumulation in the backward\npass.\n\n## Frengression as DGP\n\nFrengression can estimate an ATE, but that is not its main advantage. If I only want an ATE, I would usually use `npcausal`, TMLE, or DoubleML. The more interesting use is to train a data-generating process for benchmarking.\n\nThe idea is:\n\n1. Train frengression on observational data, so it learns the confounding structure.\n2. Replace the causal margin with a known function via `specify_causal()`.\n3. Generate synthetic data with realistic confounding and known ground truth.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Specify a known causal effect: Y = sigmoid(0.2*X + eta)\nmodel_bench <- specify_causal(model, function(x, eta) {\n  torch::torch_sigmoid(0.2 * x + eta)\n})\n\n# True ATE computed empirically from the model\ny1_true <- predict(model_bench, matrix(1, ncol = 1), type = \"mean\", nsample = 5000)\ny0_true <- predict(model_bench, matrix(0, ncol = 1), type = \"mean\", nsample = 5000)\ncat(\"True ATE (specified):\", round(as.numeric(y1_true - y0_true), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue ATE (specified): 0.0831 \n```\n\n\n:::\n:::\n\n\nNow we can generate synthetic data and benchmark any method:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsyn <- sample_joint(model_bench, sample_size = 1000)\ncat(\"Synthetic data: n =\", nrow(syn$x), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSynthetic data: n = 1000 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Treatment prevalence:\", mean(syn$x), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTreatment prevalence: 0.891 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Outcome prevalence:\", mean(syn$y), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOutcome prevalence: 0.572 \n```\n\n\n:::\n:::\n\n\n## Real Data: LaLonde\n\nThis is most useful with real data. The LaLonde job-training data have many of the problems that make simulations hard to write by hand: zeros in prior earnings, uneven covariate distributions, and poor overlap.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(MatchIt)\ndata(\"lalonde\", package = \"MatchIt\")\nlalonde$black <- as.integer(lalonde$race == \"black\")\nlalonde$hispan <- as.integer(lalonde$race == \"hispan\")\n\nx_lal <- matrix(lalonde$treat, ncol = 1)\ny_lal <- matrix(lalonde$re78, ncol = 1)\n# frengression's z_binary_dims assumes the FIRST z_binary_dims columns of z\n# are the binary ones -- so the binary covariates (black, hispan, married,\n# nodegree) must come first, followed by the continuous ones (age, educ,\n# re74, re75). The original column order (age, educ first) put two\n# continuous variables where binary ones were expected, and vice versa.\nz_lal <- as.matrix(lalonde[, c(\"black\", \"hispan\", \"married\", \"nodegree\",\n                                \"age\", \"educ\", \"re74\", \"re75\")])\n\n# Standardize for training\nz_sc <- scale(z_lal)\ny_sc <- (y_lal - mean(y_lal)) / sd(y_lal)\n\nmodel_lal <- frengression(x_dim = 1, y_dim = 1, z_dim = 8,\n                           x_binary = TRUE, y_binary = FALSE,\n                           z_binary_dims = 4, noise_dim = 10)\n\nmodel_lal <- train_y(model_lal, x_lal, z_sc, y_sc,\n                      num_iters = 1000, lr = 1e-3, print_every = 500)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEpoch 1: loss 1.4330, loss_y 0.7412 (0.7899, 0.0974), loss_eta 0.6918 (0.7855, 0.1875)\nStopping at iter 52 \n```\n\n\n:::\n\n```{.r .cell-code}\nmodel_lal <- train_xz(model_lal, x_lal, z_sc,\n                        num_iters = 1000, lr = 1e-4, print_every = 500)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEpoch 1: loss 2.7586, loss1 2.9617, loss2 0.4063\nEpoch 500: loss 2.0119, loss1 3.8498, loss2 3.6759\nEpoch 1000: loss 1.9657, loss1 3.8158, loss2 3.7002\n```\n\n\n:::\n:::\n\n\nNow specify a known effect and generate data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_lal_bench <- specify_causal(model_lal, function(x, eta) {\n  0.3 * x + eta\n})\n\n# Generate synthetic LaLonde-like data with known ATE = 0.3 (standardized)\nsyn_lal <- sample_joint(model_lal_bench, sample_size = 2000)\ncat(\"Synthetic LaLonde: n =\", nrow(syn_lal$x), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSynthetic LaLonde: n = 2000 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Treatment prevalence:\", round(mean(syn_lal$x), 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTreatment prevalence: 0.007 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"True ATE:\", 0.3, \"(standardized) =\", round(0.3 * sd(y_lal), 0), \"dollars\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue ATE: 0.3 (standardized) = 2241 dollars\n```\n\n\n:::\n:::\n\n\nThe synthetic data inherits LaLonde's confounding structure, but now the true effect is known. This is the part that is hard to do with a hand-written DGP.\n\n## Comparison: causl vs frengression\n\nBoth packages use the same decomposition:\n\n| Feature | causl | Frengression |\n|---|---|---|\n| Marginal $P(X,A)$ | Parametric families | Learned by neural net |\n| Causal margin $P_a(Y)$ | Parametric families | Learned (or specified) |\n| Copula | Gaussian, Frank, etc. | Learned by `model_eta` |\n| Requires specification | Yes — families + params | No — learns from data |\n| Can learn from real data | Limited (plasmode) | Yes — full joint |\n| Distributional flexibility | Limited by family choice | Arbitrary |\n\nThe `causl` approach is more transparent because we know exactly what we specified. Frengression is more flexible because it can learn structure we did not write down. I would treat them as complements.\n\n## Benchmarking: Frengression vs Semiparametric Methods\n\nNow compare frengression against standard semiparametric causal inference tools on the same data. The three comparison methods are:\n\n- `npcausal`: AIPW estimator with SuperLearner nuisance models\n- `tmle`: targeted minimum loss-based estimation with SuperLearner\n- `DoubleML`: partially linear regression with `ranger`\n\nThese methods are built for ATE estimation. They should usually be better for this specific estimand. The comparison is still useful because frengression is trying to learn much more than the ATE.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(npcausal)\nlibrary(tmle)\nlibrary(SuperLearner)\nlibrary(DoubleML)\nlibrary(mlr3)\nlibrary(mlr3learners)\nlibrary(tidyverse)\nlibrary(knitr)\n```\n:::\n\n\n### Single-Dataset Comparison\n\nFirst, run all four methods on the binary DGP data created above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nW <- data.frame(w1, w2, w3, w4)\nSL.library <- c(\"SL.earth\", \"SL.glm.interaction\", \"SL.mean\",\n                \"SL.ranger\", \"SL.glmnet\")\n\nset.seed(123)\naipw_fit <- ate(y = Y, a = A, x = W, nsplits = 2, sl.lib = SL.library)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |=========                                                             |  12%\n  |                                                                            \n  |==================                                                    |  25%\n  |                                                                            \n  |==========================                                            |  38%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |============================================                          |  62%\n  |                                                                            \n  |====================================================                  |  75%\n  |                                                                            \n  |=============================================================         |  88%\n  |                                                                            \n  |======================================================================| 100%\n     parameter       est         se     ci.ll     ci.ul pval\n1      E{Y(0)} 0.5697312 0.02038159 0.5297832 0.6096791    0\n2      E{Y(1)} 0.7608322 0.01207030 0.7371744 0.7844900    0\n3 E{Y(1)-Y(0)} 0.1911010 0.02335102 0.1453330 0.2368690    0\n```\n\n\n:::\n\n```{.r .cell-code}\nate_npcausal <- aipw_fit$res$est[3]\nse_npcausal  <- aipw_fit$res$se[3]\nci_npcausal  <- c(aipw_fit$res$ci.ll[3], aipw_fit$res$ci.ul[3])\n\ncat(\"npcausal ATE:\", round(ate_npcausal, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnpcausal ATE: 0.1911 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"SE:\", round(se_npcausal, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSE: 0.0234 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\ntmle_fit <- tmle(Y = Y, A = A, W = W, family = \"binomial\",\n                 Q.SL.library = SL.library, g.SL.library = SL.library)\n\nate_tmle <- tmle_fit$estimates$ATE$psi\nse_tmle  <- sqrt(tmle_fit$estimates$ATE$var.psi)\nci_tmle  <- tmle_fit$estimates$ATE$CI\n\ncat(\"TMLE ATE:\", round(ate_tmle, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTMLE ATE: 0.1916 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"SE:\", round(se_tmle, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSE: 0.0209 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlgr::get_logger(\"mlr3\")$set_threshold(\"warn\")\ndata_obs <- data.frame(w1, w2, w3, w4, A, Y)\n\ndml_data <- DoubleMLData$new(data_obs,\n                              y_col = \"Y\", d_cols = \"A\",\n                              x_cols = c(\"w1\", \"w2\", \"w3\", \"w4\"))\n\nlearner_l <- lrn(\"regr.ranger\", num.trees = 500, max.depth = 5, min.node.size = 2)\nlearner_m <- learner_l$clone()\n\nset.seed(123)\ndml_plr <- DoubleMLPLR$new(dml_data, ml_l = learner_l, ml_m = learner_m)\ndml_plr$fit()\n\nate_dml <- dml_plr$coef\nse_dml  <- dml_plr$se\nci_dml  <- c(dml_plr$confint()[1], dml_plr$confint()[2])\n\ncat(\"DoubleML ATE:\", round(ate_dml, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDoubleML ATE: 0.1872 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"SE:\", round(se_dml, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSE: 0.0229 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Frengression ATE already computed above (y1 - y0)\nate_freng <- as.numeric(y1 - y0)\n\n# Bootstrap SE via repeated prediction (Monte Carlo variability)\nset.seed(123)\nate_boot <- replicate(200, {\n  predict(model, matrix(1, ncol = 1), type = \"mean\", nsample = 500) -\n    predict(model, matrix(0, ncol = 1), type = \"mean\", nsample = 500)\n})\nse_freng <- sd(ate_boot)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresults <- data.frame(\n  Method = c(\"True ATE\", \"Frengression\", \"npcausal (AIPW)\", \"TMLE\", \"DoubleML (PLR)\"),\n  ATE = c(true_ate, ate_freng, ate_npcausal, ate_tmle, ate_dml),\n  SE = c(NA, se_freng, se_npcausal, se_tmle, se_dml),\n  CI_lower = c(NA,\n               ate_freng - 1.96 * se_freng,\n               ci_npcausal[1], ci_tmle[1], ci_dml[1]),\n  CI_upper = c(NA,\n               ate_freng + 1.96 * se_freng,\n               ci_npcausal[2], ci_tmle[2], ci_dml[2])\n)\n\nresults$Bias <- results$ATE - true_ate\nresults$Covers <- ifelse(is.na(results$CI_lower), NA,\n                         results$CI_lower <= true_ate & true_ate <= results$CI_upper)\n\nkable(results, digits = 4,\n      caption = \"ATE Estimation: Frengression vs Semiparametric Methods\")\n```\n\n::: {.cell-output-display}\n\n\nTable: ATE Estimation: Frengression vs Semiparametric Methods\n\n|Method          |    ATE|     SE| CI_lower| CI_upper|    Bias|Covers |\n|:---------------|------:|------:|--------:|--------:|-------:|:------|\n|True ATE        | 0.1935|     NA|       NA|       NA|  0.0000|NA     |\n|Frengression    | 0.1650| 0.0318|   0.1026|   0.2274| -0.0285|TRUE   |\n|npcausal (AIPW) | 0.1911| 0.0234|   0.1453|   0.2369| -0.0024|TRUE   |\n|TMLE            | 0.1916| 0.0209|   0.1506|   0.2326| -0.0019|TRUE   |\n|DoubleML (PLR)  | 0.1872| 0.0229|   0.1424|   0.2320| -0.0063|TRUE   |\n\n\n:::\n:::\n\n\nOn this single dataset the ranking is what one would expect. TMLE gives 0.1916,\nnpcausal 0.1911 and DoubleML 0.1872, all within 0.007 of the true 0.1935;\nfrengression gives 0.1650, a bias of $-0.0285$, roughly four times larger. Its\nbootstrap standard error is also the widest, 0.0318 against 0.021–0.023. All\nfour intervals cover the truth.\n\nThe semiparametric estimators target the ATE directly. Frengression learns the joint distribution and then computes the ATE as one functional of that distribution. So I would not expect it to be the most precise ATE estimator in this table.\n\n### Monte Carlo Benchmarking (Simulated DGP)\n\nThis is where frengression is more useful. Use the model trained above, plug in a known causal effect with `specify_causal()`, generate 10 synthetic datasets, and benchmark all four estimators.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nB <- 10\nn_syn <- 2000\n\nmethods <- c(\"Frengression\", \"npcausal\", \"TMLE\", \"DoubleML\")\nate_mat <- matrix(NA, nrow = B, ncol = length(methods),\n                  dimnames = list(NULL, methods))\nse_mat  <- ate_mat\ncover_mat <- ate_mat\n\nSL.lib_fast <- c(\"SL.glm.interaction\", \"SL.ranger\", \"SL.mean\")\n\n# True ATE from the specified model (already computed above as y1_true - y0_true)\ntrue_ate_bench <- as.numeric(y1_true - y0_true)\n\nset.seed(2024)\nfor (b in seq_len(B)) {\n  syn <- sample_joint(model_bench, sample_size = n_syn)\n\n  x_syn <- as.numeric(syn$x)\n  y_syn <- as.numeric(syn$y)\n  z_syn <- as.data.frame(syn$z)\n  colnames(z_syn) <- paste0(\"z\", 1:ncol(z_syn))\n  df_syn <- cbind(data.frame(A = x_syn, Y = y_syn), z_syn)\n\n  # --- Frengression ---\n  tryCatch({\n    mod_f <- frengression(x_dim = 1, y_dim = 1, z_dim = ncol(z_syn),\n                          x_binary = TRUE, y_binary = TRUE,\n                          noise_dim = 10, hidden_dim = 100, num_layer = 3)\n    mod_f <- train_y(mod_f, matrix(x_syn, ncol=1), as.matrix(z_syn),\n                     matrix(y_syn, ncol=1),\n                     num_iters = 500, lr = 1e-3, silent = TRUE)\n    mod_f <- train_xz(mod_f, matrix(x_syn, ncol=1), as.matrix(z_syn),\n                       num_iters = 500, lr = 1e-4, silent = TRUE)\n\n    y1_f <- predict(mod_f, matrix(1, ncol=1), type=\"mean\", nsample=1000)\n    y0_f <- predict(mod_f, matrix(0, ncol=1), type=\"mean\", nsample=1000)\n    ate_mat[b, \"Frengression\"] <- y1_f - y0_f\n\n    ate_mc <- replicate(100, {\n      predict(mod_f, matrix(1,ncol=1), type=\"mean\", nsample=200) -\n        predict(mod_f, matrix(0,ncol=1), type=\"mean\", nsample=200)\n    })\n    se_mat[b, \"Frengression\"] <- sd(ate_mc)\n    ci_f <- ate_mat[b, \"Frengression\"] + c(-1,1) * 1.96 * se_mat[b, \"Frengression\"]\n    cover_mat[b, \"Frengression\"] <- (ci_f[1] <= true_ate_bench & true_ate_bench <= ci_f[2])\n  }, error = function(e) message(\"Frengression failed on rep \", b, \": \", e$message))\n\n  # --- npcausal ---\n  tryCatch({\n    fit_np <- ate(y = y_syn, a = x_syn, x = z_syn,\n                  nsplits = 2, sl.lib = SL.lib_fast)\n    ate_mat[b, \"npcausal\"] <- fit_np$res$est[3]\n    se_mat[b, \"npcausal\"]  <- fit_np$res$se[3]\n    ci <- c(fit_np$res$ci.ll[3], fit_np$res$ci.ul[3])\n    cover_mat[b, \"npcausal\"] <- (ci[1] <= true_ate_bench & true_ate_bench <= ci[2])\n  }, error = function(e) message(\"npcausal failed on rep \", b, \": \", e$message))\n\n  # --- TMLE ---\n  tryCatch({\n    fit_tmle <- tmle(Y = y_syn, A = x_syn, W = z_syn, family = \"binomial\",\n                     Q.SL.library = SL.lib_fast, g.SL.library = SL.lib_fast)\n    ate_mat[b, \"TMLE\"] <- fit_tmle$estimates$ATE$psi\n    se_mat[b, \"TMLE\"]  <- sqrt(fit_tmle$estimates$ATE$var.psi)\n    ci_t <- fit_tmle$estimates$ATE$CI\n    cover_mat[b, \"TMLE\"] <- (ci_t[1] <= true_ate_bench & true_ate_bench <= ci_t[2])\n  }, error = function(e) message(\"TMLE failed on rep \", b, \": \", e$message))\n\n  # --- DoubleML ---\n  tryCatch({\n    dml_d <- DoubleMLData$new(df_syn, y_col = \"Y\", d_cols = \"A\",\n                               x_cols = colnames(z_syn))\n    lr_l <- lrn(\"regr.ranger\", num.trees = 300, max.depth = 5, min.node.size = 2)\n    lr_m <- lr_l$clone()\n    dml_obj <- DoubleMLPLR$new(dml_d, ml_l = lr_l, ml_m = lr_m)\n    dml_obj$fit()\n    ate_mat[b, \"DoubleML\"] <- dml_obj$coef\n    se_mat[b, \"DoubleML\"]  <- dml_obj$se\n    ci_d <- c(dml_obj$confint()[1], dml_obj$confint()[2])\n    cover_mat[b, \"DoubleML\"] <- (ci_d[1] <= true_ate_bench & true_ate_bench <= ci_d[2])\n  }, error = function(e) message(\"DoubleML failed on rep \", b, \": \", e$message))\n\n  if (b %% 5 == 0) cat(\"Completed replication\", b, \"of\", B, \"\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCompleted replication 5 of 10 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCompleted replication 10 of 10 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbench_summary <- data.frame(\n  Method = colnames(ate_mat),\n  Mean_ATE = colMeans(ate_mat, na.rm = TRUE),\n  Bias = colMeans(ate_mat, na.rm = TRUE) - true_ate_bench,\n  SD = apply(ate_mat, 2, sd, na.rm = TRUE),\n  RMSE = sqrt(colMeans((ate_mat - true_ate_bench)^2, na.rm = TRUE)),\n  Mean_SE = colMeans(se_mat, na.rm = TRUE),\n  Coverage_95 = colMeans(cover_mat, na.rm = TRUE),\n  N_valid = colSums(!is.na(ate_mat))\n)\n\nkable(bench_summary, digits = 4,\n      caption = paste0(\"Monte Carlo Benchmarking (B=\", B,\n                       \", n=\", n_syn, \", True ATE=\",\n                       round(true_ate_bench, 4), \")\"))\n```\n\n::: {.cell-output-display}\n\n\nTable: Monte Carlo Benchmarking (B=10, n=2000, True ATE=0.0662)\n\n|             |Method       | Mean_ATE|   Bias|     SD|   RMSE| Mean_SE| Coverage_95| N_valid|\n|:------------|:------------|--------:|------:|------:|------:|-------:|-----------:|-------:|\n|Frengression |Frengression |   0.0676| 0.0013| 0.0331| 0.0315|  0.0562|         1.0|      10|\n|npcausal     |npcausal     |   0.2194| 0.1532| 0.1113| 0.1861|  0.0715|         0.4|      10|\n|TMLE         |TMLE         |   0.2869| 0.2207| 0.2401| 0.3171|  0.0187|         0.1|      10|\n|DoubleML     |DoubleML     |   0.0728| 0.0066| 0.0646| 0.0617|  0.0686|         1.0|      10|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nate_long <- as.data.frame(ate_mat) |>\n  pivot_longer(everything(), names_to = \"Method\", values_to = \"ATE\") |>\n  filter(!is.na(ATE))\n\n# Trim extreme outliers for readable plot\nq_bounds <- quantile(ate_long$ATE, c(0.02, 0.98), na.rm = TRUE)\nate_long_trim <- ate_long |> filter(ATE >= q_bounds[1] & ATE <= q_bounds[2])\n\nggplot(ate_long_trim, aes(x = Method, y = ATE, fill = Method)) +\n  geom_boxplot(alpha = 0.7) +\n  geom_hline(yintercept = true_ate_bench, linetype = \"dashed\", color = \"red\",\n             linewidth = 1) +\n  annotate(\"text\", x = 0.5, y = true_ate_bench, label = \"True ATE\",\n           hjust = 0, vjust = -0.5, color = \"red\") +\n  labs(title = \"ATE Estimates Across Frengression-Generated Datasets\",\n       subtitle = paste0(\"B=\", B, \" replications, n=\", n_syn, \" per dataset\"),\n       y = \"Estimated ATE\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![ATE Estimates Across Synthetic Datasets](frengression_files/figure-html/benchmark_plot-1.png){width=672}\n:::\n:::\n\n\n### Monte Carlo Benchmarking (LaLonde)\n\nNow do the same exercise with the LaLonde-trained model. Here the confounding structure comes from the real data rather than from my hand-written simulation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute true ATE empirically from the specified model\ny1_lal_true <- predict(model_lal_bench, matrix(1, ncol=1), type=\"mean\", nsample=5000)\ny0_lal_true <- predict(model_lal_bench, matrix(0, ncol=1), type=\"mean\", nsample=5000)\ntrue_ate_lal <- as.numeric(y1_lal_true - y0_lal_true)\ncat(\"True ATE (standardized):\", round(true_ate_lal, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue ATE (standardized): 0.2627 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"True ATE (dollars):\", round(true_ate_lal * sd(y_lal), 0), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue ATE (dollars): 1963 \n```\n\n\n:::\n\n```{.r .cell-code}\nB_lal <- 10\nn_syn_lal <- 2000\n\nmethods <- c(\"Frengression\", \"npcausal\", \"TMLE\", \"DoubleML\")\nate_mat_lal <- matrix(NA, nrow = B_lal, ncol = length(methods),\n                       dimnames = list(NULL, methods))\nse_mat_lal  <- ate_mat_lal\ncover_mat_lal <- ate_mat_lal\n\nSL.lib_fast <- c(\"SL.glm.interaction\", \"SL.ranger\", \"SL.mean\")\n\nset.seed(2024)\nfor (b in seq_len(B_lal)) {\n  syn <- sample_joint(model_lal_bench, sample_size = n_syn_lal)\n\n  x_syn <- as.numeric(syn$x)\n  y_syn <- as.numeric(syn$y)\n  z_syn <- as.data.frame(syn$z)\n  colnames(z_syn) <- paste0(\"z\", 1:ncol(z_syn))\n  df_syn <- cbind(data.frame(A = x_syn, Y = y_syn), z_syn)\n\n  # --- Frengression ---\n  tryCatch({\n    mod_f <- frengression(x_dim = 1, y_dim = 1, z_dim = ncol(z_syn),\n                          x_binary = TRUE, y_binary = FALSE,\n                          noise_dim = 10, hidden_dim = 100, num_layer = 3)\n    mod_f <- train_y(mod_f, matrix(x_syn, ncol=1), as.matrix(z_syn),\n                     matrix(y_syn, ncol=1),\n                     num_iters = 500, lr = 1e-3, silent = TRUE)\n    mod_f <- train_xz(mod_f, matrix(x_syn, ncol=1), as.matrix(z_syn),\n                       num_iters = 500, lr = 1e-4, silent = TRUE)\n\n    y1_f <- predict(mod_f, matrix(1, ncol=1), type=\"mean\", nsample=1000)\n    y0_f <- predict(mod_f, matrix(0, ncol=1), type=\"mean\", nsample=1000)\n    ate_mat_lal[b, \"Frengression\"] <- y1_f - y0_f\n\n    ate_mc <- replicate(100, {\n      predict(mod_f, matrix(1,ncol=1), type=\"mean\", nsample=200) -\n        predict(mod_f, matrix(0,ncol=1), type=\"mean\", nsample=200)\n    })\n    se_mat_lal[b, \"Frengression\"] <- sd(ate_mc)\n    ci_f <- ate_mat_lal[b, \"Frengression\"] + c(-1,1) * 1.96 * se_mat_lal[b, \"Frengression\"]\n    cover_mat_lal[b, \"Frengression\"] <- (ci_f[1] <= true_ate_lal & true_ate_lal <= ci_f[2])\n  }, error = function(e) message(\"Frengression failed on rep \", b, \": \", e$message))\n\n  # --- npcausal ---\n  tryCatch({\n    fit_np <- ate(y = y_syn, a = x_syn, x = z_syn,\n                  nsplits = 2, sl.lib = SL.lib_fast)\n    ate_mat_lal[b, \"npcausal\"] <- fit_np$res$est[3]\n    se_mat_lal[b, \"npcausal\"]  <- fit_np$res$se[3]\n    ci <- c(fit_np$res$ci.ll[3], fit_np$res$ci.ul[3])\n    cover_mat_lal[b, \"npcausal\"] <- (ci[1] <= true_ate_lal & true_ate_lal <= ci[2])\n  }, error = function(e) message(\"npcausal failed on rep \", b, \": \", e$message))\n\n  # --- TMLE ---\n  tryCatch({\n    fit_tmle <- tmle(Y = y_syn, A = x_syn, W = z_syn, family = \"gaussian\",\n                     Q.SL.library = SL.lib_fast, g.SL.library = SL.lib_fast)\n    ate_mat_lal[b, \"TMLE\"] <- fit_tmle$estimates$ATE$psi\n    se_mat_lal[b, \"TMLE\"]  <- sqrt(fit_tmle$estimates$ATE$var.psi)\n    ci_t <- fit_tmle$estimates$ATE$CI\n    cover_mat_lal[b, \"TMLE\"] <- (ci_t[1] <= true_ate_lal & true_ate_lal <= ci_t[2])\n  }, error = function(e) message(\"TMLE failed on rep \", b, \": \", e$message))\n\n  # --- DoubleML ---\n  tryCatch({\n    dml_d <- DoubleMLData$new(df_syn, y_col = \"Y\", d_cols = \"A\",\n                               x_cols = colnames(z_syn))\n    lr_l <- lrn(\"regr.ranger\", num.trees = 300, max.depth = 5, min.node.size = 2)\n    lr_m <- lr_l$clone()\n    dml_obj <- DoubleMLPLR$new(dml_d, ml_l = lr_l, ml_m = lr_m)\n    dml_obj$fit()\n    ate_mat_lal[b, \"DoubleML\"] <- dml_obj$coef\n    se_mat_lal[b, \"DoubleML\"]  <- dml_obj$se\n    ci_d <- c(dml_obj$confint()[1], dml_obj$confint()[2])\n    cover_mat_lal[b, \"DoubleML\"] <- (ci_d[1] <= true_ate_lal & true_ate_lal <= ci_d[2])\n  }, error = function(e) message(\"DoubleML failed on rep \", b, \": \", e$message))\n\n  if (b %% 5 == 0) cat(\"Completed replication\", b, \"of\", B_lal, \"\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCompleted replication 5 of 10 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCompleted replication 10 of 10 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbench_lal <- data.frame(\n  Method = colnames(ate_mat_lal),\n  Mean_ATE = colMeans(ate_mat_lal, na.rm = TRUE),\n  Bias = colMeans(ate_mat_lal, na.rm = TRUE) - true_ate_lal,\n  SD = apply(ate_mat_lal, 2, sd, na.rm = TRUE),\n  RMSE = sqrt(colMeans((ate_mat_lal - true_ate_lal)^2, na.rm = TRUE)),\n  Mean_SE = colMeans(se_mat_lal, na.rm = TRUE),\n  Coverage_95 = colMeans(cover_mat_lal, na.rm = TRUE),\n  N_valid = colSums(!is.na(ate_mat_lal))\n)\n\nkable(bench_lal, digits = 4,\n      caption = paste0(\"LaLonde-Based Benchmarking (B=\", B_lal,\n                       \", n=\", n_syn_lal,\n                       \", True ATE=\", round(true_ate_lal, 4),\n                       \" [\", round(true_ate_lal * sd(y_lal), 0), \" dollars])\"))\n```\n\n::: {.cell-output-display}\n\n\nTable: LaLonde-Based Benchmarking (B=10, n=2000, True ATE=0.2846 [2126 dollars])\n\n|             |Method       | Mean_ATE|    Bias|     SD|   RMSE| Mean_SE| Coverage_95| N_valid|\n|:------------|:------------|--------:|-------:|------:|------:|-------:|-----------:|-------:|\n|Frengression |Frengression |   0.2381| -0.0465| 0.0911| 0.0982|  0.1058|         0.9|      10|\n|npcausal     |npcausal     |  -0.0071| -0.2918| 0.2307| 0.3647|  0.0457|         0.0|      10|\n|TMLE         |TMLE         |   0.3218|  0.0372| 0.3674| 0.3506|  0.0281|         0.3|      10|\n|DoubleML     |DoubleML     |   0.0371| -0.2475| 0.0345| 0.2496|  0.0655|         0.0|      10|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nate_long_lal <- as.data.frame(ate_mat_lal) |>\n  pivot_longer(everything(), names_to = \"Method\", values_to = \"ATE\") |>\n  filter(!is.na(ATE))\n\nq_bounds_lal <- quantile(ate_long_lal$ATE, c(0.02, 0.98), na.rm = TRUE)\nate_long_lal_trim <- ate_long_lal |>\n  filter(ATE >= q_bounds_lal[1] & ATE <= q_bounds_lal[2])\n\nggplot(ate_long_lal_trim, aes(x = Method, y = ATE, fill = Method)) +\n  geom_boxplot(alpha = 0.7) +\n  geom_hline(yintercept = true_ate_lal, linetype = \"dashed\", color = \"red\",\n             linewidth = 1) +\n  annotate(\"text\", x = 0.5, y = true_ate_lal, label = \"True ATE\",\n           hjust = 0, vjust = -0.5, color = \"red\") +\n  labs(title = \"ATE Estimates: LaLonde-Based Frengression DGP\",\n       subtitle = paste0(\"B=\", B_lal, \" replications, n=\", n_syn_lal,\n                         \" per dataset (confounding learned from real data)\"),\n       y = \"Estimated ATE (standardized)\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![ATE Estimates from LaLonde-Based Synthetic Data](frengression_files/figure-html/lalonde_plot-1.png){width=672}\n:::\n:::\n\n\nThe numbers are stark. On the hand-written DGP (true ATE 0.0662), frengression\nhas a bias of 0.0013 and 100% coverage, DoubleML 0.0066 and 100%, while npcausal\nis off by 0.1532 with 40% coverage and TMLE by 0.2207 with 10%. On the\nLaLonde-generated data (true ATE 0.2846), frengression has a bias of $-0.0465$\nwith 90% coverage, while npcausal is off by $-0.2918$ with **0%** coverage and\nTMLE by 0.0372 with 30%.\n\nRead the coverage column rather than the bias column. A method whose interval\ncovers the truth in 0 or 1 of 10 replications is not merely imprecise; its\nreported standard error is wrong. TMLE's mean SE on the simulated benchmark is\n0.0187 against an actual sampling SD of 0.2401 — understating the uncertainty by\nmore than a factor of ten.\n\nOne caveat before drawing conclusions: $B = 10$ replications is a very small\nMonte Carlo, so these coverage rates carry a standard error of about 0.15\nthemselves. The qualitative ordering is clear; the individual percentages are\nnot precise.\n\nThe semiparametric methods show more bias on the LaLonde-generated data than on the hand-written simulation. That is the point of this exercise. The synthetic data has a more realistic propensity surface and prior-earnings distribution, so it is harder than the usual clean simulation.\n\n## Summary\n\nFrengression uses the Evans and Didelez simulation decomposition, but learns the\npieces nonparametrically. The practical use is not that it beats TMLE or AIPW\nfor a simple ATE. The practical use is that it can learn a realistic\nobservational distribution, let us impose a known causal effect, and then\ngenerate synthetic data where the truth is known.\n\nThat makes it useful for benchmarking. The simulation is still artificial, but\nit is less artificial than writing down a clean logistic model and pretending\nthat it looks like real observational data.\n\n---\n\n<!-- see-also-footer -->\n*Systematic treatment: [Julia](https://xiangao.github.io/causal_econometrics_julia/distributional-effects.html).*\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}