{
  "hash": "bd899f87e3844405ac5f79b0c1fa1480",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Poisson model with exposure\"\ndate: \"2024-04-20\"\n---\n\n## Poisson with exposure or Poisson rate\n\nPoisson models for count data often arise when units are observed for different\nlengths of time. A hospital admission count for a patient followed for 30 days\nis not directly comparable to a count for a patient followed for 365 days. The\nnatural quantity of interest is the *rate* — admissions per unit time — not\nthe raw count.\n\nThere are three related but distinct specifications, each making a different\nassumption:\n\n**Model 1 — Poisson with offset (rate model):**\n\n$$\\log\\!\\bigl(E[Y]/t\\bigr) = \\beta_0 + \\beta_1 X$$\n\nEquivalently, $\\log E[Y] = \\beta_0 + \\beta_1 X + \\log t$, where $\\log t$ is\nincluded as a *fixed* offset (coefficient constrained to 1). This is the\nstandard exposure model: the expected count is proportional to exposure time.\n\n**Model 2 — Poisson on the ratio $Y/t$:**\n\n$$\\log\\!\\bigl(E[Y/t]\\bigr) = \\beta_0 + \\beta_1 X$$\n\nThis looks similar, but it is not equivalent to the offset model, and strictly\nspeaking $Y/t$ is **not a Poisson outcome at all**: a Poisson likelihood is\ndefined for non-negative integer counts, and the continuous ratio $Y/t$ is not\none. Because $t$ is a fixed constant for each unit, $E[Y/t] = E[Y]/t$ exactly\n(linearity of expectation), so the *conditional mean* is still log-linear in\n$X$; that is why the point estimates are often similar. But the Poisson variance\nassumption fails: $\\mathrm{Var}(Y/t) = \\lambda/t^2$, whereas the mean is\n$E[Y/t] = \\lambda/t$, so the variance is $1/t$ times the mean rather than equal to\nit. (Writing it as $\\lambda/t$ would make variance equal mean and quietly restore\nequidispersion, which is precisely what fails here.) So fitting `glm(rate ~ x, family = poisson)` is a quasi-likelihood\n*mean model* rather than a correct Poisson likelihood. If you use it, treat it\nas a workaround: weight by exposure (`weights = t`) so the implied variance is\nright, and/or use robust standard errors. The offset model (Model 1) avoids the\nissue entirely by keeping the integer count as the outcome.\n\n**Model 3 — Unconstrained log-exposure:**\n\n$$\\log E[Y] = \\beta_0 + \\beta_1 X + \\gamma \\log t$$\n\nHere $\\gamma$ is estimated from the data. If $\\hat\\gamma \\approx 1$, the\nproportionality assumption is supported. If $\\hat\\gamma < 1$, counts grow\nsub-linearly with exposure — a testable, substantive claim.\n\n## Simulation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nset.seed(42)\n\nn <- 800\n\n# Simulate a health study: count of adverse events\n# Covariate: age group (0 = younger, 1 = older)\nage_old <- rbinom(n, 1, 0.45)\n\n# Exposure: days under observation (varies 7–365)\nexposure <- sample(seq(7, 365, by = 7), n, replace = TRUE)\n\n# True model: rate = exp(-3 + 1.2 * age_old)\n# Count ~ Poisson(rate * exposure)\ntrue_rate <- exp(-3 + 1.2 * age_old)\ncount <- rpois(n, lambda = true_rate * exposure)\n\ndf <- data.frame(count, age_old, exposure, log_exposure = log(exposure))\nsummary(df[, c(\"count\", \"exposure\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     count          exposure    \n Min.   : 0.00   Min.   :  7.0  \n 1st Qu.: 7.00   1st Qu.:112.0  \n Median :13.00   Median :196.0  \n Mean   :18.95   Mean   :192.9  \n 3rd Qu.:27.00   3rd Qu.:281.8  \n Max.   :71.00   Max.   :364.0  \n```\n\n\n:::\n:::\n\n\nThe data has a wide range of exposure times, so ignoring them would badly\nconfound the comparison between age groups.\n\n## Fitting the three models\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 1: offset — coefficient on log(exposure) constrained to 1\nm1 <- glm(count ~ age_old + offset(log(exposure)),\n          family = poisson, data = df)\n\n# Model 2: Poisson on the rate Y/t (different response)\ndf$rate <- df$count / df$exposure\nm2 <- glm(rate ~ age_old,\n          family = poisson, data = df)\n\n# Model 3: log(exposure) as a free covariate\nm3 <- glm(count ~ age_old + log_exposure,\n          family = poisson, data = df)\n\n# Collect coefficients\nresults <- data.frame(\n  Model = c(\"1. Offset (constrained γ=1)\",\n            \"2. Rate Y/t as response\",\n            \"3. Unconstrained log(t)\"),\n  Intercept = c(coef(m1)[1], coef(m2)[1], coef(m3)[1]),\n  age_old   = c(coef(m1)[2], coef(m2)[2], coef(m3)[2]),\n  gamma_log_t = c(1, NA, coef(m3)[3])\n)\n\nknitr::kable(results, digits = 3,\n  caption = \"Coefficient estimates: true intercept = −3, true age effect = 1.2, true γ = 1\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Coefficient estimates: true intercept = −3, true age effect = 1.2, true γ = 1\n\n|Model                       | Intercept| age_old| gamma_log_t|\n|:---------------------------|---------:|-------:|-----------:|\n|1. Offset (constrained γ=1) |    -3.009|   1.212|       1.000|\n|2. Rate Y/t as response     |    -2.980|   1.176|          NA|\n|3. Unconstrained log(t)     |    -2.801|   1.212|       0.962|\n\n\n:::\n:::\n\n\n**Reading the table:** Model 1 and Model 3 give nearly identical age-group\ncoefficients because the true $\\gamma = 1$ (counts are indeed proportional to\nexposure time). Model 2 differs slightly in the intercept because the response\nvariable changes. The estimated $\\hat\\gamma$ from Model 3 should be close to 1.\n\n## When $\\gamma \\ne 1$\n\nTo see why the unconstrained model matters, repeat the simulation with a\nsub-linear count process ($\\gamma = 0.6$: an initial burst of events that\ndoesn't grow proportionally with long follow-up):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncount2 <- rpois(n, lambda = true_rate * exposure^0.6)\ndf2 <- data.frame(count2, age_old, exposure, log_exposure = log(exposure))\n\nm1b <- glm(count2 ~ age_old + offset(log(exposure)),\n           family = poisson, data = df2)\nm3b <- glm(count2 ~ age_old + log_exposure,\n           family = poisson, data = df2)\n\ncat(\"Offset model age coefficient:      \", round(coef(m1b)[2], 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOffset model age coefficient:       1.171 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Unconstrained model age coefficient:\", round(coef(m3b)[2], 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nUnconstrained model age coefficient: 1.168 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Estimated gamma (log-exposure):    \", round(coef(m3b)[3], 3),\n    \" (true = 0.6)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEstimated gamma (log-exposure):     0.566  (true = 0.6)\n```\n\n\n:::\n:::\n\n\nTwo things to read off this, and the first is not what one might expect.\n\nThe offset model's age coefficient (1.171) and the unconstrained model's (1.168)\nare essentially the same, and both sit just below the true 1.2. Forcing\n$\\gamma = 1$ when the truth is 0.6 does **not** bias the treatment coefficient\nhere --- and the reason is structural: `exposure` is drawn by `sample(...)`\nindependently of `age_old`, so the misspecified exposure elasticity is absorbed by\nthe intercept and cannot contaminate a coefficient on a covariate orthogonal to\nit. The constraint would bite if exposure were *correlated* with the covariate of\ninterest --- for instance if older patients were systematically followed longer,\nwhich is common in real cohort data and is the case worth worrying about.\n\nWhat the unconstrained model does buy, unambiguously, is $\\gamma$ itself: it\nrecovers $\\hat\\gamma = 0.566$ against a truth of 0.6, whereas the offset model\ncannot report it at all because it fixes it at 1. So Model 3's role is diagnostic\n--- it tells you whether the proportionality assumption holds --- rather than\nprotective of the treatment estimate.\n\n## Stata equivalent\n\n```stata\n* Model 1: offset\npoisson count age_old, exposure(exposure)\n\n* Model 2: rate as response\ngen rate = count / exposure\n* Stata will warn that the dependent variable is non-integer (poisson expects\n* integer counts by default) -- this is expected and can be ignored here,\n* since Poisson QMLE is valid for continuous non-negative outcomes too.\npoisson rate age_old\n\n* Model 3: unconstrained log(t)\ngen log_exposure = log(exposure)\npoisson count age_old log_exposure\n```\n\n## Which model to use?\n\n| Situation | Recommended model |\n|---|---|\n| Counts grow proportionally with time | Model 1 (offset) |\n| Uncertain about proportionality | Model 3 (unconstrained), test $\\hat\\gamma = 1$ |\n| Rate is the natural estimand | Model 1 (offset) — it estimates a rate directly; Model 2 only as a weighted/robust quasi-model |\n| Long follow-up with declining event rate | Model 3 or negative binomial with offset |\n\nIn most health and social-science applications, Model 1 (Poisson with offset)\nis the default. Model 3 is the diagnostic check: fit it, look at $\\hat\\gamma$,\nand return to Model 1 if the constraint is supported by the data.\n\n---\n\n<!-- see-also-footer -->\n*Systematic treatment: [R](https://xiangao.github.io/causal_econometrics_guide/poisson-iv.html) · [Julia](https://xiangao.github.io/causal_econometrics_julia/poisson-iv.html).*\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}