{
  "hash": "e46769b50ccc0cc960acfab9b94efa9e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Conjoint design and analysis using R\"\ndate: \"2024-08-08\"\n---\n\n\nThis post is to illustrate how to use R to do basic conjoint analysis.  \n\n## Conjoint Analysis\n\nMarketing people used to use Sawtooth to do conjoint analysis.\n\nWhat is conjoint analysis?  Here is the intro from Sawtooth:\n\n\"Conjoint analysis methods use statistical analysis to compute mathematical representations of survey respondents’ preferences for product features, simulate how attribute changes affect demand, and even predict market acceptance of new products before they launch.\n\nThis powerful research methodology has become very popular with market researchers and economists for the valuable insight that few other research methods can provide.\"\n\n\"Consider the task of purchasing a new vehicle.\n\nWhen searching for the “right” vehicle, you typically consider a multitude of variables: type, make (brand), model, year, mileage, price, color, accessories packages, etc. You can see how this is a complex choice to make.\n\nHow does anyone possibly make such a complicated decision?\n\nYou think about what features matter most to you and then make tradeoffs.\n\nFor example, one vehicle could be an acceptable make and model, but at a high price point, whereas a second option is not the ideal make and model but has a more palatable price.\n\nThe tradeoff in this simple example is whether the make and model is more preferable to a reasonable price, or vice versa.\n\nA conjoint survey captures the relationship between different attributes of a product and how preferable they are both comparatively and when combined.\n\nBecause of this, conjoint analysis is the gold standard solution for testing multiple features simultaneously, when limited A/B testing doesn’t go far enough.\"\n\n\"In simple terms, the conjoint survey design algorithm generates a balanced survey design with product profiles, also known as concepts, formulated to have ideal statistical properties (such as level balance and independence of attributes).\n\nEach profile is made up of multiple conjoined product features (hence, conjoint analysis), such as brand, type, engine, and color, each with systematically varied levels.\n\nThese product concepts are then included in a series of questions, usually 8-20, called choice tasks, that make up the conjoint analysis portion of the survey.\"\n\n\n\n## Example\n\nThe example uses the tea data that ships with the `conjoint` package\n(Bak and Bartłomowicz). A hundred respondents rate 13 tea profiles on a\nscale from 0 to 10. Each profile combines four attributes: price (low, medium,\nhigh), variety (black, green, red), kind (bags, granulated, leafy) and aroma\n(yes, no).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(conjoint)\n\ndata(tea)   # tprof: the 13 profiles; tprefm: 100 x 13 ratings; tlevn: level names\n\nlevels_list <- list(price   = c(\"low\", \"medium\", \"high\"),\n                    variety = c(\"black\", \"green\", \"red\"),\n                    kind    = c(\"bags\", \"granulated\", \"leafy\"),\n                    aroma   = c(\"yes\", \"no\"))\n\nprofiles <- tprof\nprofiles[] <- Map(function(x, l) factor(l[x], levels = l), tprof, levels_list)\n\ntea_long <- tibble(respondent = rep(1:100, each = 13),\n                   profile    = rep(1:13, times = 100),\n                   rating     = as.vector(t(tprefm))) |>\n  bind_cols(profiles[rep(1:13, times = 100), ])\n\ntea_long\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,300 × 7\n   respondent profile rating price  variety kind       aroma\n *      <int>   <int>  <int> <fct>  <fct>   <fct>      <fct>\n 1          1       1      8 high   black   bags       yes  \n 2          1       2      1 low    green   bags       yes  \n 3          1       3      1 medium green   granulated yes  \n 4          1       4      3 medium black   leafy      yes  \n 5          1       5      9 high   red     leafy      yes  \n 6          1       6      2 medium black   bags       no   \n 7          1       7      7 high   green   bags       no   \n 8          1       8      2 medium red     bags       no   \n 9          1       9      2 high   black   granulated no   \n10          1      10      2 low    red     granulated no   \n# ℹ 1,290 more rows\n```\n\n\n:::\n:::\n\n\nThe data are 1,300 rows, 100 respondents times 13 profiles.\n\n## Conjoint design of experiment\n\nWith three, three, three and two levels, the full factorial has\n$3 \\times 3 \\times 3 \\times 2 = 54$ profiles. Asking every respondent to rate 54\nteas is too much, so a conjoint study shows a fraction of them. The question is\nwhich fraction. A good design lets us estimate the effect of every attribute\nlevel, with little correlation between the attributes.\n\n`AlgDesign` searches for such designs. `optFederov()` picks the subset of the\nfull factorial that maximizes the determinant of the information matrix for a\nmain-effects model, the D-optimality criterion. A main-effects model here has 8\nparameters, an intercept plus $2 + 2 + 2 + 1$ level contrasts, so a design needs\nat least 8 profiles. We search for designs of several sizes and report their\nD-efficiency [@kuhfeld-1994] and whether every level appears equally often.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(AlgDesign)\n\nfull <- expand.grid(lapply(levels_list, factor))\n\nset.seed(123)\ndesigns <- map(c(9, 12, 13, 18, 27, 54),\n               \\(n) optFederov(~ ., data = full, nTrials = n, criterion = \"D\"))\n\ntibble(trials       = c(9, 12, 13, 18, 27, 54),\n       D_efficiency = map_dbl(designs, \"Dea\"),\n       balanced     = map_lgl(designs, \\(d) all(map_lgl(d$design,\n                                     \\(f) length(unique(table(f))) == 1))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  trials D_efficiency balanced\n   <dbl>        <dbl> <lgl>   \n1      9        0.146 FALSE   \n2     12        0.779 TRUE    \n3     13        0.67  FALSE   \n4     18        1     TRUE    \n5     27        0.969 FALSE   \n6     54        1     TRUE    \n```\n\n\n:::\n:::\n\n\nD-efficiency measures how much information a design carries per profile,\nrelative to an ideal orthogonal design. A design with efficiency 0.8 needs about\n25% more observations to give the same standard errors as one with\nefficiency 1. Balance requires a number of profiles divisible by 3 and by 2.\nAmong these sizes, only 12, 18 and 54 are balanced. The 18-profile design reaches\nan efficiency of 1: it is an orthogonal main-effects design, a third of the full\nfactorial with nothing lost for a main-effects model.\n\nThe tea study used 13 profiles. That number cannot be balanced, and the\ndesign shows it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmap(profiles, table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$price\n\n   low medium   high \n     3      5      5 \n\n$variety\n\nblack green   red \n    5     5     3 \n\n$kind\n\n      bags granulated      leafy \n         5          3          5 \n\n$aroma\n\nyes  no \n  5   8 \n```\n\n\n:::\n\n```{.r .cell-code}\nX <- model.matrix(~ price + variety + kind + aroma, profiles)[, -1]\nround(cor(X), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               pricemedium pricehigh varietygreen varietyred kindgranulated\npricemedium           1.00     -0.62         0.02      -0.06          -0.06\npricehigh            -0.62      1.00         0.02      -0.06          -0.06\nvarietygreen          0.02      0.02         1.00      -0.43          -0.06\nvarietyred           -0.06     -0.06        -0.43       1.00           0.13\nkindgranulated       -0.06     -0.06        -0.06       0.13           1.00\nkindleafy             0.02      0.02         0.02      -0.06          -0.43\naromano              -0.02     -0.02        -0.02       0.06           0.06\n               kindleafy aromano\npricemedium         0.02   -0.02\npricehigh           0.02   -0.02\nvarietygreen        0.02   -0.02\nvarietyred         -0.06    0.06\nkindgranulated     -0.43    0.06\nkindleafy           1.00   -0.02\naromano            -0.02    1.00\n```\n\n\n:::\n:::\n\n\nLow price and red variety appear 3 times, while other levels appear 5 times,\nand aroma is \"no\" in 8 of the 13 profiles. The correlations between dummies of\nthe *same* attribute, such as $-0.62$ for medium and high price, come from the\ncoding and are expected. What matters is the correlation *between* attributes,\nand it stays small: the largest is 0.13, between red variety and granulated\nkind. The attributes are close to independent, so each attribute's effect can be\nestimated without much contamination from the others.\n\n## Conjoint analysis\n\nThe part-worths are the coefficients of a regression of the rating on attribute\ndummies. Each respondent rates 13 profiles, so the ratings are clustered by\nrespondent, and the standard errors have to allow for that.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sandwich)\nlibrary(lmtest)\n\npartworths_lm <- lm(rating ~ price + variety + kind + aroma, data = tea_long)\ncoeftest(partworths_lm, vcov = vcovCL(partworths_lm, cluster = ~ respondent))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n               Estimate Std. Error t value  Pr(>|t|)    \n(Intercept)     4.95614    0.25090 19.7538 < 2.2e-16 ***\npricemedium    -0.38334    0.18135 -2.1139  0.034717 *  \npricehigh      -0.33734    0.23621 -1.4282  0.153483    \nvarietygreen   -0.58000    0.25521 -2.2727  0.023210 *  \nvarietyred     -1.26466    0.25189 -5.0206 5.870e-07 ***\nkindgranulated -1.02666    0.10561 -9.7216 < 2.2e-16 ***\nkindleafy       0.61600    0.22559  2.7306  0.006407 ** \naromano        -0.82155    0.17027 -4.8250 1.567e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe baseline profile is low-priced black tea in bags with aroma. Relative to it,\nred tea lowers the rating by 1.26 points and green tea by 0.58. Granulated tea\nlowers it by 1.03, while leafy tea raises it by 0.62. Tea without aroma is rated\n0.82 lower. Price matters least: medium and high prices lower the rating by about\n0.35, and only the medium-price contrast is significant at 5%.\n\nConjoint software usually reports part-worths in effect coding, where the\npart-worths of each attribute sum to zero. They are the same coefficients,\nre-centred within each attribute. The importance of an attribute is the range of\nits part-worths as a share of the sum of the ranges.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npart_worths <- imap_dfr(levels_list, \\(lv, attr) {\n  b <- c(0, coef(partworths_lm)[paste0(attr, lv[-1])])\n  tibble(attribute = attr, level = factor(lv, levels = lv), part_worth = b - mean(b))\n})\n\nimportance <- part_worths |>\n  group_by(attribute) |>\n  summarise(range = diff(range(part_worth))) |>\n  mutate(importance = round(100 * range / sum(range), 1))\nimportance\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  attribute range importance\n  <chr>     <dbl>      <dbl>\n1 aroma     0.822       20  \n2 kind      1.64        39.9\n3 price     0.383        9.3\n4 variety   1.26        30.8\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(part_worths, aes(level, part_worth)) +\n  geom_col(fill = \"darkcyan\") +\n  geom_hline(yintercept = 0) +\n  facet_wrap(~ attribute, scales = \"free_x\", nrow = 1) +\n  labs(x = NULL, y = \"Part-worth\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](conjoint-analysis_files/figure-html/unnamed-chunk-5-1.png){width=768}\n:::\n:::\n\n\nKind is the most important attribute, with 39.9% of the total range, followed by\nvariety with 30.8%, aroma with 20.0% and price with 9.3%.\n\nThe `conjoint` package computes the same quantities. Its pooled part-worths\nmatch ours exactly. Its importance figures do not, and the reason is worth\nknowing. `caImportance()` computes each respondent's importance from that\nrespondent's own part-worths, and then averages across respondents. Individual\npart-worths from 13 ratings are noisy, and noise widens every attribute's range,\nso the averaged importance spreads more evenly across attributes than the pooled\nfigure.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# conjoint's functions switch R to sum-to-zero contrasts globally and do not\n# switch back, which would break every later regression; save and restore.\nop <- options(\"contrasts\")\ninvisible(capture.output(pooled <- caUtilities(y = tprefm, x = tprof, z = tlevn)))\ninvisible(capture.output(imp <- caImportance(y = tprefm, x = tprof)))\noptions(op)\n\nround(pooled, 3)                      # intercept, then effect-coded part-worths\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  3.553  0.240 -0.143 -0.097  0.615  0.035 -0.650  0.137 -0.890  0.753\n[11]  0.411 -0.411\n```\n\n\n:::\n\n```{.r .cell-code}\nsetNames(imp, names(levels_list))     # averaged over respondents\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  price variety    kind   aroma \n  24.76   32.22   27.15   15.88 \n```\n\n\n:::\n:::\n\n\nThe averaged importances are 24.8 for price, 32.2 for variety, 27.2 for kind and\n15.9 for aroma. Price moves from least important to second. The two figures\nanswer different questions. The pooled range describes the average respondent.\nThe averaged importance describes how much each attribute matters within a\nrespondent, and it is inflated by sampling noise in the individual fits.\n\n## Causal effect in conjoint analysis\n\n@hainmueller-2014 define the average marginal component effect (AMCE): the\naverage change in the outcome when one attribute moves from one level to\nanother, averaged over the distribution of the other attributes. It is not to be\nconfused with the ACME, the average causal mediation effect of Imai et al. When\nthe attribute levels are randomized independently of each other and of the\nrespondents, the AMCE is identified, and it is estimated by the coefficients of a\nregression of the outcome on the attribute dummies. Standard errors are clustered\nby respondent. The `cjoint` package implements it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(cjoint)\n\namce_fit <- amce(rating ~ price + variety + kind + aroma, data = as.data.frame(tea_long),\n                 cluster = TRUE, respondent.id = \"respondent\")\n\nimap_dfr(amce_fit$estimates, \\(m, attr)\n  tibble(attribute = attr, level = colnames(m),\n         amce = round(m[\"AMCE\", ], 3), se = round(m[\"Std. Error\", ], 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 4\n  attribute level            amce    se\n  <chr>     <chr>           <dbl> <dbl>\n1 aroma     aromano        -0.822 0.17 \n2 kind      kindgranulated -1.03  0.106\n3 kind      kindleafy       0.616 0.226\n4 price     pricemedium    -0.383 0.181\n5 price     pricehigh      -0.337 0.236\n6 variety   varietygreen   -0.58  0.255\n7 variety   varietyred     -1.26  0.252\n```\n\n\n:::\n:::\n\n\nThe AMCEs are exactly the part-worth coefficients above, with the same clustered\nstandard errors. The tea profiles were not randomized; they are a fixed\n13-profile design. The attributes in it are close to independent, which is why\nthe regression coefficients still read as average effects of each attribute. The\ncausal reading also needs the ratings to reflect the attributes shown and nothing\nelse about the profile, and it holds only for the population of profiles the\ndesign represents.\n\n## Summary\n\nA conjoint study asks respondents to rate or choose among product profiles whose attributes vary by design. The full factorial is usually too long, so we use a fraction chosen for D-efficiency and balance. For the tea attributes, an 18-profile design is fully efficient and balanced. The study's own 13 profiles cannot be balanced, but the correlations between attributes stay below 0.13.\n\nThe analysis is a regression of the ratings on attribute dummies, with standard errors clustered by respondent. The coefficients are the part-worths. Kind and variety matter most, and price least. Importance from the pooled part-worths differs from `conjoint`'s average of individual importances, because individual fits are noisy. When attribute levels are independent, the same coefficients are Hainmueller et al.'s average marginal component effects, which `cjoint` reproduces.\n",
    "supporting": [
      "conjoint-analysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}