{
  "hash": "4873e0d6ed6e31045a895dfa31ab30fe",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Uplift Modeling and CATE\"\nauthor: \"Xiang Ao\"\ndate: \"2025-10-10\"\n---\n\nUplift modeling is about estimating who changes because of treatment. In a\nmarketing example, this means separating people who buy because of the campaign\nfrom people who would have bought anyway.\n\nThis is the same object as the conditional average treatment effect (CATE),\n$$\\tau(x) = E[Y(1) - Y(0) \\mid X = x].$$ {#eq-uplift-1}\nThe word \"uplift\" is more common in industry. The word \"CATE\" is more common in\nthe causal inference literature.\n\n## Python: causalml uplift trees\n\nThe `causalml` library (Uber) provides uplift tree classifiers and the\ncumulative gain curve for evaluating targeting policies. The code below\nfollows the library's tutorial with synthetic data.\n\nI am copying this code from <https://github.com/uber/causalml/blob/master/docs/examples/uplift_trees_with_synthetic_data.ipynb>.\n\n> The Python chunk below is shown for reading but **not executed**\n> (`eval: false`), because the render environment does not have `causalml`\n> installed. The R causal-forest section that follows it does run, and its\n> output appears below it.\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nimport pandas as pd\n\nfrom causalml.dataset import make_uplift_classification\nfrom causalml.inference.tree import UpliftRandomForestClassifier\nfrom causalml.metrics import plot_gain\n\nfrom sklearn.model_selection import train_test_split\nimport importlib\nprint(importlib.metadata.version('causalml') )\n\ndf, x_names = make_uplift_classification()\ndf.head()\n\n# Look at the conversion rate and sample size in each group\ndf.pivot_table(values='conversion',\n               index='treatment_group_key',\n               aggfunc=[np.mean, np.size],\n               margins=True)\n\n# Split data to training and testing samples for model validation (next section)\ndf_train, df_test = train_test_split(df, test_size=0.2, random_state=111)\n\nfrom causalml.inference.tree import UpliftTreeClassifier\n\nclf = UpliftTreeClassifier(control_name='control')\nclf.fit(df_train[x_names].values,\n         treatment=df_train['treatment_group_key'].values,\n         y=df_train['conversion'].values)\np = clf.predict(df_test[x_names].values)\n\ndf_res = pd.DataFrame(p, columns=clf.classes_)\ndf_res.head()\n\nuplift_model = UpliftRandomForestClassifier(control_name='control')\n\nuplift_model.fit(df_train[x_names].values,\n                 treatment=df_train['treatment_group_key'].values,\n                 y=df_train['conversion'].values)\n\ndf_res = uplift_model.predict(df_test[x_names].values, full_output=True)\nprint(df_res.shape)\ndf_res.head()\n\ny_pred = uplift_model.predict(df_test[x_names].values)\n\n# Put the predictions to a DataFrame for a neater presentation\n# The output of `predict()` is a numpy array with the shape of [n_sample, n_treatment] excluding the\n# predictions for the control group.\nresult = pd.DataFrame(y_pred,\n                      columns=uplift_model.classes_[1:])\nresult.head()\n\n# If all deltas are negative, assign to control; otherwise assign to the treatment\n# with the highest delta\nbest_treatment = np.where((result < 0).all(axis=1),\n                           'control',\n                           result.idxmax(axis=1))\n\n# Create indicator variables for whether a unit happened to have the\n# recommended treatment or was in the control group\nactual_is_best = np.where(df_test['treatment_group_key'] == best_treatment, 1, 0)\nactual_is_control = np.where(df_test['treatment_group_key'] == 'control', 1, 0)\n\nsynthetic = (actual_is_best == 1) | (actual_is_control == 1)\nsynth = result[synthetic]\n\nauuc_metrics = (synth.assign(is_treated = 1 - actual_is_control[synthetic],\n                             conversion = df_test.loc[synthetic, 'conversion'].values,\n                             uplift_tree = synth.max(axis=1))\n                     .drop(columns=list(uplift_model.classes_[1:])))\n\nplot_gain(auuc_metrics, outcome_col='conversion', treatment_col='is_treated')\n```\n:::\n\n\nA caution on this evaluation. The gain curve above keeps only the units whose\n*observed* treatment happened to match the recommended treatment (or who were\ncontrols), and then compares outcomes. This is a common tutorial shortcut, but\nit estimates the value of the recommended policy **only if treatment was\nrandomly assigned** (so that \"units who happened to get the recommended arm\"\nare exchangeable with those who did not). With observational treatment\nassignment, this selection is itself confounded, and a valid off-policy\nevaluation needs an inverse-probability / policy-value estimator that reweights\nby the propensity of the observed treatment. Read the gain curve here as a\ndiagnostic under randomized assignment, not as a general off-policy evaluation.\n\n## R: causal forest for CATE\n\nIn R, the `grf` package implements causal forests. The setup is simpler than\nthe uplift tree example: provide outcomes, treatments, and covariates, and the\nforest estimates CATEs using honest splitting.\n\nWe simulate $n = 5000$ users with five independent standard normal covariates.\nTreatment is randomly assigned, $W \\sim \\text{Bernoulli}(0.5)$, so there is no\nconfounding. The true CATE is $\\tau(X) = 0.3 + 0.5X_1$ — the intervention helps\nhigh-$x_1$ users more — and the outcome is\n$Y = \\tau(X)W + X_2 + \\varepsilon$ with $\\varepsilon \\sim N(0, 0.5^2)$. The\naverage true effect is therefore 0.3, and only $x_1$ modifies it while $x_2$\naffects the outcome level and $x_3$ to $x_5$ do nothing.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(grf)\nlibrary(ggplot2)\n\n# Simulate a marketing intervention\n# True CATE: treatment helps high-engagement users more\nset.seed(123)\nn  <- 5000\nX  <- matrix(rnorm(n * 5), n, 5)\ncolnames(X) <- paste0(\"x\", 1:5)\nW  <- rbinom(n, 1, 0.5)                          # random treatment\ntau_true <- 0.3 + 0.5 * X[, 1]                   # CATE depends on x1\nY  <- tau_true * W + X[, 2] + rnorm(n, sd = 0.5) # observed outcome\n\n# Fit causal forest\ncf <- causal_forest(X, Y, W, num.trees = 2000, seed = 42)\n\n# Estimate CATE for each unit\ntau_hat <- predict(cf, estimate.variance = TRUE)\ncate    <- tau_hat$predictions\ncate_se <- sqrt(tau_hat$variance.estimates)\n\ncat(\"Mean estimated CATE:\", round(mean(cate), 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean estimated CATE: 0.307 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"True mean CATE:     \", round(mean(tau_true), 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue mean CATE:      0.3 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Who benefits? Targeting policy\n# Sort by predicted CATE, target top 30%\nthreshold <- quantile(cate, 0.70)\ntargeted  <- cate >= threshold\n\ncat(\"Average CATE in targeted group:\", round(mean(cate[targeted]), 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage CATE in targeted group: 0.858 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Average CATE in non-targeted:  \", round(mean(cate[!targeted]), 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage CATE in non-targeted:   0.071 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Variable importance: which covariates drive heterogeneity?\n# variable_importance() returns a one-column matrix, so drop() it to a vector --\n# otherwise barplot() draws a single bar and rejects the five names.\nimp <- drop(variable_importance(cf))\nbarplot(imp, names.arg = colnames(X),\n        main = \"Variable importance for CATE\",\n        ylab = \"Importance\")\n```\n\n::: {.cell-output-display}\n![](uplift_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Omnibus test: is there significant CATE heterogeneity?\ntest_calibration(cf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBest linear fit using forest predictions (on held-out data)\nas well as the mean forest prediction as regressors, along\nwith one-sided heteroskedasticity-robust (HC3) SEs:\n\n                               Estimate Std. Error t value    Pr(>t)    \nmean.forest.prediction         0.999033   0.046573  21.451 < 2.2e-16 ***\ndifferential.forest.prediction 1.041590   0.031644  32.916 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe forest gives a mean estimated CATE of 0.307 against the true 0.300. Sorting\non the estimate, the targeted group averages a true CATE of 0.858 and the\nnon-targeted group 0.071 — a twelvefold separation, which is what makes the\ntargeting worth doing rather than treating everyone.\n\nThe `test_calibration()` output is a useful diagnostic. It checks whether units\nwith higher predicted CATEs also appear to have higher treatment effects.\n\n## Uplift vs CATE: the same thing with different vocabulary\n\n| Uplift term | Causal inference term |\n|---|---|\n| Uplift score | $\\hat\\tau(x)$ — estimated CATE |\n| Persuadables | Units with $\\tau(x) > 0$ |\n| Do-not-disturbs | Units with $\\tau(x) < 0$ |\n| Cumulative gain curve | Policy value curve / AUTOC |\n| Uplift tree | Causal tree / honest tree |\n| Uplift forest | Causal forest (grf) |\n\nThe Python `causalml` package comes from the marketing/tech vocabulary. `grf`\ncomes from the econometrics vocabulary. They are trying to estimate the same\nquantity. For publication, I would usually want the inference and diagnostics\nfrom `grf`. For a targeting exercise, the gain-curve tools in `causalml` are\nalso useful.\n\n---\n\n<!-- see-also-footer -->\n*Systematic treatment: [R](https://xiangao.github.io/causal_econometrics_guide/heterogeneous-effects.html) · [Julia](https://xiangao.github.io/causal_econometrics_julia/heterogeneous-effects.html).*\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}