<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="dcterms.date" content="2026-07-24">
<title>48&nbsp; Pre-registration, TOST, and why Bayes doesn’t let you skip the hard part – Topics on econometrics and causal inference</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./numpyro.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6eb2a311e0ae5a9b436ea9f7e52955e6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script>
try {
  if (window.localStorage) {
    window.localStorage.setItem("quarto-reader-mode", "false");
  }
} catch (e) {}
</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="style.css">
</head>
<body class="nav-sidebar floating fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./multilevel-models.html">Advanced Topics</a></li><li class="breadcrumb-item"><a href="./equivalence-testing.html"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Pre-registration, TOST, and why Bayes doesn’t let you skip the hard part</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Topics on econometrics and causal inference</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://xiangao.github.io/" title="Xiang Ao home" class="quarto-navigation-tool px-1" aria-label="Xiang Ao home"><i class="bi bi-house-door-fill"></i></a>
    <a href="https://xiangao.github.io/books.html" title="Other books" class="quarto-navigation-tool px-1" aria-label="Other books"><i class="bi bi-book"></i></a>
    <a href="https://github.com/xiangao/blog_book/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Regression Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./interaction-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Interpreting interaction in a regression model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./interaction-nonlinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Interaction term in a non-linear model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chow-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Chow test and more</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./weights-ols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Weights in OLS in causal inference</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Marginal Effects &amp; Fixed Effects</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./marginal-effects-fe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Marginal effects in models with fixed effects</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./comparing-margins.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Comparing Marginal effects with margins command</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fixed-random-effect.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Fixed or Random Effect, or Both?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mundlak-device.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Mundlak device in fixed effect models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlated-random-effect.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Correlated Random Effect</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./more-cre.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">More on Correlated Random Effect (CRE)</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Treatment Effects &amp; Matching</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./treatment-matching.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Treatment effects and matching</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ols-ate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">When is OLS coefficient the ATE</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./matching-part1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Matching and Weighting Part 1: matching</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./weighting-part2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Matching and Weighting - Part 2: weighting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sensitivity-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Sensitivity analysis of OLS with sensemakr</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./gwg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Gender Wage Gap Analysis Using US Current Population Survey Data</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Panel Data &amp; DiD</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal-forest-panel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Causal Forest in panel data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./synthetic-control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Synthetic Control in R and Stata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tasc-time-aware-synthetic-control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Same Data, Different Estimators: A Synthetic Control Comparison</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bartik-instrument.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Bartik Instrument and Rotemberg weights</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./extended-twfe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Extended TWFE and other DiD estimators</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal-panel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Causal Panel (why DDDiD)</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Count Data &amp; Specialized Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Which count data model to use</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rare-events.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">What model to use for rare events</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./poisson-exposure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Poisson model with exposure</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./poisson-iv-fe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">IV in Fixed effect Poisson with many fixed effects</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Causal Inference Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tmle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Using machine learning for causal effect in observational study</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mediation-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Mediation analysis in R and Stata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bunching.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Endogeneity with censored variable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./g-estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">G-computation (g-formula) with time varying covariates</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./policytree.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Policy learning by policytree</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./npcausal-tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Recent causal inference tools</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./proximal-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Intro to proximal causal inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./proximal-simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Simulation on proximal causal inference with panel data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lmtp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">longitudinal modified treatment policy (LMTP)</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Advanced Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multilevel-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Doing the same multi-level model with R and stata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./likert-scale-variance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Modeling variation, not just the mean, in Likert-scale data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conjoint-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Conjoint design and analysis using R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stata-cate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Stata 19 CATE command</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./spatial-econometrics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Spatial econometrics introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal-simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Causal simulation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./frengression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Frengression and Engression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./partial-interference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Partial Interference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./power-list-experiment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Power analysis with list experiment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal-mediation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Causal mediation analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uplift.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Uplift Modeling and CATE</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./numpyro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Using Numpyro</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./equivalence-testing.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Pre-registration, TOST, and why Bayes doesn’t let you skip the hard part</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./multilevel-models.html">Advanced Topics</a></li><li class="breadcrumb-item"><a href="./equivalence-testing.html"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Pre-registration, TOST, and why Bayes doesn’t let you skip the hard part</span></a></li></ol></nav><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">
<span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Pre-registration, TOST, and why Bayes doesn’t let you skip the hard part</span>
</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 24, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header><section id="why-this-came-up" class="level2" data-number="48.1"><h2 data-number="48.1" class="anchored" data-anchor-id="why-this-came-up">
<span class="header-section-number">48.1</span> Why this came up</h2>
<p>A colleague asked me to look over the analysis plan for a paper being submitted as a Registered Report (RR). Three of the hypotheses were the interesting kind: the authors expected an effect, but part of what they wanted to claim was that a <em>moderator</em> of that effect was absent, or negligible, in some subgroup. The draft’s plan was to run the usual test, and if it came back non-significant, report that as evidence the moderator doesn’t matter. If the data looked non-normal, switch to a different test. That doesn’t work, and working out exactly why turned into this post.</p>
</section><section id="what-pre-registration-is-actually-for" class="level2" data-number="48.2"><h2 data-number="48.2" class="anchored" data-anchor-id="what-pre-registration-is-actually-for">
<span class="header-section-number">48.2</span> What pre-registration is actually for</h2>
<p>Strip away the jargon and pre-registration does one thing: it makes you commit, in writing, before you see the data, to exactly which analysis you’ll run and how you’ll interpret every possible result it could produce. Not “we’ll run a sensible test” — the specific test, the specific decision rule for what counts as support, what counts as a null, what counts as inconclusive.</p>
<p>The reason this matters is not really about honesty in the moment you write the paper. It’s about closing off every place where a result could quietly steer your choice of method. If you look at your data, notice it’s non-normal, and <em>then</em> decide to switch from a <span class="math inline">\(t\)</span>-test to a Wilcoxon test, you’ve let the data pick the analysis — and the two tests won’t always agree, so which one you end up reporting is no longer independent of what answer it gives you. Same story if you pick your significance threshold, your covariates, or your equivalence bound after peeking. None of this requires bad faith. It’s enough that a result you don’t love makes you reach for a “more appropriate” method you wouldn’t have reached for otherwise. Pre-registration’s whole job is to make that impossible: the method is fixed before the data exists to influence it.</p>
<p>Registered Reports push this further than ordinary pre-registration. The journal grants <em>in-principle acceptance</em> of the design before any data are collected, and commits to publishing the paper whatever the result turns out to be. That’s a stronger guarantee than “I promised myself I wouldn’t switch methods” — the switch is now also unavailable in practice, because the paper’s fate no longer depends on which result you got.</p>
<p>But that guarantee creates an obligation of its own. If the journal must publish the paper regardless of outcome, and the outcome is a null result, the null has to actually mean something — otherwise the journal has committed to publishing noise. The Registered Reports template maintained by the Center for Open Science, which the journals running the format adopt close to word for word, makes this a ground for desk rejection outright. Among the listed reasons a Stage 1 submission gets turned away:</p>
<blockquote class="blockquote">
<p>Intention to infer support for the null hypothesis from statistically non-significant results, without proposing use of Bayes factors or frequentist equivalence testing (e.g., Lakens, Scheel &amp; Isager, 2018).</p>
</blockquote>
<p>The same list attaches a power requirement that people don’t always expect:</p>
<blockquote class="blockquote">
<p>Proposals should be powered to detect the smallest effect that is plausible and of theoretical value. Pilot data can help inform this estimate but is unlikely to form an acceptable basis, alone, for choosing the target effect size.</p>
</blockquote>
<p>and the accompanying author guidelines set the floor: “For frequentist analysis plans, the a priori power must be 0.9 or higher for all proposed hypothesis tests.” Individual journals tighten that — Nature Human Behaviour requires 0.95. I’ll come back to why the phrasing about pilot data matters.</p>
</section><section id="a-non-significant-result-is-not-no-effect" class="level2" data-number="48.3"><h2 data-number="48.3" class="anchored" data-anchor-id="a-non-significant-result-is-not-no-effect">
<span class="header-section-number">48.3</span> A non-significant result is not “no effect”</h2>
<p>Ordinary null hypothesis significance testing (NHST) tests <span class="math inline">\(H_0: \theta = 0\)</span> against <span class="math inline">\(H_1: \theta \neq 0\)</span>. A non-significant result (<span class="math inline">\(p &gt; 0.05\)</span>) tells you only that you couldn’t reject zero, and that has two very different possible causes:</p>
<ol type="1">
<li>the true effect really is about zero, or</li>
<li>the effect is real, but the data are too noisy or the sample too small to detect it.</li>
</ol>
<p>Both give you the same large <span class="math inline">\(p\)</span>-value, and the test itself gives you no way to tell which one you’re looking at. Here’s the reductio I keep coming back to: you could “prove” almost any effect is zero just by collecting a tiny sample. A small <span class="math inline">\(n\)</span> guarantees a wide confidence interval (CI) and non-significance, regardless of what’s actually true. A non-significant result is silence, not evidence of absence — and it’s exactly the kind of ambiguous result that invites the post-hoc-method-switching problem above, because “silence” leaves so much room for a motivated reading.</p>
</section><section id="equivalence-testing-tost-plainly" class="level2" data-number="48.4"><h2 data-number="48.4" class="anchored" data-anchor-id="equivalence-testing-tost-plainly">
<span class="header-section-number">48.4</span> Equivalence testing (TOST), plainly</h2>
<p>Equivalence testing flips the question from “is the effect exactly zero” to “can I rule out an effect large enough to matter.” You pre-specify a bound <span class="math inline">\(\Delta\)</span> — the smallest effect size of interest (SESOI), the largest effect you’d still call negligible — and run two one-sided tests (TOST):</p>
<p><span id="eq-equivalence-testing-1"><span class="math display">\[
H_{01}: \theta \le -\Delta \qquad \text{vs.} \qquad H_{02}: \theta \ge +\Delta.
\tag{48.1}\]</span></span></p>
<p>Reject both, and the effect lies inside <span class="math inline">\([-\Delta, +\Delta]\)</span>. Operationally this collapses to one check: build the <span class="math inline">\((1-2\alpha)\)</span> CI and see whether it sits entirely inside the bounds. There’s no separate machine computing something new — TOST is a decision rule wrapped around a CI you already had.</p>
<p>Notice where <span class="math inline">\(\Delta\)</span> has to come from for any of this to be worth doing: it has to be chosen <em>before</em> you see the result, for the same reason the whole test method has to be. If you’re allowed to set <span class="math inline">\(\Delta\)</span> after looking at your CI, you can always draw the bound just wide enough to swallow whatever you got — which defeats the entire point, and is really the same violation as switching from a <span class="math inline">\(t\)</span>-test to a Wilcoxon test after peeking, just one level further down.</p>
<p>Here’s a worked example using <code>mtcars</code>, purely to show the mechanics — nobody should take conclusions about 1974 cars seriously. Is the quarter-mile time (<code>qsec</code>) meaningfully different between automatic and manual transmissions?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://aaroncaldwell.us/TOSTERpkg/">TOSTER</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">mtcars</span><span class="op">)</span></span>
<span><span class="va">mtcars</span><span class="op">$</span><span class="va">am</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">mtcars</span><span class="op">$</span><span class="va">am</span>, labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"automatic"</span>, <span class="st">"manual"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">qsec</span> <span class="op">~</span> <span class="va">am</span>, data <span class="op">=</span> <span class="va">mtcars</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  qsec by am
t = 1.2878, df = 25.534, p-value = 0.2093
alternative hypothesis: true difference in means between group automatic and group manual is not equal to 0
95 percent confidence interval:
 -0.4918522  2.1381679
sample estimates:
mean in group automatic    mean in group manual 
               18.18316                17.36000 </code></pre>
</div>
</div>
<p>Not significant (<span class="math inline">\(p = 0.21\)</span>). Under plain NHST, that’s the whole story: “no evidence of a difference.” Now suppose I’d pre-specified, before looking, that anything under one second doesn’t matter (<span class="math inline">\(\Delta = 1\)</span>):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://aaroncaldwell.us/TOSTERpkg/reference/t_TOST.html">t_TOST</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">qsec</span> <span class="op">~</span> <span class="va">am</span>, data <span class="op">=</span> <span class="va">mtcars</span>, eqb <span class="op">=</span> <span class="fl">1</span>, var.equal <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Welch Two Sample t-test

The equivalence test was non-significant, t(25.53) = -0.28, p = 0.39
The null hypothesis test was non-significant, t(25.53) = 1.288, p = 0.21
NHST: don't reject null significance hypothesis that the effect is equal to zero 
TOST: don't reject null equivalence hypothesis

TOST Results 
                 t    df p.value
t-test      1.2878 25.53   0.209
TOST Lower  2.8524 25.53   0.004
TOST Upper -0.2767 25.53   0.392

Effect Sizes 
               Estimate     SE              C.I. Conf. Level
Raw              0.8232 0.6392 [-0.2678, 1.9141]         0.9
Hedges's g(av)   0.4522 0.3783 [-0.1375, 1.0342]         0.9
Note: SMD confidence intervals are an approximation. See vignette("SMD_calcs").</code></pre>
</div>
</div>
<p>TOST also fails to declare equivalence — the 90% CI is <span class="math inline">\([-0.27, 1.91]\)</span>, and it spills past <span class="math inline">\(+1\)</span>. So both the plain test and TOST agree here: the data just aren’t informative, in either direction. TOST doesn’t rescue an underpowered comparison — that’s expected, and it’s the honest answer. Now widen the bound to <span class="math inline">\(\Delta = 2\)</span>, using the exact same data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://aaroncaldwell.us/TOSTERpkg/reference/t_TOST.html">t_TOST</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">qsec</span> <span class="op">~</span> <span class="va">am</span>, data <span class="op">=</span> <span class="va">mtcars</span>, eqb <span class="op">=</span> <span class="fl">2</span>, var.equal <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Welch Two Sample t-test

The equivalence test was significant, t(25.53) = -1.8, p = 0.04
The null hypothesis test was non-significant, t(25.53) = 1.288, p = 0.21
NHST: don't reject null significance hypothesis that the effect is equal to zero 
TOST: reject null equivalence hypothesis

TOST Results 
                t    df p.value
t-test      1.288 25.53   0.209
TOST Lower  4.417 25.53 &lt; 0.001
TOST Upper -1.841 25.53   0.039

Effect Sizes 
               Estimate     SE              C.I. Conf. Level
Raw              0.8232 0.6392 [-0.2678, 1.9141]         0.9
Hedges's g(av)   0.4522 0.3783 [-0.1375, 1.0342]         0.9
Note: SMD confidence intervals are an approximation. See vignette("SMD_calcs").</code></pre>
</div>
</div>
<p>Now the CI sits entirely inside <span class="math inline">\([-2, 2]\)</span>, and TOST declares equivalence. The plain <span class="math inline">\(t\)</span>-test’s <span class="math inline">\(p\)</span>-value hasn’t moved at all — still 0.21, because it never looked at <span class="math inline">\(\Delta\)</span> in the first place. That’s the whole value of TOST in one pair of examples: NHST can’t distinguish “underpowered nonsense” from “precisely estimated and negligible,” because it never asked the second question. TOST can — but only if <span class="math inline">\(\Delta\)</span> was nailed down in advance. Run both versions after seeing the data and picking whichever looks better, and you’ve just reinvented p-hacking with extra steps.</p>
</section><section id="the-bayesian-alternative" class="level2" data-number="48.5"><h2 data-number="48.5" class="anchored" data-anchor-id="the-bayesian-alternative">
<span class="header-section-number">48.5</span> The Bayesian alternative</h2>
<p>A Bayes factor (BF) compares the marginal likelihood of the data under <span class="math inline">\(H_1\)</span> versus <span class="math inline">\(H_0\)</span>:</p>
<p><span id="eq-equivalence-testing-2"><span class="math display">\[
\text{BF}_{10} = \frac{p(\text{data} \mid H_1)}{p(\text{data} \mid H_0)}.
\tag{48.2}\]</span></span></p>
<p>Conventionally, <span class="math inline">\(\text{BF}_{10} &lt; 1/3\)</span> counts as evidence for the null, <span class="math inline">\(\text{BF}_{10} &gt; 3\)</span> for the alternative, and anything between is inconclusive. The default JZS prior puts a Cauchy distribution on the standardized effect under <span class="math inline">\(H_1\)</span>. (One asymmetry worth noting, given the theme of this post: the tests above used Welch’s correction, <code>var.equal = FALSE</code>, while <code>ttestBF</code>’s JZS model assumes equal variances. Here it makes no difference to the verdict, but it is one more incidental choice that a pre-registration should nail down rather than leave to whichever default came to hand.)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://richarddmorey.github.io/BayesFactor/">BayesFactor</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/BayesFactor/man/ttestBF.html">ttestBF</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">qsec</span> <span class="op">~</span> <span class="va">am</span>, data <span class="op">=</span> <span class="va">mtcars</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bayes factor analysis
--------------
[1] Alt., r=0.707 : 0.6401796 ±0%

Against denominator:
  Null, mu1-mu2 = 0 
---
Bayes factor type: BFindepSample, JZS</code></pre>
</div>
</div>
<p><span class="math inline">\(\text{BF}_{10} \approx 0.64\)</span>: mildly favors the null, but not by much — inconclusive by the usual thresholds. This default BF is quietly answering a different question than TOST did: it compares “no effect at all” to “some effect, of unknown size, drawn from a Cauchy prior,” not “effect inside <span class="math inline">\(\pm 2\)</span>” to “effect outside <span class="math inline">\(\pm 2\)</span>.” If you want the actual Bayesian analogue of an equivalence claim, you need an interval null.</p>
<p>One trap to clear first, and it is exactly the kind of thing this post is about. <code>TOSTER</code>’s <code>eqb</code> is in <strong>raw</strong> units — those were 2 seconds of <code>qsec</code>. <code>BayesFactor</code>’s <code>nullInterval</code> is in <strong>standardized</strong> units, Cohen’s <span class="math inline">\(d\)</span>; look at the labels it prints and you’ll see it says <code>d</code>. Handing it <code>c(-2, 2)</code> would silently test a bound of <span class="math inline">\(\pm 2\)</span> <em>standard deviations</em>, which on these data is <span class="math inline">\(\pm 3.5\)</span> seconds — nearly twice the bound I actually pre-specified, and it would make the Bayesian evidence look far stronger than it is. So the bound has to be converted before it goes in:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">grp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/split.html">split</a></span><span class="op">(</span><span class="va">mtcars</span><span class="op">$</span><span class="va">qsec</span>, <span class="va">mtcars</span><span class="op">$</span><span class="va">am</span><span class="op">)</span></span>
<span><span class="va">n1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">grp</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">)</span>; <span class="va">n2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">grp</span><span class="op">[[</span><span class="fl">2</span><span class="op">]</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="va">sd_pooled</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="op">(</span><span class="op">(</span><span class="va">n1</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">var</a></span><span class="op">(</span><span class="va">grp</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">)</span> <span class="op">+</span> <span class="op">(</span><span class="va">n2</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">var</a></span><span class="op">(</span><span class="va">grp</span><span class="op">[[</span><span class="fl">2</span><span class="op">]</span><span class="op">]</span><span class="op">)</span><span class="op">)</span> <span class="op">/</span> <span class="op">(</span><span class="va">n1</span> <span class="op">+</span> <span class="va">n2</span> <span class="op">-</span> <span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">delta_d</span> <span class="op">&lt;-</span> <span class="fl">2</span> <span class="op">/</span> <span class="va">sd_pooled</span>   <span class="co"># the same +/- 2 seconds, expressed in d units</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>sd_pooled <span class="op">=</span> <span class="va">sd_pooled</span>, delta_d <span class="op">=</span> <span class="va">delta_d</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>sd_pooled   delta_d 
 1.767842  1.131323 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/BayesFactor/man/ttestBF.html">ttestBF</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">qsec</span> <span class="op">~</span> <span class="va">am</span>, data <span class="op">=</span> <span class="va">mtcars</span>, nullInterval <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="va">delta_d</span>, <span class="va">delta_d</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bayes factor analysis
--------------
[1] Alt., r=0.707 -1.1313225176573&lt;d&lt;1.1313225176573    : 0.9813314  ±0%
[2] Alt., r=0.707 !(-1.1313225176573&lt;d&lt;1.1313225176573) : 0.02203644 ±0.03%

Against denominator:
  Null, mu1-mu2 = 0 
---
Bayes factor type: BFindepSample, JZS</code></pre>
</div>
</div>
<p>The first line is the Bayes factor for “the effect is inside <span class="math inline">\(\pm\Delta\)</span>” against the point null; the second is for “the effect is outside <span class="math inline">\(\pm\Delta\)</span>.” Their ratio favors <em>inside</em> by roughly 45 to 1 — 0.98 against 0.022. That’s the Bayesian version of what TOST just told us at <span class="math inline">\(\Delta = 2\)</span> seconds: same data, same bound, same conclusion, different formalism. (Had I skipped the unit conversion, that ratio would have printed as about 131,000 to 1 — three orders of magnitude of apparent evidence, manufactured entirely by a bound I never chose.)</p>
</section><section id="bayes-doesnt-let-you-skip-the-hard-part" class="level2" data-number="48.6"><h2 data-number="48.6" class="anchored" data-anchor-id="bayes-doesnt-let-you-skip-the-hard-part">
<span class="header-section-number">48.6</span> Bayes doesn’t let you skip the hard part</h2>
<p>Here’s the thing I think gets missed, and the reason people often reach for a Bayes factor in the first place: it feels like a way to avoid ever stating a <span class="math inline">\(\Delta\)</span>. Look at what actually happened above, though. To get a Bayesian claim that resembles “no meaningful effect,” I had to hand <code>nullInterval</code> the <em>same</em> <span class="math inline">\(\pm 2\)</span> seconds used for TOST — rescaled into the standardized units it expects, but the same substantive bound. The judgment didn’t disappear; it just needed a unit conversion on the way in.</p>
<p>Even the plain, no-interval Bayes factor doesn’t escape it — the judgment just moves somewhere harder to see. The Cauchy prior’s scale (<span class="math inline">\(r = \sqrt{2}/2\)</span> by default, visible in the printed output as <code>r=0.707</code>) encodes an assumption about how big a “typical” real effect would be, and that assumption drives whether <span class="math inline">\(\text{BF}_{10}\)</span> ends up favoring the null. Change <span class="math inline">\(r\)</span> and you change the verdict, on the same data.</p>
<p>This connects straight back to why pre-registration exists. If <span class="math inline">\(\Delta\)</span>, or the prior’s scale <span class="math inline">\(r\)</span>, isn’t locked in <em>before</em> you see the data, you’re right back to the original problem: nothing stops you from nudging it — a wider <span class="math inline">\(\Delta\)</span>, a tighter prior — until the analysis says what you wanted. TOST versus Bayes was never really the choice that matters. The choice that matters is whether the number driving either one was decided in advance or backed into afterward. A method that lets you state your commitment openly (TOST’s <span class="math inline">\(\Delta\)</span>) is easier to audit than one that lets the same commitment hide inside a prior most readers won’t think to interrogate — but both need the commitment made before the data arrive, or neither one is doing its job.</p>
<p>Plain NHST doesn’t get a pass here either. Testing against exactly zero is its own unexamined threshold — it’s just a default nobody questions, rather than a bound anyone stated and defended.</p>
</section><section id="so-how-do-you-actually-justify-delta" class="level2" data-number="48.7"><h2 data-number="48.7" class="anchored" data-anchor-id="so-how-do-you-actually-justify-delta">
<span class="header-section-number">48.7</span> So how do you actually justify <span class="math inline">\(\Delta\)</span>?</h2>
<p>This is the genuinely hard part, and pre-registering <em>something</em> doesn’t help if that something was picked arbitrarily. The general playbook (Lakens, Scheel &amp; Isager, 2018) gives three routes:</p>
<ol type="1">
<li>
<strong>Just-noticeable difference</strong> — set <span class="math inline">\(\Delta\)</span> to the smallest change that would actually be perceptible or consequential in the world. Works well when there’s a natural perceptual or operational unit.</li>
<li>
<strong>Cost-benefit analysis</strong> — decide what magnitude would actually be worth acting on, given the stakes. This is a substantive argument, not a formula, and it’s field- and context-specific by nature — a “negligible” effect in one domain can be highly consequential in another, and that’s appropriate, not a flaw.</li>
<li>
<strong>Small telescopes</strong> (Simonsohn, 2015) — anchor <span class="math inline">\(\Delta\)</span> to the effect size a comparable prior study had only <em>33% power</em> to detect: an effect so small that the original design would have missed it two times in three. Worth being careful here, because it is easy to misread: the 33% is a power level, not a fraction of the original estimate. At conventional sample sizes <span class="math inline">\(d_{33\%}\)</span> comes out a little over half of <span class="math inline">\(d_{80\%}\)</span>, not a third of it. This route has an actual formula behind it, but only works if a genuinely comparable prior study exists.</li>
</ol>
<p>What doesn’t work, and I’ve caught myself reaching for it: deriving <span class="math inline">\(\Delta\)</span> by converting some other bound through an ad hoc formula — say, dividing a level-based bound by a predictor’s range to manufacture a slope-based one — without a citation behind the conversion. That’s a self-defined bound wearing a formula as a disguise, and pre-registering it doesn’t fix the underlying problem: it was still picked to be convenient rather than derived from anything defensible.</p>
</section><section id="why-not-just-report-the-ci-and-let-the-reader-decide" class="level2" data-number="48.8"><h2 data-number="48.8" class="anchored" data-anchor-id="why-not-just-report-the-ci-and-let-the-reader-decide">
<span class="header-section-number">48.8</span> “Why not just report the CI and let the reader decide?”</h2>
<p>I pushed on this myself before landing on TOST as the thing to actually recommend. The estimation-focused view — report the point estimate and CI, skip the dichotomous decision — is a real, well-respected position (Cumming’s “New Statistics” is the standard reference). And it’s true that TOST computes nothing beyond what the CI already contains; the whole procedure collapses to a single inclusion check.</p>
<p>But “let the reader decide” quietly reintroduces the exact problem pre-registration exists to solve. Deciding a CI is “narrow enough” to call an effect negligible requires the same judgment as choosing <span class="math inline">\(\Delta\)</span> — it’s just handed to each reader’s private, unstated threshold instead of the author’s public, pre-committed one. And a pre-registered design specifically can’t defer that judgment to the reader, because pre-registration only works if it’s the <em>author</em> committing, in advance, to what counts as support, null, and inconclusive. A reader’s judgment, applied after publication, isn’t something anyone pre-registered — there’s nothing to audit it against.</p>
<p>The resolution I landed on: do both, and they stop being in tension. Report <span class="math inline">\(\Delta\)</span> as the pre-registered, defended criterion — that’s the commitment the whole framework depends on. Report the raw coefficient and CI right alongside it — that’s what lets a reader who disagrees with your <span class="math inline">\(\Delta\)</span> apply their own, using numbers you’ve already published, with no re-analysis required. That’s also a real point in TOST’s favor over a bare Bayes factor: a skeptical reader can route around a disputed <span class="math inline">\(\Delta\)</span> using the reported CI directly; disputing a Bayes factor means recomputing the whole thing under a different prior.</p>
</section><section id="what-id-actually-do" class="level2" data-number="48.9"><h2 data-number="48.9" class="anchored" data-anchor-id="what-id-actually-do">
<span class="header-section-number">48.9</span> What I’d actually do</h2>
<p>Lead with equivalence testing, report the Bayes factor alongside as a convergent check — cheap, and pure upside when they agree. Pre-register <span class="math inline">\(\Delta\)</span> using whichever of the three justification routes above actually fits the field, stated and defended before the data exist to bias the choice. And always report the plain coefficient and CI next to the equivalence verdict — not because the formal test is wrong, but because the CI is the part that survives even if a reader rejects your bound.</p>
<p>The single idea underneath all of this: pre-registration isn’t really about picking the “right” test. It’s about making sure nothing — not the test, not the normality check, not <span class="math inline">\(\Delta\)</span>, not a prior’s scale — gets to be chosen after the data have already told you what answer it would give.</p>


<!-- -->

</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/xiangao\.github\.io\/blog_book\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./numpyro.html" class="pagination-link" aria-label="Using Numpyro">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Using Numpyro</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Pre-registration, TOST, and why Bayes doesn't let you skip the hard part"</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2026-07-24"</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="fu">## Why this came up</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>A colleague asked me to look over the analysis plan for a paper being submitted as a Registered Report (RR). Three of the hypotheses were the interesting kind: the authors expected an effect, but part of what they wanted to claim was that a *moderator* of that effect was absent, or negligible, in some subgroup. The draft's plan was to run the usual test, and if it came back non-significant, report that as evidence the moderator doesn't matter. If the data looked non-normal, switch to a different test. That doesn't work, and working out exactly why turned into this post.</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="fu">## What pre-registration is actually for</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>Strip away the jargon and pre-registration does one thing: it makes you commit, in writing, before you see the data, to exactly which analysis you'll run and how you'll interpret every possible result it could produce. Not "we'll run a sensible test" — the specific test, the specific decision rule for what counts as support, what counts as a null, what counts as inconclusive.</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>The reason this matters is not really about honesty in the moment you write the paper. It's about closing off every place where a result could quietly steer your choice of method. If you look at your data, notice it's non-normal, and *then* decide to switch from a $t$-test to a Wilcoxon test, you've let the data pick the analysis — and the two tests won't always agree, so which one you end up reporting is no longer independent of what answer it gives you. Same story if you pick your significance threshold, your covariates, or your equivalence bound after peeking. None of this requires bad faith. It's enough that a result you don't love makes you reach for a "more appropriate" method you wouldn't have reached for otherwise. Pre-registration's whole job is to make that impossible: the method is fixed before the data exists to influence it.</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>Registered Reports push this further than ordinary pre-registration. The journal grants *in-principle acceptance* of the design before any data are collected, and commits to publishing the paper whatever the result turns out to be. That's a stronger guarantee than "I promised myself I wouldn't switch methods" — the switch is now also unavailable in practice, because the paper's fate no longer depends on which result you got.</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>But that guarantee creates an obligation of its own. If the journal must publish the paper regardless of outcome, and the outcome is a null result, the null has to actually mean something — otherwise the journal has committed to publishing noise. The Registered Reports template maintained by the Center for Open Science, which the journals running the format adopt close to word for word, makes this a ground for desk rejection outright. Among the listed reasons a Stage 1 submission gets turned away:</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Intention to infer support for the null hypothesis from statistically non-significant results, without proposing use of Bayes factors or frequentist equivalence testing (e.g., Lakens, Scheel &amp; Isager, 2018).</span></span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>The same list attaches a power requirement that people don't always expect:</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Proposals should be powered to detect the smallest effect that is plausible and of theoretical value. Pilot data can help inform this estimate but is unlikely to form an acceptable basis, alone, for choosing the target effect size.</span></span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>and the accompanying author guidelines set the floor: "For frequentist analysis plans, the a priori power must be 0.9 or higher for all proposed hypothesis tests." Individual journals tighten that — Nature Human Behaviour requires 0.95. I'll come back to why the phrasing about pilot data matters.</span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a><span class="fu">## A non-significant result is not "no effect"</span></span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a>Ordinary null hypothesis significance testing (NHST) tests $H_0: \theta = 0$ against $H_1: \theta \neq 0$. A non-significant result ($p &gt; 0.05$) tells you only that you couldn't reject zero, and that has two very different possible causes:</span>
<span id="cb13-31"><a href="#cb13-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-32"><a href="#cb13-32" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>the true effect really is about zero, or</span>
<span id="cb13-33"><a href="#cb13-33" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>the effect is real, but the data are too noisy or the sample too small to detect it.</span>
<span id="cb13-34"><a href="#cb13-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-35"><a href="#cb13-35" aria-hidden="true" tabindex="-1"></a>Both give you the same large $p$-value, and the test itself gives you no way to tell which one you're looking at. Here's the reductio I keep coming back to: you could "prove" almost any effect is zero just by collecting a tiny sample. A small $n$ guarantees a wide confidence interval (CI) and non-significance, regardless of what's actually true. A non-significant result is silence, not evidence of absence — and it's exactly the kind of ambiguous result that invites the post-hoc-method-switching problem above, because "silence" leaves so much room for a motivated reading.</span>
<span id="cb13-36"><a href="#cb13-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-37"><a href="#cb13-37" aria-hidden="true" tabindex="-1"></a><span class="fu">## Equivalence testing (TOST), plainly</span></span>
<span id="cb13-38"><a href="#cb13-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-39"><a href="#cb13-39" aria-hidden="true" tabindex="-1"></a>Equivalence testing flips the question from "is the effect exactly zero" to "can I rule out an effect large enough to matter." You pre-specify a bound $\Delta$ — the smallest effect size of interest (SESOI), the largest effect you'd still call negligible — and run two one-sided tests (TOST):</span>
<span id="cb13-40"><a href="#cb13-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-41"><a href="#cb13-41" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb13-42"><a href="#cb13-42" aria-hidden="true" tabindex="-1"></a>H_{01}: \theta \le -\Delta \qquad \text{vs.} \qquad H_{02}: \theta \ge +\Delta.</span>
<span id="cb13-43"><a href="#cb13-43" aria-hidden="true" tabindex="-1"></a>$$ {#eq-equivalence-testing-1}</span>
<span id="cb13-44"><a href="#cb13-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-45"><a href="#cb13-45" aria-hidden="true" tabindex="-1"></a>Reject both, and the effect lies inside $<span class="co">[</span><span class="ot">-\Delta, +\Delta</span><span class="co">]</span>$. Operationally this collapses to one check: build the $(1-2\alpha)$ CI and see whether it sits entirely inside the bounds. There's no separate machine computing something new — TOST is a decision rule wrapped around a CI you already had.</span>
<span id="cb13-46"><a href="#cb13-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-47"><a href="#cb13-47" aria-hidden="true" tabindex="-1"></a>Notice where $\Delta$ has to come from for any of this to be worth doing: it has to be chosen *before* you see the result, for the same reason the whole test method has to be. If you're allowed to set $\Delta$ after looking at your CI, you can always draw the bound just wide enough to swallow whatever you got — which defeats the entire point, and is really the same violation as switching from a $t$-test to a Wilcoxon test after peeking, just one level further down.</span>
<span id="cb13-48"><a href="#cb13-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-49"><a href="#cb13-49" aria-hidden="true" tabindex="-1"></a>Here's a worked example using <span class="in">`mtcars`</span>, purely to show the mechanics — nobody should take conclusions about 1974 cars seriously. Is the quarter-mile time (<span class="in">`qsec`</span>) meaningfully different between automatic and manual transmissions?</span>
<span id="cb13-50"><a href="#cb13-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-53"><a href="#cb13-53" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-54"><a href="#cb13-54" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb13-55"><a href="#cb13-55" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(TOSTER)</span>
<span id="cb13-56"><a href="#cb13-56" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(mtcars)</span>
<span id="cb13-57"><a href="#cb13-57" aria-hidden="true" tabindex="-1"></a>mtcars<span class="sc">$</span>am <span class="ot">&lt;-</span> <span class="fu">factor</span>(mtcars<span class="sc">$</span>am, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"automatic"</span>, <span class="st">"manual"</span>))</span>
<span id="cb13-58"><a href="#cb13-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-59"><a href="#cb13-59" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(qsec <span class="sc">~</span> am, <span class="at">data =</span> mtcars)</span>
<span id="cb13-60"><a href="#cb13-60" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-61"><a href="#cb13-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-62"><a href="#cb13-62" aria-hidden="true" tabindex="-1"></a>Not significant ($p = 0.21$). Under plain NHST, that's the whole story: "no evidence of a difference." Now suppose I'd pre-specified, before looking, that anything under one second doesn't matter ($\Delta = 1$):</span>
<span id="cb13-63"><a href="#cb13-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-66"><a href="#cb13-66" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-67"><a href="#cb13-67" aria-hidden="true" tabindex="-1"></a><span class="fu">t_TOST</span>(<span class="at">formula =</span> qsec <span class="sc">~</span> am, <span class="at">data =</span> mtcars, <span class="at">eqb =</span> <span class="dv">1</span>, <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span>
<span id="cb13-68"><a href="#cb13-68" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-69"><a href="#cb13-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-70"><a href="#cb13-70" aria-hidden="true" tabindex="-1"></a>TOST also fails to declare equivalence — the 90% CI is $<span class="co">[</span><span class="ot">-0.27, 1.91</span><span class="co">]</span>$, and it spills past $+1$. So both the plain test and TOST agree here: the data just aren't informative, in either direction. TOST doesn't rescue an underpowered comparison — that's expected, and it's the honest answer. Now widen the bound to $\Delta = 2$, using the exact same data:</span>
<span id="cb13-71"><a href="#cb13-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-74"><a href="#cb13-74" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-75"><a href="#cb13-75" aria-hidden="true" tabindex="-1"></a><span class="fu">t_TOST</span>(<span class="at">formula =</span> qsec <span class="sc">~</span> am, <span class="at">data =</span> mtcars, <span class="at">eqb =</span> <span class="dv">2</span>, <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span>
<span id="cb13-76"><a href="#cb13-76" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-77"><a href="#cb13-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-78"><a href="#cb13-78" aria-hidden="true" tabindex="-1"></a>Now the CI sits entirely inside $<span class="co">[</span><span class="ot">-2, 2</span><span class="co">]</span>$, and TOST declares equivalence. The plain $t$-test's $p$-value hasn't moved at all — still 0.21, because it never looked at $\Delta$ in the first place. That's the whole value of TOST in one pair of examples: NHST can't distinguish "underpowered nonsense" from "precisely estimated and negligible," because it never asked the second question. TOST can — but only if $\Delta$ was nailed down in advance. Run both versions after seeing the data and picking whichever looks better, and you've just reinvented p-hacking with extra steps.</span>
<span id="cb13-79"><a href="#cb13-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-80"><a href="#cb13-80" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Bayesian alternative</span></span>
<span id="cb13-81"><a href="#cb13-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-82"><a href="#cb13-82" aria-hidden="true" tabindex="-1"></a>A Bayes factor (BF) compares the marginal likelihood of the data under $H_1$ versus $H_0$:</span>
<span id="cb13-83"><a href="#cb13-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-84"><a href="#cb13-84" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb13-85"><a href="#cb13-85" aria-hidden="true" tabindex="-1"></a>\text{BF}_{10} = \frac{p(\text{data} \mid H_1)}{p(\text{data} \mid H_0)}.</span>
<span id="cb13-86"><a href="#cb13-86" aria-hidden="true" tabindex="-1"></a>$$ {#eq-equivalence-testing-2}</span>
<span id="cb13-87"><a href="#cb13-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-88"><a href="#cb13-88" aria-hidden="true" tabindex="-1"></a>Conventionally, $\text{BF}_{10} &lt; 1/3$ counts as evidence for the null, $\text{BF}_{10} &gt; 3$ for the alternative, and anything between is inconclusive. The default JZS prior puts a Cauchy distribution on the standardized effect under $H_1$. (One asymmetry worth noting, given the theme of this post: the tests above used Welch's correction, <span class="in">`var.equal = FALSE`</span>, while <span class="in">`ttestBF`</span>'s JZS model assumes equal variances. Here it makes no difference to the verdict, but it is one more incidental choice that a pre-registration should nail down rather than leave to whichever default came to hand.)</span>
<span id="cb13-89"><a href="#cb13-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-92"><a href="#cb13-92" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-93"><a href="#cb13-93" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb13-94"><a href="#cb13-94" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(BayesFactor)</span>
<span id="cb13-95"><a href="#cb13-95" aria-hidden="true" tabindex="-1"></a><span class="fu">ttestBF</span>(<span class="at">formula =</span> qsec <span class="sc">~</span> am, <span class="at">data =</span> mtcars)</span>
<span id="cb13-96"><a href="#cb13-96" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-97"><a href="#cb13-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-98"><a href="#cb13-98" aria-hidden="true" tabindex="-1"></a>$\text{BF}_{10} \approx 0.64$: mildly favors the null, but not by much — inconclusive by the usual thresholds. This default BF is quietly answering a different question than TOST did: it compares "no effect at all" to "some effect, of unknown size, drawn from a Cauchy prior," not "effect inside $\pm 2$" to "effect outside $\pm 2$." If you want the actual Bayesian analogue of an equivalence claim, you need an interval null.</span>
<span id="cb13-99"><a href="#cb13-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-100"><a href="#cb13-100" aria-hidden="true" tabindex="-1"></a>One trap to clear first, and it is exactly the kind of thing this post is about. <span class="in">`TOSTER`</span>'s <span class="in">`eqb`</span> is in **raw** units — those were 2 seconds of `qsec`. `BayesFactor`'s `nullInterval` is in **standardized** units, Cohen's $d$; look at the labels it prints and you'll see it says <span class="in">`d`</span>. Handing it <span class="in">`c(-2, 2)`</span> would silently test a bound of $\pm 2$ *standard deviations*, which on these data is $\pm 3.5$ seconds — nearly twice the bound I actually pre-specified, and it would make the Bayesian evidence look far stronger than it is. So the bound has to be converted before it goes in:</span>
<span id="cb13-101"><a href="#cb13-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-104"><a href="#cb13-104" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-105"><a href="#cb13-105" aria-hidden="true" tabindex="-1"></a>grp <span class="ot">&lt;-</span> <span class="fu">split</span>(mtcars<span class="sc">$</span>qsec, mtcars<span class="sc">$</span>am)</span>
<span id="cb13-106"><a href="#cb13-106" aria-hidden="true" tabindex="-1"></a>n1 <span class="ot">&lt;-</span> <span class="fu">length</span>(grp[[<span class="dv">1</span>]]); n2 <span class="ot">&lt;-</span> <span class="fu">length</span>(grp[[<span class="dv">2</span>]])</span>
<span id="cb13-107"><a href="#cb13-107" aria-hidden="true" tabindex="-1"></a>sd_pooled <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(((n1 <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="fu">var</span>(grp[[<span class="dv">1</span>]]) <span class="sc">+</span> (n2 <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="fu">var</span>(grp[[<span class="dv">2</span>]])) <span class="sc">/</span> (n1 <span class="sc">+</span> n2 <span class="sc">-</span> <span class="dv">2</span>))</span>
<span id="cb13-108"><a href="#cb13-108" aria-hidden="true" tabindex="-1"></a>delta_d <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">/</span> sd_pooled   <span class="co"># the same +/- 2 seconds, expressed in d units</span></span>
<span id="cb13-109"><a href="#cb13-109" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">sd_pooled =</span> sd_pooled, <span class="at">delta_d =</span> delta_d)</span>
<span id="cb13-110"><a href="#cb13-110" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-111"><a href="#cb13-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-114"><a href="#cb13-114" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-115"><a href="#cb13-115" aria-hidden="true" tabindex="-1"></a><span class="fu">ttestBF</span>(<span class="at">formula =</span> qsec <span class="sc">~</span> am, <span class="at">data =</span> mtcars, <span class="at">nullInterval =</span> <span class="fu">c</span>(<span class="sc">-</span>delta_d, delta_d))</span>
<span id="cb13-116"><a href="#cb13-116" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-117"><a href="#cb13-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-118"><a href="#cb13-118" aria-hidden="true" tabindex="-1"></a>The first line is the Bayes factor for "the effect is inside $\pm\Delta$" against the point null; the second is for "the effect is outside $\pm\Delta$." Their ratio favors *inside* by roughly 45 to 1 — 0.98 against 0.022. That's the Bayesian version of what TOST just told us at $\Delta = 2$ seconds: same data, same bound, same conclusion, different formalism. (Had I skipped the unit conversion, that ratio would have printed as about 131,000 to 1 — three orders of magnitude of apparent evidence, manufactured entirely by a bound I never chose.)</span>
<span id="cb13-119"><a href="#cb13-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-120"><a href="#cb13-120" aria-hidden="true" tabindex="-1"></a><span class="fu">## Bayes doesn't let you skip the hard part</span></span>
<span id="cb13-121"><a href="#cb13-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-122"><a href="#cb13-122" aria-hidden="true" tabindex="-1"></a>Here's the thing I think gets missed, and the reason people often reach for a Bayes factor in the first place: it feels like a way to avoid ever stating a $\Delta$. Look at what actually happened above, though. To get a Bayesian claim that resembles "no meaningful effect," I had to hand <span class="in">`nullInterval`</span> the *same* $\pm 2$ seconds used for TOST — rescaled into the standardized units it expects, but the same substantive bound. The judgment didn't disappear; it just needed a unit conversion on the way in.</span>
<span id="cb13-123"><a href="#cb13-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-124"><a href="#cb13-124" aria-hidden="true" tabindex="-1"></a>Even the plain, no-interval Bayes factor doesn't escape it — the judgment just moves somewhere harder to see. The Cauchy prior's scale ($r = \sqrt{2}/2$ by default, visible in the printed output as <span class="in">`r=0.707`</span>) encodes an assumption about how big a "typical" real effect would be, and that assumption drives whether $\text{BF}_{10}$ ends up favoring the null. Change $r$ and you change the verdict, on the same data.</span>
<span id="cb13-125"><a href="#cb13-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-126"><a href="#cb13-126" aria-hidden="true" tabindex="-1"></a>This connects straight back to why pre-registration exists. If $\Delta$, or the prior's scale $r$, isn't locked in *before* you see the data, you're right back to the original problem: nothing stops you from nudging it — a wider $\Delta$, a tighter prior — until the analysis says what you wanted. TOST versus Bayes was never really the choice that matters. The choice that matters is whether the number driving either one was decided in advance or backed into afterward. A method that lets you state your commitment openly (TOST's $\Delta$) is easier to audit than one that lets the same commitment hide inside a prior most readers won't think to interrogate — but both need the commitment made before the data arrive, or neither one is doing its job.</span>
<span id="cb13-127"><a href="#cb13-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-128"><a href="#cb13-128" aria-hidden="true" tabindex="-1"></a>Plain NHST doesn't get a pass here either. Testing against exactly zero is its own unexamined threshold — it's just a default nobody questions, rather than a bound anyone stated and defended.</span>
<span id="cb13-129"><a href="#cb13-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-130"><a href="#cb13-130" aria-hidden="true" tabindex="-1"></a><span class="fu">## So how do you actually justify $\Delta$?</span></span>
<span id="cb13-131"><a href="#cb13-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-132"><a href="#cb13-132" aria-hidden="true" tabindex="-1"></a>This is the genuinely hard part, and pre-registering *something* doesn't help if that something was picked arbitrarily. The general playbook (Lakens, Scheel &amp; Isager, 2018) gives three routes:</span>
<span id="cb13-133"><a href="#cb13-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-134"><a href="#cb13-134" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Just-noticeable difference** — set $\Delta$ to the smallest change that would actually be perceptible or consequential in the world. Works well when there's a natural perceptual or operational unit.</span>
<span id="cb13-135"><a href="#cb13-135" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Cost-benefit analysis** — decide what magnitude would actually be worth acting on, given the stakes. This is a substantive argument, not a formula, and it's field- and context-specific by nature — a "negligible" effect in one domain can be highly consequential in another, and that's appropriate, not a flaw.</span>
<span id="cb13-136"><a href="#cb13-136" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Small telescopes** (Simonsohn, 2015) — anchor $\Delta$ to the effect size a comparable prior study had only *33% power* to detect: an effect so small that the original design would have missed it two times in three. Worth being careful here, because it is easy to misread: the 33% is a power level, not a fraction of the original estimate. At conventional sample sizes $d_{33\%}$ comes out a little over half of $d_{80\%}$, not a third of it. This route has an actual formula behind it, but only works if a genuinely comparable prior study exists.</span>
<span id="cb13-137"><a href="#cb13-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-138"><a href="#cb13-138" aria-hidden="true" tabindex="-1"></a>What doesn't work, and I've caught myself reaching for it: deriving $\Delta$ by converting some other bound through an ad hoc formula — say, dividing a level-based bound by a predictor's range to manufacture a slope-based one — without a citation behind the conversion. That's a self-defined bound wearing a formula as a disguise, and pre-registering it doesn't fix the underlying problem: it was still picked to be convenient rather than derived from anything defensible.</span>
<span id="cb13-139"><a href="#cb13-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-140"><a href="#cb13-140" aria-hidden="true" tabindex="-1"></a><span class="fu">## "Why not just report the CI and let the reader decide?"</span></span>
<span id="cb13-141"><a href="#cb13-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-142"><a href="#cb13-142" aria-hidden="true" tabindex="-1"></a>I pushed on this myself before landing on TOST as the thing to actually recommend. The estimation-focused view — report the point estimate and CI, skip the dichotomous decision — is a real, well-respected position (Cumming's "New Statistics" is the standard reference). And it's true that TOST computes nothing beyond what the CI already contains; the whole procedure collapses to a single inclusion check.</span>
<span id="cb13-143"><a href="#cb13-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-144"><a href="#cb13-144" aria-hidden="true" tabindex="-1"></a>But "let the reader decide" quietly reintroduces the exact problem pre-registration exists to solve. Deciding a CI is "narrow enough" to call an effect negligible requires the same judgment as choosing $\Delta$ — it's just handed to each reader's private, unstated threshold instead of the author's public, pre-committed one. And a pre-registered design specifically can't defer that judgment to the reader, because pre-registration only works if it's the *author* committing, in advance, to what counts as support, null, and inconclusive. A reader's judgment, applied after publication, isn't something anyone pre-registered — there's nothing to audit it against.</span>
<span id="cb13-145"><a href="#cb13-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-146"><a href="#cb13-146" aria-hidden="true" tabindex="-1"></a>The resolution I landed on: do both, and they stop being in tension. Report $\Delta$ as the pre-registered, defended criterion — that's the commitment the whole framework depends on. Report the raw coefficient and CI right alongside it — that's what lets a reader who disagrees with your $\Delta$ apply their own, using numbers you've already published, with no re-analysis required. That's also a real point in TOST's favor over a bare Bayes factor: a skeptical reader can route around a disputed $\Delta$ using the reported CI directly; disputing a Bayes factor means recomputing the whole thing under a different prior.</span>
<span id="cb13-147"><a href="#cb13-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-148"><a href="#cb13-148" aria-hidden="true" tabindex="-1"></a><span class="fu">## What I'd actually do</span></span>
<span id="cb13-149"><a href="#cb13-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-150"><a href="#cb13-150" aria-hidden="true" tabindex="-1"></a>Lead with equivalence testing, report the Bayes factor alongside as a convergent check — cheap, and pure upside when they agree. Pre-register $\Delta$ using whichever of the three justification routes above actually fits the field, stated and defended before the data exist to bias the choice. And always report the plain coefficient and CI next to the equivalence verdict — not because the formal test is wrong, but because the CI is the part that survives even if a reader rejects your bound.</span>
<span id="cb13-151"><a href="#cb13-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-152"><a href="#cb13-152" aria-hidden="true" tabindex="-1"></a>The single idea underneath all of this: pre-registration isn't really about picking the "right" test. It's about making sure nothing — not the test, not the normality check, not $\Delta$, not a prior's scale — gets to be chosen after the data have already told you what answer it would give.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->



<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions"><ul><li><a href="https://github.com/xiangao/blog_book/edit/main/equivalence-testing.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/xiangao/blog_book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>