<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="dcterms.date" content="2019-05-23">
<title>7&nbsp; Fixed or Random Effect, or Both? – Topics on econometrics and causal inference</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./mundlak-device.html" rel="next">
<link href="./comparing-margins.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6eb2a311e0ae5a9b436ea9f7e52955e6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script>
try {
  if (window.localStorage) {
    window.localStorage.setItem("quarto-reader-mode", "false");
  }
} catch (e) {}
</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="style.css">
</head>
<body class="nav-sidebar floating fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./marginal-effects-fe.html">Marginal Effects &amp; Fixed Effects</a></li><li class="breadcrumb-item"><a href="./fixed-random-effect.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Fixed or Random Effect, or Both?</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Topics on econometrics and causal inference</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://xiangao.github.io/" title="Xiang Ao home" class="quarto-navigation-tool px-1" aria-label="Xiang Ao home"><i class="bi bi-house-door-fill"></i></a>
    <a href="https://xiangao.github.io/books.html" title="Other books" class="quarto-navigation-tool px-1" aria-label="Other books"><i class="bi bi-book"></i></a>
    <a href="https://github.com/xiangao/blog_book/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Regression Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./interaction-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Interpreting interaction in a regression model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./interaction-nonlinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Interaction term in a non-linear model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chow-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Chow test and more</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./weights-ols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Weights in OLS in causal inference</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Marginal Effects &amp; Fixed Effects</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./marginal-effects-fe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Marginal effects in models with fixed effects</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./comparing-margins.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Comparing Marginal effects with margins command</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fixed-random-effect.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Fixed or Random Effect, or Both?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mundlak-device.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Mundlak device in fixed effect models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlated-random-effect.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Correlated Random Effect</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./more-cre.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">More on Correlated Random Effect (CRE)</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Treatment Effects &amp; Matching</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./treatment-matching.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Treatment effects and matching</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ols-ate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">When is OLS coefficient the ATE</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./matching-part1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Matching and Weighting Part 1: matching</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./weighting-part2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Matching and Weighting - Part 2: weighting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sensitivity-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Sensitivity analysis of OLS with sensemakr</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./gwg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Gender Wage Gap Analysis Using US Current Population Survey Data</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Panel Data &amp; DiD</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal-forest-panel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Causal Forest in panel data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./synthetic-control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Synthetic Control in R and Stata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tasc-time-aware-synthetic-control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Same Data, Different Estimators: A Synthetic Control Comparison</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bartik-instrument.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Bartik Instrument and Rotemberg weights</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./extended-twfe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Extended TWFE and other DiD estimators</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal-panel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Causal Panel (why DDDiD)</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Count Data &amp; Specialized Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Which count data model to use</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rare-events.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">What model to use for rare events</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./poisson-exposure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Poisson model with exposure</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./poisson-iv-fe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">IV in Fixed effect Poisson with many fixed effects</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Causal Inference Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tmle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Using machine learning for causal effect in observational study</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mediation-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Mediation analysis in R and Stata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bunching.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Endogeneity with censored variable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./g-estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">G-computation (g-formula) with time varying covariates</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./policytree.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Policy learning by policytree</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./npcausal-tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Recent causal inference tools</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./proximal-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Intro to proximal causal inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./proximal-simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Simulation on proximal causal inference with panel data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lmtp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">longitudinal modified treatment policy (LMTP)</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Advanced Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multilevel-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Doing the same multi-level model with R and stata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./likert-scale-variance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Modeling variation, not just the mean, in Likert-scale data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conjoint-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Conjoint design and analysis using R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stata-cate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Stata 19 CATE command</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./spatial-econometrics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Spatial econometrics introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal-simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Causal simulation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./frengression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Frengression and Engression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./partial-interference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Partial Interference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./power-list-experiment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Power analysis with list experiment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal-mediation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Causal mediation analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uplift.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Uplift Modeling and CATE</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./numpyro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Using Numpyro</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./equivalence-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Pre-registration, TOST, and why Bayes doesn’t let you skip the hard part</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./marginal-effects-fe.html">Marginal Effects &amp; Fixed Effects</a></li><li class="breadcrumb-item"><a href="./fixed-random-effect.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Fixed or Random Effect, or Both?</span></a></li></ol></nav><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">
<span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Fixed or Random Effect, or Both?</span>
</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 23, 2019</p>
    </div>
  </div>
  
    
  </div>
  


</header><section id="panel-data" class="level2" data-number="7.1"><h2 data-number="7.1" class="anchored" data-anchor-id="panel-data">
<span class="header-section-number">7.1</span> Panel data</h2>
<p>With panel data — repeated observations over time or observations clustered at a higher level — the standard choice is between fixed and random effects. Consider</p>
<p><span id="eq-fixed-random-effect-1"><span class="math display">\[ y_{it} = \beta_0 + \beta_1 x_{it} + c_i + \epsilon_{it}  \tag{7.1}\]</span></span></p>
<p>for individuals <span class="math inline">\(i = 1, \ldots, n\)</span> measured at <span class="math inline">\(t = 1, \ldots, T\)</span>, where <span class="math inline">\(c_i\)</span> is an unobserved time-invariant individual effect. The two approaches differ in how they handle <span class="math inline">\(c_i\)</span>.</p>
<p>Fixed effects eliminate <span class="math inline">\(c_i\)</span> by demeaning or by including individual dummies (the two are equivalent in a linear model). In nonlinear models only Poisson avoids the incidental-parameter problem; the standard solution for other models is conditional likelihood (conditional logit, for example), which absorbs the fixed effects in the likelihood. When no conditional likelihood exists, the incidental-parameter bias shrinks with panel depth but does not vanish.</p>
<p>Random effects treat <span class="math inline">\(c_i\)</span> as part of the error term. This is more efficient but requires <span class="math inline">\(x_{it}\)</span> to be uncorrelated with <span class="math inline">\(c_i\)</span> — an assumption economists are generally skeptical of.</p>
</section><section id="time-invariant-variables" class="level2" data-number="7.2"><h2 data-number="7.2" class="anchored" data-anchor-id="time-invariant-variables">
<span class="header-section-number">7.2</span> Time-invariant variables</h2>
<p>Sometimes we want the effect of a time-invariant variable, so the model becomes</p>
<p><span id="eq-fixed-random-effect-2"><span class="math display">\[ y_{it} = \beta_0  + \beta_1 x_{it} + c_i  + \gamma z_i+ \epsilon_{it}  \tag{7.2}\]</span></span></p>
<p>Fixed effects cannot identify <span class="math inline">\(\gamma\)</span> because <span class="math inline">\(z_i\)</span> is perfectly collinear with <span class="math inline">\(c_i\)</span>. Random effects can still estimate both, treating <span class="math inline">\(z_i\)</span> as another covariate.</p>
</section><section id="between-within-model" class="level2" data-number="7.3"><h2 data-number="7.3" class="anchored" data-anchor-id="between-within-model">
<span class="header-section-number">7.3</span> Between-within model</h2>
<p>The textbook advice is a Hausman test: random effects are more efficient when the uncorrelatedness assumption holds; if not, fixed effects are still consistent. The between-within model (BW) sidesteps the choice. <a href="https://www.ncbi.nlm.nih.gov/pubmed/9629647">Neuhaus and Kalbfleisch (1998)</a> introduced the BW estimator,</p>
<p><span id="eq-fixed-random-effect-3"><span class="math display">\[ y_{it} = \beta_0  + \beta_1 (x_{it} - \bar x_i) + \beta_2 \bar x_i + c_i  + \gamma z_i+ \epsilon_{it}  \tag{7.3}\]</span></span></p>
<p>Here <span class="math inline">\(\beta_1\)</span> is the within effect — identical to the fixed-effect coefficient. <span class="math inline">\(\beta_2\)</span> is the between effect (mean of <span class="math inline">\(x\)</span> on mean of <span class="math inline">\(y\)</span>). <span class="math inline">\(\gamma\)</span> is the effect of the time-invariant variable.</p>
<p>The other specification of BW estimator is</p>
<p><span id="eq-fixed-random-effect-4"><span class="math display">\[ y_{it} = \beta_0  + \beta_1 x_{it}  + \beta_2 \bar x_i + c_i  + \gamma z_i+ \epsilon_{it}  \tag{7.4}\]</span></span></p>
<p>This is the same model reparametrized. <span class="math inline">\(\beta_1\)</span> is unchanged, and <span class="math inline">\(\beta_2\)</span> is now the between-minus-within difference (substitute <span class="math inline">\(\beta_1(x_{it}-\bar x_i) + \beta_2 \bar x_i = \beta_1 x_{it} + (\beta_2-\beta_1)\bar x_i\)</span> to see this). This is the “contextual model”; <span class="math inline">\(\beta_2\)</span> is the contextual effect and acts as an embedded Hausman test.</p>
<p>The BW model has two advantages. It recovers the fixed-effect coefficient while estimating time-invariant covariates. And it extends naturally to cross-level interactions, random slopes, and other multilevel structures. Implementation is straightforward: run a random-effects model on either equation above.</p>
<section id="is-this-just-mundlak" class="level3" data-number="7.3.1"><h3 data-number="7.3.1" class="anchored" data-anchor-id="is-this-just-mundlak">
<span class="header-section-number">7.3.1</span> Is this just Mundlak?</h3>
<p>Yes. <a href="#eq-fixed-random-effect-4" class="quarto-xref">Equation&nbsp;<span>7.4</span></a> <em>is</em> the Mundlak device: Mundlak’s regression puts <span class="math inline">\(x_{it}\)</span> and <span class="math inline">\(\bar x_i\)</span> on the right-hand side of a random-effects model, which is exactly what that equation does. So the between-within model and the Mundlak device are one model in two parameterisations, fitted by the same random-effects command. It is worth doing the algebra, because the identity is easy to state loosely and easy to get wrong on the inference side.</p>
<p>Write <span class="math inline">\(d_{it} = x_{it} - \bar x_i\)</span> for the within deviation, and label the two specifications by their coefficients: <span class="math inline">\(b_1, b_2\)</span> for the hybrid form <a href="#eq-fixed-random-effect-3" class="quarto-xref">Equation&nbsp;<span>7.3</span></a> and <span class="math inline">\(p_1, p_2\)</span> for the contextual form <a href="#eq-fixed-random-effect-4" class="quarto-xref">Equation&nbsp;<span>7.4</span></a>. Expanding the hybrid regressor block,</p>
<p><span id="eq-fixed-random-effect-5"><span class="math display">\[
b_1 (x_{it} - \bar x_i) + b_2 \bar x_i = b_1 x_{it} + (b_2 - b_1)\bar x_i ,
\tag{7.5}\]</span></span></p>
<p>so <span class="math inline">\(p_1 = b_1\)</span> and <span class="math inline">\(p_2 = b_2 - b_1\)</span>. Substitution shows the map, but the reason behind it is worth stating more strongly: the two regressor matrices are related by an invertible linear transformation. With <span class="math inline">\(X = [\,x_{it}, \bar x_i\,]\)</span> and <span class="math inline">\(W = [\,d_{it}, \bar x_i\,]\)</span>,</p>
<p><span id="eq-fixed-random-effect-6"><span class="math display">\[
W = XA, \qquad
A = \begin{pmatrix} 1 &amp; 0 \\ -1 &amp; 1 \end{pmatrix}, \qquad
A^{-1} = \begin{pmatrix} 1 &amp; 0 \\ 1 &amp; 1 \end{pmatrix},
\tag{7.6}\]</span></span></p>
<p>and <span class="math inline">\(\det A = 1\)</span>, so the two designs span the same column space. Everything that depends only on that space is numerically identical: fitted values, residuals, the likelihood, the estimated variance components, and the GLS quasi-demeaning weight <span class="math inline">\(\theta\)</span>. Only the coordinates change, by <span class="math inline">\(b = A^{-1}p\)</span>, and the covariance matrix by <span class="math inline">\(\text{Var}(b) = A^{-1}\text{Var}(p)A^{-1\prime}\)</span>. Componentwise that is</p>
<p><span id="eq-fixed-random-effect-7"><span class="math display">\[
\text{Var}(p_1) = \text{Var}(b_1), \qquad
\text{Var}(p_2) = \text{Var}(b_1) + \text{Var}(b_2) + 2\,\text{Cov}(b_1,b_2),
\tag{7.7}\]</span></span></p>
<p>which already says something useful: the standard error printed next to the between effect is not the standard error you want for the contextual effect.</p>
<section id="why-the-within-coefficient-is-the-fixed-effect-estimator" class="level4" data-number="7.3.1.1"><h4 data-number="7.3.1.1" class="anchored" data-anchor-id="why-the-within-coefficient-is-the-fixed-effect-estimator">
<span class="header-section-number">7.3.1.1</span> Why the within coefficient is the fixed-effect estimator</h4>
<p>This part needs a proof rather than a substitution. The relevant fact is that <span class="math inline">\(\sum_t d_{it} = 0\)</span> within every unit by construction, so <span class="math inline">\(d\)</span> is orthogonal to any group-invariant column: for <span class="math inline">\(v_i\)</span> constant within <span class="math inline">\(i\)</span>,</p>
<p><span id="eq-fixed-random-effect-8"><span class="math display">\[
\sum_{i,t} d_{it} v_i = \sum_i v_i \sum_t d_{it} = 0 ,
\tag{7.8}\]</span></span></p>
<p>which covers the intercept, <span class="math inline">\(\bar x_i\)</span> and <span class="math inline">\(z_i\)</span> alike.</p>
<p>Random effects is OLS after quasi-demeaning, <span class="math inline">\(\tilde w_{it} = w_{it} - \theta \bar w_i\)</span> with <span class="math inline">\(\theta = 1 - \sqrt{\sigma^2_\epsilon / (\sigma^2_\epsilon + T\sigma^2_c)}\)</span>. Apply it to the hybrid regressors. Because <span class="math inline">\(\bar d_i = 0\)</span> we get <span class="math inline">\(\tilde d_{it} = d_{it}\)</span>: the within-deviation regressor passes through the GLS transform untouched, whatever <span class="math inline">\(\theta\)</span> is. The remaining regressors are group-invariant and stay so after scaling by <span class="math inline">\(1-\theta\)</span>. Orthogonality therefore survives the transform, and by Frisch-Waugh-Lovell</p>
<p><span id="eq-fixed-random-effect-9"><span class="math display">\[
b_1 = \frac{\sum d_{it}\tilde y_{it}}{\sum d_{it}^2}
    = \frac{\sum d_{it} y_{it}}{\sum d_{it}^2}
    = \frac{\sum (x_{it}-\bar x_i)(y_{it}-\bar y_i)}{\sum (x_{it}-\bar x_i)^2},
\tag{7.9}\]</span></span></p>
<p>the second and third equalities both by <a href="#eq-fixed-random-effect-8" class="quarto-xref">Equation&nbsp;<span>7.8</span></a>. That last expression is the within estimator. Note that <span class="math inline">\(\theta\)</span> has dropped out, so the identity holds for <em>any</em> <span class="math inline">\(\theta\)</span> — for random effects, for pooled OLS (<span class="math inline">\(\theta = 0\)</span>) and for fixed effects (<span class="math inline">\(\theta = 1\)</span>). That is why running a random-effects model on either equation returns the fixed-effect coefficient. It also gives <span class="math inline">\(\text{Cov}(b_1,b_2) = 0\)</span> exactly, which combined with <a href="#eq-fixed-random-effect-7" class="quarto-xref">Equation&nbsp;<span>7.7</span></a> yields <span class="math inline">\(\text{Var}(p_2) = \text{Var}(b_1) + \text{Var}(b_2)\)</span> and <span class="math inline">\(\text{Cov}(p_1,p_2) = -\text{Var}(b_1)\)</span>.</p>
<p>All of this is checkable on the chapter’s own data. We take a single regressor, weeks worked, fit both parameterisations by <code>plm</code>, and compare against the within estimator and against the variance map:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://cran.r-project.org/package=plm">plm</a></span><span class="op">)</span>; <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://panelr.jacob-long.com">panelr</a></span><span class="op">)</span>; <span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"WageData"</span><span class="op">)</span></span>
<span><span class="va">d</span> <span class="op">&lt;-</span> <span class="va">WageData</span></span>
<span><span class="va">d</span><span class="op">$</span><span class="va">xbar</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/ave.html">ave</a></span><span class="op">(</span><span class="va">d</span><span class="op">$</span><span class="va">wks</span>, <span class="va">d</span><span class="op">$</span><span class="va">id</span><span class="op">)</span>          <span class="co"># unit mean</span></span>
<span><span class="va">d</span><span class="op">$</span><span class="va">xdev</span> <span class="op">&lt;-</span> <span class="va">d</span><span class="op">$</span><span class="va">wks</span> <span class="op">-</span> <span class="va">d</span><span class="op">$</span><span class="va">xbar</span>            <span class="co"># within deviation</span></span>
<span></span>
<span><span class="va">fe</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/plm/man/plm.html">plm</a></span><span class="op">(</span><span class="va">lwage</span> <span class="op">~</span> <span class="va">wks</span>,          data <span class="op">=</span> <span class="va">d</span>, index <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"id"</span>, <span class="st">"t"</span><span class="op">)</span>, model <span class="op">=</span> <span class="st">"within"</span><span class="op">)</span></span>
<span><span class="va">hyb</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/plm/man/plm.html">plm</a></span><span class="op">(</span><span class="va">lwage</span> <span class="op">~</span> <span class="va">xdev</span> <span class="op">+</span> <span class="va">xbar</span>,  data <span class="op">=</span> <span class="va">d</span>, index <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"id"</span>, <span class="st">"t"</span><span class="op">)</span>, model <span class="op">=</span> <span class="st">"random"</span><span class="op">)</span></span>
<span><span class="va">mun</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/plm/man/plm.html">plm</a></span><span class="op">(</span><span class="va">lwage</span> <span class="op">~</span> <span class="va">wks</span>  <span class="op">+</span> <span class="va">xbar</span>,  data <span class="op">=</span> <span class="va">d</span>, index <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"id"</span>, <span class="st">"t"</span><span class="op">)</span>, model <span class="op">=</span> <span class="st">"random"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">b</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">hyb</span><span class="op">)</span>; <span class="va">p</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">mun</span><span class="op">)</span>; <span class="va">Vh</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/vcov.html">vcov</a></span><span class="op">(</span><span class="va">hyb</span><span class="op">)</span>; <span class="va">Vm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/vcov.html">vcov</a></span><span class="op">(</span><span class="va">mun</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  check <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"p1 - b1"</span>, <span class="st">"p2 - (b2 - b1)"</span>, <span class="st">"b1 - FE within"</span>,</span>
<span>            <span class="st">"sum(xdev * xbar)"</span>, <span class="st">"Cov(b1, b2)"</span>,</span>
<span>            <span class="st">"Var(p2) - [Var(b1) + Var(b2)]"</span>, <span class="st">"Cov(p1, p2) + Var(b1)"</span>,</span>
<span>            <span class="st">"theta(hybrid) - theta(Mundlak)"</span><span class="op">)</span>,</span>
<span>  value <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">p</span><span class="op">[</span><span class="st">"wks"</span><span class="op">]</span> <span class="op">-</span> <span class="va">b</span><span class="op">[</span><span class="st">"xdev"</span><span class="op">]</span>,</span>
<span>            <span class="va">p</span><span class="op">[</span><span class="st">"xbar"</span><span class="op">]</span> <span class="op">-</span> <span class="op">(</span><span class="va">b</span><span class="op">[</span><span class="st">"xbar"</span><span class="op">]</span> <span class="op">-</span> <span class="va">b</span><span class="op">[</span><span class="st">"xdev"</span><span class="op">]</span><span class="op">)</span>,</span>
<span>            <span class="va">b</span><span class="op">[</span><span class="st">"xdev"</span><span class="op">]</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">fe</span><span class="op">)</span><span class="op">[</span><span class="st">"wks"</span><span class="op">]</span>,</span>
<span>            <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">d</span><span class="op">$</span><span class="va">xdev</span> <span class="op">*</span> <span class="va">d</span><span class="op">$</span><span class="va">xbar</span><span class="op">)</span>,</span>
<span>            <span class="va">Vh</span><span class="op">[</span><span class="st">"xdev"</span>, <span class="st">"xbar"</span><span class="op">]</span>,</span>
<span>            <span class="va">Vm</span><span class="op">[</span><span class="st">"xbar"</span>, <span class="st">"xbar"</span><span class="op">]</span> <span class="op">-</span> <span class="op">(</span><span class="va">Vh</span><span class="op">[</span><span class="st">"xdev"</span>, <span class="st">"xdev"</span><span class="op">]</span> <span class="op">+</span> <span class="va">Vh</span><span class="op">[</span><span class="st">"xbar"</span>, <span class="st">"xbar"</span><span class="op">]</span><span class="op">)</span>,</span>
<span>            <span class="va">Vm</span><span class="op">[</span><span class="st">"wks"</span>, <span class="st">"xbar"</span><span class="op">]</span> <span class="op">+</span> <span class="va">Vh</span><span class="op">[</span><span class="st">"xdev"</span>, <span class="st">"xdev"</span><span class="op">]</span>,</span>
<span>            <span class="va">hyb</span><span class="op">$</span><span class="va">ercomp</span><span class="op">$</span><span class="va">theta</span> <span class="op">-</span> <span class="va">mun</span><span class="op">$</span><span class="va">ercomp</span><span class="op">$</span><span class="va">theta</span><span class="op">)</span>,</span>
<span>  row.names <span class="op">=</span> <span class="cn">NULL</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>                           check         value
1                        p1 - b1  2.385245e-18
2                 p2 - (b2 - b1)  7.459311e-17
3                 b1 - FE within  1.886512e-17
4               sum(xdev * xbar)  3.534950e-12
5                    Cov(b1, b2) -5.676184e-21
6  Var(p2) - [Var(b1) + Var(b2)] -4.404571e-20
7          Cov(p1, p2) + Var(b1)  2.117582e-21
8 theta(hybrid) - theta(Mundlak)  1.110223e-16</code></pre>
</div>
</div>
<p>Every entry is zero to machine precision. The two parameterisations are the same fit, the within coefficient is the fixed-effect estimate, the hybrid regressors are orthogonal, and the variance map holds as derived.</p>
</section><section id="so-why-keep-both" class="level4" data-number="7.3.1.2"><h4 data-number="7.3.1.2" class="anchored" data-anchor-id="so-why-keep-both">
<span class="header-section-number">7.3.1.2</span> So why keep both</h4>
<p>The fit is one object, but the parameterisation settles three practical things.</p>
<p><em>Which quantity is printed.</em> <span class="math inline">\(b_2\)</span> is the between effect and <span class="math inline">\(p_2\)</span> is between minus within. They are different parameters with non-interchangeable standard errors, and whichever form you fit, the other costs a <code>lincom</code>.</p>
<p><em>Which hypothesis is one line.</em> <span class="math inline">\(p_2 = 0\)</span> says between equals within, which is exactly the random-effects assumption that the regressors are uncorrelated with <span class="math inline">\(c_i\)</span>. The Mundlak form prints that as a single <span class="math inline">\(t\)</span>; in hybrid form it is the contrast <span class="math inline">\(b_1 = b_2\)</span>. The two tests agree numerically, but only one is printed. This is the Mundlak form of the Hausman test, asymptotically equivalent to the classical version and with the practical advantage of working directly with cluster-robust standard errors. The <a href="./mundlak-device.html">next chapter</a> develops it and its two-way extension for difference-in-differences.</p>
<p><em>What the second coefficient is for.</em> In multilevel work <span class="math inline">\(p_2\)</span> is not a diagnostic but the estimand: holding a pupil’s own status fixed, what does the school mean do? The hybrid’s <span class="math inline">\(b_2\)</span> answers a different question, the total between-unit association. Two literatures ask two questions of one regression, and each named the parameterisation that printed its answer. That is the honest reason both names survive.</p>
<p>There is also a reason to prefer the hybrid form in extensions. Its two regressors are exactly orthogonal, where <span class="math inline">\(x_{it}\)</span> and <span class="math inline">\(\bar x_i\)</span> are correlated. That does not change the fit, but if you want a random slope on the within component you need the deviation as its own column; a random slope on <span class="math inline">\(x_{it}\)</span> would mix within and between variation.</p>
</section><section id="where-the-equivalence-stops" class="level4" data-number="7.3.1.3"><h4 data-number="7.3.1.3" class="anchored" data-anchor-id="where-the-equivalence-stops">
<span class="header-section-number">7.3.1.3</span> Where the equivalence stops</h4>
<p>The reparameterisation is exact for anything with a linear index, logit and Poisson mixed models included, since <span class="math inline">\(XA\)</span> spans the same space and the index is unchanged. The two names stay interchangeable there.</p>
<p>The fixed-effect identity does not carry over. The proof above used two linear-model facts: that random effects is OLS on quasi-demeaned data, and that <span class="math inline">\(d\)</span> is orthogonal to group constants. A logit or Poisson mixed model has no such transform, the unit effects do not sweep out, and the hybrid within coefficient is not the conditional-logit estimate but an approximation to it. Keep the two claims separate: the parameterisations are always the same model, while “within coefficient equals fixed effects” is a linear-model result. The last section of this chapter returns to that point.</p>
</section></section></section><section id="bw-model-in-r" class="level2" data-number="7.4"><h2 data-number="7.4" class="anchored" data-anchor-id="bw-model-in-r">
<span class="header-section-number">7.4</span> BW model in R</h2>
<p>R’s <a href="https://panelr.jacob-long.com/articles/wbm.html"><code>panelr</code></a> package implements BW models directly. The data are <code>WageData</code>, a balanced panel of 595 men observed over 7 years. We model log wage on weeks worked, union membership, marital status and occupation, all time-varying, plus two time-invariant covariates — black and female — that a fixed-effect model could not touch.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://panelr.jacob-long.com">panelr</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"WageData"</span><span class="op">)</span></span>
<span><span class="va">wages</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://panelr.jacob-long.com/reference/panel_data.html">panel_data</a></span><span class="op">(</span><span class="va">WageData</span>, id <span class="op">=</span> <span class="va">id</span>, wave <span class="op">=</span> <span class="va">t</span><span class="op">)</span></span>
<span><span class="va">model1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://panelr.jacob-long.com/reference/wbm.html">wbm</a></span><span class="op">(</span><span class="va">lwage</span> <span class="op">~</span> <span class="va">wks</span> <span class="op">+</span> <span class="va">union</span> <span class="op">+</span> <span class="va">ms</span> <span class="op">+</span> <span class="va">occ</span> <span class="op">|</span> <span class="va">blk</span> <span class="op">+</span> <span class="va">fem</span>, data <span class="op">=</span> <span class="va">wages</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model1</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>MODEL INFO:
Entities: 595
Time periods: 1-7
Dependent variable: lwage
Model type: Linear mixed effects
Specification: within-between

MODEL FIT:
AIC = 2036.78, BIC = 2119.13
Pseudo-R² (fixed effects) = 0.27
Pseudo-R² (total) = 0.69
Entity ICC = 0.57

WITHIN EFFECTS:
------------------------------------------
               Est.   S.E.   t val.      p
----------- ------- ------ -------- ------
wks            0.00   0.00     1.06   0.29
union          0.06   0.03     2.53   0.01
ms            -0.08   0.03    -2.57   0.01
occ           -0.08   0.02    -3.32   0.00
------------------------------------------

BETWEEN EFFECTS:
-------------------------------------------------
                      Est.   S.E.   t val.      p
------------------ ------- ------ -------- ------
(Intercept)           6.30   0.20    30.85   0.00
imean(wks)            0.01   0.00     2.25   0.02
imean(union)          0.15   0.03     4.67   0.00
imean(ms)             0.17   0.05     3.07   0.00
imean(occ)           -0.41   0.03   -13.31   0.00
blk                  -0.15   0.05    -2.81   0.00
fem                  -0.32   0.06    -4.96   0.00
-------------------------------------------------

p values calculated using df = 4153 
 
RANDOM EFFECTS:
------------------------------------
  Group      Parameter    Std. Dev. 
---------- ------------- -----------
    id      (Intercept)    0.2992   
 Residual                  0.2589   
------------------------------------</code></pre>
</div>
</div>
<p>The within estimates are 0.00 for weeks, 0.06 for union, <span class="math inline">\(-0.08\)</span> for married and <span class="math inline">\(-0.08\)</span> for occupation. The between estimates for the same four variables are 0.01, 0.15, 0.17 and <span class="math inline">\(-0.41\)</span> — two to five times larger, and for <code>ms</code> the opposite sign. That gap is the reason the fixed-versus-random choice matters here: a random-effects model without the decomposition would blend the two and report neither. The time-invariant covariates come out at <span class="math inline">\(-0.15\)</span> for black and <span class="math inline">\(-0.32\)</span> for female, quantities a fixed-effect model cannot produce at all.</p>
<p>Compare with <code>lfe</code>.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/r-econometrics/lfe">lfe</a></span><span class="op">)</span></span>
<span><span class="va">model2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/lfe/man/felm.html">felm</a></span><span class="op">(</span><span class="va">lwage</span> <span class="op">~</span> <span class="va">wks</span> <span class="op">+</span> <span class="va">union</span> <span class="op">+</span> <span class="va">ms</span> <span class="op">+</span> <span class="va">occ</span> <span class="op">|</span> <span class="va">id</span>, data <span class="op">=</span> <span class="va">wages</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model2</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
Call:
   felm(formula = lwage ~ wks + union + ms + occ | id, data = wages) 

Residuals:
     Min       1Q   Median       3Q      Max 
-1.89500 -0.16174  0.00652  0.17060  1.94521 

Coefficients:
       Estimate Std. Error t value Pr(&gt;|t|)    
wks    0.001083   0.001019   1.063 0.287816    
union  0.064320   0.025378   2.534 0.011305 *  
ms    -0.082905   0.032226  -2.573 0.010132 *  
occ   -0.077507   0.023359  -3.318 0.000916 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2589 on 3566 degrees of freedom
Multiple R-squared(full model): 0.7304   Adjusted R-squared: 0.6852 
Multiple R-squared(proj model): 0.006509   Adjusted R-squared: -0.1601 
F-statistic(full model):16.16 on 598 and 3566 DF, p-value: &lt; 2.2e-16 
F-statistic(proj model): 5.841 on 4 and 3566 DF, p-value: 0.0001106 </code></pre>
</div>
</div>
<p><code>felm</code> gives 0.001083, 0.064320, <span class="math inline">\(-0.082905\)</span> and <span class="math inline">\(-0.077507\)</span> — the same four numbers <code>panelr</code> reported as within effects, identical to machine precision (<code>WageData</code> is a balanced panel: 7 waves, 595 individuals). That is the BW model’s selling point: it reproduces the fixed-effect estimates exactly while also estimating the time-invariant covariates <code>blk</code> and <code>fem</code>, which <code>felm</code> cannot. <code>lfe</code> supports clustered standard errors, which <code>panelr</code> does not.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/lfe/man/felm.html">felm</a></span><span class="op">(</span><span class="va">lwage</span> <span class="op">~</span> <span class="va">wks</span> <span class="op">+</span> <span class="va">union</span> <span class="op">+</span> <span class="va">ms</span> <span class="op">+</span> <span class="va">occ</span> <span class="op">|</span> <span class="va">id</span> <span class="op">|</span> <span class="fl">0</span> <span class="op">|</span> <span class="va">id</span>, data <span class="op">=</span> <span class="va">wages</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model3</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
Call:
   felm(formula = lwage ~ wks + union + ms + occ | id | 0 | id,      data = wages) 

Residuals:
     Min       1Q   Median       3Q      Max 
-1.89500 -0.16174  0.00652  0.17060  1.94521 

Coefficients:
       Estimate Cluster s.e. t value Pr(&gt;|t|)  
wks    0.001083     0.001331   0.814   0.4160  
union  0.064320     0.040936   1.571   0.1167  
ms    -0.082905     0.047399  -1.749   0.0808 .
occ   -0.077507     0.031320  -2.475   0.0136 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2589 on 3566 degrees of freedom
Multiple R-squared(full model): 0.7304   Adjusted R-squared: 0.6852 
Multiple R-squared(proj model): 0.006509   Adjusted R-squared: -0.1601 
F-statistic(full model, *iid*):16.16 on 598 and 3566 DF, p-value: &lt; 2.2e-16 
F-statistic(proj model): 3.456 on 4 and 594 DF, p-value: 0.008358 </code></pre>
</div>
</div>
<p>Clustering on <code>id</code> leaves every coefficient untouched and changes the standard errors substantially: <code>union</code> goes from 0.0254 to 0.0409, <code>ms</code> from 0.0322 to 0.0474, <code>wks</code> from 0.00102 to 0.00133. Two of the four results do not survive. <code>union</code> falls from <span class="math inline">\(p = 0.011\)</span> to <span class="math inline">\(p = 0.117\)</span> and <code>ms</code> from <span class="math inline">\(0.010\)</span> to <span class="math inline">\(0.081\)</span>; only <code>occ</code> stays significant at 5%. With 7 observations per man the residuals are serially correlated, and the unclustered standard errors were treating 4,165 observations as though they were independent draws.</p>
</section><section id="bw-model-in-stata" class="level2" data-number="7.5"><h2 data-number="7.5" class="anchored" data-anchor-id="bw-model-in-stata">
<span class="header-section-number">7.5</span> BW model in Stata</h2>
<p>Stata has no dedicated BW command, but <code>xtreg</code> suffices. We switch to <code>nlswork</code>, an unbalanced panel of 4,710 women over 28,510 person-years, and regress log wage on age.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">webuse</span> nlswork</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>xtset idcode</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="kw">xtreg</span> ln_w age, <span class="kw">fe</span> <span class="kw">cluster</span>(idcode)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>(National Longitudinal Survey of Young Women, 14-24 years old in 1968)


Panel variable: idcode (unbalanced)


Fixed-effects (within) regression               Number of obs     =     28,510
Group variable: idcode                          Number of groups  =      4,710

R-squared:                                      Obs per group:
     Within  = 0.1026                                         min =          1
     Between = 0.0877                                         avg =        6.1
     Overall = 0.0774                                         max =         15

                                                F(1, 4709)        =     884.05
corr(u_i, Xb) = 0.0314                          Prob &gt; F          =     0.0000

                             (Std. err. adjusted for 4,710 clusters in idcode)
------------------------------------------------------------------------------
             |               Robust
     ln_wage | Coefficient  std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
         age |   .0181349   .0006099    29.73   0.000     .0169392    .0193306
       _cons |   1.148214   .0177153    64.81   0.000     1.113483    1.182944
-------------+----------------------------------------------------------------
     sigma_u |  .40635023
     sigma_e |  .30349389
         rho |  .64192015   (fraction of variance due to u_i)
------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>The fixed-effect estimate is <span class="math inline">\(.0181349\)</span> with a clustered standard error of <span class="math inline">\(.0006099\)</span>: within a woman, each additional year of age raises log wage by about 1.8%. Keep that number in view — the BW model has to reproduce it.</p>
<p>Generate the group mean and run the BW estimation.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="kw">webuse</span> nlswork</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>xtset idcode</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="kw">bysort</span> idcode: <span class="bn">center</span> age, <span class="kw">prefix</span>(<span class="kw">d</span>) <span class="kw">mean</span>(<span class="fu">m</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="kw">xtreg</span> ln_w dage mage i.race, re <span class="kw">cluster</span>(idcode)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>(National Longitudinal Survey of Young Women, 14-24 years old in 1968)


Panel variable: idcode (unbalanced)

(generated variables: dage mage)


Random-effects GLS regression                   Number of obs     =     28,510
Group variable: idcode                          Number of groups  =      4,710

R-squared:                                      Obs per group:
     Within  = 0.1026                                         min =          1
     Between = 0.1040                                         avg =        6.1
     Overall = 0.0950                                         max =         15

                                                Wald chi2(4)      =    1335.89
corr(u_i, X) = 0 (assumed)                      Prob &gt; chi2       =     0.0000

                             (Std. err. adjusted for 4,710 clusters in idcode)
------------------------------------------------------------------------------
             |               Robust
     ln_wage | Coefficient  std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
        dage |   .0181349     .00061    29.73   0.000     .0169394    .0193304
        mage |    .022558   .0011405    19.78   0.000     .0203226    .0247933
             |
        race |
      Black  |  -.1190246   .0127418    -9.34   0.000    -.1439982   -.0940511
      Other  |   .0974996   .0617364     1.58   0.114    -.0235016    .2185008
             |
       _cons |   1.037566   .0323185    32.10   0.000     .9742233     1.10091
-------------+----------------------------------------------------------------
     sigma_u |  .36581005
     sigma_e |  .30349389
         rho |  .59230575   (fraction of variance due to u_i)
------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>In this BW model, we use the centered (within-group-demeaned) <code>dage</code> together with the group mean <code>mage</code>, which gives the standard within-between (Mundlak) decomposition: the coefficient on <code>dage</code>, .0181349, is exactly the fixed-effect (“within”) coefficient on age reported above — the same seven digits, with a standard error of .00061 against .0006099 — and the coefficient on <code>mage</code>, .022558, is directly the between effect. Women who are older on average earn about 2.3% more per year of average age, against a within-woman return of 1.8%; the between effect is larger because it also carries cohort and selection differences that the within estimate sweeps out. And we have the effect of time-invariant covariate race estimated: Black women earn 11.9% less (<span class="math inline">\(-.1190246\)</span>, SE .0127), while the “Other” category is not distinguishable from white (<span class="math inline">\(.0975\)</span>, <span class="math inline">\(p = 0.114\)</span>). The advantage of using xtreg is that we have clustered standard errors implemented.</p>
<p>Note: if we instead ran <code>xtreg ln_w age mage i.race, re cluster(idcode)</code> — using the raw (uncentered) <code>age</code> together with <code>mage</code> — we would get the <em>contextual model</em> instead: the coefficient on <code>age</code> stays .0181, but the coefficient on <code>mage</code> becomes .0044, the “contextual effect” (the <em>additional</em> between-effect on top of the within effect). The two models are algebraically related: contextual-model mage = Mundlak-model mage − Mundlak-model dage (here, .0226 − .0181 ≈ .0044).</p>
</section><section id="bw-model-in-non-linear-models" class="level2" data-number="7.6"><h2 data-number="7.6" class="anchored" data-anchor-id="bw-model-in-non-linear-models">
<span class="header-section-number">7.6</span> BW model in non-linear models</h2>
<p><a href="https://statisticalhorizons.com/between-within-contextual-effects">Allison</a> applies the BW model to binary outcomes. The bias relative to conditional logit is an open question, but if the linear probability model is a reasonable approximation the BW approach should perform similarly for binary panel data.</p>


<!-- -->

</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/xiangao\.github\.io\/blog_book\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./comparing-margins.html" class="pagination-link" aria-label="Comparing Marginal effects with margins command">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Comparing Marginal effects with margins command</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./mundlak-device.html" class="pagination-link" aria-label="Mundlak device in fixed effect models">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Mundlak device in fixed effect models</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Fixed or Random Effect, or Both?"</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2019-05-23"</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="fu">## Panel data</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>With panel data — repeated observations over time or observations clustered at a higher level — the standard choice is between fixed and random effects. Consider</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>$$ y_{it} = \beta_0 + \beta_1 x_{it} + c_i + \epsilon_{it} $$ {#eq-fixed-random-effect-1}</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>for individuals $i = 1, \ldots, n$ measured at $t = 1, \ldots, T$, where $c_i$ is an unobserved time-invariant individual effect. The two approaches differ in how they handle $c_i$.</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>Fixed effects eliminate $c_i$ by demeaning or by including individual dummies (the two are equivalent in a linear model). In nonlinear models only Poisson avoids the incidental-parameter problem; the standard solution for other models is conditional likelihood (conditional logit, for example), which absorbs the fixed effects in the likelihood. When no conditional likelihood exists, the incidental-parameter bias shrinks with panel depth but does not vanish.</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>Random effects treat $c_i$ as part of the error term. This is more efficient but requires $x_{it}$ to be uncorrelated with $c_i$ — an assumption economists are generally skeptical of.</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a><span class="fu">## Time-invariant variables</span></span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>Sometimes we want the effect of a time-invariant variable, so the model becomes</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>$$ y_{it} = \beta_0  + \beta_1 x_{it} + c_i  + \gamma z_i+ \epsilon_{it} $$ {#eq-fixed-random-effect-2}</span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>Fixed effects cannot identify $\gamma$ because $z_i$ is perfectly collinear with $c_i$. Random effects can still estimate both, treating $z_i$ as another covariate.</span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a><span class="fu">## Between-within model</span></span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a>The textbook advice is a Hausman test: random effects are more efficient when the uncorrelatedness assumption holds; if not, fixed effects are still consistent. The between-within model (BW) sidesteps the choice. <span class="co">[</span><span class="ot">Neuhaus and Kalbfleisch (1998)</span><span class="co">](https://www.ncbi.nlm.nih.gov/pubmed/9629647)</span> introduced the BW estimator,</span>
<span id="cb13-31"><a href="#cb13-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-32"><a href="#cb13-32" aria-hidden="true" tabindex="-1"></a>$$ y_{it} = \beta_0  + \beta_1 (x_{it} - \bar x_i) + \beta_2 \bar x_i + c_i  + \gamma z_i+ \epsilon_{it} $$ {#eq-fixed-random-effect-3}</span>
<span id="cb13-33"><a href="#cb13-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-34"><a href="#cb13-34" aria-hidden="true" tabindex="-1"></a>Here $\beta_1$ is the within effect — identical to the fixed-effect coefficient. $\beta_2$ is the between effect (mean of $x$ on mean of $y$). $\gamma$ is the effect of the time-invariant variable.</span>
<span id="cb13-35"><a href="#cb13-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-36"><a href="#cb13-36" aria-hidden="true" tabindex="-1"></a>The other specification of BW estimator is</span>
<span id="cb13-37"><a href="#cb13-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-38"><a href="#cb13-38" aria-hidden="true" tabindex="-1"></a>$$ y_{it} = \beta_0  + \beta_1 x_{it}  + \beta_2 \bar x_i + c_i  + \gamma z_i+ \epsilon_{it} $$ {#eq-fixed-random-effect-4}</span>
<span id="cb13-39"><a href="#cb13-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-40"><a href="#cb13-40" aria-hidden="true" tabindex="-1"></a>This is the same model reparametrized. $\beta_1$ is unchanged, and $\beta_2$ is now the between-minus-within difference (substitute $\beta_1(x_{it}-\bar x_i) + \beta_2 \bar x_i = \beta_1 x_{it} + (\beta_2-\beta_1)\bar x_i$ to see this). This is the "contextual model"; $\beta_2$ is the contextual effect and acts as an embedded Hausman test.</span>
<span id="cb13-41"><a href="#cb13-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-42"><a href="#cb13-42" aria-hidden="true" tabindex="-1"></a>The BW model has two advantages. It recovers the fixed-effect coefficient while estimating time-invariant covariates. And it extends naturally to cross-level interactions, random slopes, and other multilevel structures. Implementation is straightforward: run a random-effects model on either equation above.</span>
<span id="cb13-43"><a href="#cb13-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-44"><a href="#cb13-44" aria-hidden="true" tabindex="-1"></a><span class="fu">### Is this just Mundlak?</span></span>
<span id="cb13-45"><a href="#cb13-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-46"><a href="#cb13-46" aria-hidden="true" tabindex="-1"></a>Yes. @eq-fixed-random-effect-4 *is* the Mundlak device: Mundlak's regression puts</span>
<span id="cb13-47"><a href="#cb13-47" aria-hidden="true" tabindex="-1"></a>$x_{it}$ and $\bar x_i$ on the right-hand side of a random-effects model, which is</span>
<span id="cb13-48"><a href="#cb13-48" aria-hidden="true" tabindex="-1"></a>exactly what that equation does. So the between-within model and the Mundlak</span>
<span id="cb13-49"><a href="#cb13-49" aria-hidden="true" tabindex="-1"></a>device are one model in two parameterisations, fitted by the same random-effects</span>
<span id="cb13-50"><a href="#cb13-50" aria-hidden="true" tabindex="-1"></a>command. It is worth doing the algebra, because the identity is easy to state</span>
<span id="cb13-51"><a href="#cb13-51" aria-hidden="true" tabindex="-1"></a>loosely and easy to get wrong on the inference side.</span>
<span id="cb13-52"><a href="#cb13-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-53"><a href="#cb13-53" aria-hidden="true" tabindex="-1"></a>Write $d_{it} = x_{it} - \bar x_i$ for the within deviation, and label the two</span>
<span id="cb13-54"><a href="#cb13-54" aria-hidden="true" tabindex="-1"></a>specifications by their coefficients: $b_1, b_2$ for the hybrid form</span>
<span id="cb13-55"><a href="#cb13-55" aria-hidden="true" tabindex="-1"></a>@eq-fixed-random-effect-3 and $p_1, p_2$ for the contextual form</span>
<span id="cb13-56"><a href="#cb13-56" aria-hidden="true" tabindex="-1"></a>@eq-fixed-random-effect-4. Expanding the hybrid regressor block,</span>
<span id="cb13-57"><a href="#cb13-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-58"><a href="#cb13-58" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb13-59"><a href="#cb13-59" aria-hidden="true" tabindex="-1"></a>b_1 (x_{it} - \bar x_i) + b_2 \bar x_i = b_1 x_{it} + (b_2 - b_1)\bar x_i ,</span>
<span id="cb13-60"><a href="#cb13-60" aria-hidden="true" tabindex="-1"></a>$$ {#eq-fixed-random-effect-5}</span>
<span id="cb13-61"><a href="#cb13-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-62"><a href="#cb13-62" aria-hidden="true" tabindex="-1"></a>so $p_1 = b_1$ and $p_2 = b_2 - b_1$. Substitution shows the map, but the reason</span>
<span id="cb13-63"><a href="#cb13-63" aria-hidden="true" tabindex="-1"></a>behind it is worth stating more strongly: the two regressor matrices are related</span>
<span id="cb13-64"><a href="#cb13-64" aria-hidden="true" tabindex="-1"></a>by an invertible linear transformation. With $X = <span class="co">[</span><span class="ot">\,x_{it}, \bar x_i\,</span><span class="co">]</span>$ and</span>
<span id="cb13-65"><a href="#cb13-65" aria-hidden="true" tabindex="-1"></a>$W = <span class="co">[</span><span class="ot">\,d_{it}, \bar x_i\,</span><span class="co">]</span>$,</span>
<span id="cb13-66"><a href="#cb13-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-67"><a href="#cb13-67" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb13-68"><a href="#cb13-68" aria-hidden="true" tabindex="-1"></a>W = XA, \qquad</span>
<span id="cb13-69"><a href="#cb13-69" aria-hidden="true" tabindex="-1"></a>A = \begin{pmatrix} 1 &amp; 0 <span class="sc">\\</span> -1 &amp; 1 \end{pmatrix}, \qquad</span>
<span id="cb13-70"><a href="#cb13-70" aria-hidden="true" tabindex="-1"></a>A^{-1} = \begin{pmatrix} 1 &amp; 0 <span class="sc">\\</span> 1 &amp; 1 \end{pmatrix},</span>
<span id="cb13-71"><a href="#cb13-71" aria-hidden="true" tabindex="-1"></a>$$ {#eq-fixed-random-effect-6}</span>
<span id="cb13-72"><a href="#cb13-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-73"><a href="#cb13-73" aria-hidden="true" tabindex="-1"></a>and $\det A = 1$, so the two designs span the same column space. Everything that</span>
<span id="cb13-74"><a href="#cb13-74" aria-hidden="true" tabindex="-1"></a>depends only on that space is numerically identical: fitted values, residuals,</span>
<span id="cb13-75"><a href="#cb13-75" aria-hidden="true" tabindex="-1"></a>the likelihood, the estimated variance components, and the GLS quasi-demeaning</span>
<span id="cb13-76"><a href="#cb13-76" aria-hidden="true" tabindex="-1"></a>weight $\theta$. Only the coordinates change, by</span>
<span id="cb13-77"><a href="#cb13-77" aria-hidden="true" tabindex="-1"></a>$b = A^{-1}p$, and the covariance matrix by $\text{Var}(b) = A^{-1}\text{Var}(p)A^{-1\prime}$.</span>
<span id="cb13-78"><a href="#cb13-78" aria-hidden="true" tabindex="-1"></a>Componentwise that is</span>
<span id="cb13-79"><a href="#cb13-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-80"><a href="#cb13-80" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb13-81"><a href="#cb13-81" aria-hidden="true" tabindex="-1"></a>\text{Var}(p_1) = \text{Var}(b_1), \qquad</span>
<span id="cb13-82"><a href="#cb13-82" aria-hidden="true" tabindex="-1"></a>\text{Var}(p_2) = \text{Var}(b_1) + \text{Var}(b_2) + 2\,\text{Cov}(b_1,b_2),</span>
<span id="cb13-83"><a href="#cb13-83" aria-hidden="true" tabindex="-1"></a>$$ {#eq-fixed-random-effect-7}</span>
<span id="cb13-84"><a href="#cb13-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-85"><a href="#cb13-85" aria-hidden="true" tabindex="-1"></a>which already says something useful: the standard error printed next to the</span>
<span id="cb13-86"><a href="#cb13-86" aria-hidden="true" tabindex="-1"></a>between effect is not the standard error you want for the contextual effect.</span>
<span id="cb13-87"><a href="#cb13-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-88"><a href="#cb13-88" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Why the within coefficient is the fixed-effect estimator</span></span>
<span id="cb13-89"><a href="#cb13-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-90"><a href="#cb13-90" aria-hidden="true" tabindex="-1"></a>This part needs a proof rather than a substitution. The relevant fact is that</span>
<span id="cb13-91"><a href="#cb13-91" aria-hidden="true" tabindex="-1"></a>$\sum_t d_{it} = 0$ within every unit by construction, so $d$ is orthogonal to</span>
<span id="cb13-92"><a href="#cb13-92" aria-hidden="true" tabindex="-1"></a>any group-invariant column: for $v_i$ constant within $i$,</span>
<span id="cb13-93"><a href="#cb13-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-94"><a href="#cb13-94" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb13-95"><a href="#cb13-95" aria-hidden="true" tabindex="-1"></a>\sum_{i,t} d_{it} v_i = \sum_i v_i \sum_t d_{it} = 0 ,</span>
<span id="cb13-96"><a href="#cb13-96" aria-hidden="true" tabindex="-1"></a>$$ {#eq-fixed-random-effect-8}</span>
<span id="cb13-97"><a href="#cb13-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-98"><a href="#cb13-98" aria-hidden="true" tabindex="-1"></a>which covers the intercept, $\bar x_i$ and $z_i$ alike.</span>
<span id="cb13-99"><a href="#cb13-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-100"><a href="#cb13-100" aria-hidden="true" tabindex="-1"></a>Random effects is OLS after quasi-demeaning, $\tilde w_{it} = w_{it} - \theta \bar w_i$</span>
<span id="cb13-101"><a href="#cb13-101" aria-hidden="true" tabindex="-1"></a>with $\theta = 1 - \sqrt{\sigma^2_\epsilon / (\sigma^2_\epsilon + T\sigma^2_c)}$.</span>
<span id="cb13-102"><a href="#cb13-102" aria-hidden="true" tabindex="-1"></a>Apply it to the hybrid regressors. Because $\bar d_i = 0$ we get</span>
<span id="cb13-103"><a href="#cb13-103" aria-hidden="true" tabindex="-1"></a>$\tilde d_{it} = d_{it}$: the within-deviation regressor passes through the GLS</span>
<span id="cb13-104"><a href="#cb13-104" aria-hidden="true" tabindex="-1"></a>transform untouched, whatever $\theta$ is. The remaining regressors are</span>
<span id="cb13-105"><a href="#cb13-105" aria-hidden="true" tabindex="-1"></a>group-invariant and stay so after scaling by $1-\theta$. Orthogonality therefore</span>
<span id="cb13-106"><a href="#cb13-106" aria-hidden="true" tabindex="-1"></a>survives the transform, and by Frisch-Waugh-Lovell</span>
<span id="cb13-107"><a href="#cb13-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-108"><a href="#cb13-108" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb13-109"><a href="#cb13-109" aria-hidden="true" tabindex="-1"></a>b_1 = \frac{\sum d_{it}\tilde y_{it}}{\sum d_{it}^2}</span>
<span id="cb13-110"><a href="#cb13-110" aria-hidden="true" tabindex="-1"></a>    = \frac{\sum d_{it} y_{it}}{\sum d_{it}^2}</span>
<span id="cb13-111"><a href="#cb13-111" aria-hidden="true" tabindex="-1"></a>    = \frac{\sum (x_{it}-\bar x_i)(y_{it}-\bar y_i)}{\sum (x_{it}-\bar x_i)^2},</span>
<span id="cb13-112"><a href="#cb13-112" aria-hidden="true" tabindex="-1"></a>$$ {#eq-fixed-random-effect-9}</span>
<span id="cb13-113"><a href="#cb13-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-114"><a href="#cb13-114" aria-hidden="true" tabindex="-1"></a>the second and third equalities both by @eq-fixed-random-effect-8. That last</span>
<span id="cb13-115"><a href="#cb13-115" aria-hidden="true" tabindex="-1"></a>expression is the within estimator. Note that $\theta$ has dropped out, so the</span>
<span id="cb13-116"><a href="#cb13-116" aria-hidden="true" tabindex="-1"></a>identity holds for *any* $\theta$ — for random effects, for pooled OLS</span>
<span id="cb13-117"><a href="#cb13-117" aria-hidden="true" tabindex="-1"></a>($\theta = 0$) and for fixed effects ($\theta = 1$). That is why running a</span>
<span id="cb13-118"><a href="#cb13-118" aria-hidden="true" tabindex="-1"></a>random-effects model on either equation returns the fixed-effect coefficient. It</span>
<span id="cb13-119"><a href="#cb13-119" aria-hidden="true" tabindex="-1"></a>also gives $\text{Cov}(b_1,b_2) = 0$ exactly, which combined with</span>
<span id="cb13-120"><a href="#cb13-120" aria-hidden="true" tabindex="-1"></a>@eq-fixed-random-effect-7 yields</span>
<span id="cb13-121"><a href="#cb13-121" aria-hidden="true" tabindex="-1"></a>$\text{Var}(p_2) = \text{Var}(b_1) + \text{Var}(b_2)$ and</span>
<span id="cb13-122"><a href="#cb13-122" aria-hidden="true" tabindex="-1"></a>$\text{Cov}(p_1,p_2) = -\text{Var}(b_1)$.</span>
<span id="cb13-123"><a href="#cb13-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-124"><a href="#cb13-124" aria-hidden="true" tabindex="-1"></a>All of this is checkable on the chapter's own data. We take a single regressor,</span>
<span id="cb13-125"><a href="#cb13-125" aria-hidden="true" tabindex="-1"></a>weeks worked, fit both parameterisations by <span class="in">`plm`</span>, and compare against the</span>
<span id="cb13-126"><a href="#cb13-126" aria-hidden="true" tabindex="-1"></a>within estimator and against the variance map:</span>
<span id="cb13-127"><a href="#cb13-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-130"><a href="#cb13-130" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-131"><a href="#cb13-131" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: bw-mundlak-identity</span></span>
<span id="cb13-132"><a href="#cb13-132" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb13-133"><a href="#cb13-133" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb13-134"><a href="#cb13-134" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb13-135"><a href="#cb13-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-136"><a href="#cb13-136" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plm); <span class="fu">library</span>(panelr); <span class="fu">data</span>(<span class="st">"WageData"</span>)</span>
<span id="cb13-137"><a href="#cb13-137" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> WageData</span>
<span id="cb13-138"><a href="#cb13-138" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>xbar <span class="ot">&lt;-</span> <span class="fu">ave</span>(d<span class="sc">$</span>wks, d<span class="sc">$</span>id)          <span class="co"># unit mean</span></span>
<span id="cb13-139"><a href="#cb13-139" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>xdev <span class="ot">&lt;-</span> d<span class="sc">$</span>wks <span class="sc">-</span> d<span class="sc">$</span>xbar            <span class="co"># within deviation</span></span>
<span id="cb13-140"><a href="#cb13-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-141"><a href="#cb13-141" aria-hidden="true" tabindex="-1"></a>fe  <span class="ot">&lt;-</span> <span class="fu">plm</span>(lwage <span class="sc">~</span> wks,          <span class="at">data =</span> d, <span class="at">index =</span> <span class="fu">c</span>(<span class="st">"id"</span>, <span class="st">"t"</span>), <span class="at">model =</span> <span class="st">"within"</span>)</span>
<span id="cb13-142"><a href="#cb13-142" aria-hidden="true" tabindex="-1"></a>hyb <span class="ot">&lt;-</span> <span class="fu">plm</span>(lwage <span class="sc">~</span> xdev <span class="sc">+</span> xbar,  <span class="at">data =</span> d, <span class="at">index =</span> <span class="fu">c</span>(<span class="st">"id"</span>, <span class="st">"t"</span>), <span class="at">model =</span> <span class="st">"random"</span>)</span>
<span id="cb13-143"><a href="#cb13-143" aria-hidden="true" tabindex="-1"></a>mun <span class="ot">&lt;-</span> <span class="fu">plm</span>(lwage <span class="sc">~</span> wks  <span class="sc">+</span> xbar,  <span class="at">data =</span> d, <span class="at">index =</span> <span class="fu">c</span>(<span class="st">"id"</span>, <span class="st">"t"</span>), <span class="at">model =</span> <span class="st">"random"</span>)</span>
<span id="cb13-144"><a href="#cb13-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-145"><a href="#cb13-145" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">coef</span>(hyb); p <span class="ot">&lt;-</span> <span class="fu">coef</span>(mun); Vh <span class="ot">&lt;-</span> <span class="fu">vcov</span>(hyb); Vm <span class="ot">&lt;-</span> <span class="fu">vcov</span>(mun)</span>
<span id="cb13-146"><a href="#cb13-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-147"><a href="#cb13-147" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb13-148"><a href="#cb13-148" aria-hidden="true" tabindex="-1"></a>  <span class="at">check =</span> <span class="fu">c</span>(<span class="st">"p1 - b1"</span>, <span class="st">"p2 - (b2 - b1)"</span>, <span class="st">"b1 - FE within"</span>,</span>
<span id="cb13-149"><a href="#cb13-149" aria-hidden="true" tabindex="-1"></a>            <span class="st">"sum(xdev * xbar)"</span>, <span class="st">"Cov(b1, b2)"</span>,</span>
<span id="cb13-150"><a href="#cb13-150" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Var(p2) - [Var(b1) + Var(b2)]"</span>, <span class="st">"Cov(p1, p2) + Var(b1)"</span>,</span>
<span id="cb13-151"><a href="#cb13-151" aria-hidden="true" tabindex="-1"></a>            <span class="st">"theta(hybrid) - theta(Mundlak)"</span>),</span>
<span id="cb13-152"><a href="#cb13-152" aria-hidden="true" tabindex="-1"></a>  <span class="at">value =</span> <span class="fu">c</span>(p[<span class="st">"wks"</span>] <span class="sc">-</span> b[<span class="st">"xdev"</span>],</span>
<span id="cb13-153"><a href="#cb13-153" aria-hidden="true" tabindex="-1"></a>            p[<span class="st">"xbar"</span>] <span class="sc">-</span> (b[<span class="st">"xbar"</span>] <span class="sc">-</span> b[<span class="st">"xdev"</span>]),</span>
<span id="cb13-154"><a href="#cb13-154" aria-hidden="true" tabindex="-1"></a>            b[<span class="st">"xdev"</span>] <span class="sc">-</span> <span class="fu">coef</span>(fe)[<span class="st">"wks"</span>],</span>
<span id="cb13-155"><a href="#cb13-155" aria-hidden="true" tabindex="-1"></a>            <span class="fu">sum</span>(d<span class="sc">$</span>xdev <span class="sc">*</span> d<span class="sc">$</span>xbar),</span>
<span id="cb13-156"><a href="#cb13-156" aria-hidden="true" tabindex="-1"></a>            Vh[<span class="st">"xdev"</span>, <span class="st">"xbar"</span>],</span>
<span id="cb13-157"><a href="#cb13-157" aria-hidden="true" tabindex="-1"></a>            Vm[<span class="st">"xbar"</span>, <span class="st">"xbar"</span>] <span class="sc">-</span> (Vh[<span class="st">"xdev"</span>, <span class="st">"xdev"</span>] <span class="sc">+</span> Vh[<span class="st">"xbar"</span>, <span class="st">"xbar"</span>]),</span>
<span id="cb13-158"><a href="#cb13-158" aria-hidden="true" tabindex="-1"></a>            Vm[<span class="st">"wks"</span>, <span class="st">"xbar"</span>] <span class="sc">+</span> Vh[<span class="st">"xdev"</span>, <span class="st">"xdev"</span>],</span>
<span id="cb13-159"><a href="#cb13-159" aria-hidden="true" tabindex="-1"></a>            hyb<span class="sc">$</span>ercomp<span class="sc">$</span>theta <span class="sc">-</span> mun<span class="sc">$</span>ercomp<span class="sc">$</span>theta),</span>
<span id="cb13-160"><a href="#cb13-160" aria-hidden="true" tabindex="-1"></a>  <span class="at">row.names =</span> <span class="cn">NULL</span>)</span>
<span id="cb13-161"><a href="#cb13-161" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-162"><a href="#cb13-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-163"><a href="#cb13-163" aria-hidden="true" tabindex="-1"></a>Every entry is zero to machine precision. The two parameterisations are the same</span>
<span id="cb13-164"><a href="#cb13-164" aria-hidden="true" tabindex="-1"></a>fit, the within coefficient is the fixed-effect estimate, the hybrid regressors</span>
<span id="cb13-165"><a href="#cb13-165" aria-hidden="true" tabindex="-1"></a>are orthogonal, and the variance map holds as derived.</span>
<span id="cb13-166"><a href="#cb13-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-167"><a href="#cb13-167" aria-hidden="true" tabindex="-1"></a><span class="fu">#### So why keep both</span></span>
<span id="cb13-168"><a href="#cb13-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-169"><a href="#cb13-169" aria-hidden="true" tabindex="-1"></a>The fit is one object, but the parameterisation settles three practical things.</span>
<span id="cb13-170"><a href="#cb13-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-171"><a href="#cb13-171" aria-hidden="true" tabindex="-1"></a>*Which quantity is printed.* $b_2$ is the between effect and $p_2$ is between</span>
<span id="cb13-172"><a href="#cb13-172" aria-hidden="true" tabindex="-1"></a>minus within. They are different parameters with non-interchangeable standard</span>
<span id="cb13-173"><a href="#cb13-173" aria-hidden="true" tabindex="-1"></a>errors, and whichever form you fit, the other costs a <span class="in">`lincom`</span>.</span>
<span id="cb13-174"><a href="#cb13-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-175"><a href="#cb13-175" aria-hidden="true" tabindex="-1"></a>*Which hypothesis is one line.* $p_2 = 0$ says between equals within, which is</span>
<span id="cb13-176"><a href="#cb13-176" aria-hidden="true" tabindex="-1"></a>exactly the random-effects assumption that the regressors are uncorrelated with</span>
<span id="cb13-177"><a href="#cb13-177" aria-hidden="true" tabindex="-1"></a>$c_i$. The Mundlak form prints that as a single $t$; in hybrid form it is the</span>
<span id="cb13-178"><a href="#cb13-178" aria-hidden="true" tabindex="-1"></a>contrast $b_1 = b_2$. The two tests agree numerically, but only one is printed.</span>
<span id="cb13-179"><a href="#cb13-179" aria-hidden="true" tabindex="-1"></a>This is the Mundlak form of the Hausman test, asymptotically equivalent to the</span>
<span id="cb13-180"><a href="#cb13-180" aria-hidden="true" tabindex="-1"></a>classical version and with the practical advantage of working directly with</span>
<span id="cb13-181"><a href="#cb13-181" aria-hidden="true" tabindex="-1"></a>cluster-robust standard errors. The <span class="co">[</span><span class="ot">next chapter</span><span class="co">](mundlak-device.qmd)</span> develops</span>
<span id="cb13-182"><a href="#cb13-182" aria-hidden="true" tabindex="-1"></a>it and its two-way extension for difference-in-differences.</span>
<span id="cb13-183"><a href="#cb13-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-184"><a href="#cb13-184" aria-hidden="true" tabindex="-1"></a>*What the second coefficient is for.* In multilevel work $p_2$ is not a</span>
<span id="cb13-185"><a href="#cb13-185" aria-hidden="true" tabindex="-1"></a>diagnostic but the estimand: holding a pupil's own status fixed, what does the</span>
<span id="cb13-186"><a href="#cb13-186" aria-hidden="true" tabindex="-1"></a>school mean do? The hybrid's $b_2$ answers a different question, the total</span>
<span id="cb13-187"><a href="#cb13-187" aria-hidden="true" tabindex="-1"></a>between-unit association. Two literatures ask two questions of one regression,</span>
<span id="cb13-188"><a href="#cb13-188" aria-hidden="true" tabindex="-1"></a>and each named the parameterisation that printed its answer. That is the honest</span>
<span id="cb13-189"><a href="#cb13-189" aria-hidden="true" tabindex="-1"></a>reason both names survive.</span>
<span id="cb13-190"><a href="#cb13-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-191"><a href="#cb13-191" aria-hidden="true" tabindex="-1"></a>There is also a reason to prefer the hybrid form in extensions. Its two</span>
<span id="cb13-192"><a href="#cb13-192" aria-hidden="true" tabindex="-1"></a>regressors are exactly orthogonal, where $x_{it}$ and $\bar x_i$ are correlated.</span>
<span id="cb13-193"><a href="#cb13-193" aria-hidden="true" tabindex="-1"></a>That does not change the fit, but if you want a random slope on the within</span>
<span id="cb13-194"><a href="#cb13-194" aria-hidden="true" tabindex="-1"></a>component you need the deviation as its own column; a random slope on $x_{it}$</span>
<span id="cb13-195"><a href="#cb13-195" aria-hidden="true" tabindex="-1"></a>would mix within and between variation.</span>
<span id="cb13-196"><a href="#cb13-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-197"><a href="#cb13-197" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Where the equivalence stops</span></span>
<span id="cb13-198"><a href="#cb13-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-199"><a href="#cb13-199" aria-hidden="true" tabindex="-1"></a>The reparameterisation is exact for anything with a linear index, logit and</span>
<span id="cb13-200"><a href="#cb13-200" aria-hidden="true" tabindex="-1"></a>Poisson mixed models included, since $XA$ spans the same space and the index is</span>
<span id="cb13-201"><a href="#cb13-201" aria-hidden="true" tabindex="-1"></a>unchanged. The two names stay interchangeable there.</span>
<span id="cb13-202"><a href="#cb13-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-203"><a href="#cb13-203" aria-hidden="true" tabindex="-1"></a>The fixed-effect identity does not carry over. The proof above used two</span>
<span id="cb13-204"><a href="#cb13-204" aria-hidden="true" tabindex="-1"></a>linear-model facts: that random effects is OLS on quasi-demeaned data, and that</span>
<span id="cb13-205"><a href="#cb13-205" aria-hidden="true" tabindex="-1"></a>$d$ is orthogonal to group constants. A logit or Poisson mixed model has no such</span>
<span id="cb13-206"><a href="#cb13-206" aria-hidden="true" tabindex="-1"></a>transform, the unit effects do not sweep out, and the hybrid within coefficient</span>
<span id="cb13-207"><a href="#cb13-207" aria-hidden="true" tabindex="-1"></a>is not the conditional-logit estimate but an approximation to it. Keep the two</span>
<span id="cb13-208"><a href="#cb13-208" aria-hidden="true" tabindex="-1"></a>claims separate: the parameterisations are always the same model, while "within</span>
<span id="cb13-209"><a href="#cb13-209" aria-hidden="true" tabindex="-1"></a>coefficient equals fixed effects" is a linear-model result. The last section of</span>
<span id="cb13-210"><a href="#cb13-210" aria-hidden="true" tabindex="-1"></a>this chapter returns to that point.</span>
<span id="cb13-211"><a href="#cb13-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-212"><a href="#cb13-212" aria-hidden="true" tabindex="-1"></a><span class="fu">## BW model in R</span></span>
<span id="cb13-213"><a href="#cb13-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-214"><a href="#cb13-214" aria-hidden="true" tabindex="-1"></a>R's <span class="co">[</span><span class="ot">`panelr`</span><span class="co">](https://panelr.jacob-long.com/articles/wbm.html)</span> package implements BW models directly. The data are <span class="in">`WageData`</span>, a balanced panel of 595 men observed over 7 years. We model log wage on weeks worked, union membership, marital status and occupation, all time-varying, plus two time-invariant covariates — black and female — that a fixed-effect model could not touch.</span>
<span id="cb13-215"><a href="#cb13-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-216"><a href="#cb13-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-219"><a href="#cb13-219" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-220"><a href="#cb13-220" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb13-221"><a href="#cb13-221" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb13-222"><a href="#cb13-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-223"><a href="#cb13-223" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(panelr)</span>
<span id="cb13-224"><a href="#cb13-224" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"WageData"</span>)</span>
<span id="cb13-225"><a href="#cb13-225" aria-hidden="true" tabindex="-1"></a>wages <span class="ot">&lt;-</span> <span class="fu">panel_data</span>(WageData, <span class="at">id =</span> id, <span class="at">wave =</span> t)</span>
<span id="cb13-226"><a href="#cb13-226" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">wbm</span>(lwage <span class="sc">~</span> wks <span class="sc">+</span> union <span class="sc">+</span> ms <span class="sc">+</span> occ <span class="sc">|</span> blk <span class="sc">+</span> fem, <span class="at">data =</span> wages)</span>
<span id="cb13-227"><a href="#cb13-227" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span>
<span id="cb13-228"><a href="#cb13-228" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-229"><a href="#cb13-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-230"><a href="#cb13-230" aria-hidden="true" tabindex="-1"></a>The within estimates are 0.00 for weeks, 0.06 for union, $-0.08$ for married</span>
<span id="cb13-231"><a href="#cb13-231" aria-hidden="true" tabindex="-1"></a>and $-0.08$ for occupation. The between estimates for the same four variables</span>
<span id="cb13-232"><a href="#cb13-232" aria-hidden="true" tabindex="-1"></a>are 0.01, 0.15, 0.17 and $-0.41$ — two to five times larger, and for <span class="in">`ms`</span> the</span>
<span id="cb13-233"><a href="#cb13-233" aria-hidden="true" tabindex="-1"></a>opposite sign. That gap is the reason the fixed-versus-random choice matters</span>
<span id="cb13-234"><a href="#cb13-234" aria-hidden="true" tabindex="-1"></a>here: a random-effects model without the decomposition would blend the two and</span>
<span id="cb13-235"><a href="#cb13-235" aria-hidden="true" tabindex="-1"></a>report neither. The time-invariant covariates come out at $-0.15$ for black and</span>
<span id="cb13-236"><a href="#cb13-236" aria-hidden="true" tabindex="-1"></a>$-0.32$ for female, quantities a fixed-effect model cannot produce at all.</span>
<span id="cb13-237"><a href="#cb13-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-238"><a href="#cb13-238" aria-hidden="true" tabindex="-1"></a>Compare with <span class="in">`lfe`</span>.</span>
<span id="cb13-239"><a href="#cb13-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-242"><a href="#cb13-242" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-243"><a href="#cb13-243" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb13-244"><a href="#cb13-244" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb13-245"><a href="#cb13-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-246"><a href="#cb13-246" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lfe)</span>
<span id="cb13-247"><a href="#cb13-247" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">felm</span>(lwage <span class="sc">~</span> wks <span class="sc">+</span> union <span class="sc">+</span> ms <span class="sc">+</span> occ <span class="sc">|</span> id, <span class="at">data =</span> wages)</span>
<span id="cb13-248"><a href="#cb13-248" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span>
<span id="cb13-249"><a href="#cb13-249" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-250"><a href="#cb13-250" aria-hidden="true" tabindex="-1"></a><span class="in">`felm`</span> gives 0.001083, 0.064320, $-0.082905$ and $-0.077507$ — the same four</span>
<span id="cb13-251"><a href="#cb13-251" aria-hidden="true" tabindex="-1"></a>numbers <span class="in">`panelr`</span> reported as within effects, identical to machine precision</span>
<span id="cb13-252"><a href="#cb13-252" aria-hidden="true" tabindex="-1"></a>(<span class="in">`WageData`</span> is a balanced panel: 7 waves, 595 individuals). That is the BW</span>
<span id="cb13-253"><a href="#cb13-253" aria-hidden="true" tabindex="-1"></a>model's selling point: it reproduces the fixed-effect estimates exactly while</span>
<span id="cb13-254"><a href="#cb13-254" aria-hidden="true" tabindex="-1"></a>also estimating the time-invariant covariates <span class="in">`blk`</span> and <span class="in">`fem`</span>, which <span class="in">`felm`</span></span>
<span id="cb13-255"><a href="#cb13-255" aria-hidden="true" tabindex="-1"></a>cannot. <span class="in">`lfe`</span> supports clustered standard errors, which <span class="in">`panelr`</span> does not.</span>
<span id="cb13-256"><a href="#cb13-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-259"><a href="#cb13-259" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-260"><a href="#cb13-260" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb13-261"><a href="#cb13-261" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb13-262"><a href="#cb13-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-263"><a href="#cb13-263" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">felm</span>(lwage <span class="sc">~</span> wks <span class="sc">+</span> union <span class="sc">+</span> ms <span class="sc">+</span> occ <span class="sc">|</span> id <span class="sc">|</span> <span class="dv">0</span> <span class="sc">|</span> id, <span class="at">data =</span> wages)</span>
<span id="cb13-264"><a href="#cb13-264" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span>
<span id="cb13-265"><a href="#cb13-265" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-266"><a href="#cb13-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-267"><a href="#cb13-267" aria-hidden="true" tabindex="-1"></a>Clustering on <span class="in">`id`</span> leaves every coefficient untouched and changes the standard</span>
<span id="cb13-268"><a href="#cb13-268" aria-hidden="true" tabindex="-1"></a>errors substantially: <span class="in">`union`</span> goes from 0.0254 to 0.0409, <span class="in">`ms`</span> from 0.0322 to</span>
<span id="cb13-269"><a href="#cb13-269" aria-hidden="true" tabindex="-1"></a>0.0474, <span class="in">`wks`</span> from 0.00102 to 0.00133. Two of the four results do not survive.</span>
<span id="cb13-270"><a href="#cb13-270" aria-hidden="true" tabindex="-1"></a><span class="in">`union`</span> falls from $p = 0.011$ to $p = 0.117$ and <span class="in">`ms`</span> from $0.010$ to $0.081$;</span>
<span id="cb13-271"><a href="#cb13-271" aria-hidden="true" tabindex="-1"></a>only <span class="in">`occ`</span> stays significant at 5%. With 7 observations per man the residuals</span>
<span id="cb13-272"><a href="#cb13-272" aria-hidden="true" tabindex="-1"></a>are serially correlated, and the unclustered standard errors were treating 4,165</span>
<span id="cb13-273"><a href="#cb13-273" aria-hidden="true" tabindex="-1"></a>observations as though they were independent draws.</span>
<span id="cb13-274"><a href="#cb13-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-275"><a href="#cb13-275" aria-hidden="true" tabindex="-1"></a><span class="fu">## BW model in Stata</span></span>
<span id="cb13-276"><a href="#cb13-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-277"><a href="#cb13-277" aria-hidden="true" tabindex="-1"></a>Stata has no dedicated BW command, but <span class="in">`xtreg`</span> suffices. We switch to <span class="in">`nlswork`</span>,</span>
<span id="cb13-278"><a href="#cb13-278" aria-hidden="true" tabindex="-1"></a>an unbalanced panel of 4,710 women over 28,510 person-years, and regress log</span>
<span id="cb13-279"><a href="#cb13-279" aria-hidden="true" tabindex="-1"></a>wage on age.</span>
<span id="cb13-280"><a href="#cb13-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-283"><a href="#cb13-283" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-284"><a href="#cb13-284" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb13-285"><a href="#cb13-285" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb13-286"><a href="#cb13-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-287"><a href="#cb13-287" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Statamarkdown)</span>
<span id="cb13-288"><a href="#cb13-288" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-289"><a href="#cb13-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-292"><a href="#cb13-292" aria-hidden="true" tabindex="-1"></a><span class="in">```{stata}</span></span>
<span id="cb13-293"><a href="#cb13-293" aria-hidden="true" tabindex="-1"></a><span class="in">*| cache: true</span></span>
<span id="cb13-294"><a href="#cb13-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-295"><a href="#cb13-295" aria-hidden="true" tabindex="-1"></a><span class="in">webuse nlswork</span></span>
<span id="cb13-296"><a href="#cb13-296" aria-hidden="true" tabindex="-1"></a><span class="in">xtset idcode</span></span>
<span id="cb13-297"><a href="#cb13-297" aria-hidden="true" tabindex="-1"></a><span class="in">xtreg ln_w age, fe cluster(idcode)</span></span>
<span id="cb13-298"><a href="#cb13-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-299"><a href="#cb13-299" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-300"><a href="#cb13-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-301"><a href="#cb13-301" aria-hidden="true" tabindex="-1"></a>The fixed-effect estimate is $.0181349$ with a clustered standard error of</span>
<span id="cb13-302"><a href="#cb13-302" aria-hidden="true" tabindex="-1"></a>$.0006099$: within a woman, each additional year of age raises log wage by about</span>
<span id="cb13-303"><a href="#cb13-303" aria-hidden="true" tabindex="-1"></a>1.8%. Keep that number in view — the BW model has to reproduce it.</span>
<span id="cb13-304"><a href="#cb13-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-305"><a href="#cb13-305" aria-hidden="true" tabindex="-1"></a>Generate the group mean and run the BW estimation.</span>
<span id="cb13-308"><a href="#cb13-308" aria-hidden="true" tabindex="-1"></a><span class="in">```{stata}</span></span>
<span id="cb13-309"><a href="#cb13-309" aria-hidden="true" tabindex="-1"></a><span class="in">*| cache: true</span></span>
<span id="cb13-310"><a href="#cb13-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-311"><a href="#cb13-311" aria-hidden="true" tabindex="-1"></a><span class="in">webuse nlswork</span></span>
<span id="cb13-312"><a href="#cb13-312" aria-hidden="true" tabindex="-1"></a><span class="in">xtset idcode</span></span>
<span id="cb13-313"><a href="#cb13-313" aria-hidden="true" tabindex="-1"></a><span class="in">bysort idcode: center age, prefix(d) mean(m)</span></span>
<span id="cb13-314"><a href="#cb13-314" aria-hidden="true" tabindex="-1"></a><span class="in">xtreg ln_w dage mage i.race, re cluster(idcode)</span></span>
<span id="cb13-315"><a href="#cb13-315" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-316"><a href="#cb13-316" aria-hidden="true" tabindex="-1"></a>In this BW model, we use the centered (within-group-demeaned) <span class="in">`dage`</span> together with the group mean <span class="in">`mage`</span>, which gives the standard within-between (Mundlak) decomposition: the coefficient on <span class="in">`dage`</span>, .0181349, is exactly the fixed-effect ("within") coefficient on age reported above — the same seven digits, with a standard error of .00061 against .0006099 — and the coefficient on <span class="in">`mage`</span>, .022558, is directly the between effect. Women who are older on average earn about 2.3% more per year of average age, against a within-woman return of 1.8%; the between effect is larger because it also carries cohort and selection differences that the within estimate sweeps out. And we have the effect of time-invariant covariate race estimated: Black women earn 11.9% less ($-.1190246$, SE .0127), while the "Other" category is not distinguishable from white ($.0975$, $p = 0.114$).  The advantage of using xtreg is that we have clustered standard errors implemented.</span>
<span id="cb13-317"><a href="#cb13-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-318"><a href="#cb13-318" aria-hidden="true" tabindex="-1"></a>Note: if we instead ran <span class="in">`xtreg ln_w age mage i.race, re cluster(idcode)`</span> — using the raw (uncentered) <span class="in">`age`</span> together with <span class="in">`mage`</span> — we would get the *contextual model* instead: the coefficient on `age` stays .0181, but the coefficient on `mage` becomes .0044, the "contextual effect" (the *additional* between-effect on top of the within effect). The two models are algebraically related: contextual-model mage = Mundlak-model mage − Mundlak-model dage (here, .0226 − .0181 ≈ .0044).</span>
<span id="cb13-319"><a href="#cb13-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-320"><a href="#cb13-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-321"><a href="#cb13-321" aria-hidden="true" tabindex="-1"></a><span class="fu">## BW model in non-linear models</span></span>
<span id="cb13-322"><a href="#cb13-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-323"><a href="#cb13-323" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Allison</span><span class="co">](https://statisticalhorizons.com/between-within-contextual-effects)</span> applies the BW model to binary outcomes. The bias relative to conditional logit is an open question, but if the linear probability model is a reasonable approximation the BW approach should perform similarly for binary panel data.</span>
<span id="cb13-324"><a href="#cb13-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-325"><a href="#cb13-325" aria-hidden="true" tabindex="-1"></a></span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->



<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions"><ul><li><a href="https://github.com/xiangao/blog_book/edit/main/fixed-random-effect.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/xiangao/blog_book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>