<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Xiang Ao">
<meta name="dcterms.date" content="2025-11-17">
<title>16&nbsp; Gender Wage Gap Analysis Using US Current Population Survey Data – Topics on econometrics and causal inference</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./causal-forest-panel.html" rel="next">
<link href="./sensitivity-analysis.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6eb2a311e0ae5a9b436ea9f7e52955e6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script>
try {
  if (window.localStorage) {
    window.localStorage.setItem("quarto-reader-mode", "false");
  }
} catch (e) {}
</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="style.css">
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./treatment-matching.html">Treatment Effects &amp; Matching</a></li><li class="breadcrumb-item"><a href="./gwg.html"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Gender Wage Gap Analysis Using US Current Population Survey Data</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Topics on econometrics and causal inference</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://xiangao.github.io/" title="Xiang Ao home" class="quarto-navigation-tool px-1" aria-label="Xiang Ao home"><i class="bi bi-house-door-fill"></i></a>
    <a href="https://xiangao.github.io/books.html" title="Other books" class="quarto-navigation-tool px-1" aria-label="Other books"><i class="bi bi-book"></i></a>
    <a href="https://github.com/xiangao/blog_book/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Regression Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./interaction-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Interpreting interaction in a regression model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./interaction-nonlinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Interaction term in a non-linear model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chow-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Chow test and more</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./weights-ols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Weights in OLS in causal inference</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Marginal Effects &amp; Fixed Effects</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./marginal-effects-fe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Marginal effects in models with fixed effects</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./comparing-margins.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Comparing Marginal effects with margins command</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fixed-random-effect.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Fixed or Random Effect, or Both?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mundlak-device.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Mundlak device in fixed effect models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlated-random-effect.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Correlated Random Effect</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./more-cre.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">More on Correlated Random Effect (CRE)</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Treatment Effects &amp; Matching</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./treatment-matching.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Treatment effects and matching</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ols-ate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">When is OLS coefficient the ATE</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./matching-part1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Matching and Weighting Part 1: matching</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./weighting-part2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Matching and Weighting - Part 2: weighting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sensitivity-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Sensitivity analysis of OLS with sensemakr</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./gwg.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Gender Wage Gap Analysis Using US Current Population Survey Data</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Panel Data &amp; DiD</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal-forest-panel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Causal Forest in panel data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./synthetic-control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Synthetic Control in R and Stata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tasc-time-aware-synthetic-control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Same Data, Different Estimators: A Synthetic Control Comparison</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bartik-instrument.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Bartik Instrument and Rotemberg weights</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./extended-twfe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Extended TWFE and other DiD estimators</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal-panel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Causal Panel (why DDDiD)</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Count Data &amp; Specialized Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Which count data model to use</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rare-events.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">What model to use for rare events</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./poisson-exposure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Poisson model with exposure</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./poisson-iv-fe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">IV in Fixed effect Poisson with many fixed effects</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Causal Inference Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tmle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Using machine learning for causal effect in observational study</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mediation-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Mediation analysis in R and Stata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bunching.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Endogeneity with censored variable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./g-estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">G-computation (g-formula) with time varying covariates</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./policytree.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Policy learning by policytree</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./npcausal-tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Recent causal inference tools</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./proximal-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Intro to proximal causal inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./proximal-simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Simulation on proximal causal inference with panel data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lmtp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">longitudinal modified treatment policy (LMTP)</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Advanced Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multilevel-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Doing the same multi-level model with R and stata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./likert-scale-variance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Modeling variation, not just the mean, in Likert-scale data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conjoint-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Conjoint design and analysis using R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stata-cate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Stata 19 CATE command</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./spatial-econometrics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Spatial econometrics introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal-simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Causal simulation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./frengression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Frengression and Engression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./partial-interference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Partial Interference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./power-list-experiment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Power analysis with list experiment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal-mediation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Causal mediation analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uplift.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Uplift Modeling and CATE</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./numpyro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Using Numpyro</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./equivalence-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Pre-registration, TOST, and why Bayes doesn’t let you skip the hard part</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#oaxaca-blinder-decomposition" id="toc-oaxaca-blinder-decomposition" class="nav-link active" data-scroll-target="#oaxaca-blinder-decomposition"><span class="header-section-number">16.1</span> Oaxaca-Blinder decomposition</a></li>
  <li>
<a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example"><span class="header-section-number">16.2</span> Example</a>
  <ul class="collapse">
<li><a href="#regression-adjustment" id="toc-regression-adjustment" class="nav-link" data-scroll-target="#regression-adjustment"><span class="header-section-number">16.2.1</span> Regression adjustment</a></li>
  <li><a href="#occupation-and-industry-a-bad-control-problem" id="toc-occupation-and-industry-a-bad-control-problem" class="nav-link" data-scroll-target="#occupation-and-industry-a-bad-control-problem"><span class="header-section-number">16.2.2</span> Occupation and industry: a bad control problem</a></li>
  <li><a href="#nonparametric-estimation" id="toc-nonparametric-estimation" class="nav-link" data-scroll-target="#nonparametric-estimation"><span class="header-section-number">16.2.3</span> Nonparametric estimation</a></li>
  </ul>
</li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/xiangao/blog_book/edit/main/gwg.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/xiangao/blog_book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./treatment-matching.html">Treatment Effects &amp; Matching</a></li><li class="breadcrumb-item"><a href="./gwg.html"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Gender Wage Gap Analysis Using US Current Population Survey Data</span></a></li></ol></nav><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">
<span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Gender Wage Gap Analysis Using US Current Population Survey Data</span>
</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Xiang Ao </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 17, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header><p>Traditionally Oaxaca-Blinder decomposition is used to decompose the wage gap into explained and unexplained parts. The explained part is due to differences in observable characteristics, such as education, experience, occupation, etc. The unexplained part is due to discrimination or other unobserved factors.</p>
<p>It has a problem that when decomposing, using female as reference group or male as reference group will give different results.</p>
<p>Słoczyński (2015) and Słoczyński (2013) have shown that a regression adjustment type of analysis is equivalent to Oaxaca-Blinder decomposition in a nonstandard way.</p>
<section id="oaxaca-blinder-decomposition" class="level2" data-number="16.1"><h2 data-number="16.1" class="anchored" data-anchor-id="oaxaca-blinder-decomposition">
<span class="header-section-number">16.1</span> Oaxaca-Blinder decomposition</h2>
<p>Assume the regression model is different for male and female: <span class="math display">\[ y_i = X_i \beta_a + \epsilon_a \]</span></p>
<p>where <span class="math inline">\(a\)</span> is gender (female is 1), <span class="math inline">\(X\)</span>’s are person characteristics.</p>
<p><span class="math display">\[ E[y_i | a_i = 1] - E[y_i | a_i = 0] = E[X_i | a_i=1]  (\beta_1 - \beta_0) + (E[X_i | a_i =1 ] - E[X_i | a_i = 0]) \beta_0 \]</span></p>
<p>or</p>
<p><span class="math display">\[ E[y_i | a_i = 1] - E[y_i | a_i = 0] = E[X_i | a_i=0]  (\beta_1 - \beta_0) + (E[X_i | a_i =1 ] - E[X_i | a_i = 0]) \beta_1 \]</span> These two equations are different forms of the Oaxaca-Blinder decomposition. The first element is the “unexplained component”, which is the difference in the coefficients, and the second element is the “explained component”, which is the difference in the means of the covariates.</p>
<p>These two equations can give different results for the two components, one has a baseline of male, and other one female.</p>
<p>We can further shows that</p>
<p><span class="math display">\[
\begin{align}
E[y_i | a_i =1] - E[y_i | a_i=0] &amp;= E[X_i | a_i=1]  (\beta_1 - \beta_0) + (E[X_i | a_i =1 ] - E[X_i | a_i = 0]) \beta_0  \\
&amp;= E[y_i(1) - y_i(0) | a_i=1] + (E[y_i(0) | a_i=1] - E[y_i(0) | a_i = 0]) \\
&amp;= \tau_{PATT} + (E[y_i(0) | a_i=1] - E[y_i(0) | a_i=0])
\end{align}
\]</span></p>
<p>That is, the observed difference is the sum of <span class="math inline">\(\tau_{PATT}\)</span> and selection bias. It is also known in the OB decomposition literature as the unexplained component and the explained component. The former as “discrimination”.</p>
<p>We can simply use Regression Adjustment for these quantities. The easiest is an OLS of <span class="math inline">\(y_i\)</span> on <span class="math inline">\(a_i\)</span>, the demeaned <span class="math inline">\(X_i\)</span>, and their interaction; the coefficient on <span class="math inline">\(a_i\)</span> is then the effect evaluated at the mean of the covariates used for the demeaning. Demean at the <strong>overall</strong> mean and that coefficient is <span class="math inline">\(\tau_{PAGE}\)</span> (the ATE), which is what the example below does; demean at the mean among <strong>women</strong> instead and it is <span class="math inline">\(\tau_{PATT}\)</span>. The choice of centring is what selects the estimand, so it is worth being explicit about which one you have.</p>
<p>He also advocates the “population average gender effect” (PAGE):</p>
<p><span class="math display">\[ \tau_{PAGE} = E[\tau(X_i)] \]</span></p>
<p>which is basically ATE, or conditional average effect (CATE), then average over the <span class="math inline">\(X\)</span>’s.</p>
<p>In this version, the two forms of OB decomposition can be <span class="math inline">\(\tau_{PAGM}\)</span> and <span class="math inline">\(\tau_{PAGW}\)</span>, for men and women.</p>
<p>The nice thing about this estimator <span class="math inline">\(\tau_{PAGE}\)</span> is that first, it is consistent with the treatment effect (causal inference) literature, and it is invariant to the choice of reference group.</p>
<p>The second advantage is that we also do not need to assume homogeneity of treatment effect, which is a strong assumption in the Oaxaca-Blinder decomposition.</p>
<p>The third advantage is that we can use nonparametric methods to estimate the treatment effect. Traditional OB decomposition is based on linear regression, which assumes a linear relationship between the covariates and the outcome.</p>
</section><section id="example" class="level2" data-number="16.2"><h2 data-number="16.2" class="anchored" data-anchor-id="example">
<span class="header-section-number">16.2</span> Example</h2>
<p>I am using the data from https://github.com/d2cml-ai/CausalAI-Course/tree/main/data.</p>
<p>“The data set we consider is from the 2015 March Supplement of the U.S. Current Population Survey. We select white non-hispanic individuals, aged 25 to 64 years, and working more than 35 hours per week for at least 50 weeks of the year. We exclude self-employed workers; individuals living in group quarters; individuals in the military, agricultural or private household sectors; individuals with inconsistent reports on earnings and employment status; individuals with allocated or missing information in any of the variables used in the analysis; and individuals with hourly wage below 3.”</p>
<p>I am using this data to study gender wage gap (GWP).</p>
<p>We can model GWP using the potential outcome framework, with some care about what plays the role of “treatment.” Gender itself is an immutable characteristic, not something that can be manipulated or randomized — the standard “no causation without manipulation” principle (Holland, 1986) says we should not treat gender itself as a causal treatment. What we really have in mind, and what the “treatment” indicator below is best understood as a proxy for, is something like <em>being perceived/treated as female by employers</em> (e.g., employer discrimination), which is at least conceptually manipulable even though we cannot experimentally assign it here. With that caveat in mind, we let <span class="math inline">\(D=1\)</span> if female, <span class="math inline">\(D=0\)</span> if male, and outcome <span class="math inline">\(Y\)</span> is logged wage.</p>
<p>The ATE would be</p>
<p><span class="math display">\[ \delta_{ATE} = E[Y(1) - Y(0)] \]</span></p>
<p>where <span class="math inline">\(Y(1)\)</span> is the potential outcome if treated, and <span class="math inline">\(Y(0)\)</span> is the potential outcome if not treated.</p>
<section id="regression-adjustment" class="level3" data-number="16.2.1"><h3 data-number="16.2.1" class="anchored" data-anchor-id="regression-adjustment">
<span class="header-section-number">16.2.1</span> Regression adjustment</h3>
<p>Since this is to estimate ATE, we can use regression adjustment to estimate the ATE. First let’s use de-meaned <span class="math inline">\(X\)</span>’s. Then the coefficient on gender is the ATE.</p>
<p>We use These variables as <span class="math inline">\(X\)</span>’s:</p>
<p>“shs”,“hsg”,“scl”,“clg”,“ad”,“ne”,“mw”,“so”,“we”,“exp1”, “occ”, “occ2”, “ind”, and “ind2”.</p>
<p>They are:</p>
<p>“Less then High School”,“High School Graduate”,“Some College”,“College Graduate”,“Advanced Degree”, “Northeast”,“Midwest”,“South”,“West”,“Experience”, “occupation”, “occupation 2”, “industry”, and “industry 2”.</p>
<p>I decide to use “occ2” and “ind2” as they are broader categories of occupation and industry. We don’t have enough data for finer categories “occ” and “ind”.</p>
<p>“exp1” seems to be the only variable that is continuous, let’s demean it first. Let’s also input “occ2” and “ind2” as factors.</p>
<p>Let’s include demeaned “exp1”, “sohs”, “hsg”, “socl”, “clg”, “mw”, “sout”, and “we” first. I leave out “occ2” and “ind2” since there are too many levels to demean.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://broom.tidymodels.org/">broom</a></span><span class="op">)</span></span>
<span></span>
<span></span>
<span><span class="va">data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"wage2015_subsample_inference.csv"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a></span><span class="op">(</span>socl <span class="op">=</span> <span class="va">scl</span>, sohs <span class="op">=</span> <span class="va">shs</span>, sout <span class="op">=</span> <span class="va">so</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>exp_dm <span class="op">=</span> <span class="va">exp1</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">exp1</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>, female<span class="op">=</span><span class="va">sex</span>, occ2 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">occ2</span><span class="op">)</span>, ind2 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">ind2</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>sohs_dm <span class="op">=</span> <span class="va">sohs</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">sohs</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>         hsg_dm <span class="op">=</span> <span class="va">hsg</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">hsg</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>         socl_dm <span class="op">=</span> <span class="va">socl</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">socl</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>         clg_dm <span class="op">=</span> <span class="va">clg</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">clg</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>         mw_dm <span class="op">=</span> <span class="va">mw</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">mw</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>         sout_dm <span class="op">=</span> <span class="va">sout</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">sout</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>         we_dm <span class="op">=</span> <span class="va">we</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">we</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">data</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 5,150
Columns: 30
$ rownames &lt;dbl&gt; 10, 12, 15, 18, 19, 30, 43, 44, 47, 71, 73, 77, 84, 89, 96, 1…
$ wage     &lt;dbl&gt; 9.615385, 48.076923, 11.057692, 13.942308, 28.846154, 11.7307…
$ lwage    &lt;dbl&gt; 2.263364, 3.872802, 2.403126, 2.634928, 3.361977, 2.462215, 2…
$ sex      &lt;dbl&gt; 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1…
$ sohs     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ hsg      &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0…
$ socl     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1…
$ clg      &lt;dbl&gt; 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0…
$ ad       &lt;dbl&gt; 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ mw       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ sout     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ we       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ ne       &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ exp1     &lt;dbl&gt; 7.0, 31.0, 18.0, 25.0, 22.0, 1.0, 42.0, 37.0, 31.0, 4.0, 7.0,…
$ exp2     &lt;dbl&gt; 0.4900, 9.6100, 3.2400, 6.2500, 4.8400, 0.0100, 17.6400, 13.6…
$ exp3     &lt;dbl&gt; 0.343000, 29.791000, 5.832000, 15.625000, 10.648000, 0.001000…
$ exp4     &lt;dbl&gt; 0.24010000, 92.35210000, 10.49760000, 39.06250000, 23.4256000…
$ occ      &lt;dbl&gt; 3600, 3050, 6260, 420, 2015, 1650, 5120, 5240, 4040, 3255, 40…
$ occ2     &lt;fct&gt; 11, 10, 19, 1, 6, 5, 17, 17, 13, 10, 13, 14, 11, 11, 1, 19, 1…
$ ind      &lt;dbl&gt; 8370, 5070, 770, 6990, 9470, 7460, 7280, 5680, 8590, 8190, 82…
$ ind2     &lt;fct&gt; 18, 9, 4, 12, 22, 14, 14, 9, 19, 18, 18, 18, 18, 18, 17, 4, 4…
$ exp_dm   &lt;dbl&gt; -6.760583, 17.239417, 4.239417, 11.239417, 8.239417, -12.7605…
$ female   &lt;dbl&gt; 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1…
$ sohs_dm  &lt;dbl&gt; -0.02330097, -0.02330097, -0.02330097, -0.02330097, -0.023300…
$ hsg_dm   &lt;dbl&gt; -0.2438835, -0.2438835, 0.7561165, -0.2438835, -0.2438835, -0…
$ socl_dm  &lt;dbl&gt; -0.2780583, -0.2780583, -0.2780583, -0.2780583, -0.2780583, -…
$ clg_dm   &lt;dbl&gt; 0.6823301, 0.6823301, -0.3176699, -0.3176699, 0.6823301, 0.68…
$ mw_dm    &lt;dbl&gt; -0.2596117, -0.2596117, -0.2596117, -0.2596117, -0.2596117, -…
$ sout_dm  &lt;dbl&gt; -0.2965049, -0.2965049, -0.2965049, -0.2965049, -0.2965049, -…
$ we_dm    &lt;dbl&gt; -0.2161165, -0.2161165, -0.2161165, -0.2161165, -0.2161165, -…</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># construct matrices for estimation from the data</span></span>
<span></span>
<span><span class="co"># 1. basic model</span></span>
<span><span class="va">reg1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">lwage</span> <span class="op">~</span> <span class="va">female</span>, data<span class="op">=</span><span class="va">data</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">reg1</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 (Intercept)   2.99      0.0107    280.    0     
2 female       -0.0383    0.0160     -2.40  0.0165</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">reg2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">lwage</span> <span class="op">~</span> <span class="va">female</span><span class="op">*</span><span class="op">(</span><span class="va">exp_dm</span> <span class="op">+</span> <span class="va">sohs_dm</span> <span class="op">+</span> <span class="va">hsg_dm</span> <span class="op">+</span> <span class="va">socl_dm</span> <span class="op">+</span> <span class="va">clg_dm</span> <span class="op">+</span> <span class="va">mw_dm</span> <span class="op">+</span> <span class="va">sout_dm</span> <span class="op">+</span> <span class="va">we_dm</span><span class="op">)</span>, data<span class="op">=</span><span class="va">data</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">reg2</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 5
   term           estimate std.error statistic  p.value
   &lt;chr&gt;             &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
 1 (Intercept)     3.02     0.00974    310.    0       
 2 female         -0.115    0.0147      -7.80  7.39e-15
 3 exp_dm          0.00801  0.000957     8.37  7.31e-17
 4 sohs_dm        -0.811    0.0620     -13.1   1.63e-38
 5 hsg_dm         -0.706    0.0350     -20.1   6.09e-87
 6 socl_dm        -0.553    0.0351     -15.7   1.45e-54
 7 clg_dm         -0.256    0.0345      -7.41  1.42e-13
 8 mw_dm           0.0337   0.0280       1.20  2.29e- 1
 9 sout_dm         0.0148   0.0271       0.548 5.84e- 1
10 we_dm           0.0555   0.0290       1.91  5.59e- 2
11 female:exp_dm   0.00212  0.00140      1.51  1.30e- 1
12 female:sohs_dm -0.0180   0.117       -0.154 8.78e- 1
13 female:hsg_dm   0.0398   0.0507       0.786 4.32e- 1
14 female:socl_dm  0.0466   0.0482       0.968 3.33e- 1
15 female:clg_dm   0.0992   0.0468       2.12  3.41e- 2
16 female:mw_dm   -0.124    0.0417      -2.98  2.93e- 3
17 female:sout_dm -0.0530   0.0403      -1.31  1.89e- 1
18 female:we_dm   -0.0655   0.0435      -1.51  1.32e- 1</code></pre>
</div>
</div>
<p>We see the raw gap is 3.8%. Adjusting for some covariates we have 11% gap.</p>
<p>Or, we can use “marginaleffects” instead of demeaning.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">reg3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">lwage</span> <span class="op">~</span> <span class="va">female</span><span class="op">*</span><span class="op">(</span><span class="va">exp1</span> <span class="op">+</span> <span class="va">sohs</span> <span class="op">+</span> <span class="va">hsg</span><span class="op">+</span> <span class="va">socl</span> <span class="op">+</span> <span class="va">clg</span> <span class="op">+</span> <span class="va">mw</span> <span class="op">+</span> <span class="va">sout</span> <span class="op">+</span> <span class="va">we</span> <span class="op">)</span>, data<span class="op">=</span><span class="va">data</span><span class="op">)</span></span>
<span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://marginaleffects.com/">marginaleffects</a></span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/marginaleffects/man/comparisons.html">avg_comparisons</a></span><span class="op">(</span><span class="va">reg3</span>,</span>
<span>                variables <span class="op">=</span> <span class="st">"female"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Estimate Std. Error    z Pr(&gt;|z|)    S  2.5 %  97.5 %
   -0.115     0.0147 -7.8   &lt;0.001 47.2 -0.143 -0.0858

Term: female
Type: response
Comparison: 1 - 0</code></pre>
</div>
</div>
<p>We get the same result as the demeaned regression.</p>
<p>If we want <span class="math inline">\(\tau_{ATT}\)</span>, then we can use the “newdata” argument to specify the treatment group,</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/marginaleffects/man/comparisons.html">avg_comparisons</a></span><span class="op">(</span><span class="va">reg3</span>,</span>
<span>                variables <span class="op">=</span> <span class="st">"female"</span>,</span>
<span>                newdata <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">data</span>, <span class="va">female</span> <span class="op">==</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Estimate Std. Error     z Pr(&gt;|z|)    S  2.5 %  97.5 %
   -0.113     0.0148 -7.65   &lt;0.001 45.5 -0.142 -0.0844

Term: female
Type: response
Comparison: 1 - 0</code></pre>
</div>
</div>
</section><section id="occupation-and-industry-a-bad-control-problem" class="level3" data-number="16.2.2"><h3 data-number="16.2.2" class="anchored" data-anchor-id="occupation-and-industry-a-bad-control-problem">
<span class="header-section-number">16.2.2</span> Occupation and industry: a bad control problem</h3>
<p>Before adding occupation and industry, it is worth being clear about what kind of variables they are. Everything used so far — experience, education, region — is plausibly settled before the wage is determined and is not itself much of a consequence of gender. Occupation and industry are different. They are <strong>post-treatment</strong>: whatever “being perceived and treated as female” does, one of the things it does is shift which occupations people end up in.</p>
<p>That makes them <em>bad controls</em> in the sense of Cinelli, Forney and Pearl (2022), and for two separate reasons at the same time.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/r-causal/ggdag">ggdag</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">g</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-causal.github.io/ggdag/reference/dagify.html">dagify</a></span><span class="op">(</span></span>
<span>  <span class="va">Wage</span> <span class="op">~</span> <span class="va">Female</span> <span class="op">+</span> <span class="va">Occupation</span> <span class="op">+</span> <span class="va">U</span>,</span>
<span>  <span class="va">Occupation</span> <span class="op">~</span> <span class="va">Female</span> <span class="op">+</span> <span class="va">U</span>,</span>
<span>  exposure <span class="op">=</span> <span class="st">"Female"</span>,</span>
<span>  outcome  <span class="op">=</span> <span class="st">"Wage"</span>,</span>
<span>  coords <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>Female <span class="op">=</span> <span class="fl">0</span>, Occupation <span class="op">=</span> <span class="fl">1.1</span>, U <span class="op">=</span> <span class="fl">1.1</span>, Wage <span class="op">=</span> <span class="fl">2.2</span><span class="op">)</span>,</span>
<span>                y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>Female <span class="op">=</span> <span class="fl">0</span>, Occupation <span class="op">=</span> <span class="op">-</span><span class="fl">1</span>,  U <span class="op">=</span> <span class="fl">1</span>,   Wage <span class="op">=</span> <span class="fl">0</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># node_size has to stay small: ggdag stops each edge at the node boundary, so</span></span>
<span><span class="co"># large nodes swallow the arrowheads -- and the arrowheads are the whole point.</span></span>
<span><span class="fu"><a href="https://r-causal.github.io/ggdag/reference/ggdag.html">ggdag</a></span><span class="op">(</span><span class="va">g</span>, text <span class="op">=</span> <span class="cn">FALSE</span>, node_size <span class="op">=</span> <span class="fl">9</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://r-causal.github.io/ggdag/reference/repel.html">geom_dag_text_repel</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>label <span class="op">=</span> <span class="va">name</span><span class="op">)</span>, colour <span class="op">=</span> <span class="st">"black"</span>, size <span class="op">=</span> <span class="fl">3.2</span>,</span>
<span>                      box.padding <span class="op">=</span> <span class="fl">0.9</span>, seed <span class="op">=</span> <span class="fl">42</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://r-causal.github.io/ggdag/reference/theme_dag_blank.html">theme_dag</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/expand_limits.html">expand_limits</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">0.45</span>, <span class="fl">2.65</span><span class="op">)</span>, y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">1.5</span>, <span class="fl">1.5</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="gwg_files/figure-html/gwg-dag-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Occupation is both a mediator of the gender–wage relationship and a collider on a path through unobserved wage determinants <span class="math inline">\(U\)</span>.</figcaption></figure>
</div>
</div>
</div>
<p>Here <span class="math inline">\(U\)</span> stands for unobserved wage determinants — drive, negotiation propensity, family constraints, expected career continuity — and <code>Occupation</code> covers occupation and industry together.</p>
<p><strong>Occupation is a mediator.</strong> Part of the total effect of gender on wages runs <code>Female -&gt; Occupation -&gt; Wage</code>. Conditioning on occupation blocks that path, so the coefficient stops estimating a total effect. On its own this would be tolerable, as long as we said so: we would be reporting a within-occupation gap, which is a perfectly coherent descriptive quantity.</p>
<p><strong>Occupation is also a collider.</strong> It is a common effect of gender and of <span class="math inline">\(U\)</span>. Conditioning on a common effect <em>induces</em> an association between its causes, so conditioning on occupation opens the non-causal path <code>Female -&gt; Occupation &lt;- U -&gt; Wage</code>, which was closed before we touched anything (Elwert and Winship, 2014).</p>
<p>We do not have to take that on faith. <code>dagitty</code> will enumerate the paths and say which are open, with and without conditioning on occupation:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">paths_table</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">Z</span> <span class="op">=</span> <span class="cn">NULL</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">p</span> <span class="op">&lt;-</span> <span class="fu">dagitty</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/dagitty/man/paths.html">paths</a></span><span class="op">(</span><span class="va">g</span>, from <span class="op">=</span> <span class="st">"Female"</span>, to <span class="op">=</span> <span class="st">"Wage"</span>, Z <span class="op">=</span> <span class="va">Z</span><span class="op">)</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>path <span class="op">=</span> <span class="va">p</span><span class="op">$</span><span class="va">paths</span>, open <span class="op">=</span> <span class="va">p</span><span class="op">$</span><span class="va">open</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="fu">paths_table</span><span class="op">(</span><span class="op">)</span>                   <span class="co"># nothing conditioned on</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                               path  open
1      Female -&gt; Occupation -&gt; Wage  TRUE
2 Female -&gt; Occupation &lt;- U -&gt; Wage FALSE
3                    Female -&gt; Wage  TRUE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">paths_table</span><span class="op">(</span>Z <span class="op">=</span> <span class="st">"Occupation"</span><span class="op">)</span>   <span class="co"># conditioning on occupation</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                               path  open
1      Female -&gt; Occupation -&gt; Wage FALSE
2 Female -&gt; Occupation &lt;- U -&gt; Wage  TRUE
3                    Female -&gt; Wage  TRUE</code></pre>
</div>
</div>
<p>The two tables are the whole argument. Conditioning on occupation flips <code>Female -&gt; Occupation -&gt; Wage</code> from open to closed — that is the mediation we knowingly gave up — and simultaneously flips <code>Female -&gt; Occupation &lt;- U -&gt; Wage</code> from closed to open. That second flip is the damage. Blocking a mediator removes something we wanted; conditioning on a collider manufactures something we did not. After adjustment, gender and <span class="math inline">\(U\)</span> are correlated <em>within</em> occupation cells even if they are independent in the population, and because <span class="math inline">\(U\)</span> also drives wages, that induced correlation leaks into the gender coefficient.</p>
<p>Stated formally: conditioning on a mediator identifies a <em>controlled direct effect</em> only under <strong>no unmeasured mediator–outcome confounding</strong> (VanderWeele and Robinson, 2014). <span class="math inline">\(U\)</span> is exactly such a confounder, and in a wage setting it is not a remote worry — it is more or less why this literature exists.</p>
<p>Two consequences worth flagging before we run the model. First, this is not a problem that a better estimator solves: the AIPW and SuperLearner fits later in this chapter relax functional form, and do nothing at all about a structurally uninterpretable estimand. Second, the same graph applies to the sample itself. This extract keeps only full-year, full-time workers, and employment is likewise a common effect of gender and <span class="math inline">\(U\)</span> — so the sample restriction is a second conditioning-on-a-collider step, built in before any regression is run.</p>
<p>With all that on the table, here is the model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">reg4</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">lwage</span> <span class="op">~</span> <span class="va">female</span><span class="op">*</span><span class="op">(</span><span class="va">exp1</span> <span class="op">+</span> <span class="va">sohs</span> <span class="op">+</span> <span class="va">hsg</span><span class="op">+</span> <span class="va">socl</span> <span class="op">+</span> <span class="va">clg</span> <span class="op">+</span> <span class="va">mw</span> <span class="op">+</span> <span class="va">sout</span> <span class="op">+</span> <span class="va">we</span> <span class="op">+</span> <span class="va">occ2</span> <span class="op">+</span> <span class="va">ind2</span><span class="op">)</span>, data<span class="op">=</span><span class="va">data</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/marginaleffects/man/comparisons.html">avg_comparisons</a></span><span class="op">(</span><span class="va">reg4</span>,</span>
<span>                variables <span class="op">=</span> <span class="st">"female"</span>,</span>
<span>                newdata <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">data</span>, <span class="va">female</span> <span class="op">==</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Estimate Std. Error     z Pr(&gt;|z|)    S  2.5 %  97.5 %
   -0.075     0.0162 -4.62   &lt;0.001 18.0 -0.107 -0.0432

Term: female
Type: response
Comparison: 1 - 0</code></pre>
</div>
</div>
<p>So in the model with full interaction, we have a gap of 7.5%, against 11.3% without occupation and industry.</p>
<p>The tempting reading of that pair — “occupational and industrial sorting accounts for roughly four points of the gap” — is exactly the reading the graph above forbids. Three things are mixed into that four-point move, and nothing in the output separates them:</p>
<ol type="1">
<li>genuine mediation, the part of the gap that really does operate through sorting;</li>
<li>collider bias, from the gender–<span class="math inline">\(U\)</span> association induced by conditioning;</li>
<li>ordinary confounding of the occupation–wage relationship.</li>
</ol>
<p>The likely <em>direction</em> of (2) is worth spelling out. If women who enter male-dominated, high-paying occupations are positively selected on <span class="math inline">\(U\)</span> — they had more to overcome to get there — then within those occupations they are better on unobservables than the men they are being compared with, which pushes the within-occupation gap <strong>toward zero</strong>. Some of the attenuation from 11.3% to 7.5% may therefore be bias rather than mediation.</p>
<p>The defensible way to report this: 11.3% is the total-effect estimate; 7.5% is a within-occupation descriptive contrast whose causal reading rests on an assumption we cannot verify. What we <em>can</em> do is ask how strong <span class="math inline">\(U\)</span> would have to be to account for the whole difference.</p>
<section id="how-strong-would-u-have-to-be" class="level4" data-number="16.2.2.1"><h4 data-number="16.2.2.1" class="anchored" data-anchor-id="how-strong-would-u-have-to-be">
<span class="header-section-number">16.2.2.1</span> How strong would <span class="math inline">\(U\)</span> have to be?</h4>
<p>The omitted-variable-bias machinery in <code>sensemakr</code> (Cinelli and Hazlett, 2020) needs a single treatment coefficient, so for this exercise we drop the interactions and use additive specifications. That costs us the heterogeneity, but the attenuation we are interrogating survives the simplification almost exactly.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/carloscinelli/sensemakr">sensemakr</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">Xb</span> <span class="op">&lt;-</span> <span class="st">"exp1 + sohs + hsg + socl + clg + mw + sout + we"</span></span>
<span></span>
<span><span class="va">fit_total</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/formula.html">as.formula</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"lwage ~ female +"</span>, <span class="va">Xb</span><span class="op">)</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">data</span><span class="op">)</span></span>
<span><span class="va">fit_adj</span>   <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/formula.html">as.formula</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"lwage ~ female +"</span>, <span class="va">Xb</span>, <span class="st">"+ occ2 + ind2"</span><span class="op">)</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">data</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>total    <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">fit_total</span><span class="op">)</span><span class="op">[</span><span class="st">"female"</span><span class="op">]</span>,</span>
<span>  adjusted <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">fit_adj</span><span class="op">)</span><span class="op">[</span><span class="st">"female"</span><span class="op">]</span>,</span>
<span>  attenuation <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">fit_adj</span><span class="op">)</span><span class="op">[</span><span class="st">"female"</span><span class="op">]</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">fit_total</span><span class="op">)</span><span class="op">[</span><span class="st">"female"</span><span class="op">]</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      total.female    adjusted.female attenuation.female 
       -0.11375231        -0.07285748         0.04089483 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sens</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/sensemakr/man/sensemakr.html">sensemakr</a></span><span class="op">(</span>model <span class="op">=</span> <span class="va">fit_adj</span>, treatment <span class="op">=</span> <span class="st">"female"</span>,</span>
<span>                  benchmark_covariates <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"clg"</span>, <span class="st">"exp1"</span><span class="op">)</span>,</span>
<span>                  kd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">3</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">sens</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sensitivity Analysis to Unobserved Confounding

Model Formula: lwage ~ female + exp1 + sohs + hsg + socl + clg + mw + sout + 
    we + occ2 + ind2

Null hypothesis: q = 1 and reduce = TRUE 
-- This means we are considering biases that reduce the absolute value of the current estimate.
-- The null hypothesis deemed problematic is H0:tau = 0 

Unadjusted Estimates of 'female': 
  Coef. estimate: -0.0729 
  Standard Error: 0.015 
  t-value (H0:tau = 0): -4.8485 

Sensitivity Statistics:
  Partial R2 of treatment with outcome: 0.0046 
  Robustness Value, q = 1: 0.0656 
  Robustness Value, q = 1, alpha = 0.05: 0.0396 

Verbal interpretation of sensitivity statistics:

-- Partial R2 of the treatment with the outcome: an extreme confounder (orthogonal to the covariates) that explains 100% of the residual variance of the outcome, would need to explain at least 0.46% of the residual variance of the treatment to fully account for the observed estimated effect.

-- Robustness Value, q = 1: unobserved confounders (orthogonal to the covariates) that explain more than 6.56% of the residual variance of both the treatment and the outcome are strong enough to bring the point estimate to 0 (a bias of 100% of the original estimate). Conversely, unobserved confounders that do not explain more than 6.56% of the residual variance of both the treatment and the outcome are not strong enough to bring the point estimate to 0.

-- Robustness Value, q = 1, alpha = 0.05: unobserved confounders (orthogonal to the covariates) that explain more than 3.96% of the residual variance of both the treatment and the outcome are strong enough to bring the estimate to a range where it is no longer 'statistically different' from 0 (a bias of 100% of the original estimate), at the significance level of alpha = 0.05. Conversely, unobserved confounders that do not explain more than 3.96% of the residual variance of both the treatment and the outcome are not strong enough to bring the estimate to a range where it is no longer 'statistically different' from 0, at the significance level of alpha = 0.05.

Bounds on omitted variable bias:

--The table below shows the maximum strength of unobserved confounders with association with the treatment and the outcome bounded by a multiple of the observed explanatory power of the chosen benchmark covariate(s).

 Bound Label R2dz.x R2yz.dx Treatment Adjusted Estimate Adjusted Se Adjusted T
      1x clg 0.0001  0.0124    female           -0.0718      0.0149    -4.8081
      2x clg 0.0002  0.0247    female           -0.0708      0.0148    -4.7680
      3x clg 0.0002  0.0371    female           -0.0697      0.0147    -4.7275
     1x exp1 0.0016  0.0338    female           -0.0649      0.0148    -4.3914
     2x exp1 0.0032  0.0676    female           -0.0570      0.0145    -3.9199
     3x exp1 0.0048  0.1014    female           -0.0490      0.0143    -3.4322
 Adjusted Lower CI Adjusted Upper CI
           -0.1011           -0.0425
           -0.0999           -0.0417
           -0.0986           -0.0408
           -0.0939           -0.0359
           -0.0855           -0.0285
           -0.0770           -0.0210</code></pre>
</div>
</div>
<p>The additive models put the total effect at <span class="math inline">\(-11.4\%\)</span> and the occupation-adjusted effect at <span class="math inline">\(-7.3\%\)</span>, an attenuation of <span class="math inline">\(4.1\)</span> log points — essentially the same gap as in the interacted specifications.</p>
<p>Now invert the bias formula. Instead of asking how strong a confounder must be to drive the adjusted estimate to zero (the usual question), ask how strong it must be to move the adjusted estimate <em>back</em> to the total effect. That is the strength at which the entire apparent contribution of occupation is bias rather than mediation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">target</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">fit_total</span><span class="op">)</span><span class="op">[</span><span class="st">"female"</span><span class="op">]</span></span>
<span></span>
<span><span class="va">grid</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/expand.grid.html">expand.grid</a></span><span class="op">(</span>r2dz <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.0125</span>, <span class="fl">0.02</span>, <span class="fl">0.033</span>, <span class="fl">0.06</span><span class="op">)</span>,</span>
<span>                    r2yz <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0.001</span>, <span class="fl">0.60</span>, length.out <span class="op">=</span> <span class="fl">4000</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">grid</span><span class="op">$</span><span class="va">adj</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/sensemakr/man/adjusted_estimate.html">adjusted_estimate</a></span><span class="op">(</span><span class="va">fit_adj</span>, treatment <span class="op">=</span> <span class="st">"female"</span>,</span>
<span>                              r2dz.x <span class="op">=</span> <span class="va">grid</span><span class="op">$</span><span class="va">r2dz</span>, r2yz.dx <span class="op">=</span> <span class="va">grid</span><span class="op">$</span><span class="va">r2yz</span>,</span>
<span>                              reduce <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">grid</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">r2dz</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice_min</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">adj</span> <span class="op">-</span> <span class="va">target</span><span class="op">)</span>, n <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">ungroup</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/transmute.html">transmute</a></span><span class="op">(</span>`partial R2 with gender` <span class="op">=</span> <span class="va">r2dz</span>,</span>
<span>            `partial R2 with wage`   <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">r2yz</span>, <span class="fl">3</span><span class="op">)</span>,</span>
<span>            `restored estimate`      <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">adj</span>, <span class="fl">4</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  `partial R2 with gender` `partial R2 with wage` `restored estimate`
                     &lt;dbl&gt;                  &lt;dbl&gt;               &lt;dbl&gt;
1                   0.0125                  0.115              -0.114
2                   0.02                    0.071              -0.114
3                   0.033                   0.042              -0.114
4                   0.06                    0.023              -0.114</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># sensemakr is attached again here on purpose: the chunk above is cached, so on a</span></span>
<span><span class="co"># cache hit its library() call never runs and plot() would dispatch to</span></span>
<span><span class="co"># plot.default instead of the sensemakr method.</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/carloscinelli/sensemakr">sensemakr</a></span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">sens</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="gwg_files/figure-html/cde-contour-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Adjusted estimate of the gender gap as a function of a hypothetical confounder’s partial <span class="math inline">\(R^2\)</span> with gender (horizontal) and with log wage (vertical), benchmarked against college and experience.</figcaption></figure>
</div>
</div>
</div>
<p>The answer is uncomfortable. A confounder explaining about <strong>3% of the residual variance of gender and about 4% of the residual variance of wages</strong> is enough to restore the full total effect — that is, enough for occupation to be contributing no genuine mediation at all. For scale, <code>sensemakr</code> reports a robustness value of <span class="math inline">\(6.6\%\)</span>: a confounder explaining more than that share of both residual variances would drive the adjusted estimate to zero. So a <span class="math inline">\(U\)</span> roughly <em>half</em> as strong as the one needed to erase the within-occupation gap entirely is already strong enough to explain the whole <span class="math inline">\(11.3\% \to 7.5\%\)</span> attenuation.</p>
<p>The benchmark rows give another angle. Experience explains <span class="math inline">\(3.4\%\)</span> of the residual variance of wages but only <span class="math inline">\(0.16\%\)</span> of the residual variance of gender, so along the outcome dimension the required <span class="math inline">\(U\)</span> is only a little stronger than experience. Along the gender dimension the required multiple looks large, but that is mostly because gender is close to orthogonal to experience in this sample; in absolute terms we are still only asking for a few percent of residual variance.</p>
<p>None of this shows that occupational sorting explains nothing. It shows that this design cannot distinguish “sorting explains four points” from “conditioning on a collider costs four points,” and that the confounder needed to tip the balance is unremarkable in size. Which is why the total effect, not the occupation-adjusted number, is the estimate to lead with.</p>
<p>Now let’s try nonparametric estimation.</p>
</section></section><section id="nonparametric-estimation" class="level3" data-number="16.2.3"><h3 data-number="16.2.3" class="anchored" data-anchor-id="nonparametric-estimation">
<span class="header-section-number">16.2.3</span> Nonparametric estimation</h3>
<p>If we’d like to go for nonparametric, relaxing linearity assumption, then we can use “npcausal”. Note this may take a while, depending on which machine learning packages you decide to include. We can also use other nonparametric estimators, such as TMLE or doubleML.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">npcausal</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#SL.library &lt;- c("SL.earth","SL.glmnet","SL.glm.interaction", "SL.mean","SL.ranger", "SL.xgboost")</span></span>
<span></span>
<span></span>
<span><span class="va">SL.library</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"SL.earth"</span>,<span class="st">"SL.glmnet"</span>,<span class="st">"SL.mean"</span>,<span class="st">"SL.ranger"</span>, <span class="st">"SL.xgboost"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># construct W from model matrix of reg3</span></span>
<span><span class="va">reg3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">lwage</span> <span class="op">~</span> <span class="va">exp_dm</span> <span class="op">+</span> <span class="va">sohs</span> <span class="op">+</span> <span class="va">hsg</span><span class="op">+</span> <span class="va">socl</span> <span class="op">+</span> <span class="va">clg</span> <span class="op">+</span> <span class="va">mw</span> <span class="op">+</span> <span class="va">sout</span> <span class="op">+</span> <span class="va">we</span> <span class="op">+</span> <span class="va">occ2</span> <span class="op">+</span> <span class="va">ind2</span>, data<span class="op">=</span><span class="va">data</span><span class="op">)</span></span>
<span><span class="va">W</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/model.matrix.html">model.matrix</a></span><span class="op">(</span><span class="va">reg3</span><span class="op">)</span><span class="op">[</span>, <span class="op">-</span><span class="fl">1</span><span class="op">]</span><span class="op">)</span> <span class="co"># remove intercept</span></span>
<span></span>
<span><span class="va">Y</span> <span class="op">&lt;-</span> <span class="va">data</span><span class="op">$</span><span class="va">lwage</span></span>
<span><span class="va">A</span> <span class="op">&lt;-</span> <span class="va">data</span><span class="op">$</span><span class="va">female</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span></span>
<span><span class="va">aipw_ate</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/npcausal/man/ate.html">ate</a></span><span class="op">(</span>y<span class="op">=</span><span class="va">Y</span>, a<span class="op">=</span><span class="va">A</span>, x<span class="op">=</span><span class="va">W</span>, nsplits<span class="op">=</span><span class="fl">5</span>, sl.lib<span class="op">=</span><span class="va">SL.library</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  |                                                                            
  |                                                                      |   0%</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
  |                                                                            
  |====                                                                  |   5%
  |                                                                            
  |=======                                                               |  10%
  |                                                                            
  |==========                                                            |  15%
  |                                                                            
  |==============                                                        |  20%
  |                                                                            
  |==================                                                    |  25%
  |                                                                            
  |=====================                                                 |  30%</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
  |                                                                            
  |========================                                              |  35%
  |                                                                            
  |============================                                          |  40%
  |                                                                            
  |================================                                      |  45%
  |                                                                            
  |===================================                                   |  50%
  |                                                                            
  |======================================                                |  55%
  |                                                                            
  |==========================================                            |  60%
  |                                                                            
  |==============================================                        |  65%
  |                                                                            
  |=================================================                     |  70%
  |                                                                            
  |====================================================                  |  75%
  |                                                                            
  |========================================================              |  80%
  |                                                                            
  |============================================================          |  85%
  |                                                                            
  |===============================================================       |  90%
  |                                                                            
  |==================================================================    |  95%
  |                                                                            
  |======================================================================| 100%
     parameter         est         se       ci.ll       ci.ul pval
1      E{Y(0)}  2.99695506 0.01093465  2.97552315  3.01838697    0
2      E{Y(1)}  2.93906408 0.01327342  2.91304817  2.96507999    0
3 E{Y(1)-Y(0)} -0.05789098 0.01597522 -0.08920241 -0.02657955    0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">aipw_att</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/npcausal/man/att.html">att</a></span><span class="op">(</span>y<span class="op">=</span><span class="va">Y</span>, a<span class="op">=</span><span class="va">A</span>, x<span class="op">=</span><span class="va">W</span>, nsplits<span class="op">=</span><span class="fl">5</span>, sl.lib<span class="op">=</span><span class="va">SL.library</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  |                                                                            
  |                                                                      |   0%</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
  |                                                                            
  |=======                                                               |  10%
  |                                                                            
  |==============                                                        |  20%</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
  |                                                                            
  |=====================                                                 |  30%
  |                                                                            
  |============================                                          |  40%
  |                                                                            
  |===================================                                   |  50%
  |                                                                            
  |==========================================                            |  60%
  |                                                                            
  |=================================================                     |  70%
  |                                                                            
  |========================================================              |  80%
  |                                                                            
  |===============================================================       |  90%
  |                                                                            
  |======================================================================| 100%
      parameter         est         se       ci.ll       ci.ul pval
1      E(Y|A=1)  2.94948490 0.01160804  2.92673314  2.97223666    0
2   E{Y(0)|A=1}  3.01689509 0.01221863  2.99294658  3.04084360    0
3 E{Y-Y(0)|A=1} -0.06741019 0.01409116 -0.09502886 -0.03979152    0</code></pre>
</div>
</div>
<p>The two fits above print only SuperLearner’s progress bars, so the estimates themselves have to be asked for:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">aipw_ate</span><span class="op">$</span><span class="va">res</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     parameter         est         se       ci.ll       ci.ul pval
1      E{Y(0)}  2.99695506 0.01093465  2.97552315  3.01838697    0
2      E{Y(1)}  2.93906408 0.01327342  2.91304817  2.96507999    0
3 E{Y(1)-Y(0)} -0.05789098 0.01597522 -0.08920241 -0.02657955    0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">aipw_att</span><span class="op">$</span><span class="va">res</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      parameter         est         se       ci.ll       ci.ul pval
1      E(Y|A=1)  2.94948490 0.01160804  2.92673314  2.97223666    0
2   E{Y(0)|A=1}  3.01689509 0.01221863  2.99294658  3.04084360    0
3 E{Y-Y(0)|A=1} -0.06741019 0.01409116 -0.09502886 -0.03979152    0</code></pre>
</div>
</div>
<p>Two estimates come out of this: an AIPW <strong>ATE</strong> of <span class="math inline">\(-5.8\%\)</span> (95% CI <span class="math inline">\(-8.9\%\)</span> to <span class="math inline">\(-2.7\%\)</span>) and an AIPW <strong>ATT</strong> of <span class="math inline">\(-6.7\%\)</span> (95% CI <span class="math inline">\(-9.5\%\)</span> to <span class="math inline">\(-3.9\%\)</span>).</p>
<p>The comparison worth making is like with like. The <span class="math inline">\(-7.5\%\)</span> from the fully interacted linear model above was an ATT (it was computed on <code>newdata = subset(data, female == 1)</code>), so it should be set against the nonparametric <strong>ATT</strong> of <span class="math inline">\(-6.7\%\)</span>, not against the ATE. Those two agree closely, which is reassuring: dropping the linearity assumption altogether moves the estimate by less than a percentage point, and both use the same covariate set including occupation and industry.</p>
<p>That last clause is also the caveat. Because both specifications condition on occupation and industry, both inherit the bad-control problem set out above: the agreement between <span class="math inline">\(-7.5\%\)</span> and <span class="math inline">\(-6.7\%\)</span> tells us the two estimators recover the same quantity, not that the quantity is a causal effect. Relaxing linearity addresses functional form; it leaves the collider untouched.</p>
<p>The ATE and ATT point estimates do differ a little, in the direction of a larger gap among women than in the sample as a whole — which would indicate effect heterogeneity across the covariates. Their confidence intervals overlap heavily, though, so this data cannot really distinguish them.</p>


<!-- -->

</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/xiangao\.github\.io\/blog_book\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./sensitivity-analysis.html" class="pagination-link" aria-label="Sensitivity analysis of OLS with sensemakr">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Sensitivity analysis of OLS with sensemakr</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./causal-forest-panel.html" class="pagination-link" aria-label="Causal Forest in panel data">
        <span class="nav-page-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Causal Forest in panel data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb37" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Gender Wage Gap Analysis Using US Current Population Survey Data"</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Xiang Ao"</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2025-11-17"</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>Traditionally Oaxaca-Blinder decomposition is used to decompose the wage gap into explained and unexplained parts. The explained part is due to differences in observable characteristics, such as education, experience, occupation, etc. The unexplained part is due to discrimination or other unobserved factors.</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>It has a problem that when decomposing, using female as reference group or male as reference group will give different results.</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>Słoczyński (2015) and Słoczyński (2013) have shown that a regression adjustment type of analysis is equivalent to Oaxaca-Blinder decomposition in a nonstandard way.</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a><span class="fu">## Oaxaca-Blinder decomposition</span></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>Assume the regression model is different for male and female: $$ y_i = X_i \beta_a + \epsilon_a $$</span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>where $a$ is gender (female is 1), $X$'s are person characteristics.</span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a>$$ E<span class="co">[</span><span class="ot">y_i | a_i = 1</span><span class="co">]</span> - E<span class="co">[</span><span class="ot">y_i | a_i = 0</span><span class="co">]</span> = E<span class="co">[</span><span class="ot">X_i | a_i=1</span><span class="co">]</span>  (\beta_1 - \beta_0) + (E<span class="co">[</span><span class="ot">X_i | a_i =1 </span><span class="co">]</span> - E<span class="co">[</span><span class="ot">X_i | a_i = 0</span><span class="co">]</span>) \beta_0 $$</span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a>or</span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-23"><a href="#cb37-23" aria-hidden="true" tabindex="-1"></a>$$ E<span class="co">[</span><span class="ot">y_i | a_i = 1</span><span class="co">]</span> - E<span class="co">[</span><span class="ot">y_i | a_i = 0</span><span class="co">]</span> = E<span class="co">[</span><span class="ot">X_i | a_i=0</span><span class="co">]</span>  (\beta_1 - \beta_0) + (E<span class="co">[</span><span class="ot">X_i | a_i =1 </span><span class="co">]</span> - E<span class="co">[</span><span class="ot">X_i | a_i = 0</span><span class="co">]</span>) \beta_1 $$ These two equations are different forms of the Oaxaca-Blinder decomposition. The first element is the "unexplained component", which is the difference in the coefficients, and the second element is the "explained component", which is the difference in the means of the covariates.</span>
<span id="cb37-24"><a href="#cb37-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-25"><a href="#cb37-25" aria-hidden="true" tabindex="-1"></a>These two equations can give different results for the two components, one has a baseline of male, and other one female.</span>
<span id="cb37-26"><a href="#cb37-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-27"><a href="#cb37-27" aria-hidden="true" tabindex="-1"></a>We can further shows that</span>
<span id="cb37-28"><a href="#cb37-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-29"><a href="#cb37-29" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb37-30"><a href="#cb37-30" aria-hidden="true" tabindex="-1"></a>\begin{align}</span>
<span id="cb37-31"><a href="#cb37-31" aria-hidden="true" tabindex="-1"></a>E<span class="co">[</span><span class="ot">y_i | a_i =1</span><span class="co">]</span> - E<span class="co">[</span><span class="ot">y_i | a_i=0</span><span class="co">]</span> &amp;= E<span class="co">[</span><span class="ot">X_i | a_i=1</span><span class="co">]</span>  (\beta_1 - \beta_0) + (E<span class="co">[</span><span class="ot">X_i | a_i =1 </span><span class="co">]</span> - E<span class="co">[</span><span class="ot">X_i | a_i = 0</span><span class="co">]</span>) \beta_0  <span class="sc">\\</span></span>
<span id="cb37-32"><a href="#cb37-32" aria-hidden="true" tabindex="-1"></a>&amp;= E<span class="co">[</span><span class="ot">y_i(1) - y_i(0) | a_i=1</span><span class="co">]</span> + (E<span class="co">[</span><span class="ot">y_i(0) | a_i=1</span><span class="co">]</span> - E<span class="co">[</span><span class="ot">y_i(0) | a_i = 0</span><span class="co">]</span>) <span class="sc">\\</span></span>
<span id="cb37-33"><a href="#cb37-33" aria-hidden="true" tabindex="-1"></a>&amp;= \tau_{PATT} + (E<span class="co">[</span><span class="ot">y_i(0) | a_i=1</span><span class="co">]</span> - E<span class="co">[</span><span class="ot">y_i(0) | a_i=0</span><span class="co">]</span>)</span>
<span id="cb37-34"><a href="#cb37-34" aria-hidden="true" tabindex="-1"></a>\end{align}</span>
<span id="cb37-35"><a href="#cb37-35" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb37-36"><a href="#cb37-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-37"><a href="#cb37-37" aria-hidden="true" tabindex="-1"></a>That is, the observed difference is the sum of $\tau_{PATT}$ and selection bias. It is also known in the OB decomposition literature as the unexplained component and the explained component. The former as "discrimination".</span>
<span id="cb37-38"><a href="#cb37-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-39"><a href="#cb37-39" aria-hidden="true" tabindex="-1"></a>We can simply use Regression Adjustment for these quantities.  The easiest is an OLS of $y_i$ on $a_i$, the demeaned $X_i$, and their interaction; the coefficient on $a_i$ is then the effect evaluated at the mean of the covariates used for the demeaning.  Demean at the **overall** mean and that coefficient is $\tau_{PAGE}$ (the ATE), which is what the example below does; demean at the mean among **women** instead and it is $\tau_{PATT}$.  The choice of centring is what selects the estimand, so it is worth being explicit about which one you have.</span>
<span id="cb37-40"><a href="#cb37-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-41"><a href="#cb37-41" aria-hidden="true" tabindex="-1"></a>He also advocates the "population average gender effect" (PAGE):</span>
<span id="cb37-42"><a href="#cb37-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-43"><a href="#cb37-43" aria-hidden="true" tabindex="-1"></a>$$ \tau_{PAGE} = E<span class="co">[</span><span class="ot">\tau(X_i)</span><span class="co">]</span> $$</span>
<span id="cb37-44"><a href="#cb37-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-45"><a href="#cb37-45" aria-hidden="true" tabindex="-1"></a>which is basically ATE, or conditional average effect (CATE), then average over the $X$'s.</span>
<span id="cb37-46"><a href="#cb37-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-47"><a href="#cb37-47" aria-hidden="true" tabindex="-1"></a>In this version, the two forms of OB decomposition can be $\tau_{PAGM}$ and $\tau_{PAGW}$, for men and women.</span>
<span id="cb37-48"><a href="#cb37-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-49"><a href="#cb37-49" aria-hidden="true" tabindex="-1"></a>The nice thing about this estimator $\tau_{PAGE}$ is that first, it is consistent with the treatment effect (causal inference) literature, and it is invariant to the choice of reference group.</span>
<span id="cb37-50"><a href="#cb37-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-51"><a href="#cb37-51" aria-hidden="true" tabindex="-1"></a>The second advantage is that we also do not need to assume homogeneity of treatment effect, which is a strong assumption in the Oaxaca-Blinder decomposition.</span>
<span id="cb37-52"><a href="#cb37-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-53"><a href="#cb37-53" aria-hidden="true" tabindex="-1"></a>The third advantage is that we can use nonparametric methods to estimate the treatment effect. Traditional OB decomposition is based on linear regression, which assumes a linear relationship between the covariates and the outcome.</span>
<span id="cb37-54"><a href="#cb37-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-55"><a href="#cb37-55" aria-hidden="true" tabindex="-1"></a><span class="fu">## Example</span></span>
<span id="cb37-56"><a href="#cb37-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-57"><a href="#cb37-57" aria-hidden="true" tabindex="-1"></a>I am using the data from https://github.com/d2cml-ai/CausalAI-Course/tree/main/data.</span>
<span id="cb37-58"><a href="#cb37-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-59"><a href="#cb37-59" aria-hidden="true" tabindex="-1"></a>"The data set we consider is from the 2015 March Supplement of the U.S. Current Population Survey. We select white non-hispanic individuals, aged 25 to 64 years, and working more than 35 hours per week for at least 50 weeks of the year. We exclude self-employed workers; individuals living in group quarters; individuals in the military, agricultural or private household sectors; individuals with inconsistent reports on earnings and employment status; individuals with allocated or missing information in any of the variables used in the analysis; and individuals with hourly wage below 3. "</span>
<span id="cb37-60"><a href="#cb37-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-61"><a href="#cb37-61" aria-hidden="true" tabindex="-1"></a>I am using this data to study gender wage gap (GWP).</span>
<span id="cb37-62"><a href="#cb37-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-63"><a href="#cb37-63" aria-hidden="true" tabindex="-1"></a>We can model GWP using the potential outcome framework, with some care about what plays the role of "treatment." Gender itself is an immutable characteristic, not something that can be manipulated or randomized — the standard "no causation without manipulation" principle (Holland, 1986) says we should not treat gender itself as a causal treatment. What we really have in mind, and what the "treatment" indicator below is best understood as a proxy for, is something like *being perceived/treated as female by employers* (e.g., employer discrimination), which is at least conceptually manipulable even though we cannot experimentally assign it here. With that caveat in mind, we let $D=1$ if female, $D=0$ if male, and outcome $Y$ is logged wage.</span>
<span id="cb37-64"><a href="#cb37-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-65"><a href="#cb37-65" aria-hidden="true" tabindex="-1"></a>The ATE would be</span>
<span id="cb37-66"><a href="#cb37-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-67"><a href="#cb37-67" aria-hidden="true" tabindex="-1"></a>$$ \delta_{ATE} = E<span class="co">[</span><span class="ot">Y(1) - Y(0)</span><span class="co">]</span> $$</span>
<span id="cb37-68"><a href="#cb37-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-69"><a href="#cb37-69" aria-hidden="true" tabindex="-1"></a>where $Y(1)$ is the potential outcome if treated, and $Y(0)$ is the potential outcome if not treated.</span>
<span id="cb37-70"><a href="#cb37-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-71"><a href="#cb37-71" aria-hidden="true" tabindex="-1"></a><span class="fu">### Regression adjustment</span></span>
<span id="cb37-72"><a href="#cb37-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-73"><a href="#cb37-73" aria-hidden="true" tabindex="-1"></a>Since this is to estimate ATE, we can use regression adjustment to estimate the ATE. First let's use de-meaned $X$'s. Then the coefficient on gender is the ATE.</span>
<span id="cb37-74"><a href="#cb37-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-75"><a href="#cb37-75" aria-hidden="true" tabindex="-1"></a>We use These variables as $X$'s:</span>
<span id="cb37-76"><a href="#cb37-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-77"><a href="#cb37-77" aria-hidden="true" tabindex="-1"></a>"shs","hsg","scl","clg","ad","ne","mw","so","we","exp1", "occ", "occ2", "ind", and "ind2".</span>
<span id="cb37-78"><a href="#cb37-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-79"><a href="#cb37-79" aria-hidden="true" tabindex="-1"></a>They are:</span>
<span id="cb37-80"><a href="#cb37-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-81"><a href="#cb37-81" aria-hidden="true" tabindex="-1"></a>"Less then High School","High School Graduate","Some College","College Graduate","Advanced Degree", "Northeast","Midwest","South","West","Experience", "occupation", "occupation 2", "industry", and "industry 2".</span>
<span id="cb37-82"><a href="#cb37-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-83"><a href="#cb37-83" aria-hidden="true" tabindex="-1"></a>I decide to use "occ2" and "ind2" as they are broader categories of occupation and industry. We don't have enough data for finer categories "occ" and "ind".</span>
<span id="cb37-84"><a href="#cb37-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-85"><a href="#cb37-85" aria-hidden="true" tabindex="-1"></a>"exp1" seems to be the only variable that is continuous, let's demean it first. Let's also input "occ2" and "ind2" as factors.</span>
<span id="cb37-86"><a href="#cb37-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-87"><a href="#cb37-87" aria-hidden="true" tabindex="-1"></a>Let's include demeaned "exp1", "sohs", "hsg", "socl", "clg", "mw", "sout", and "we" first.  I leave out "occ2" and "ind2" since there are too many levels to demean.</span>
<span id="cb37-88"><a href="#cb37-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-91"><a href="#cb37-91" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-92"><a href="#cb37-92" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: ra1</span></span>
<span id="cb37-93"><a href="#cb37-93" aria-hidden="true" tabindex="-1"></a><span class="co">#| cache: true</span></span>
<span id="cb37-94"><a href="#cb37-94" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb37-95"><a href="#cb37-95" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb37-96"><a href="#cb37-96" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb37-97"><a href="#cb37-97" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb37-98"><a href="#cb37-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-99"><a href="#cb37-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-100"><a href="#cb37-100" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"wage2015_subsample_inference.csv"</span>) <span class="sc">|&gt;</span></span>
<span id="cb37-101"><a href="#cb37-101" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">socl =</span> scl, <span class="at">sohs =</span> shs, <span class="at">sout =</span> so) <span class="sc">|&gt;</span></span>
<span id="cb37-102"><a href="#cb37-102" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">exp_dm =</span> exp1 <span class="sc">-</span> <span class="fu">mean</span>(exp1, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">female=</span>sex, <span class="at">occ2 =</span> <span class="fu">factor</span>(occ2), <span class="at">ind2 =</span> <span class="fu">factor</span>(ind2)) <span class="sc">|&gt;</span></span>
<span id="cb37-103"><a href="#cb37-103" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sohs_dm =</span> sohs <span class="sc">-</span> <span class="fu">mean</span>(sohs, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb37-104"><a href="#cb37-104" aria-hidden="true" tabindex="-1"></a>         <span class="at">hsg_dm =</span> hsg <span class="sc">-</span> <span class="fu">mean</span>(hsg, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb37-105"><a href="#cb37-105" aria-hidden="true" tabindex="-1"></a>         <span class="at">socl_dm =</span> socl <span class="sc">-</span> <span class="fu">mean</span>(socl, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb37-106"><a href="#cb37-106" aria-hidden="true" tabindex="-1"></a>         <span class="at">clg_dm =</span> clg <span class="sc">-</span> <span class="fu">mean</span>(clg, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb37-107"><a href="#cb37-107" aria-hidden="true" tabindex="-1"></a>         <span class="at">mw_dm =</span> mw <span class="sc">-</span> <span class="fu">mean</span>(mw, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb37-108"><a href="#cb37-108" aria-hidden="true" tabindex="-1"></a>         <span class="at">sout_dm =</span> sout <span class="sc">-</span> <span class="fu">mean</span>(sout, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb37-109"><a href="#cb37-109" aria-hidden="true" tabindex="-1"></a>         <span class="at">we_dm =</span> we <span class="sc">-</span> <span class="fu">mean</span>(we, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb37-110"><a href="#cb37-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-111"><a href="#cb37-111" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data)</span>
<span id="cb37-112"><a href="#cb37-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-113"><a href="#cb37-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-114"><a href="#cb37-114" aria-hidden="true" tabindex="-1"></a><span class="co"># construct matrices for estimation from the data</span></span>
<span id="cb37-115"><a href="#cb37-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-116"><a href="#cb37-116" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. basic model</span></span>
<span id="cb37-117"><a href="#cb37-117" aria-hidden="true" tabindex="-1"></a>reg1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(lwage <span class="sc">~</span> female, <span class="at">data=</span>data)</span>
<span id="cb37-118"><a href="#cb37-118" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(reg1)</span>
<span id="cb37-119"><a href="#cb37-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-120"><a href="#cb37-120" aria-hidden="true" tabindex="-1"></a>reg2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(lwage <span class="sc">~</span> female<span class="sc">*</span>(exp_dm <span class="sc">+</span> sohs_dm <span class="sc">+</span> hsg_dm <span class="sc">+</span> socl_dm <span class="sc">+</span> clg_dm <span class="sc">+</span> mw_dm <span class="sc">+</span> sout_dm <span class="sc">+</span> we_dm), <span class="at">data=</span>data)</span>
<span id="cb37-121"><a href="#cb37-121" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(reg2)</span>
<span id="cb37-122"><a href="#cb37-122" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-123"><a href="#cb37-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-124"><a href="#cb37-124" aria-hidden="true" tabindex="-1"></a>We see the raw gap is 3.8%.  Adjusting for some covariates we have 11% gap.</span>
<span id="cb37-125"><a href="#cb37-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-126"><a href="#cb37-126" aria-hidden="true" tabindex="-1"></a>Or, we can use "marginaleffects" instead of demeaning.</span>
<span id="cb37-127"><a href="#cb37-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-130"><a href="#cb37-130" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-131"><a href="#cb37-131" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: ra2</span></span>
<span id="cb37-132"><a href="#cb37-132" aria-hidden="true" tabindex="-1"></a><span class="co">#| cache: true</span></span>
<span id="cb37-133"><a href="#cb37-133" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb37-134"><a href="#cb37-134" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb37-135"><a href="#cb37-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-136"><a href="#cb37-136" aria-hidden="true" tabindex="-1"></a>reg3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(lwage <span class="sc">~</span> female<span class="sc">*</span>(exp1 <span class="sc">+</span> sohs <span class="sc">+</span> hsg<span class="sc">+</span> socl <span class="sc">+</span> clg <span class="sc">+</span> mw <span class="sc">+</span> sout <span class="sc">+</span> we ), <span class="at">data=</span>data)</span>
<span id="cb37-137"><a href="#cb37-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-138"><a href="#cb37-138" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(marginaleffects)</span>
<span id="cb37-139"><a href="#cb37-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-140"><a href="#cb37-140" aria-hidden="true" tabindex="-1"></a><span class="fu">avg_comparisons</span>(reg3,</span>
<span id="cb37-141"><a href="#cb37-141" aria-hidden="true" tabindex="-1"></a>                <span class="at">variables =</span> <span class="st">"female"</span>)</span>
<span id="cb37-142"><a href="#cb37-142" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-143"><a href="#cb37-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-144"><a href="#cb37-144" aria-hidden="true" tabindex="-1"></a>We get the same result as the demeaned regression.</span>
<span id="cb37-145"><a href="#cb37-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-146"><a href="#cb37-146" aria-hidden="true" tabindex="-1"></a>If we want $\tau_{ATT}$, then we can use the "newdata" argument to specify the treatment group,</span>
<span id="cb37-149"><a href="#cb37-149" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-150"><a href="#cb37-150" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: ra3</span></span>
<span id="cb37-151"><a href="#cb37-151" aria-hidden="true" tabindex="-1"></a><span class="co">#| cache: true</span></span>
<span id="cb37-152"><a href="#cb37-152" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb37-153"><a href="#cb37-153" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb37-154"><a href="#cb37-154" aria-hidden="true" tabindex="-1"></a><span class="fu">avg_comparisons</span>(reg3,</span>
<span id="cb37-155"><a href="#cb37-155" aria-hidden="true" tabindex="-1"></a>                <span class="at">variables =</span> <span class="st">"female"</span>,</span>
<span id="cb37-156"><a href="#cb37-156" aria-hidden="true" tabindex="-1"></a>                <span class="at">newdata =</span> <span class="fu">subset</span>(data, female <span class="sc">==</span> <span class="dv">1</span>))</span>
<span id="cb37-157"><a href="#cb37-157" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-158"><a href="#cb37-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-159"><a href="#cb37-159" aria-hidden="true" tabindex="-1"></a><span class="fu">### Occupation and industry: a bad control problem</span></span>
<span id="cb37-160"><a href="#cb37-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-161"><a href="#cb37-161" aria-hidden="true" tabindex="-1"></a>Before adding occupation and industry, it is worth being clear about what kind of variables they are. Everything used so far --- experience, education, region --- is plausibly settled before the wage is determined and is not itself much of a consequence of gender. Occupation and industry are different. They are **post-treatment**: whatever "being perceived and treated as female" does, one of the things it does is shift which occupations people end up in.</span>
<span id="cb37-162"><a href="#cb37-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-163"><a href="#cb37-163" aria-hidden="true" tabindex="-1"></a>That makes them *bad controls* in the sense of Cinelli, Forney and Pearl (2022), and for two separate reasons at the same time.</span>
<span id="cb37-164"><a href="#cb37-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-167"><a href="#cb37-167" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-168"><a href="#cb37-168" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: gwg-dag</span></span>
<span id="cb37-169"><a href="#cb37-169" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Occupation is both a mediator of the gender--wage relationship and a collider on a path through unobserved wage determinants $U$."</span></span>
<span id="cb37-170"><a href="#cb37-170" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 7</span></span>
<span id="cb37-171"><a href="#cb37-171" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 3.6</span></span>
<span id="cb37-172"><a href="#cb37-172" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb37-173"><a href="#cb37-173" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb37-174"><a href="#cb37-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-175"><a href="#cb37-175" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggdag)</span>
<span id="cb37-176"><a href="#cb37-176" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb37-177"><a href="#cb37-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-178"><a href="#cb37-178" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">dagify</span>(</span>
<span id="cb37-179"><a href="#cb37-179" aria-hidden="true" tabindex="-1"></a>  Wage <span class="sc">~</span> Female <span class="sc">+</span> Occupation <span class="sc">+</span> U,</span>
<span id="cb37-180"><a href="#cb37-180" aria-hidden="true" tabindex="-1"></a>  Occupation <span class="sc">~</span> Female <span class="sc">+</span> U,</span>
<span id="cb37-181"><a href="#cb37-181" aria-hidden="true" tabindex="-1"></a>  <span class="at">exposure =</span> <span class="st">"Female"</span>,</span>
<span id="cb37-182"><a href="#cb37-182" aria-hidden="true" tabindex="-1"></a>  <span class="at">outcome  =</span> <span class="st">"Wage"</span>,</span>
<span id="cb37-183"><a href="#cb37-183" aria-hidden="true" tabindex="-1"></a>  <span class="at">coords =</span> <span class="fu">list</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="at">Female =</span> <span class="dv">0</span>, <span class="at">Occupation =</span> <span class="fl">1.1</span>, <span class="at">U =</span> <span class="fl">1.1</span>, <span class="at">Wage =</span> <span class="fl">2.2</span>),</span>
<span id="cb37-184"><a href="#cb37-184" aria-hidden="true" tabindex="-1"></a>                <span class="at">y =</span> <span class="fu">c</span>(<span class="at">Female =</span> <span class="dv">0</span>, <span class="at">Occupation =</span> <span class="sc">-</span><span class="dv">1</span>,  <span class="at">U =</span> <span class="dv">1</span>,   <span class="at">Wage =</span> <span class="dv">0</span>))</span>
<span id="cb37-185"><a href="#cb37-185" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb37-186"><a href="#cb37-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-187"><a href="#cb37-187" aria-hidden="true" tabindex="-1"></a><span class="co"># node_size has to stay small: ggdag stops each edge at the node boundary, so</span></span>
<span id="cb37-188"><a href="#cb37-188" aria-hidden="true" tabindex="-1"></a><span class="co"># large nodes swallow the arrowheads -- and the arrowheads are the whole point.</span></span>
<span id="cb37-189"><a href="#cb37-189" aria-hidden="true" tabindex="-1"></a><span class="fu">ggdag</span>(g, <span class="at">text =</span> <span class="cn">FALSE</span>, <span class="at">node_size =</span> <span class="dv">9</span>) <span class="sc">+</span></span>
<span id="cb37-190"><a href="#cb37-190" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_dag_text_repel</span>(<span class="fu">aes</span>(<span class="at">label =</span> name), <span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="fl">3.2</span>,</span>
<span id="cb37-191"><a href="#cb37-191" aria-hidden="true" tabindex="-1"></a>                      <span class="at">box.padding =</span> <span class="fl">0.9</span>, <span class="at">seed =</span> <span class="dv">42</span>) <span class="sc">+</span></span>
<span id="cb37-192"><a href="#cb37-192" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_dag</span>() <span class="sc">+</span></span>
<span id="cb37-193"><a href="#cb37-193" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expand_limits</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.45</span>, <span class="fl">2.65</span>), <span class="at">y =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">1.5</span>, <span class="fl">1.5</span>))</span>
<span id="cb37-194"><a href="#cb37-194" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-195"><a href="#cb37-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-196"><a href="#cb37-196" aria-hidden="true" tabindex="-1"></a>Here $U$ stands for unobserved wage determinants --- drive, negotiation propensity, family constraints, expected career continuity --- and <span class="in">`Occupation`</span> covers occupation and industry together.</span>
<span id="cb37-197"><a href="#cb37-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-198"><a href="#cb37-198" aria-hidden="true" tabindex="-1"></a>**Occupation is a mediator.** Part of the total effect of gender on wages runs <span class="in">`Female -&gt; Occupation -&gt; Wage`</span>. Conditioning on occupation blocks that path, so the coefficient stops estimating a total effect. On its own this would be tolerable, as long as we said so: we would be reporting a within-occupation gap, which is a perfectly coherent descriptive quantity.</span>
<span id="cb37-199"><a href="#cb37-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-200"><a href="#cb37-200" aria-hidden="true" tabindex="-1"></a>**Occupation is also a collider.** It is a common effect of gender and of $U$. Conditioning on a common effect *induces* an association between its causes, so conditioning on occupation opens the non-causal path <span class="in">`Female -&gt; Occupation &lt;- U -&gt; Wage`</span>, which was closed before we touched anything (Elwert and Winship, 2014).</span>
<span id="cb37-201"><a href="#cb37-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-202"><a href="#cb37-202" aria-hidden="true" tabindex="-1"></a>We do not have to take that on faith. <span class="in">`dagitty`</span> will enumerate the paths and say which are open, with and without conditioning on occupation:</span>
<span id="cb37-203"><a href="#cb37-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-206"><a href="#cb37-206" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-207"><a href="#cb37-207" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: gwg-paths</span></span>
<span id="cb37-208"><a href="#cb37-208" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb37-209"><a href="#cb37-209" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb37-210"><a href="#cb37-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-211"><a href="#cb37-211" aria-hidden="true" tabindex="-1"></a>paths_table <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">Z =</span> <span class="cn">NULL</span>) {</span>
<span id="cb37-212"><a href="#cb37-212" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> dagitty<span class="sc">::</span><span class="fu">paths</span>(g, <span class="at">from =</span> <span class="st">"Female"</span>, <span class="at">to =</span> <span class="st">"Wage"</span>, <span class="at">Z =</span> Z)</span>
<span id="cb37-213"><a href="#cb37-213" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">path =</span> p<span class="sc">$</span>paths, <span class="at">open =</span> p<span class="sc">$</span>open)</span>
<span id="cb37-214"><a href="#cb37-214" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb37-215"><a href="#cb37-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-216"><a href="#cb37-216" aria-hidden="true" tabindex="-1"></a><span class="fu">paths_table</span>()                   <span class="co"># nothing conditioned on</span></span>
<span id="cb37-217"><a href="#cb37-217" aria-hidden="true" tabindex="-1"></a><span class="fu">paths_table</span>(<span class="at">Z =</span> <span class="st">"Occupation"</span>)   <span class="co"># conditioning on occupation</span></span>
<span id="cb37-218"><a href="#cb37-218" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-219"><a href="#cb37-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-220"><a href="#cb37-220" aria-hidden="true" tabindex="-1"></a>The two tables are the whole argument. Conditioning on occupation flips <span class="in">`Female -&gt; Occupation -&gt; Wage`</span> from open to closed --- that is the mediation we knowingly gave up --- and simultaneously flips <span class="in">`Female -&gt; Occupation &lt;- U -&gt; Wage`</span> from closed to open. That second flip is the damage. Blocking a mediator removes something we wanted; conditioning on a collider manufactures something we did not. After adjustment, gender and $U$ are correlated *within* occupation cells even if they are independent in the population, and because $U$ also drives wages, that induced correlation leaks into the gender coefficient.</span>
<span id="cb37-221"><a href="#cb37-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-222"><a href="#cb37-222" aria-hidden="true" tabindex="-1"></a>Stated formally: conditioning on a mediator identifies a *controlled direct effect* only under **no unmeasured mediator--outcome confounding** (VanderWeele and Robinson, 2014). $U$ is exactly such a confounder, and in a wage setting it is not a remote worry --- it is more or less why this literature exists.</span>
<span id="cb37-223"><a href="#cb37-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-224"><a href="#cb37-224" aria-hidden="true" tabindex="-1"></a>Two consequences worth flagging before we run the model. First, this is not a problem that a better estimator solves: the AIPW and SuperLearner fits later in this chapter relax functional form, and do nothing at all about a structurally uninterpretable estimand. Second, the same graph applies to the sample itself. This extract keeps only full-year, full-time workers, and employment is likewise a common effect of gender and $U$ --- so the sample restriction is a second conditioning-on-a-collider step, built in before any regression is run.</span>
<span id="cb37-225"><a href="#cb37-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-226"><a href="#cb37-226" aria-hidden="true" tabindex="-1"></a>With all that on the table, here is the model.</span>
<span id="cb37-227"><a href="#cb37-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-230"><a href="#cb37-230" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-231"><a href="#cb37-231" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: ra4</span></span>
<span id="cb37-232"><a href="#cb37-232" aria-hidden="true" tabindex="-1"></a><span class="co">#| cache: true</span></span>
<span id="cb37-233"><a href="#cb37-233" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb37-234"><a href="#cb37-234" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb37-235"><a href="#cb37-235" aria-hidden="true" tabindex="-1"></a>reg4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(lwage <span class="sc">~</span> female<span class="sc">*</span>(exp1 <span class="sc">+</span> sohs <span class="sc">+</span> hsg<span class="sc">+</span> socl <span class="sc">+</span> clg <span class="sc">+</span> mw <span class="sc">+</span> sout <span class="sc">+</span> we <span class="sc">+</span> occ2 <span class="sc">+</span> ind2), <span class="at">data=</span>data)</span>
<span id="cb37-236"><a href="#cb37-236" aria-hidden="true" tabindex="-1"></a><span class="fu">avg_comparisons</span>(reg4,</span>
<span id="cb37-237"><a href="#cb37-237" aria-hidden="true" tabindex="-1"></a>                <span class="at">variables =</span> <span class="st">"female"</span>,</span>
<span id="cb37-238"><a href="#cb37-238" aria-hidden="true" tabindex="-1"></a>                <span class="at">newdata =</span> <span class="fu">subset</span>(data, female <span class="sc">==</span> <span class="dv">1</span>))</span>
<span id="cb37-239"><a href="#cb37-239" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-240"><a href="#cb37-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-241"><a href="#cb37-241" aria-hidden="true" tabindex="-1"></a>So in the model with full interaction, we have a gap of 7.5%, against 11.3% without occupation and industry.</span>
<span id="cb37-242"><a href="#cb37-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-243"><a href="#cb37-243" aria-hidden="true" tabindex="-1"></a>The tempting reading of that pair --- "occupational and industrial sorting accounts for roughly four points of the gap" --- is exactly the reading the graph above forbids. Three things are mixed into that four-point move, and nothing in the output separates them:</span>
<span id="cb37-244"><a href="#cb37-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-245"><a href="#cb37-245" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>genuine mediation, the part of the gap that really does operate through sorting;</span>
<span id="cb37-246"><a href="#cb37-246" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>collider bias, from the gender--$U$ association induced by conditioning;</span>
<span id="cb37-247"><a href="#cb37-247" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>ordinary confounding of the occupation--wage relationship.</span>
<span id="cb37-248"><a href="#cb37-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-249"><a href="#cb37-249" aria-hidden="true" tabindex="-1"></a>The likely *direction* of (2) is worth spelling out. If women who enter male-dominated, high-paying occupations are positively selected on $U$ --- they had more to overcome to get there --- then within those occupations they are better on unobservables than the men they are being compared with, which pushes the within-occupation gap **toward zero**. Some of the attenuation from 11.3% to 7.5% may therefore be bias rather than mediation.</span>
<span id="cb37-250"><a href="#cb37-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-251"><a href="#cb37-251" aria-hidden="true" tabindex="-1"></a>The defensible way to report this: 11.3% is the total-effect estimate; 7.5% is a within-occupation descriptive contrast whose causal reading rests on an assumption we cannot verify. What we *can* do is ask how strong $U$ would have to be to account for the whole difference.</span>
<span id="cb37-252"><a href="#cb37-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-253"><a href="#cb37-253" aria-hidden="true" tabindex="-1"></a><span class="fu">#### How strong would $U$ have to be?</span></span>
<span id="cb37-254"><a href="#cb37-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-255"><a href="#cb37-255" aria-hidden="true" tabindex="-1"></a>The omitted-variable-bias machinery in <span class="in">`sensemakr`</span> (Cinelli and Hazlett, 2020) needs a single treatment coefficient, so for this exercise we drop the interactions and use additive specifications. That costs us the heterogeneity, but the attenuation we are interrogating survives the simplification almost exactly.</span>
<span id="cb37-256"><a href="#cb37-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-259"><a href="#cb37-259" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-260"><a href="#cb37-260" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: cde-sens</span></span>
<span id="cb37-261"><a href="#cb37-261" aria-hidden="true" tabindex="-1"></a><span class="co">#| cache: true</span></span>
<span id="cb37-262"><a href="#cb37-262" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb37-263"><a href="#cb37-263" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb37-264"><a href="#cb37-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-265"><a href="#cb37-265" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sensemakr)</span>
<span id="cb37-266"><a href="#cb37-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-267"><a href="#cb37-267" aria-hidden="true" tabindex="-1"></a>Xb <span class="ot">&lt;-</span> <span class="st">"exp1 + sohs + hsg + socl + clg + mw + sout + we"</span></span>
<span id="cb37-268"><a href="#cb37-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-269"><a href="#cb37-269" aria-hidden="true" tabindex="-1"></a>fit_total <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">as.formula</span>(<span class="fu">paste</span>(<span class="st">"lwage ~ female +"</span>, Xb)), <span class="at">data =</span> data)</span>
<span id="cb37-270"><a href="#cb37-270" aria-hidden="true" tabindex="-1"></a>fit_adj   <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">as.formula</span>(<span class="fu">paste</span>(<span class="st">"lwage ~ female +"</span>, Xb, <span class="st">"+ occ2 + ind2"</span>)), <span class="at">data =</span> data)</span>
<span id="cb37-271"><a href="#cb37-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-272"><a href="#cb37-272" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">total    =</span> <span class="fu">coef</span>(fit_total)[<span class="st">"female"</span>],</span>
<span id="cb37-273"><a href="#cb37-273" aria-hidden="true" tabindex="-1"></a>  <span class="at">adjusted =</span> <span class="fu">coef</span>(fit_adj)[<span class="st">"female"</span>],</span>
<span id="cb37-274"><a href="#cb37-274" aria-hidden="true" tabindex="-1"></a>  <span class="at">attenuation =</span> <span class="fu">coef</span>(fit_adj)[<span class="st">"female"</span>] <span class="sc">-</span> <span class="fu">coef</span>(fit_total)[<span class="st">"female"</span>])</span>
<span id="cb37-275"><a href="#cb37-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-276"><a href="#cb37-276" aria-hidden="true" tabindex="-1"></a>sens <span class="ot">&lt;-</span> <span class="fu">sensemakr</span>(<span class="at">model =</span> fit_adj, <span class="at">treatment =</span> <span class="st">"female"</span>,</span>
<span id="cb37-277"><a href="#cb37-277" aria-hidden="true" tabindex="-1"></a>                  <span class="at">benchmark_covariates =</span> <span class="fu">c</span>(<span class="st">"clg"</span>, <span class="st">"exp1"</span>),</span>
<span id="cb37-278"><a href="#cb37-278" aria-hidden="true" tabindex="-1"></a>                  <span class="at">kd =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>))</span>
<span id="cb37-279"><a href="#cb37-279" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sens)</span>
<span id="cb37-280"><a href="#cb37-280" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-281"><a href="#cb37-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-282"><a href="#cb37-282" aria-hidden="true" tabindex="-1"></a>The additive models put the total effect at $-11.4\%$ and the occupation-adjusted effect at $-7.3\%$, an attenuation of $4.1$ log points --- essentially the same gap as in the interacted specifications.</span>
<span id="cb37-283"><a href="#cb37-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-284"><a href="#cb37-284" aria-hidden="true" tabindex="-1"></a>Now invert the bias formula. Instead of asking how strong a confounder must be to drive the adjusted estimate to zero (the usual question), ask how strong it must be to move the adjusted estimate *back* to the total effect. That is the strength at which the entire apparent contribution of occupation is bias rather than mediation.</span>
<span id="cb37-285"><a href="#cb37-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-288"><a href="#cb37-288" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-289"><a href="#cb37-289" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: cde-invert</span></span>
<span id="cb37-290"><a href="#cb37-290" aria-hidden="true" tabindex="-1"></a><span class="co">#| cache: true</span></span>
<span id="cb37-291"><a href="#cb37-291" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb37-292"><a href="#cb37-292" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb37-293"><a href="#cb37-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-294"><a href="#cb37-294" aria-hidden="true" tabindex="-1"></a>target <span class="ot">&lt;-</span> <span class="fu">coef</span>(fit_total)[<span class="st">"female"</span>]</span>
<span id="cb37-295"><a href="#cb37-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-296"><a href="#cb37-296" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">r2dz =</span> <span class="fu">c</span>(<span class="fl">0.0125</span>, <span class="fl">0.02</span>, <span class="fl">0.033</span>, <span class="fl">0.06</span>),</span>
<span id="cb37-297"><a href="#cb37-297" aria-hidden="true" tabindex="-1"></a>                    <span class="at">r2yz =</span> <span class="fu">seq</span>(<span class="fl">0.001</span>, <span class="fl">0.60</span>, <span class="at">length.out =</span> <span class="dv">4000</span>))</span>
<span id="cb37-298"><a href="#cb37-298" aria-hidden="true" tabindex="-1"></a>grid<span class="sc">$</span>adj <span class="ot">&lt;-</span> <span class="fu">adjusted_estimate</span>(fit_adj, <span class="at">treatment =</span> <span class="st">"female"</span>,</span>
<span id="cb37-299"><a href="#cb37-299" aria-hidden="true" tabindex="-1"></a>                              <span class="at">r2dz.x =</span> grid<span class="sc">$</span>r2dz, <span class="at">r2yz.dx =</span> grid<span class="sc">$</span>r2yz,</span>
<span id="cb37-300"><a href="#cb37-300" aria-hidden="true" tabindex="-1"></a>                              <span class="at">reduce =</span> <span class="cn">FALSE</span>)</span>
<span id="cb37-301"><a href="#cb37-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-302"><a href="#cb37-302" aria-hidden="true" tabindex="-1"></a>grid <span class="sc">|&gt;</span></span>
<span id="cb37-303"><a href="#cb37-303" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(r2dz) <span class="sc">|&gt;</span></span>
<span id="cb37-304"><a href="#cb37-304" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_min</span>(<span class="fu">abs</span>(adj <span class="sc">-</span> target), <span class="at">n =</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb37-305"><a href="#cb37-305" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb37-306"><a href="#cb37-306" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(<span class="st">`</span><span class="at">partial R2 with gender</span><span class="st">`</span> <span class="ot">=</span> r2dz,</span>
<span id="cb37-307"><a href="#cb37-307" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">partial R2 with wage</span><span class="st">`</span>   <span class="ot">=</span> <span class="fu">round</span>(r2yz, <span class="dv">3</span>),</span>
<span id="cb37-308"><a href="#cb37-308" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">restored estimate</span><span class="st">`</span>      <span class="ot">=</span> <span class="fu">round</span>(adj, <span class="dv">4</span>))</span>
<span id="cb37-309"><a href="#cb37-309" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-310"><a href="#cb37-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-313"><a href="#cb37-313" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-314"><a href="#cb37-314" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: cde-contour</span></span>
<span id="cb37-315"><a href="#cb37-315" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Adjusted estimate of the gender gap as a function of a hypothetical confounder's partial $R^2$ with gender (horizontal) and with log wage (vertical), benchmarked against college and experience."</span></span>
<span id="cb37-316"><a href="#cb37-316" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 7</span></span>
<span id="cb37-317"><a href="#cb37-317" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb37-318"><a href="#cb37-318" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb37-319"><a href="#cb37-319" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb37-320"><a href="#cb37-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-321"><a href="#cb37-321" aria-hidden="true" tabindex="-1"></a><span class="co"># sensemakr is attached again here on purpose: the chunk above is cached, so on a</span></span>
<span id="cb37-322"><a href="#cb37-322" aria-hidden="true" tabindex="-1"></a><span class="co"># cache hit its library() call never runs and plot() would dispatch to</span></span>
<span id="cb37-323"><a href="#cb37-323" aria-hidden="true" tabindex="-1"></a><span class="co"># plot.default instead of the sensemakr method.</span></span>
<span id="cb37-324"><a href="#cb37-324" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sensemakr)</span>
<span id="cb37-325"><a href="#cb37-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-326"><a href="#cb37-326" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sens)</span>
<span id="cb37-327"><a href="#cb37-327" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-328"><a href="#cb37-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-329"><a href="#cb37-329" aria-hidden="true" tabindex="-1"></a>The answer is uncomfortable. A confounder explaining about **3% of the residual variance of gender and about 4% of the residual variance of wages** is enough to restore the full total effect --- that is, enough for occupation to be contributing no genuine mediation at all. For scale, <span class="in">`sensemakr`</span> reports a robustness value of $6.6\%$: a confounder explaining more than that share of both residual variances would drive the adjusted estimate to zero. So a $U$ roughly *half* as strong as the one needed to erase the within-occupation gap entirely is already strong enough to explain the whole $11.3\% \to 7.5\%$ attenuation.</span>
<span id="cb37-330"><a href="#cb37-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-331"><a href="#cb37-331" aria-hidden="true" tabindex="-1"></a>The benchmark rows give another angle. Experience explains $3.4\%$ of the residual variance of wages but only $0.16\%$ of the residual variance of gender, so along the outcome dimension the required $U$ is only a little stronger than experience. Along the gender dimension the required multiple looks large, but that is mostly because gender is close to orthogonal to experience in this sample; in absolute terms we are still only asking for a few percent of residual variance.</span>
<span id="cb37-332"><a href="#cb37-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-333"><a href="#cb37-333" aria-hidden="true" tabindex="-1"></a>None of this shows that occupational sorting explains nothing. It shows that this design cannot distinguish "sorting explains four points" from "conditioning on a collider costs four points," and that the confounder needed to tip the balance is unremarkable in size. Which is why the total effect, not the occupation-adjusted number, is the estimate to lead with.</span>
<span id="cb37-334"><a href="#cb37-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-335"><a href="#cb37-335" aria-hidden="true" tabindex="-1"></a>Now let's try nonparametric estimation.</span>
<span id="cb37-336"><a href="#cb37-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-337"><a href="#cb37-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-338"><a href="#cb37-338" aria-hidden="true" tabindex="-1"></a><span class="fu">### Nonparametric estimation</span></span>
<span id="cb37-339"><a href="#cb37-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-340"><a href="#cb37-340" aria-hidden="true" tabindex="-1"></a>If we'd like to go for nonparametric, relaxing linearity assumption, then we can use "npcausal". Note this may take a while, depending on which machine learning packages you decide to include. We can also use other nonparametric estimators, such as TMLE or doubleML.</span>
<span id="cb37-341"><a href="#cb37-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-344"><a href="#cb37-344" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-345"><a href="#cb37-345" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: npcausal1</span></span>
<span id="cb37-346"><a href="#cb37-346" aria-hidden="true" tabindex="-1"></a><span class="co">#| cache: true</span></span>
<span id="cb37-347"><a href="#cb37-347" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb37-348"><a href="#cb37-348" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb37-349"><a href="#cb37-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-350"><a href="#cb37-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-351"><a href="#cb37-351" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(npcausal)</span>
<span id="cb37-352"><a href="#cb37-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-353"><a href="#cb37-353" aria-hidden="true" tabindex="-1"></a><span class="co">#SL.library &lt;- c("SL.earth","SL.glmnet","SL.glm.interaction", "SL.mean","SL.ranger", "SL.xgboost")</span></span>
<span id="cb37-354"><a href="#cb37-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-355"><a href="#cb37-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-356"><a href="#cb37-356" aria-hidden="true" tabindex="-1"></a>SL.library <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"SL.earth"</span>,<span class="st">"SL.glmnet"</span>,<span class="st">"SL.mean"</span>,<span class="st">"SL.ranger"</span>, <span class="st">"SL.xgboost"</span>)</span>
<span id="cb37-357"><a href="#cb37-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-358"><a href="#cb37-358" aria-hidden="true" tabindex="-1"></a><span class="co"># construct W from model matrix of reg3</span></span>
<span id="cb37-359"><a href="#cb37-359" aria-hidden="true" tabindex="-1"></a>reg3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(lwage <span class="sc">~</span> exp_dm <span class="sc">+</span> sohs <span class="sc">+</span> hsg<span class="sc">+</span> socl <span class="sc">+</span> clg <span class="sc">+</span> mw <span class="sc">+</span> sout <span class="sc">+</span> we <span class="sc">+</span> occ2 <span class="sc">+</span> ind2, <span class="at">data=</span>data)</span>
<span id="cb37-360"><a href="#cb37-360" aria-hidden="true" tabindex="-1"></a>W <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">model.matrix</span>(reg3)[, <span class="sc">-</span><span class="dv">1</span>]) <span class="co"># remove intercept</span></span>
<span id="cb37-361"><a href="#cb37-361" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-362"><a href="#cb37-362" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> data<span class="sc">$</span>lwage</span>
<span id="cb37-363"><a href="#cb37-363" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> data<span class="sc">$</span>female</span>
<span id="cb37-364"><a href="#cb37-364" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb37-365"><a href="#cb37-365" aria-hidden="true" tabindex="-1"></a>aipw_ate <span class="ot">&lt;-</span> <span class="fu">ate</span>(<span class="at">y=</span>Y, <span class="at">a=</span>A, <span class="at">x=</span>W, <span class="at">nsplits=</span><span class="dv">5</span>, <span class="at">sl.lib=</span>SL.library)</span>
<span id="cb37-366"><a href="#cb37-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-367"><a href="#cb37-367" aria-hidden="true" tabindex="-1"></a>aipw_att <span class="ot">&lt;-</span> <span class="fu">att</span>(<span class="at">y=</span>Y, <span class="at">a=</span>A, <span class="at">x=</span>W, <span class="at">nsplits=</span><span class="dv">5</span>, <span class="at">sl.lib=</span>SL.library)</span>
<span id="cb37-368"><a href="#cb37-368" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-369"><a href="#cb37-369" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-370"><a href="#cb37-370" aria-hidden="true" tabindex="-1"></a>The two fits above print only SuperLearner's progress bars, so the estimates</span>
<span id="cb37-371"><a href="#cb37-371" aria-hidden="true" tabindex="-1"></a>themselves have to be asked for:</span>
<span id="cb37-372"><a href="#cb37-372" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-375"><a href="#cb37-375" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-376"><a href="#cb37-376" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: npcausal-results</span></span>
<span id="cb37-377"><a href="#cb37-377" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb37-378"><a href="#cb37-378" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb37-379"><a href="#cb37-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-380"><a href="#cb37-380" aria-hidden="true" tabindex="-1"></a>aipw_ate<span class="sc">$</span>res</span>
<span id="cb37-381"><a href="#cb37-381" aria-hidden="true" tabindex="-1"></a>aipw_att<span class="sc">$</span>res</span>
<span id="cb37-382"><a href="#cb37-382" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-383"><a href="#cb37-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-384"><a href="#cb37-384" aria-hidden="true" tabindex="-1"></a>Two estimates come out of this: an AIPW **ATE** of $-5.8\%$ (95% CI $-8.9\%$ to</span>
<span id="cb37-385"><a href="#cb37-385" aria-hidden="true" tabindex="-1"></a>$-2.7\%$) and an AIPW **ATT** of $-6.7\%$ (95% CI $-9.5\%$ to $-3.9\%$).</span>
<span id="cb37-386"><a href="#cb37-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-387"><a href="#cb37-387" aria-hidden="true" tabindex="-1"></a>The comparison worth making is like with like. The $-7.5\%$ from the fully</span>
<span id="cb37-388"><a href="#cb37-388" aria-hidden="true" tabindex="-1"></a>interacted linear model above was an ATT (it was computed on</span>
<span id="cb37-389"><a href="#cb37-389" aria-hidden="true" tabindex="-1"></a><span class="in">`newdata = subset(data, female == 1)`</span>), so it should be set against the</span>
<span id="cb37-390"><a href="#cb37-390" aria-hidden="true" tabindex="-1"></a>nonparametric **ATT** of $-6.7\%$, not against the ATE. Those two agree closely,</span>
<span id="cb37-391"><a href="#cb37-391" aria-hidden="true" tabindex="-1"></a>which is reassuring: dropping the linearity assumption altogether moves the</span>
<span id="cb37-392"><a href="#cb37-392" aria-hidden="true" tabindex="-1"></a>estimate by less than a percentage point, and both use the same covariate set</span>
<span id="cb37-393"><a href="#cb37-393" aria-hidden="true" tabindex="-1"></a>including occupation and industry.</span>
<span id="cb37-394"><a href="#cb37-394" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-395"><a href="#cb37-395" aria-hidden="true" tabindex="-1"></a>That last clause is also the caveat. Because both specifications condition on</span>
<span id="cb37-396"><a href="#cb37-396" aria-hidden="true" tabindex="-1"></a>occupation and industry, both inherit the bad-control problem set out above: the</span>
<span id="cb37-397"><a href="#cb37-397" aria-hidden="true" tabindex="-1"></a>agreement between $-7.5\%$ and $-6.7\%$ tells us the two estimators recover the</span>
<span id="cb37-398"><a href="#cb37-398" aria-hidden="true" tabindex="-1"></a>same quantity, not that the quantity is a causal effect. Relaxing linearity</span>
<span id="cb37-399"><a href="#cb37-399" aria-hidden="true" tabindex="-1"></a>addresses functional form; it leaves the collider untouched.</span>
<span id="cb37-400"><a href="#cb37-400" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-401"><a href="#cb37-401" aria-hidden="true" tabindex="-1"></a>The ATE and ATT point estimates do differ a little, in the direction of a larger</span>
<span id="cb37-402"><a href="#cb37-402" aria-hidden="true" tabindex="-1"></a>gap among women than in the sample as a whole — which would indicate effect</span>
<span id="cb37-403"><a href="#cb37-403" aria-hidden="true" tabindex="-1"></a>heterogeneity across the covariates. Their confidence intervals overlap heavily,</span>
<span id="cb37-404"><a href="#cb37-404" aria-hidden="true" tabindex="-1"></a>though, so this data cannot really distinguish them.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->



<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/xiangao/blog_book/edit/main/gwg.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/xiangao/blog_book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>