<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="dcterms.date" content="2024-08-29">
<title>26&nbsp; IV in fixed-effect Poisson with many fixed effects: worked examples – Topics on econometrics and causal inference</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./tmle.html" rel="next">
<link href="./poisson-exposure.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6eb2a311e0ae5a9b436ea9f7e52955e6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script>
try {
  if (window.localStorage) {
    window.localStorage.setItem("quarto-reader-mode", "false");
  }
} catch (e) {}
</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="style.css">
</head>
<body class="nav-sidebar floating fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./count-data.html">Count Data &amp; Specialized Models</a></li><li class="breadcrumb-item"><a href="./poisson-iv-fe.html"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">IV in fixed-effect Poisson with many fixed effects: worked examples</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Topics on econometrics and causal inference</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://xiangao.github.io/" title="Xiang Ao home" class="quarto-navigation-tool px-1" aria-label="Xiang Ao home"><i class="bi bi-house-door-fill"></i></a>
    <a href="https://xiangao.github.io/books.html" title="Other books" class="quarto-navigation-tool px-1" aria-label="Other books"><i class="bi bi-book"></i></a>
    <a href="https://github.com/xiangao/blog_book/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Regression Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./interaction-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Interpreting interaction in a regression model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./interaction-nonlinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Interaction term in a non-linear model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chow-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Chow test and more</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./weights-ols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Weights in OLS in causal inference</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Marginal Effects &amp; Fixed Effects</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./marginal-effects-fe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Marginal effects in models with fixed effects</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./comparing-margins.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Comparing Marginal effects with margins command</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fixed-random-effect.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Fixed or Random Effect, or Both?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mundlak-device.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Mundlak device in fixed effect models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlated-random-effect.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Correlated Random Effect</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./more-cre.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">More on Correlated Random Effect (CRE)</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Treatment Effects &amp; Matching</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./treatment-matching.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Treatment effects and matching</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ols-ate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">When is OLS coefficient the ATE</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./matching-part1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Matching and Weighting Part 1: matching</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./weighting-part2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Matching and Weighting - Part 2: weighting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sensitivity-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Sensitivity analysis of OLS with sensemakr</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./gwg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Gender Wage Gap Analysis Using US Current Population Survey Data</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Panel Data &amp; DiD</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal-forest-panel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Causal Forest in panel data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./synthetic-control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Synthetic Control in R and Stata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tasc-time-aware-synthetic-control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Same Data, Different Estimators: A Synthetic Control Comparison</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bartik-instrument.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Bartik Instrument and Rotemberg weights</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./extended-twfe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Extended TWFE and other DiD estimators</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal-panel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Causal Panel (why DDDiD)</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Count Data &amp; Specialized Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Which count data model to use</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rare-events.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">What model to use for rare events</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./poisson-exposure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Poisson model with exposure</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./poisson-iv-fe.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">IV in fixed-effect Poisson with many fixed effects: worked examples</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Causal Inference Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tmle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Using machine learning for causal effect in observational study</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mediation-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Mediation analysis in R and Stata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bunching.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Endogeneity with censored variable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./g-estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">G-computation (g-formula) with time varying covariates</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./policytree.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Policy learning by policytree</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./npcausal-tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Recent causal inference tools</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./proximal-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Intro to proximal causal inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./proximal-simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Simulation on proximal causal inference with panel data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lmtp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">longitudinal modified treatment policy (LMTP)</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Advanced Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multilevel-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Doing the same multi-level model with R and stata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./likert-scale-variance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Modeling variation, not just the mean, in Likert-scale data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conjoint-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Conjoint design and analysis using R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stata-cate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Stata 19 CATE command</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./spatial-econometrics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Spatial econometrics introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal-simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Causal simulation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./frengression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Frengression and Engression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./partial-interference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Partial Interference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./power-list-experiment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Power analysis with list experiment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal-mediation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Causal mediation analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uplift.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Uplift Modeling and CATE</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./numpyro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Using Numpyro</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./equivalence-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Pre-registration, TOST, and why Bayes doesn’t let you skip the hard part</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./count-data.html">Count Data &amp; Specialized Models</a></li><li class="breadcrumb-item"><a href="./poisson-iv-fe.html"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">IV in fixed-effect Poisson with many fixed effects: worked examples</span></a></li></ol></nav><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">
<span class="chapter-number">26</span>&nbsp; <span class="chapter-title">IV in fixed-effect Poisson with many fixed effects: worked examples</span>
</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 29, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header><p>This is the applied companion to the <a href="https://xiangao.github.io/causal_econometrics_guide/poisson-iv.html">Poisson IV chapter</a> of the <em>Causal Econometrics Guide</em>. Everything here is code and output: which commands to type, what the estimates look like on real and simulated data, and the places the mechanics bite. The derivations behind it — why the control function is not 2SLS once the mean is exponential, why a linear first stage stops being valid for a discrete endogenous variable, Terza’s exact correction and the Taylor expansion that makes the generalized residual its first-order approximation — are in the guide chapter, and are not repeated below. A Julia version of the same material is <a href="https://xiangao.github.io/causal_econometrics_julia/poisson-iv.html">here</a>.</p>
<section id="which-commands" class="level2" data-number="26.1"><h2 data-number="26.1" class="anchored" data-anchor-id="which-commands">
<span class="header-section-number">26.1</span> Which commands</h2>
<p>Stata’s <code>xtpoisson, fe</code> fits fixed-effect Poisson, but <code>ppmlhdfe</code> is the better choice: it absorbs several dimensions of fixed effects at once, it is faster, and it reports predicted values with the fixed effects put back in. That last point is the one that catches people — after <code>xtpoisson, fe</code> or <code>xtreg, fe</code> the effects are absorbed rather than estimated, so predicted values come back without them. The same author’s <code>reghdfe</code> replaces <code>areg</code> and <code>xtreg, fe</code> for the linear first stage, with the same advantages.</p>
<p><code>ivpoisson</code> handles endogenous regressors in a Poisson model but has no option for fixed effects, which is why the route below is a two-step control function rather than a packaged IV command.</p>
<p>In R, <code><a href="https://lrberge.github.io/fixest/reference/feglm.html">fixest::fepois()</a></code> and <code><a href="https://lrberge.github.io/fixest/reference/feols.html">fixest::feols()</a></code> do the same jobs.</p>
</section><section id="the-recipe" class="level2" data-number="26.2"><h2 data-number="26.2" class="anchored" data-anchor-id="the-recipe">
<span class="header-section-number">26.2</span> The recipe</h2>
<p>For a continuous endogenous variable this is Procedure 3 of Lin and Wooldridge (2019):</p>
<ol type="1">
<li><p>Run the reduced form for the endogenous variable and keep the residual. All fixed effects that appear in the second stage go into this regression too. In Stata, <code>reghdfe ..., resid</code>.</p></li>
<li><p>Put the endogenous variable and that residual into the second-stage Poisson, absorbing the same fixed effects. In Stata, <code>ppmlhdfe</code>.</p></li>
<li><p>Bootstrap. The second-stage standard errors are wrong as reported, because the residual is generated. Lin and Wooldridge (2019, p.&nbsp;30) recommend a panel bootstrap that redoes both steps within each replication. With clustered errors, resample the clusters.</p></li>
</ol>
<p>The <span class="math inline">\(t\)</span>-statistic on the residual is a test of endogeneity. It is not a model-selection device: do not run it and then drop the residual if it comes back insignificant. Guggenberger (2010) shows that this two-stage procedure has asymptotic size one. Report both columns. The reasoning is in the <a href="https://xiangao.github.io/causal_econometrics_guide/poisson-iv.html">guide chapter</a>.</p>
<section id="a-terminology-note" class="level3" data-number="26.2.1"><h3 data-number="26.2.1" class="anchored" data-anchor-id="a-terminology-note">
<span class="header-section-number">26.2.1</span> A terminology note</h3>
<p>Three things carry similar names and are easy to conflate.</p>
<p>The <strong>Mundlak device</strong> means adding group <em>means</em> of covariates as regressors — see the <a href="./mundlak-device.html">Mundlak chapter</a>. The <strong>control-function residual</strong> is the residual from a reduced form. Those are different constructions. But Lin and Wooldridge (2019) call the residual from a reduced form <em>that itself includes the Mundlak means</em> — from regressing <span class="math inline">\(y_{it2}\)</span> on <span class="math inline">\(z_{it}\)</span> and <span class="math inline">\(\bar z_i\)</span> — the <strong>Mundlak residual</strong>, as against the <strong>FE residual</strong> from within-transforming. So in that paper “Mundlak residual” denotes a control-function residual, not the device.</p>
<p>Which of those two residuals you use does not matter: they give numerically identical estimates of the structural coefficient and of the coefficient on the control function (Lin and Wooldridge 2019, appendices A.1 and A.2), because they differ only by a term that is constant within unit and the second-stage fixed effects absorb it.</p>
<p>That result has a practical consequence, and it is the reason it is worth knowing. The first stage does not need thousands of unit dummies; the unit means will do, at no cost in the estimate. That is what makes a <strong>nonlinear</strong> first stage practical — you cannot put 2,000 dummies into a logit without an incidental-parameters problem, but you can put in 2,000 unit means. The result as stated is for a <em>linear</em> reduced form.</p>
</section></section><section id="continuous-endogenous-variable-the-website-data" class="level2" data-number="26.3"><h2 data-number="26.3" class="anchored" data-anchor-id="continuous-endogenous-variable-the-website-data">
<span class="header-section-number">26.3</span> Continuous endogenous variable: the <code>website</code> data</h2>
<p>Stata’s <code>website.dta</code> has 500 observations. <code>visits</code> is the count outcome, <code>time</code> (minutes on the site) is the endogenous regressor, <code>phone</code> (support calls) is the excluded instrument, and <code>frfam</code> (referrals from friends and family) is an exogenous control. <code>ad</code> and <code>female</code> are the two fixed-effect dimensions.</p>
<div class="cell" data-collectcode="true">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">webuse</span> website, <span class="kw">clear</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>* step 1: linear first stage, absorbing both sets <span class="kw">of</span> fixed <span class="kw">effects</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>reghdfe time phone frfam, absorb(ad female) <span class="kw">resid</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="kw">predict</span> <span class="kw">double</span> u2h_fe, <span class="kw">resid</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>* step 2: FE Poisson with the control-<span class="kw">function</span> residual added</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>ppmlhdfe visits time u2h_fe frfam, absorb(ad female)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>(Visits to website)

(dropped 1 singleton observations)
(MWFE estimator converged in 3 iterations)

HDFE Linear regression                            Number of obs   =        499
Absorbing 2 HDFE groups                           F(   2,    484) =      29.02
                                                  Prob &gt; F        =     0.0000
                                                  R-squared       =     0.3137
                                                  Adj R-squared   =     0.2938
                                                  Within R-sq.    =     0.1071
                                                  Root MSE        =     2.2239

------------------------------------------------------------------------------
        time | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
       phone |   .2705429   .0626834     4.32   0.000     .1473778     .393708
       frfam |   .2539231   .0619373     4.10   0.000     .1322239    .3756222
       _cons |   1.406026   .2549245     5.52   0.000     .9051305    1.906921
------------------------------------------------------------------------------

Absorbed degrees of freedom:
-----------------------------------------------------+
 Absorbed FE | Categories  - Redundant  = Num. Coefs |
-------------+---------------------------------------|
          ad |        12           0          12     |
      female |         2           1           1     |
-----------------------------------------------------+

(1 missing value generated)

Iteration 1:   deviance = 3.7303e+02  eps = .         iters = 3    tol = 1.0e-0
&gt; 4                                                                            
&gt;    min(eta) =  -0.57  P   
Iteration 2:   deviance = 3.5849e+02  eps = 4.06e-02  iters = 3    tol = 1.0e-0
&gt; 4                                                                            
&gt;    min(eta) =  -0.59      
Iteration 3:   deviance = 3.5840e+02  eps = 2.46e-04  iters = 3    tol = 1.0e-0
&gt; 4                                                                            
&gt;    min(eta) =  -0.60      
Iteration 4:   deviance = 3.5840e+02  eps = 3.17e-08  iters = 2    tol = 1.0e-0
&gt; 4                                                                            
&gt;    min(eta) =  -0.60      
Iteration 5:   deviance = 3.5840e+02  eps = 9.72e-16  iters = 2    tol = 1.0e-0
&gt; 5                                                                            
&gt;    min(eta) =  -0.60   S  
Iteration 6:   deviance = 3.5840e+02  eps = 1.62e-16  iters = 1    tol = 1.0e-0
&gt; 9                                                                            
&gt;    min(eta) =  -0.60   S O
-------------------------------------------------------------------------------
&gt; -----------------------------
(legend: p: exact partial-out   s: exact solver   h: step-halving   o: epsilon 
&gt; below tolerance)
Converged in 6 iterations and 14 HDFE sub-iterations (tol = 1.0e-08)

HDFE PPML regression                              No. of obs      =        499
Absorbing 2 HDFE groups                           Residual df     =        483
                                                  Wald chi2(3)    =     169.93
Deviance             =  358.4027719               Prob &gt; chi2     =     0.0000
Log pseudolikelihood = -993.8547331               Pseudo R2       =     0.2976
------------------------------------------------------------------------------
             |               Robust
      visits | Coefficient  std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
        time |   .0448103   .0448665     1.00   0.318    -.0431265    .1327471
      u2h_fe |   .0765144   .0459404     1.67   0.096    -.0135272     .166556
       frfam |   .0004108   .0205161     0.02   0.984       -.0398    .0406215
       _cons |   1.510566   .1033122    14.62   0.000     1.308078    1.713054
------------------------------------------------------------------------------

Absorbed degrees of freedom:
-----------------------------------------------------+
 Absorbed FE | Categories  - Redundant  = Num. Coefs |
-------------+---------------------------------------|
          ad |        12           0          12     |
      female |         2           1           1     |
-----------------------------------------------------+</code></pre>
</div>
</div>
<p><code>time</code> comes out at 0.0448 with <span class="math inline">\(p = 0.318\)</span>. The residual <code>u2h_fe</code> gets 0.0765 with <span class="math inline">\(p = 0.096\)</span>, so what endogeneity the data can detect is positive and weakly signalled. Both standard errors are wrong; see the bootstrap section below.</p>
<section id="checking-the-mechanics-against-a-linear-model" class="level3" data-number="26.3.1"><h3 data-number="26.3.1" class="anchored" data-anchor-id="checking-the-mechanics-against-a-linear-model">
<span class="header-section-number">26.3.1</span> Checking the mechanics against a linear model</h3>
<p>The control function is exactly 2SLS in a linear model, so running the linear version both ways is a check that the two steps are wired up correctly. It is a check on the code, not evidence that the Poisson version is valid — that rests on assumptions the linear case does not need.</p>
<div class="cell" data-collectcode="true">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">clear</span> <span class="ot">all</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="kw">webuse</span> website, <span class="kw">clear</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>* 1. linear 2SLS</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>ivreghdfe visits frfam (time=phone), absorb(ad female)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>* 2. the same thing <span class="kw">as</span> a manual <span class="kw">two</span>-step control <span class="kw">function</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>reghdfe time phone frfam, absorb(ad female) <span class="kw">resid</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="kw">predict</span> <span class="kw">double</span> u2h_fe, <span class="kw">resid</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>reghdfe visits time u2h_fe frfam, absorb(ad female)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>* 3. naive models, ignoring the endogeneity</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>reghdfe visits time frfam, absorb(ad female)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>ppmlhdfe visits time frfam, absorb(ad female)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>(Visits to website)

(dropped 1 singleton observations)
(MWFE estimator converged in 3 iterations)

IV (2SLS) estimation
--------------------

Estimates efficient for homoskedasticity only
Statistics consistent for homoskedasticity only

                                                      Number of obs =      499
                                                      F(  2,   484) =     8.31
                                                      Prob &gt; F      =   0.0003
Total (centered) SS     =  3335.918099                Centered R2   =   0.3971
Total (uncentered) SS   =  3335.918099                Uncentered R2 =   0.3971
Residual SS             =  2011.119506                Root MSE      =    2.038

------------------------------------------------------------------------------
      visits | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
        time |   .5642802   .2123745     2.66   0.008     .1469904      .98157
       frfam |    -.04045   .0922873    -0.44   0.661    -.2217832    .1408833
------------------------------------------------------------------------------
Underidentification test (Anderson canon. corr. LM statistic):          18.494
                                                   Chi-sq(1) P-val =    0.0000
------------------------------------------------------------------------------
Weak identification test (Cragg-Donald Wald F statistic):               18.628
Stock-Yogo weak ID test critical values: 10% maximal IV size             16.38
                                         15% maximal IV size              8.96
                                         20% maximal IV size              6.66
                                         25% maximal IV size              5.53
Source: Stock-Yogo (2005).  Reproduced by permission.
------------------------------------------------------------------------------
Sargan statistic (overidentification test of all instruments):           0.000
                                                 (equation exactly identified)
------------------------------------------------------------------------------
Instrumented:         time
Included instruments: frfam
Excluded instruments: phone
Partialled-out:       _cons
                      nb: total SS, model F and R2s are after partialling-out;
                          any small-sample adjustments include partialled-out
                          variables in regressor count K
------------------------------------------------------------------------------

Absorbed degrees of freedom:
-----------------------------------------------------+
 Absorbed FE | Categories  - Redundant  = Num. Coefs |
-------------+---------------------------------------|
          ad |        12           0          12     |
      female |         2           1           1     |
-----------------------------------------------------+

(dropped 1 singleton observations)
(MWFE estimator converged in 3 iterations)

HDFE Linear regression                            Number of obs   =        499
Absorbing 2 HDFE groups                           F(   2,    484) =      29.02
                                                  Prob &gt; F        =     0.0000
                                                  R-squared       =     0.3137
                                                  Adj R-squared   =     0.2938
                                                  Within R-sq.    =     0.1071
                                                  Root MSE        =     2.2239

------------------------------------------------------------------------------
        time | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
       phone |   .2705429   .0626834     4.32   0.000     .1473778     .393708
       frfam |   .2539231   .0619373     4.10   0.000     .1322239    .3756222
       _cons |   1.406026   .2549245     5.52   0.000     .9051305    1.906921
------------------------------------------------------------------------------

Absorbed degrees of freedom:
-----------------------------------------------------+
 Absorbed FE | Categories  - Redundant  = Num. Coefs |
-------------+---------------------------------------|
          ad |        12           0          12     |
      female |         2           1           1     |
-----------------------------------------------------+

(1 missing value generated)

(MWFE estimator converged in 3 iterations)

HDFE Linear regression                            Number of obs   =        499
Absorbing 2 HDFE groups                           F(   3,    483) =     117.11
                                                  Prob &gt; F        =     0.0000
                                                  R-squared       =     0.7677
                                                  Adj R-squared   =     0.7605
                                                  Within R-sq.    =     0.4211
                                                  Root MSE        =     1.9996

------------------------------------------------------------------------------
      visits | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
        time |   .5642802   .2083276     2.71   0.007       .15494    .9736205
      u2h_fe |   .1827169   .2122987     0.86   0.390    -.2344262    .5998601
       frfam |    -.04045   .0905287    -0.45   0.655    -.2183288    .1374288
       _cons |   3.357879   .4427337     7.58   0.000     2.487957    4.227801
------------------------------------------------------------------------------

Absorbed degrees of freedom:
-----------------------------------------------------+
 Absorbed FE | Categories  - Redundant  = Num. Coefs |
-------------+---------------------------------------|
          ad |        12           0          12     |
      female |         2           1           1     |
-----------------------------------------------------+

(dropped 1 singleton observations)
(MWFE estimator converged in 3 iterations)

HDFE Linear regression                            Number of obs   =        499
Absorbing 2 HDFE groups                           F(   2,    484) =     175.38
                                                  Prob &gt; F        =     0.0000
                                                  R-squared       =     0.7673
                                                  Adj R-squared   =     0.7606
                                                  Within R-sq.    =     0.4202
                                                  Root MSE        =     1.9991

------------------------------------------------------------------------------
      visits | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
        time |   .7402254   .0400951    18.46   0.000     .6614435    .8190073
       frfam |  -.1034523    .053248    -1.94   0.053     -.208078    .0011735
       _cons |   3.027348   .2202211    13.75   0.000     2.594641    3.460055
------------------------------------------------------------------------------

Absorbed degrees of freedom:
-----------------------------------------------------+
 Absorbed FE | Categories  - Redundant  = Num. Coefs |
-------------+---------------------------------------|
          ad |        12           0          12     |
      female |         2           1           1     |
-----------------------------------------------------+

(dropped 1 observations that are either singletons or separated by a fixed effe
&gt; ct)
Iteration 1:   deviance = 3.7573e+02  eps = .         iters = 3    tol = 1.0e-0
&gt; 4                                                                            
&gt;    min(eta) =  -0.64  P   
Iteration 2:   deviance = 3.6107e+02  eps = 4.06e-02  iters = 3    tol = 1.0e-0
&gt; 4                                                                            
&gt;    min(eta) =  -0.64      
Iteration 3:   deviance = 3.6098e+02  eps = 2.57e-04  iters = 3    tol = 1.0e-0
&gt; 4                                                                            
&gt;    min(eta) =  -0.64      
Iteration 4:   deviance = 3.6098e+02  eps = 3.76e-08  iters = 2    tol = 1.0e-0
&gt; 4                                                                            
&gt;    min(eta) =  -0.64      
Iteration 5:   deviance = 3.6098e+02  eps = 1.45e-15  iters = 2    tol = 1.0e-0
&gt; 5                                                                            
&gt;    min(eta) =  -0.64   S  
Iteration 6:   deviance = 3.6098e+02  eps = 0.00e+00  iters = 1    tol = 1.0e-0
&gt; 9                                                                            
&gt;    min(eta) =  -0.64   S O
-------------------------------------------------------------------------------
&gt; -----------------------------
(legend: p: exact partial-out   s: exact solver   h: step-halving   o: epsilon 
&gt; below tolerance)
Converged in 6 iterations and 14 HDFE sub-iterations (tol = 1.0e-08)

HDFE PPML regression                              No. of obs      =        499
Absorbing 2 HDFE groups                           Residual df     =        484
                                                  Wald chi2(2)    =     164.67
Deviance             =  360.9797175               Prob &gt; chi2     =     0.0000
Log pseudolikelihood = -995.1432059               Pseudo R2       =     0.2967
------------------------------------------------------------------------------
             |               Robust
      visits | Coefficient  std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
        time |   .1187612   .0095895    12.38   0.000     .0999662    .1375563
       frfam |  -.0281572   .0099614    -2.83   0.005    -.0476812   -.0086332
       _cons |   1.345121   .0497098    27.06   0.000     1.247692    1.442551
------------------------------------------------------------------------------

Absorbed degrees of freedom:
-----------------------------------------------------+
 Absorbed FE | Categories  - Redundant  = Num. Coefs |
-------------+---------------------------------------|
          ad |        12           0          12     |
      female |         2           1           1     |
-----------------------------------------------------+</code></pre>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: left;">Command</th>
<th style="text-align: center;">Coefficient on <code>time</code>
</th>
<th style="text-align: center;">Std. err.</th>
<th style="text-align: center;"><span class="math inline">\(p\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Naive linear FE</td>
<td style="text-align: left;"><code>reghdfe</code></td>
<td style="text-align: center;">0.7402</td>
<td style="text-align: center;">0.0401</td>
<td style="text-align: center;"><span class="math inline">\(&lt;0.001\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Linear 2SLS</td>
<td style="text-align: left;"><code>ivreghdfe</code></td>
<td style="text-align: center;">0.5643</td>
<td style="text-align: center;">0.2124</td>
<td style="text-align: center;">0.008</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Linear control function</td>
<td style="text-align: left;">two-step <code>reghdfe</code>
</td>
<td style="text-align: center;">0.5643</td>
<td style="text-align: center;">0.2083</td>
<td style="text-align: center;">0.007</td>
</tr>
<tr class="even">
<td style="text-align: left;">Naive FE Poisson</td>
<td style="text-align: left;">
<code>ppmlhdfe</code>, no residual</td>
<td style="text-align: center;">0.1188</td>
<td style="text-align: center;">0.0096</td>
<td style="text-align: center;"><span class="math inline">\(&lt;0.001\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Control-function FE Poisson</td>
<td style="text-align: left;">
<code>ppmlhdfe</code>, with <code>u2h_fe</code>
</td>
<td style="text-align: center;">0.0448</td>
<td style="text-align: center;">0.0449</td>
<td style="text-align: center;">0.318</td>
</tr>
</tbody>
</table>
<p>The two linear rows agree on the coefficient to seven digits, which is the check working. Their standard errors do not agree, and that is the generated-regressor problem in miniature: <code>ivreghdfe</code> accounts for the first stage, the manual two-step does not, and the gap here happens to be small only because the design is favourable.</p>
<p>In the Poisson rows the naive estimate is 0.1188 and the control-function estimate is 0.0448. The correction is large and in the direction the sign of <code>u2h_fe</code> predicts.</p>
</section></section><section id="bootstrapping-the-standard-errors" class="level2" data-number="26.4"><h2 data-number="26.4" class="anchored" data-anchor-id="bootstrapping-the-standard-errors">
<span class="header-section-number">26.4</span> Bootstrapping the standard errors</h2>
<p>Suppose we want errors clustered on <code>ad</code>.</p>
<div class="cell" data-collectcode="true">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>* Note <span class="kw">on</span> idcluster(newid): it gives each resampled COPY <span class="kw">of</span> a <span class="kw">cluster</span> its own</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>* <span class="kw">unique</span> id.  A <span class="kw">cluster</span> can <span class="kw">be</span> drawn <span class="kw">more</span> than once within a replication, and</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>* the <span class="kw">duplicates</span> must <span class="kw">be</span> treated <span class="kw">as</span> distinct groups.  The regressions inside</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>* the <span class="kw">program</span> must therefore absorb <span class="st">"newid"</span>, <span class="kw">not</span> the original <span class="st">"ad"</span> --- absorbing</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>* <span class="st">"ad"</span> would pool the <span class="kw">duplicates</span> back into a single fixed effect, which breaks</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>* the <span class="kw">cluster</span>-<span class="kw">bootstrap</span> logic.  Verified empirically: within a replication the</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>* number <span class="kw">of</span> distinct <span class="st">"ad"</span> <span class="kw">values</span> is consistently below the true <span class="kw">cluster</span> <span class="fu">count</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>* <span class="kw">while</span> <span class="st">"newid"</span> always has exactly that many.</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="kw">clear</span> <span class="ot">all</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="kw">capture</span> <span class="kw">program</span> <span class="kw">drop</span> ppmlhdfe_cf</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="kw">program</span> ppmlhdfe_cf, rclass</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  reghdfe time phone frfam, absorb(newid female) <span class="kw">resid</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="kw">predict</span> <span class="kw">double</span> u2h_fe, <span class="kw">resid</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>  ppmlhdfe visits time u2h_fe frfam, absorb(newid female)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span> <span class="fu">scalar</span> b_time = _b[time]</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span> <span class="fu">scalar</span> b_u2h  = _b[u2h_fe]</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>  <span class="kw">drop</span> u2h_fe</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>  xtset, <span class="kw">clear</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a><span class="kw">webuse</span> website, <span class="kw">clear</span></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>xtset, <span class="kw">clear</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a><span class="kw">bootstrap</span> <span class="fu">r</span>(b_time) <span class="fu">r</span>(b_u2h), reps(1000) <span class="dv">seed</span>(123) <span class="kw">cluster</span>(ad) idcluster(newid) <span class="kw">nodots</span>: ppmlhdfe_cf</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>(Visits to website)



Bootstrap results                                        Number of obs =   499
                                                         Replications  = 1,000

      Command: ppmlhdfe_cf
        _bs_1: r(b_time)
        _bs_2: r(b_u2h)

                                     (Replications based on 12 clusters in ad)
------------------------------------------------------------------------------
             |   Observed   Bootstrap                         Normal-based
             | coefficient  std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
       _bs_1 |   .0448103   .0477457     0.94   0.348    -.0487697    .1383902
       _bs_2 |   .0765144   .0486568     1.57   0.116    -.0188511    .1718799
------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>The bootstrap standard error on <code>time</code> comes out at 0.0477 against the 0.0449 reported analytically. Before reading anything into that six per cent, see the comparison with the R bootstrap below — the two do not agree, and the reason matters more than either number.</p>
<p>A troubleshooting note: <code>xtset, clear</code> is needed before each regression inside the bootstrap. Stata’s cluster bootstrap creates a new id variable for the resampled clusters and leaves the panel <code>xtset</code> to it; if that is not cleared, a later regression can pick up the stale panel setting even when it does not use the id.</p>
</section><section id="the-same-thing-in-r" class="level2" data-number="26.5"><h2 data-number="26.5" class="anchored" data-anchor-id="the-same-thing-in-r">
<span class="header-section-number">26.5</span> The same thing in R</h2>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://lrberge.github.io/fixest/">fixest</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://haven.tidyverse.org">haven</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://haven.tidyverse.org/reference/read_dta.html">read_dta</a></span><span class="op">(</span><span class="st">"https://www.stata-press.com/data/r18/website.dta"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">df</span><span class="op">$</span><span class="va">ad</span>     <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">df</span><span class="op">$</span><span class="va">ad</span><span class="op">)</span></span>
<span><span class="va">df</span><span class="op">$</span><span class="va">female</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">df</span><span class="op">$</span><span class="va">female</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># step 1: linear first stage, absorbing both sets of fixed effects</span></span>
<span><span class="va">fs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://lrberge.github.io/fixest/reference/feols.html">feols</a></span><span class="op">(</span><span class="va">time</span> <span class="op">~</span> <span class="va">phone</span> <span class="op">+</span> <span class="va">frfam</span> <span class="op">|</span> <span class="va">ad</span> <span class="op">+</span> <span class="va">female</span>, data <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># feols drops a singleton (ad == 10 has one observation), exactly as reghdfe</span></span>
<span><span class="co"># does, so the residual is shorter than the data.  obs() gives the rows that</span></span>
<span><span class="co"># were kept; align on those rather than assuming the lengths match.</span></span>
<span><span class="va">d</span> <span class="op">&lt;-</span> <span class="va">df</span><span class="op">[</span><span class="fu"><a href="https://lrberge.github.io/fixest/reference/obs.html">obs</a></span><span class="op">(</span><span class="va">fs</span><span class="op">)</span>, <span class="op">]</span></span>
<span><span class="va">d</span><span class="op">$</span><span class="va">u2h_fe</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">fs</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># step 2: FE Poisson, without and with the control function</span></span>
<span><span class="va">m_naive</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://lrberge.github.io/fixest/reference/feglm.html">fepois</a></span><span class="op">(</span><span class="va">visits</span> <span class="op">~</span> <span class="va">time</span> <span class="op">+</span> <span class="va">frfam</span>          <span class="op">|</span> <span class="va">ad</span> <span class="op">+</span> <span class="va">female</span>, data <span class="op">=</span> <span class="va">d</span>, notes <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">m_cf</span>    <span class="op">&lt;-</span> <span class="fu"><a href="https://lrberge.github.io/fixest/reference/feglm.html">fepois</a></span><span class="op">(</span><span class="va">visits</span> <span class="op">~</span> <span class="va">time</span> <span class="op">+</span> <span class="va">u2h_fe</span> <span class="op">+</span> <span class="va">frfam</span> <span class="op">|</span> <span class="va">ad</span> <span class="op">+</span> <span class="va">female</span>, data <span class="op">=</span> <span class="va">d</span>, notes <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://lrberge.github.io/fixest/reference/etable.html">etable</a></span><span class="op">(</span><span class="va">m_naive</span>, <span class="va">m_cf</span>,</span>
<span>       headers <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Naive FE Poisson"</span>, <span class="st">"Control function"</span><span class="op">)</span>,</span>
<span>       se.below <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>                         m_naive             m_cf
                Naive FE Poisson Control function
Dependent Var.:           visits           visits
                                                 
time                   0.1188***          0.0448 
                      (0.0076)           (0.0477)
frfam                 -0.0282**           0.0004 
                      (0.0108)           (0.0211)
u2h_fe                                    0.0765 
                                         (0.0487)
Fixed-Effects:        ----------         --------
ad                           Yes              Yes
female                       Yes              Yes
_______________       __________         ________
S.E. type                    IID              IID
Observations                 499              499
Squared Cor.             0.75130          0.75528
Pseudo R2                0.29670          0.29761
BIC                      2,083.5          2,087.1
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>These reproduce the Stata estimates to seven digits: 0.1187612 naive, 0.0448103 with the control function, and 0.0765144 on the residual. That is worth checking whenever a two-step procedure is assembled by hand in two languages, because the two steps give a lot of scope for a silent misalignment — the singleton above being the obvious one.</p>
<section id="bootstrapping-in-r" class="level3" data-number="26.5.1"><h3 data-number="26.5.1" class="anchored" data-anchor-id="bootstrapping-in-r">
<span class="header-section-number">26.5.1</span> Bootstrapping in R</h3>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span></span>
<span><span class="va">B</span> <span class="op">&lt;-</span> <span class="fl">1000</span></span>
<span><span class="va">clusters</span>   <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">d</span><span class="op">$</span><span class="va">ad</span><span class="op">)</span></span>
<span><span class="va">boot_coefs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="cn">NA_real_</span>, nrow <span class="op">=</span> <span class="va">B</span>, ncol <span class="op">=</span> <span class="fl">2</span>,</span>
<span>                     dimnames <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="cn">NULL</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"time"</span>, <span class="st">"resid"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="kw">for</span> <span class="op">(</span><span class="va">b</span> <span class="kw">in</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_len</a></span><span class="op">(</span><span class="va">B</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="co"># resample clusters with replacement; each drawn copy gets its own id, for</span></span>
<span>  <span class="co"># the same reason idcluster() is needed in Stata</span></span>
<span>  <span class="va">drawn</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="va">clusters</span>, <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">clusters</span><span class="op">)</span>, replace <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span>  <span class="va">boot_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/do.call.html">do.call</a></span><span class="op">(</span><span class="va">rbind</span>, <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_along</a></span><span class="op">(</span><span class="va">drawn</span><span class="op">)</span>, <span class="kw">function</span><span class="op">(</span><span class="va">k</span><span class="op">)</span> <span class="op">{</span></span>
<span>    <span class="va">sub</span> <span class="op">&lt;-</span> <span class="va">d</span><span class="op">[</span><span class="va">d</span><span class="op">$</span><span class="va">ad</span> <span class="op">==</span> <span class="va">drawn</span><span class="op">[</span><span class="va">k</span><span class="op">]</span>, <span class="op">]</span></span>
<span>    <span class="va">sub</span><span class="op">$</span><span class="va">boot_id</span> <span class="op">&lt;-</span> <span class="va">k</span></span>
<span>    <span class="va">sub</span></span>
<span>  <span class="op">}</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="va">boot_data</span><span class="op">$</span><span class="va">boot_id</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">boot_data</span><span class="op">$</span><span class="va">boot_id</span><span class="op">)</span></span>
<span></span>
<span>  <span class="va">fs_b</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://lrberge.github.io/fixest/reference/feols.html">feols</a></span><span class="op">(</span><span class="va">time</span> <span class="op">~</span> <span class="va">phone</span> <span class="op">+</span> <span class="va">frfam</span> <span class="op">|</span> <span class="va">boot_id</span> <span class="op">+</span> <span class="va">female</span>, data <span class="op">=</span> <span class="va">boot_data</span>, notes <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span>  <span class="va">bb</span>   <span class="op">&lt;-</span> <span class="va">boot_data</span><span class="op">[</span><span class="fu"><a href="https://lrberge.github.io/fixest/reference/obs.html">obs</a></span><span class="op">(</span><span class="va">fs_b</span><span class="op">)</span>, <span class="op">]</span></span>
<span>  <span class="va">bb</span><span class="op">$</span><span class="va">u_b</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">fs_b</span><span class="op">)</span></span>
<span></span>
<span>  <span class="va">m_b</span> <span class="op">&lt;-</span> <span class="kw"><a href="https://rdrr.io/r/base/try.html">try</a></span><span class="op">(</span><span class="fu"><a href="https://lrberge.github.io/fixest/reference/feglm.html">fepois</a></span><span class="op">(</span><span class="va">visits</span> <span class="op">~</span> <span class="va">time</span> <span class="op">+</span> <span class="va">u_b</span> <span class="op">+</span> <span class="va">frfam</span> <span class="op">|</span> <span class="va">boot_id</span> <span class="op">+</span> <span class="va">female</span>,</span>
<span>                    data <span class="op">=</span> <span class="va">bb</span>, notes <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>, silent <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span>  <span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/class.html">inherits</a></span><span class="op">(</span><span class="va">m_b</span>, <span class="st">"try-error"</span><span class="op">)</span><span class="op">)</span> <span class="va">boot_coefs</span><span class="op">[</span><span class="va">b</span>, <span class="op">]</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">m_b</span><span class="op">)</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"time"</span>, <span class="st">"u_b"</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"completed replications :"</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/complete.cases.html">complete.cases</a></span><span class="op">(</span><span class="va">boot_coefs</span><span class="op">)</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>completed replications : 1000 </code></pre>
</div>
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"bootstrap SE, time     :"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">boot_coefs</span><span class="op">[</span>, <span class="st">"time"</span><span class="op">]</span>,  na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>, <span class="fl">4</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>bootstrap SE, time     : 0.045 </code></pre>
</div>
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"bootstrap SE, residual :"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">boot_coefs</span><span class="op">[</span>, <span class="st">"resid"</span><span class="op">]</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>, <span class="fl">4</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>bootstrap SE, residual : 0.0457 </code></pre>
</div>
</div>
</section><section id="the-two-bootstraps-do-not-agree-and-that-is-the-lesson" class="level3" data-number="26.5.2"><h3 data-number="26.5.2" class="anchored" data-anchor-id="the-two-bootstraps-do-not-agree-and-that-is-the-lesson">
<span class="header-section-number">26.5.2</span> The two bootstraps do not agree, and that is the lesson</h3>
<p>Stata returns 0.0477 for <code>time</code>; R returns 0.0450, against an analytic 0.0449. At 1,000 replications that gap is larger than Monte Carlo error, so it is not noise in the replication count.</p>
<p>It is not a difference in the estimator. Handed one identical resampled dataset, <code>reghdfe</code> + <code>ppmlhdfe</code> and <code>feols</code> + <code>fepois</code> return 0.05226498 and 0.06030401 for the two coefficients — the same to eight decimal places. Nor is it Stata’s <code>bootstrap</code> prefix doing something unexpected: a hand-written cluster bootstrap in Stata, drawing the twelve clusters directly, gives 0.0498. Two Stata routes agree with each other and disagree with R.</p>
<p>The replication sample sizes match across the two, averaging about 501. What does not match is the tails of the replicate distribution: the Stata replicates run from <span class="math inline">\(-0.238\)</span> to <span class="math inline">\(0.224\)</span>, the R ones only from <span class="math inline">\(-0.173\)</span> to <span class="math inline">\(0.168\)</span>. That points at the draws where the resample degenerates — a cluster drawn several times, groups left with one or two observations, outcomes that are all zero within a group — which is exactly where <code>ppmlhdfe</code> and <code>fepois</code> make their own decisions about dropping singletons and separated observations. Those decisions agree on a well-behaved sample, as the identical draw above shows, and there is no reason to expect them to agree on a degenerate one. I have not confirmed this is the whole of it.</p>
<p>The conclusion does not depend on settling it. <code>ad</code> supplies twelve usable clusters. A cluster bootstrap on twelve clusters is not something to lean on, and two competent implementations disagreeing by ten per cent is a fair reflection of how much information twelve clusters carry. Bootstrap because the analytic standard error is wrong in a known direction; do not report the result to three digits as though it were settled.</p>
</section></section><section id="what-if-the-endogenous-variable-is-binary" class="level2" data-number="26.6"><h2 data-number="26.6" class="anchored" data-anchor-id="what-if-the-endogenous-variable-is-binary">
<span class="header-section-number">26.6</span> What if the endogenous variable is binary?</h2>
<p>The linear first stage is no longer valid — the independence condition it needs cannot hold for a discrete endogenous variable. The <a href="https://xiangao.github.io/causal_econometrics_guide/poisson-iv.html">guide chapter</a> works through why, and derives the replacement: a <strong>generalized residual</strong> from a reduced-form probit or logit in <span class="math inline">\(w_{it} = (1, z_{it}, \bar z_i)\)</span>. What follows is the part that matters when you sit down to compute it.</p>
<p><strong>For a logit the generalized residual is just <span class="math inline">\(y_{it2} - \hat p_{it2}\)</span>.</strong> The generalized residual is the score of the log-likelihood with respect to the index, and for a logit that score is exactly the response residual. So the familiar “predict the probability, then subtract” recipe <em>is</em> the generalized residual, not an approximation to it. For a probit it is not: there the generalized residual is the inverse-Mills expression, a genuinely different variable. In a simulated sample of 5,000 the two differ by as much as 1.59 while correlating at 0.999 — so the subtraction recipe is exact for a logit and simply wrong for a probit, and the high correlation means the mistake will not announce itself.</p>
<p><strong>Get the right residual out of the software.</strong> <code>predict</code> on its own after a binary model returns a probability, not a residual. The residuals it will give you are not the generalized residual either: Pearson residuals divide through by <span class="math inline">\(\sqrt{\hat p(1-\hat p)}\)</span>, and deviance residuals are a different transformation again. In the same simulation those correlate with the response residual at 0.991 and 0.995 — close enough to look right at a glance, and the wrong variable to put in the second stage. Compute <span class="math inline">\(d - \hat p\)</span> by hand.</p>
<p><strong>On the name.</strong> This construction is filed in the literature under <strong>correlated random effects</strong> (CRE) — see the <a href="./more-cre.html">CRE chapter</a> — and that is how to find it. The name describes the assumption, not the estimator. What is actually computed below is a <strong>pooled logit</strong> with group means added as regressors. No random effect is estimated, no variance component appears, nothing is integrated out. It is labelled “CRE (Mundlak device)” so both names stay visible: the first tells you where to look it up, the second tells you what runs.</p>
<section id="several-fixed-effects-in-the-first-stage" class="level3" data-number="26.6.1"><h3 data-number="26.6.1" class="anchored" data-anchor-id="several-fixed-effects-in-the-first-stage">
<span class="header-section-number">26.6.1</span> Several fixed effects in the first stage</h3>
<p><span class="math inline">\(w_{it} = (1, z_{it}, \bar z_i)\)</span> is written for a single unobserved effect. If the second stage absorbs more than one set of fixed effects — units, years, something else — the first stage needs the treatment in the <a href="./mundlak-device.html">Mundlak chapter</a>: take means over the <em>one</em> dimension you are eliminating, of everything else in the model, retained dummies included. In practice that means unit means of the instrument and the time-varying controls, plus unit means of the year and other dummies, with those dummies themselves kept in levels. Not one set of means per dimension — that construction is exact only for orthogonal designs, which observational panels are not.</p>
</section><section id="why-not-put-the-dummies-in-the-first-stage" class="level3" data-number="26.6.2"><h3 data-number="26.6.2" class="anchored" data-anchor-id="why-not-put-the-dummies-in-the-first-stage">
<span class="header-section-number">26.6.2</span> Why not put the dummies in the first stage?</h3>
<p>Because a logit with many thin groups is badly biased, and that is the whole reason for the Mundlak route. The size of the problem depends on observations per group, not on the number of groups. In a simulation with the total sample held near 12,000 and a true slope of 1, a logit with group dummies returns about 2.0 at two observations per group — matching the known result that the fixed-effects logit slope is inflated by a factor of two in that case — about 1.37 at four per group, 1.15 at six, 1.04 at twenty-five, and essentially the truth by a hundred. A panel with a few thousand units and four or five observations each sits in the worst part of that range. Year effects with hundreds of observations apiece are harmless and can simply be estimated.</p>
<p>The CRE (Mundlak device) first stage is better but not unbiased: in the same simulation it ran roughly ten per cent low at small group sizes, because integrating a logit over normal heterogeneity does not give a logit.</p>
</section><section id="a-worked-example" class="level3" data-number="26.6.3"><h3 data-number="26.6.3" class="anchored" data-anchor-id="a-worked-example">
<span class="header-section-number">26.6.3</span> A worked example</h3>
<p>The <code>website</code> data does not have the shape that causes trouble. <code>ad</code> has 13 levels, but they are very uneven — 128, 122, 90, 51, 44, 19, 16, 13, 8, 4, 2, 2, 1 observations — and <code>female</code> has 2 levels of about 250 each. Most of the sample therefore sits in cells large enough that a logit with dummies would be fine, even though a handful of <code>ad</code> cells are tiny.</p>
<p>So this simulates something more awkward instead: a count outcome, a binary endogenous regressor, an instrument, and two thousand units with between two and six observations each.</p>
<div class="cell" data-collectcode="true">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="kw">preserve</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="kw">clear</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="kw">set</span> <span class="dv">seed</span> 20260731</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="kw">set</span> <span class="kw">obs</span> 2000</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> i = <span class="dt">_n</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> <span class="kw">double</span> <span class="kw">ci</span> = rnormal()*0.5</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> T = 2 + <span class="kw">int</span>(runiform()*5)        <span class="co">/* unbalanced: 2-6 observations per unit */</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>expand T</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="kw">bysort</span> i: <span class="kw">gen</span> t = <span class="dt">_n</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> <span class="kw">double</span> z = rnormal()             <span class="co">/* the instrument */</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> <span class="kw">double</span> <span class="fu">e</span> = rnormal()</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> <span class="kw">double</span> u = 0.8*<span class="fu">e</span> + rnormal()*0.6 <span class="co">/* correlated with e, hence the endogeneity */</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> <span class="kw">byte</span>   <span class="kw">d</span> = (-0.2 + 0.9*z + <span class="kw">ci</span> + <span class="fu">e</span> &gt; 0)</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> <span class="kw">double</span> mu = <span class="fu">exp</span>(0.3*<span class="kw">d</span> + <span class="kw">ci</span> + 0.5*u)</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> <span class="fu">y</span> = rpoisson(mu)                 <span class="co">/* true coefficient on d is 0.3 */</span></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>* 1. naive FE Poisson, ignoring the endogeneity</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a><span class="kw">quietly</span> ppmlhdfe <span class="fu">y</span> <span class="kw">d</span>, absorb(i)</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> b_naive = _b[<span class="kw">d</span>]</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>* 2. control <span class="kw">function</span> with a CRE (Mundlak device) <span class="kw">logit</span> first stage: a POOLED</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>*    <span class="kw">logit</span> with the <span class="fu">group</span> <span class="kw">mean</span> <span class="kw">of</span> the instrument added.  No random effect is</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>*    estimated.  For a <span class="kw">logit</span> the generalized residual is just <span class="kw">d</span> - phat.</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a><span class="kw">bysort</span> i: <span class="kw">egen</span> <span class="kw">double</span> z_i = <span class="kw">mean</span>(z)</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a><span class="kw">quietly</span> <span class="kw">logit</span> <span class="kw">d</span> z z_i</span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a><span class="kw">predict</span> <span class="kw">double</span> phat, pr</span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> <span class="kw">double</span> <span class="kw">gr</span> = <span class="kw">d</span> - phat</span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a><span class="kw">quietly</span> ppmlhdfe <span class="fu">y</span> <span class="kw">d</span> <span class="kw">gr</span>, absorb(i)</span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> b_cre = _b[<span class="kw">d</span>]</span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a>* 3. control <span class="kw">function</span> with a linear first stage, unit FE absorbed exactly</span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a><span class="kw">quietly</span> reghdfe <span class="kw">d</span> z, absorb(i) <span class="kw">resid</span></span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a><span class="kw">predict</span> <span class="kw">double</span> v_lin, <span class="kw">resid</span></span>
<span id="cb15-35"><a href="#cb15-35" aria-hidden="true" tabindex="-1"></a><span class="kw">quietly</span> ppmlhdfe <span class="fu">y</span> <span class="kw">d</span> v_lin, absorb(i)</span>
<span id="cb15-36"><a href="#cb15-36" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> b_lin = _b[<span class="kw">d</span>]</span>
<span id="cb15-37"><a href="#cb15-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-38"><a href="#cb15-38" aria-hidden="true" tabindex="-1"></a><span class="kw">di</span> <span class="st">"true coefficient on d           = 0.300000"</span></span>
<span id="cb15-39"><a href="#cb15-39" aria-hidden="true" tabindex="-1"></a><span class="kw">di</span> <span class="st">"naive FE Poisson                = "</span> %8.6f b_naive</span>
<span id="cb15-40"><a href="#cb15-40" aria-hidden="true" tabindex="-1"></a><span class="kw">di</span> <span class="st">"CF, CRE (Mundlak) logit         = "</span> %8.6f b_cre</span>
<span id="cb15-41"><a href="#cb15-41" aria-hidden="true" tabindex="-1"></a><span class="kw">di</span> <span class="st">"CF, linear FE first stage       = "</span> %8.6f b_lin</span>
<span id="cb15-42"><a href="#cb15-42" aria-hidden="true" tabindex="-1"></a><span class="kw">restore</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Number of observations (_N) was 0, now 2,000.




(5,969 observations created)




















true coefficient on d           = 0.300000

naive FE Poisson                = 0.747206

CF, CRE (Mundlak) logit         = 0.293829

CF, linear FE first stage       = 0.277644</code></pre>
</div>
</div>
<p>Against a true coefficient of 0.300000, the naive FE Poisson gives 0.747206, the CRE/Mundlak logit first stage gives 0.293829, and the linear FE first stage gives 0.277644.</p>
<p>The naive estimate is inflated by about two and a half times. Both control-function versions land close to the truth, and they agree with each other — within 0.016 of one another, both within 0.023 of the truth. That agreement is the point. With a binary endogenous variable I would report both: the linear first stage rests on the numerical-equivalence result above and drops no observations, while the logit version is better specified for a binary variable but rests on an approximation the literature has not settled. If they diverge materially, that is the most important thing you have learned, and it belongs in the write-up.</p>
<p>The standard errors in that chunk are wrong, for the reason given earlier. Bootstrap both stages together, as above.</p>
<hr>
<!-- see-also-footer --><p><em>Theory and derivations: <a href="https://xiangao.github.io/causal_econometrics_guide/poisson-iv.html">R</a> · <a href="https://xiangao.github.io/causal_econometrics_julia/poisson-iv.html">Julia</a>.</em></p>


<!-- -->

</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/xiangao\.github\.io\/blog_book\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./poisson-exposure.html" class="pagination-link" aria-label="Poisson model with exposure">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Poisson model with exposure</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./tmle.html" class="pagination-link" aria-label="Using machine learning for causal effect in observational study">
        <span class="nav-page-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Using machine learning for causal effect in observational study</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "IV in fixed-effect Poisson with many fixed effects: worked examples"</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2024-08-29"</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>This is the applied companion to the <span class="co">[</span><span class="ot">Poisson IV chapter</span><span class="co">](https://xiangao.github.io/causal_econometrics_guide/poisson-iv.html)</span> of the *Causal Econometrics Guide*.  Everything here is code and output: which commands to type, what the estimates look like on real and simulated data, and the places the mechanics bite.  The derivations behind it --- why the control function is not 2SLS once the mean is exponential, why a linear first stage stops being valid for a discrete endogenous variable, Terza's exact correction and the Taylor expansion that makes the generalized residual its first-order approximation --- are in the guide chapter, and are not repeated below.  A Julia version of the same material is <span class="co">[</span><span class="ot">here</span><span class="co">](https://xiangao.github.io/causal_econometrics_julia/poisson-iv.html)</span>.</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="fu">## Which commands</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>Stata's <span class="in">`xtpoisson, fe`</span> fits fixed-effect Poisson, but <span class="in">`ppmlhdfe`</span> is the better choice: it absorbs several dimensions of fixed effects at once, it is faster, and it reports predicted values with the fixed effects put back in.  That last point is the one that catches people --- after <span class="in">`xtpoisson, fe`</span> or <span class="in">`xtreg, fe`</span> the effects are absorbed rather than estimated, so predicted values come back without them.  The same author's <span class="in">`reghdfe`</span> replaces <span class="in">`areg`</span> and <span class="in">`xtreg, fe`</span> for the linear first stage, with the same advantages.</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="in">`ivpoisson`</span> handles endogenous regressors in a Poisson model but has no option for fixed effects, which is why the route below is a two-step control function rather than a packaged IV command.</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>In R, <span class="in">`fixest::fepois()`</span> and <span class="in">`fixest::feols()`</span> do the same jobs.</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a><span class="fu">## The recipe</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>For a continuous endogenous variable this is Procedure 3 of Lin and Wooldridge (2019):</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Run the reduced form for the endogenous variable and keep the residual.  All fixed effects that appear in the second stage go into this regression too.  In Stata, <span class="in">`reghdfe ..., resid`</span>.</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Put the endogenous variable and that residual into the second-stage Poisson, absorbing the same fixed effects.  In Stata, <span class="in">`ppmlhdfe`</span>.</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Bootstrap.  The second-stage standard errors are wrong as reported, because the residual is generated.  Lin and Wooldridge (2019, p. 30) recommend a panel bootstrap that redoes both steps within each replication.  With clustered errors, resample the clusters.</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>The $t$-statistic on the residual is a test of endogeneity.  It is not a model-selection device: do not run it and then drop the residual if it comes back insignificant.  Guggenberger (2010) shows that this two-stage procedure has asymptotic size one.  Report both columns.  The reasoning is in the <span class="co">[</span><span class="ot">guide chapter</span><span class="co">](https://xiangao.github.io/causal_econometrics_guide/poisson-iv.html)</span>.</span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a><span class="fu">### A terminology note</span></span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a>Three things carry similar names and are easy to conflate.</span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a>The **Mundlak device** means adding group *means* of covariates as regressors --- see the [Mundlak chapter](mundlak-device.qmd).  The **control-function residual** is the residual from a reduced form.  Those are different constructions.  But Lin and Wooldridge (2019) call the residual from a reduced form *that itself includes the Mundlak means* --- from regressing $y_{it2}$ on $z_{it}$ and $\bar z_i$ --- the **Mundlak residual**, as against the **FE residual** from within-transforming.  So in that paper "Mundlak residual" denotes a control-function residual, not the device.</span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a>Which of those two residuals you use does not matter: they give numerically identical estimates of the structural coefficient and of the coefficient on the control function (Lin and Wooldridge 2019, appendices A.1 and A.2), because they differ only by a term that is constant within unit and the second-stage fixed effects absorb it.</span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a>That result has a practical consequence, and it is the reason it is worth knowing.  The first stage does not need thousands of unit dummies; the unit means will do, at no cost in the estimate.  That is what makes a **nonlinear** first stage practical --- you cannot put 2,000 dummies into a logit without an incidental-parameters problem, but you can put in 2,000 unit means.  The result as stated is for a *linear* reduced form.</span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a><span class="fu">## Continuous endogenous variable: the `website` data</span></span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-42"><a href="#cb17-42" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-43"><a href="#cb17-43" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb17-44"><a href="#cb17-44" aria-hidden="true" tabindex="-1"></a><span class="co">#| include: false</span></span>
<span id="cb17-45"><a href="#cb17-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-46"><a href="#cb17-46" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-47"><a href="#cb17-47" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Statamarkdown)</span>
<span id="cb17-48"><a href="#cb17-48" aria-hidden="true" tabindex="-1"></a>stataexe <span class="ot">&lt;-</span> <span class="fu">find_stata</span>()</span>
<span id="cb17-49"><a href="#cb17-49" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">engine.path =</span> <span class="fu">list</span>(<span class="at">stata =</span> stataexe))</span>
<span id="cb17-50"><a href="#cb17-50" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-51"><a href="#cb17-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-52"><a href="#cb17-52" aria-hidden="true" tabindex="-1"></a>Stata's <span class="in">`website.dta`</span> has 500 observations.  <span class="in">`visits`</span> is the count outcome, <span class="in">`time`</span> (minutes on the site) is the endogenous regressor, <span class="in">`phone`</span> (support calls) is the excluded instrument, and <span class="in">`frfam`</span> (referrals from friends and family) is an exogenous control.  <span class="in">`ad`</span> and <span class="in">`female`</span> are the two fixed-effect dimensions.</span>
<span id="cb17-53"><a href="#cb17-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-56"><a href="#cb17-56" aria-hidden="true" tabindex="-1"></a><span class="in">```{stata}</span></span>
<span id="cb17-57"><a href="#cb17-57" aria-hidden="true" tabindex="-1"></a><span class="in">*| label: stata1</span></span>
<span id="cb17-58"><a href="#cb17-58" aria-hidden="true" tabindex="-1"></a><span class="in">*| echo: true</span></span>
<span id="cb17-59"><a href="#cb17-59" aria-hidden="true" tabindex="-1"></a><span class="in">*| collectcode: true</span></span>
<span id="cb17-60"><a href="#cb17-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-61"><a href="#cb17-61" aria-hidden="true" tabindex="-1"></a><span class="in">webuse website, clear</span></span>
<span id="cb17-62"><a href="#cb17-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-63"><a href="#cb17-63" aria-hidden="true" tabindex="-1"></a><span class="in">* step 1: linear first stage, absorbing both sets of fixed effects</span></span>
<span id="cb17-64"><a href="#cb17-64" aria-hidden="true" tabindex="-1"></a><span class="in">reghdfe time phone frfam, absorb(ad female) resid</span></span>
<span id="cb17-65"><a href="#cb17-65" aria-hidden="true" tabindex="-1"></a><span class="in">predict double u2h_fe, resid</span></span>
<span id="cb17-66"><a href="#cb17-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-67"><a href="#cb17-67" aria-hidden="true" tabindex="-1"></a><span class="in">* step 2: FE Poisson with the control-function residual added</span></span>
<span id="cb17-68"><a href="#cb17-68" aria-hidden="true" tabindex="-1"></a><span class="in">ppmlhdfe visits time u2h_fe frfam, absorb(ad female)</span></span>
<span id="cb17-69"><a href="#cb17-69" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-70"><a href="#cb17-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-71"><a href="#cb17-71" aria-hidden="true" tabindex="-1"></a><span class="in">`time`</span> comes out at 0.0448 with $p = 0.318$.  The residual <span class="in">`u2h_fe`</span> gets 0.0765 with $p = 0.096$, so what endogeneity the data can detect is positive and weakly signalled.  Both standard errors are wrong; see the bootstrap section below.</span>
<span id="cb17-72"><a href="#cb17-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-73"><a href="#cb17-73" aria-hidden="true" tabindex="-1"></a><span class="fu">### Checking the mechanics against a linear model</span></span>
<span id="cb17-74"><a href="#cb17-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-75"><a href="#cb17-75" aria-hidden="true" tabindex="-1"></a>The control function is exactly 2SLS in a linear model, so running the linear version both ways is a check that the two steps are wired up correctly.  It is a check on the code, not evidence that the Poisson version is valid --- that rests on assumptions the linear case does not need.</span>
<span id="cb17-76"><a href="#cb17-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-79"><a href="#cb17-79" aria-hidden="true" tabindex="-1"></a><span class="in">```{stata}</span></span>
<span id="cb17-80"><a href="#cb17-80" aria-hidden="true" tabindex="-1"></a><span class="in">*| label: stata2</span></span>
<span id="cb17-81"><a href="#cb17-81" aria-hidden="true" tabindex="-1"></a><span class="in">*| echo: true</span></span>
<span id="cb17-82"><a href="#cb17-82" aria-hidden="true" tabindex="-1"></a><span class="in">*| collectcode: true</span></span>
<span id="cb17-83"><a href="#cb17-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-84"><a href="#cb17-84" aria-hidden="true" tabindex="-1"></a><span class="in">clear all</span></span>
<span id="cb17-85"><a href="#cb17-85" aria-hidden="true" tabindex="-1"></a><span class="in">webuse website, clear</span></span>
<span id="cb17-86"><a href="#cb17-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-87"><a href="#cb17-87" aria-hidden="true" tabindex="-1"></a><span class="in">* 1. linear 2SLS</span></span>
<span id="cb17-88"><a href="#cb17-88" aria-hidden="true" tabindex="-1"></a><span class="in">ivreghdfe visits frfam (time=phone), absorb(ad female)</span></span>
<span id="cb17-89"><a href="#cb17-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-90"><a href="#cb17-90" aria-hidden="true" tabindex="-1"></a><span class="in">* 2. the same thing as a manual two-step control function</span></span>
<span id="cb17-91"><a href="#cb17-91" aria-hidden="true" tabindex="-1"></a><span class="in">reghdfe time phone frfam, absorb(ad female) resid</span></span>
<span id="cb17-92"><a href="#cb17-92" aria-hidden="true" tabindex="-1"></a><span class="in">predict double u2h_fe, resid</span></span>
<span id="cb17-93"><a href="#cb17-93" aria-hidden="true" tabindex="-1"></a><span class="in">reghdfe visits time u2h_fe frfam, absorb(ad female)</span></span>
<span id="cb17-94"><a href="#cb17-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-95"><a href="#cb17-95" aria-hidden="true" tabindex="-1"></a><span class="in">* 3. naive models, ignoring the endogeneity</span></span>
<span id="cb17-96"><a href="#cb17-96" aria-hidden="true" tabindex="-1"></a><span class="in">reghdfe visits time frfam, absorb(ad female)</span></span>
<span id="cb17-97"><a href="#cb17-97" aria-hidden="true" tabindex="-1"></a><span class="in">ppmlhdfe visits time frfam, absorb(ad female)</span></span>
<span id="cb17-98"><a href="#cb17-98" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-99"><a href="#cb17-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-100"><a href="#cb17-100" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Model <span class="pp">|</span> Command <span class="pp">|</span> Coefficient on <span class="in">`time`</span> <span class="pp">|</span> Std. err. <span class="pp">|</span> $p$ <span class="pp">|</span></span>
<span id="cb17-101"><a href="#cb17-101" aria-hidden="true" tabindex="-1"></a><span class="pp">|:---|:---|:---:|:---:|:---:|</span></span>
<span id="cb17-102"><a href="#cb17-102" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Naive linear FE <span class="pp">|</span> <span class="in">`reghdfe`</span> <span class="pp">|</span> 0.7402 <span class="pp">|</span> 0.0401 <span class="pp">|</span> $&lt;0.001$ <span class="pp">|</span></span>
<span id="cb17-103"><a href="#cb17-103" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Linear 2SLS <span class="pp">|</span> <span class="in">`ivreghdfe`</span> <span class="pp">|</span> 0.5643 <span class="pp">|</span> 0.2124 <span class="pp">|</span> 0.008 <span class="pp">|</span></span>
<span id="cb17-104"><a href="#cb17-104" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Linear control function <span class="pp">|</span> two-step <span class="in">`reghdfe`</span> <span class="pp">|</span> 0.5643 <span class="pp">|</span> 0.2083 <span class="pp">|</span> 0.007 <span class="pp">|</span></span>
<span id="cb17-105"><a href="#cb17-105" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Naive FE Poisson <span class="pp">|</span> <span class="in">`ppmlhdfe`</span>, no residual <span class="pp">|</span> 0.1188 <span class="pp">|</span> 0.0096 <span class="pp">|</span> $&lt;0.001$ <span class="pp">|</span></span>
<span id="cb17-106"><a href="#cb17-106" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Control-function FE Poisson <span class="pp">|</span> <span class="in">`ppmlhdfe`</span>, with <span class="in">`u2h_fe`</span> <span class="pp">|</span> 0.0448 <span class="pp">|</span> 0.0449 <span class="pp">|</span> 0.318 <span class="pp">|</span></span>
<span id="cb17-107"><a href="#cb17-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-108"><a href="#cb17-108" aria-hidden="true" tabindex="-1"></a>The two linear rows agree on the coefficient to seven digits, which is the check working.  Their standard errors do not agree, and that is the generated-regressor problem in miniature: <span class="in">`ivreghdfe`</span> accounts for the first stage, the manual two-step does not, and the gap here happens to be small only because the design is favourable.</span>
<span id="cb17-109"><a href="#cb17-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-110"><a href="#cb17-110" aria-hidden="true" tabindex="-1"></a>In the Poisson rows the naive estimate is 0.1188 and the control-function estimate is 0.0448.  The correction is large and in the direction the sign of <span class="in">`u2h_fe`</span> predicts.</span>
<span id="cb17-111"><a href="#cb17-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-112"><a href="#cb17-112" aria-hidden="true" tabindex="-1"></a><span class="fu">## Bootstrapping the standard errors</span></span>
<span id="cb17-113"><a href="#cb17-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-114"><a href="#cb17-114" aria-hidden="true" tabindex="-1"></a>Suppose we want errors clustered on <span class="in">`ad`</span>.</span>
<span id="cb17-115"><a href="#cb17-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-118"><a href="#cb17-118" aria-hidden="true" tabindex="-1"></a><span class="in">```{stata}</span></span>
<span id="cb17-119"><a href="#cb17-119" aria-hidden="true" tabindex="-1"></a><span class="in">*| label: stata3</span></span>
<span id="cb17-120"><a href="#cb17-120" aria-hidden="true" tabindex="-1"></a><span class="in">*| echo: true</span></span>
<span id="cb17-121"><a href="#cb17-121" aria-hidden="true" tabindex="-1"></a><span class="in">*| collectcode: true</span></span>
<span id="cb17-122"><a href="#cb17-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-123"><a href="#cb17-123" aria-hidden="true" tabindex="-1"></a><span class="in">* Note on idcluster(newid): it gives each resampled COPY of a cluster its own</span></span>
<span id="cb17-124"><a href="#cb17-124" aria-hidden="true" tabindex="-1"></a><span class="in">* unique id.  A cluster can be drawn more than once within a replication, and</span></span>
<span id="cb17-125"><a href="#cb17-125" aria-hidden="true" tabindex="-1"></a><span class="in">* the duplicates must be treated as distinct groups.  The regressions inside</span></span>
<span id="cb17-126"><a href="#cb17-126" aria-hidden="true" tabindex="-1"></a><span class="in">* the program must therefore absorb "newid", not the original "ad" --- absorbing</span></span>
<span id="cb17-127"><a href="#cb17-127" aria-hidden="true" tabindex="-1"></a><span class="in">* "ad" would pool the duplicates back into a single fixed effect, which breaks</span></span>
<span id="cb17-128"><a href="#cb17-128" aria-hidden="true" tabindex="-1"></a><span class="in">* the cluster-bootstrap logic.  Verified empirically: within a replication the</span></span>
<span id="cb17-129"><a href="#cb17-129" aria-hidden="true" tabindex="-1"></a><span class="in">* number of distinct "ad" values is consistently below the true cluster count,</span></span>
<span id="cb17-130"><a href="#cb17-130" aria-hidden="true" tabindex="-1"></a><span class="in">* while "newid" always has exactly that many.</span></span>
<span id="cb17-131"><a href="#cb17-131" aria-hidden="true" tabindex="-1"></a><span class="in">clear all</span></span>
<span id="cb17-132"><a href="#cb17-132" aria-hidden="true" tabindex="-1"></a><span class="in">capture program drop ppmlhdfe_cf</span></span>
<span id="cb17-133"><a href="#cb17-133" aria-hidden="true" tabindex="-1"></a><span class="in">program ppmlhdfe_cf, rclass</span></span>
<span id="cb17-134"><a href="#cb17-134" aria-hidden="true" tabindex="-1"></a><span class="in">  reghdfe time phone frfam, absorb(newid female) resid</span></span>
<span id="cb17-135"><a href="#cb17-135" aria-hidden="true" tabindex="-1"></a><span class="in">  predict double u2h_fe, resid</span></span>
<span id="cb17-136"><a href="#cb17-136" aria-hidden="true" tabindex="-1"></a><span class="in">  ppmlhdfe visits time u2h_fe frfam, absorb(newid female)</span></span>
<span id="cb17-137"><a href="#cb17-137" aria-hidden="true" tabindex="-1"></a><span class="in">  return scalar b_time = _b[time]</span></span>
<span id="cb17-138"><a href="#cb17-138" aria-hidden="true" tabindex="-1"></a><span class="in">  return scalar b_u2h  = _b[u2h_fe]</span></span>
<span id="cb17-139"><a href="#cb17-139" aria-hidden="true" tabindex="-1"></a><span class="in">  drop u2h_fe</span></span>
<span id="cb17-140"><a href="#cb17-140" aria-hidden="true" tabindex="-1"></a><span class="in">  xtset, clear</span></span>
<span id="cb17-141"><a href="#cb17-141" aria-hidden="true" tabindex="-1"></a><span class="in">end</span></span>
<span id="cb17-142"><a href="#cb17-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-143"><a href="#cb17-143" aria-hidden="true" tabindex="-1"></a><span class="in">webuse website, clear</span></span>
<span id="cb17-144"><a href="#cb17-144" aria-hidden="true" tabindex="-1"></a><span class="in">xtset, clear</span></span>
<span id="cb17-145"><a href="#cb17-145" aria-hidden="true" tabindex="-1"></a><span class="in">bootstrap r(b_time) r(b_u2h), reps(1000) seed(123) cluster(ad) idcluster(newid) nodots: ppmlhdfe_cf</span></span>
<span id="cb17-146"><a href="#cb17-146" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-147"><a href="#cb17-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-148"><a href="#cb17-148" aria-hidden="true" tabindex="-1"></a>The bootstrap standard error on <span class="in">`time`</span> comes out at 0.0477 against the 0.0449 reported analytically.  Before reading anything into that six per cent, see the comparison with the R bootstrap below --- the two do not agree, and the reason matters more than either number.</span>
<span id="cb17-149"><a href="#cb17-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-150"><a href="#cb17-150" aria-hidden="true" tabindex="-1"></a>A troubleshooting note: <span class="in">`xtset, clear`</span> is needed before each regression inside the bootstrap.  Stata's cluster bootstrap creates a new id variable for the resampled clusters and leaves the panel <span class="in">`xtset`</span> to it; if that is not cleared, a later regression can pick up the stale panel setting even when it does not use the id.</span>
<span id="cb17-151"><a href="#cb17-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-152"><a href="#cb17-152" aria-hidden="true" tabindex="-1"></a><span class="fu">## The same thing in R</span></span>
<span id="cb17-153"><a href="#cb17-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-156"><a href="#cb17-156" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-157"><a href="#cb17-157" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: r-demo</span></span>
<span id="cb17-158"><a href="#cb17-158" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb17-159"><a href="#cb17-159" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb17-160"><a href="#cb17-160" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb17-161"><a href="#cb17-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-162"><a href="#cb17-162" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fixest)</span>
<span id="cb17-163"><a href="#cb17-163" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb17-164"><a href="#cb17-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-165"><a href="#cb17-165" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">read_dta</span>(<span class="st">"https://www.stata-press.com/data/r18/website.dta"</span>))</span>
<span id="cb17-166"><a href="#cb17-166" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>ad     <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(df<span class="sc">$</span>ad)</span>
<span id="cb17-167"><a href="#cb17-167" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>female <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(df<span class="sc">$</span>female)</span>
<span id="cb17-168"><a href="#cb17-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-169"><a href="#cb17-169" aria-hidden="true" tabindex="-1"></a><span class="co"># step 1: linear first stage, absorbing both sets of fixed effects</span></span>
<span id="cb17-170"><a href="#cb17-170" aria-hidden="true" tabindex="-1"></a>fs <span class="ot">&lt;-</span> <span class="fu">feols</span>(time <span class="sc">~</span> phone <span class="sc">+</span> frfam <span class="sc">|</span> ad <span class="sc">+</span> female, <span class="at">data =</span> df)</span>
<span id="cb17-171"><a href="#cb17-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-172"><a href="#cb17-172" aria-hidden="true" tabindex="-1"></a><span class="co"># feols drops a singleton (ad == 10 has one observation), exactly as reghdfe</span></span>
<span id="cb17-173"><a href="#cb17-173" aria-hidden="true" tabindex="-1"></a><span class="co"># does, so the residual is shorter than the data.  obs() gives the rows that</span></span>
<span id="cb17-174"><a href="#cb17-174" aria-hidden="true" tabindex="-1"></a><span class="co"># were kept; align on those rather than assuming the lengths match.</span></span>
<span id="cb17-175"><a href="#cb17-175" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> df[<span class="fu">obs</span>(fs), ]</span>
<span id="cb17-176"><a href="#cb17-176" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>u2h_fe <span class="ot">&lt;-</span> <span class="fu">residuals</span>(fs)</span>
<span id="cb17-177"><a href="#cb17-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-178"><a href="#cb17-178" aria-hidden="true" tabindex="-1"></a><span class="co"># step 2: FE Poisson, without and with the control function</span></span>
<span id="cb17-179"><a href="#cb17-179" aria-hidden="true" tabindex="-1"></a>m_naive <span class="ot">&lt;-</span> <span class="fu">fepois</span>(visits <span class="sc">~</span> time <span class="sc">+</span> frfam          <span class="sc">|</span> ad <span class="sc">+</span> female, <span class="at">data =</span> d, <span class="at">notes =</span> <span class="cn">FALSE</span>)</span>
<span id="cb17-180"><a href="#cb17-180" aria-hidden="true" tabindex="-1"></a>m_cf    <span class="ot">&lt;-</span> <span class="fu">fepois</span>(visits <span class="sc">~</span> time <span class="sc">+</span> u2h_fe <span class="sc">+</span> frfam <span class="sc">|</span> ad <span class="sc">+</span> female, <span class="at">data =</span> d, <span class="at">notes =</span> <span class="cn">FALSE</span>)</span>
<span id="cb17-181"><a href="#cb17-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-182"><a href="#cb17-182" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(m_naive, m_cf,</span>
<span id="cb17-183"><a href="#cb17-183" aria-hidden="true" tabindex="-1"></a>       <span class="at">headers =</span> <span class="fu">c</span>(<span class="st">"Naive FE Poisson"</span>, <span class="st">"Control function"</span>),</span>
<span id="cb17-184"><a href="#cb17-184" aria-hidden="true" tabindex="-1"></a>       <span class="at">se.below =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-185"><a href="#cb17-185" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-186"><a href="#cb17-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-187"><a href="#cb17-187" aria-hidden="true" tabindex="-1"></a>These reproduce the Stata estimates to seven digits: 0.1187612 naive, 0.0448103 with the control function, and 0.0765144 on the residual.  That is worth checking whenever a two-step procedure is assembled by hand in two languages, because the two steps give a lot of scope for a silent misalignment --- the singleton above being the obvious one.</span>
<span id="cb17-188"><a href="#cb17-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-189"><a href="#cb17-189" aria-hidden="true" tabindex="-1"></a><span class="fu">### Bootstrapping in R</span></span>
<span id="cb17-190"><a href="#cb17-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-193"><a href="#cb17-193" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-194"><a href="#cb17-194" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: r-bootstrap</span></span>
<span id="cb17-195"><a href="#cb17-195" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb17-196"><a href="#cb17-196" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb17-197"><a href="#cb17-197" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb17-198"><a href="#cb17-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-199"><a href="#cb17-199" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb17-200"><a href="#cb17-200" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb17-201"><a href="#cb17-201" aria-hidden="true" tabindex="-1"></a>clusters   <span class="ot">&lt;-</span> <span class="fu">unique</span>(d<span class="sc">$</span>ad)</span>
<span id="cb17-202"><a href="#cb17-202" aria-hidden="true" tabindex="-1"></a>boot_coefs <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA_real_</span>, <span class="at">nrow =</span> B, <span class="at">ncol =</span> <span class="dv">2</span>,</span>
<span id="cb17-203"><a href="#cb17-203" aria-hidden="true" tabindex="-1"></a>                     <span class="at">dimnames =</span> <span class="fu">list</span>(<span class="cn">NULL</span>, <span class="fu">c</span>(<span class="st">"time"</span>, <span class="st">"resid"</span>)))</span>
<span id="cb17-204"><a href="#cb17-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-205"><a href="#cb17-205" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (b <span class="cf">in</span> <span class="fu">seq_len</span>(B)) {</span>
<span id="cb17-206"><a href="#cb17-206" aria-hidden="true" tabindex="-1"></a>  <span class="co"># resample clusters with replacement; each drawn copy gets its own id, for</span></span>
<span id="cb17-207"><a href="#cb17-207" aria-hidden="true" tabindex="-1"></a>  <span class="co"># the same reason idcluster() is needed in Stata</span></span>
<span id="cb17-208"><a href="#cb17-208" aria-hidden="true" tabindex="-1"></a>  drawn <span class="ot">&lt;-</span> <span class="fu">sample</span>(clusters, <span class="fu">length</span>(clusters), <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-209"><a href="#cb17-209" aria-hidden="true" tabindex="-1"></a>  boot_data <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, <span class="fu">lapply</span>(<span class="fu">seq_along</span>(drawn), <span class="cf">function</span>(k) {</span>
<span id="cb17-210"><a href="#cb17-210" aria-hidden="true" tabindex="-1"></a>    sub <span class="ot">&lt;-</span> d[d<span class="sc">$</span>ad <span class="sc">==</span> drawn[k], ]</span>
<span id="cb17-211"><a href="#cb17-211" aria-hidden="true" tabindex="-1"></a>    sub<span class="sc">$</span>boot_id <span class="ot">&lt;-</span> k</span>
<span id="cb17-212"><a href="#cb17-212" aria-hidden="true" tabindex="-1"></a>    sub</span>
<span id="cb17-213"><a href="#cb17-213" aria-hidden="true" tabindex="-1"></a>  }))</span>
<span id="cb17-214"><a href="#cb17-214" aria-hidden="true" tabindex="-1"></a>  boot_data<span class="sc">$</span>boot_id <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(boot_data<span class="sc">$</span>boot_id)</span>
<span id="cb17-215"><a href="#cb17-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-216"><a href="#cb17-216" aria-hidden="true" tabindex="-1"></a>  fs_b <span class="ot">&lt;-</span> <span class="fu">feols</span>(time <span class="sc">~</span> phone <span class="sc">+</span> frfam <span class="sc">|</span> boot_id <span class="sc">+</span> female, <span class="at">data =</span> boot_data, <span class="at">notes =</span> <span class="cn">FALSE</span>)</span>
<span id="cb17-217"><a href="#cb17-217" aria-hidden="true" tabindex="-1"></a>  bb   <span class="ot">&lt;-</span> boot_data[<span class="fu">obs</span>(fs_b), ]</span>
<span id="cb17-218"><a href="#cb17-218" aria-hidden="true" tabindex="-1"></a>  bb<span class="sc">$</span>u_b <span class="ot">&lt;-</span> <span class="fu">residuals</span>(fs_b)</span>
<span id="cb17-219"><a href="#cb17-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-220"><a href="#cb17-220" aria-hidden="true" tabindex="-1"></a>  m_b <span class="ot">&lt;-</span> <span class="fu">try</span>(<span class="fu">fepois</span>(visits <span class="sc">~</span> time <span class="sc">+</span> u_b <span class="sc">+</span> frfam <span class="sc">|</span> boot_id <span class="sc">+</span> female,</span>
<span id="cb17-221"><a href="#cb17-221" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> bb, <span class="at">notes =</span> <span class="cn">FALSE</span>), <span class="at">silent =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-222"><a href="#cb17-222" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">inherits</span>(m_b, <span class="st">"try-error"</span>)) boot_coefs[b, ] <span class="ot">&lt;-</span> <span class="fu">coef</span>(m_b)[<span class="fu">c</span>(<span class="st">"time"</span>, <span class="st">"u_b"</span>)]</span>
<span id="cb17-223"><a href="#cb17-223" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb17-224"><a href="#cb17-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-225"><a href="#cb17-225" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"completed replications :"</span>, <span class="fu">sum</span>(<span class="fu">complete.cases</span>(boot_coefs)), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb17-226"><a href="#cb17-226" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"bootstrap SE, time     :"</span>, <span class="fu">round</span>(<span class="fu">sd</span>(boot_coefs[, <span class="st">"time"</span>],  <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb17-227"><a href="#cb17-227" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"bootstrap SE, residual :"</span>, <span class="fu">round</span>(<span class="fu">sd</span>(boot_coefs[, <span class="st">"resid"</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb17-228"><a href="#cb17-228" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-229"><a href="#cb17-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-230"><a href="#cb17-230" aria-hidden="true" tabindex="-1"></a><span class="fu">### The two bootstraps do not agree, and that is the lesson</span></span>
<span id="cb17-231"><a href="#cb17-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-232"><a href="#cb17-232" aria-hidden="true" tabindex="-1"></a>Stata returns 0.0477 for <span class="in">`time`</span>; R returns 0.0450, against an analytic 0.0449.  At 1,000 replications that gap is larger than Monte Carlo error, so it is not noise in the replication count.</span>
<span id="cb17-233"><a href="#cb17-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-234"><a href="#cb17-234" aria-hidden="true" tabindex="-1"></a>It is not a difference in the estimator.  Handed one identical resampled dataset, <span class="in">`reghdfe`</span> + <span class="in">`ppmlhdfe`</span> and <span class="in">`feols`</span> + <span class="in">`fepois`</span> return 0.05226498 and 0.06030401 for the two coefficients --- the same to eight decimal places.  Nor is it Stata's <span class="in">`bootstrap`</span> prefix doing something unexpected: a hand-written cluster bootstrap in Stata, drawing the twelve clusters directly, gives 0.0498.  Two Stata routes agree with each other and disagree with R.</span>
<span id="cb17-235"><a href="#cb17-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-236"><a href="#cb17-236" aria-hidden="true" tabindex="-1"></a>The replication sample sizes match across the two, averaging about 501.  What does not match is the tails of the replicate distribution: the Stata replicates run from $-0.238$ to $0.224$, the R ones only from $-0.173$ to $0.168$.  That points at the draws where the resample degenerates --- a cluster drawn several times, groups left with one or two observations, outcomes that are all zero within a group --- which is exactly where <span class="in">`ppmlhdfe`</span> and <span class="in">`fepois`</span> make their own decisions about dropping singletons and separated observations.  Those decisions agree on a well-behaved sample, as the identical draw above shows, and there is no reason to expect them to agree on a degenerate one.  I have not confirmed this is the whole of it.</span>
<span id="cb17-237"><a href="#cb17-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-238"><a href="#cb17-238" aria-hidden="true" tabindex="-1"></a>The conclusion does not depend on settling it.  <span class="in">`ad`</span> supplies twelve usable clusters.  A cluster bootstrap on twelve clusters is not something to lean on, and two competent implementations disagreeing by ten per cent is a fair reflection of how much information twelve clusters carry.  Bootstrap because the analytic standard error is wrong in a known direction; do not report the result to three digits as though it were settled.</span>
<span id="cb17-239"><a href="#cb17-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-240"><a href="#cb17-240" aria-hidden="true" tabindex="-1"></a><span class="fu">## What if the endogenous variable is binary?</span></span>
<span id="cb17-241"><a href="#cb17-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-242"><a href="#cb17-242" aria-hidden="true" tabindex="-1"></a>The linear first stage is no longer valid --- the independence condition it needs cannot hold for a discrete endogenous variable.  The <span class="co">[</span><span class="ot">guide chapter</span><span class="co">](https://xiangao.github.io/causal_econometrics_guide/poisson-iv.html)</span> works through why, and derives the replacement: a **generalized residual** from a reduced-form probit or logit in $w_{it} = (1, z_{it}, \bar z_i)$.  What follows is the part that matters when you sit down to compute it.</span>
<span id="cb17-243"><a href="#cb17-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-244"><a href="#cb17-244" aria-hidden="true" tabindex="-1"></a>**For a logit the generalized residual is just $y_{it2} - \hat p_{it2}$.**  The generalized residual is the score of the log-likelihood with respect to the index, and for a logit that score is exactly the response residual.  So the familiar "predict the probability, then subtract" recipe *is* the generalized residual, not an approximation to it.  For a probit it is not: there the generalized residual is the inverse-Mills expression, a genuinely different variable.  In a simulated sample of 5,000 the two differ by as much as 1.59 while correlating at 0.999 --- so the subtraction recipe is exact for a logit and simply wrong for a probit, and the high correlation means the mistake will not announce itself.</span>
<span id="cb17-245"><a href="#cb17-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-246"><a href="#cb17-246" aria-hidden="true" tabindex="-1"></a>**Get the right residual out of the software.**  <span class="in">`predict`</span> on its own after a binary model returns a probability, not a residual.  The residuals it will give you are not the generalized residual either: Pearson residuals divide through by $\sqrt{\hat p(1-\hat p)}$, and deviance residuals are a different transformation again.  In the same simulation those correlate with the response residual at 0.991 and 0.995 --- close enough to look right at a glance, and the wrong variable to put in the second stage.  Compute $d - \hat p$ by hand.</span>
<span id="cb17-247"><a href="#cb17-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-248"><a href="#cb17-248" aria-hidden="true" tabindex="-1"></a>**On the name.**  This construction is filed in the literature under **correlated random effects** (CRE) --- see the [CRE chapter](more-cre.qmd) --- and that is how to find it.  The name describes the assumption, not the estimator.  What is actually computed below is a **pooled logit** with group means added as regressors.  No random effect is estimated, no variance component appears, nothing is integrated out.  It is labelled "CRE (Mundlak device)" so both names stay visible: the first tells you where to look it up, the second tells you what runs.</span>
<span id="cb17-249"><a href="#cb17-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-250"><a href="#cb17-250" aria-hidden="true" tabindex="-1"></a><span class="fu">### Several fixed effects in the first stage</span></span>
<span id="cb17-251"><a href="#cb17-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-252"><a href="#cb17-252" aria-hidden="true" tabindex="-1"></a>$w_{it} = (1, z_{it}, \bar z_i)$ is written for a single unobserved effect.  If the second stage absorbs more than one set of fixed effects --- units, years, something else --- the first stage needs the treatment in the <span class="co">[</span><span class="ot">Mundlak chapter</span><span class="co">](mundlak-device.qmd)</span>: take means over the *one* dimension you are eliminating, of everything else in the model, retained dummies included.  In practice that means unit means of the instrument and the time-varying controls, plus unit means of the year and other dummies, with those dummies themselves kept in levels.  Not one set of means per dimension --- that construction is exact only for orthogonal designs, which observational panels are not.</span>
<span id="cb17-253"><a href="#cb17-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-254"><a href="#cb17-254" aria-hidden="true" tabindex="-1"></a><span class="fu">### Why not put the dummies in the first stage?</span></span>
<span id="cb17-255"><a href="#cb17-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-256"><a href="#cb17-256" aria-hidden="true" tabindex="-1"></a>Because a logit with many thin groups is badly biased, and that is the whole reason for the Mundlak route.  The size of the problem depends on observations per group, not on the number of groups.  In a simulation with the total sample held near 12,000 and a true slope of 1, a logit with group dummies returns about 2.0 at two observations per group --- matching the known result that the fixed-effects logit slope is inflated by a factor of two in that case --- about 1.37 at four per group, 1.15 at six, 1.04 at twenty-five, and essentially the truth by a hundred.  A panel with a few thousand units and four or five observations each sits in the worst part of that range.  Year effects with hundreds of observations apiece are harmless and can simply be estimated.</span>
<span id="cb17-257"><a href="#cb17-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-258"><a href="#cb17-258" aria-hidden="true" tabindex="-1"></a>The CRE (Mundlak device) first stage is better but not unbiased: in the same simulation it ran roughly ten per cent low at small group sizes, because integrating a logit over normal heterogeneity does not give a logit.</span>
<span id="cb17-259"><a href="#cb17-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-260"><a href="#cb17-260" aria-hidden="true" tabindex="-1"></a><span class="fu">### A worked example</span></span>
<span id="cb17-261"><a href="#cb17-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-262"><a href="#cb17-262" aria-hidden="true" tabindex="-1"></a>The <span class="in">`website`</span> data does not have the shape that causes trouble.  <span class="in">`ad`</span> has 13 levels, but they are very uneven --- 128, 122, 90, 51, 44, 19, 16, 13, 8, 4, 2, 2, 1 observations --- and <span class="in">`female`</span> has 2 levels of about 250 each.  Most of the sample therefore sits in cells large enough that a logit with dummies would be fine, even though a handful of <span class="in">`ad`</span> cells are tiny.</span>
<span id="cb17-263"><a href="#cb17-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-264"><a href="#cb17-264" aria-hidden="true" tabindex="-1"></a>So this simulates something more awkward instead: a count outcome, a binary endogenous regressor, an instrument, and two thousand units with between two and six observations each.</span>
<span id="cb17-265"><a href="#cb17-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-268"><a href="#cb17-268" aria-hidden="true" tabindex="-1"></a><span class="in">```{stata}</span></span>
<span id="cb17-269"><a href="#cb17-269" aria-hidden="true" tabindex="-1"></a><span class="in">*| label: binary_cf</span></span>
<span id="cb17-270"><a href="#cb17-270" aria-hidden="true" tabindex="-1"></a><span class="in">*| echo: true</span></span>
<span id="cb17-271"><a href="#cb17-271" aria-hidden="true" tabindex="-1"></a><span class="in">*| collectcode: true</span></span>
<span id="cb17-272"><a href="#cb17-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-273"><a href="#cb17-273" aria-hidden="true" tabindex="-1"></a><span class="in">preserve</span></span>
<span id="cb17-274"><a href="#cb17-274" aria-hidden="true" tabindex="-1"></a><span class="in">clear</span></span>
<span id="cb17-275"><a href="#cb17-275" aria-hidden="true" tabindex="-1"></a><span class="in">set seed 20260731</span></span>
<span id="cb17-276"><a href="#cb17-276" aria-hidden="true" tabindex="-1"></a><span class="in">set obs 2000</span></span>
<span id="cb17-277"><a href="#cb17-277" aria-hidden="true" tabindex="-1"></a><span class="in">gen i = _n</span></span>
<span id="cb17-278"><a href="#cb17-278" aria-hidden="true" tabindex="-1"></a><span class="in">gen double ci = rnormal()*0.5</span></span>
<span id="cb17-279"><a href="#cb17-279" aria-hidden="true" tabindex="-1"></a><span class="in">gen T = 2 + int(runiform()*5)        /* unbalanced: 2-6 observations per unit */</span></span>
<span id="cb17-280"><a href="#cb17-280" aria-hidden="true" tabindex="-1"></a><span class="in">expand T</span></span>
<span id="cb17-281"><a href="#cb17-281" aria-hidden="true" tabindex="-1"></a><span class="in">bysort i: gen t = _n</span></span>
<span id="cb17-282"><a href="#cb17-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-283"><a href="#cb17-283" aria-hidden="true" tabindex="-1"></a><span class="in">gen double z = rnormal()             /* the instrument */</span></span>
<span id="cb17-284"><a href="#cb17-284" aria-hidden="true" tabindex="-1"></a><span class="in">gen double e = rnormal()</span></span>
<span id="cb17-285"><a href="#cb17-285" aria-hidden="true" tabindex="-1"></a><span class="in">gen double u = 0.8*e + rnormal()*0.6 /* correlated with e, hence the endogeneity */</span></span>
<span id="cb17-286"><a href="#cb17-286" aria-hidden="true" tabindex="-1"></a><span class="in">gen byte   d = (-0.2 + 0.9*z + ci + e &gt; 0)</span></span>
<span id="cb17-287"><a href="#cb17-287" aria-hidden="true" tabindex="-1"></a><span class="in">gen double mu = exp(0.3*d + ci + 0.5*u)</span></span>
<span id="cb17-288"><a href="#cb17-288" aria-hidden="true" tabindex="-1"></a><span class="in">gen y = rpoisson(mu)                 /* true coefficient on d is 0.3 */</span></span>
<span id="cb17-289"><a href="#cb17-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-290"><a href="#cb17-290" aria-hidden="true" tabindex="-1"></a><span class="in">* 1. naive FE Poisson, ignoring the endogeneity</span></span>
<span id="cb17-291"><a href="#cb17-291" aria-hidden="true" tabindex="-1"></a><span class="in">quietly ppmlhdfe y d, absorb(i)</span></span>
<span id="cb17-292"><a href="#cb17-292" aria-hidden="true" tabindex="-1"></a><span class="in">scalar b_naive = _b[d]</span></span>
<span id="cb17-293"><a href="#cb17-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-294"><a href="#cb17-294" aria-hidden="true" tabindex="-1"></a><span class="in">* 2. control function with a CRE (Mundlak device) logit first stage: a POOLED</span></span>
<span id="cb17-295"><a href="#cb17-295" aria-hidden="true" tabindex="-1"></a><span class="in">*    logit with the group mean of the instrument added.  No random effect is</span></span>
<span id="cb17-296"><a href="#cb17-296" aria-hidden="true" tabindex="-1"></a><span class="in">*    estimated.  For a logit the generalized residual is just d - phat.</span></span>
<span id="cb17-297"><a href="#cb17-297" aria-hidden="true" tabindex="-1"></a><span class="in">bysort i: egen double z_i = mean(z)</span></span>
<span id="cb17-298"><a href="#cb17-298" aria-hidden="true" tabindex="-1"></a><span class="in">quietly logit d z z_i</span></span>
<span id="cb17-299"><a href="#cb17-299" aria-hidden="true" tabindex="-1"></a><span class="in">predict double phat, pr</span></span>
<span id="cb17-300"><a href="#cb17-300" aria-hidden="true" tabindex="-1"></a><span class="in">gen double gr = d - phat</span></span>
<span id="cb17-301"><a href="#cb17-301" aria-hidden="true" tabindex="-1"></a><span class="in">quietly ppmlhdfe y d gr, absorb(i)</span></span>
<span id="cb17-302"><a href="#cb17-302" aria-hidden="true" tabindex="-1"></a><span class="in">scalar b_cre = _b[d]</span></span>
<span id="cb17-303"><a href="#cb17-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-304"><a href="#cb17-304" aria-hidden="true" tabindex="-1"></a><span class="in">* 3. control function with a linear first stage, unit FE absorbed exactly</span></span>
<span id="cb17-305"><a href="#cb17-305" aria-hidden="true" tabindex="-1"></a><span class="in">quietly reghdfe d z, absorb(i) resid</span></span>
<span id="cb17-306"><a href="#cb17-306" aria-hidden="true" tabindex="-1"></a><span class="in">predict double v_lin, resid</span></span>
<span id="cb17-307"><a href="#cb17-307" aria-hidden="true" tabindex="-1"></a><span class="in">quietly ppmlhdfe y d v_lin, absorb(i)</span></span>
<span id="cb17-308"><a href="#cb17-308" aria-hidden="true" tabindex="-1"></a><span class="in">scalar b_lin = _b[d]</span></span>
<span id="cb17-309"><a href="#cb17-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-310"><a href="#cb17-310" aria-hidden="true" tabindex="-1"></a><span class="in">di "true coefficient on d           = 0.300000"</span></span>
<span id="cb17-311"><a href="#cb17-311" aria-hidden="true" tabindex="-1"></a><span class="in">di "naive FE Poisson                = " %8.6f b_naive</span></span>
<span id="cb17-312"><a href="#cb17-312" aria-hidden="true" tabindex="-1"></a><span class="in">di "CF, CRE (Mundlak) logit         = " %8.6f b_cre</span></span>
<span id="cb17-313"><a href="#cb17-313" aria-hidden="true" tabindex="-1"></a><span class="in">di "CF, linear FE first stage       = " %8.6f b_lin</span></span>
<span id="cb17-314"><a href="#cb17-314" aria-hidden="true" tabindex="-1"></a><span class="in">restore</span></span>
<span id="cb17-315"><a href="#cb17-315" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-316"><a href="#cb17-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-317"><a href="#cb17-317" aria-hidden="true" tabindex="-1"></a>Against a true coefficient of 0.300000, the naive FE Poisson gives 0.747206, the CRE/Mundlak logit first stage gives 0.293829, and the linear FE first stage gives 0.277644.</span>
<span id="cb17-318"><a href="#cb17-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-319"><a href="#cb17-319" aria-hidden="true" tabindex="-1"></a>The naive estimate is inflated by about two and a half times.  Both control-function versions land close to the truth, and they agree with each other --- within 0.016 of one another, both within 0.023 of the truth.  That agreement is the point.  With a binary endogenous variable I would report both: the linear first stage rests on the numerical-equivalence result above and drops no observations, while the logit version is better specified for a binary variable but rests on an approximation the literature has not settled.  If they diverge materially, that is the most important thing you have learned, and it belongs in the write-up.</span>
<span id="cb17-320"><a href="#cb17-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-321"><a href="#cb17-321" aria-hidden="true" tabindex="-1"></a>The standard errors in that chunk are wrong, for the reason given earlier.  Bootstrap both stages together, as above.</span>
<span id="cb17-322"><a href="#cb17-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-323"><a href="#cb17-323" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb17-324"><a href="#cb17-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-325"><a href="#cb17-325" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- see-also-footer --&gt;</span></span>
<span id="cb17-326"><a href="#cb17-326" aria-hidden="true" tabindex="-1"></a>*Theory and derivations: [R](https://xiangao.github.io/causal_econometrics_guide/poisson-iv.html) · [Julia](https://xiangao.github.io/causal_econometrics_julia/poisson-iv.html).*</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->



<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions"><ul><li><a href="https://github.com/xiangao/blog_book/edit/main/poisson-iv-fe.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/xiangao/blog_book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>