<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="dcterms.date" content="2019-01-10">
<title>11&nbsp; Treatment effects and matching – Topics on econometrics and causal inference</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./ols-ate.html" rel="next">
<link href="./more-cre.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6eb2a311e0ae5a9b436ea9f7e52955e6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script>
try {
  if (window.localStorage) {
    window.localStorage.setItem("quarto-reader-mode", "false");
  }
} catch (e) {}
</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="style.css">
</head>
<body class="nav-sidebar floating fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./treatment-matching.html">Treatment Effects &amp; Matching</a></li><li class="breadcrumb-item"><a href="./treatment-matching.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Treatment effects and matching</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Topics on econometrics and causal inference</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://xiangao.github.io/" title="Xiang Ao home" class="quarto-navigation-tool px-1" aria-label="Xiang Ao home"><i class="bi bi-house-door-fill"></i></a>
    <a href="https://xiangao.github.io/books.html" title="Other books" class="quarto-navigation-tool px-1" aria-label="Other books"><i class="bi bi-book"></i></a>
    <a href="https://github.com/xiangao/blog_book/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Regression Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./interaction-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Interpreting interaction in a regression model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./interaction-nonlinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Interaction term in a non-linear model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chow-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Chow test and more</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./weights-ols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Weights in OLS in causal inference</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Marginal Effects &amp; Fixed Effects</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./marginal-effects-fe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Marginal effects in models with fixed effects</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./comparing-margins.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Comparing Marginal effects with margins command</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fixed-random-effect.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Fixed or Random Effect, or Both?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mundlak-device.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Mundlak device in fixed effect models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlated-random-effect.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Correlated Random Effect</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./more-cre.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">More on Correlated Random Effect (CRE)</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Treatment Effects &amp; Matching</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./treatment-matching.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Treatment effects and matching</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ols-ate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">When is OLS coefficient the ATE</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./matching-part1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Matching and Weighting Part 1: matching</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./weighting-part2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Matching and Weighting - Part 2: weighting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sensitivity-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Sensitivity analysis of OLS with sensemakr</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./gwg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Gender Wage Gap Analysis Using US Current Population Survey Data</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Panel Data &amp; DiD</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal-forest-panel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Causal Forest in panel data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./synthetic-control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Synthetic Control in R and Stata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tasc-time-aware-synthetic-control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Same Data, Different Estimators: A Synthetic Control Comparison</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bartik-instrument.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Bartik Instrument and Rotemberg weights</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./extended-twfe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Extended TWFE and other DiD estimators</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal-panel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Causal Panel (why DDDiD)</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Count Data &amp; Specialized Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Which count data model to use</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rare-events.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">What model to use for rare events</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./poisson-exposure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Poisson model with exposure</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./poisson-iv-fe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">IV in Fixed effect Poisson with many fixed effects</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Causal Inference Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tmle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Using machine learning for causal effect in observational study</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mediation-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Mediation analysis in R and Stata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bunching.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Endogeneity with censored variable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./g-estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">G-computation (g-formula) with time varying covariates</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./policytree.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Policy learning by policytree</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./npcausal-tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Recent causal inference tools</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./proximal-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Intro to proximal causal inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./proximal-simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Simulation on proximal causal inference with panel data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lmtp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">longitudinal modified treatment policy (LMTP)</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Advanced Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multilevel-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Doing the same multi-level model with R and stata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./likert-scale-variance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Modeling variation, not just the mean, in Likert-scale data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conjoint-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Conjoint design and analysis using R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stata-cate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Stata 19 CATE command</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./spatial-econometrics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Spatial econometrics introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal-simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Causal simulation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./frengression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Frengression and Engression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./partial-interference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Partial Interference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./power-list-experiment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Power analysis with list experiment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal-mediation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Causal mediation analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uplift.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Uplift Modeling and CATE</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./numpyro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Using Numpyro</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./equivalence-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Pre-registration, TOST, and why Bayes doesn’t let you skip the hard part</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./treatment-matching.html">Treatment Effects &amp; Matching</a></li><li class="breadcrumb-item"><a href="./treatment-matching.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Treatment effects and matching</span></a></li></ol></nav><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">
<span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Treatment effects and matching</span>
</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 10, 2019</p>
    </div>
  </div>
  
    
  </div>
  


</header><section id="treatment-effects-in-observational-studies" class="level2" data-number="11.1"><h2 data-number="11.1" class="anchored" data-anchor-id="treatment-effects-in-observational-studies">
<span class="header-section-number">11.1</span> Treatment effects in observational studies</h2>
<p>Most economic data are observational. With unobserved confounders we need instrumental variables, but instruments are hard to find and harder to justify. Under conditional independence — no unobserved confounders given the covariates — we can proceed without them.</p>
<p>Stata’s <code>teffects</code> suite implements the standard estimators under conditional independence. (The companion <code>eteffects</code> handles endogenous treatment via a control-function approach with instruments.) This chapter walks through how <code>teffects</code> works.</p>
<section id="regression-adjustment-ra" class="level3" data-number="11.1.1"><h3 data-number="11.1.1" class="anchored" data-anchor-id="regression-adjustment-ra">
<span class="header-section-number">11.1.1</span> Regression adjustment (RA)</h3>
<p>RA allows all covariate effects to differ between treatment and control — equivalent to an outcome model with treatment interacted with all covariates.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">clear</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="kw">webuse</span> bweightex</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>teffects ra (bweight prenatal1 mmarried mage fbaby) (mbsmoke)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> bweight i.mbsmoke##c.(prenatal1 mmarried mage fbaby)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>margins <span class="fu">r</span>.mbsmoke</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
. clear

. webuse bweightex
(Hypothetical birthweight data)

. teffects ra (bweight prenatal1 mmarried mage fbaby) (mbsmoke)

Iteration 0:  EE criterion = 1.223e-24  
Iteration 1:  EE criterion = 1.792e-25  

Treatment-effects estimation                    Number of obs     =         60
Estimator      : regression adjustment
Outcome model  : linear
Treatment model: none
------------------------------------------------------------------------------
             |               Robust
     bweight | Coefficient  std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
ATE          |
     mbsmoke |
    (Smoker  |
         vs  |
 Nonsmoker)  |  -389.3099   37.00882   -10.52   0.000    -461.8458   -316.7739
-------------+----------------------------------------------------------------
POmean       |
     mbsmoke |
  Nonsmoker  |   3613.769   29.97438   120.56   0.000     3555.021    3672.518
------------------------------------------------------------------------------

. reg bweight i.mbsmoke##c.(prenatal1 mmarried mage fbaby)

      Source |       SS           df       MS      Number of obs   =        60
-------------+----------------------------------   F(9, 50)        =     18.11
       Model |  1376306.34         9  152922.927   Prob &gt; F        =    0.0000
    Residual |  422241.592        50  8444.83184   R-squared       =    0.7652
-------------+----------------------------------   Adj R-squared   =    0.7230
       Total |  1798547.93        59  30483.8633   Root MSE        =    91.896

------------------------------------------------------------------------------
     bweight | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
     mbsmoke |
     Smoker  |  -32.87702   193.2827    -0.17   0.866    -421.0967    355.3426
   prenatal1 |   -23.8431   38.31014    -0.62   0.537    -100.7913    53.10507
    mmarried |  -40.39753   50.21942    -0.80   0.425    -141.2662    60.47114
        mage |    27.9537   7.671423     3.64   0.001     12.54519    43.36221
       fbaby |  -2.030497   40.76029    -0.05   0.960    -83.89995    79.83896
             |
     mbsmoke#|
 c.prenatal1 |
     Smoker  |   8.436558   56.38855     0.15   0.882    -104.8232    121.6963
             |
     mbsmoke#|
  c.mmarried |
     Smoker  |   33.92362   61.34015     0.55   0.583     -89.2817    157.1289
             |
     mbsmoke#|
      c.mage |
     Smoker  |  -15.98608   9.006494    -1.77   0.082    -34.07616    2.103995
             |
     mbsmoke#|
     c.fbaby |
     Smoker  |   14.86782   57.58771     0.26   0.797    -100.8005    130.5362
             |
       _cons |   2976.807   151.0117    19.71   0.000     2673.491    3280.123
------------------------------------------------------------------------------

. margins r.mbsmoke

Contrasts of predictive margins                             Number of obs = 60
Model VCE: OLS

Expression: Linear prediction, predict()

------------------------------------------------
             |         df           F        P&gt;F
-------------+----------------------------------
     mbsmoke |          1      116.06     0.0000
             |
 Denominator |         50
------------------------------------------------

------------------------------------------------------------------------
                       |            Delta-method
                       |   Contrast   std. err.     [95% conf. interval]
-----------------------+------------------------------------------------
               mbsmoke |
(Smoker vs Nonsmoker)  |  -389.3099   36.13675     -461.8927   -316.7271
------------------------------------------------------------------------</code></pre>
</div>
</div>
<p><code>teffects ra</code> returns the same ATE as <code>margins r.mbsmoke</code> after the interacted regression.</p>
<p>For the ATET (average treatment effect on the treated):</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">clear</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="kw">webuse</span> bweightex</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>teffects ra (bweight prenatal1 mmarried mage fbaby) (mbsmoke), atet</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> bweight i.mbsmoke##c.(prenatal1 mmarried mage fbaby)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>margins <span class="fu">r</span>.mbsmoke, subpop(mbsmoke)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
. clear

. webuse bweightex
(Hypothetical birthweight data)

. teffects ra (bweight prenatal1 mmarried mage fbaby) (mbsmoke), atet

Iteration 0:  EE criterion = 1.159e-24  
Iteration 1:  EE criterion = 5.133e-26  

Treatment-effects estimation                    Number of obs     =         60
Estimator      : regression adjustment
Outcome model  : linear
Treatment model: none
------------------------------------------------------------------------------
             |               Robust
     bweight | Coefficient  std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
ATET         |
     mbsmoke |
    (Smoker  |
         vs  |
 Nonsmoker)  |  -437.4721   53.43513    -8.19   0.000     -542.203   -332.7412
-------------+----------------------------------------------------------------
POmean       |
     mbsmoke |
  Nonsmoker  |   3693.639   53.80537    68.65   0.000     3588.182    3799.095
------------------------------------------------------------------------------

. reg bweight i.mbsmoke##c.(prenatal1 mmarried mage fbaby)

      Source |       SS           df       MS      Number of obs   =        60
-------------+----------------------------------   F(9, 50)        =     18.11
       Model |  1376306.34         9  152922.927   Prob &gt; F        =    0.0000
    Residual |  422241.592        50  8444.83184   R-squared       =    0.7652
-------------+----------------------------------   Adj R-squared   =    0.7230
       Total |  1798547.93        59  30483.8633   Root MSE        =    91.896

------------------------------------------------------------------------------
     bweight | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
     mbsmoke |
     Smoker  |  -32.87702   193.2827    -0.17   0.866    -421.0967    355.3426
   prenatal1 |   -23.8431   38.31014    -0.62   0.537    -100.7913    53.10507
    mmarried |  -40.39753   50.21942    -0.80   0.425    -141.2662    60.47114
        mage |    27.9537   7.671423     3.64   0.001     12.54519    43.36221
       fbaby |  -2.030497   40.76029    -0.05   0.960    -83.89995    79.83896
             |
     mbsmoke#|
 c.prenatal1 |
     Smoker  |   8.436558   56.38855     0.15   0.882    -104.8232    121.6963
             |
     mbsmoke#|
  c.mmarried |
     Smoker  |   33.92362   61.34015     0.55   0.583     -89.2817    157.1289
             |
     mbsmoke#|
      c.mage |
     Smoker  |  -15.98608   9.006494    -1.77   0.082    -34.07616    2.103995
             |
     mbsmoke#|
     c.fbaby |
     Smoker  |   14.86782   57.58771     0.26   0.797    -100.8005    130.5362
             |
       _cons |   2976.807   151.0117    19.71   0.000     2673.491    3280.123
------------------------------------------------------------------------------

. margins r.mbsmoke, subpop(mbsmoke)

Contrasts of predictive margins                           Number of obs   = 60
Model VCE: OLS                                            Subpop. no. obs = 30

Expression: Linear prediction, predict()

------------------------------------------------
             |         df           F        P&gt;F
-------------+----------------------------------
     mbsmoke |          1       73.30     0.0000
             |
 Denominator |         50
------------------------------------------------

------------------------------------------------------------------------
                       |            Delta-method
                       |   Contrast   std. err.     [95% conf. interval]
-----------------------+------------------------------------------------
               mbsmoke |
(Smoker vs Nonsmoker)  |  -437.4721   51.09606     -540.1015   -334.8426
------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>The ATET compares potential outcomes for the treated subpopulation, hence the <code>subpop(mbsmoke)</code> option in <code>margins</code>.</p>
</section><section id="inverse-probability-weighting-ipw" class="level3" data-number="11.1.2"><h3 data-number="11.1.2" class="anchored" data-anchor-id="inverse-probability-weighting-ipw">
<span class="header-section-number">11.1.2</span> Inverse Probability Weighting (IPW)</h3>
<p>IPW has two steps. First, estimate the treatment model (typically logit) to obtain the propensity score. Second, use inverse-probability weights to compute the outcome difference between treated and control units.</p>
<p>These steps produce consistent estimates of the effect parameters because the treatment is assumed to be independent of the potential outcomes after conditioning on the covariates.</p>
<p>We can manually conduct the two steps, but the nice thing about using Stata’s teffects is that it takes account of the noise of estimating probability in the first step when calculating standard errors in the second step.</p>
<section id="example" class="level4" data-number="11.1.2.1"><h4 data-number="11.1.2.1" class="anchored" data-anchor-id="example">
<span class="header-section-number">11.1.2.1</span> example</h4>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">clear</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="kw">webuse</span> cattaneo2</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>teffects ipw (bweight) (mbsmoke mmarried c.mage##c.mage fbaby medu, <span class="kw">probit</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="kw">probit</span> mbsmoke mmarried c.mage##c.mage fbaby medu</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="kw">predict</span> ps</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="kw">replace</span> ps = 1/ps <span class="kw">if</span> mbsmoke==1</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="kw">replace</span> ps = 1/(1-ps) <span class="kw">if</span> mbsmoke==0</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> bweight mbsmoke [<span class="kw">pweight</span>=ps]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
. clear

. webuse cattaneo2
(Excerpt from Cattaneo (2010) Journal of Econometrics 155: 138–154)

. teffects ipw (bweight) (mbsmoke mmarried c.mage##c.mage fbaby medu, probit)

Iteration 0:  EE criterion = 4.622e-21  
Iteration 1:  EE criterion = 8.453e-26  

Treatment-effects estimation                    Number of obs     =      4,642
Estimator      : inverse-probability weights
Outcome model  : weighted mean
Treatment model: probit
------------------------------------------------------------------------------
             |               Robust
     bweight | Coefficient  std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
ATE          |
     mbsmoke |
    (Smoker  |
         vs  |
 Nonsmoker)  |  -230.6886   25.81524    -8.94   0.000    -281.2856   -180.0917
-------------+----------------------------------------------------------------
POmean       |
     mbsmoke |
  Nonsmoker  |   3403.463   9.571369   355.59   0.000     3384.703    3422.222
------------------------------------------------------------------------------

. probit mbsmoke mmarried c.mage##c.mage fbaby medu

Iteration 0:  Log likelihood = -2230.7484  
Iteration 1:  Log likelihood = -2042.6734  
Iteration 2:  Log likelihood = -2040.5088  
Iteration 3:  Log likelihood = -2040.5061  
Iteration 4:  Log likelihood = -2040.5061  

Probit regression                                       Number of obs =  4,642
                                                        LR chi2(5)    = 380.48
                                                        Prob &gt; chi2   = 0.0000
Log likelihood = -2040.5061                             Pseudo R2     = 0.0853

------------------------------------------------------------------------------
     mbsmoke | Coefficient  Std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
    mmarried |  -.6484821   .0526991   -12.31   0.000    -.7517705   -.5451938
        mage |   .1744327   .0352437     4.95   0.000     .1053562    .2435092
             |
      c.mage#|
      c.mage |  -.0032559   .0006462    -5.04   0.000    -.0045224   -.0019894
             |
       fbaby |  -.2175962   .0491066    -4.43   0.000    -.3138433    -.121349
        medu |  -.0863631   .0098692    -8.75   0.000    -.1057064   -.0670198
       _cons |  -1.558255   .4511589    -3.45   0.001     -2.44251       -.674
------------------------------------------------------------------------------

. predict ps
(option pr assumed; Pr(mbsmoke))

. replace ps = 1/ps if mbsmoke==1
(864 real changes made)

. replace ps = 1/(1-ps) if mbsmoke==0
(3,778 real changes made)

. reg bweight mbsmoke [pweight=ps]
(sum of wgt is 9,193.96990537643)

Linear regression                               Number of obs     =      4,642
                                                F(1, 4640)        =      79.08
                                                Prob &gt; F          =     0.0000
                                                R-squared         =     0.0389
                                                Root MSE          =     573.36

------------------------------------------------------------------------------
             |               Robust
     bweight | Coefficient  std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
     mbsmoke |  -230.6886   25.94182    -8.89   0.000    -281.5469   -179.8303
       _cons |   3403.463   9.616992   353.90   0.000     3384.609    3422.317
------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>The manual two-step replication matches the point estimate; the only difference is the standard error (the manual version does not account for first-stage estimation noise).</p>
</section></section><section id="doubly-robust-estimators" class="level3" data-number="11.1.3"><h3 data-number="11.1.3" class="anchored" data-anchor-id="doubly-robust-estimators">
<span class="header-section-number">11.1.3</span> Doubly robust estimators</h3>
<p>RA models the outcome; IPW models the treatment assignment. Doubly-robust estimators model both, requiring only one to be correctly specified.</p>
<p>Stata implements the AIPW combination of Robins and Rotnitzky (1995) and the IPWRA combination of Wooldridge (2010).</p>
<p>The AIPW estimator augments the IPW estimator with a correction term built from the outcome model. Double robustness is best stated as a <strong>consistency</strong> property: AIPW is consistent if <em>either</em> the treatment model <em>or</em> the outcome model is correctly specified (not necessarily both). It is <em>not</em> that the correction term literally “goes to zero” when the treatment model is right and the outcome model is wrong — with a misspecified outcome model the correction term does not generally vanish. Rather, the two pieces are constructed so that the estimator’s bias cancels in the limit as long as one of the two models is right.</p>
<p>The IPWRA estimator uses IPW probability weights when performing RA. The weights do not affect the accuracy of the RA estimator if the treatment model is wrong and the outcome model is correct. The weights correct the RA estimator if the treatment model is correct and the outcome model is wrong.</p>
<p>Here we run the two commands, then manually replicate both as a two-step (“plug-in”) procedure. <code>teffects</code> estimates the treatment and outcome models jointly by GMM/ML, using the joint estimation to get standard errors that account for first-stage estimation noise; the manual two-step version below gets essentially the same point estimate but not the correct standard errors (for the same reason noted above for IPW).</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">clear</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="kw">webuse</span> cattaneo2</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>teffects ipwra (bweight mmarried mage prenatal1 fbaby)  (mbsmoke mmarried mage prenatal1 fbaby)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>teffects aipw (bweight mmarried mage prenatal1 fbaby) (mbsmoke mmarried mage prenatal1 fbaby)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
. clear

. webuse cattaneo2
(Excerpt from Cattaneo (2010) Journal of Econometrics 155: 138–154)

. teffects ipwra (bweight mmarried mage prenatal1 fbaby)  (mbsmoke mmarried mag
&gt; e prenatal1 fbaby)

Iteration 0:  EE criterion = 9.066e-22  
Iteration 1:  EE criterion = 2.902e-26  

Treatment-effects estimation                    Number of obs     =      4,642
Estimator      : IPW regression adjustment
Outcome model  : linear
Treatment model: logit
------------------------------------------------------------------------------
             |               Robust
     bweight | Coefficient  std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
ATE          |
     mbsmoke |
    (Smoker  |
         vs  |
 Nonsmoker)  |  -238.7679   24.38353    -9.79   0.000    -286.5587    -190.977
-------------+----------------------------------------------------------------
POmean       |
     mbsmoke |
  Nonsmoker  |   3402.851   9.538741   356.74   0.000     3384.155    3421.546
------------------------------------------------------------------------------

. teffects aipw (bweight mmarried mage prenatal1 fbaby) (mbsmoke mmarried mage 
&gt; prenatal1 fbaby)

Iteration 0:  EE criterion = 2.115e-22  
Iteration 1:  EE criterion = 1.343e-26  

Treatment-effects estimation                    Number of obs     =      4,642
Estimator      : augmented IPW
Outcome model  : linear by ML
Treatment model: logit
------------------------------------------------------------------------------
             |               Robust
     bweight | Coefficient  std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
ATE          |
     mbsmoke |
    (Smoker  |
         vs  |
 Nonsmoker)  |  -239.0294    24.2524    -9.86   0.000    -286.5632   -191.4955
-------------+----------------------------------------------------------------
POmean       |
     mbsmoke |
  Nonsmoker  |   3402.839   9.538926   356.73   0.000     3384.143    3421.535
------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p><strong>Manual IPWRA:</strong> first estimate the propensity score, then run <em>weighted</em> regression adjustment within each treatment arm, using the inverse probability of the <em>observed</em> treatment status as weights:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">clear</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="kw">webuse</span> cattaneo2</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="kw">logit</span> mbsmoke mmarried mage prenatal1 fbaby</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="kw">predict</span> ps</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> wgt1 = mbsmoke/ps</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> wgt0 = (1-mbsmoke)/(1-ps)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> bweight mmarried mage prenatal1 fbaby <span class="kw">if</span> mbsmoke==1 [<span class="kw">pweight</span>=wgt1]</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="kw">predict</span> mu1_ipwra</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> bweight mmarried mage prenatal1 fbaby <span class="kw">if</span> mbsmoke==0 [<span class="kw">pweight</span>=wgt0]</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="kw">predict</span> mu0_ipwra</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> tau_ipwra_i = mu1_ipwra - mu0_ipwra</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="kw">sum</span> tau_ipwra_i</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
. clear

. webuse cattaneo2
(Excerpt from Cattaneo (2010) Journal of Econometrics 155: 138–154)

. logit mbsmoke mmarried mage prenatal1 fbaby

Iteration 0:  Log likelihood = -2230.7484  
Iteration 1:  Log likelihood = -2089.7838  
Iteration 2:  Log likelihood = -2082.3958  
Iteration 3:  Log likelihood = -2082.3879  
Iteration 4:  Log likelihood = -2082.3879  

Logistic regression                                     Number of obs =  4,642
                                                        LR chi2(4)    = 296.72
                                                        Prob &gt; chi2   = 0.0000
Log likelihood = -2082.3879                             Pseudo R2     = 0.0665

------------------------------------------------------------------------------
     mbsmoke | Coefficient  Std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
    mmarried |   -1.10666    .091279   -12.12   0.000    -1.285564   -.9277569
        mage |  -.0187894   .0082217    -2.29   0.022    -.0349036   -.0026751
   prenatal1 |  -.2721103   .0943067    -2.89   0.004    -.4569481   -.0872725
       fbaby |  -.5428134   .0864561    -6.28   0.000    -.7122642   -.3733625
       _cons |   .1297324   .2095812     0.62   0.536    -.2810391     .540504
------------------------------------------------------------------------------

. predict ps
(option pr assumed; Pr(mbsmoke))

. 
. gen wgt1 = mbsmoke/ps

. gen wgt0 = (1-mbsmoke)/(1-ps)

. reg bweight mmarried mage prenatal1 fbaby if mbsmoke==1 [pweight=wgt1]
(sum of wgt is 4,620.9067401886)

Linear regression                               Number of obs     =        864
                                                F(4, 859)         =       3.12
                                                Prob &gt; F          =     0.0145
                                                R-squared         =     0.0142
                                                Root MSE          =     563.01

------------------------------------------------------------------------------
             |               Robust
     bweight | Coefficient  std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
    mmarried |   130.5978   39.90558     3.27   0.001     52.27399    208.9217
        mage |  -6.495147    4.95637    -1.31   0.190    -16.22316    3.232866
   prenatal1 |   23.29089   40.04843     0.58   0.561    -55.31335    101.8951
       fbaby |   45.19338   48.48447     0.93   0.352    -49.96852    140.3553
       _cons |   3206.397   126.7646    25.29   0.000     2957.592    3455.202
------------------------------------------------------------------------------

. predict mu1_ipwra
(option xb assumed; fitted values)

. reg bweight mmarried mage prenatal1 fbaby if mbsmoke==0 [pweight=wgt0]
(sum of wgt is 4,643.79376959801)

Linear regression                               Number of obs     =      3,778
                                                F(4, 3773)        =      26.89
                                                Prob &gt; F          =     0.0000
                                                R-squared         =     0.0336
                                                Root MSE          =     567.52

------------------------------------------------------------------------------
             |               Robust
     bweight | Coefficient  std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
    mmarried |   160.9954   26.87191     5.99   0.000     108.3105    213.6803
        mage |   3.061463   2.181356     1.40   0.161    -1.215289    7.338214
   prenatal1 |    62.4539   28.28456     2.21   0.027      6.99938    117.9084
       fbaby |  -67.38469   20.29791    -3.32   0.001    -107.1806   -27.58876
       _cons |   3188.522   56.19956    56.74   0.000     3078.338    3298.707
------------------------------------------------------------------------------

. predict mu0_ipwra
(option xb assumed; fitted values)

. gen tau_ipwra_i = mu1_ipwra - mu0_ipwra

. sum tau_ipwra_i

    Variable |        Obs        Mean    Std. dev.       Min        Max
-------------+---------------------------------------------------------
 tau_ipwra_i |      4,642   -238.7679    97.94189  -481.7334   6.216553</code></pre>
</div>
</div>
<p>The mean of <code>tau_ipwra_i</code> matches <code>teffects ipwra</code>’s ATE.</p>
<p><strong>Manual AIPW:</strong> estimate outcome models <span class="math inline">\(\hat\mu_1(X)\)</span>, <span class="math inline">\(\hat\mu_0(X)\)</span> (unweighted, one per arm) and the propensity score <span class="math inline">\(\hat p(X)\)</span>, then combine via the augmented-IPW formula <span id="eq-treatment-matching-1"><span class="math display">\[ \hat\tau_{i}^{aipw} = D_i\frac{Y_i-\hat\mu_1(X_i)}{\hat p(X_i)} + \hat\mu_1(X_i) - (1-D_i)\frac{Y_i-\hat\mu_0(X_i)}{1-\hat p(X_i)} - \hat\mu_0(X_i)  \tag{11.1}\]</span></span></p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="kw">clear</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="kw">webuse</span> cattaneo2</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="kw">logit</span> mbsmoke mmarried mage prenatal1 fbaby</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="kw">predict</span> ps</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> bweight mmarried mage prenatal1 fbaby <span class="kw">if</span> mbsmoke==1</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="kw">predict</span> mu1_aipw</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> bweight mmarried mage prenatal1 fbaby <span class="kw">if</span> mbsmoke==0</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="kw">predict</span> mu0_aipw</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> aipw_i = mbsmoke*(bweight-mu1_aipw)/ps + mu1_aipw - (1-mbsmoke)*(bweight-mu0_aipw)/(1-ps) - mu0_aipw</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="kw">sum</span> aipw_i</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
. clear

. webuse cattaneo2
(Excerpt from Cattaneo (2010) Journal of Econometrics 155: 138–154)

. logit mbsmoke mmarried mage prenatal1 fbaby

Iteration 0:  Log likelihood = -2230.7484  
Iteration 1:  Log likelihood = -2089.7838  
Iteration 2:  Log likelihood = -2082.3958  
Iteration 3:  Log likelihood = -2082.3879  
Iteration 4:  Log likelihood = -2082.3879  

Logistic regression                                     Number of obs =  4,642
                                                        LR chi2(4)    = 296.72
                                                        Prob &gt; chi2   = 0.0000
Log likelihood = -2082.3879                             Pseudo R2     = 0.0665

------------------------------------------------------------------------------
     mbsmoke | Coefficient  Std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
    mmarried |   -1.10666    .091279   -12.12   0.000    -1.285564   -.9277569
        mage |  -.0187894   .0082217    -2.29   0.022    -.0349036   -.0026751
   prenatal1 |  -.2721103   .0943067    -2.89   0.004    -.4569481   -.0872725
       fbaby |  -.5428134   .0864561    -6.28   0.000    -.7122642   -.3733625
       _cons |   .1297324   .2095812     0.62   0.536    -.2810391     .540504
------------------------------------------------------------------------------

. predict ps
(option pr assumed; Pr(mbsmoke))

. 
. reg bweight mmarried mage prenatal1 fbaby if mbsmoke==1

      Source |       SS           df       MS      Number of obs   =       864
-------------+----------------------------------   F(4, 859)       =      3.69
       Model |  4586519.21         4   1146629.8   Prob &gt; F        =    0.0055
    Residual |   266914157       859  310726.609   R-squared       =    0.0169
-------------+----------------------------------   Adj R-squared   =    0.0123
       Total |   271500676       863  314601.015   Root MSE        =    557.43

------------------------------------------------------------------------------
     bweight | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
    mmarried |   133.6617   41.33023     3.23   0.001     52.54164    214.7818
        mage |  -7.370881   3.983409    -1.85   0.065    -15.18924    .4474735
   prenatal1 |   25.11133   43.64639     0.58   0.565    -60.55473    110.7774
       fbaby |   41.43991   41.82146     0.99   0.322     -40.6443    123.5241
       _cons |   3227.169   102.3392    31.53   0.000     3026.305    3428.033
------------------------------------------------------------------------------

. predict mu1_aipw
(option xb assumed; fitted values)

. reg bweight mmarried mage prenatal1 fbaby if mbsmoke==0

      Source |       SS           df       MS      Number of obs   =     3,778
-------------+----------------------------------   F(4, 3773)      =     30.00
       Model |    37916015         4  9479003.74   Prob &gt; F        =    0.0000
    Residual |  1.1922e+09     3,773  315979.752   R-squared       =    0.0308
-------------+----------------------------------   Adj R-squared   =    0.0298
       Total |  1.2301e+09     3,777  325683.776   Root MSE        =    562.12

------------------------------------------------------------------------------
     bweight | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
    mmarried |   160.9513   24.55483     6.55   0.000     112.8092    209.0933
        mage |   2.546828   1.935504     1.32   0.188    -1.247908    6.341564
   prenatal1 |   64.40859   25.83668     2.49   0.013     13.75338    115.0638
       fbaby |   -71.3286    19.4895    -3.66   0.000    -109.5396   -33.11763
       _cons |   3202.746   51.20076    62.55   0.000     3102.362     3303.13
------------------------------------------------------------------------------

. predict mu0_aipw
(option xb assumed; fitted values)

. gen aipw_i = mbsmoke*(bweight-mu1_aipw)/ps + mu1_aipw - (1-mbsmoke)*(bweight-
&gt; mu0_aipw)/(1-ps) - mu0_aipw

. sum aipw_i

    Variable |        Obs        Mean    Std. dev.       Min        Max
-------------+---------------------------------------------------------
      aipw_i |      4,642   -239.0294     1618.64  -29389.38   16313.36</code></pre>
</div>
</div>
<p>The mean of <code>aipw_i</code> is close to <code>teffects aipw</code>’s ATE (small differences are expected: <code>teffects</code> estimates the treatment and outcome models jointly by ML, while this is a two-step plug-in version).</p>
</section></section><section id="matching" class="level2" data-number="11.2"><h2 data-number="11.2" class="anchored" data-anchor-id="matching">
<span class="header-section-number">11.2</span> Matching</h2>
<p>Matching does not solve the endogeneity problem. It addresses selection on observables only; with unobserved confounders it does not help.</p>
<p>What matching does is balance the covariate distributions across treatment and control groups. Regression does this too, but matching makes the lack of overlap visible — a plain regression can extrapolate far outside the support without warning. Running regression on a matched sample combines the strengths of both approaches.</p>
<p>Below we cover three matching methods in Stata: propensity score matching, nearest-neighbor matching, and coarsened exact matching.</p>
<section id="propensity-score-matching" class="level3" data-number="11.2.1"><h3 data-number="11.2.1" class="anchored" data-anchor-id="propensity-score-matching">
<span class="header-section-number">11.2.1</span> Propensity score matching</h3>
<p>Exact matching on all covariates is ideal but infeasible in high dimensions. Rosenbaum and Rubin (1983) showed that the propensity score provides a scalar sufficient statistic, reducing the matching problem to one dimension.</p>
<p>Stata’s <code>teffects psmatch</code> and <code>psmatch2</code> both estimate the propensity score, match, and compute the treatment effect with correct standard errors in one step.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="kw">clear</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="kw">webuse</span> cattaneo2</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>teffects psmatch (bweight) (mbsmoke mmarried c.mage##c.mage fbaby medu), atet</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>psmatch2 mbsmoke mmarried c.mage##c.mage fbaby medu, <span class="kw">logit</span> ties</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> bweight mbsmoke   [<span class="kw">aweight</span>=_weight]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
. clear

. webuse cattaneo2
(Excerpt from Cattaneo (2010) Journal of Econometrics 155: 138–154)

. teffects psmatch (bweight) (mbsmoke mmarried c.mage##c.mage fbaby medu), atet

Treatment-effects estimation                   Number of obs      =      4,642
Estimator      : propensity-score matching     Matches: requested =          1
Outcome model  : matching                                     min =          1
Treatment model: logit                                        max =         74
------------------------------------------------------------------------------
             |              AI robust
     bweight | Coefficient  std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
ATET         |
     mbsmoke |
    (Smoker  |
         vs  |
 Nonsmoker)  |  -236.7848   26.57789    -8.91   0.000    -288.8765    -184.693
------------------------------------------------------------------------------

. psmatch2 mbsmoke mmarried c.mage##c.mage fbaby medu, logit ties

Logistic regression                                     Number of obs =  4,642
                                                        LR chi2(5)    = 375.00
                                                        Prob &gt; chi2   = 0.0000
Log likelihood = -2043.2504                             Pseudo R2     = 0.0841

------------------------------------------------------------------------------
     mbsmoke | Coefficient  Std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
    mmarried |  -1.145706   .0918962   -12.47   0.000     -1.32582    -.965593
        mage |    .321518   .0638472     5.04   0.000     .1963798    .4466563
             |
      c.mage#|
      c.mage |  -.0060368   .0011849    -5.09   0.000    -.0083592   -.0037144
             |
       fbaby |  -.3864258   .0880445    -4.39   0.000    -.5589898   -.2138618
        medu |  -.1420833   .0173215    -8.20   0.000    -.1760328   -.1081338
       _cons |  -2.950915   .8102504    -3.64   0.000    -4.538976   -1.362853
------------------------------------------------------------------------------

. reg bweight mbsmoke   [aweight=_weight]
(sum of wgt is 1,728)

      Source |       SS           df       MS      Number of obs   =     3,671
-------------+----------------------------------   F(1, 3669)      =    151.87
       Model |    51455506         1    51455506   Prob &gt; F        =    0.0000
    Residual |  1.2431e+09     3,669  338808.237   R-squared       =    0.0397
-------------+----------------------------------   Adj R-squared   =    0.0395
       Total |  1.2945e+09     3,670  352736.492   Root MSE        =    582.07

------------------------------------------------------------------------------
     bweight | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
     mbsmoke |  -236.7848   19.21387   -12.32   0.000    -274.4557   -199.1138
       _cons |   3374.444   13.58626   248.37   0.000     3347.807    3401.082
------------------------------------------------------------------------------

. </code></pre>
</div>
</div>
<p><code>teffects psmatch</code> gives the ATT of smoking on birthweight. The manual replication uses <code>psmatch2</code> with <code>logit</code> and <code>ties</code> (by default <code>teffects</code> includes all tied matches, while <code>psmatch2</code> keeps only one), then runs a weighted regression. Point estimates match; standard errors should be taken from <code>teffects</code>.</p>
</section><section id="nearest-neighbor-matching" class="level3" data-number="11.2.2"><h3 data-number="11.2.2" class="anchored" data-anchor-id="nearest-neighbor-matching">
<span class="header-section-number">11.2.2</span> Nearest neighbor matching</h3>
<p><code>teffects nnmatch</code> uses Mahalanobis distance by default and can also enforce exact matching on discrete covariates. It is nonparametric.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="kw">clear</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="kw">webuse</span> cattaneo2</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>teffects nnmatch  (bweight mmarried mage fbaby medu) (mbsmoke) , atet</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>teffects psmatch (bweight) (mbsmoke mmarried mage fbaby medu), atet</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
. clear

. webuse cattaneo2
(Excerpt from Cattaneo (2010) Journal of Econometrics 155: 138–154)

. teffects nnmatch  (bweight mmarried mage fbaby medu) (mbsmoke) , atet

Treatment-effects estimation                   Number of obs      =      4,642
Estimator      : nearest-neighbor matching     Matches: requested =          1
Outcome model  : matching                                     min =          1
Distance metric: Mahalanobis                                  max =         74
------------------------------------------------------------------------------
             |              AI robust
     bweight | Coefficient  std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
ATET         |
     mbsmoke |
    (Smoker  |
         vs  |
 Nonsmoker)  |  -239.2433   25.68524    -9.31   0.000    -289.5854   -188.9011
------------------------------------------------------------------------------

. teffects psmatch (bweight) (mbsmoke mmarried mage fbaby medu), atet

Treatment-effects estimation                   Number of obs      =      4,642
Estimator      : propensity-score matching     Matches: requested =          1
Outcome model  : matching                                     min =          1
Treatment model: logit                                        max =         74
------------------------------------------------------------------------------
             |              AI robust
     bweight | Coefficient  std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
ATET         |
     mbsmoke |
    (Smoker  |
         vs  |
 Nonsmoker)  |   -245.711   26.38675    -9.31   0.000    -297.4281   -193.9939
------------------------------------------------------------------------------

. </code></pre>
</div>
</div>
<p>Note the specification difference: <code>nnmatch</code> lists covariates in the outcome parentheses, <code>psmatch</code> lists them in the treatment parentheses.</p>
</section><section id="coarsened-exact-matching-cem" class="level3" data-number="11.2.3"><h3 data-number="11.2.3" class="anchored" data-anchor-id="coarsened-exact-matching-cem">
<span class="header-section-number">11.2.3</span> Coarsened Exact Matching (CEM)</h3>
<p>CEM is available as a separate Stata package.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="kw">clear</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="kw">webuse</span> cattaneo2</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>cem  mmarried mage fbaby medu, treatment(mbsmoke)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> bweight mbsmoke   [<span class="kw">aweight</span>=cem_weights]</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>* Note: cem creates the <span class="kw">variable</span> <span class="st">"cem_weights"</span> (<span class="fu">plural</span>). We spell it out</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>* <span class="kw">in</span> full here rather than relying <span class="kw">on</span> Stata's automatic <span class="kw">variable</span>-<span class="bn">name</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>* abbreviation matching, to <span class="kw">keep</span> the reference unambiguous.</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
. clear

. webuse cattaneo2
(Excerpt from Cattaneo (2010) Journal of Econometrics 155: 138–154)

. cem  mmarried mage fbaby medu, treatment(mbsmoke)

Matching Summary:
-----------------
Number of strata: 274
Number of matched strata: 135

              0     1
      All  3778   864
  Matched  3421   827
Unmatched   357    37


Multivariate L1 distance: .25424705

Univariate imbalance:

               L1     mean      min      25%      50%      75%      max
mmarried  6.4e-15  8.4e-15        0        0        0        0        0
    mage   .04955  -.00887        1        0        1        0       -2
   fbaby  6.1e-15  6.1e-15        0        0        0        0        0
    medu   .03809  -.03316        0        0        0        0        0

. reg bweight mbsmoke   [aweight=cem_weights]
(sum of wgt is 4,248.00000000005)

      Source |       SS           df       MS      Number of obs   =     4,248
-------------+----------------------------------   F(1, 4246)      =    121.12
       Model |  40566772.9         1  40566772.9   Prob &gt; F        =    0.0000
    Residual |  1.4221e+09     4,246  334928.257   R-squared       =    0.0277
-------------+----------------------------------   Adj R-squared   =    0.0275
       Total |  1.4627e+09     4,247   344401.26   Root MSE        =    578.73

------------------------------------------------------------------------------
     bweight | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
     mbsmoke |  -246.8017   22.42533   -11.01   0.000    -290.7671   -202.8364
       _cons |   3383.394   9.894625   341.94   0.000     3363.996    3402.793
------------------------------------------------------------------------------

. * Note: cem creates the variable "cem_weights" (plural). We spell it out
. * in full here rather than relying on Stata's automatic variable-name
. * abbreviation matching, to keep the reference unambiguous.
. </code></pre>
</div>
</div>
<p>CEM creates exact-match strata on coarsened covariates and generates weights for the final regression. The standard errors do not account for the matching step.</p>
</section></section><section id="modern-matching-in-r-balance-diagnostics-and-entropy-weighting" class="level2" data-number="11.3"><h2 data-number="11.3" class="anchored" data-anchor-id="modern-matching-in-r-balance-diagnostics-and-entropy-weighting">
<span class="header-section-number">11.3</span> Modern matching in R: balance diagnostics and entropy weighting</h2>
<p>The 2019 vintage of this chapter used Stata’s <code>teffects</code> throughout. R’s <code>MatchIt</code> and <code>WeightIt</code> packages have since become the standard for matching workflows, and <code>cobalt</code> provides publication-quality balance tables and plots that are now expected in applied papers.</p>
<section id="balance-checking-with-cobalt" class="level3" data-number="11.3.1"><h3 data-number="11.3.1" class="anchored" data-anchor-id="balance-checking-with-cobalt">
<span class="header-section-number">11.3.1</span> Balance checking with cobalt</h3>
<p>After any matching or weighting step, always inspect covariate balance. <code>cobalt</code>’s <code><a href="https://ngreifer.github.io/cobalt/reference/bal.tab.html">bal.tab()</a></code> and <code><a href="https://ngreifer.github.io/cobalt/reference/love.plot.html">love.plot()</a></code> are the go-to tools:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://kosukeimai.github.io/MatchIt/">MatchIt</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ngreifer.github.io/cobalt/">cobalt</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Propensity score matching on the lalonde data</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"lalonde"</span>, package <span class="op">=</span> <span class="st">"MatchIt"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">m_out</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://kosukeimai.github.io/MatchIt/reference/matchit.html">matchit</a></span><span class="op">(</span><span class="va">treat</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">educ</span> <span class="op">+</span> <span class="va">race</span> <span class="op">+</span> <span class="va">married</span> <span class="op">+</span> <span class="va">nodegree</span> <span class="op">+</span></span>
<span>                   <span class="va">re74</span> <span class="op">+</span> <span class="va">re75</span>,</span>
<span>                 data <span class="op">=</span> <span class="va">lalonde</span>, method <span class="op">=</span> <span class="st">"nearest"</span>, distance <span class="op">=</span> <span class="st">"glm"</span>,</span>
<span>                 ratio <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Balance table: standardized mean differences before and after matching</span></span>
<span><span class="fu"><a href="https://ngreifer.github.io/cobalt/reference/bal.tab.html">bal.tab</a></span><span class="op">(</span><span class="va">m_out</span>, stats <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"mean.diffs"</span>, <span class="st">"variance.ratios"</span><span class="op">)</span>, thresholds <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>m <span class="op">=</span> <span class="fl">0.1</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Balance Measures
                Type Diff.Adj        M.Threshold V.Ratio.Adj
distance    Distance   0.9739                         0.7566
age          Contin.   0.0718     Balanced, &lt;0.1      0.4568
educ         Contin.  -0.1290 Not Balanced, &gt;0.1      0.5721
race_black    Binary   0.3730 Not Balanced, &gt;0.1           .
race_hispan   Binary  -0.1568 Not Balanced, &gt;0.1           .
race_white    Binary  -0.2162 Not Balanced, &gt;0.1           .
married       Binary  -0.0216     Balanced, &lt;0.1           .
nodegree      Binary   0.0703     Balanced, &lt;0.1           .
re74         Contin.  -0.0505     Balanced, &lt;0.1      1.3289
re75         Contin.  -0.0257     Balanced, &lt;0.1      1.4956

Balance tally for mean differences
                   count
Balanced, &lt;0.1         5
Not Balanced, &gt;0.1     4

Variable with the greatest mean difference
   Variable Diff.Adj        M.Threshold
 race_black    0.373 Not Balanced, &gt;0.1

Sample sizes
          Control Treated
All           429     185
Matched       185     185
Unmatched     244       0</code></pre>
</div>
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Love plot: visualize balance improvement</span></span>
<span><span class="fu"><a href="https://ngreifer.github.io/cobalt/reference/love.plot.html">love.plot</a></span><span class="op">(</span><span class="va">m_out</span>, stats <span class="op">=</span> <span class="st">"mean.diffs"</span>, threshold <span class="op">=</span> <span class="fl">0.1</span>,</span>
<span>          abs <span class="op">=</span> <span class="cn">TRUE</span>, var.order <span class="op">=</span> <span class="st">"unadjusted"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="treatment-matching_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The love plot shows each covariate’s standardized mean difference (SMD) before matching (open circles) and after (filled circles). The vertical line at SMD = 0.1 is the conventional threshold for “balanced.” If post-matching points cross the line, the matching is not improving balance and a different specification is needed.</p>
<p>That is exactly what happens here, which is why it is worth running the diagnostic rather than assuming. 1:1 nearest-neighbour matching on the propensity score leaves four of the nine covariates <em>above</em> the 0.1 threshold, <code>race</code> worst of all (an adjusted SMD of 0.37 for the black indicator), while discarding 244 of the 429 controls. Matching on a propensity score balances the score, not necessarily the covariates that went into it.</p>
</section><section id="entropy-balancing" class="level3" data-number="11.3.2"><h3 data-number="11.3.2" class="anchored" data-anchor-id="entropy-balancing">
<span class="header-section-number">11.3.2</span> Entropy balancing</h3>
<p>Propensity score matching discards unmatched units and can reduce effective sample size substantially. <strong>Entropy balancing</strong> (Hainmueller 2012) keeps all units and reweights the control group so that weighted covariate moments exactly match the treatment group — without discarding anyone.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ngreifer.github.io/WeightIt/">WeightIt</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ngreifer.github.io/cobalt/">cobalt</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Entropy balancing: exact balance on means, variances, and covariances</span></span>
<span><span class="va">w_out</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ngreifer.github.io/WeightIt/reference/weightit.html">weightit</a></span><span class="op">(</span><span class="va">treat</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">educ</span> <span class="op">+</span> <span class="va">race</span> <span class="op">+</span> <span class="va">married</span> <span class="op">+</span> <span class="va">nodegree</span> <span class="op">+</span></span>
<span>                    <span class="va">re74</span> <span class="op">+</span> <span class="va">re75</span>,</span>
<span>                  data <span class="op">=</span> <span class="va">lalonde</span>, method <span class="op">=</span> <span class="st">"ebal"</span>, estimand <span class="op">=</span> <span class="st">"ATT"</span>,</span>
<span>                  moments <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>   <span class="co"># moments=1: balance means only</span></span>
<span>                                 <span class="co"># moments=2: balance means + variances</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">w_out</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>                  Summary of weights

- Weight ranges:

          Min                                 Max
treated 1.           ||                     1.   
control 0.008 |---------------------------| 4.062

- Units with the 5 most extreme weights by group:
                                                
            NSW5    NSW4    NSW3    NSW2    NSW1
 treated       1       1       1       1       1
         PSID423 PSID196 PSID412 PSID118 PSID226
 control   3.073   3.235    3.45   3.897   4.062

- Weight statistics:

        Coef of Var   MAD Entropy # Zeros
treated       0.    0.      0.          0
control       1.834 1.287   1.101       0

- Effective Sample Sizes:

           Control Treated
Unweighted  429.       185
Weighted     98.46     185</code></pre>
</div>
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Check balance</span></span>
<span><span class="fu"><a href="https://ngreifer.github.io/cobalt/reference/bal.tab.html">bal.tab</a></span><span class="op">(</span><span class="va">w_out</span>, stats <span class="op">=</span> <span class="st">"mean.diffs"</span>, thresholds <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>m <span class="op">=</span> <span class="fl">0.1</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Balance Measures
               Type Diff.Adj    M.Threshold
age         Contin.       -0 Balanced, &lt;0.1
educ        Contin.       -0 Balanced, &lt;0.1
race_black   Binary        0 Balanced, &lt;0.1
race_hispan  Binary        0 Balanced, &lt;0.1
race_white   Binary       -0 Balanced, &lt;0.1
married      Binary       -0 Balanced, &lt;0.1
nodegree     Binary        0 Balanced, &lt;0.1
re74        Contin.       -0 Balanced, &lt;0.1
re75        Contin.       -0 Balanced, &lt;0.1

Balance tally for mean differences
                   count
Balanced, &lt;0.1         9
Not Balanced, &gt;0.1     0

Variable with the greatest mean difference
 Variable Diff.Adj    M.Threshold
     re74       -0 Balanced, &lt;0.1

Effective sample sizes
           Control Treated
Unadjusted  429.       185
Adjusted     98.46     185</code></pre>
</div>
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ngreifer.github.io/cobalt/reference/love.plot.html">love.plot</a></span><span class="op">(</span><span class="va">w_out</span>, threshold <span class="op">=</span> <span class="fl">0.1</span>, abs <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="treatment-matching_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Weighted outcome regression</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">lmtest</span><span class="op">)</span>; <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://zeileis.codeberg.page/sandwich/">sandwich</a></span><span class="op">)</span></span>
<span><span class="va">m_eb</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">re78</span> <span class="op">~</span> <span class="va">treat</span> <span class="op">+</span> <span class="va">age</span> <span class="op">+</span> <span class="va">educ</span> <span class="op">+</span> <span class="va">race</span> <span class="op">+</span> <span class="va">married</span> <span class="op">+</span> <span class="va">nodegree</span> <span class="op">+</span></span>
<span>             <span class="va">re74</span> <span class="op">+</span> <span class="va">re75</span>,</span>
<span>           data <span class="op">=</span> <span class="va">lalonde</span>, weights <span class="op">=</span> <span class="va">w_out</span><span class="op">$</span><span class="va">weights</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/lmtest/man/coeftest.html">coeftest</a></span><span class="op">(</span><span class="va">m_eb</span>, vcov <span class="op">=</span> <span class="fu"><a href="https://zeileis.codeberg.page/sandwich/reference/vcovHC.html">vcovHC</a></span><span class="op">(</span><span class="va">m_eb</span>, type <span class="op">=</span> <span class="st">"HC3"</span><span class="op">)</span><span class="op">)</span><span class="op">[</span><span class="st">"treat"</span>, <span class="op">]</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>    Estimate   Std. Error      t value     Pr(&gt;|t|) 
1273.2618139  820.1848528    1.5524083    0.1210883 </code></pre>
</div>
</div>
<p>Entropy balancing delivers on its promise here: the largest absolute standardized mean difference after weighting is <strong>exactly zero</strong>, since the weights are chosen to satisfy the mean-balance constraints as equalities. All 429 controls are retained.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead><tr class="header">
<th>Method</th>
<th>Pros</th>
<th>Cons</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>PSM (nearest neighbor)</td>
<td>Intuitive; respects overlap</td>
<td>Discards units; balance not guaranteed</td>
</tr>
<tr class="even">
<td>CEM</td>
<td>Exact balance in bins</td>
<td>Requires discretizing continuous vars</td>
</tr>
<tr class="odd">
<td>Entropy balancing</td>
<td>Exact mean balance; keeps all units</td>
<td>Weights can be extreme; no variance balance by default</td>
</tr>
<tr class="even">
<td>IPW (logistic)</td>
<td>Simple; relies only on the treatment model</td>
<td>Not doubly robust on its own; extreme weights if overlap is poor</td>
</tr>
<tr class="odd">
<td>AIPW / IPWRA</td>
<td>Doubly robust: consistent if <em>either</em> the treatment or outcome model is correct</td>
<td>Needs both models specified; more moving parts</td>
</tr>
</tbody>
</table>
<p>For most applications, entropy balancing or IPW with trimmed weights (via <code>WeightIt</code>’s <code><a href="https://ngreifer.github.io/WeightIt/reference/trim.html">trim()</a></code>) is preferred over PSM: better effective sample size, guaranteed balance, and easy integration with doubly-robust estimators.</p>
<p>See also the <a href="./weighting-part2.html">weighting chapter</a> for IPW estimators and the <a href="./ols-ate.html">OLS-ATE chapter</a> for regression-based approaches.</p>
<hr>
<!-- see-also-footer --><p><em>Systematic treatment: <a href="https://xiangao.github.io/causal_econometrics_guide/matching.html">R</a> · <a href="https://xiangao.github.io/causal_econometrics_julia/matching.html">Julia</a>.</em></p>


<!-- -->

</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/xiangao\.github\.io\/blog_book\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./more-cre.html" class="pagination-link" aria-label="More on Correlated Random Effect (CRE)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">More on Correlated Random Effect (CRE)</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./ols-ate.html" class="pagination-link" aria-label="When is OLS coefficient the ATE">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">When is OLS coefficient the ATE</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb29" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Treatment effects and matching"</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2019-01-10"</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="fu">## Treatment effects in observational studies</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>Most economic data are observational. With unobserved confounders we need instrumental variables, but instruments are hard to find and harder to justify. Under conditional independence — no unobserved confounders given the covariates — we can proceed without them.</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>Stata's <span class="in">`teffects`</span> suite implements the standard estimators under conditional independence. (The companion <span class="in">`eteffects`</span> handles endogenous treatment via a control-function approach with instruments.) This chapter walks through how <span class="in">`teffects`</span> works.</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="fu">### Regression adjustment (RA)</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>RA allows all covariate effects to differ between treatment and control — equivalent to an outcome model with treatment interacted with all covariates.</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: stata-chunk1</span></span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a><span class="co">#| engine: 'stata'</span></span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a><span class="co">#| engine.path: '/usr/local/bin/stata'</span></span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a><span class="co">#| cache: true</span></span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a>clear</span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a>webuse bweightex</span>
<span id="cb29-27"><a href="#cb29-27" aria-hidden="true" tabindex="-1"></a>teffects <span class="fu">ra</span> (bweight prenatal1 mmarried mage fbaby) (mbsmoke)</span>
<span id="cb29-28"><a href="#cb29-28" aria-hidden="true" tabindex="-1"></a>reg bweight i.mbsmoke<span class="do">##c.(prenatal1 mmarried mage fbaby)</span></span>
<span id="cb29-29"><a href="#cb29-29" aria-hidden="true" tabindex="-1"></a>margins r.mbsmoke</span>
<span id="cb29-30"><a href="#cb29-30" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-31"><a href="#cb29-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-32"><a href="#cb29-32" aria-hidden="true" tabindex="-1"></a><span class="in">`teffects ra`</span> returns the same ATE as <span class="in">`margins r.mbsmoke`</span> after the interacted regression.</span>
<span id="cb29-33"><a href="#cb29-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-34"><a href="#cb29-34" aria-hidden="true" tabindex="-1"></a>For the ATET (average treatment effect on the treated):</span>
<span id="cb29-35"><a href="#cb29-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-38"><a href="#cb29-38" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-39"><a href="#cb29-39" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: stata-chunk2</span></span>
<span id="cb29-40"><a href="#cb29-40" aria-hidden="true" tabindex="-1"></a><span class="co">#| engine: 'stata'</span></span>
<span id="cb29-41"><a href="#cb29-41" aria-hidden="true" tabindex="-1"></a><span class="co">#| engine.path: '/usr/local/bin/stata'</span></span>
<span id="cb29-42"><a href="#cb29-42" aria-hidden="true" tabindex="-1"></a><span class="co">#| cache: true</span></span>
<span id="cb29-43"><a href="#cb29-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-44"><a href="#cb29-44" aria-hidden="true" tabindex="-1"></a>clear</span>
<span id="cb29-45"><a href="#cb29-45" aria-hidden="true" tabindex="-1"></a>webuse bweightex</span>
<span id="cb29-46"><a href="#cb29-46" aria-hidden="true" tabindex="-1"></a>teffects <span class="fu">ra</span> (bweight prenatal1 mmarried mage fbaby) (mbsmoke), atet</span>
<span id="cb29-47"><a href="#cb29-47" aria-hidden="true" tabindex="-1"></a>reg bweight i.mbsmoke<span class="do">##c.(prenatal1 mmarried mage fbaby)</span></span>
<span id="cb29-48"><a href="#cb29-48" aria-hidden="true" tabindex="-1"></a>margins r.mbsmoke, <span class="fu">subpop</span>(mbsmoke)</span>
<span id="cb29-49"><a href="#cb29-49" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-50"><a href="#cb29-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-51"><a href="#cb29-51" aria-hidden="true" tabindex="-1"></a>The ATET compares potential outcomes for the treated subpopulation, hence the <span class="in">`subpop(mbsmoke)`</span> option in <span class="in">`margins`</span>.</span>
<span id="cb29-52"><a href="#cb29-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-53"><a href="#cb29-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-54"><a href="#cb29-54" aria-hidden="true" tabindex="-1"></a><span class="fu">### Inverse Probability Weighting (IPW)</span></span>
<span id="cb29-55"><a href="#cb29-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-56"><a href="#cb29-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-57"><a href="#cb29-57" aria-hidden="true" tabindex="-1"></a>IPW has two steps. First, estimate the treatment model (typically logit) to obtain the propensity score. Second, use inverse-probability weights to compute the outcome difference between treated and control units.</span>
<span id="cb29-58"><a href="#cb29-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-59"><a href="#cb29-59" aria-hidden="true" tabindex="-1"></a>These steps produce consistent estimates of the effect parameters</span>
<span id="cb29-60"><a href="#cb29-60" aria-hidden="true" tabindex="-1"></a>because the treatment is assumed to be independent of the potential</span>
<span id="cb29-61"><a href="#cb29-61" aria-hidden="true" tabindex="-1"></a>outcomes after conditioning on the covariates.</span>
<span id="cb29-62"><a href="#cb29-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-63"><a href="#cb29-63" aria-hidden="true" tabindex="-1"></a>We can manually conduct the two steps, but the nice thing about using Stata's teffects is that it takes account of the noise of estimating probability in the first step when calculating standard errors in the second step.</span>
<span id="cb29-64"><a href="#cb29-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-65"><a href="#cb29-65" aria-hidden="true" tabindex="-1"></a><span class="fu">#### example</span></span>
<span id="cb29-68"><a href="#cb29-68" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-69"><a href="#cb29-69" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: stata-chunk3</span></span>
<span id="cb29-70"><a href="#cb29-70" aria-hidden="true" tabindex="-1"></a><span class="co">#| engine: 'stata'</span></span>
<span id="cb29-71"><a href="#cb29-71" aria-hidden="true" tabindex="-1"></a><span class="co">#| engine.path: '/usr/local/bin/stata'</span></span>
<span id="cb29-72"><a href="#cb29-72" aria-hidden="true" tabindex="-1"></a><span class="co">#| cache: true</span></span>
<span id="cb29-73"><a href="#cb29-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-74"><a href="#cb29-74" aria-hidden="true" tabindex="-1"></a>clear</span>
<span id="cb29-75"><a href="#cb29-75" aria-hidden="true" tabindex="-1"></a>webuse cattaneo2</span>
<span id="cb29-76"><a href="#cb29-76" aria-hidden="true" tabindex="-1"></a>teffects <span class="fu">ipw</span> (bweight) (mbsmoke mmarried c.mage<span class="do">##c.mage fbaby medu, probit)</span></span>
<span id="cb29-77"><a href="#cb29-77" aria-hidden="true" tabindex="-1"></a>probit mbsmoke mmarried c.mage<span class="do">##c.mage fbaby medu</span></span>
<span id="cb29-78"><a href="#cb29-78" aria-hidden="true" tabindex="-1"></a>predict ps</span>
<span id="cb29-79"><a href="#cb29-79" aria-hidden="true" tabindex="-1"></a>replace <span class="at">ps =</span> <span class="dv">1</span><span class="sc">/</span>ps <span class="cf">if</span> mbsmoke<span class="sc">==</span><span class="dv">1</span></span>
<span id="cb29-80"><a href="#cb29-80" aria-hidden="true" tabindex="-1"></a>replace <span class="at">ps =</span> <span class="dv">1</span><span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>ps) <span class="cf">if</span> mbsmoke<span class="sc">==</span><span class="dv">0</span></span>
<span id="cb29-81"><a href="#cb29-81" aria-hidden="true" tabindex="-1"></a>reg bweight mbsmoke [<span class="at">pweight=</span>ps]</span>
<span id="cb29-82"><a href="#cb29-82" aria-hidden="true" tabindex="-1"></a><span class="st">```</span></span>
<span id="cb29-83"><a href="#cb29-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-84"><a href="#cb29-84" aria-hidden="true" tabindex="-1"></a><span class="at">The manual two-step replication matches the point estimate; the only difference is the standard error (the manual version does not account for first-stage estimation noise).</span></span>
<span id="cb29-85"><a href="#cb29-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-86"><a href="#cb29-86" aria-hidden="true" tabindex="-1"></a><span class="at">### Doubly robust estimators</span></span>
<span id="cb29-87"><a href="#cb29-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-88"><a href="#cb29-88" aria-hidden="true" tabindex="-1"></a><span class="at">RA models the outcome; IPW models the treatment assignment. Doubly-robust estimators model both, requiring only one to be correctly specified.</span></span>
<span id="cb29-89"><a href="#cb29-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-90"><a href="#cb29-90" aria-hidden="true" tabindex="-1"></a><span class="at">Stata implements the AIPW combination of Robins and Rotnitzky (1995) and the IPWRA combination of Wooldridge (2010).</span></span>
<span id="cb29-91"><a href="#cb29-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-92"><a href="#cb29-92" aria-hidden="true" tabindex="-1"></a><span class="at">The AIPW estimator augments the IPW estimator with a correction term built from the outcome model. Double robustness is best stated as a **consistency** property: AIPW is consistent if *either* the treatment model *or* the outcome model is correctly specified (not necessarily both). It is *not* that the correction term literally "goes to zero" when the treatment model is right and the outcome model is wrong — with a misspecified outcome model the correction term does not generally vanish. Rather, the two pieces are constructed so that the estimator's bias cancels in the limit as long as one of the two models is right.</span></span>
<span id="cb29-93"><a href="#cb29-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-94"><a href="#cb29-94" aria-hidden="true" tabindex="-1"></a><span class="at">The IPWRA estimator uses IPW probability weights when performing RA. The weights do not affect the accuracy of the RA estimator if the treatment model is wrong and the outcome model is correct. The weights correct the RA estimator if the treatment model is correct and the outcome model is wrong.</span></span>
<span id="cb29-95"><a href="#cb29-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-96"><a href="#cb29-96" aria-hidden="true" tabindex="-1"></a><span class="at">Here we run the two commands, then manually replicate both as a two-step ("plug-in") procedure. </span><span class="st">`</span>teffects<span class="st">`</span><span class="at"> estimates the treatment and outcome models jointly by GMM/ML, using the joint estimation to get standard errors that account for first-stage estimation noise; the manual two-step version below gets essentially the same point estimate but not the correct standard errors (for the same reason noted above for IPW).</span></span>
<span id="cb29-97"><a href="#cb29-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-100"><a href="#cb29-100" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-101"><a href="#cb29-101" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: stata-chunk4</span></span>
<span id="cb29-102"><a href="#cb29-102" aria-hidden="true" tabindex="-1"></a><span class="co">#| engine: 'stata'</span></span>
<span id="cb29-103"><a href="#cb29-103" aria-hidden="true" tabindex="-1"></a><span class="co">#| engine.path: '/usr/local/bin/stata'</span></span>
<span id="cb29-104"><a href="#cb29-104" aria-hidden="true" tabindex="-1"></a><span class="co">#| cache: true</span></span>
<span id="cb29-105"><a href="#cb29-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-106"><a href="#cb29-106" aria-hidden="true" tabindex="-1"></a>clear</span>
<span id="cb29-107"><a href="#cb29-107" aria-hidden="true" tabindex="-1"></a>webuse cattaneo2</span>
<span id="cb29-108"><a href="#cb29-108" aria-hidden="true" tabindex="-1"></a>teffects <span class="fu">ipwra</span> (bweight mmarried mage prenatal1 fbaby)  (mbsmoke mmarried mage prenatal1 fbaby)</span>
<span id="cb29-109"><a href="#cb29-109" aria-hidden="true" tabindex="-1"></a>teffects <span class="fu">aipw</span> (bweight mmarried mage prenatal1 fbaby) (mbsmoke mmarried mage prenatal1 fbaby)</span>
<span id="cb29-110"><a href="#cb29-110" aria-hidden="true" tabindex="-1"></a><span class="st">```</span></span>
<span id="cb29-111"><a href="#cb29-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-112"><a href="#cb29-112" aria-hidden="true" tabindex="-1"></a><span class="at">**Manual IPWRA:** first estimate the propensity score, then run *weighted* regression adjustment within each treatment arm, using the inverse probability of the *observed* treatment status as weights:</span></span>
<span id="cb29-113"><a href="#cb29-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-116"><a href="#cb29-116" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-117"><a href="#cb29-117" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: stata-chunk4b</span></span>
<span id="cb29-118"><a href="#cb29-118" aria-hidden="true" tabindex="-1"></a><span class="co">#| engine: 'stata'</span></span>
<span id="cb29-119"><a href="#cb29-119" aria-hidden="true" tabindex="-1"></a><span class="co">#| engine.path: '/usr/local/bin/stata'</span></span>
<span id="cb29-120"><a href="#cb29-120" aria-hidden="true" tabindex="-1"></a><span class="co">#| cache: true</span></span>
<span id="cb29-121"><a href="#cb29-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-122"><a href="#cb29-122" aria-hidden="true" tabindex="-1"></a>clear</span>
<span id="cb29-123"><a href="#cb29-123" aria-hidden="true" tabindex="-1"></a>webuse cattaneo2</span>
<span id="cb29-124"><a href="#cb29-124" aria-hidden="true" tabindex="-1"></a>logit mbsmoke mmarried mage prenatal1 fbaby</span>
<span id="cb29-125"><a href="#cb29-125" aria-hidden="true" tabindex="-1"></a>predict ps</span>
<span id="cb29-126"><a href="#cb29-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-127"><a href="#cb29-127" aria-hidden="true" tabindex="-1"></a>gen <span class="at">wgt1 =</span> mbsmoke<span class="sc">/</span>ps</span>
<span id="cb29-128"><a href="#cb29-128" aria-hidden="true" tabindex="-1"></a>gen <span class="at">wgt0 =</span> (<span class="dv">1</span><span class="sc">-</span>mbsmoke)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>ps)</span>
<span id="cb29-129"><a href="#cb29-129" aria-hidden="true" tabindex="-1"></a>reg bweight mmarried mage prenatal1 fbaby <span class="cf">if</span> mbsmoke<span class="sc">==</span><span class="dv">1</span> [<span class="at">pweight=</span>wgt1]</span>
<span id="cb29-130"><a href="#cb29-130" aria-hidden="true" tabindex="-1"></a>predict mu1_ipwra</span>
<span id="cb29-131"><a href="#cb29-131" aria-hidden="true" tabindex="-1"></a>reg bweight mmarried mage prenatal1 fbaby <span class="cf">if</span> mbsmoke<span class="sc">==</span><span class="dv">0</span> [<span class="at">pweight=</span>wgt0]</span>
<span id="cb29-132"><a href="#cb29-132" aria-hidden="true" tabindex="-1"></a>predict mu0_ipwra</span>
<span id="cb29-133"><a href="#cb29-133" aria-hidden="true" tabindex="-1"></a>gen <span class="at">tau_ipwra_i =</span> mu1_ipwra <span class="sc">-</span> mu0_ipwra</span>
<span id="cb29-134"><a href="#cb29-134" aria-hidden="true" tabindex="-1"></a>sum tau_ipwra_i</span>
<span id="cb29-135"><a href="#cb29-135" aria-hidden="true" tabindex="-1"></a><span class="st">```</span></span>
<span id="cb29-136"><a href="#cb29-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-137"><a href="#cb29-137" aria-hidden="true" tabindex="-1"></a><span class="at">The mean of </span><span class="st">`</span>tau_ipwra_i<span class="st">`</span><span class="at"> matches </span><span class="st">`</span>teffects ipwra<span class="st">`</span><span class="at">'s ATE.</span></span>
<span id="cb29-138"><a href="#cb29-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-139"><a href="#cb29-139" aria-hidden="true" tabindex="-1"></a><span class="at">**Manual AIPW:** estimate outcome models $\hat\mu_1(X)$, $\hat\mu_0(X)$ (unweighted, one per arm) and the propensity score $\hat p(X)$, then combine via the augmented-IPW formula</span></span>
<span id="cb29-140"><a href="#cb29-140" aria-hidden="true" tabindex="-1"></a><span class="at">$$ \hat</span><span class="sc">\t</span><span class="at">au_{i}^{aipw} = D_i</span><span class="sc">\f</span><span class="at">rac{Y_i-\hat\mu_1(X_i)}{\hat p(X_i)} + \hat\mu_1(X_i) - (1-D_i)</span><span class="sc">\f</span><span class="at">rac{Y_i-\hat\mu_0(X_i)}{1-\hat p(X_i)} - \hat\mu_0(X_i) $$ {#eq-treatment-matching-1}</span></span>
<span id="cb29-141"><a href="#cb29-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-144"><a href="#cb29-144" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-145"><a href="#cb29-145" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: stata-chunk4c</span></span>
<span id="cb29-146"><a href="#cb29-146" aria-hidden="true" tabindex="-1"></a><span class="co">#| engine: 'stata'</span></span>
<span id="cb29-147"><a href="#cb29-147" aria-hidden="true" tabindex="-1"></a><span class="co">#| engine.path: '/usr/local/bin/stata'</span></span>
<span id="cb29-148"><a href="#cb29-148" aria-hidden="true" tabindex="-1"></a><span class="co">#| cache: true</span></span>
<span id="cb29-149"><a href="#cb29-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-150"><a href="#cb29-150" aria-hidden="true" tabindex="-1"></a>clear</span>
<span id="cb29-151"><a href="#cb29-151" aria-hidden="true" tabindex="-1"></a>webuse cattaneo2</span>
<span id="cb29-152"><a href="#cb29-152" aria-hidden="true" tabindex="-1"></a>logit mbsmoke mmarried mage prenatal1 fbaby</span>
<span id="cb29-153"><a href="#cb29-153" aria-hidden="true" tabindex="-1"></a>predict ps</span>
<span id="cb29-154"><a href="#cb29-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-155"><a href="#cb29-155" aria-hidden="true" tabindex="-1"></a>reg bweight mmarried mage prenatal1 fbaby <span class="cf">if</span> mbsmoke<span class="sc">==</span><span class="dv">1</span></span>
<span id="cb29-156"><a href="#cb29-156" aria-hidden="true" tabindex="-1"></a>predict mu1_aipw</span>
<span id="cb29-157"><a href="#cb29-157" aria-hidden="true" tabindex="-1"></a>reg bweight mmarried mage prenatal1 fbaby <span class="cf">if</span> mbsmoke<span class="sc">==</span><span class="dv">0</span></span>
<span id="cb29-158"><a href="#cb29-158" aria-hidden="true" tabindex="-1"></a>predict mu0_aipw</span>
<span id="cb29-159"><a href="#cb29-159" aria-hidden="true" tabindex="-1"></a>gen <span class="at">aipw_i =</span> mbsmoke<span class="sc">*</span>(bweight<span class="sc">-</span>mu1_aipw)<span class="sc">/</span>ps <span class="sc">+</span> mu1_aipw <span class="sc">-</span> (<span class="dv">1</span><span class="sc">-</span>mbsmoke)<span class="sc">*</span>(bweight<span class="sc">-</span>mu0_aipw)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>ps) <span class="sc">-</span> mu0_aipw</span>
<span id="cb29-160"><a href="#cb29-160" aria-hidden="true" tabindex="-1"></a>sum aipw_i</span>
<span id="cb29-161"><a href="#cb29-161" aria-hidden="true" tabindex="-1"></a><span class="st">```</span></span>
<span id="cb29-162"><a href="#cb29-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-163"><a href="#cb29-163" aria-hidden="true" tabindex="-1"></a><span class="at">The mean of </span><span class="st">`</span>aipw_i<span class="st">`</span><span class="at"> is close to </span><span class="st">`</span>teffects aipw<span class="st">`</span><span class="at">'s ATE (small differences are expected: </span><span class="st">`</span>teffects<span class="st">`</span><span class="at"> estimates the treatment and outcome models jointly by ML, while this is a two-step plug-in version).</span></span>
<span id="cb29-164"><a href="#cb29-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-165"><a href="#cb29-165" aria-hidden="true" tabindex="-1"></a><span class="at">## Matching</span></span>
<span id="cb29-166"><a href="#cb29-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-167"><a href="#cb29-167" aria-hidden="true" tabindex="-1"></a><span class="at">Matching does not solve the endogeneity problem. It addresses selection on observables only; with unobserved confounders it does not help.</span></span>
<span id="cb29-168"><a href="#cb29-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-169"><a href="#cb29-169" aria-hidden="true" tabindex="-1"></a><span class="at">What matching does is balance the covariate distributions across treatment and control groups. Regression does this too, but matching makes the lack of overlap visible — a plain regression can extrapolate far outside the support without warning. Running regression on a matched sample combines the strengths of both approaches.</span></span>
<span id="cb29-170"><a href="#cb29-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-171"><a href="#cb29-171" aria-hidden="true" tabindex="-1"></a><span class="at">Below we cover three matching methods in Stata: propensity score matching, nearest-neighbor matching, and coarsened exact matching.</span></span>
<span id="cb29-172"><a href="#cb29-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-173"><a href="#cb29-173" aria-hidden="true" tabindex="-1"></a><span class="at">### Propensity score matching</span></span>
<span id="cb29-174"><a href="#cb29-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-175"><a href="#cb29-175" aria-hidden="true" tabindex="-1"></a><span class="at">Exact matching on all covariates is ideal but infeasible in high dimensions. Rosenbaum and Rubin (1983) showed that the propensity score provides a scalar sufficient statistic, reducing the matching problem to one dimension.</span></span>
<span id="cb29-176"><a href="#cb29-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-177"><a href="#cb29-177" aria-hidden="true" tabindex="-1"></a><span class="at">Stata's </span><span class="st">`</span>teffects psmatch<span class="st">`</span><span class="at"> and </span><span class="st">`</span>psmatch2<span class="st">`</span><span class="at"> both estimate the propensity score, match, and compute the treatment effect with correct standard errors in one step.</span></span>
<span id="cb29-178"><a href="#cb29-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-181"><a href="#cb29-181" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-182"><a href="#cb29-182" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: stata-chunk5</span></span>
<span id="cb29-183"><a href="#cb29-183" aria-hidden="true" tabindex="-1"></a><span class="co">#| engine: 'stata'</span></span>
<span id="cb29-184"><a href="#cb29-184" aria-hidden="true" tabindex="-1"></a><span class="co">#| engine.path: '/usr/local/bin/stata'</span></span>
<span id="cb29-185"><a href="#cb29-185" aria-hidden="true" tabindex="-1"></a><span class="co">#| cache: true</span></span>
<span id="cb29-186"><a href="#cb29-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-187"><a href="#cb29-187" aria-hidden="true" tabindex="-1"></a>clear</span>
<span id="cb29-188"><a href="#cb29-188" aria-hidden="true" tabindex="-1"></a>webuse cattaneo2</span>
<span id="cb29-189"><a href="#cb29-189" aria-hidden="true" tabindex="-1"></a>teffects <span class="fu">psmatch</span> (bweight) (mbsmoke mmarried c.mage<span class="do">##c.mage fbaby medu), atet</span></span>
<span id="cb29-190"><a href="#cb29-190" aria-hidden="true" tabindex="-1"></a>psmatch2 mbsmoke mmarried c.mage<span class="do">##c.mage fbaby medu, logit ties</span></span>
<span id="cb29-191"><a href="#cb29-191" aria-hidden="true" tabindex="-1"></a>reg bweight mbsmoke   [<span class="at">aweight=</span>_weight]</span>
<span id="cb29-192"><a href="#cb29-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-193"><a href="#cb29-193" aria-hidden="true" tabindex="-1"></a><span class="st">```</span></span>
<span id="cb29-194"><a href="#cb29-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-195"><a href="#cb29-195" aria-hidden="true" tabindex="-1"></a><span class="st">`</span>teffects psmatch<span class="st">`</span><span class="at"> gives the ATT of smoking on birthweight. The manual replication uses </span><span class="st">`</span>psmatch2<span class="st">`</span><span class="at"> with </span><span class="st">`</span>logit<span class="st">`</span><span class="at"> and </span><span class="st">`</span>ties<span class="st">`</span><span class="at"> (by default </span><span class="st">`</span>teffects<span class="st">`</span><span class="at"> includes all tied matches, while </span><span class="st">`</span>psmatch2<span class="st">`</span><span class="at"> keeps only one), then runs a weighted regression. Point estimates match; standard errors should be taken from </span><span class="st">`</span>teffects<span class="st">`</span><span class="at">.</span></span>
<span id="cb29-196"><a href="#cb29-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-197"><a href="#cb29-197" aria-hidden="true" tabindex="-1"></a><span class="at">### Nearest neighbor matching</span></span>
<span id="cb29-198"><a href="#cb29-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-199"><a href="#cb29-199" aria-hidden="true" tabindex="-1"></a><span class="st">`</span>teffects nnmatch<span class="st">`</span><span class="at"> uses Mahalanobis distance by default and can also enforce exact matching on discrete covariates. It is nonparametric.</span></span>
<span id="cb29-200"><a href="#cb29-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-201"><a href="#cb29-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-204"><a href="#cb29-204" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-205"><a href="#cb29-205" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: stata-chunk6</span></span>
<span id="cb29-206"><a href="#cb29-206" aria-hidden="true" tabindex="-1"></a><span class="co">#| engine: 'stata'</span></span>
<span id="cb29-207"><a href="#cb29-207" aria-hidden="true" tabindex="-1"></a><span class="co">#| engine.path: '/usr/local/bin/stata'</span></span>
<span id="cb29-208"><a href="#cb29-208" aria-hidden="true" tabindex="-1"></a><span class="co">#| cache: true</span></span>
<span id="cb29-209"><a href="#cb29-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-210"><a href="#cb29-210" aria-hidden="true" tabindex="-1"></a>clear</span>
<span id="cb29-211"><a href="#cb29-211" aria-hidden="true" tabindex="-1"></a>webuse cattaneo2</span>
<span id="cb29-212"><a href="#cb29-212" aria-hidden="true" tabindex="-1"></a>teffects <span class="fu">nnmatch</span>  (bweight mmarried mage fbaby medu) (mbsmoke) , atet</span>
<span id="cb29-213"><a href="#cb29-213" aria-hidden="true" tabindex="-1"></a>teffects <span class="fu">psmatch</span> (bweight) (mbsmoke mmarried mage fbaby medu), atet</span>
<span id="cb29-214"><a href="#cb29-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-215"><a href="#cb29-215" aria-hidden="true" tabindex="-1"></a><span class="st">```</span></span>
<span id="cb29-216"><a href="#cb29-216" aria-hidden="true" tabindex="-1"></a><span class="at">Note the specification difference: </span><span class="st">`</span>nnmatch<span class="st">`</span><span class="at"> lists covariates in the outcome parentheses, </span><span class="st">`</span>psmatch<span class="st">`</span><span class="at"> lists them in the treatment parentheses.</span></span>
<span id="cb29-217"><a href="#cb29-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-218"><a href="#cb29-218" aria-hidden="true" tabindex="-1"></a><span class="at">### Coarsened Exact Matching (CEM)</span></span>
<span id="cb29-219"><a href="#cb29-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-220"><a href="#cb29-220" aria-hidden="true" tabindex="-1"></a><span class="at">CEM is available as a separate Stata package.</span></span>
<span id="cb29-221"><a href="#cb29-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-224"><a href="#cb29-224" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-225"><a href="#cb29-225" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: stata-chunk7</span></span>
<span id="cb29-226"><a href="#cb29-226" aria-hidden="true" tabindex="-1"></a><span class="co">#| engine: 'stata'</span></span>
<span id="cb29-227"><a href="#cb29-227" aria-hidden="true" tabindex="-1"></a><span class="co">#| engine.path: '/usr/local/bin/stata'</span></span>
<span id="cb29-228"><a href="#cb29-228" aria-hidden="true" tabindex="-1"></a><span class="co">#| cache: true</span></span>
<span id="cb29-229"><a href="#cb29-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-230"><a href="#cb29-230" aria-hidden="true" tabindex="-1"></a>clear</span>
<span id="cb29-231"><a href="#cb29-231" aria-hidden="true" tabindex="-1"></a>webuse cattaneo2</span>
<span id="cb29-232"><a href="#cb29-232" aria-hidden="true" tabindex="-1"></a>cem  mmarried mage fbaby medu, <span class="fu">treatment</span>(mbsmoke)</span>
<span id="cb29-233"><a href="#cb29-233" aria-hidden="true" tabindex="-1"></a>reg bweight mbsmoke   [<span class="at">aweight=</span>cem_weights]</span>
<span id="cb29-234"><a href="#cb29-234" aria-hidden="true" tabindex="-1"></a><span class="sc">*</span> Note<span class="sc">:</span> cem creates the variable <span class="st">"cem_weights"</span> (plural). We spell it out</span>
<span id="cb29-235"><a href="#cb29-235" aria-hidden="true" tabindex="-1"></a><span class="sc">*</span> <span class="cf">in</span> full here rather than relying on Stata<span class="st">'s automatic variable-name</span></span>
<span id="cb29-236"><a href="#cb29-236" aria-hidden="true" tabindex="-1"></a><span class="st">* abbreviation matching, to keep the reference unambiguous.</span></span>
<span id="cb29-237"><a href="#cb29-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-238"><a href="#cb29-238" aria-hidden="true" tabindex="-1"></a><span class="st">```</span></span>
<span id="cb29-239"><a href="#cb29-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-240"><a href="#cb29-240" aria-hidden="true" tabindex="-1"></a><span class="st">CEM creates exact-match strata on coarsened covariates and generates weights for the final regression. The standard errors do not account for the matching step.</span></span>
<span id="cb29-241"><a href="#cb29-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-242"><a href="#cb29-242" aria-hidden="true" tabindex="-1"></a><span class="st">## Modern matching in R: balance diagnostics and entropy weighting</span></span>
<span id="cb29-243"><a href="#cb29-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-244"><a href="#cb29-244" aria-hidden="true" tabindex="-1"></a><span class="st">The 2019 vintage of this chapter used Stata'</span>s <span class="st">`</span><span class="at">teffects</span><span class="st">`</span> throughout. R<span class="st">'s</span></span>
<span id="cb29-245"><a href="#cb29-245" aria-hidden="true" tabindex="-1"></a><span class="st">`MatchIt` and `WeightIt` packages have since become the standard for matching</span></span>
<span id="cb29-246"><a href="#cb29-246" aria-hidden="true" tabindex="-1"></a><span class="st">workflows, and `cobalt` provides publication-quality balance tables and plots</span></span>
<span id="cb29-247"><a href="#cb29-247" aria-hidden="true" tabindex="-1"></a><span class="st">that are now expected in applied papers.</span></span>
<span id="cb29-248"><a href="#cb29-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-249"><a href="#cb29-249" aria-hidden="true" tabindex="-1"></a><span class="st">### Balance checking with cobalt</span></span>
<span id="cb29-250"><a href="#cb29-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-251"><a href="#cb29-251" aria-hidden="true" tabindex="-1"></a><span class="st">After any matching or weighting step, always inspect covariate balance.</span></span>
<span id="cb29-252"><a href="#cb29-252" aria-hidden="true" tabindex="-1"></a><span class="st">`cobalt`'</span>s <span class="st">`</span><span class="at">bal.tab()</span><span class="st">`</span> and <span class="st">`</span><span class="at">love.plot()</span><span class="st">`</span> are the go<span class="sc">-</span>to tools<span class="sc">:</span></span>
<span id="cb29-253"><a href="#cb29-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-256"><a href="#cb29-256" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-257"><a href="#cb29-257" aria-hidden="true" tabindex="-1"></a><span class="at">#| echo: true</span></span>
<span id="cb29-258"><a href="#cb29-258" aria-hidden="true" tabindex="-1"></a><span class="at">#| message: false</span></span>
<span id="cb29-259"><a href="#cb29-259" aria-hidden="true" tabindex="-1"></a><span class="at">#| warning: false</span></span>
<span id="cb29-260"><a href="#cb29-260" aria-hidden="true" tabindex="-1"></a><span class="at">#| cache: true</span></span>
<span id="cb29-261"><a href="#cb29-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-262"><a href="#cb29-262" aria-hidden="true" tabindex="-1"></a><span class="at">library(MatchIt)</span></span>
<span id="cb29-263"><a href="#cb29-263" aria-hidden="true" tabindex="-1"></a><span class="at">library(cobalt)</span></span>
<span id="cb29-264"><a href="#cb29-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-265"><a href="#cb29-265" aria-hidden="true" tabindex="-1"></a><span class="at"># Propensity score matching on the lalonde data</span></span>
<span id="cb29-266"><a href="#cb29-266" aria-hidden="true" tabindex="-1"></a><span class="at">data("lalonde", package = "MatchIt")</span></span>
<span id="cb29-267"><a href="#cb29-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-268"><a href="#cb29-268" aria-hidden="true" tabindex="-1"></a><span class="at">m_out &lt;- matchit(treat ~ age + educ + race + married + nodegree +</span></span>
<span id="cb29-269"><a href="#cb29-269" aria-hidden="true" tabindex="-1"></a><span class="at">                   re74 + re75,</span></span>
<span id="cb29-270"><a href="#cb29-270" aria-hidden="true" tabindex="-1"></a><span class="at">                 data = lalonde, method = "nearest", distance = "glm",</span></span>
<span id="cb29-271"><a href="#cb29-271" aria-hidden="true" tabindex="-1"></a><span class="at">                 ratio = 1)</span></span>
<span id="cb29-272"><a href="#cb29-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-273"><a href="#cb29-273" aria-hidden="true" tabindex="-1"></a><span class="at"># Balance table: standardized mean differences before and after matching</span></span>
<span id="cb29-274"><a href="#cb29-274" aria-hidden="true" tabindex="-1"></a><span class="at">bal.tab(m_out, stats = c("mean.diffs", "variance.ratios"), thresholds = c(m = 0.1))</span></span>
<span id="cb29-275"><a href="#cb29-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-276"><a href="#cb29-276" aria-hidden="true" tabindex="-1"></a><span class="at"># Love plot: visualize balance improvement</span></span>
<span id="cb29-277"><a href="#cb29-277" aria-hidden="true" tabindex="-1"></a><span class="at">love.plot(m_out, stats = "mean.diffs", threshold = 0.1,</span></span>
<span id="cb29-278"><a href="#cb29-278" aria-hidden="true" tabindex="-1"></a><span class="at">          abs = TRUE, var.order = "unadjusted")</span></span>
<span id="cb29-279"><a href="#cb29-279" aria-hidden="true" tabindex="-1"></a><span class="st">```</span></span>
<span id="cb29-280"><a href="#cb29-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-281"><a href="#cb29-281" aria-hidden="true" tabindex="-1"></a>The love plot shows each covariate<span class="st">'s standardized mean difference (SMD)</span></span>
<span id="cb29-282"><a href="#cb29-282" aria-hidden="true" tabindex="-1"></a><span class="st">before matching (open circles) and after (filled circles). The vertical line</span></span>
<span id="cb29-283"><a href="#cb29-283" aria-hidden="true" tabindex="-1"></a><span class="st">at SMD = 0.1 is the conventional threshold for "balanced." If post-matching</span></span>
<span id="cb29-284"><a href="#cb29-284" aria-hidden="true" tabindex="-1"></a><span class="st">points cross the line, the matching is not improving balance and a different</span></span>
<span id="cb29-285"><a href="#cb29-285" aria-hidden="true" tabindex="-1"></a><span class="st">specification is needed.</span></span>
<span id="cb29-286"><a href="#cb29-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-287"><a href="#cb29-287" aria-hidden="true" tabindex="-1"></a><span class="st">That is exactly what happens here, which is why it is worth running the</span></span>
<span id="cb29-288"><a href="#cb29-288" aria-hidden="true" tabindex="-1"></a><span class="st">diagnostic rather than assuming. 1:1 nearest-neighbour matching on the</span></span>
<span id="cb29-289"><a href="#cb29-289" aria-hidden="true" tabindex="-1"></a><span class="st">propensity score leaves four of the nine covariates *above* the 0.1 threshold,</span></span>
<span id="cb29-290"><a href="#cb29-290" aria-hidden="true" tabindex="-1"></a><span class="st">`race` worst of all (an adjusted SMD of 0.37 for the black indicator), while</span></span>
<span id="cb29-291"><a href="#cb29-291" aria-hidden="true" tabindex="-1"></a><span class="st">discarding 244 of the 429 controls. Matching on a propensity score balances the</span></span>
<span id="cb29-292"><a href="#cb29-292" aria-hidden="true" tabindex="-1"></a><span class="st">score, not necessarily the covariates that went into it.</span></span>
<span id="cb29-293"><a href="#cb29-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-294"><a href="#cb29-294" aria-hidden="true" tabindex="-1"></a><span class="st">### Entropy balancing</span></span>
<span id="cb29-295"><a href="#cb29-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-296"><a href="#cb29-296" aria-hidden="true" tabindex="-1"></a><span class="st">Propensity score matching discards unmatched units and can reduce effective</span></span>
<span id="cb29-297"><a href="#cb29-297" aria-hidden="true" tabindex="-1"></a><span class="st">sample size substantially. **Entropy balancing** (Hainmueller 2012) keeps all</span></span>
<span id="cb29-298"><a href="#cb29-298" aria-hidden="true" tabindex="-1"></a><span class="st">units and reweights the control group so that weighted covariate moments</span></span>
<span id="cb29-299"><a href="#cb29-299" aria-hidden="true" tabindex="-1"></a><span class="st">exactly match the treatment group — without discarding anyone.</span></span>
<span id="cb29-300"><a href="#cb29-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-303"><a href="#cb29-303" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-304"><a href="#cb29-304" aria-hidden="true" tabindex="-1"></a><span class="st">#| echo: true</span></span>
<span id="cb29-305"><a href="#cb29-305" aria-hidden="true" tabindex="-1"></a><span class="st">#| message: false</span></span>
<span id="cb29-306"><a href="#cb29-306" aria-hidden="true" tabindex="-1"></a><span class="st">#| warning: false</span></span>
<span id="cb29-307"><a href="#cb29-307" aria-hidden="true" tabindex="-1"></a><span class="st">#| cache: true</span></span>
<span id="cb29-308"><a href="#cb29-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-309"><a href="#cb29-309" aria-hidden="true" tabindex="-1"></a><span class="st">library(WeightIt)</span></span>
<span id="cb29-310"><a href="#cb29-310" aria-hidden="true" tabindex="-1"></a><span class="st">library(cobalt)</span></span>
<span id="cb29-311"><a href="#cb29-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-312"><a href="#cb29-312" aria-hidden="true" tabindex="-1"></a><span class="st"># Entropy balancing: exact balance on means, variances, and covariances</span></span>
<span id="cb29-313"><a href="#cb29-313" aria-hidden="true" tabindex="-1"></a><span class="st">w_out &lt;- weightit(treat ~ age + educ + race + married + nodegree +</span></span>
<span id="cb29-314"><a href="#cb29-314" aria-hidden="true" tabindex="-1"></a><span class="st">                    re74 + re75,</span></span>
<span id="cb29-315"><a href="#cb29-315" aria-hidden="true" tabindex="-1"></a><span class="st">                  data = lalonde, method = "ebal", estimand = "ATT",</span></span>
<span id="cb29-316"><a href="#cb29-316" aria-hidden="true" tabindex="-1"></a><span class="st">                  moments = 1)   # moments=1: balance means only</span></span>
<span id="cb29-317"><a href="#cb29-317" aria-hidden="true" tabindex="-1"></a><span class="st">                                 # moments=2: balance means + variances</span></span>
<span id="cb29-318"><a href="#cb29-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-319"><a href="#cb29-319" aria-hidden="true" tabindex="-1"></a><span class="st">summary(w_out)</span></span>
<span id="cb29-320"><a href="#cb29-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-321"><a href="#cb29-321" aria-hidden="true" tabindex="-1"></a><span class="st"># Check balance</span></span>
<span id="cb29-322"><a href="#cb29-322" aria-hidden="true" tabindex="-1"></a><span class="st">bal.tab(w_out, stats = "mean.diffs", thresholds = c(m = 0.1))</span></span>
<span id="cb29-323"><a href="#cb29-323" aria-hidden="true" tabindex="-1"></a><span class="st">love.plot(w_out, threshold = 0.1, abs = TRUE)</span></span>
<span id="cb29-324"><a href="#cb29-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-325"><a href="#cb29-325" aria-hidden="true" tabindex="-1"></a><span class="st"># Weighted outcome regression</span></span>
<span id="cb29-326"><a href="#cb29-326" aria-hidden="true" tabindex="-1"></a><span class="st">library(lmtest); library(sandwich)</span></span>
<span id="cb29-327"><a href="#cb29-327" aria-hidden="true" tabindex="-1"></a><span class="st">m_eb &lt;- lm(re78 ~ treat + age + educ + race + married + nodegree +</span></span>
<span id="cb29-328"><a href="#cb29-328" aria-hidden="true" tabindex="-1"></a><span class="st">             re74 + re75,</span></span>
<span id="cb29-329"><a href="#cb29-329" aria-hidden="true" tabindex="-1"></a><span class="st">           data = lalonde, weights = w_out$weights)</span></span>
<span id="cb29-330"><a href="#cb29-330" aria-hidden="true" tabindex="-1"></a><span class="st">coeftest(m_eb, vcov = vcovHC(m_eb, type = "HC3"))["treat", ]</span></span>
<span id="cb29-331"><a href="#cb29-331" aria-hidden="true" tabindex="-1"></a><span class="st">```</span></span>
<span id="cb29-332"><a href="#cb29-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-333"><a href="#cb29-333" aria-hidden="true" tabindex="-1"></a><span class="st">Entropy balancing delivers on its promise here: the largest absolute</span></span>
<span id="cb29-334"><a href="#cb29-334" aria-hidden="true" tabindex="-1"></a><span class="st">standardized mean difference after weighting is **exactly zero**, since the</span></span>
<span id="cb29-335"><a href="#cb29-335" aria-hidden="true" tabindex="-1"></a><span class="st">weights are chosen to satisfy the mean-balance constraints as equalities. All</span></span>
<span id="cb29-336"><a href="#cb29-336" aria-hidden="true" tabindex="-1"></a><span class="st">429 controls are retained.</span></span>
<span id="cb29-337"><a href="#cb29-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-338"><a href="#cb29-338" aria-hidden="true" tabindex="-1"></a><span class="st">| Method | Pros | Cons |</span></span>
<span id="cb29-339"><a href="#cb29-339" aria-hidden="true" tabindex="-1"></a><span class="st">|---|---|---|</span></span>
<span id="cb29-340"><a href="#cb29-340" aria-hidden="true" tabindex="-1"></a><span class="st">| PSM (nearest neighbor) | Intuitive; respects overlap | Discards units; balance not guaranteed |</span></span>
<span id="cb29-341"><a href="#cb29-341" aria-hidden="true" tabindex="-1"></a><span class="st">| CEM | Exact balance in bins | Requires discretizing continuous vars |</span></span>
<span id="cb29-342"><a href="#cb29-342" aria-hidden="true" tabindex="-1"></a><span class="st">| Entropy balancing | Exact mean balance; keeps all units | Weights can be extreme; no variance balance by default |</span></span>
<span id="cb29-343"><a href="#cb29-343" aria-hidden="true" tabindex="-1"></a><span class="st">| IPW (logistic) | Simple; relies only on the treatment model | Not doubly robust on its own; extreme weights if overlap is poor |</span></span>
<span id="cb29-344"><a href="#cb29-344" aria-hidden="true" tabindex="-1"></a><span class="st">| AIPW / IPWRA | Doubly robust: consistent if *either* the treatment or outcome model is correct | Needs both models specified; more moving parts |</span></span>
<span id="cb29-345"><a href="#cb29-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-346"><a href="#cb29-346" aria-hidden="true" tabindex="-1"></a><span class="st">For most applications, entropy balancing or IPW with trimmed weights (via</span></span>
<span id="cb29-347"><a href="#cb29-347" aria-hidden="true" tabindex="-1"></a><span class="st">`WeightIt`'</span>s <span class="st">`</span><span class="at">trim()</span><span class="st">`</span>) is preferred over PSM<span class="sc">:</span> better effective sample size,</span>
<span id="cb29-348"><a href="#cb29-348" aria-hidden="true" tabindex="-1"></a>guaranteed balance, and easy integration with doubly<span class="sc">-</span>robust estimators.</span>
<span id="cb29-349"><a href="#cb29-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-350"><a href="#cb29-350" aria-hidden="true" tabindex="-1"></a>See also the [weighting chapter](weighting<span class="sc">-</span>part2.qmd) <span class="cf">for</span> IPW estimators and</span>
<span id="cb29-351"><a href="#cb29-351" aria-hidden="true" tabindex="-1"></a>the [OLS<span class="sc">-</span>ATE chapter](ols<span class="sc">-</span>ate.qmd) <span class="cf">for</span> regression<span class="sc">-</span>based approaches.</span>
<span id="cb29-352"><a href="#cb29-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-353"><a href="#cb29-353" aria-hidden="true" tabindex="-1"></a><span class="sc">---</span></span>
<span id="cb29-354"><a href="#cb29-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-355"><a href="#cb29-355" aria-hidden="true" tabindex="-1"></a><span class="er">&lt;</span><span class="sc">!--</span> see<span class="sc">-</span>also<span class="sc">-</span>footer <span class="sc">-</span><span class="ot">-&gt;</span></span>
<span id="cb29-356"><a href="#cb29-356" aria-hidden="true" tabindex="-1"></a><span class="er">*</span>Systematic treatment<span class="sc">:</span> [R](https<span class="sc">:</span><span class="er">//</span>xiangao.github.io<span class="sc">/</span>causal_econometrics_guide<span class="sc">/</span>matching.html) · [Julia](https<span class="sc">:</span><span class="er">//</span>xiangao.github.io<span class="sc">/</span>causal_econometrics_julia<span class="sc">/</span>matching.html).<span class="sc">*</span></span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->



<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions"><ul><li><a href="https://github.com/xiangao/blog_book/edit/main/treatment-matching.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/xiangao/blog_book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>