{
  "hash": "c7b00d51edcb3e630a715d5c8d477710",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Instrumental variables in fixed-effects Poisson models\"\ndate: \"2024-08-29\"\n---\n\n\n\n## Why a control function is needed\n\nSuppose a panel count-data model has the conditional mean\n\n$$E[y_{it} \\mid x_{it}, c_i] = c_i \\exp(x_{it} \\beta)$$\n\nIf a variable in $x_{it}$ is endogenous, linear two-stage least squares does not fit this exponential conditional mean. Nonlinear IV commands such as Stata's `ivpoisson` also cannot absorb high-dimensional individual and time fixed effects.\n\nLin and Wooldridge (2019) propose a two-step control-function estimator for this setting.\n\n## The two-step estimator\n\nLet $w_{it}$ be a continuous endogenous regressor and $z_{it}$ an excluded instrument. The first stage regresses $w_{it}$ on the instrument and exogenous controls while absorbing all fixed effects:\n\n$$w_{it} = z_{it}\\pi + x_{it1}\\gamma + c_i + f_t + v_{it}$$\n\nWe save the OLS residual $\\hat v_{it}$ and include it in a fixed-effects Poisson model:\n\n$$E[y_{it} \\mid w_{it}, x_{it1}, c_i, f_t, \\hat{v}_{it}] = c_i f_t \\exp(w_{it}\\beta_1 + x_{it1}\\beta_2 + \\rho \\hat{v}_{it})$$\n\nIn Stata, the two commands are `reghdfe ..., resid` and `ppmlhdfe`. In R, we can use `fixest::feols()` and `fixest::fepois()`. Testing $H_0:\\rho=0$ gives a test of exogeneity. Because $\\hat v_{it}$ is estimated, the usual second-stage standard errors are not valid. I use a cluster bootstrap that repeats both stages.\n\n## A continuous endogenous variable in Stata\n\nI use Stata's `website.dta`, which has 500 observations. `visits` is the count outcome, `time` is the endogenous regressor, `phone` is the instrument, and `frfam` is an exogenous control. The model absorbs fixed effects for the 13 advertising campaigns and for `female`.\n\n\n::: {.cell collectcode='true'}\n\n```{.stata .cell-code}\nwebuse website, clear\n\n* Step 1: Linear first stage absorbing both fixed effects\nreghdfe time phone frfam, absorb(ad female) resid\npredict double u2h_fe, resid\n\n* Step 2: FE Poisson with control function residual\nppmlhdfe visits time u2h_fe frfam, absorb(ad female)\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Visits to website)\n\n(dropped 1 singleton observations)\n(MWFE estimator converged in 3 iterations)\n\nHDFE Linear regression                            Number of obs   =        499\nAbsorbing 2 HDFE groups                           F(   2,    484) =      29.02\n                                                  Prob > F        =     0.0000\n                                                  R-squared       =     0.3137\n                                                  Adj R-squared   =     0.2938\n                                                  Within R-sq.    =     0.1071\n                                                  Root MSE        =     2.2239\n\n------------------------------------------------------------------------------\n        time | Coefficient  Std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n       phone |   .2705429   .0626834     4.32   0.000     .1473778     .393708\n       frfam |   .2539231   .0619373     4.10   0.000     .1322239    .3756222\n       _cons |   1.406026   .2549245     5.52   0.000     .9051305    1.906921\n------------------------------------------------------------------------------\n\nAbsorbed degrees of freedom:\n-----------------------------------------------------+\n Absorbed FE | Categories  - Redundant  = Num. Coefs |\n-------------+---------------------------------------|\n          ad |        12           0          12     |\n      female |         2           1           1     |\n-----------------------------------------------------+\n\n(1 missing value generated)\n\nIteration 1:   deviance = 3.7303e+02  eps = .         iters = 3    tol = 1.0e-0\n> 4                                                                            \n>    min(eta) =  -0.57  P   \nIteration 2:   deviance = 3.5849e+02  eps = 4.06e-02  iters = 3    tol = 1.0e-0\n> 4                                                                            \n>    min(eta) =  -0.59      \nIteration 3:   deviance = 3.5840e+02  eps = 2.46e-04  iters = 3    tol = 1.0e-0\n> 4                                                                            \n>    min(eta) =  -0.60      \nIteration 4:   deviance = 3.5840e+02  eps = 3.17e-08  iters = 2    tol = 1.0e-0\n> 4                                                                            \n>    min(eta) =  -0.60      \nIteration 5:   deviance = 3.5840e+02  eps = 9.72e-16  iters = 2    tol = 1.0e-0\n> 5                                                                            \n>    min(eta) =  -0.60   S  \nIteration 6:   deviance = 3.5840e+02  eps = 1.62e-16  iters = 1    tol = 1.0e-0\n> 9                                                                            \n>    min(eta) =  -0.60   S O\n-------------------------------------------------------------------------------\n> -----------------------------\n(legend: p: exact partial-out   s: exact solver   h: step-halving   o: epsilon \n> below tolerance)\nConverged in 6 iterations and 14 HDFE sub-iterations (tol = 1.0e-08)\n\nHDFE PPML regression                              No. of obs      =        499\nAbsorbing 2 HDFE groups                           Residual df     =        483\n                                                  Wald chi2(3)    =     169.93\nDeviance             =  358.4027719               Prob > chi2     =     0.0000\nLog pseudolikelihood = -993.8547331               Pseudo R2       =     0.2976\n------------------------------------------------------------------------------\n             |               Robust\n      visits | Coefficient  std. err.      z    P>|z|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n        time |   .0448103   .0448665     1.00   0.318    -.0431265    .1327471\n      u2h_fe |   .0765144   .0459404     1.67   0.096    -.0135272     .166556\n       frfam |   .0004108   .0205161     0.02   0.984       -.0398    .0406215\n       _cons |   1.510566   .1033122    14.62   0.000     1.308078    1.713054\n------------------------------------------------------------------------------\n\nAbsorbed degrees of freedom:\n-----------------------------------------------------+\n Absorbed FE | Categories  - Redundant  = Num. Coefs |\n-------------+---------------------------------------|\n          ad |        12           0          12     |\n      female |         2           1           1     |\n-----------------------------------------------------+\n```\n\n\n:::\n:::\n\n\nThe coefficient on `time` is $0.0448$ ($p = 0.318$). The residual coefficient is $\\hat{\\rho} = 0.0765$ ($p = 0.096$), indicating weak positive selection.\n\n### A comparison with linear models\n\nIn a linear model, the control-function estimator gives the same coefficient as 2SLS. I fit both as a check on the two-step code:\n\n\n::: {.cell collectcode='true'}\n\n```{.stata .cell-code}\nclear all\nwebuse website, clear\n\n* 1. Linear 2SLS\nivreghdfe visits frfam (time=phone), absorb(ad female)\n\n* 2. Linear control function\nreghdfe time phone frfam, absorb(ad female) resid\npredict double u2h_fe, resid\nreghdfe visits time u2h_fe frfam, absorb(ad female)\n\n* 3. Naive models (ignoring endogeneity)\nreghdfe visits time frfam, absorb(ad female)\nppmlhdfe visits time frfam, absorb(ad female)\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Visits to website)\n\n(dropped 1 singleton observations)\n(MWFE estimator converged in 3 iterations)\n\nIV (2SLS) estimation\n--------------------\n\nEstimates efficient for homoskedasticity only\nStatistics consistent for homoskedasticity only\n\n                                                      Number of obs =      499\n                                                      F(  2,   484) =     8.31\n                                                      Prob > F      =   0.0003\nTotal (centered) SS     =  3335.918099                Centered R2   =   0.3971\nTotal (uncentered) SS   =  3335.918099                Uncentered R2 =   0.3971\nResidual SS             =  2011.119506                Root MSE      =    2.038\n\n------------------------------------------------------------------------------\n      visits | Coefficient  Std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n        time |   .5642802   .2123745     2.66   0.008     .1469904      .98157\n       frfam |    -.04045   .0922873    -0.44   0.661    -.2217832    .1408833\n------------------------------------------------------------------------------\nUnderidentification test (Anderson canon. corr. LM statistic):          18.494\n                                                   Chi-sq(1) P-val =    0.0000\n------------------------------------------------------------------------------\nWeak identification test (Cragg-Donald Wald F statistic):               18.628\nStock-Yogo weak ID test critical values: 10% maximal IV size             16.38\n                                         15% maximal IV size              8.96\n                                         20% maximal IV size              6.66\n                                         25% maximal IV size              5.53\nSource: Stock-Yogo (2005).  Reproduced by permission.\n------------------------------------------------------------------------------\nSargan statistic (overidentification test of all instruments):           0.000\n                                                 (equation exactly identified)\n------------------------------------------------------------------------------\nInstrumented:         time\nIncluded instruments: frfam\nExcluded instruments: phone\nPartialled-out:       _cons\n                      nb: total SS, model F and R2s are after partialling-out;\n                          any small-sample adjustments include partialled-out\n                          variables in regressor count K\n------------------------------------------------------------------------------\n\nAbsorbed degrees of freedom:\n-----------------------------------------------------+\n Absorbed FE | Categories  - Redundant  = Num. Coefs |\n-------------+---------------------------------------|\n          ad |        12           0          12     |\n      female |         2           1           1     |\n-----------------------------------------------------+\n\n(dropped 1 singleton observations)\n(MWFE estimator converged in 3 iterations)\n\nHDFE Linear regression                            Number of obs   =        499\nAbsorbing 2 HDFE groups                           F(   2,    484) =      29.02\n                                                  Prob > F        =     0.0000\n                                                  R-squared       =     0.3137\n                                                  Adj R-squared   =     0.2938\n                                                  Within R-sq.    =     0.1071\n                                                  Root MSE        =     2.2239\n\n------------------------------------------------------------------------------\n        time | Coefficient  Std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n       phone |   .2705429   .0626834     4.32   0.000     .1473778     .393708\n       frfam |   .2539231   .0619373     4.10   0.000     .1322239    .3756222\n       _cons |   1.406026   .2549245     5.52   0.000     .9051305    1.906921\n------------------------------------------------------------------------------\n\nAbsorbed degrees of freedom:\n-----------------------------------------------------+\n Absorbed FE | Categories  - Redundant  = Num. Coefs |\n-------------+---------------------------------------|\n          ad |        12           0          12     |\n      female |         2           1           1     |\n-----------------------------------------------------+\n\n(1 missing value generated)\n\n(MWFE estimator converged in 3 iterations)\n\nHDFE Linear regression                            Number of obs   =        499\nAbsorbing 2 HDFE groups                           F(   3,    483) =     117.11\n                                                  Prob > F        =     0.0000\n                                                  R-squared       =     0.7677\n                                                  Adj R-squared   =     0.7605\n                                                  Within R-sq.    =     0.4211\n                                                  Root MSE        =     1.9996\n\n------------------------------------------------------------------------------\n      visits | Coefficient  Std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n        time |   .5642802   .2083276     2.71   0.007       .15494    .9736205\n      u2h_fe |   .1827169   .2122987     0.86   0.390    -.2344262    .5998601\n       frfam |    -.04045   .0905287    -0.45   0.655    -.2183288    .1374288\n       _cons |   3.357879   .4427337     7.58   0.000     2.487957    4.227801\n------------------------------------------------------------------------------\n\nAbsorbed degrees of freedom:\n-----------------------------------------------------+\n Absorbed FE | Categories  - Redundant  = Num. Coefs |\n-------------+---------------------------------------|\n          ad |        12           0          12     |\n      female |         2           1           1     |\n-----------------------------------------------------+\n\n(dropped 1 singleton observations)\n(MWFE estimator converged in 3 iterations)\n\nHDFE Linear regression                            Number of obs   =        499\nAbsorbing 2 HDFE groups                           F(   2,    484) =     175.38\n                                                  Prob > F        =     0.0000\n                                                  R-squared       =     0.7673\n                                                  Adj R-squared   =     0.7606\n                                                  Within R-sq.    =     0.4202\n                                                  Root MSE        =     1.9991\n\n------------------------------------------------------------------------------\n      visits | Coefficient  Std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n        time |   .7402254   .0400951    18.46   0.000     .6614435    .8190073\n       frfam |  -.1034523    .053248    -1.94   0.053     -.208078    .0011735\n       _cons |   3.027348   .2202211    13.75   0.000     2.594641    3.460055\n------------------------------------------------------------------------------\n\nAbsorbed degrees of freedom:\n-----------------------------------------------------+\n Absorbed FE | Categories  - Redundant  = Num. Coefs |\n-------------+---------------------------------------|\n          ad |        12           0          12     |\n      female |         2           1           1     |\n-----------------------------------------------------+\n\n(dropped 1 observations that are either singletons or separated by a fixed effe\n> ct)\nIteration 1:   deviance = 3.7573e+02  eps = .         iters = 3    tol = 1.0e-0\n> 4                                                                            \n>    min(eta) =  -0.64  P   \nIteration 2:   deviance = 3.6107e+02  eps = 4.06e-02  iters = 3    tol = 1.0e-0\n> 4                                                                            \n>    min(eta) =  -0.64      \nIteration 3:   deviance = 3.6098e+02  eps = 2.57e-04  iters = 3    tol = 1.0e-0\n> 4                                                                            \n>    min(eta) =  -0.64      \nIteration 4:   deviance = 3.6098e+02  eps = 3.76e-08  iters = 2    tol = 1.0e-0\n> 4                                                                            \n>    min(eta) =  -0.64      \nIteration 5:   deviance = 3.6098e+02  eps = 1.45e-15  iters = 2    tol = 1.0e-0\n> 5                                                                            \n>    min(eta) =  -0.64   S  \nIteration 6:   deviance = 3.6098e+02  eps = 0.00e+00  iters = 1    tol = 1.0e-0\n> 9                                                                            \n>    min(eta) =  -0.64   S O\n-------------------------------------------------------------------------------\n> -----------------------------\n(legend: p: exact partial-out   s: exact solver   h: step-halving   o: epsilon \n> below tolerance)\nConverged in 6 iterations and 14 HDFE sub-iterations (tol = 1.0e-08)\n\nHDFE PPML regression                              No. of obs      =        499\nAbsorbing 2 HDFE groups                           Residual df     =        484\n                                                  Wald chi2(2)    =     164.67\nDeviance             =  360.9797175               Prob > chi2     =     0.0000\nLog pseudolikelihood = -995.1432059               Pseudo R2       =     0.2967\n------------------------------------------------------------------------------\n             |               Robust\n      visits | Coefficient  std. err.      z    P>|z|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n        time |   .1187612   .0095895    12.38   0.000     .0999662    .1375563\n       frfam |  -.0281572   .0099614    -2.83   0.005    -.0476812   -.0086332\n       _cons |   1.345121   .0497098    27.06   0.000     1.247692    1.442551\n------------------------------------------------------------------------------\n\nAbsorbed degrees of freedom:\n-----------------------------------------------------+\n Absorbed FE | Categories  - Redundant  = Num. Coefs |\n-------------+---------------------------------------|\n          ad |        12           0          12     |\n      female |         2           1           1     |\n-----------------------------------------------------+\n```\n\n\n:::\n:::\n\n\n| Model | Estimator | `time` Coef. | Std. Err. | $p$-value |\n|:---|:---|:---:|:---:|:---:|\n| Naive Linear FE | `reghdfe` | 0.7402 | 0.0401 | $<0.001$ |\n| Linear 2SLS | `ivreghdfe` | 0.5643 | 0.2124 | 0.008 |\n| Linear Control Function | Manual two-step | 0.5643 | 0.2083 | 0.007 |\n| Naive FE Poisson | `ppmlhdfe` (no residual) | 0.1188 | 0.0096 | $<0.001$ |\n| Control-Function FE Poisson | `ppmlhdfe` (with $\\hat{v}$) | 0.0448 | 0.0449 | 0.318 |\n\nThe manual linear control function reproduces the 2SLS coefficient exactly. In the Poisson model, adding the control-function residual reduces the `time` coefficient from $0.1188$ to $0.0448$.\n\n### Cluster bootstrap in Stata\n\nThe bootstrap can draw the same cluster more than once. Each copy must get a new identifier through `idcluster()`; otherwise Stata pools the copies into one fixed effect.\n\n\n::: {.cell collectcode='true'}\n\n```{.stata .cell-code}\nclear all\ncapture program drop ppmlhdfe_cf\nprogram ppmlhdfe_cf, rclass\n  reghdfe time phone frfam, absorb(newid female) resid\n  predict double u2h_fe, resid\n  ppmlhdfe visits time u2h_fe frfam, absorb(newid female)\n  return scalar b_time = _b[time]\n  return scalar b_u2h  = _b[u2h_fe]\n  drop u2h_fe\n  xtset, clear\nend\n\nwebuse website, clear\nxtset, clear\nbootstrap r(b_time) r(b_u2h), reps(1000) seed(123) cluster(ad) idcluster(newid) nodots: ppmlhdfe_cf\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Visits to website)\n\n\n\nBootstrap results                                        Number of obs =   499\n                                                         Replications  = 1,000\n\n      Command: ppmlhdfe_cf\n        _bs_1: r(b_time)\n        _bs_2: r(b_u2h)\n\n                                     (Replications based on 12 clusters in ad)\n------------------------------------------------------------------------------\n             |   Observed   Bootstrap                         Normal-based\n             | coefficient  std. err.      z    P>|z|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n       _bs_1 |   .0448103   .0477457     0.94   0.348    -.0487697    .1383902\n       _bs_2 |   .0765144   .0486568     1.57   0.116    -.0188511    .1718799\n------------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\nThe bootstrap standard error on `time` is $0.0477$ (compared to the unadjusted analytic standard error of $0.0449$).\n\n## The same estimator in R\n\nIn R, I use `fixest::feols()` and `fixest::fepois()`. `feols()` drops a singleton cluster here (`ad == 10`), so we use `obs()` to align the residuals with the rows kept in the first stage:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(fixest)\nlibrary(haven)\n\ndf <- as.data.frame(read_dta(\"https://www.stata-press.com/data/r18/website.dta\"))\ndf$ad     <- as.factor(df$ad)\ndf$female <- as.factor(df$female)\n\n# Step 1: Linear first stage\nfs <- feols(time ~ phone + frfam | ad + female, data = df)\n\n# Align rows (feols drops singletons)\nd <- df[obs(fs), ]\nd$u2h_fe <- residuals(fs)\n\n# Step 2: FE Poisson with and without control function\nm_naive <- fepois(visits ~ time + frfam          | ad + female, data = d, notes = FALSE)\nm_cf    <- fepois(visits ~ time + u2h_fe + frfam | ad + female, data = d, notes = FALSE)\n\netable(m_naive, m_cf, headers = c(\"Naive FE Poisson\", \"Control Function\"), se.below = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                         m_naive             m_cf\n                Naive FE Poisson Control Function\nDependent Var.:           visits           visits\n                                                 \ntime                   0.1188***          0.0448 \n                      (0.0076)           (0.0477)\nfrfam                 -0.0282**           0.0004 \n                      (0.0108)           (0.0211)\nu2h_fe                                    0.0765 \n                                         (0.0487)\nFixed-Effects:        ----------         --------\nad                           Yes              Yes\nfemale                       Yes              Yes\n_______________       __________         ________\nS.E. type                    IID              IID\nObservations                 499              499\nSquared Cor.             0.75130          0.75528\nPseudo R2                0.29670          0.29761\nBIC                      2,083.5          2,087.1\n---\nSignif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe point estimates match Stata to seven digits: $0.1187612$ (naive) and $0.0448103$ (control function).\n\n### Cluster bootstrap in R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nB <- 1000\nclusters   <- unique(d$ad)\nboot_coefs <- matrix(NA_real_, nrow = B, ncol = 2, dimnames = list(NULL, c(\"time\", \"resid\")))\n\nfor (b in seq_len(B)) {\n  drawn <- sample(clusters, length(clusters), replace = TRUE)\n  boot_data <- do.call(rbind, lapply(seq_along(drawn), function(k) {\n    sub <- d[d$ad == drawn[k], ]\n    sub$boot_id <- k\n    sub\n  }))\n  boot_data$boot_id <- as.factor(boot_data$boot_id)\n\n  fs_b <- feols(time ~ phone + frfam | boot_id + female, data = boot_data, notes = FALSE)\n  bb   <- boot_data[obs(fs_b), ]\n  bb$u_b <- residuals(fs_b)\n\n  m_b <- try(fepois(visits ~ time + u_b + frfam | boot_id + female, data = bb, notes = FALSE), silent = TRUE)\n  if (!inherits(m_b, \"try-error\")) boot_coefs[b, ] <- coef(m_b)[c(\"time\", \"u_b\")]\n}\n\ncat(\"Completed replications :\", sum(complete.cases(boot_coefs)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCompleted replications : 1000 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Bootstrap SE, time     :\", round(sd(boot_coefs[, \"time\"],  na.rm = TRUE), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBootstrap SE, time     : 0.045 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Bootstrap SE, residual :\", round(sd(boot_coefs[, \"resid\"], na.rm = TRUE), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBootstrap SE, residual : 0.0457 \n```\n\n\n:::\n:::\n\n\nThe R bootstrap yields $\\text{SE} = 0.0450$. With only 12 clusters in `ad`, small differences across software packages ($0.0477$ in Stata vs. $0.0450$ in R) reflect finite-sample sensitivity in how rare degenerate resamples and singletons are handled.\n\n## A binary endogenous regressor\n\nWhen $D_{it}$ is binary, as with program participation, a linear first stage is misspecified because its error cannot satisfy the required conditional-independence restriction.\n\n### A CRE logit first stage\n\nA first-stage logit with a dummy for every unit has an incidental-parameters problem when $T$ is small. For example, its slopes can be about twice as large as they should be when $T=2$. I instead use pooled logit with a Mundlak adjustment, adding the unit means of the time-varying covariates:\n\n$$P(D_{it} = 1 \\mid z_{it}, \\bar{z}_i) = \\Lambda(z_{it}\\gamma + \\bar{z}_i \\pi)$$\n\nFor logit, the generalized residual is simply the response residual,\n\n$$\\hat r_{it}=D_{it}-\\hat p_{it}.$$\n\nWe then include $\\hat r_{it}$ in the fixed-effects Poisson model.\n\n### A simulation\n\nLet's simulate 2,000 units with unbalanced panels, where $T_i$ ranges from 2 to 6. The treatment $D$ is binary and endogenous, and its true coefficient is $\\beta=0.30$.\n\n\n::: {.cell collectcode='true'}\n\n```{.stata .cell-code}\npreserve\nclear\nset seed 20260731\nset obs 2000\ngen i = _n\ngen double ci = rnormal()*0.5\ngen T = 2 + int(runiform()*5)        /* 2-6 observations per unit */\nexpand T\nbysort i: gen t = _n\n\ngen double z = rnormal()             /* instrument */\ngen double e = rnormal()\ngen double u = 0.8*e + rnormal()*0.6 /* correlated with e -> endogeneity */\ngen byte   d = (-0.2 + 0.9*z + ci + e > 0)\ngen double mu = exp(0.3*d + ci + 0.5*u)\ngen y = rpoisson(mu)                 /* true beta = 0.3 */\n\n* 1. Naive FE Poisson (ignores endogeneity)\nquietly ppmlhdfe y d, absorb(i)\nscalar b_naive = _b[d]\n\n* 2. CF with CRE (Mundlak) logit first stage\nbysort i: egen double z_i = mean(z)\nquietly logit d z z_i\npredict double phat, pr\ngen double gr = d - phat\nquietly ppmlhdfe y d gr, absorb(i)\nscalar b_cre = _b[d]\n\n* 3. CF with linear first stage\nquietly reghdfe d z, absorb(i) resid\npredict double v_lin, resid\nquietly ppmlhdfe y d v_lin, absorb(i)\nscalar b_lin = _b[d]\n\ndi \"True coefficient on d       = 0.300000\"\ndi \"Naive FE Poisson            = \" %8.6f b_naive\ndi \"CF, CRE (Mundlak) Logit     = \" %8.6f b_cre\ndi \"CF, Linear First Stage      = \" %8.6f b_lin\nrestore\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of observations (_N) was 0, now 2,000.\n\n\n\n\n(5,969 observations created)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nTrue coefficient on d       = 0.300000\n\nNaive FE Poisson            = 0.747206\n\nCF, CRE (Mundlak) Logit     = 0.293829\n\nCF, Linear First Stage      = 0.277644\n```\n\n\n:::\n:::\n\n\nThe naive fixed-effects Poisson estimate is $0.747$, more than 2.4 times the true value. The CRE logit control function gives $0.294$, while the linear first-stage control function gives $0.278$.\n\nIn an application, I would report both control-function specifications as a sensitivity check.\n\n## What to remember\n\nThe control-function approach adds the first-stage residual to the exponential outcome model. For a continuous endogenous variable, we can combine `reghdfe` with `ppmlhdfe` in Stata, or `feols()` with `fepois()` in R. Inference should bootstrap both stages by cluster. For a binary endogenous variable, a CRE logit first stage avoids the incidental-parameters problem from unit dummies, and its residual is $d-\\hat p$.\n",
    "supporting": [
      "poisson-iv-fe_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}