{
  "hash": "7fee27ca039115b131de735108074d3e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"incremental effects for continuous exposures\"\ndate: \"2026-10-05\"\n---\n\nThe [LMTP chapter](lmtp.html) answered questions like \"what if every unit's dose were one unit lower?\" That shift needs positivity at the shifted dose. A unit whose dose sits near the edge of the support, or just beside a gap in it, is moved to a dose that no comparable unit ever received. @schindl-2026 study an intervention that avoids this. Instead of moving each unit's dose, it reweights the distribution each unit's dose is drawn from, so that higher (or lower) doses become more likely. Doses the unit could never receive stay impossible.\n\nFor a binary treatment this is the incremental propensity score intervention of @kennedy-2019, which multiplies every unit's odds of treatment by a factor. `npcausal::ipsi()` estimates it, and `lmtp::ipsi()` gives a shift function for binary exposures that scales the probability of treatment by a risk ratio. This chapter is about the continuous version, for which the authors provide replication code but no package. We write the estimator, check it in a simulation, and apply it to the authors' example, political ads and campaign contributions.\n\n## The exponential tilt\n\nWe observe covariates $X$, a dose $A$ and an outcome $Y$. Let $\\pi(a \\mid x)$ be the conditional law of the dose and $\\mu(x, a) = E(Y \\mid X = x, A = a)$ the outcome regression. For a number $\\delta$, the tilted law of the dose is\n\n$$\nq_\\delta(a \\mid x) = \\frac{e^{\\delta a}\\, \\pi(a \\mid x)}{\\int e^{\\delta t}\\, \\pi(t \\mid x)\\, dt}.\n$$ {#eq-incremental-tilt}\n\nThe denominator only makes the result integrate to one. On the log scale, $\\log q_\\delta(a \\mid x) = \\log \\pi(a \\mid x) + \\delta a - \\text{const}$: we add a line of slope $\\delta$ to the log density, which tips it toward high doses when $\\delta > 0$ and toward low doses when $\\delta < 0$. That is why it is called a tilt. It goes back to @esscher-1932 in actuarial work and is the standard device in importance sampling. A normal density with mean $m$ and variance $s^2$, tilted by $\\delta$, becomes a normal with mean $m + \\delta s^2$ and the same variance. On a bounded support it cannot shift forever, so the mass piles up against the edge, and as $\\delta \\to \\infty$ it becomes a point mass at the top dose.\n\nTwo features matter for what follows. First, $\\delta$ is not a dose. It is the slope of the log likelihood ratio between $q_\\delta$ and $\\pi$, measured in one over the units of $A$. The dose change it implies is the change in the conditional mean, which for small $\\delta$ is about $\\delta \\operatorname{var}(A \\mid X)$. Second, where $\\pi(a \\mid x) = 0$, so is $q_\\delta(a \\mid x)$. The tilt never sends anyone to a dose they could not have received.\n\nThe estimand is the mean outcome when $X$ keeps its distribution and each unit's dose is drawn from $q_\\delta$:\n\n$$\n\\psi(\\delta) = E\\left[\\int \\mu(X, a)\\, q_\\delta(a \\mid X)\\, da\\right].\n$$ {#eq-incremental-psi}\n\nUnder consistency and conditional exchangeability, $\\psi(\\delta)$ is identified by @eq-incremental-psi, and it needs no positivity, because the integral only uses $\\mu$ where $\\pi$ is positive. At $\\delta = 0$ the tilt does nothing and $\\psi(0) = E(Y)$. That gives an exact check on any estimator.\n\n## Tilt or shift\n\nThe two interventions differ in what they act on. A shift, the modified treatment policy of @diaz-2012 and @haneuse-2013 that `lmtp` estimates, acts on each unit's own dose: it replaces the observed $A$ with $A + s$, or with $A + s$ only when that dose is still feasible. A tilt acts on the law the dose is drawn from. Each unit keeps its covariates and receives a new dose drawn from $q_\\delta(\\cdot \\mid X)$, and its observed dose plays no part.\n\nFour differences follow. A shift needs positivity at the shifted dose, $\\pi(a + s \\mid x) > 0$ wherever $\\pi(a \\mid x) > 0$; a tilt needs none. A shift moves everyone by $s$ in dose units; a tilt moves the conditional mean by about $\\delta \\operatorname{var}(A \\mid X)$, so units whose dose is more uncertain given their covariates move further. The efficient influence function of a shift weights residuals by the density ratio $\\pi(A - s \\mid X)/\\pi(A \\mid X)$, which `lmtp` estimates with a classifier; the tilt weights them by $e^{\\delta A}/E(e^{\\delta A} \\mid X)$. And when the dose is normal given $X$ with variance $\\sigma^2(X)$, the tilt by $\\delta$ is exactly a shift by $\\delta\\sigma^2(X)$, so with constant variance the two are the same intervention. They part ways when the support is bounded, lumpy or has holes, which is the setting where the shift's positivity condition bites.\n\n## Efficiency, and why the tilt size matters\n\nWrite $E_Q(\\mu \\mid X) = \\int \\mu(X, a)\\, q_\\delta(a \\mid X)\\, da$ for the regression averaged over the tilted law. For bounded $\\delta$, the efficient influence function is\n\n$$\n\\varphi(Z; \\delta) = \\frac{q_\\delta(A \\mid X)}{\\pi(A \\mid X)}\\bigl\\{Y - E_Q(\\mu \\mid X)\\bigr\\} + E_Q(\\mu \\mid X) - \\psi(\\delta),\n$$ {#eq-incremental-eif}\n\nand the one-step estimator replaces the nuisances by cross-fitted estimates and averages $\\hat\\varphi + \\hat\\psi$ over the sample. The likelihood ratio in @eq-incremental-eif has a simple form, $q_\\delta(A \\mid X)/\\pi(A \\mid X) = e^{\\delta A} / \\int e^{\\delta t} \\pi(t \\mid X)\\, dt$, so we never need the density at the observed dose, only integrals against it.\n\nThat ratio grows with $\\delta$. If $\\pi$ is uniform on $[0, 1]$, it equals $\\delta e^{\\delta a}/(e^\\delta - 1)$, which is at least $\\delta$ at $a = 1$. @schindl-2026 show that, when the dose density is bounded below on an interval at the top of the support (they call this weak positivity), the variance of $\\varphi$ is bounded above and below by multiples of $\\delta$. A two-point argument then gives a minimax lower bound of order $\\sqrt{\\delta / n}$ for any estimator, and the cross-fitted one-step estimator attains it. The effective sample size is $n / \\delta$. Without weak positivity, for example when the density goes to zero at the top edge, the variance can grow like any power of $\\delta$. As $\\delta \\to \\infty$ in both directions around an interior dose $a'$, a \"reflected\" tilt also gives an estimate of the dose-response curve $E(Y^{a'})$, with $\\delta$ playing the role of an inverse bandwidth. We come back to that at the end.\n\n## Implementing it\n\nThe paper estimates $\\pi(a \\mid x)$ on a grid of design points $a_j$ by regressing the kernel-transformed outcome $K_h(A - a_j)$ on $X$, since $E\\{K_h(A - a) \\mid X = x\\}$ is close to $\\pi(a \\mid x)$ for small $h$. The integrals in @eq-incremental-tilt and $E_Q(\\mu \\mid X)$ are then weighted sums over the grid. We keep that approach and change four things.\n\nThe first is the bandwidth. The authors' code chooses $h$ by the cross-validated RMSE of the regression of $K_h(A - a_j)$ on $X$. The variance of $K_h(A - a)$ is of order $1/h$, so the criterion is not comparable across bandwidths. Run on a subsample of the application data, it picks an end of its grid at every design point: the largest bandwidth wherever doses are nearby, and the smallest wherever the design point falls between the discrete dose values, since there a narrow kernel sees no data and its target is close to zero. We fix $h$ by Silverman's rule. The second is normalisation. Their $\\hat\\pi$ for $\\psi(\\delta)$ is not rescaled to integrate to one, so $\\hat q_\\delta / \\hat\\pi$ is off by a factor $1 / \\int \\hat\\pi$, and $\\hat\\psi(0)$ need not equal $\\bar Y$. We renormalise each unit's density. The third is the edge of the support. A Gaussian kernel loses about half its mass at the boundary, which is exactly where the tilt puts its weight, so we reflect the kernel at both ends. The fourth is specific to the application: 12% of the ZIP codes there have no ads at all, a point mass at $A = 0$. The tilt in @eq-incremental-tilt is defined for any law, with or without an atom: the zero dose keeps weight $e^{0} = 1$, so $q_\\delta / \\pi = e^{\\delta A} / \\nu(X)$ with $\\nu(x) = E(e^{\\delta A} \\mid X = x)$, also at $A = 0$. We estimate $P(A = 0 \\mid X)$ with a classification forest and fit the kernel to the positive doses only. The influence function keeps the form of @eq-incremental-eif. The paper instead smooths the zeros into the density.\n\nThe paper also mentions a version with no density at all (their Remark 3). Since $E_Q(\\mu \\mid X) = \\eta(X)/\\nu(X)$ with $\\eta(x) = E\\{e^{\\delta A}\\mu(X, A) \\mid X = x\\}$, both pieces are regressions on $X$. The bias of the one-step estimator is then $(\\hat\\nu - \\nu)(\\hat\\eta/\\hat\\nu - \\eta/\\nu)/\\hat\\nu$, a product of errors, so it is as doubly robust as the density version. The authors report that it is unstable, and we include it in the simulation to see.\n\nAll four estimators below share the outcome forest and the cross-fitting. `tilt_grid()` takes a function that returns the conditional law on a grid, so the same code runs with our mixed law, the paper's law, and the true law in the simulation.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the estimator code\"}\nlibrary(ranger)\n\n# ---- Our estimator: tilts through regressions on X -------------------------\n# With nu(x) = E[exp(delta A) | X = x] and eta(x) = E[exp(delta A) mu(X, A) | X = x],\n# the tilted mean of mu is eta / nu and q / pi at the observed dose is\n# exp(delta A) / nu. Both are regressions on X, so no conditional density is\n# needed and an atom in the dose distribution (here, A = 0) is handled as it is.\n# The influence value is (q / pi)(Y - eta / nu) + eta / nu. eta is fitted to\n# exp(delta A) mu_hat(X, A), using out-of-bag predictions of mu on the training\n# fold. Exponentials are scaled by exp(-delta c) with c = max(A) for delta > 0,\n# which cancels in every ratio. With shift = TRUE we also return the implied\n# change in the mean dose, E_Q(A | X) - E(A | X), averaged over units.\ntilt_regression <- function(y, a, x, deltas, folds, shift = FALSE, cluster = NULL,\n                            num.trees = 200, threads = 1) {\n  x  <- as.data.frame(x)\n  n  <- length(y)\n  phi <- matrix(NA_real_, n, length(deltas))\n  dA  <- matrix(NA_real_, n, length(deltas))\n  reg <- function(target, tr, va) {\n    f <- ranger(t ~ ., data = data.frame(x[tr, , drop = FALSE], t = target),\n                num.trees = num.trees, num.threads = threads)\n    predict(f, data = x[va, , drop = FALSE], num.threads = threads)$predictions\n  }\n  for (k in sort(unique(folds))) {\n    va <- which(folds == k); tr <- which(folds != k)\n    fmu <- ranger(y ~ ., data = data.frame(x[tr, , drop = FALSE], a = a[tr], y = y[tr]),\n                  num.trees = 500, num.threads = threads)\n    mu_oob <- fmu$predictions\n    if (shift) ea0 <- reg(a[tr], tr, va)\n    for (j in seq_along(deltas)) {\n      d   <- deltas[j]\n      c0  <- if (d > 0) max(a) else 0\n      t   <- exp(d * (a[tr] - c0))\n      nu  <- reg(t, tr, va)\n      eq  <- reg(t * mu_oob, tr, va) / nu\n      qp  <- exp(d * (a[va] - c0)) / nu\n      phi[va, j] <- qp * (y[va] - eq) + eq\n      if (shift) dA[va, j] <- reg(t * a[tr], tr, va) / nu - ea0\n    }\n  }\n  out <- data.frame(delta = deltas, est = colMeans(phi), se = if_se(phi))\n  if (!is.null(cluster)) out$se_cluster <- if_se(phi, cluster)\n  if (shift) out$mean_shift <- colMeans(dA)\n  out\n}\n\n# ---- Conditional law of the dose on a grid ----------------------------------\n# pi(a | x) at each of D design points a_j is the regression on X of the\n# kernel-transformed outcome K_h(A - a_j), as in Section 5.1 of the paper, with\n# two changes to the authors' code: h is fixed by Silverman's rule (their CV on\n# the RMSE of K_h always picks the largest h) and each unit's density is\n# renormalised to integrate to one. With atom = TRUE (our default) the zeros\n# get their own probability p0(x) from a classification forest and the kernel\n# is fitted to the positive doses only; with reflect = TRUE the kernel is\n# reflected at the ends of the support so it does not lose mass there. The\n# paper's version is atom = FALSE, reflect = FALSE.\nfit_kernel_law <- function(a_tr, x_tr, x_va, atom = TRUE, reflect = TRUE, D = 50,\n                           num.trees = 100, threads = 1) {\n  p0 <- rep(0, nrow(x_va))\n  if (atom) {\n    d0 <- data.frame(x_tr, zero = factor(a_tr == 0, levels = c(FALSE, TRUE)))\n    f0 <- ranger(zero ~ ., data = d0, probability = TRUE,\n                 num.trees = 300, num.threads = threads)\n    p0 <- predict(f0, data = x_va, num.threads = threads)$predictions[, \"TRUE\"]\n    x_tr <- x_tr[a_tr > 0, , drop = FALSE]; a_tr <- a_tr[a_tr > 0]\n  }\n  L <- min(a_tr); U <- max(a_tr); h <- bw.nrd0(a_tr)\n  ag <- L + (U - L) * (seq_len(D) - 0.5) / D\n  Fh <- sapply(ag, function(g) {\n    k <- dnorm((a_tr - g) / h)\n    if (reflect) k <- k + dnorm((2 * L - a_tr - g) / h) + dnorm((2 * U - a_tr - g) / h)\n    f <- ranger(k ~ ., data = data.frame(x_tr, k = k / h),\n                num.trees = num.trees, num.threads = threads)\n    predict(f, data = x_va, num.threads = threads)$predictions\n  })\n  list(p0 = p0, agrid = matrix(ag, nrow(x_va), D, byrow = TRUE),\n       W = Fh / rowSums(Fh), da = (U - L) / D)\n}\n\nmu_on_grid <- function(fmu, x_va, agrid, threads = 1) {\n  G  <- ncol(agrid)\n  xx <- x_va[rep(seq_len(nrow(x_va)), times = G), , drop = FALSE]\n  pr <- predict(fmu, data = data.frame(xx, a = as.vector(agrid)),\n                num.threads = threads)$predictions\n  matrix(pr, nrow(x_va), G)\n}\n\n# Grid estimator for a given conditional law: law(a_tr, x_tr, x_va) returns an\n# atom probability p0 at A = 0, a dose grid, weights summing to one per unit and\n# the cell width da. Used with fit_kernel_law and, in the simulation, the truth.\ntilt_grid <- function(y, a, x, deltas, folds, law, cluster = NULL, threads = 1) {\n  x <- as.data.frame(x)\n  n <- length(y)\n  phi <- matrix(NA_real_, n, length(deltas))\n  dA  <- matrix(NA_real_, n, length(deltas))\n  for (k in sort(unique(folds))) {\n    va <- which(folds == k); tr <- which(folds != k)\n    fmu <- ranger(y ~ ., data = data.frame(x[tr, , drop = FALSE], a = a[tr], y = y[tr]),\n                  num.trees = 500, num.threads = threads)\n    f    <- law(a[tr], x[tr, , drop = FALSE], x[va, , drop = FALSE])\n    ea0  <- (1 - f$p0) * rowSums(f$W * f$agrid)               # E(A | X)\n    mu_g <- mu_on_grid(fmu, x[va, , drop = FALSE], f$agrid, threads)\n    mu_0 <- predict(fmu, data = data.frame(x[va, , drop = FALSE], a = 0),\n                    num.threads = threads)$predictions\n    for (j in seq_along(deltas)) {\n      d  <- deltas[j]\n      c0 <- if (d > 0) max(a) else 0\n      # exact integral of exp(delta a) over each grid cell of width da\n      cf <- if (d == 0) 1 else sinh(d * f$da / 2) / (d * f$da / 2)\n      ew <- cf * f$W * exp(d * (f$agrid - c0))\n      nu <- f$p0 * exp(-d * c0) + (1 - f$p0) * rowSums(ew)\n      eq <- (f$p0 * exp(-d * c0) * mu_0 + (1 - f$p0) * rowSums(ew * mu_g)) / nu\n      qp <- exp(d * (a[va] - c0)) / nu\n      phi[va, j] <- qp * (y[va] - eq) + eq\n      dA[va, j]  <- (1 - f$p0) * rowSums(ew * f$agrid) / nu - ea0\n    }\n  }\n  out <- data.frame(delta = deltas, est = colMeans(phi), se = if_se(phi),\n                    mean_shift = colMeans(dA))\n  if (!is.null(cluster)) out$se_cluster <- if_se(phi, cluster)\n  out\n}\n\n# Standard error of a mean of influence values, one column per estimand:\n# iid by default, or clustered when units share a cluster (here, a market).\n# With a cluster, the estimators return both.\nif_se <- function(phi, cluster = NULL) {\n  n <- nrow(phi)\n  if (is.null(cluster)) return(apply(phi, 2, sd) / sqrt(n))\n  ctr <- sweep(phi, 2, colMeans(phi))\n  sqrt(colSums(rowsum(ctr, cluster)^2)) / n\n}\n\n# Reflected tilt at interior doses a1 (dose-response): tilt up below a1 and\n# down above it, with side weights omega = P(A <= a1 | X) and 1 - omega. The\n# atom at 0 lies below every a1 > 0. The influence value is (r / pi)(Y - U) + U,\n# where U is the tilted mean of mu on the side of a1 where the unit's dose lies.\nreflect_grid <- function(y, a, x, a1s, delta, folds, law, cluster = NULL,\n                         threads = 1) {\n  x <- as.data.frame(x)\n  n <- length(y)\n  phi <- matrix(NA_real_, n, length(a1s))\n  cf  <- function(da) sinh(delta * da / 2) / (delta * da / 2)\n  for (k in sort(unique(folds))) {\n    va <- which(folds == k); tr <- which(folds != k)\n    fmu <- ranger(y ~ ., data = data.frame(x[tr, , drop = FALSE], a = a[tr], y = y[tr]),\n                  num.trees = 500, num.threads = threads)\n    f    <- law(a[tr], x[tr, , drop = FALSE], x[va, , drop = FALSE])\n    mu_g <- mu_on_grid(fmu, x[va, , drop = FALSE], f$agrid, threads)\n    mu_0 <- predict(fmu, data = data.frame(x[va, , drop = FALSE], a = 0),\n                    num.threads = threads)$predictions\n    for (j in seq_along(a1s)) {\n      a1  <- a1s[j]\n      lo  <- f$agrid <= a1\n      elo <- cf(f$da) * f$W * exp(delta * (f$agrid - a1)) * lo     # at most 1\n      ehi <- cf(f$da) * f$W * exp(-delta * (f$agrid - a1)) * !lo   # at most 1\n      p0s <- f$p0 * exp(-delta * a1)\n      D1  <- p0s + (1 - f$p0) * rowSums(elo)\n      D2  <- (1 - f$p0) * rowSums(ehi)\n      om  <- f$p0 + (1 - f$p0) * rowSums(f$W * lo)\n      m1  <- (p0s * mu_0 + (1 - f$p0) * rowSums(elo * mu_g)) / D1\n      m2  <- ((1 - f$p0) * rowSums(ehi * mu_g)) / D2\n      low <- a[va] <= a1\n      rp  <- ifelse(low, om * exp(delta * (a[va] - a1)) / D1,\n                         (1 - om) * exp(-delta * (a[va] - a1)) / D2)\n      U   <- ifelse(low, m1, m2)\n      phi[va, j] <- rp * (y[va] - U) + U\n    }\n  }\n  out <- data.frame(a1 = a1s, delta = delta, est = colMeans(phi), se = if_se(phi))\n  if (!is.null(cluster)) out$se_cluster <- if_se(phi, cluster)\n  out\n}\n```\n:::\n\n\n## Simulation\n\nThe aim is to see whether the one-step estimator is unbiased and covers at 95% as $\\delta$ moves away from zero, how fast its precision falls with $\\delta$, and what ignoring the atom at zero does. The covariates $X_1$ and $X_2$ are independent uniforms on $(0, 1)$. The dose is zero with probability $\\operatorname{expit}(-1.5 + X_1)$; otherwise it is drawn from an equal mixture of a $\\text{Uniform}(0, 1)$ and a $\\text{Beta}(1 + 2X_2, 1)$, whose density is at least $0.5$ everywhere on $(0, 1)$, so weak positivity holds at both edges. The outcome is $Y = 1 + X_1 + X_2 + 2A + \\sin(3A) + \\varepsilon$ with standard normal $\\varepsilon$. The true $\\psi(\\delta)$ comes from numerical integration over $X$ and $A$. We compare four estimators: our mixed law, the paper's law with zeros smoothed into the density, the regression version, and the true law with the outcome forest still estimated (the oracle). The tilts are $\\delta \\in \\{-10, -5, -2, 0, 2, 5, 10, 25\\}$, the sample sizes $n = 1000$ (200 replications) and $n = 4000$ (100 replications). The run takes about 40 minutes at $n = 1000$ and an hour and a half at $n = 4000$ on six cores, so the chunk reads the saved results when they exist.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu_true <- function(x1, x2, a) 1 + x1 + x2 + 2 * a + sin(3 * a)\np0_true <- function(x1) plogis(-1.5 + x1)\n# density of A given A > 0: half Uniform(0, 1), half Beta(1 + 2 x2, 1), so it is\n# at least 0.5 on all of [0, 1] (weak positivity at both edges)\nf_pos <- function(a, x2) 0.5 + 0.5 * dbeta(a, 1 + 2 * x2, 1)\n\nsim_data <- function(n) {\n  x1 <- runif(n); x2 <- runif(n)\n  zero <- runif(n) < p0_true(x1)\n  pos <- ifelse(runif(n) < 0.5, runif(n), rbeta(n, 1 + 2 * x2, 1))\n  a <- ifelse(zero, 0, pos)\n  y <- mu_true(x1, x2, a) + rnorm(n)\n  list(y = y, a = a, x = data.frame(x1 = x1, x2 = x2))\n}\n\n# True psi(delta) by quadrature: midpoint grids over (x1, x2) and over a.\ntrue_psi <- function(deltas, nx = 100, na = 2000) {\n  g  <- (seq_len(nx) - 0.5) / nx\n  ag <- (seq_len(na) - 0.5) / na\n  X  <- expand.grid(x1 = g, x2 = g)\n  sapply(deltas, function(d) {\n    p0 <- p0_true(X$x1)\n    num <- den <- numeric(nrow(X))\n    c0 <- if (d > 0) 1 else 0                           # scale exp(delta a) by exp(-delta c0)\n    for (j in seq_len(nrow(X))) {\n      f  <- f_pos(ag, X$x2[j]) / na\n      ew <- f * exp(d * (ag - c0))\n      den[j] <- sum(ew)\n      num[j] <- sum(ew * mu_true(X$x1[j], X$x2[j], ag))\n    }\n    s  <- exp(-d * c0)                                  # same scaling for the atom\n    mean((p0 * s * mu_true(X$x1, X$x2, 0) + (1 - p0) * num) /\n         (p0 * s + (1 - p0) * den))\n  })\n}\n\noracle_law <- function(a_tr, x_tr, x_va, G = 200) {\n  ag <- (seq_len(G) - 0.5) / G\n  W  <- t(sapply(x_va$x2, function(v) { f <- f_pos(ag, v); f / sum(f) }))\n  list(p0 = p0_true(x_va$x1), agrid = matrix(ag, nrow(x_va), G, byrow = TRUE), W = W,\n       da = 1 / G)\n}\n\none_rep <- function(n, deltas) {\n  d <- sim_data(n)\n  folds <- sample(rep(1:5, length.out = n))\n  out <- rbind(\n    data.frame(estimator = \"regression\",\n               tilt_regression(d$y, d$a, d$x, deltas, folds)),\n    data.frame(estimator = \"mixed\",\n               tilt_grid(d$y, d$a, d$x, deltas, folds, law = fit_kernel_law)),\n    data.frame(estimator = \"paper\",\n               tilt_grid(d$y, d$a, d$x, deltas, folds, law = function(...)\n                 fit_kernel_law(..., atom = FALSE, reflect = FALSE))),\n    data.frame(estimator = \"oracle\",\n               tilt_grid(d$y, d$a, d$x, deltas, folds, law = oracle_law)))\n  stopifnot(all(abs(out$est[out$delta == 0] - mean(d$y)) < 1e-8))\n  out$n <- n\n  out\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(parallel)\n# About 40 minutes for n = 1000 and 95 for n = 4000 on six cores, so the chunk\n# reads the saved results when they exist.\nif (!file.exists(\"incremental-effects-sim.rds\")) {\n  RNGkind(\"L'Ecuyer-CMRG\"); set.seed(20261005)\n  deltas <- c(-10, -5, -2, 0, 2, 5, 10, 25)\n  truth  <- data.frame(delta = deltas, truth = true_psi(deltas))\n  res <- list()\n  for (n in c(1000, 4000)) {\n    reps <- if (n == 1000) 200 else 100\n    t0 <- Sys.time()\n    out <- mclapply(seq_len(reps), function(r) {\n      o <- try(one_rep(n, deltas)); if (!inherits(o, \"try-error\")) o$rep <- r; o\n    }, mc.cores = 6, mc.set.seed = TRUE)\n    bad <- vapply(out, inherits, logical(1), \"try-error\")\n    if (any(bad)) message(\"n=\", n, \": \", sum(bad), \" failed reps: \", out[bad][[1]])\n    res[[as.character(n)]] <- do.call(rbind, out[!bad])\n    message(\"n=\", n, \" done in \", format(Sys.time() - t0))\n    saveRDS(list(truth = truth, sims = do.call(rbind, res)), \"incremental-effects-sim.rds\")\n  }\n}\nsim <- readRDS(\"incremental-effects-sim.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Bias, standard deviation, mean estimated standard error and coverage of nominal 95% intervals.\n\n|Dose law          |    n| $\\delta$|   Bias|    SD| Mean SE| Coverage|\n|:-----------------|----:|--------:|------:|-----:|-------:|--------:|\n|true law (oracle) | 1000|      -10| -0.004| 0.058|   0.058|    0.950|\n|true law (oracle) | 1000|       -5| -0.004| 0.054|   0.053|    0.955|\n|true law (oracle) | 1000|       -2| -0.002| 0.051|   0.049|    0.930|\n|true law (oracle) | 1000|        2|  0.000| 0.040|   0.045|    0.960|\n|true law (oracle) | 1000|        5|  0.000| 0.048|   0.056|    0.965|\n|true law (oracle) | 1000|       10|  0.002| 0.068|   0.075|    0.960|\n|true law (oracle) | 1000|       25|  0.003| 0.116|   0.115|    0.945|\n|true law (oracle) | 4000|      -10| -0.001| 0.027|   0.028|    0.970|\n|true law (oracle) | 4000|       -5|  0.000| 0.025|   0.026|    0.940|\n|true law (oracle) | 4000|       -2|  0.001| 0.024|   0.024|    0.950|\n|true law (oracle) | 4000|        2| -0.001| 0.025|   0.022|    0.940|\n|true law (oracle) | 4000|        5| -0.002| 0.031|   0.028|    0.950|\n|true law (oracle) | 4000|       10| -0.003| 0.039|   0.037|    0.940|\n|true law (oracle) | 4000|       25| -0.004| 0.057|   0.057|    0.950|\n|mixed law (ours)  | 1000|      -10| -0.104| 0.091|   0.099|    0.900|\n|mixed law (ours)  | 1000|       -5| -0.116| 0.068|   0.074|    0.680|\n|mixed law (ours)  | 1000|       -2| -0.070| 0.053|   0.054|    0.755|\n|mixed law (ours)  | 1000|        2|  0.055| 0.042|   0.050|    0.840|\n|mixed law (ours)  | 1000|        5|  0.060| 0.065|   0.077|    0.925|\n|mixed law (ours)  | 1000|       10|  0.046| 0.130|   0.141|    0.960|\n|mixed law (ours)  | 1000|       25|  0.046| 0.394|   0.392|    0.975|\n|mixed law (ours)  | 4000|      -10| -0.069| 0.041|   0.045|    0.730|\n|mixed law (ours)  | 4000|       -5| -0.088| 0.032|   0.035|    0.300|\n|mixed law (ours)  | 4000|       -2| -0.057| 0.025|   0.027|    0.490|\n|mixed law (ours)  | 4000|        2|  0.044| 0.026|   0.024|    0.590|\n|mixed law (ours)  | 4000|        5|  0.034| 0.039|   0.037|    0.830|\n|mixed law (ours)  | 4000|       10|  0.004| 0.067|   0.067|    0.960|\n|mixed law (ours)  | 4000|       25| -0.043| 0.264|   0.219|    0.970|\n|paper's law       | 1000|      -10| -0.849| 0.261|   0.251|    0.040|\n|paper's law       | 1000|       -5| -0.514| 0.111|   0.127|    0.000|\n|paper's law       | 1000|       -2| -0.158| 0.060|   0.068|    0.345|\n|paper's law       | 1000|        2|  0.038| 0.042|   0.045|    0.895|\n|paper's law       | 1000|        5|  0.054| 0.065|   0.073|    0.920|\n|paper's law       | 1000|       10|  0.053| 0.151|   0.153|    0.955|\n|paper's law       | 1000|       25|  0.017| 0.850|   0.615|    0.965|\n|paper's law       | 4000|      -10| -0.627| 0.120|   0.106|    0.000|\n|paper's law       | 4000|       -5| -0.423| 0.053|   0.059|    0.000|\n|paper's law       | 4000|       -2| -0.141| 0.029|   0.033|    0.000|\n|paper's law       | 4000|        2|  0.032| 0.025|   0.022|    0.650|\n|paper's law       | 4000|        5|  0.032| 0.038|   0.034|    0.820|\n|paper's law       | 4000|       10|  0.010| 0.069|   0.070|    0.940|\n|paper's law       | 4000|       25| -0.075| 0.329|   0.298|    0.960|\n\n\n:::\n:::\n\n\nWith the true dose law, the one-step estimator is unbiased and its intervals cover at close to 95% at every tilt and both sample sizes. Its standard deviation at $n = 4000$ grows from 0.025 at $\\delta = 2$ to 0.057 at $\\delta = 25$, and it halves when $n$ quadruples, as an error of order $\\sqrt{\\delta/n}$ should. So the influence function and the one-step estimator are right, and $\\hat\\psi(0) = \\bar Y$ held in every replication.\n\nEstimating the dose law changes the picture. With our mixed law, the bias at $\\delta = -5$ is -0.116 at $n = 1000$ and -0.088 at $n = 4000$, while the standard deviation falls from 0.068 to 0.032. The bias shrinks by about a quarter when the sample quadruples, a rate near $n^{-0.2}$, which is slower than the $n^{-1/2}$ of the standard error. Coverage therefore gets worse with more data, from 0.68 to 0.3 at $\\delta = -5$ and from 0.84 to 0.59 at $\\delta = 2$. The reason is in the remainder. For the average treatment effect, the second-order term is a product of the outcome and propensity errors. For the tilt it also contains the squared error of the density estimate itself, $\\|\\hat\\pi - \\pi\\|^2$ in the mixed norm of @schindl-2026's Theorem 3. A good outcome model does not protect us. The conditional density has to be estimated faster than $n^{-1/4}$, uniformly over the dose, and a kernel regression on forests does not get there in this design.\n\nIgnoring the atom is much worse. The paper's law smooths the zeros into a bump over small positive doses, and its bias at $\\delta = -10$ is -0.849 at $n = 1000$ and -0.627 at $n = 4000$, with coverage of 0. For positive tilts the two laws give similar results, since the atom gets little weight there. The regression version is unstable, as the authors reported: when $\\hat\\nu(X)$ is too small for a few units, $e^{\\delta A}/\\hat\\nu(X)$ explodes, and the mean estimate at $\\delta = 25$ is -416 against a true value of 4.18.\n\n## Political ads and campaign contributions\n\nThe application follows @urban-niebler-2014, with data from @fong-2018 as distributed in the authors' repository. The units are 16,265 ZIP codes in states that were not competitive in the 2008 presidential election. Media markets cross state lines, so some of these ZIP codes received ads aimed at a neighbouring competitive state. The dose is $\\log(\\text{ads} + 1)$, the outcome $\\log(\\text{contributions} + 1)$, and the eight covariates are those of the paper. Two facts about the dose shape the analysis. It has a point mass at zero and a hole between about 3.6 and 5.0. And ads are bought by media market, so every ZIP code in one of the 138 markets has the same dose. The dose takes only 73 distinct values. The paper treats the ZIP codes as independent. We cross-fit with folds made of whole markets and report standard errors clustered by market next to the iid ones.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ne <- new.env(); load(\"FECForCEM.RData\", envir = e); fec <- e$x\ny <- log(fec$Cont + 1)\na <- log(fec$TotAds + 1)\nX <- model.matrix(~ -1 + log(TotalPop) + PercentOver65 + log(Inc + 1) + PercentHispanic +\n                    PercentBlack + density + per_collegegrads + CanCommute, data = fec)\ncolnames(X) <- make.names(colnames(X))\nmarket <- fec$DMACode\nset.seed(20261005)\nmk <- unique(market)\nfolds <- sample(rep(1:5, length.out = length(mk)))[match(market, mk)]\nif (!file.exists(\"incremental-effects-app.rds\")) {\n  deltas <- seq(-2.5, 5, by = 0.05)\n  mixed <- tilt_grid(y, a, X, deltas, folds, cluster = market, threads = 6,\n                     law = function(...) fit_kernel_law(..., D = 100, threads = 6))\n  paper <- tilt_grid(y, a, X, deltas, folds, cluster = market, threads = 6,\n                     law = function(...) fit_kernel_law(..., atom = FALSE, reflect = FALSE,\n                                                        D = 100, threads = 6))\n  stopifnot(abs(mixed$est[mixed$delta == 0] - mean(y)) < 1e-8,\n            abs(paper$est[paper$delta == 0] - mean(y)) < 1e-8)\n  apos <- a[a > 0]\n  delta_dr <- length(y)^(1/3) / diff(range(apos))\n  a1s <- c(1, 2, 3, 5.5, 6.5, 7.5, 8.5, 9.5)\n  dr <- reflect_grid(y, a, X, a1s, delta_dr, folds, cluster = market, threads = 6,\n                     law = function(...) fit_kernel_law(..., D = 100, threads = 6))\n  saveRDS(list(mixed = mixed, paper = paper, dr = dr, delta_dr = delta_dr, ybar = mean(y)),\n          \"incremental-effects-app.rds\")\n}\napp <- readRDS(\"incremental-effects-app.rds\")\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Estimated incremental effect of political ads on log contributions (top) and the implied change in the mean dose (bottom), for the mixed law and for the paper's law that smooths the zeros. Bands are 95% intervals clustered by media market.](incremental-effects_files/figure-pdf/fig-incremental-app-1.pdf){#fig-incremental-app}\n:::\n:::\n\n\nThe check at zero holds: $\\hat\\psi(0) =$ 1.2431, the sample mean of log contributions. The first thing the bottom panel shows is how strong these tilts are. The dose has variance 10.8 across ZIP codes, so $\\delta = 0.05$ already moves the mean dose by 0.48 log ads, and the paper's largest tilt, $\\delta = 5$, moves it by 5.51, which puts nearly every ZIP code at the largest ad counts. The range of $\\delta$ the paper plots, from $-2.5$ to $5$, runs from almost no ads to the maximum.\n\nThe estimated curve rises slightly from 1.243 to a peak of 1.25 near $\\delta =$ 0.15, then falls to 0.745 at $\\delta = 5$. Negative tilts lower it to 1.045 at $\\delta = -2.5$. For positive tilts the two laws agree, because the atom at zero gets little weight there. For negative tilts the paper's law gives lower values, 0.758 at $\\delta = -2.5$, which is the same direction as its bias in the simulation.\n\nThe standard errors clustered by market are about ten times the iid ones: 0.12 against 0.012 at $\\delta = 0$. Ads vary across 138 markets, and the iid errors treat 16,265 ZIP codes as independent doses. With intervals of about $\\pm 0.24$, moderate tilts cannot be told apart from no tilt, and the simulation warns that even these intervals are too narrow at moderate $\\delta$. We read the curve as descriptive.\n\nThis does not match the paper's application. It reports average contributions rising from about \\$2.00 at $\\delta = 0$ to \\$2.20 at $\\delta = 5$, with most of the gain below $\\delta = 1$. Whatever transformation turns $\\psi$ into dollars, at $\\delta = 0$ it must reproduce the sample mean of log contributions, 1.243, which is \\$2.47 under $e^{\\psi} - 1$. Their value at zero is not the sample mean. The missing normalisation of $\\hat\\pi$ in their code does not explain this: run on a subsample of the data, their code puts $\\hat\\psi(0)$ within 0.01 of the sample mean, and the scripts do not show how the dollar figures were computed.\n\n## Shift and tilt on the same ZIP codes\n\nWe now estimate shifts with `lmtp` on the same data: the same covariates, a ranger learner for both nuisances, cross-fitting and standard errors by market. Each unit's dose moves by $s = \\pm 0.5$ log ads when the shifted dose stays inside the observed range and is left alone otherwise. For each shift we take the tilt whose implied change in the mean dose is the same, read off the fine grid of $\\delta$ above, so the two interventions move the average dose by the same amount.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Shift interventions on the same ZIP codes with lmtp: move each unit's dose by\n# s log ads when the shifted dose stays inside the observed range, and leave it\n# unchanged otherwise. Same covariates, a ranger learner for both nuisances,\n# cross-fitting and standard errors by media market.\nlibrary(lmtp); library(SuperLearner)\nSL.ranger6 <- function(...) SL.ranger(..., num.trees = 500, num.threads = 6)\nfeasible_shift <- function(s, lo, hi) function(data, trt) {\n  a <- data[[trt]]\n  ifelse(a + s >= lo & a + s <= hi, a + s, a)\n}\nfec_df <- data.frame(X, a = a, y = y, market = market)\nif (!file.exists(\"incremental-effects-lmtp.rds\")) {\n  shifts <- c(-0.5, 0.5)\n  lmtp_fits <- lapply(shifts, function(s) {\n    f <- lmtp_sdr(fec_df, trt = \"a\", outcome = \"y\", baseline = colnames(X),\n                  shift = feasible_shift(s, min(a), max(a)), mtp = TRUE,\n                  outcome_type = \"continuous\", id = \"market\",\n                  learners_outcome = \"SL.ranger6\", learners_trt = \"SL.ranger6\", folds = 5)\n    d <- feasible_shift(s, min(a), max(a))(fec_df, \"a\")\n    data.frame(s = s, est = f$estimate@x, se = f$estimate@std_error,\n               mean_shift = mean(d - a), share_moved = mean(d != a))\n  })\n  lmtp_res <- do.call(rbind, lmtp_fits)\n  saveRDS(lmtp_res, \"incremental-effects-lmtp.rds\")\n}\nlmtp_res <- readRDS(\"incremental-effects-lmtp.rds\")\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Shift (lmtp) and tilt with the same change in the mean dose. Standard errors clustered by market; the tilt estimate is interpolated on the grid of $\\delta$.\n\n|  $s$| Share moved| Mean change in dose| Shift estimate|    SE| Matched $\\delta$| Tilt estimate|    SE|\n|----:|-----------:|-------------------:|--------------:|-----:|----------------:|-------------:|-----:|\n| -0.5|       0.879|              -0.439|          1.241| 0.202|           -0.047|         1.238| 0.118|\n|  0.5|       0.975|               0.488|          1.251| 0.207|            0.051|         1.247| 0.122|\n\n\n:::\n:::\n\n\nFor a change of half a log ad in the average dose, the two interventions give almost the same answer: 1.251 for the shift and 1.247 for the tilt when the mean dose rises, and 1.241 against 1.238 when it falls. Both are within a few thousandths of $\\bar Y =$ 1.243, and the differences are far inside the standard errors. Small changes in ads move contributions very little under either intervention.\n\nThey differ in who moves. The shift moves everyone it can by the same amount: 97.5% of ZIP codes for the upward shift, and 87.9% for the downward one, since the ZIP codes with no ads cannot go lower. The tilt with the same mean moves units in proportion to the spread of their dose given covariates and never sends anyone to a dose they could not receive. The shift also sends most ZIP codes to ad counts that no market had, since the dose takes only 73 values; `lmtp`'s density-ratio classifier smooths over this. Its standard errors here are larger, 0.207 against 0.122.\n\n## Dose-response by a reflected tilt\n\nTo reach an interior dose $a'$, tilt upward below $a'$ and downward above it. With $\\omega(x) = P(A \\le a' \\mid X = x)$, the reflected tilt is\n\n$$\nr_\\delta(a \\mid x) = \\omega(x)\\, \\frac{e^{\\delta a}\\pi(a\\mid x)\\, 1(a \\le a')}{\\int_{t \\le a'} e^{\\delta t}\\pi(t\\mid x)\\, dt} + \\{1 - \\omega(x)\\}\\, \\frac{e^{-\\delta a}\\pi(a\\mid x)\\, 1(a > a')}{\\int_{t > a'} e^{-\\delta t}\\pi(t\\mid x)\\, dt},\n$$ {#eq-incremental-reflect}\n\nand $\\psi_R(\\delta, a')$ averages $\\mu$ over it. As $\\delta \\to \\infty$ it converges to $E(Y^{a'})$. If $\\mu$ is Lipschitz in the dose, the estimate is within $O_P(1/\\delta + \\sqrt{\\delta/n})$ of $E(Y^{a'})$, so $\\delta$ of order $n^{1/3}$ gives the usual $n^{-1/3}$ rate. The two sides of $a'$ get the weights $\\omega$ and $1 - \\omega$, which makes the tilt an asymmetric exponential kernel. Its bias is first order in $1/\\delta$, which is why the result stops at Lipschitz smoothness. The rate is stated for a dose on $[0, 1]$, so we set $\\delta = n^{1/3}$ on that scale, which is $\\delta =$ 2.72 per log ad here, and evaluate the curve away from the hole, where weak positivity fails.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Dose-response of log contributions on log ads by the reflected tilt, with 95% intervals clustered by market. The curve is not evaluated in the hole of the dose distribution between about 3.6 and 5.0.](incremental-effects_files/figure-pdf/fig-incremental-dr-1.pdf){#fig-incremental-dr}\n:::\n:::\n\n\nThe estimated curve is flat within its noise. It rises from 1.244 at one log ad to 1.366 at 5.5 and falls to 1.108 at 9.5, with clustered standard errors between 0.13 and 0.2. The dashed line is the sample mean. The same caveats apply as before: intervals that understate uncertainty when the density is estimated, and a bias of order $1/\\delta$.\n\n## Summary\n\nAn incremental effect tilts each unit's dose distribution toward higher or lower doses, $q_\\delta(a \\mid x) \\propto e^{\\delta a}\\pi(a \\mid x)$, and asks for the mean outcome under the tilted distribution. Doses a unit could never receive stay impossible, so the effect is identified without positivity, which a shift of the dose needs. The price is that $\\delta$ is not a dose: it changes the mean dose by about $\\delta \\operatorname{var}(A \\mid X)$. Its efficient influence function weights residuals by $e^{\\delta A}/E(e^{\\delta A} \\mid X)$. Under weak positivity at the top of the support, the best attainable error is of order $\\sqrt{\\delta/n}$, and the cross-fitted one-step estimator attains it when the nuisances are good enough.\n\n\"Good enough\" is the catch. In our simulation the one-step estimator is unbiased and covers at 95% when the dose law is known. With the law estimated by the paper's kernel regression, made to integrate to one, reflected at the edges and given its own probability for an atom at zero, the bias falls more slowly than the standard error, and coverage at moderate tilts gets worse as $n$ grows. The remainder contains the squared error of the density estimate, so the conditional density has to be estimated well, uniformly over doses. Treating an atom at zero as part of a density biases negative tilts badly, and the regression version without a density is unstable.\n\nIn the political-ads data the tilts are strong, standard errors must be clustered by the 138 media markets that set the dose, and the curve is flat within those errors. Shifting the dose by half a log ad with `lmtp` and tilting it to give the same change in the mean dose give the same answer.\n\n---\n\n<!-- see-also-footer -->\n*Systematic treatment: [R](https://xiangao.github.io/causal_econometrics_guide/continuous-treatments.html) · [Julia](https://xiangao.github.io/causal_econometrics_julia/continuous-treatments.html).*\n",
    "supporting": [
      "incremental-effects_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}