{
  "hash": "f74f652721a3d8c23a9a94be2e27e1c1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"The Mundlak device in panel data and difference-in-differences\"\ndate: \"2021-10-23\"\n---\n\n\n\n## The basic idea\n\nSuppose we have a panel-data model with an individual effect $c_i$:\n\n$$y_{it} = X_{it}\\beta + c_i + u_{it}$$\n\nThe fixed-effects estimator removes $c_i$ by demeaning, so $c_i$ can be correlated with $X_{it}$. But the same transformation also removes time-invariant variables such as gender, race, or baseline schooling.\n\nMundlak (1978) instead writes $c_i$ as a linear projection on the unit means of the time-varying covariates:\n\n$$c_i = \\bar{X}_i \\theta + \\eta_i, \\qquad E[\\eta_i \\mid X_i] = 0$$\n\nSubstituting into the regression yields:\n\n$$y_{it} = X_{it}\\beta + \\bar{X}_i \\theta + \\eta_i + u_{it}$$\n\nWe can estimate this equation by pooled OLS or random effects. By the Frisch--Waugh--Lovell theorem, the coefficient on $X_{it}$ is the same as the fixed-effects coefficient.\n\nTesting $H_0:\\theta=0$ gives a regression-based version of the Hausman test and works with cluster-robust standard errors. We can also add time-invariant covariates directly. They do not change $\\hat\\beta$ because within-unit deviations are orthogonal to every time-invariant variable.\n\n## A one-way panel example\n\nI start with Stata's `nlswork` data, using 19,229 person-year observations:\n\n\n::: {.cell collectcode='true'}\n\n```{.stata .cell-code}\nclear\nwebuse nlswork\nxtset idcode year\ndrop if union==. | age==.\nbysort idcode: egen mean_age = mean(age)\nbysort idcode: egen mean_union = mean(union)\n\n* 1. Standard FE\nxtreg ln_wage age union, fe cluster(idcode)\n\n* 2. Pooled OLS with Mundlak means\nreg ln_wage age union mean_age mean_union, cluster(idcode)\n\n* 3. Random Effects with Mundlak means\nxtreg ln_wage age union mean_age mean_union, re cluster(idcode)\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(National Longitudinal Survey of Young Women, 14-24 years old in 1968)\n\n\nPanel variable: idcode (unbalanced)\n Time variable: year, 68 to 88, but with gaps\n         Delta: 1 unit\n\n(9,305 observations deleted)\n\n\n\n\nFixed-effects (within) regression               Number of obs     =     19,229\nGroup variable: idcode                          Number of groups  =      4,150\n\nR-squared:                                      Obs per group:\n     Within  = 0.0963                                         min =          1\n     Between = 0.0433                                         avg =        4.6\n     Overall = 0.0562                                         max =         12\n\n                                                F(2, 4149)        =     331.52\ncorr(u_i, Xb) = 0.0127                          Prob > F          =     0.0000\n\n                             (Std. err. adjusted for 4,150 clusters in idcode)\n------------------------------------------------------------------------------\n             |               Robust\n     ln_wage | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n         age |   .0153507   .0006912    22.21   0.000     .0139956    .0167058\n       union |   .1055274   .0098582    10.70   0.000     .0862001    .1248546\n       _cons |   1.248435   .0215661    57.89   0.000     1.206154    1.290716\n-------------+----------------------------------------------------------------\n     sigma_u |  .42353003\n     sigma_e |  .26213464\n         rho |  .72302816   (fraction of variance due to u_i)\n------------------------------------------------------------------------------\n\n\nLinear regression                               Number of obs     =     19,229\n                                                F(4, 4149)        =     234.77\n                                                Prob > F          =     0.0000\n                                                R-squared         =     0.0769\n                                                Root MSE          =     .44953\n\n                             (Std. err. adjusted for 4,150 clusters in idcode)\n------------------------------------------------------------------------------\n             |               Robust\n     ln_wage | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n         age |   .0153507   .0006912    22.21   0.000     .0139956    .0167059\n       union |   .1055274   .0098587    10.70   0.000     .0861991    .1248556\n    mean_age |  -.0064208    .001548    -4.15   0.000    -.0094556   -.0033859\n  mean_union |   .1900785   .0223172     8.52   0.000     .1463249    .2338321\n       _cons |   1.405264    .042734    32.88   0.000     1.321482    1.489046\n------------------------------------------------------------------------------\n\n\nRandom-effects GLS regression                   Number of obs     =     19,229\nGroup variable: idcode                          Number of groups  =      4,150\n\nR-squared:                                      Obs per group:\n     Within  = 0.0963                                         min =          1\n     Between = 0.0750                                         avg =        4.6\n     Overall = 0.0768                                         max =         12\n\n                                                Wald chi2(4)      =    1023.99\ncorr(u_i, X) = 0 (assumed)                      Prob > chi2       =     0.0000\n\n                             (Std. err. adjusted for 4,150 clusters in idcode)\n------------------------------------------------------------------------------\n             |               Robust\n     ln_wage | Coefficient  std. err.      z    P>|z|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n         age |   .0153507   .0006912    22.21   0.000     .0139959    .0167055\n       union |   .1055274   .0098587    10.70   0.000     .0862047      .12485\n    mean_age |  -.0061464   .0014254    -4.31   0.000    -.0089401   -.0033527\n  mean_union |    .212183   .0210098    10.10   0.000     .1710046    .2533614\n       _cons |   1.362101   .0383784    35.49   0.000     1.286881    1.437322\n-------------+----------------------------------------------------------------\n     sigma_u |  .38505558\n     sigma_e |  .26213464\n         rho |  .68331727   (fraction of variance due to u_i)\n------------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\nAll three models yield identical coefficients: $\\hat{\\beta}_{\\text{age}} = 0.0153507$ ($\\text{SE} = 0.00069$) and $\\hat{\\beta}_{\\text{union}} = 0.1055274$ ($\\text{SE} = 0.00986$).\n\n### Adding a time-invariant covariate\n\nWe add `race` (constant within individual) to the Mundlak Pooled OLS model:\n\n\n::: {.cell collectcode='true'}\n\n```{.stata .cell-code}\nreg ln_wage age union mean_age mean_union i.race, cluster(idcode)\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear regression                               Number of obs     =     19,229\n                                                F(6, 4149)        =     189.66\n                                                Prob > F          =     0.0000\n                                                R-squared         =     0.1069\n                                                Root MSE          =      .4422\n\n                             (Std. err. adjusted for 4,150 clusters in idcode)\n------------------------------------------------------------------------------\n             |               Robust\n     ln_wage | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n         age |   .0153507   .0006913    22.21   0.000     .0139955    .0167059\n       union |   .1055274   .0098592    10.70   0.000     .0861981    .1248566\n    mean_age |  -.0070345   .0015342    -4.59   0.000    -.0100424   -.0040266\n  mean_union |   .2227511   .0220026    10.12   0.000     .1796142     .265888\n             |\n        race |\n      Black  |  -.1790995   .0143624   -12.47   0.000    -.2072575   -.1509415\n      Other  |   .0882461   .0715315     1.23   0.217    -.0519939    .2284861\n             |\n       _cons |   1.466452   .0426087    34.42   0.000     1.382916    1.549988\n------------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\nThe coefficients on `age` and `union` remain unchanged to seven digits, while the coefficient on `race` is identified (Black women earn $-17.9\\%$ relative to white women, $\\text{SE} = 0.0144$).\n\n## Two-way Mundlak and balanced panels\n\nWooldridge (2021) extends Mundlak's idea to Two-Way Fixed Effects (TWFE):\n\n$$y_{it} = X_{it}\\beta + c_i + f_t + u_{it}$$\n\nThe Two-Way Mundlak (TWM) estimator adds both unit means ($\\bar{X}_{i\\cdot}$) and time means ($\\bar{X}_{\\cdot t}$):\n\n$$y_{it} = X_{it}\\beta + \\bar{X}_{i\\cdot}\\lambda + \\bar{X}_{\\cdot t}\\theta + u_{it}$$\n\n### What changes in an unbalanced panel\n\nThe simple equivalence between TWM and TWFE requires the unit and time factors to be orthogonal. This holds automatically in a balanced panel, where every unit is observed in every period.\n\nIn an unbalanced panel, separate unit and time means do not span the two-way dummy-variable space. To recover the equivalence, we also include the unit means of the time dummies ($\\bar d_{it}$). These means describe each unit's observation pattern, $s_{it}/T_i$.\n\n\n::: {.cell collectcode='true'}\n\n```{.stata .cell-code}\npreserve\nwebuse nlswork, clear\nkeep if !missing(ln_wage, age, union)\nxtset idcode year\n\nbysort idcode: egen m_age   = mean(age)\nbysort idcode: egen m_union = mean(union)\negen t_age   = mean(age),   by(year)\negen t_union = mean(union), by(year)\n\n* Unit means of time dummies\nlevelsof year, local(yrs)\nforeach y of local yrs {\n    bysort idcode: egen my_`y' = mean(year==`y')\n}\n\nquietly xtreg ln_wage age union i.year, fe\nscalar b_twfe = _b[age]\n\n* Naive TWM with unit and time means only\nquietly regress ln_wage age union m_age m_union t_age t_union\nscalar b_twm = _b[age]\n\n* Correct TWM with unit means of time dummies\nquietly regress ln_wage age union m_age m_union i.year my_*\nscalar b_fix = _b[age]\n\ndi \"TWFE                           age = \" %9.7f b_twfe\ndi \"Naive TWM (unit + time means)  age = \" %9.7f b_twm\ndi \"TWM + unit means of dummies    age = \" %9.7f b_fix\n\nrestore\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(National Longitudinal Survey of Young Women, 14-24 years old in 1968)\n\n(9,305 observations deleted)\n\n\nPanel variable: idcode (unbalanced)\n Time variable: year, 70 to 88, but with gaps\n         Delta: 1 unit\n\n\n\n\n\n70 71 72 73 77 78 80 82 83 85 87 88\n\n\n\n\n\n\n\n\nTWFE                           age = 0.0276645\n\nNaive TWM (unit + time means)  age = 0.0117968\n\nTWM + unit means of dummies    age = 0.0276646\n```\n\n\n:::\n:::\n\n\nTWFE gives $\\hat\\beta_{\\text{age}}=0.0276645$. The simple TWM regression gives only $0.0117968$. Once we add the unit means of the time dummies, the estimate is $0.0276646$, equal to TWFE to six decimal places.\n\n## More than two fixed effects\n\nWith three or more fixed-effect factors, such as individual $i$, year $t$, and group $g$, one set of means for each dimension is not generally enough. It works only when the factors are mutually orthogonal, as in a Latin-square design. A safer approach is to eliminate the high-dimensional factor, usually the individual, keep dummies for the other factors, and add the within-individual means of every time-varying regressor, including those dummies.\n\n\n::: {.cell collectcode='true'}\n\n```{.stata .cell-code}\npreserve\ncapture program drop twm3\nprogram define twm3\n    args label\n    quietly {\n        capture drop x_i x_t x_g mt_* mg_* x y ft hg\n        sort t\n        by t: gen double ft = rnormal() if _n==1\n        by t: replace ft = ft[1]\n        sort g\n        by g: gen double hg = rnormal() if _n==1\n        by g: replace hg = hg[1]\n        gen double x = 0.6*ci + 0.5*ft + 0.4*hg + rnormal()\n        gen double y = 1*x + ci + ft + hg + rnormal()\n        bysort i: egen double x_i = mean(x)\n        bysort t: egen double x_t = mean(x)\n        bysort g: egen double x_g = mean(x)\n        levelsof t, local(ts)\n        foreach k of local ts {\n            bysort i: egen double mt_`k' = mean(t==`k')\n        }\n        levelsof g, local(gs)\n        foreach k of local gs {\n            bysort i: egen double mg_`k' = mean(g==`k')\n        }\n        areg y x i.t i.g, absorb(i)\n        scalar b_fe = _b[x]\n        regress y x x_i x_t x_g\n        scalar b_A = _b[x]\n        regress y x x_i i.t i.g mt_* mg_*\n        scalar b_B = _b[x]\n    }\n    di \"`label'\"\n    di \"   Three-way FE                      = \" %9.6f b_fe\n    di \"   A: One set of means per factor     = \" %9.6f b_A  \"   gap: \" %9.6f (b_A-b_fe)\n    di \"   B: Means over i, dummies included  = \" %9.6f b_B  \"   gap: \" %9.6f (b_B-b_fe)\nend\n\nclear\nset seed 20260731\nset obs 300\ngen i = _n\ngen double ci = rnormal()\nexpand 10\nbysort i: gen t = _n\n\n* Non-orthogonal design (random assignment of g)\ngen g = 1 + int(runiform()*5)\ntwm3 \"Non-orthogonal factor assignment:\"\n\n* Orthogonal design (Latin square)\nreplace g = mod(i+t,5)+1\ntwm3 \"Orthogonal factor assignment (Latin square):\"\n\ncapture program drop twm3\nrestore\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of observations (_N) was 0, now 300.\n\n\n\n(2,700 observations created)\n\n\n\nNon-orthogonal factor assignment:\n   Three-way FE                      =  0.994424\n   A: One set of means per factor     =  1.007648   gap:  0.013224\n   B: Means over i, dummies included  =  0.994424   gap:  0.000000\n\n(2,435 real changes made)\n\nOrthogonal factor assignment (Latin square):\n   Three-way FE                      =  0.996471\n   A: One set of means per factor     =  0.996471   gap:  0.000000\n   B: Means over i, dummies included  =  0.996471   gap:  0.000000\n```\n\n\n:::\n:::\n\n\nConstruction B (means over $i$ including factor dummies) is exact in both orthogonal and non-orthogonal designs.\n\n## Difference-in-differences with common timing\n\nIn standard DiD with common treatment timing:\n$$y_{it} = \\beta w_{it} + c_i + f_t + u_{it}$$\nwhere $w_{it} = d_i \\cdot \\text{post}_t$. Because $d_i$ is time-invariant and $\\text{post}_t$ is unit-invariant:\n- Unit mean: $\\bar{w}_{i\\cdot} = d_i \\cdot \\bar{p}$\n- Time mean: $\\bar{w}_{\\cdot t} = \\bar{d} \\cdot \\text{post}_t$\n\nSo we can span the Mundlak projection with $d_i$ and the post-treatment indicator, or with the full set of time dummies. We can also interact treatment with time to allow the treatment effect to vary:\n\n\n::: {.cell collectcode='true'}\n\n```{.stata .cell-code}\nclear\nset obs 100\nset seed 1234567\ngen id = _n\ngen w1 = rnormal()\ngen w2 = rnormal()\nexpand 4\nbysort id: gen year=2011+_n\ngen post=(year>2013)\ngen d=(id>50)\ngen w=d*post\ngen x1 = rnormal() + w1 + 2*w2\ngen u = rnormal()\n\ngen f2014=(year==2014)\ngen f2015=(year==2015)\n\n* DGP with growing treatment effect: 2.5 in 2014, 3.5 in 2015 (ATT = 3.0)\ngen y1 = 1 + 2*x1 + 3*w1 + u\ngen logy = y1 + 2.5*d*f2014 + 3.5*d*f2015\n\nxtset id year\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of observations (_N) was 0, now 100.\n\n\n\n\n\n(300 observations created)\n\n\n\n\n\n\n\n\n\n\n\n\nPanel variable: id (strongly balanced)\n Time variable: year, 2012 to 2015\n         Delta: 1 unit\n```\n\n\n:::\n:::\n\n\n\n::: {.cell collectcode='true'}\n\n```{.stata .cell-code}\n* 1. TWFE with year-specific treatment effects\nxtreg logy c.w#c.f2014 c.w#c.f2015 i.year, fe vce(cluster id)\n\n* 2. Pooled OLS with Mundlak controls (d and year dummies)\nreg logy c.w#c.f2014 c.w#c.f2015 d f2014 f2015, vce(cluster id)\nlincom (c.w#c.f2014 + c.w#c.f2015)/2\n\n* 3. Adding time-invariant controls (x1 and interaction with d)\nreg logy c.w#c.f2014 c.w#c.f2015 d f2014 f2015 x1 c.d#c.x1, vce(cluster id)\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFixed-effects (within) regression               Number of obs     =        400\nGroup variable: id                              Number of groups  =        100\n\nR-squared:                                      Obs per group:\n     Within  = 0.2575                                         min =          4\n     Between = 0.0129                                         avg =        4.0\n     Overall = 0.0387                                         max =          4\n\n                                                F(5, 99)          =      21.98\ncorr(u_i, Xb) = -0.0027                         Prob > F          =     0.0000\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |               Robust\n        logy | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n c.w#c.f2014 |   2.813593   .5368268     5.24   0.000     1.748412    3.878774\n             |\n c.w#c.f2015 |   3.600121   .5765523     6.24   0.000     2.456116    4.744126\n             |\n        year |\n       2013  |   .3260046   .3325494     0.98   0.329    -.3338456    .9858548\n       2014  |   -.341502   .4488412    -0.76   0.449      -1.2321    .5490964\n       2015  |   .4164204   .4300378     0.97   0.335    -.4368679    1.269709\n             |\n       _cons |  -.0817754   .2006423    -0.41   0.684    -.4798932    .3163424\n-------------+----------------------------------------------------------------\n     sigma_u |  6.7557992\n     sigma_e |  2.3288408\n         rho |  .89379082   (fraction of variance due to u_i)\n------------------------------------------------------------------------------\n\n\nLinear regression                               Number of obs     =        400\n                                                F(5, 99)          =      21.97\n                                                Prob > F          =     0.0000\n                                                R-squared         =     0.0384\n                                                Root MSE          =     7.0672\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |               Robust\n        logy | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n c.w#c.f2014 |   2.813593   .5368268     5.24   0.000     1.748412    3.878774\n             |\n c.w#c.f2015 |   3.600121   .5765523     6.24   0.000     2.456116    4.744126\n             |\n           d |  -.0636461    1.36017    -0.05   0.963    -2.762519    2.635227\n       f2014 |  -.5045043   .3923088    -1.29   0.201     -1.28293    .2739216\n       f2015 |   .2534181   .4206018     0.60   0.548    -.5811472    1.087983\n       _cons |     .11305   .9296453     0.12   0.903    -1.731568    1.957668\n------------------------------------------------------------------------------\n\n\n ( 1)  .5*c.w#c.f2014 + .5*c.w#c.f2015 = 0\n\n------------------------------------------------------------------------------\n        logy | Coefficient  Std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n         (1) |   3.206857   .4325887     7.41   0.000     2.348507    4.065207\n------------------------------------------------------------------------------\n\n\nLinear regression                               Number of obs     =        400\n                                                F(7, 99)          =     182.67\n                                                Prob > F          =     0.0000\n                                                R-squared         =     0.8438\n                                                Root MSE          =     2.8557\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |               Robust\n        logy | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n c.w#c.f2014 |   2.503103   .3066694     8.16   0.000     1.894605    3.111602\n             |\n c.w#c.f2015 |   3.327274   .2902385    11.46   0.000     2.751378     3.90317\n             |\n           d |    .881691   .5285779     1.67   0.098    -.1671223    1.930504\n       f2014 |   .0840872   .2215839     0.38   0.705    -.3555834    .5237578\n       f2015 |   .2391039   .2082552     1.15   0.254    -.1741196    .6523275\n          x1 |   2.506694   .1327049    18.89   0.000     2.243379     2.77001\n             |\n    c.d#c.x1 |   .0743163   .1915921     0.39   0.699     -.305844    .4544765\n             |\n       _cons |   .2148708   .3676352     0.58   0.560    -.5145972    .9443389\n------------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\nThe pooled Mundlak regression reproduces the TWFE estimates of 2.5 and 3.5 in the two post-treatment years. `lincom` gives their average, 3.0. We can add time-invariant controls and group interactions without changing these treatment-effect estimates.\n\n## What to remember\n\nFor a one-way model, adding unit means to pooled OLS or random effects recovers the within coefficient and lets us include time-invariant variables. For two-way models, the simple result holds in a balanced panel; an unbalanced panel also needs unit means of the time dummies. With more fixed-effect dimensions, I would eliminate the high-dimensional factor and retain explicit dummies for the others. The same formulation is useful in DiD because it accommodates time-varying effects and time-invariant moderators in an ordinary regression.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}