{
  "hash": "747e12c260f0ccf53839ee4b112ea4ba",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Mundlak device in fixed effect models\"\ndate: \"2021-10-23\"\n---\n\n\n\n\n## TWFE\n\nThe two-way fixed-effect model is standard for difference-in-differences with panel data:\n\n$$ y_{it} = X_{it} \\beta + c_i + f_t + u_{it} $$ {#eq-mundlak-device-1}\n\nwith $k$ covariates, $T$ periods, and $N$ units. In a linear model we can include $N$ unit dummies and $T$ time dummies, but this becomes impractical when either dimension is large. In nonlinear models the problem is worse.\n\n## TWM\n\n[Wooldridge (2021)](https://www.researchgate.net/publication/353938385_Two-Way_Fixed_Effects_the_Two-Way_Mundlak_Regression_and_Difference-in-Differences_Estimators) shows that the two-way Mundlak regression (TWM) works for both common and staggered treatment timing. This chapter covers the common-timing case; staggered timing is treated separately.\n\nThe idea goes back to Mundlak (1978). In the one-way case,\n\n$$ y_{it} = x_{it} \\beta + c_i + u_{it} $$ {#eq-mundlak-device-2}\n\nMundlak models $c_i$ as a function of the mean of $x_{it}$ for each unit:\n\n$$ c_i = \\bar x_i \\theta + \\eta_i $$ {#eq-mundlak-device-3}\n\nThen\n\n$$ y_{it} = x_{it} \\beta + \\bar x_i \\theta + \\eta_i + u_{it} $$ {#eq-mundlak-device-4}\n\nThe composite error is $\\eta_i + u_{it}$. Instead of $N$ unit dummies we add $k$ group means. This model can be estimated by pooled OLS or random effects; the coefficients are identical, and so are the standard errors once we cluster on units.\n\nA by-product: testing $\\theta = 0$ is the Mundlak form of the Hausman test. Under the random-effects assumptions it is asymptotically equivalent to the classical Hausman test, with the practical advantage of working directly with cluster-robust standard errors.\n\n\n\n\n::: {.cell collectcode='true'}\n\n```{.stata .cell-code}\n\nclear\nwebuse nlswork\nxtset idcode year\ndrop if union==.\ndrop if age==.\nbysort idcode: egen mean_age=mean(age)\nbysort idcode: egen mean_union=mean(union)\nxtreg ln_wage age union, fe cluster(idcode)\nreg ln_wage age union mean_age mean_union, cluster(idcode)\nxtreg ln_wage age union mean_age mean_union, re cluster(idcode)\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(National Longitudinal Survey of Young Women, 14-24 years old in 1968)\n\n\nPanel variable: idcode (unbalanced)\n Time variable: year, 68 to 88, but with gaps\n         Delta: 1 unit\n\n(9,296 observations deleted)\n\n(9 observations deleted)\n\n\n\n\nFixed-effects (within) regression               Number of obs     =     19,229\nGroup variable: idcode                          Number of groups  =      4,150\n\nR-squared:                                      Obs per group:\n     Within  = 0.0963                                         min =          1\n     Between = 0.0433                                         avg =        4.6\n     Overall = 0.0562                                         max =         12\n\n                                                F(2, 4149)        =     331.52\ncorr(u_i, Xb) = 0.0127                          Prob > F          =     0.0000\n\n                             (Std. err. adjusted for 4,150 clusters in idcode)\n------------------------------------------------------------------------------\n             |               Robust\n     ln_wage | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n         age |   .0153507   .0006912    22.21   0.000     .0139956    .0167058\n       union |   .1055274   .0098582    10.70   0.000     .0862001    .1248546\n       _cons |   1.248435   .0215661    57.89   0.000     1.206154    1.290716\n-------------+----------------------------------------------------------------\n     sigma_u |  .42353003\n     sigma_e |  .26213464\n         rho |  .72302816   (fraction of variance due to u_i)\n------------------------------------------------------------------------------\n\n\nLinear regression                               Number of obs     =     19,229\n                                                F(4, 4149)        =     234.77\n                                                Prob > F          =     0.0000\n                                                R-squared         =     0.0769\n                                                Root MSE          =     .44953\n\n                             (Std. err. adjusted for 4,150 clusters in idcode)\n------------------------------------------------------------------------------\n             |               Robust\n     ln_wage | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n         age |   .0153507   .0006912    22.21   0.000     .0139956    .0167059\n       union |   .1055274   .0098587    10.70   0.000     .0861991    .1248556\n    mean_age |  -.0064208    .001548    -4.15   0.000    -.0094556   -.0033859\n  mean_union |   .1900785   .0223172     8.52   0.000     .1463249    .2338321\n       _cons |   1.405264    .042734    32.88   0.000     1.321482    1.489046\n------------------------------------------------------------------------------\n\n\nRandom-effects GLS regression                   Number of obs     =     19,229\nGroup variable: idcode                          Number of groups  =      4,150\n\nR-squared:                                      Obs per group:\n     Within  = 0.0963                                         min =          1\n     Between = 0.0750                                         avg =        4.6\n     Overall = 0.0768                                         max =         12\n\n                                                Wald chi2(4)      =    1023.99\ncorr(u_i, X) = 0 (assumed)                      Prob > chi2       =     0.0000\n\n                             (Std. err. adjusted for 4,150 clusters in idcode)\n------------------------------------------------------------------------------\n             |               Robust\n     ln_wage | Coefficient  std. err.      z    P>|z|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n         age |   .0153507   .0006912    22.21   0.000     .0139959    .0167055\n       union |   .1055274   .0098587    10.70   0.000     .0862047      .12485\n    mean_age |  -.0061464   .0014254    -4.31   0.000    -.0089401   -.0033527\n  mean_union |    .212183   .0210098    10.10   0.000     .1710046    .2533614\n       _cons |   1.362101   .0383784    35.49   0.000     1.286881    1.437322\n-------------+----------------------------------------------------------------\n     sigma_u |  .38505558\n     sigma_e |  .26213464\n         rho |  .68331727   (fraction of variance due to u_i)\n------------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\nAll three models return the same coefficients and standard errors on age and union. On the 19,229 person-years of `nlswork` with non-missing union and age, every one of them gives `age` = .0153507 with a clustered standard error of .00069 and `union` = .1055274 with .00986 — agreeing to the last printed digit, with only the confidence bounds differing in the seventh decimal. The $N$ unit dummies of `xtreg, fe` have been replaced by two group means, and nothing was lost.\n\nWooldridge (2021) extends this to the two-way case. For the TWFE,\n$$ y_{it} = X_{it} \\beta + c_i + f_t + u_{it} $$ {#eq-mundlak-device-5}\nit's equivalent to estimate\n\n$$ y_{it} = X_{it} \\beta + X_{i \\cdot} \\lambda + X_{\\cdot t} \\theta + u_{it} $$ {#eq-mundlak-device-6}\n\nwhere $X_{i \\cdot}$ is the unit-specific average over time and $X_{\\cdot t}$ is the time-specific average over units. By FWL, the two models are equivalent (see Wooldridge 2021 for the proof). Wooldridge calls this the two-way Mundlak (TWM) model.\n\nTWM has two advantages over the dummy-variable approach. It can sharply reduce the number of regressors. And it allows time-invariant or unit-invariant variables in the regression without disturbing the $\\beta$ estimates.\n\nWe can see in the following example of POLS (which is TWM), we add in `race`, which is **time-invariant** --- constant within a person, but varying across people.  (In `nlswork` the within-person standard deviation of `race` is exactly 0, while within any given year it is about 0.50, so it is emphatically not unit-invariant.)  It can be estimated in TWM, but would not be estimable in TWFE.  Notice that coefficients on age and union remain unchanged.\n\nThe reason is *not* that `race` is orthogonal to the other regressors --- it is not orthogonal to the unit means `mean_age` and `mean_union`.  It is that the variation identifying $\\beta$ is the within-unit variation, and within-unit deviations are orthogonal to **any** unit-level variable by construction, since $\\sum_t (x_{it} - \\bar x_i) = 0$ for every $i$.  Adding a unit-level regressor therefore cannot move $\\beta$, whatever that regressor happens to be.  A genuinely unit-invariant variable --- one constant across units within a period, such as a time dummy --- leaves $\\beta$ unchanged for the mirror-image reason.\n\n\n\n::: {.cell}\n\n```{.stata .cell-code}\n\nreg ln_wage age union mean_age mean_union i.race, cluster(idcode)\n\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear regression                               Number of obs     =     19,229\n                                                F(6, 4149)        =     189.66\n                                                Prob > F          =     0.0000\n                                                R-squared         =     0.1069\n                                                Root MSE          =      .4422\n\n                             (Std. err. adjusted for 4,150 clusters in idcode)\n------------------------------------------------------------------------------\n             |               Robust\n     ln_wage | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n         age |   .0153507   .0006913    22.21   0.000     .0139955    .0167059\n       union |   .1055274   .0098592    10.70   0.000     .0861981    .1248566\n    mean_age |  -.0070345   .0015342    -4.59   0.000    -.0100424   -.0040266\n  mean_union |   .2227511   .0220026    10.12   0.000     .1796142     .265888\n             |\n        race |\n      Black  |  -.1790995   .0143624   -12.47   0.000    -.2072575   -.1509415\n      Other  |   .0882461   .0715315     1.23   0.217    -.0519939    .2284861\n             |\n       _cons |   1.466452   .0426087    34.42   0.000     1.382916    1.549988\n------------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\nAnd indeed `age` stays at .0153507 and `union` at .1055274, unchanged to seven\ndigits by the addition of `i.race`, while race itself is estimated: Black women\nearn 17.9% less ($-.1790995$, SE .0144). A fixed-effect model could report the\nfirst two numbers but not the third.\n\n## An important qualification: TWM needs a balanced panel\n\nThe two-way equivalence above holds for a **balanced** panel.  It is worth stating this\nexplicitly, because the one-way result does *not* need balance and the contrast is easy to\nmiss.\n\nThe one-way version --- regressing $y_{it}$ on $X_{it}$ and $X_{i \\cdot}$ --- is exact\nwhatever the panel looks like, for the reason given below: $\\sum_t (x_{it} - \\bar x_i) = 0$\nholds within each unit by construction, no matter how many periods that unit contributes.\n\nThe two-way version needs something stronger.  Subtracting both margins and adding back the\ngrand mean, $x_{it} - \\bar x_{i \\cdot} - \\bar x_{\\cdot t} + \\bar x$, is the projection onto\n*both* sets of dummies only when the unit and time factors are **orthogonal** --- that is,\nwhen every unit appears in every period.  In a balanced panel that holds automatically.  In\nan unbalanced panel it fails, and TWM is then simply a different estimator from TWFE.\n\nThe difference is large enough to matter in applied work.  Using `nlswork`, which is unbalanced (persons contribute between 1\nand 12 observations), the coefficient on `age` differs by more than a factor of two:\n\n\n::: {.cell collectcode='true'}\n\n```{.stata .cell-code}\n* preserve/restore so this illustration leaves the data as later chunks expect\npreserve\nwebuse nlswork, clear\nkeep if !missing(ln_wage, age, union)\nxtset idcode year\n\nbysort idcode: egen m_age   = mean(age)\nbysort idcode: egen m_union = mean(union)\negen t_age   = mean(age),   by(year)\negen t_union = mean(union), by(year)\n\n* unit means of the year dummies -- the terms the unbalanced case needs\nlevelsof year, local(yrs)\nforeach y of local yrs {\n    bysort idcode: egen my_`y' = mean(year==`y')\n}\n\nquietly xtreg ln_wage age union i.year, fe\nscalar b_twfe = _b[age]\nquietly regress ln_wage age union m_age m_union t_age t_union\nscalar b_twm = _b[age]\nquietly regress ln_wage age union m_age m_union i.year my_*\nscalar b_fix = _b[age]\n\ndi \"TWFE                      age = \" %9.7f b_twfe\ndi \"TWM (unit + time means)   age = \" %9.7f b_twm\ndi \"TWM + unit means of dummies   = \" %9.7f b_fix\n\nrestore\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(National Longitudinal Survey of Young Women, 14-24 years old in 1968)\n\n(9,305 observations deleted)\n\n\nPanel variable: idcode (unbalanced)\n Time variable: year, 70 to 88, but with gaps\n         Delta: 1 unit\n\n\n\n\n\n70 71 72 73 77 78 80 82 83 85 87 88\n\n\n\n\n\n\n\n\nTWFE                      age = 0.0276645\n\nTWM (unit + time means)   age = 0.0117968\n\nTWM + unit means of dummies   = 0.0276646\n```\n\n\n:::\n:::\n\n\nThe numbers make the point. TWFE gives `age` = 0.0276645; two-way Mundlak with\nunit and time means gives 0.0117968 — 43% of it, a factor of 2.35 apart. These\nare not two estimates of the same thing that happen to disagree; on an\nunbalanced panel they are different estimators.\n\nWhat restores the equivalence is including the **unit means of the time dummies**.  Adding them\nbrings TWM to 0.0276646 against TWFE's 0.0276645 — agreement to six decimal\nplaces, on the same unbalanced data that produced the factor-of-two gap.  They have a\nclear meaning: the unit mean of the dummy for period $t$ is $s_{it}/T_i$, where $s_{it}$\nindicates whether unit $i$ is observed in period $t$.  So adding them amounts to conditioning on\n*which* periods each unit is observed in --- the panel's selection pattern.  This is the\nconditioning set in Wooldridge's work on correlated random effects with unbalanced panels.\n\nTwo practical notes.  In a balanced panel these extra terms have zero variance --- every unit\nis observed in every period, so each mean is $1/T$ for everybody --- which is exactly why they\nnever come up in the balanced case.  And the number of observations per unit, $T_i$, is *not* a\nsubstitute for them: it does not restore exactness, and it is collinear with them once they are\nincluded.\n\nEverything in this section is about the *point estimate*.  Standard errors from TWM are not the\nTWFE standard errors, and should not be read as such.\n\nIt is worth pausing on the fact that this chapter now demonstrates both results on the *same*\ndata.  The `xtreg` example near the top shows one-way Mundlak matching one-way FE on `nlswork`, and\nthe chunk just above shows two-way Mundlak failing on `nlswork`.  Same dataset, opposite verdicts,\nbecause the two claims do not have the same requirements.  The one-way result needs nothing:\n$\\sum_t (x_{it} - \\bar x_i) = 0$ holds within each unit whatever periods that unit contributes, so\n$T_i$ may vary freely.  The two-way result needs the unit and time factors to be orthogonal *to each\nother*, which is a statement about the relationship between two dimensions, and that is what\nimbalance destroys.  Nothing one-way can be affected, because there is no second dimension for the\nfirst to fail to be orthogonal to.\n\n**Which regressors need means, then?**  Those that vary within unit.  This is why `i.race` above\ntakes no mean: `race` is constant within a person, so its within-person mean *is* `race` --- in\n`nlswork` the two agree to the last digit --- and adding it would be perfectly collinear.  A year\ndummy is the opposite case: it does vary within a person (in `nlswork` the within-person standard\ndeviation of the 1971 dummy is about 0.71), so its unit mean is not the dummy but the fraction of\nthat person's observations falling in that year.  That fraction is new information, and in an\nunbalanced panel it is exactly the information the equivalence needs.\n\n## More than two fixed effects: one set of means, not one per dimension\n\nThe natural guess, having seen TWM, is that three fixed effects call for three sets of means ---\n$X_{i \\cdot}$, $X_{\\cdot t}$, and the averages over the third factor.  That guess is wrong in general,\nand the reason is worth spelling out because it also explains the balanced-panel condition above.\n\nThe Mundlak device deals with **one** unobserved effect at a time.  It replaces $c_i$ by its projection\non the within-$i$ means of the other regressors.  So the number of sets of means you need is the number\nof dimensions you are *eliminating*, not the number of dimensions you have.  With three fixed effects the\nrobust recipe is:\n\n- pick the dimension you cannot estimate --- typically the one with many levels and few observations\n  each --- and replace it with means;\n- **keep the other dimensions as dummies**, since they have few levels and many observations each;\n- take the means over the chosen dimension of *everything else in the model*, the retained dummies\n  included.\n\nThat last clause is what does the work, and it is the same clause that fixes the unbalanced two-way case\nabove.  The test for whether a given regressor needs a mean is the one stated there: does it vary\nwithin the dimension you are eliminating?  Time and group dummies do, so their means carry\ninformation; a regressor already constant within unit does not, so its mean is itself.  Call this construction **B**, and call the three-sets-of-means guess **A**.\n\n\n::: {.cell collectcode='true'}\n\n```{.stata .cell-code}\npreserve\ncapture program drop twm3\nprogram define twm3\n    args label\n    quietly {\n        capture drop x_i x_t x_g mt_* mg_* x y ft hg\n        sort t\n        by t: gen double ft = rnormal() if _n==1\n        by t: replace ft = ft[1]\n        sort g\n        by g: gen double hg = rnormal() if _n==1\n        by g: replace hg = hg[1]\n        gen double x = 0.6*ci + 0.5*ft + 0.4*hg + rnormal()\n        gen double y = 1*x + ci + ft + hg + rnormal()\n        bysort i: egen double x_i = mean(x)\n        bysort t: egen double x_t = mean(x)\n        bysort g: egen double x_g = mean(x)\n        levelsof t, local(ts)\n        foreach k of local ts {\n            bysort i: egen double mt_`k' = mean(t==`k')\n        }\n        levelsof g, local(gs)\n        foreach k of local gs {\n            bysort i: egen double mg_`k' = mean(g==`k')\n        }\n        areg y x i.t i.g, absorb(i)\n        scalar b_fe = _b[x]\n        regress y x x_i x_t x_g\n        scalar b_A = _b[x]\n        regress y x x_i i.t i.g mt_* mg_*\n        scalar b_B = _b[x]\n    }\n    di \"`label'\"\n    di \"   three-way FE                       = \" %9.6f b_fe\n    di \"   A: one set of means per dimension   = \" %9.6f b_A  \"   gap \" %9.6f (b_A-b_fe)\n    di \"   B: means over i, dummies included   = \" %9.6f b_B  \"   gap \" %9.6f (b_B-b_fe)\nend\n\nclear\nset seed 20260731\nset obs 300\ngen i = _n\ngen double ci = rnormal()\nexpand 10\nbysort i: gen t = _n\n\n* third factor assigned at random: the three factors are not orthogonal\ngen g = 1 + int(runiform()*5)\ntwm3 \"g assigned at random (NOT orthogonal):\"\n\n* Latin square: every unit sees every g equally, and so does every period\nreplace g = mod(i+t,5)+1\ntwm3 \"g from a Latin square (orthogonal):\"\n\ncapture program drop twm3\nrestore\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of observations (_N) was 0, now 300.\n\n\n\n(2,700 observations created)\n\n\n\ng assigned at random (NOT orthogonal):\n   three-way FE                       =  0.994424\n   A: one set of means per dimension   =  1.007648   gap  0.013224\n   B: means over i, dummies included   =  0.994424   gap  0.000000\n\n(2,435 real changes made)\n\ng from a Latin square (orthogonal):\n   three-way FE                       =  0.996471\n   A: one set of means per dimension   =  0.996471   gap  0.000000\n   B: means over i, dummies included   =  0.996471   gap  0.000000\n```\n\n\n:::\n:::\n\n\nWith `g` assigned at random, the three-way fixed-effect estimate is 0.994424.\nConstruction B reproduces it exactly, gap 0.000000; construction A gives\n1.007648, a gap of 0.013224. Replace the random assignment with a Latin square,\nwhich makes the three factors mutually orthogonal, and all three agree at\n0.996471 with both gaps at 0.000000.\n\nSo **A is not incorrect but conditional**: it is exact when the factors are mutually orthogonal, and\ninexact otherwise.  A full factorial design gives orthogonality, but so does a Latin square, which\nfills only a fraction of the possible cells --- what matters is the balance property, that each level of\none factor appears equally often with each level of the others, not the number of cells.  Deleting a\nsingle row from either design is enough to lose exactness, and the size of the gap tracks how far from\northogonal the design is.\n\nThis is the general statement of the balanced-panel condition from the previous section.  A balanced\ntwo-way panel *is* an orthogonal design: every unit appears in every period.  Unbalance it, and the unit\nand time factors stop being orthogonal, which is why the two-way equivalence fails there.\n\nThe practical reading is that orthogonality is a property of **designed** data --- factorial experiments,\nLatin squares, crop trials, where somebody chose the assignment.  It requires each level of one factor to\nappear equally often with each level of the others, which is not something that happens by accident in\ndata you did not design.  A third factor tends to make matters worse rather than better, because it is\nfrequently determined in part by the first two.  In an audit panel I looked at recently, for instance, the third fixed effect was the\nrunning count of audits within a factory, which is mechanically a function of factory and calendar time;\nthat design cannot be orthogonal even in principle.  For observational work, B is the construction to\nuse.\n\n## Applications of TWM to DID in common treatment timing\n\nThere is an extension: if $x_{it}$ can be written as an interaction between a time-invariant and a unit-invariant variable,\n\n$$ x_{itj} = z_{ij} * m_{tj} $$ {#eq-mundlak-device-7}\n\nThen\n\n$$ \\bar x_{i \\cdot j} = z_{ij} \\bar m_j $$ {#eq-mundlak-device-8}\n$$ \\bar x_{\\cdot t j} = \\bar z_{j}  m_{tj} $$ {#eq-mundlak-device-9}\n\nThe two averages are just constants times $z_{ij}$ and $m_{tj}$ respectively. So by Mundlak we can include $z_{ij}$ and $m_{tj}$ as controls instead.\n\nWooldridge (2021) shows that TWM extends to staggered timing as well, provided we allow flexible interactions of treatment cohorts and periods. The simulation below covers the common-timing case. The code follows Wooldridge's do files.\n\nIn the common-timing setting all treated units are treated at the same period. The identifying assumptions are parallel trends and no anticipation.\n\n\n$$ y_{it} = w_{it} \\beta + c_i + f_t + u_{it} $$ {#eq-mundlak-device-10}\n\nwhere $w_{it}$ is the treatment indicator, with $T$ periods and treatment happens at $t=q$.\n\n$$ w_{it} = d_i \\cdot p_t $$ {#eq-mundlak-device-11}\n\nwhere $d_i$ is the treatment group dummy, and $p_t$ is the post treatment dummy.\n\n$$ \\bar w_{i \\cdot} = d_i \\cdot \\bar p $$ {#eq-mundlak-device-12}\n$$ \\bar w_{ \\cdot t} = \\bar d \\cdot  p_t $$ {#eq-mundlak-device-13}\n\nTherefore, we just need to include $d_i$ and $p_t$ as controls in the regression to be the same estimator as TWFE, by the spirit of Mundlak.\n\nThat is, instead of doing TWFE, we can do TWM by regressing $y$ on $w$, $d_i$ and $p_t$.\n\nMoreover, in a TWM, we can include any time-invariant or unit-invariant controls, or both and have no effect on $\\beta$.\n\nWe can also allow the effect to change across time post treatment by doing\n\n$$y_{it} = \\alpha + \\beta_q (w_{it} \\cdot f_q) + \\dots + \\beta_T (w_{it} \\cdot f_T) + \\eta d_i + \\theta_q f_q + \\dots + \\theta_T f_T + e_{it} $$ {#eq-mundlak-device-14}\n\nIn the TWM, we allow effects change from $t=q$ to $t=T$, by interacting $w_{it}$ and $f_t$, which is an dummy for time $t$.  Very flexible, yet easy to do, given everything is linear.\n\nEven more, if we have another variable, $x_i$, say gender, which is time-invariant, we can allow the effect to be different across gender, across time!\n\nNow I use Wooldridge's code to run on a simulated data set.\n\nThe simulation has 100 units observed over 2012–2015, 400 observations, with\ncommon treatment timing. Each unit draws time-invariant $w_1, w_2 \\sim N(0,1)$.\nUnits with `id > 50` are treated ($d = 1$, so 50 treated and 50 control), the\npost period is 2014–2015, and $w_{it} = d_i \\cdot \\text{post}_t$. The covariate\nis $x_1 = N(0,1) + w_1 + 2w_2$, correlated with the unit effects by\nconstruction, and the untreated outcome is\n$y_1 = 1 + 2x_1 + 3w_1 + u$ with $u \\sim N(0,1)$. The observed outcome adds a\ntreatment effect that grows over time,\n\n$$\n\\text{logy} = y_1 + 2.5\\,d_i f_{2014} + 3.5\\,d_i f_{2015}.\n$$ {#eq-mundlak-device-15}\n\nSo the true effect is 2.5 in the first post year and 3.5 in the second, and\nbecause the panel is balanced the overall ATT is their average, exactly 3.\n\n::: {.cell collectcode='true'}\n\n```{.stata .cell-code}\nclear\nset obs 100\nset seed 1234567\ngen id = _n\ngen w1 = rnormal()\ngen w2 = rnormal()\nexpand 4\nbysort id: gen year=2011+_n\ngen post=(year>2013)\ngen d=(id>50)\ngen w=d*post\ngen x1 = rnormal() + w1 + 2*w2\ngen u = rnormal()\n\ngen f2014=(year==2014)\ngen f2015=(year==2015)\n\ngen y1 = 1 +2*x1 + 3*w1  + u\n* let's allow each year's treatment effect being different.  ATT for post period would be roughly 3, because of balanced panel.\ngen logy = y1 + 2.5*d*f2014 + 3.5*d*f2015\n\nxtset id year\ntab year w\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of observations (_N) was 0, now 100.\n\n\n\n\n\n(300 observations created)\n\n\n\n\n\n\n\n\n\n\n\n\nPanel variable: id (strongly balanced)\n Time variable: year, 2012 to 2015\n         Delta: 1 unit\n\n           |           w\n      year |         0          1 |     Total\n-----------+----------------------+----------\n      2012 |       100          0 |       100 \n      2013 |       100          0 |       100 \n      2014 |        50         50 |       100 \n      2015 |        50         50 |       100 \n-----------+----------------------+----------\n     Total |       300        100 |       400 \n```\n\n\n:::\n:::\n\n\nWe have 100 units over four years (2012--2015). Half are treated starting in 2014 ($w = d \\times \\text{post}$). The treatment effect is 2.5 in 2014 and 3.5 in 2015, so the overall post-period ATT should be about 3 in this balanced panel.\n\nThe code below is from Wooldridge. The main difficulty is specifying the correct interaction terms for each estimand.\n\n\n::: {.cell}\n\n```{.stata .cell-code}\n* CACHE WARNING: this chunk depends on the data built by the earlier\n* `collectcode: true` chunks.  If those are served from the knitr cache while\n* this one re-executes, their code never enters Statamarkdown's accumulated\n* buffer, every command below fails on missing data, and the chunk silently\n* renders with NO output.  If that happens, delete the whole\n* `mundlak-device_cache/` directory (not just this chunk's entry) and\n* `_freeze/mundlak-device/`, then re-render so all chunks run in order.\n\n\n* Basic DID regression. Only need the post-treatment dummy but including\n* all time dummies is harmless (and necessary for heterogeneous trends).\n* Standard errors change a little because of different degrees-of-freedom.\n\nreg logy c.d#c.post d post, vce(cluster id)\nreg logy w d post, vce(cluster id)\nreg logy w d f2014 f2015, vce(cluster id)\nreg logy w d i.year, vce(cluster id)\n\n* Using fixed effects is equivalent:\n\nxtreg logy w i.year, fe vce(cluster id)\nxtreg logy w post, fe vce(cluster id)\n\n* So is RE with d included:\nxtreg logy w d post, re vce(cluster id)\n\n* Allow a separate effect in each of the treated time periods:\n* It is the ATT for each treated period:\n\nxtreg logy c.w#c.f2014 c.w#c.f2015 i.year, fe vce(cluster id)\nxtreg logy c.d#c.f2014 c.d#c.f2015 i.year, fe vce(cluster id)\n\n* POLS version:\n\nreg logy c.w#c.f2014 c.w#c.f2015 d f2014 f2015, vce(cluster id)\nlincom (c.w#c.f2014 + c.w#c.f2015)/2\n\n* RE still gives same estimates:\n\nxtreg logy c.w#c.f2014 c.w#c.f2015 d f2014 f2015, re vce(cluster id)\n\n* Putting in time-constant controls in the levels and even interacted with d\n* does not change the estimates. It does boost the R-squared and\n* slightly changes the standard errors:\n\nreg logy c.w#c.f2014 c.w#c.f2015 d f2014 f2015 x1 c.d#c.x1, vce(cluster id)\nreg logy c.w#c.f2014 c.w#c.f2015 d i.year x1 c.d#c.x1, vce(cluster id)\n\n* Now add covariate interacted with everything:\n\nsum x1 if d\ngen x1_dm_1 = x1 - r(mean)\n\nxtreg logy c.w#c.f2014 c.w#c.f2015 c.w#c.f2014#c.x1_dm_1 c.w#c.f2015#c.x1_dm_1 i.year c.f2014#c.x1 c.f2015#c.x1,  fe vce(cluster id)\n\nreg logy c.w#c.f2014 c.w#c.f2015 c.w#c.f2014#c.x1_dm_1 c.w#c.f2015#c.x1_dm_1 i.year c.f2014#c.x1 c.f2015#c.x1 d x1 c.d#c.x1, vce(cluster id)\n\nreg logy c.w#c.f2014 c.w#c.f2015 c.w#c.f2014#c.x1_dm_1 c.w#c.f2015#c.x1_dm_1 i.year i.year#c.x1 d x1 c.d#c.x1, vce(cluster id)\n\n* Now use margins to account for the sampling error in the mean of x1. It is\n* important to have w defined as the time-varying treatment variable.\n* In practice, it seems to have little effect:\n\nreg logy c.w#c.f2014 c.w#c.f2015 c.w#c.f2014#c.x1 c.w#c.f2015#c.x1 i.year c.f2014#c.x1 c.f2015#c.x1 d x1 c.d#c.x1, vce(cluster id)\nmargins, dydx(w) at(f2014 = 1 f2015 = 0) subpop(if d == 1) vce(uncond)\nmargins, dydx(w) at(f2014 = 0 f2015 = 1) subpop(if d == 1) vce(uncond)\n\n* Apply Callaway & Sant'Anna (2021):\n\ngen first_treat = 0\nreplace first_treat = 2014 if d\ncsdid logy x1, ivar(id) time(year) gvar(first_treat)\n\n* Show imputation is equivalent to POLS/ETWFE:\n\nreg logy i.year c.f2014#c.x1 c.f2015#c.x1 d x1 c.d#c.x1 if w == 0\npredict tetilda, resid\nsum tetilda if (d & f2014)\nsum tetilda if (d & f2015)\n\n* Regression produces same ATT estimates, but use the full pooled regression for\n* valid standard errors:\n\nreg tetilda c.w#c.f2014 c.w#c.f2015 c.w#c.f2014#c.x1_dm_1 c.w#c.f2015#c.x1_dm_1 if w == 1, nocons\n\n* Now test parallel trends. First, unconditionally.\n\nxtdidreg (logy) (w), group(id) time(year)\n* estat trendplots\nestat ptrends\n\n* With two control periods, same as the following:\n* Note: since the pre-period only spans 2012-2013, D.logy is non-missing\n* only for year==2013, so this is a single cross-section of first\n* differences (2013 vs 2012), not a multi-period trend test — it's a\n* valid two-period parallel-trends check, but should not be read as\n* testing trends across more than two pre-periods.\n\nsort id year\nreg D.logy d if year <= 2013, vce(robust)\n\n* Test/correct for common trends in a general equation:\n\ngen t = year - 2011\n\nxtreg logy c.w#c.f2014 c.w#c.f2015 c.w#c.f2014#c.x1_dm_1 c.w#c.f2015#c.x1_dm_1 i.year i.year#c.x1 c.d#c.t,  fe vce(cluster id)\n\nreg logy c.w#c.f2014 c.w#c.f2015 c.w#c.f2014#c.x1_dm_1 c.w#c.f2015#c.x1_dm_1 i.year i.year#c.x1 d x1 c.d#c.x1 c.d#c.t, vce(cluster id)\n\n* Allow the trend to also vary with x1:\n\nreg logy c.w#c.f2014 c.w#c.f2015 c.w#c.f2014#c.x1_dm_1 c.w#c.f2015#c.x1_dm_1 i.year i.year#c.x1 d x1 c.d#c.x1 c.d#c.t c.d#c.t#c.x1, vce(cluster id)\ntest c.d#c.t c.d#c.t#c.x1\n\n* Imputation. Note that the estimates on c.d#c.t and c.d#c.t#c.x1\n* are the same as full regression with all data, as is the joint\n* F statistic:\n\ndrop tetilda\n\nreg logy i.year i.year#c.x1 d x1 c.d#c.x1 c.d#c.t c.d#c.t#c.x1 if w == 0, vce(cluster id)\ntest c.d#c.t c.d#c.t#c.x1\n\npredict tetilda, resid\nsum tetilda if (d & f2014)\nsum tetilda if (d & f2015)\n\n* Again, can use regression to obtain the estimates but not the standard errors:\n\nreg tetilda c.w#c.f2014 c.w#c.f2015 c.w#c.f2014#c.x1_dm_1 c.w#c.f2015#c.x1_dm_1 if w == 1, nocons\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear regression                               Number of obs     =        400\n                                                F(3, 99)          =      34.04\n                                                Prob > F          =     0.0000\n                                                R-squared         =     0.0348\n                                                Root MSE          =     7.0626\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |               Robust\n        logy | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n  c.d#c.post |   3.206857   .4314949     7.43   0.000     2.350677    4.063036\n             |\n           d |  -.0636461   1.356731    -0.05   0.963    -2.755695    2.628403\n        post |  -.1255431   .3021942    -0.42   0.679     -.725162    .4740758\n       _cons |     .11305   .9272947     0.12   0.903    -1.726904    1.953004\n------------------------------------------------------------------------------\n\n\nLinear regression                               Number of obs     =        400\n                                                F(3, 99)          =      34.04\n                                                Prob > F          =     0.0000\n                                                R-squared         =     0.0348\n                                                Root MSE          =     7.0626\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |               Robust\n        logy | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n           w |   3.206857   .4314949     7.43   0.000     2.350677    4.063036\n           d |  -.0636461   1.356731    -0.05   0.963    -2.755695    2.628403\n        post |  -.1255431   .3021942    -0.42   0.679     -.725162    .4740758\n       _cons |     .11305   .9272947     0.12   0.903    -1.726904    1.953004\n------------------------------------------------------------------------------\n\n\nLinear regression                               Number of obs     =        400\n                                                F(4, 99)          =      27.19\n                                                Prob > F          =     0.0000\n                                                R-squared         =     0.0381\n                                                Root MSE          =     7.0597\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |               Robust\n        logy | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n           w |   3.206857   .4320407     7.42   0.000     2.349594    4.064119\n           d |  -.0636461   1.358447    -0.05   0.963      -2.7591    2.631808\n       f2014 |  -.7011363   .3419429    -2.05   0.043    -1.379625   -.0226474\n       f2015 |   .4500501   .3583234     1.26   0.212    -.2609413    1.161041\n       _cons |     .11305   .9284678     0.12   0.903    -1.729232    1.955331\n------------------------------------------------------------------------------\n\n\nLinear regression                               Number of obs     =        400\n                                                F(5, 99)          =      21.95\n                                                Prob > F          =     0.0000\n                                                R-squared         =     0.0383\n                                                Root MSE          =     7.0677\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |               Robust\n        logy | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n           w |   3.206857   .4325887     7.41   0.000     2.348507    4.065207\n           d |  -.0636461    1.36017    -0.05   0.963    -2.762519    2.635227\n             |\n        year |\n       2013  |   .3260046   .3325494     0.98   0.329    -.3338456    .9858548\n       2014  |   -.538134   .3934578    -1.37   0.175     -1.31884    .2425716\n       2015  |   .6130524   .3830314     1.60   0.113     -.146965     1.37307\n             |\n       _cons |  -.0499523   .9214237    -0.05   0.957    -1.878257    1.778352\n------------------------------------------------------------------------------\n\n\nFixed-effects (within) regression               Number of obs     =        400\nGroup variable: id                              Number of groups  =        100\n\nR-squared:                                      Obs per group:\n     Within  = 0.2539                                         min =          4\n     Between = 0.0129                                         avg =        4.0\n     Overall = 0.0383                                         max =          4\n\n                                                F(4, 99)          =      27.29\ncorr(u_i, Xb) = -0.0027                         Prob > F          =     0.0000\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |               Robust\n        logy | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n           w |   3.206857   .4320407     7.42   0.000     2.349594    4.064119\n             |\n        year |\n       2013  |   .3260046   .3321282     0.98   0.329    -.3330098     .985019\n       2014  |   -.538134   .3929594    -1.37   0.174    -1.317851    .2415828\n       2015  |   .6130524   .3825463     1.60   0.112    -.1460024    1.372107\n             |\n       _cons |  -.0817754   .2003881    -0.41   0.684    -.4793889    .3158381\n-------------+----------------------------------------------------------------\n     sigma_u |  6.7557992\n     sigma_e |  2.3305153\n         rho |  .89365429   (fraction of variance due to u_i)\n------------------------------------------------------------------------------\n\n\nFixed-effects (within) regression               Number of obs     =        400\nGroup variable: id                              Number of groups  =        100\n\nR-squared:                                      Obs per group:\n     Within  = 0.2207                                         min =          4\n     Between = 0.0129                                         avg =        4.0\n     Overall = 0.0348                                         max =          4\n\n                                                F(2, 99)          =      50.25\ncorr(u_i, Xb) = -0.0028                         Prob > F          =     0.0000\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |               Robust\n        logy | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n           w |   3.206857   .4309511     7.44   0.000     2.351756    4.061957\n        post |  -.1255431   .3018134    -0.42   0.678    -.7244064    .4733201\n       _cons |   .0812269   .1077378     0.75   0.453    -.1325482     .295002\n-------------+----------------------------------------------------------------\n     sigma_u |  6.7557992\n     sigma_e |  2.3738231\n         rho |  .89010353   (fraction of variance due to u_i)\n------------------------------------------------------------------------------\n\n\nRandom-effects GLS regression                   Number of obs     =        400\nGroup variable: id                              Number of groups  =        100\n\nR-squared:                                      Obs per group:\n     Within  = 0.2207                                         min =          4\n     Between = 0.0129                                         avg =        4.0\n     Overall = 0.0348                                         max =          4\n\n                                                Wald chi2(3)      =     102.12\ncorr(u_i, X) = 0 (assumed)                      Prob > chi2       =     0.0000\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |               Robust\n        logy | Coefficient  std. err.      z    P>|z|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n           w |   3.206857   .4314949     7.43   0.000     2.361142    4.052571\n           d |  -.0636461   1.356731    -0.05   0.963     -2.72279    2.595498\n        post |  -.1255431   .3021942    -0.42   0.678    -.7178329    .4667467\n       _cons |     .11305   .9272947     0.12   0.903    -1.704414    1.930514\n-------------+----------------------------------------------------------------\n     sigma_u |   6.685563\n     sigma_e |  2.3738231\n         rho |  .88804221   (fraction of variance due to u_i)\n------------------------------------------------------------------------------\n\n\nFixed-effects (within) regression               Number of obs     =        400\nGroup variable: id                              Number of groups  =        100\n\nR-squared:                                      Obs per group:\n     Within  = 0.2575                                         min =          4\n     Between = 0.0129                                         avg =        4.0\n     Overall = 0.0387                                         max =          4\n\n                                                F(5, 99)          =      21.98\ncorr(u_i, Xb) = -0.0027                         Prob > F          =     0.0000\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |               Robust\n        logy | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n c.w#c.f2014 |   2.813593   .5368268     5.24   0.000     1.748412    3.878774\n             |\n c.w#c.f2015 |   3.600121   .5765523     6.24   0.000     2.456116    4.744126\n             |\n        year |\n       2013  |   .3260046   .3325494     0.98   0.329    -.3338456    .9858548\n       2014  |   -.341502   .4488412    -0.76   0.449      -1.2321    .5490964\n       2015  |   .4164204   .4300378     0.97   0.335    -.4368679    1.269709\n             |\n       _cons |  -.0817754   .2006423    -0.41   0.684    -.4798932    .3163424\n-------------+----------------------------------------------------------------\n     sigma_u |  6.7557992\n     sigma_e |  2.3288408\n         rho |  .89379082   (fraction of variance due to u_i)\n------------------------------------------------------------------------------\n\n\nFixed-effects (within) regression               Number of obs     =        400\nGroup variable: id                              Number of groups  =        100\n\nR-squared:                                      Obs per group:\n     Within  = 0.2575                                         min =          4\n     Between = 0.0129                                         avg =        4.0\n     Overall = 0.0387                                         max =          4\n\n                                                F(5, 99)          =      21.98\ncorr(u_i, Xb) = -0.0027                         Prob > F          =     0.0000\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |               Robust\n        logy | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n c.d#c.f2014 |   2.813593   .5368268     5.24   0.000     1.748412    3.878774\n             |\n c.d#c.f2015 |   3.600121   .5765523     6.24   0.000     2.456116    4.744126\n             |\n        year |\n       2013  |   .3260046   .3325494     0.98   0.329    -.3338456    .9858548\n       2014  |   -.341502   .4488412    -0.76   0.449      -1.2321    .5490964\n       2015  |   .4164204   .4300378     0.97   0.335    -.4368679    1.269709\n             |\n       _cons |  -.0817754   .2006423    -0.41   0.684    -.4798932    .3163424\n-------------+----------------------------------------------------------------\n     sigma_u |  6.7557992\n     sigma_e |  2.3288408\n         rho |  .89379082   (fraction of variance due to u_i)\n------------------------------------------------------------------------------\n\n\nLinear regression                               Number of obs     =        400\n                                                F(5, 99)          =      21.97\n                                                Prob > F          =     0.0000\n                                                R-squared         =     0.0384\n                                                Root MSE          =     7.0672\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |               Robust\n        logy | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n c.w#c.f2014 |   2.813593   .5368268     5.24   0.000     1.748412    3.878774\n             |\n c.w#c.f2015 |   3.600121   .5765523     6.24   0.000     2.456116    4.744126\n             |\n           d |  -.0636461    1.36017    -0.05   0.963    -2.762519    2.635227\n       f2014 |  -.5045043   .3923088    -1.29   0.201     -1.28293    .2739216\n       f2015 |   .2534181   .4206018     0.60   0.548    -.5811472    1.087983\n       _cons |     .11305   .9296453     0.12   0.903    -1.731568    1.957668\n------------------------------------------------------------------------------\n\n\n ( 1)  .5*c.w#c.f2014 + .5*c.w#c.f2015 = 0\n\n------------------------------------------------------------------------------\n        logy | Coefficient  Std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n         (1) |   3.206857   .4325887     7.41   0.000     2.348507    4.065207\n------------------------------------------------------------------------------\n\n\nRandom-effects GLS regression                   Number of obs     =        400\nGroup variable: id                              Number of groups  =        100\n\nR-squared:                                      Obs per group:\n     Within  = 0.2550                                         min =          4\n     Between = 0.0129                                         avg =        4.0\n     Overall = 0.0384                                         max =          4\n\n                                                Wald chi2(5)      =     109.84\ncorr(u_i, X) = 0 (assumed)                      Prob > chi2       =     0.0000\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |               Robust\n        logy | Coefficient  std. err.      z    P>|z|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n c.w#c.f2014 |   2.813593   .5368268     5.24   0.000     1.761432    3.865754\n             |\n c.w#c.f2015 |   3.600121   .5765523     6.24   0.000     2.470099    4.730143\n             |\n           d |  -.0636461    1.36017    -0.05   0.963    -2.729531    2.602239\n       f2014 |  -.5045043   .3923088    -1.29   0.198    -1.273415    .2644069\n       f2015 |   .2534181   .4206018     0.60   0.547    -.5709463    1.077782\n       _cons |     .11305   .9296453     0.12   0.903    -1.709021    1.935121\n-------------+----------------------------------------------------------------\n     sigma_u |  6.6895238\n     sigma_e |  2.3287614\n         rho |  .89191109   (fraction of variance due to u_i)\n------------------------------------------------------------------------------\n\n\nLinear regression                               Number of obs     =        400\n                                                F(7, 99)          =     182.67\n                                                Prob > F          =     0.0000\n                                                R-squared         =     0.8438\n                                                Root MSE          =     2.8557\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |               Robust\n        logy | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n c.w#c.f2014 |   2.503103   .3066694     8.16   0.000     1.894605    3.111602\n             |\n c.w#c.f2015 |   3.327274   .2902385    11.46   0.000     2.751378     3.90317\n             |\n           d |    .881691   .5285779     1.67   0.098    -.1671223    1.930504\n       f2014 |   .0840872   .2215839     0.38   0.705    -.3555834    .5237578\n       f2015 |   .2391039   .2082552     1.15   0.254    -.1741196    .6523275\n          x1 |   2.506694   .1327049    18.89   0.000     2.243379     2.77001\n             |\n    c.d#c.x1 |   .0743163   .1915921     0.39   0.699     -.305844    .4544765\n             |\n       _cons |   .2148708   .3676352     0.58   0.560    -.5145972    .9443389\n------------------------------------------------------------------------------\n\n\nLinear regression                               Number of obs     =        400\n                                                F(8, 99)          =     166.57\n                                                Prob > F          =     0.0000\n                                                R-squared         =     0.8438\n                                                Root MSE          =     2.8593\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |               Robust\n        logy | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n c.w#c.f2014 |   2.503013   .3070762     8.15   0.000     1.893707    3.112319\n             |\n c.w#c.f2015 |   3.327292   .2906341    11.45   0.000     2.750611    3.903973\n             |\n           d |   .8816195   .5292507     1.67   0.099    -.1685288    1.931768\n             |\n        year |\n       2013  |  -.0324553   .1709047    -0.19   0.850    -.3715673    .3066568\n       2014  |    .067934   .2343565     0.29   0.773    -.3970801    .5329482\n       2015  |   .2228745   .2273177     0.98   0.329    -.2281732    .6739222\n             |\n          x1 |   2.507011   .1335155    18.78   0.000     2.242087    2.771935\n             |\n    c.d#c.x1 |   .0738548   .1927512     0.38   0.702    -.3086053    .4563149\n             |\n       _cons |   .2311113     .37362     0.62   0.538    -.5102317    .9724544\n------------------------------------------------------------------------------\n\n    Variable |        Obs        Mean    Std. dev.       Min        Max\n-------------+---------------------------------------------------------\n          x1 |        200   -.4048388    2.493319   -6.95061   4.588676\n\n\n\nFixed-effects (within) regression               Number of obs     =        400\nGroup variable: id                              Number of groups  =        100\n\nR-squared:                                      Obs per group:\n     Within  = 0.3620                                         min =          4\n     Between = 0.4276                                         avg =        4.0\n     Overall = 0.2782                                         max =          4\n\n                                                F(9, 99)          =      23.70\ncorr(u_i, Xb) = 0.3305                          Prob > F          =     0.0000\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |               Robust\n        logy | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n c.w#c.f2014 |   2.938834   .5031086     5.84   0.000     1.940557     3.93711\n             |\n c.w#c.f2015 |   3.742608    .534969     7.00   0.000     2.681113    4.804102\n             |\n c.w#c.f2014#|\n   c.x1_dm_1 |  -.2243583   .1904085    -1.18   0.242      -.60217    .1534535\n             |\n c.w#c.f2015#|\n   c.x1_dm_1 |   .0296616   .2431933     0.12   0.903    -.4528867    .5122099\n             |\n        year |\n       2013  |   .3260046   .3342504     0.98   0.332    -.3372208      .98923\n       2014  |    -.16839   .3880607    -0.43   0.665    -.9383866    .6016067\n       2015  |   .4360252   .3954162     1.10   0.273    -.3485664    1.220617\n             |\nc.f2014#c.x1 |   .6285213   .1342955     4.68   0.000     .3620499    .8949926\n             |\nc.f2015#c.x1 |   .5615944   .1919492     2.93   0.004     .1807255    .9424633\n             |\n       _cons |  -.0817754   .1900787    -0.43   0.668    -.4589327    .2953819\n-------------+----------------------------------------------------------------\n     sigma_u |  6.1628203\n     sigma_e |  2.1734897\n         rho |  .88937776   (fraction of variance due to u_i)\n------------------------------------------------------------------------------\n\n\nLinear regression                               Number of obs     =        400\n                                                F(12, 99)         =     112.09\n                                                Prob > F          =     0.0000\n                                                R-squared         =     0.8445\n                                                Root MSE          =     2.8679\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |               Robust\n        logy | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n c.w#c.f2014 |   2.496168   .3173129     7.87   0.000      1.86655    3.125785\n             |\n c.w#c.f2015 |   3.349012   .3132217    10.69   0.000     2.727513    3.970512\n             |\n c.w#c.f2014#|\n   c.x1_dm_1 |  -.2701343   .1759396    -1.54   0.128    -.6192367    .0789681\n             |\n c.w#c.f2015#|\n   c.x1_dm_1 |  -.0683301   .1502763    -0.45   0.650    -.3665108    .2298506\n             |\n        year |\n       2013  |  -.0188111   .1738311    -0.11   0.914    -.3637298    .3261075\n       2014  |   .0787158   .2377676     0.33   0.741    -.3930668    .5504984\n       2015  |   .2325892   .2297992     1.01   0.314    -.2233823    .6885607\n             |\nc.f2014#c.x1 |   .0404883   .1103324     0.37   0.714    -.1784352    .2594118\n             |\nc.f2015#c.x1 |   .0778513   .1061898     0.73   0.465    -.1328523    .2885549\n             |\n           d |    .904209   .5311615     1.70   0.092    -.1497307    1.958149\n          x1 |   2.476382   .1544607    16.03   0.000     2.169899    2.782866\n             |\n    c.d#c.x1 |   .1570952   .2113815     0.74   0.459    -.2623316     .576522\n             |\n       _cons |   .2230452   .3747574     0.60   0.553    -.5205549    .9666452\n------------------------------------------------------------------------------\n\n\nLinear regression                               Number of obs     =        400\n                                                F(13, 99)         =     103.22\n                                                Prob > F          =     0.0000\n                                                R-squared         =     0.8445\n                                                Root MSE          =     2.8715\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |               Robust\n        logy | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n c.w#c.f2014 |   2.500641   .3196658     7.82   0.000     1.866354    3.134927\n             |\n c.w#c.f2015 |   3.353485   .3142809    10.67   0.000     2.729884    3.977087\n             |\n c.w#c.f2014#|\n   c.x1_dm_1 |  -.2674635    .177262    -1.51   0.135    -.6191897    .0842627\n             |\n c.w#c.f2015#|\n   c.x1_dm_1 |  -.0656593   .1506332    -0.44   0.664    -.3645482    .2332296\n             |\n        year |\n       2013  |  -.0261778   .1756818    -0.15   0.882    -.3747686    .3224129\n       2014  |     .07109   .2439251     0.29   0.771    -.4129104    .5550904\n       2015  |   .2249634   .2325834     0.97   0.336    -.2365326    .6864593\n             |\n   year#c.x1 |\n       2013  |  -.0298874   .0910807    -0.33   0.743    -.2106112    .1508364\n       2014  |   .0227905   .1348423     0.17   0.866    -.2447658    .2903469\n       2015  |   .0601535   .1180653     0.51   0.612    -.1741137    .2944207\n             |\n           d |   .8986549   .5321658     1.69   0.094    -.1572776    1.954587\n          x1 |    2.49408   .1726029    14.45   0.000     2.151599    2.836562\n             |\n    c.d#c.x1 |   .1544244   .2128387     0.73   0.470    -.2678938    .5767426\n             |\n       _cons |    .230671   .3794753     0.61   0.545    -.5222904    .9836324\n------------------------------------------------------------------------------\n\n\nLinear regression                               Number of obs     =        400\n                                                F(12, 99)         =     112.09\n                                                Prob > F          =     0.0000\n                                                R-squared         =     0.8445\n                                                Root MSE          =     2.8679\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |               Robust\n        logy | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n c.w#c.f2014 |   2.386807   .3096756     7.71   0.000     1.772343    3.001271\n             |\n c.w#c.f2015 |    3.32135   .2964989    11.20   0.000     2.733032    3.909668\n             |\n c.w#c.f2014#|\n        c.x1 |  -.2701343   .1759396    -1.54   0.128    -.6192367    .0789681\n             |\n c.w#c.f2015#|\n        c.x1 |  -.0683301   .1502763    -0.45   0.650    -.3665109    .2298506\n             |\n        year |\n       2013  |  -.0188111   .1738311    -0.11   0.914    -.3637298    .3261075\n       2014  |   .0787158   .2377676     0.33   0.741    -.3930668    .5504984\n       2015  |   .2325892   .2297992     1.01   0.314    -.2233823    .6885607\n             |\nc.f2014#c.x1 |   .0404883   .1103324     0.37   0.714    -.1784352    .2594118\n             |\nc.f2015#c.x1 |   .0778513   .1061898     0.73   0.465    -.1328523    .2885549\n             |\n           d |    .904209   .5311615     1.70   0.092    -.1497307    1.958149\n          x1 |   2.476382   .1544607    16.03   0.000     2.169899    2.782866\n             |\n    c.d#c.x1 |   .1570952   .2113815     0.74   0.459    -.2623316     .576522\n             |\n       _cons |   .2230452   .3747574     0.60   0.553    -.5205549    .9666452\n------------------------------------------------------------------------------\n\n\nAverage marginal effects                                 Number of obs   = 400\n                                                         Subpop. no. obs = 200\n\nExpression: Linear prediction, predict()\ndy/dx wrt:  w\nAt: f2014 = 1\n    f2015 = 0\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |            Unconditional\n             |      dy/dx   std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n           w |   2.496168   .3059971     8.16   0.000     1.889003    3.103333\n------------------------------------------------------------------------------\n\n\nAverage marginal effects                                 Number of obs   = 400\n                                                         Subpop. no. obs = 200\n\nExpression: Linear prediction, predict()\ndy/dx wrt:  w\nAt: f2014 = 0\n    f2015 = 1\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |            Unconditional\n             |      dy/dx   std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n           w |   3.349012   .3110518    10.77   0.000     2.731818    3.966207\n------------------------------------------------------------------------------\n\n\n(200 real changes made)\n\n...\nDifference-in-difference with Multiple Time Periods\n\n                                                           Number of obs = 400\nOutcome model  : least squares\nTreatment model: inverse probability\n------------------------------------------------------------------------------\n             | Coefficient  Std. err.      z    P>|z|     [95% conf. interval]\n-------------+----------------------------------------------------------------\ng2014        |\n t_2012_2013 |  -1.401593   .6428278    -2.18   0.029    -2.661512   -.1416737\n t_2013_2014 |   3.388112   .5850216     5.79   0.000     2.241491    4.534734\n t_2013_2015 |   3.915051   .6484609     6.04   0.000     2.644091    5.186011\n------------------------------------------------------------------------------\nControl: Never Treated\n\nSee Callaway and Sant'Anna (2021) for details\n\n      Source |       SS           df       MS      Number of obs   =       300\n-------------+----------------------------------   F(8, 291)       =    210.00\n       Model |  12568.7919         8  1571.09898   Prob > F        =    0.0000\n    Residual |  2177.12159       291  7.48151749   R-squared       =    0.8524\n-------------+----------------------------------   Adj R-squared   =    0.8483\n       Total |  14745.9135       299  49.3174363   Root MSE        =    2.7352\n\n------------------------------------------------------------------------------\n        logy | Coefficient  Std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n        year |\n       2013  |  -.0188111   .3880383    -0.05   0.961    -.7825286    .7449063\n       2014  |   .0787158    .513587     0.15   0.878    -.9321002    1.089532\n       2015  |   .2325892   .5121166     0.45   0.650    -.7753329    1.240511\n             |\nc.f2014#c.x1 |   .0404883   .1798899     0.23   0.822    -.3135619    .3945385\n             |\nc.f2015#c.x1 |   .0778513   .1879703     0.41   0.679    -.2921023    .4478049\n             |\n           d |    .904209   .3894073     2.32   0.021     .1377972    1.670621\n          x1 |   2.476382   .1100309    22.51   0.000     2.259825     2.69294\n             |\n    c.d#c.x1 |   .1570952   .1556659     1.01   0.314    -.1492786     .463469\n             |\n       _cons |   .2230452   .3355663     0.66   0.507    -.4373996    .8834899\n------------------------------------------------------------------------------\n\n    Variable |        Obs        Mean    Std. dev.       Min        Max\n-------------+---------------------------------------------------------\n     tetilda |         50    2.525512    3.370158  -5.463166   10.58631\n\n    Variable |        Obs        Mean    Std. dev.       Min        Max\n-------------+---------------------------------------------------------\n     tetilda |         50     3.34147    3.105354  -3.463709   10.24051\n\n      Source |       SS           df       MS      Number of obs   =       100\n-------------+----------------------------------   F(4, 96)        =     21.48\n       Model |  900.277122         4   225.06928   Prob > F        =    0.0000\n    Residual |  1005.96245        96  10.4787755   R-squared       =    0.4723\n-------------+----------------------------------   Adj R-squared   =    0.4503\n       Total |  1906.23957       100  19.0623957   Root MSE        =    3.2371\n\n------------------------------------------------------------------------------\n     tetilda | Coefficient  Std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n c.w#c.f2014 |   2.496168   .4582501     5.45   0.000     1.586549    3.405787\n             |\n c.w#c.f2015 |   3.349012   .4582306     7.31   0.000     2.439432    4.258593\n             |\n c.w#c.f2014#|\n   c.x1_dm_1 |  -.2701343   .1881329    -1.44   0.154    -.6435751    .1033065\n             |\n c.w#c.f2015#|\n   c.x1_dm_1 |  -.0683301   .1811302    -0.38   0.707    -.4278707    .2912104\n------------------------------------------------------------------------------\n\n\nTreatment and time information\n\nTime variable: year\nControl:       w = 0\nTreatment:     w = 1\n-----------------------------------\n             |   Control  Treatment\n-------------+---------------------\nGroup        |\n          id |        50         50\n-------------+---------------------\nTime         |\n     Minimum |      2012       2014\n     Maximum |      2012       2014\n-----------------------------------\n\nDifference-in-differences regression                       Number of obs = 400\nData type: Longitudinal\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |               Robust\n        logy | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\nATET         |\n           w |\n   (1 vs 0)  |   3.206857   .4320407     7.42   0.000     2.349594    4.064119\n------------------------------------------------------------------------------\nNote: ATET estimate adjusted for panel effects and time effects.\n\n\nParallel-trends test (pretreatment time period)\nH0: Linear trends are parallel\n\nF(1, 99) =   4.64\nProb > F = 0.0337\n\n\n\nLinear regression                               Number of obs     =        100\n                                                F(1, 98)          =       4.66\n                                                Prob > F          =     0.0332\n                                                R-squared         =     0.0454\n                                                Root MSE          =     3.2451\n\n------------------------------------------------------------------------------\n             |               Robust\n      D.logy | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n           d |  -1.401579   .6490187    -2.16   0.033    -2.689536   -.1136226\n       _cons |   1.026794   .4697368     2.19   0.031     .0946167    1.958972\n------------------------------------------------------------------------------\n\n\n\nFixed-effects (within) regression               Number of obs     =        400\nGroup variable: id                              Number of groups  =        100\n\nR-squared:                                      Obs per group:\n     Within  = 0.8680                                         min =          4\n     Between = 0.8466                                         avg =        4.0\n     Overall = 0.8412                                         max =          4\n\n                                                F(12, 99)         =     157.25\ncorr(u_i, Xb) = 0.4488                          Prob > F          =     0.0000\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |               Robust\n        logy | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n c.w#c.f2014 |   2.456402   .5067512     4.85   0.000     1.450898    3.461907\n             |\n c.w#c.f2015 |   3.208291   .7927064     4.05   0.000      1.63539    4.781193\n             |\n c.w#c.f2014#|\n   c.x1_dm_1 |  -.0503407   .1059229    -0.48   0.636    -.2605148    .1598333\n             |\n c.w#c.f2015#|\n   c.x1_dm_1 |   .0924389   .0842389     1.10   0.275    -.0747095    .2595872\n             |\n        year |\n       2013  |   .0205346   .1993658     0.10   0.918    -.3750504    .4161195\n       2014  |   -.009636   .2174468    -0.04   0.965    -.4410976    .4218256\n       2015  |   .2623215   .1940125     1.35   0.179    -.1226414    .6472845\n             |\n   year#c.x1 |\n       2012  |   1.933064   .0764551    25.28   0.000     1.781361    2.084768\n       2013  |   2.003714   .0662191    30.26   0.000     1.872321    2.135107\n       2014  |    2.01687   .0849868    23.73   0.000     1.848238    2.185502\n       2015  |   1.991922    .072964    27.30   0.000     1.847146    2.136699\n             |\n     c.d#c.t |   .0668116   .2957253     0.23   0.822    -.5199715    .6535946\n             |\n       _cons |   .4575496   .1764897     2.59   0.011     .1073557    .8077434\n-------------+----------------------------------------------------------------\n     sigma_u |  3.0627341\n     sigma_e |  .99359271\n         rho |  .90477742   (fraction of variance due to u_i)\n------------------------------------------------------------------------------\n\n\nLinear regression                               Number of obs     =        400\n                                                F(14, 99)         =     101.72\n                                                Prob > F          =     0.0000\n                                                R-squared         =     0.8446\n                                                Root MSE          =     2.8741\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |               Robust\n        logy | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n c.w#c.f2014 |   1.833542   .6136741     2.99   0.004      .615879    3.051204\n             |\n c.w#c.f2015 |   2.243344   .9499793     2.36   0.020      .358379    4.128309\n             |\n c.w#c.f2014#|\n   c.x1_dm_1 |  -.2653456    .177891    -1.49   0.139    -.6183199    .0876287\n             |\n c.w#c.f2015#|\n   c.x1_dm_1 |  -.0635414    .150658    -0.42   0.674    -.3624795    .2353968\n             |\n        year |\n       2013  |  -.2472397   .2421693    -1.02   0.310    -.7277561    .2332767\n       2014  |  -.0388673   .2538858    -0.15   0.879    -.5426319    .4648973\n       2015  |   .1150061   .2472402     0.47   0.643     -.375572    .6055842\n             |\n   year#c.x1 |\n       2013  |  -.0241251   .0913453    -0.26   0.792    -.2053741    .1571239\n       2014  |   .0216128   .1358993     0.16   0.874     -.248041    .2912665\n       2015  |   .0589757   .1180401     0.50   0.618    -.1752415     .293193\n             |\n           d |     .23577   .7209278     0.33   0.744    -1.194707    1.666247\n          x1 |   2.495258   .1736213    14.37   0.000     2.150756     2.83976\n             |\n    c.d#c.x1 |   .1523065   .2136548     0.71   0.478    -.2716309    .5762438\n             |\n     c.d#c.t |   .4430422   .3468509     1.28   0.204    -.2451853     1.13127\n             |\n       _cons |   .3406282   .3823786     0.89   0.375     -.418094     1.09935\n------------------------------------------------------------------------------\n\n\nLinear regression                               Number of obs     =        400\n                                                F(15, 99)         =      95.45\n                                                Prob > F          =     0.0000\n                                                R-squared         =     0.8450\n                                                Root MSE          =     2.8744\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |               Robust\n        logy | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n c.w#c.f2014 |   1.917612   .6348799     3.02   0.003     .6578725    3.177352\n             |\n c.w#c.f2015 |   2.378839   .9651184     2.46   0.015     .4638351    4.293844\n             |\n c.w#c.f2014#|\n   c.x1_dm_1 |  -.7263424   .2927708    -2.48   0.015    -1.307263   -.1454217\n             |\n c.w#c.f2015#|\n   c.x1_dm_1 |  -.8415862   .4868867    -1.73   0.087    -1.807675    .1245027\n             |\n        year |\n       2013  |  -.2611685   .2476914    -1.05   0.294    -.7526419    .2303049\n       2014  |  -.0671335   .2642967    -0.25   0.800    -.5915555    .4572885\n       2015  |   .0867399   .2545516     0.34   0.734    -.4183457    .5918255\n             |\n   year#c.x1 |\n       2013  |  -.1857772   .1396877    -1.33   0.187    -.4629479    .0913934\n       2014  |  -.0735746   .1623912    -0.45   0.651     -.395794    .2486448\n       2015  |  -.0362116   .1317686    -0.27   0.784    -.2976691    .2252458\n             |\n           d |   .1075441    .732768     0.15   0.884    -1.346427    1.561515\n          x1 |   2.590445   .1878499    13.79   0.000      2.21771     2.96318\n             |\n    c.d#c.x1 |  -.3378406   .3669519    -0.92   0.359    -1.065953    .3902716\n             |\n     c.d#c.t |   .5199705   .3447009     1.51   0.135    -.1639908    1.203932\n             |\nc.d#c.t#c.x1 |    .317048   .1852193     1.71   0.090    -.0504673    .6845633\n             |\n       _cons |   .3688944   .3868765     0.95   0.343    -.3987525    1.136541\n------------------------------------------------------------------------------\n\n\n ( 1)  c.d#c.t = 0\n ( 2)  c.d#c.t#c.x1 = 0\n\n       F(  2,    99) =    2.47\n            Prob > F =    0.0898\n\n\n\nLinear regression                               Number of obs     =        300\n                                                F(11, 99)         =      82.82\n                                                Prob > F          =     0.0000\n                                                R-squared         =     0.8531\n                                                Root MSE          =     2.7429\n\n                                   (Std. err. adjusted for 100 clusters in id)\n------------------------------------------------------------------------------\n             |               Robust\n        logy | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n        year |\n       2013  |  -.2611685   .2475879    -1.05   0.294    -.7524366    .2300996\n       2014  |  -.0671335   .2641863    -0.25   0.800    -.5913364    .4570694\n       2015  |   .0867399   .2544452     0.34   0.734    -.4181347    .5916145\n             |\n   year#c.x1 |\n       2013  |  -.1857773   .1396293    -1.33   0.186    -.4628321    .0912775\n       2014  |  -.0735746   .1623234    -0.45   0.651    -.3956594    .2485101\n       2015  |  -.0362116   .1317135    -0.27   0.784    -.2975599    .2251366\n             |\n           d |    .107544   .7324618     0.15   0.884    -1.345819    1.560907\n          x1 |   2.590445   .1877714    13.80   0.000     2.217866    2.963025\n             |\n    c.d#c.x1 |  -.3378407   .3667986    -0.92   0.359    -1.065649    .3899672\n             |\n     c.d#c.t |   .5199705   .3445569     1.51   0.134    -.1637051    1.203646\n             |\nc.d#c.t#c.x1 |   .3170481   .1851419     1.71   0.090    -.0503137    .6844098\n             |\n       _cons |   .3688944   .3867149     0.95   0.342    -.3984318    1.136221\n------------------------------------------------------------------------------\n\n\n ( 1)  c.d#c.t = 0\n ( 2)  c.d#c.t#c.x1 = 0\n\n       F(  2,    99) =    2.47\n            Prob > F =    0.0896\n\n    Variable |        Obs        Mean    Std. dev.       Min        Max\n-------------+---------------------------------------------------------\n     tetilda |         50    1.996512    3.755621  -5.357233   9.968782\n\n    Variable |        Obs        Mean    Std. dev.       Min        Max\n-------------+---------------------------------------------------------\n     tetilda |         50    2.285944    3.772198  -4.526336   10.79229\n\n      Source |       SS           df       MS      Number of obs   =       100\n-------------+----------------------------------   F(4, 96)        =     20.11\n       Model |  842.991546         4  210.747887   Prob > F        =    0.0000\n    Residual |  1005.96248        96  10.4787758   R-squared       =    0.4559\n-------------+----------------------------------   Adj R-squared   =    0.4333\n       Total |  1848.95402       100  18.4895402   Root MSE        =    3.2371\n\n------------------------------------------------------------------------------\n     tetilda | Coefficient  Std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n c.w#c.f2014 |   1.917612   .4582501     4.18   0.000     1.007993    2.827231\n             |\n c.w#c.f2015 |   2.378839   .4582306     5.19   0.000     1.469259     3.28842\n             |\n c.w#c.f2014#|\n   c.x1_dm_1 |  -.7263426   .1881329    -3.86   0.000    -1.099783   -.3529017\n             |\n c.w#c.f2015#|\n   c.x1_dm_1 |  -.8415865   .1811302    -4.65   0.000    -1.201127   -.4820459\n------------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\n\n\nThat is a long chunk, so here is what to take from it. Every specification that\ntargets the overall ATT returns **3.206857** — the two-way fixed-effect\nregression, pooled OLS with unit and time means, random effects, and the\n`did`-style variants all agree to seven digits, differing only in the standard\nerror's fourth decimal (0.4310 to 0.4326). Against a true ATT of 3, that is\nabout half a standard error high. The equivalences claimed throughout this\nchapter hold numerically, not just in the algebra.\n\nAllowing the effect to vary by year recovers the two components separately:\n2.496168 for 2014 and 3.349012 for 2015, against true values of 2.5 and 3.5.\nTheir average, 2.92, is what the single-number ATT is summarising, and reporting\nonly 3.21 would hide that the effect grows by about a third between the two post\nyears.\n\nThe imputation approach at the end fits the model on untreated observations only\nand reads the treatment effects off the residuals. Its estimates of\n`c.d#c.t` and `c.d#c.t#c.x1` match the full-sample regression, and the\npre-treatment interaction `c.d#c.t` is 0.0668 with $p = 0.822$ — no detectable\ndifferential trend before treatment, which is what the design needs.\n",
    "supporting": [
      "mundlak-device_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}