{
  "hash": "60a779a5de11a09f3cccc41260bb73a2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Sensitivity analysis of OLS with sensemakr\"\ndate: \"2025-04-03\"\n---\n\n\n## OVB\n\nConsider a true model,\n\n$$ Y = \\delta D + X \\beta + \\gamma Z + \\epsilon $$ {#eq-sensitivity-analysis-1}\n\nIf $Z$ is unobserved we estimate\n\n$$ Y = \\delta D + X \\beta + u $$ {#eq-sensitivity-analysis-2}\n\nand face omitted variable bias (OVB). Cinelli and Hazlett (2020) show that\n\n$$ |\\widehat{\\text{bias}}| = \\sqrt{\\frac{R^2_{Y \\sim Z|D,X} R^2_{D \\sim Z|X}}{1-R^2_{D \\sim Z|X}}} (\\frac{\\hat \\sigma_{y.dx}}{\\hat \\sigma_{d.x}})$$ {#eq-sensitivity-analysis-3}\n\nBias is large only when the omitted variable is strongly associated with both $Y$ and $D$. The Cinelli and Hazlett framework yields three key quantities.\n\n## Partial $R^2$ of treatment on outcome\n\nThis measures how much variation in the outcome the treatment explains after partialling out $X$. In the extreme case where the confounder explains all remaining outcome variance ($R^2_{Y \\sim Z|D,X} = 1$), the treatment effect goes to zero only if $R^2_{D \\sim Z|X} \\ge R^2_{Y \\sim D|X}$. In other words, the confounder's association with treatment must exceed the treatment's partial association with the outcome.\n\n## Robust value\n\n$RV_{q,\\alpha}$ is the minimum strength of association the confounder must have with both treatment and outcome for a $(1-\\alpha)$ confidence interval to include a $q\\%$ change from the current estimate. With $q=1$ this gives the threshold for the effect to include zero. Both the $Z$-$D$ and $Z$-$Y$ associations must exceed this threshold simultaneously.\n\n\n## Bounds using observed covariate(s)\n\nThe first two quantities are dimensionless but hard to interpret without context. Benchmarking against an observed covariate helps. If a covariate $X_j$ is known to be an important predictor, we can ask how much stronger the confounder must be relative to $X_j$ to drive the effect to zero.\n\n$$ k_D := \\frac{R^2_{D \\sim Z|X_{-j}}}{R^2_{D \\sim X_j|X_{-j}}} $$ {#eq-sensitivity-analysis-4}\n\nwhere $X_{-j}$ represents all covariates other than the $j$th we pick as the benchmark covariate.\n\n$$ k_Y := \\frac{R^2_{Y \\sim Z|D,X_{-j}}}{R^2_{Y \\sim X_j|D,X_{-j}}} $$ {#eq-sensitivity-analysis-5}\n\n\n## Example\n\nHere is an example from sensemakr documentation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# loads package\nlibrary(sensemakr)\n\n# loads dataset\ndata(\"darfur\")\n\n# runs regression model\nmodel <- lm(peacefactor ~ directlyharmed + age + farmer_dar + herder_dar +\n                         pastvoted + hhsize_darfur + female + village, data = darfur)\n\n# runs sensemakr for sensitivity analysis\nsensitivity <- sensemakr(model = model, \n                         treatment = \"directlyharmed\",\n                         benchmark_covariates = \"female\",\n                         kd = 1:3)\n\n# short description of results\nsensitivity\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSensitivity Analysis to Unobserved Confounding\n\nModel Formula: peacefactor ~ directlyharmed + age + farmer_dar + herder_dar + \n    pastvoted + hhsize_darfur + female + village\n\nNull hypothesis: q = 1 and reduce = TRUE \n\nUnadjusted Estimates of ' directlyharmed ':\n  Coef. estimate: 0.09732 \n  Standard Error: 0.02326 \n  t-value: 4.18445 \n\nSensitivity Statistics:\n  Partial R2 of treatment with outcome: 0.02187 \n  Robustness Value, q = 1 : 0.13878 \n  Robustness Value, q = 1 alpha = 0.05 : 0.07626 \n\nFor more information, check summary.\n```\n\n\n:::\n\n```{.r .cell-code}\n# long description of results\nsummary(sensitivity)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSensitivity Analysis to Unobserved Confounding\n\nModel Formula: peacefactor ~ directlyharmed + age + farmer_dar + herder_dar + \n    pastvoted + hhsize_darfur + female + village\n\nNull hypothesis: q = 1 and reduce = TRUE \n-- This means we are considering biases that reduce the absolute value of the current estimate.\n-- The null hypothesis deemed problematic is H0:tau = 0 \n\nUnadjusted Estimates of 'directlyharmed': \n  Coef. estimate: 0.0973 \n  Standard Error: 0.0233 \n  t-value (H0:tau = 0): 4.1844 \n\nSensitivity Statistics:\n  Partial R2 of treatment with outcome: 0.0219 \n  Robustness Value, q = 1: 0.1388 \n  Robustness Value, q = 1, alpha = 0.05: 0.0763 \n\nVerbal interpretation of sensitivity statistics:\n\n-- Partial R2 of the treatment with the outcome: an extreme confounder (orthogonal to the covariates) that explains 100% of the residual variance of the outcome, would need to explain at least 2.19% of the residual variance of the treatment to fully account for the observed estimated effect.\n\n-- Robustness Value, q = 1: unobserved confounders (orthogonal to the covariates) that explain more than 13.88% of the residual variance of both the treatment and the outcome are strong enough to bring the point estimate to 0 (a bias of 100% of the original estimate). Conversely, unobserved confounders that do not explain more than 13.88% of the residual variance of both the treatment and the outcome are not strong enough to bring the point estimate to 0.\n\n-- Robustness Value, q = 1, alpha = 0.05: unobserved confounders (orthogonal to the covariates) that explain more than 7.63% of the residual variance of both the treatment and the outcome are strong enough to bring the estimate to a range where it is no longer 'statistically different' from 0 (a bias of 100% of the original estimate), at the significance level of alpha = 0.05. Conversely, unobserved confounders that do not explain more than 7.63% of the residual variance of both the treatment and the outcome are not strong enough to bring the estimate to a range where it is no longer 'statistically different' from 0, at the significance level of alpha = 0.05.\n\nBounds on omitted variable bias:\n\n--The table below shows the maximum strength of unobserved confounders with association with the treatment and the outcome bounded by a multiple of the observed explanatory power of the chosen benchmark covariate(s).\n\n Bound Label R2dz.x R2yz.dx      Treatment Adjusted Estimate Adjusted Se\n   1x female 0.0092  0.1246 directlyharmed            0.0752      0.0219\n   2x female 0.0183  0.2493 directlyharmed            0.0529      0.0204\n   3x female 0.0275  0.3741 directlyharmed            0.0304      0.0187\n Adjusted T Adjusted Lower CI Adjusted Upper CI\n     3.4389            0.0323            0.1182\n     2.6002            0.0130            0.0929\n     1.6281           -0.0063            0.0670\n```\n\n\n:::\n:::\n\n\n```{.r .cell-code}\n# minimal reporting\novb_minimal_reporting(sensitivity, format = \"html\")\n```\n\n<table>\n<thead>\n<tr>\n\t<th style=\"text-align:left;border-bottom: 1px solid transparent;border-top: 1px solid black\"> </th>\n\t<th colspan = 6 style=\"text-align:center;border-bottom: 1px solid black;border-top: 1px solid black\"> Outcome: peacefactor</th>\n</tr>\n<tr>\n\t<th style=\"text-align:left;border-top: 1px solid black\"> Treatment </th>\n\t<th style=\"text-align:right;border-top: 1px solid black\"> Est. </th>\n\t<th style=\"text-align:right;border-top: 1px solid black\"> S.E. </th>\n\t<th style=\"text-align:right;border-top: 1px solid black\"> t-value </th>\n\t<th style=\"text-align:right;border-top: 1px solid black\"> $R^2_{Y \\sim D |{\\bf X}}$ </th>\n\t<th style=\"text-align:right;border-top: 1px solid black\">  $RV_{q = 1}$ </th>\n\t<th style=\"text-align:right;border-top: 1px solid black\"> $RV_{q = 1, \\alpha = 0.05}$ </th>\n</tr>\n</thead>\n<tbody>\n <tr>\n\t<td style=\"text-align:left; border-bottom: 1px solid black\"><i>directlyharmed</i></td>\n\t<td style=\"text-align:right;border-bottom: 1px solid black\">0.097 </td>\n\t<td style=\"text-align:right;border-bottom: 1px solid black\">0.023 </td>\n\t<td style=\"text-align:right;border-bottom: 1px solid black\">4.184 </td>\n\t<td style=\"text-align:right;border-bottom: 1px solid black\">2.2\\% </td>\n\t<td style=\"text-align:right;border-bottom: 1px solid black\">13.9\\% </td>\n\t<td style=\"text-align:right;border-bottom: 1px solid black\">7.6\\% </td>\n</tr>\n</tbody>\n<tr>\n<td colspan = 7 style='text-align:right;border-top: 1px solid black;border-bottom: 1px solid transparent;font-size:11px'>Note: df = 783; Bound ( 1x female ):  $R^2_{Y\\sim Z| {\\bf X}, D}$ = 12.5\\%, $R^2_{D\\sim Z| {\\bf X} }$ = 0.9\\%</td>\n</tr>\n</table>\n\nLet's see how to interpret this.  \n\n$RV_{q=1} = 13.9 \\%$.  This means that unobserved confounders that explain 13.9% of the residual variance both of the treatment and of the outcome are sufficiently strong to explain away all the observed effect. On the other hand, unobserved confounders that do not explain at least 13.9% of the residual variance both of the treatment and of the outcome are not sufficiently strong to do so.    \n\nThe robustness value for testing the null hypothesis that the coefficient of \"directlyharmed\" is zero ($RV_{q=1,\\alpha=0.05}$) is 7.6%. This means that unobserved confounders that explain 7.6% of the residual variance both of the treatment and of the outcome are sufficiently strong to bring the lower bound of the confidence interval to zero (at the chosen significance level of 5%).\n \n \nThe partial $R^2$ of `directlyharmed` with `peacefactor` is 2.2%. This means that, in an extreme scenario in which we assume that unobserved confounders explain all of the left-out variance of the outcome, these unobserved confounders would need to explain at least 2.2% of the residual variance of the treatment to fully explain away the observed effect.\n\nThe above numbers are for the absolute strength the confounder needs to be to explain away the treatment effect.   The authors believe in this context, \"female\" is an important factor.  Suppose the confounder is as important as \"female\", what the partial $R^2$ would be?  It is shown that $R^2_{Y \\sim Z|X,D} = 12.5 \\%$ and $R^2_{D \\sim Z|X} = 0.9 \\%$, so a confounder as strong as \"female\" is not strong enough to explain away the treatment effect.\n\nIt is worth being careful about *why*, because comparing each number to $RV_{q=1} = 13.9\\%$ one at a time invites the wrong reading. The $RV$ is defined for a confounder of *equal* strength on both sides, so it is not a threshold that each partial $R^2$ must separately clear. Here the outcome-side association (12.5%) is in fact close to the $RV$, which on its own might look like a near miss --- but the treatment-side association is only 0.9%, more than an order of magnitude short. It is the treatment side that does the work: \"female\" predicts the outcome nearly well enough to matter, and barely predicts the treatment at all. The contour plot below is the honest check, since it evaluates the pair jointly rather than either coordinate alone.  \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# plot bias contour of point estimate\nplot(sensitivity)\n```\n\n::: {.cell-output-display}\n![](sensitivity-analysis_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nThis plot shows that even 3 times as strong as \"female\", the confounder is not strong enough to explain away the treatment effect.  \n\n## sensitivity analysis for IV\n\nEven with an IV model, we need sensitivity analysis.  The worry would be there could be an unobserved confounder that affects both the instrument and the outcome.  \n\nCinelli and Hazlett have a package \"iv.sensemakr\" for this.  The usage is similar to \"sensemakr\".\n\nThe example is Card's returns-to-schooling data, 3,010 men from the 1976 NLS.\nThe outcome is log wage, the treatment is years of education, and the instrument\nis `nearc4`, an indicator for growing up near a four-year college. The covariates\nare experience and its square, race, region, and urban indicators. The concern\nthe sensitivity analysis addresses is a confounder affecting both proximity to a\ncollege and wages.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# loads package\nlibrary(iv.sensemakr)\n\n# loads dataset\ndata(\"card\")\n\n# prepares data\ny <- card$lwage  # outcome\nd <- card$educ   # treatment\nz <- card$nearc4 # instrument\nx <- model.matrix( ~ exper + expersq + black + south + smsa + reg661 + reg662 +\n                     reg663 + reg664 + reg665+ reg666 + reg667 + reg668 + smsa66,\n                   data = card) # covariates\n# fits IV model\ncard.fit <- iv_fit(y,d,z,x)\n\n# see results\ncard.fit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nInstrumental Variable Estimation\n(Anderson-Rubin Approach)\n=============================================\nIV Estimates:\n  Coef. Estimate: 0.132\n  t-value: 2.33\n  p-value: 0.02\n  Conf. Interval: [0.025, 0.285]\nNote: H0 = 0, alpha = 0.05, df = 2994.\n=============================================\nSee summary for first stage and reduced form.\n```\n\n\n:::\n\n```{.r .cell-code}\n# runs sensitivity analysis\ncard.sens <- sensemakr(card.fit, benchmark_covariates = c(\"black\", \"smsa\"))\n\n# see results\ncard.sens\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nSensitivity Analysis for Instrumental Variables\n(Anderson-Rubin Approach)\n=============================================================\nIV Estimates:\n  Coef. Estimate: 0.132\n  t-value: 2.33\n  p-value: 0.02\n  Conf. Interval: [0.025, 0.285]\n\nSensitivity Statistics:\n  Extreme Robustness Value: 0.000523\n  Robustness Value: 0.00667\n\nBounds on Omitted Variable Bias:\n Bound Label  R2zw.x R2y0w.zx Lower CI Upper CI Crit. Thr.\n    1x black 0.00221   0.0750  -0.0212    0.402       2.59\n     1x smsa 0.00639   0.0202  -0.0192    0.396       2.57\n\nNote: H0 = 0, q >= 1, alpha = 0.05, df = 2994.\n=============================================================\nSee summary for first stage and reduced form.\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(card.sens)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nSensitivity Analysis for Instrumental Variables\n(Anderson-Rubin Approach)\n=============================================================\nIV Estimates:\n  Coef. Estimate: 0.132\n  t-value: 2.33\n  p-value: 0.02\n  Conf. Interval: [0.025, 0.285]\n\nSensitivity Statistics:\n  Extreme Robustness Value: 0.000523\n  Robustness Value: 0.00667\n\nBounds on Omitted Variable Bias:\n Bound Label  R2zw.x r2y0w.zx Lower CI Upper CI Crit. Thr.\n    1x black 0.00221   0.0750  -0.0212    0.402       2.59\n     1x smsa 0.00639   0.0202  -0.0192    0.396       2.57\n\nNote: H0 = 0, q >= 1, alpha = 0.05, df = 2994.\n-------------------------------------------------------------\nFS Estimates:\n  Coef. Estimate: 0.32\n  Standard Error: 0.0879\n  t-value: 3.64\n  p-value: 0.000276\n  Conf. Interval: [0.148, 0.492]\n\nSensitivity Statistics:\n  Extreme Robustness Value: 0.00313\n  Robustness Value: 0.0302\n\nBounds on Omitted Variable Bias:\n Bound Label  R2zw.x R2dw.zx Lower CI Upper CI Crit. Thr.\n    1x black 0.00221 0.03342    0.109    0.531       2.40\n     1x smsa 0.00639 0.00498    0.120    0.520       2.27\n\nNote: H0 = 0, q = 1, alpha = 0.05, df = 2994.\n-------------------------------------------------------------\nRF Estimates:\n  Coef. Estimate: 0.0421\n  Standard Error: 0.0181\n  t-value: 2.33\n  p-value: 0.02\n  Conf. Interval: [0.007, 0.078]\n\nSensitivity Statistics:\n  Extreme Robustness Value: 0.000523\n  Robustness Value: 0.00667\n\nBounds on Omitted Variable Bias:\n Bound Label  R2zw.x R2yw.zx Lower CI Upper CI Crit. Thr.\n    1x black 0.00221  0.0657 -0.00418   0.0883       2.56\n     1x smsa 0.00639  0.0197 -0.00429   0.0884       2.56\n\nNote: H0 = 0, q = 1, alpha = 0.05, df = 2994.\n=============================================================\n```\n\n\n:::\n:::\n\n\nThe basic idea is to run an IV regression, then apply sensemakr to that model.  In this case, the authors use \"black\" and \"smsa\" as benchmark covariates.  The authors believe these are important factors.\n\nThe IV estimate is 0.132 with $t = 2.33$, $p = 0.02$, and an Anderson-Rubin\nconfidence interval of $[0.025, 0.285]$ that excludes zero. Read the sensitivity\nstatistics next to that, and the picture is not reassuring. The Robustness Value\nis 0.00667 — two-thirds of one percent. Compare the OLS example earlier in this\nchapter, where $RV_{q=1}$ was 13.9%. This IV result is roughly twenty times more\nfragile than that one.\n\nThe benchmark bounds make it concrete, and they point the other way from what one\nmight hope. A confounder as strong as `black` explains 0.22% of the residual\nvariance of the instrument and 7.5% of the outcome, and under it the adjusted\ninterval becomes $[-0.021, 0.402]$. For `smsa` the figures are 0.64% and 2.0%,\ngiving $[-0.019, 0.396]$. **Both intervals contain zero.** A confounder no\nstronger than either benchmark covariate is enough to remove the significance of\nthe estimate.\n\nThat `smsa` number is worth a second look on its own terms: its instrument-side\npartial $R^2$ of 0.00639 sits just under the Robustness Value of 0.00667, so a\nconfounder of that strength lands essentially exactly on the tipping point. The\ntwo diagnostics agree.\n\nNone of this says the Card estimate is wrong. It says the identification rests on\nthe instrument being cleaner than `black` or `smsa` are as predictors, which is\nan assumption about college proximity that the data cannot check. We can also plot a contour plot to see how strong the confounder needs to be to explain away the treatment effect.\n\n\n```{.r .cell-code}\nplot(card.sens, parm = \"rf\", sensitivity.of = \"t-value\", lim = 0.08, kz = 1, ky = 1)\n```\n\n![](sensitivity-analysis_files/figure-html/unnamed-chunk-5-1.png){width=672}\n\nUnfortunately the package currently only allows for one instrument.  Should not be too hard to modify it to be more general.\n\n---\n\n<!-- see-also-footer -->\n*Systematic treatment: [R](https://xiangao.github.io/causal_econometrics_guide/sensitivity-analysis.html) · [Julia](https://xiangao.github.io/causal_econometrics_julia/sensitivity-analysis.html).*\n",
    "supporting": [
      "sensitivity-analysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}