{
  "hash": "b933f1f3de32941db5db72fe39eded73",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Causal Panel (why DDDiD)\"\ndate: \"2025-01-14\"\n---\n\n\n## Why DDDiD\n\nGuido Imbens has been saying DDDiD (Don't Do Diff in Diff).  But why?\n\n\nTo see that, DiD objective function (in the form of TWFE) is:\n\n$$ \\small (\\hat \\tau^{did}, \\hat \\mu, \\hat \\alpha, \\hat \\beta) = \\underset{\\tau, \\mu, \\alpha, \\beta}{argmin} { \\Sigma_{i=1}^N \\Sigma_{t=1}^T (Y_{it} - \\mu - \\alpha_i - \\beta_t - W_{it} \\tau)^2}$$ {#eq-causal-panel-1}\n\nWe can see that in this objective function, we are allowing only $\\alpha_i$ and $\\beta_t$ to capture the difference between units and time periods.  The obvious drawback is that control units that are less similar to a treated unit is given the same weight as those that are more similar.  A time period that is far from the beginning of the treatment period is given the same weight as those that are closer.  Say the treatment period is 2000, we have observations from 1988 to 2005, then 1988 observations are the same as 1999 observations.  This is not ideal.  The same logic applies to the units.\n\n\n## Synthetic Control\n\n\nSC objective function: $$ (\\hat \\tau^{sc}, \\hat \\mu, \\hat \\beta) = \\underset{\\tau, \\mu, \\beta}{argmin} { \\Sigma_{i=1}^N \\Sigma_{t=1}^T (Y_{it} - \\mu - \\beta_t - W_{it} \\tau)^2 \\hat \\omega_i^{sc}}$$ {#eq-causal-panel-2}\n\nIt's a weighted version of DiD, but note carefully that it is **not** a nesting of it: setting every $\\hat\\omega_i^{sc}$ to 1 here does not recover the DiD objective above, because SC has no $\\alpha_i$ term --- it would give a pooled regression with time effects only.  Dropping the unit fixed effects is a substantive restriction, not a re-weighting.  (DiD *is* nested in synthetic DiD below, which keeps $\\alpha_i$ and sets both weights to be constant; that is the right way to see DiD as a special case.)  The weights are set to optimally match donor units to the treated unit so that they are as close as possible at each time point.  There is no time weight.\n\n\n## Synthetic DiD\n\nArkhangelsky et al (2021) tries to combine the idea of DiD and SC. SC assigns different weights to different control units. The standard DiD is a TWFE, assigning equal weights to all time periods and units.\n\n$$ \\small (\\hat \\tau^{sdid}, \\hat \\mu, \\hat \\alpha, \\hat \\beta) = \\underset{\\tau, \\mu, \\alpha, \\beta}{argmin} { \\Sigma_{i=1}^N \\Sigma_{t=1}^T \\hat \\omega_i^{sdid} \\lambda_t^{sdid} (Y_{it} - \\mu - \\alpha_i - \\beta_t - W_{it} \\tau)^2}$$ {#eq-causal-panel-3}\n\nSDiD sets another weight in addition to SC weights, which changes over time. The SC weights are trying to construct a control unit that is close to the treated unit; the SDiD weights are trying to put more weights on pre-treatment periods that are more similar to post-treatment periods.\n\n## Example from synthdid\n\nThe data are the California Proposition 99 panel: annual per-capita cigarette\nsales in packs for 39 states from 1970 to 2000, with California the single\ntreated unit, 38 donors, 19 pre-treatment years and 12 post-treatment years.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(synthdid)\ndata('california_prop99')\nsetup = panel.matrices(california_prop99)\ntau.hat = synthdid_estimate(setup$Y, setup$N0, setup$T0)\nsummary(tau.hat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$estimate\n[1] -15.60383\n\n$se\n     [,1]\n[1,]   NA\n\n$controls\n               estimate 1\nNevada              0.124\nNew Hampshire       0.105\nConnecticut         0.078\nDelaware            0.070\nColorado            0.058\nIllinois            0.053\nNebraska            0.048\nMontana             0.045\nUtah                0.042\nNew Mexico          0.041\nMinnesota           0.039\nWisconsin           0.037\nWest Virginia       0.034\nNorth Carolina      0.033\nIdaho               0.031\nOhio                0.031\nMaine               0.028\nIowa                0.026\n\n$periods\n     estimate 1\n1988      0.427\n1986      0.366\n1987      0.206\n\n$dimensions\n          N1           N0 N0.effective           T1           T0 T0.effective \n       1.000       38.000       16.388       12.000       19.000        2.783 \n```\n\n\n:::\n:::\n\n\nThe estimate is $-15.60$ packs per capita, and the summary shows how it gets\nthere. The unit weights are concentrated — Nevada 0.124, New Hampshire 0.105,\nConnecticut 0.078 — giving an effective 16.4 donors out of 38. The time weights\nare more concentrated still: 0.427 on 1988, 0.366 on 1986 and 0.206 on 1987,\nwhich is an effective 2.8 pre-periods out of 19. That is the \"time-aware\" part of\nsynthetic DiD in numbers, and it is the mechanism behind the estimator's\nadvantage over plain DiD.\n\nNote also that `se` comes back `NA`. That is not a glitch: the default is a\njackknife standard error, which deletes one treated unit at a time, and\nCalifornia is the only treated unit. The placebo method is the usable option\nhere.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntau.sc   = sc_estimate(setup$Y, setup$N0, setup$T0)\ntau.did  = did_estimate(setup$Y, setup$N0, setup$T0)\nestimates = list(tau.did, tau.sc, tau.hat)\nnames(estimates) = c('Diff-in-Diff', 'Synthetic Control', 'Synthetic Diff-in-Diff')\nprint(unlist(estimates))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Diff-in-Diff      Synthetic Control Synthetic Diff-in-Diff \n             -27.34911              -19.61966              -15.60383 \n```\n\n\n:::\n:::\n\n\nPlain DiD gives $-27.35$, synthetic control $-19.62$, and synthetic DiD\n$-15.60$. The spread across the three is nearly twelve packs per capita, on the\nsame data with the same identification assumptions. DiD moves furthest because it\nweights all 38 donors and all 19 pre-periods equally: states unlike California,\nand years unlike the late 1980s, all count in full.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot <- synthdid_plot(estimates, facet.vertical=FALSE,\n              control.name='control', treated.name='california',\n              lambda.comparable=TRUE, se.method = 'none',\n              trajectory.linetype = 1, line.width=.75, effect.curvature=-.4,\n              trajectory.alpha=.7, effect.alpha=.7,\n              diagram.alpha=1, onset.alpha=.7) +\n    theme(legend.position=c(.26,.07), legend.direction='horizontal',\n          legend.key=element_blank(), legend.background=element_blank(),\n          strip.background=element_blank(), strip.text.x = element_blank())\nplot\n```\n\n::: {.cell-output-display}\n![](causal-panel_files/figure-html/did16-1.png){width=672}\n:::\n:::\n\n\nEach panel shows California's path against its weighted control, with the\nestimated effect as the post-1989 gap. Note: $\\lambda_t$ is plotted at the\nbottom, so the pre-periods that actually enter each comparison are visible —\nfor synthetic DiD they pile up on 1986–1988, while for DiD the weight is flat\nacross all nineteen years.\n\n## Summary\n\nTo me, \"DDDiD\" is saying DiD is too simple.  Even if all the identification assumptions are correct for DiD, namely parallel trend and no anticipation, there are still better ways to do it, in the sense of putting weights on units and time periods, such as synthetic DiD.\n\n---\n\n<!-- see-also-footer -->\n*Systematic treatment: [R](https://xiangao.github.io/causal_econometrics_guide/g-methods.html) · [Julia](https://xiangao.github.io/causal_econometrics_julia/g-methods.html).*\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}