{
  "hash": "b99f05f8befc0a696e230fd11914e9ad",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Fixed or Random Effect, or Both?\"\ndate: \"2019-05-23\"\n---\n\n\n\n## Panel data\n\nWith panel data — repeated observations over time or observations clustered at a higher level — the standard choice is between fixed and random effects. Consider\n\n$$ y_{it} = \\beta_0 + \\beta_1 x_{it} + c_i + \\epsilon_{it} $$ {#eq-fixed-random-effect-1}\n\nfor individuals $i = 1, \\ldots, n$ measured at $t = 1, \\ldots, T$, where $c_i$ is an unobserved time-invariant individual effect. The two approaches differ in how they handle $c_i$.\n\nFixed effects eliminate $c_i$ by demeaning or by including individual dummies (the two are equivalent in a linear model). In nonlinear models only Poisson avoids the incidental-parameter problem; the standard solution for other models is conditional likelihood (conditional logit, for example), which absorbs the fixed effects in the likelihood. When no conditional likelihood exists, the incidental-parameter bias shrinks with panel depth but does not vanish.\n\nRandom effects treat $c_i$ as part of the error term. This is more efficient but requires $x_{it}$ to be uncorrelated with $c_i$ — an assumption economists are generally skeptical of.\n\n## Time-invariant variables\n\nSometimes we want the effect of a time-invariant variable, so the model becomes\n\n$$ y_{it} = \\beta_0  + \\beta_1 x_{it} + c_i  + \\gamma z_i+ \\epsilon_{it} $$ {#eq-fixed-random-effect-2}\n\nFixed effects cannot identify $\\gamma$ because $z_i$ is perfectly collinear with $c_i$. Random effects can still estimate both, treating $z_i$ as another covariate.\n\n## Between-within model\n\nThe textbook advice is a Hausman test: random effects are more efficient when the uncorrelatedness assumption holds; if not, fixed effects are still consistent. The between-within model (BW) sidesteps the choice. [Neuhaus and Kalbfleisch (1998)](https://www.ncbi.nlm.nih.gov/pubmed/9629647) introduced the BW estimator,\n\n$$ y_{it} = \\beta_0  + \\beta_1 (x_{it} - \\bar x_i) + \\beta_2 \\bar x_i + c_i  + \\gamma z_i+ \\epsilon_{it} $$ {#eq-fixed-random-effect-3}\n\nHere $\\beta_1$ is the within effect — identical to the fixed-effect coefficient. $\\beta_2$ is the between effect (mean of $x$ on mean of $y$). $\\gamma$ is the effect of the time-invariant variable.\n\nThe other specification of BW estimator is\n\n$$ y_{it} = \\beta_0  + \\beta_1 x_{it}  + \\beta_2 \\bar x_i + c_i  + \\gamma z_i+ \\epsilon_{it} $$ {#eq-fixed-random-effect-4}\n\nThis is the same model reparametrized. $\\beta_1$ is unchanged, and $\\beta_2$ is now the between-minus-within difference (substitute $\\beta_1(x_{it}-\\bar x_i) + \\beta_2 \\bar x_i = \\beta_1 x_{it} + (\\beta_2-\\beta_1)\\bar x_i$ to see this). This is the \"contextual model\"; $\\beta_2$ is the contextual effect and acts as an embedded Hausman test.\n\nThe BW model has two advantages. It recovers the fixed-effect coefficient while estimating time-invariant covariates. And it extends naturally to cross-level interactions, random slopes, and other multilevel structures. Implementation is straightforward: run a random-effects model on either equation above.\n\n## BW model in R\n\nR's [`panelr`](https://panelr.jacob-long.com/articles/wbm.html) package implements BW models directly. The data are `WageData`, a balanced panel of 595 men observed over 7 years. We model log wage on weeks worked, union membership, marital status and occupation, all time-varying, plus two time-invariant covariates — black and female — that a fixed-effect model could not touch.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(panelr)\ndata(\"WageData\")\nwages <- panel_data(WageData, id = id, wave = t)\nmodel1 <- wbm(lwage ~ wks + union + ms + occ | blk + fem, data = wages)\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMODEL INFO:\nEntities: 595\nTime periods: 1-7\nDependent variable: lwage\nModel type: Linear mixed effects\nSpecification: within-between\n\nMODEL FIT:\nAIC = 2036.78, BIC = 2119.13\nPseudo-R² (fixed effects) = 0.27\nPseudo-R² (total) = 0.69\nEntity ICC = 0.57\n\nWITHIN EFFECTS:\n------------------------------------------\n               Est.   S.E.   t val.      p\n----------- ------- ------ -------- ------\nwks            0.00   0.00     1.06   0.29\nunion          0.06   0.03     2.53   0.01\nms            -0.08   0.03    -2.57   0.01\nocc           -0.08   0.02    -3.32   0.00\n------------------------------------------\n\nBETWEEN EFFECTS:\n-------------------------------------------------\n                      Est.   S.E.   t val.      p\n------------------ ------- ------ -------- ------\n(Intercept)           6.30   0.20    30.85   0.00\nimean(wks)            0.01   0.00     2.25   0.02\nimean(union)          0.15   0.03     4.67   0.00\nimean(ms)             0.17   0.05     3.07   0.00\nimean(occ)           -0.41   0.03   -13.31   0.00\nblk                  -0.15   0.05    -2.81   0.00\nfem                  -0.32   0.06    -4.96   0.00\n-------------------------------------------------\n\np values calculated using df = 4153 \n \nRANDOM EFFECTS:\n------------------------------------\n  Group      Parameter    Std. Dev. \n---------- ------------- -----------\n    id      (Intercept)    0.2992   \n Residual                  0.2589   \n------------------------------------\n```\n\n\n:::\n:::\n\n\nThe within estimates are 0.00 for weeks, 0.06 for union, $-0.08$ for married\nand $-0.08$ for occupation. The between estimates for the same four variables\nare 0.01, 0.15, 0.17 and $-0.41$ — two to five times larger, and for `ms` the\nopposite sign. That gap is the reason the fixed-versus-random choice matters\nhere: a random-effects model without the decomposition would blend the two and\nreport neither. The time-invariant covariates come out at $-0.15$ for black and\n$-0.32$ for female, quantities a fixed-effect model cannot produce at all.\n\nCompare with `lfe`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lfe)\nmodel2 <- felm(lwage ~ wks + union + ms + occ | id, data = wages)\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\n   felm(formula = lwage ~ wks + union + ms + occ | id, data = wages) \n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.89500 -0.16174  0.00652  0.17060  1.94521 \n\nCoefficients:\n       Estimate Std. Error t value Pr(>|t|)    \nwks    0.001083   0.001019   1.063 0.287816    \nunion  0.064320   0.025378   2.534 0.011305 *  \nms    -0.082905   0.032226  -2.573 0.010132 *  \nocc   -0.077507   0.023359  -3.318 0.000916 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.2589 on 3566 degrees of freedom\nMultiple R-squared(full model): 0.7304   Adjusted R-squared: 0.6852 \nMultiple R-squared(proj model): 0.006509   Adjusted R-squared: -0.1601 \nF-statistic(full model):16.16 on 598 and 3566 DF, p-value: < 2.2e-16 \nF-statistic(proj model): 5.841 on 4 and 3566 DF, p-value: 0.0001106 \n```\n\n\n:::\n:::\n\n`felm` gives 0.001083, 0.064320, $-0.082905$ and $-0.077507$ — the same four\nnumbers `panelr` reported as within effects, identical to machine precision\n(`WageData` is a balanced panel: 7 waves, 595 individuals). That is the BW\nmodel's selling point: it reproduces the fixed-effect estimates exactly while\nalso estimating the time-invariant covariates `blk` and `fem`, which `felm`\ncannot. `lfe` supports clustered standard errors, which `panelr` does not.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel3 <- felm(lwage ~ wks + union + ms + occ | id | 0 | id, data = wages)\nsummary(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\n   felm(formula = lwage ~ wks + union + ms + occ | id | 0 | id,      data = wages) \n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.89500 -0.16174  0.00652  0.17060  1.94521 \n\nCoefficients:\n       Estimate Cluster s.e. t value Pr(>|t|)  \nwks    0.001083     0.001331   0.814   0.4160  \nunion  0.064320     0.040936   1.571   0.1167  \nms    -0.082905     0.047399  -1.749   0.0808 .\nocc   -0.077507     0.031320  -2.475   0.0136 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.2589 on 3566 degrees of freedom\nMultiple R-squared(full model): 0.7304   Adjusted R-squared: 0.6852 \nMultiple R-squared(proj model): 0.006509   Adjusted R-squared: -0.1601 \nF-statistic(full model, *iid*):16.16 on 598 and 3566 DF, p-value: < 2.2e-16 \nF-statistic(proj model): 3.456 on 4 and 594 DF, p-value: 0.008358 \n```\n\n\n:::\n:::\n\n\nClustering on `id` leaves every coefficient untouched and changes the standard\nerrors substantially: `union` goes from 0.0254 to 0.0409, `ms` from 0.0322 to\n0.0474, `wks` from 0.00102 to 0.00133. Two of the four results do not survive.\n`union` falls from $p = 0.011$ to $p = 0.117$ and `ms` from $0.010$ to $0.081$;\nonly `occ` stays significant at 5%. With 7 observations per man the residuals\nare serially correlated, and the unclustered standard errors were treating 4,165\nobservations as though they were independent draws.\n\n## BW model in Stata\n\nStata has no dedicated BW command, but `xtreg` suffices. We switch to `nlswork`,\nan unbalanced panel of 4,710 women over 28,510 person-years, and regress log\nwage on age.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.stata .cell-code}\nwebuse nlswork\nxtset idcode\nxtreg ln_w age, fe cluster(idcode)\n\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(National Longitudinal Survey of Young Women, 14-24 years old in 1968)\n\n\nPanel variable: idcode (unbalanced)\n\n\nFixed-effects (within) regression               Number of obs     =     28,510\nGroup variable: idcode                          Number of groups  =      4,710\n\nR-squared:                                      Obs per group:\n     Within  = 0.1026                                         min =          1\n     Between = 0.0877                                         avg =        6.1\n     Overall = 0.0774                                         max =         15\n\n                                                F(1, 4709)        =     884.05\ncorr(u_i, Xb) = 0.0314                          Prob > F          =     0.0000\n\n                             (Std. err. adjusted for 4,710 clusters in idcode)\n------------------------------------------------------------------------------\n             |               Robust\n     ln_wage | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n         age |   .0181349   .0006099    29.73   0.000     .0169392    .0193306\n       _cons |   1.148214   .0177153    64.81   0.000     1.113483    1.182944\n-------------+----------------------------------------------------------------\n     sigma_u |  .40635023\n     sigma_e |  .30349389\n         rho |  .64192015   (fraction of variance due to u_i)\n------------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\nThe fixed-effect estimate is $.0181349$ with a clustered standard error of\n$.0006099$: within a woman, each additional year of age raises log wage by about\n1.8%. Keep that number in view — the BW model has to reproduce it.\n\nGenerate the group mean and run the BW estimation.\n\n::: {.cell}\n\n```{.stata .cell-code}\nwebuse nlswork\nxtset idcode\nbysort idcode: center age, prefix(d) mean(m)\nxtreg ln_w dage mage i.race, re cluster(idcode)\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(National Longitudinal Survey of Young Women, 14-24 years old in 1968)\n\n\nPanel variable: idcode (unbalanced)\n\n(generated variables: dage mage)\n\n\nRandom-effects GLS regression                   Number of obs     =     28,510\nGroup variable: idcode                          Number of groups  =      4,710\n\nR-squared:                                      Obs per group:\n     Within  = 0.1026                                         min =          1\n     Between = 0.1040                                         avg =        6.1\n     Overall = 0.0950                                         max =         15\n\n                                                Wald chi2(4)      =    1335.89\ncorr(u_i, X) = 0 (assumed)                      Prob > chi2       =     0.0000\n\n                             (Std. err. adjusted for 4,710 clusters in idcode)\n------------------------------------------------------------------------------\n             |               Robust\n     ln_wage | Coefficient  std. err.      z    P>|z|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n        dage |   .0181349     .00061    29.73   0.000     .0169394    .0193304\n        mage |    .022558   .0011405    19.78   0.000     .0203226    .0247933\n             |\n        race |\n      Black  |  -.1190246   .0127418    -9.34   0.000    -.1439982   -.0940511\n      Other  |   .0974996   .0617364     1.58   0.114    -.0235016    .2185008\n             |\n       _cons |   1.037566   .0323185    32.10   0.000     .9742233     1.10091\n-------------+----------------------------------------------------------------\n     sigma_u |  .36581005\n     sigma_e |  .30349389\n         rho |  .59230575   (fraction of variance due to u_i)\n------------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\nIn this BW model, we use the centered (within-group-demeaned) `dage` together with the group mean `mage`, which gives the standard within-between (Mundlak) decomposition: the coefficient on `dage`, .0181349, is exactly the fixed-effect (\"within\") coefficient on age reported above — the same seven digits, with a standard error of .00061 against .0006099 — and the coefficient on `mage`, .022558, is directly the between effect. Women who are older on average earn about 2.3% more per year of average age, against a within-woman return of 1.8%; the between effect is larger because it also carries cohort and selection differences that the within estimate sweeps out. And we have the effect of time-invariant covariate race estimated: Black women earn 11.9% less ($-.1190246$, SE .0127), while the \"Other\" category is not distinguishable from white ($.0975$, $p = 0.114$).  The advantage of using xtreg is that we have clustered standard errors implemented.\n\nNote: if we instead ran `xtreg ln_w age mage i.race, re cluster(idcode)` — using the raw (uncentered) `age` together with `mage` — we would get the *contextual model* instead: the coefficient on `age` stays .0181, but the coefficient on `mage` becomes .0044, the \"contextual effect\" (the *additional* between-effect on top of the within effect). The two models are algebraically related: contextual-model mage = Mundlak-model mage − Mundlak-model dage (here, .0226 − .0181 ≈ .0044).\n\n\n## BW model in non-linear models\n\n[Allison](https://statisticalhorizons.com/between-within-contextual-effects) applies the BW model to binary outcomes. The bias relative to conditional logit is an open question, but if the linear probability model is a reasonable approximation the BW approach should perform similarly for binary panel data.\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}