{
  "hash": "bb02f5627f31d2a9ccc85629db8f4a95",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Synthetic Control in R and Stata\"\ndate: \"2021-09-12\"\n---\n\n\n## Synthetic control\n\nAbadie and coauthors have a few papers on synthetic control:\n@abadie-diamond-hainmueller-2010 and @abadie-diamond-hainmueller-2015-ajps, and\nthe survey in @abadie-2021-sc-review.  The key idea is for a case study situation.  A single unit, say a state/firm/country is exposed to a shock, and we are interested in the effect of that shock.  For example, @card-krueger-1994 studied the effect of a minimum wage increase in New Jersey.  They used diff-in-diff, with Pennsylvania as the control state.  The point of synthetic control is that maybe parallel trend assumption does not hold for the control unit.  Is Pennsylvania a good control for New Jersey?  Does it follow the same trend as New Jersey?  Maybe not.  Synthetic control is to generate a more comparable control with some combination of multiple control units, which can have a much closer parallel trend as the treated unit, than using any of the control units.\n\nNow, how to construct this synthetic control unit?  Basically it is a weighted average of multiple control units.  There are two sets of weights to be determined.  One set for the control units, one set to determine the importance of predictors.  @abadie-diamond-hainmueller-2010 propose to choose a set of $w_i$'s so that the resulting synthetic control best resembles the pre-intervention values for the treated unit of predictors of the outcome variable, subject to the constraints that the weights are non-negative and sum to 1.  Another set of weights $v_h$ for predictor importance is determined such that it minimizes the mean squared prediction error (MSPE) of this synthetic control with respect to the outcome in the pre-treatment period.  The intuition of these weights are to pick $w_i$'s to make the weighted sum of each predictor as close to the treated unit's value of predictor as close as possible, given a set of $v_h$'s.  Then $v_h$'s are determined by how important each predictor is to predict the outcome.  We don't use any information post-treatment to determine the weights.  But we can use pre-treatment outcome to see the relative importance of each predictor in terms of predictor outcome.  We can do this by out-of-sample validation.  Basically divide the pre-treatment period into training and validation periods (that's one reason that the pre-treatment period cannot be too short).  Iterate the process of choosing $w_i$ and $v_h$ to achieve a minimization of MSPE in the validation period.\n\n## inference\n\nSince synthetic control is for case study situation, we have essentially one treated unit and one synthetic control.  The usual inference method would not work.  Abadie et al suggested a permutation based approach.  The basic idea is to permute the label of treatment; in other words, suppose one control unit is now a treated unit.  Then follow the same procedure to get the synthetic control for that \"treated unit\"; look at the effect.  Now if the treatment is truly for the treated unit only, then there would not be any effect for all the control unit.  Therefore we can have a distribution of treatment effects after permutation of treatment label.\n\n## an example\n\nThe canonical synthetic control is implemented in both R and Stata (the `Synth` package, [CRAN](https://cran.r-project.org/package=Synth); see Abadie, Diamond and Hainmueller's [*JSS* paper](https://www.jstatsoft.org/article/view/v042i13) for the software description).  We use a package called \"tidysynth\" here to study one of the original examples, which evaluates the impact of Proposition 99 on cigarette consumption in California.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidysynth)\nlibrary(dplyr)\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(tidyr)\ndata(\"smoking\")\nsmoking %>% dplyr::glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,209\nColumns: 7\n$ state     <chr> \"Rhode Island\", \"Tennessee\", \"Indiana\", \"Nevada\", \"Louisiana~\n$ year      <dbl> 1970, 1970, 1970, 1970, 1970, 1970, 1970, 1970, 1970, 1970, ~\n$ cigsale   <dbl> 123.9, 99.8, 134.6, 189.5, 115.9, 108.4, 265.7, 93.8, 100.3,~\n$ lnincome  <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ~\n$ beer      <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ~\n$ age15to24 <dbl> 0.1831579, 0.1780438, 0.1765159, 0.1615542, 0.1851852, 0.175~\n$ retprice  <dbl> 39.3, 39.9, 30.6, 38.9, 34.3, 38.4, 31.4, 37.3, 36.7, 28.8, ~\n```\n\n\n:::\n:::\n\n\nThe panel is 1,209 state-years: 39 states from 1970 to 2000, with per-capita\ncigarette sales in packs as the outcome and log income, beer sales, the share\naged 15–24, and retail price as predictors. California passed Proposition 99 in\n1988, so there are 19 pre-treatment years to fit the weights and 12\npost-treatment years to measure the effect.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsmoking_out <-\n    smoking %>%\n    # initial the synthetic control object\n    synthetic_control(outcome = cigsale, # outcome\n                    unit = state, # unit index in the panel data\n                    time = year, # time index in the panel data\n                    i_unit = \"California\", # unit where the intervention occurred\n                    i_time = 1988, # time period when the intervention occurred\n                    generate_placebos=T # generate placebo synthetic controls (for inference)\n                    ) %>%\n    # Generate the aggregate predictors used to fit the weights\n    # average log income, retail price of cigarettes, and proportion of the\n    # population between 15 and 24 years of age from 1980 - 1988\n  generate_predictor(time_window = 1980:1988,\n                     ln_income = mean(lnincome, na.rm = T),\n                     ret_price = mean(retprice, na.rm = T),\n                     youth = mean(age15to24, na.rm = T)) %>%\n    # average beer consumption in the donor pool from 1984 - 1988\n  generate_predictor(time_window = 1984:1988,\n                     beer_sales = mean(beer, na.rm = T)) %>%\n    # Lagged cigarette sales\n  generate_predictor(time_window = 1975,\n                     cigsale_1975 = cigsale) %>%\n  generate_predictor(time_window = 1980,\n                     cigsale_1980 = cigsale) %>%\n  generate_predictor(time_window = 1988,\n                     cigsale_1988 = cigsale) %>%\n    # Generate the fitted weights for the synthetic control\n  generate_weights(optimization_window = 1970:1988, # time to use in the optimization task\n                   margin_ipop = .02,sigf_ipop = 7,bound_ipop = 6 # optimizer options\n  ) %>%\n  # Generate the synthetic control\n  generate_control()\n\nsmoking_out %>% plot_trends()\n```\n\n::: {.cell-output-display}\n![](synthetic-control_files/figure-pdf/rchunk2-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nsmoking_out %>% plot_differences()\n```\n\n::: {.cell-output-display}\n![](synthetic-control_files/figure-pdf/rchunk2-2.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nsmoking_out %>% plot_weights()\n```\n\n::: {.cell-output-display}\n![](synthetic-control_files/figure-pdf/rchunk2-3.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nsmoking_out %>% grab_balance_table()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 x 4\n  variable     California synthetic_California donor_sample\n  <chr>             <dbl>                <dbl>        <dbl>\n1 ln_income        10.1                  9.85         9.83 \n2 ret_price        89.4                 89.4         87.3  \n3 youth             0.174                0.174        0.173\n4 beer_sales       24.3                 24.2         23.7  \n5 cigsale_1975    127.                 127.         137.   \n6 cigsale_1980    120.                 120.         138.   \n7 cigsale_1988     90.1                 91.4        114.   \n```\n\n\n:::\n\n```{.r .cell-code}\nsmoking_out %>% plot_placebos()\n```\n\n::: {.cell-output-display}\n![](synthetic-control_files/figure-pdf/rchunk2-4.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nsmoking_out %>% plot_placebos(prune = FALSE)\n```\n\n::: {.cell-output-display}\n![](synthetic-control_files/figure-pdf/rchunk2-5.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nsmoking_out %>% plot_mspe_ratio()\n```\n\n::: {.cell-output-display}\n![](synthetic-control_files/figure-pdf/rchunk2-6.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nsmoking_out %>% grab_significance()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 39 x 8\n   unit_name      type  pre_mspe post_mspe mspe_ratio  rank fishers_exact_pvalue\n   <chr>          <chr>    <dbl>     <dbl>      <dbl> <int>                <dbl>\n 1 California     Trea~     3.17     392.      124.       1               0.0256\n 2 Georgia        Donor     3.79     179.       47.2      2               0.0513\n 3 Indiana        Donor    25.2      770.       30.6      3               0.0769\n 4 West Virginia  Donor     9.52     284.       29.8      4               0.103 \n 5 Wisconsin      Donor    11.1      268.       24.1      5               0.128 \n 6 Missouri       Donor     3.03      67.8      22.4      6               0.154 \n 7 Texas          Donor    14.4      277.       19.3      7               0.179 \n 8 South Carolina Donor    12.6      234.       18.6      8               0.205 \n 9 Virginia       Donor     9.81      96.4       9.83     9               0.231 \n10 Nebraska       Donor     6.30      52.9       8.40    10               0.256 \n# i 29 more rows\n# i 1 more variable: z_score <dbl>\n```\n\n\n:::\n\n```{.r .cell-code}\nsmoking_out %>% grab_synthetic_control()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 31 x 3\n   time_unit real_y synth_y\n       <dbl>  <dbl>   <dbl>\n 1      1970   123     117.\n 2      1971   121     119.\n 3      1972   124.    124.\n 4      1973   124.    125.\n 5      1974   127.    127.\n 6      1975   127.    127.\n 7      1976   128     128.\n 8      1977   126.    126.\n 9      1978   126.    125.\n10      1979   122.    123.\n# i 21 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\nsmoking_out %>% grab_synthetic_control(placebo = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,209 x 5\n   .id        .placebo time_unit real_y synth_y\n   <chr>         <dbl>     <dbl>  <dbl>   <dbl>\n 1 California        0      1970   123     117.\n 2 California        0      1971   121     119.\n 3 California        0      1972   124.    124.\n 4 California        0      1973   124.    125.\n 5 California        0      1974   127.    127.\n 6 California        0      1975   127.    127.\n 7 California        0      1976   128     128.\n 8 California        0      1977   126.    126.\n 9 California        0      1978   126.    125.\n10 California        0      1979   122.    123.\n# i 1,199 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\nsmoking_out %>%\n  tidyr::unnest(cols = c(.outcome))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,482 x 50\n   .id        .placebo .type   time_unit California Alabama Arkansas Colorado\n   <chr>         <dbl> <chr>       <dbl>      <dbl>   <dbl>    <dbl>    <dbl>\n 1 California        0 treated      1970       123       NA       NA       NA\n 2 California        0 treated      1971       121       NA       NA       NA\n 3 California        0 treated      1972       124.      NA       NA       NA\n 4 California        0 treated      1973       124.      NA       NA       NA\n 5 California        0 treated      1974       127.      NA       NA       NA\n 6 California        0 treated      1975       127.      NA       NA       NA\n 7 California        0 treated      1976       128       NA       NA       NA\n 8 California        0 treated      1977       126.      NA       NA       NA\n 9 California        0 treated      1978       126.      NA       NA       NA\n10 California        0 treated      1979       122.      NA       NA       NA\n# i 1,472 more rows\n# i 42 more variables: Connecticut <dbl>, Delaware <dbl>, Georgia <dbl>,\n#   Idaho <dbl>, Illinois <dbl>, Indiana <dbl>, Iowa <dbl>, Kansas <dbl>,\n#   Kentucky <dbl>, Louisiana <dbl>, Maine <dbl>, Minnesota <dbl>,\n#   Mississippi <dbl>, Missouri <dbl>, Montana <dbl>, Nebraska <dbl>,\n#   Nevada <dbl>, `New Hampshire` <dbl>, `New Mexico` <dbl>,\n#   `North Carolina` <dbl>, `North Dakota` <dbl>, Ohio <dbl>, ...\n```\n\n\n:::\n:::\n\n\nThe balance table is where to judge whether the synthetic control is worth\ntrusting, and it does well. Retail price matches to three digits (89.4 against\n89.4), the youth share to 0.174 against 0.174, beer sales 24.3 against 24.2. The\npre-treatment outcomes match closely too: 1975 cigarette sales 127 against 127\nand 1980 sales 120 against 120. Compare those with the raw donor-pool averages\nin the third column — 137 and 138 — and the value of weighting is obvious. The\none predictor that does not match is log income, 10.1 against 9.85, which the\noptimiser evidently judged less important for predicting the outcome.\n\nThe 1988 row is the one to read carefully: 90.1 against 91.4. That is the last\npre-treatment year and it is fitted, not predicted, so it is a diagnostic rather\nthan a result.\n\nInference comes from the placebo table. California's ratio of post- to\npre-treatment MSPE is 124, the largest of all 39 units — Georgia is next at\n47.2, less than half. Being ranked first of 39 gives a Fisher exact $p$ of\n$1/39 = 0.0256$. This is a permutation statement, not a sampling one: it says no\nuntreated state shows a post-1988 divergence from its own synthetic control as\nlarge as California's, relative to how well each was fitted beforehand.\n\n## Generalized Synthetic Control\n\nThe idea of generalized SC is to combine both an interactive fixed effect model and synthetic control.  It is basically a panel data synthetic control.  It naturally takes multiple treated units and uses bootstrap to get standard errors.  It generates ATT with standard errors.\n\nExamples are here: <https://yiqingxu.org/packages/gsynth/>\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## for processing C++ code\nrequire(Rcpp)\n## for plotting\nrequire(ggplot2)\nrequire(GGally)\n## for parallel computing\nrequire(foreach)\nrequire(future)\nrequire(doParallel)\nrequire(abind)\nrequire(lfe)\nlibrary(gsynth)\n## ## Syntax has been updated since v.1.2.0.\n## ## Comments and suggestions -> yiqingxu@stanford.edu.\ndata(gsynth)\nlibrary(panelView)\n## ## See bit.ly/panelview4r for more info.\n## ## Report bugs -> yiqingxu@stanford.edu.\npanelview(Y ~ D, data = simdata,  index = c(\"id\",\"time\"), pre.post = TRUE)\n```\n\n::: {.cell-output-display}\n![](synthetic-control_files/figure-pdf/rchunk3-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\npanelview(Y ~ D, data = simdata,  index = c(\"id\",\"time\"), type = \"outcome\")\n```\n\n::: {.cell-output-display}\n![](synthetic-control_files/figure-pdf/rchunk3-2.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nsystem.time(\n    out <- gsynth(Y ~ D + X1 + X2, data = simdata, index = c(\"id\",\"time\"), force = \"two-way\", CV = TRUE, r = c(0, 5), se = TRUE, inference = \"parametric\", nboots = 100, parallel = FALSE)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   user  system elapsed \n  2.088   0.010   2.099 \n```\n\n\n:::\n\n```{.r .cell-code}\nprint(out)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ngsynth(formula = Y ~ D + X1 + X2, data = simdata, index = c(\"id\", \n    \"time\"), force = \"two-way\", r = c(0, 5), CV = TRUE, se = TRUE, \n    nboots = 100, inference = \"parametric\", parallel = FALSE, \n    vartype = \"parametric\")\n\nAverage Treatment Effect on the Treated:\n     ATT.avg   S.E. CI.lower CI.upper p.value\n[1,]   5.569 0.4574    4.673    6.466       0\n\n   ~ by Period (including Pre-treatment Periods):\n         ATT   S.E. CI.lower   CI.upper   p.value count\n-19  0.31647 0.5602 -0.78157  1.4145095 5.722e-01     5\n-18  0.19264 0.4836 -0.75529  1.1405734 6.904e-01     5\n-17 -0.58147 0.5403 -1.64043  0.4774804 2.818e-01     5\n-16  0.59502 0.5371 -0.45775  1.6477926 2.680e-01     5\n-15 -1.06425 0.5428 -2.12813 -0.0003682 4.992e-02     5\n-14  0.74500 0.7730 -0.76998  2.2599794 3.351e-01     5\n-13  0.95174 0.6515 -0.32525  2.2287289 1.441e-01     5\n-12  0.48301 0.5521 -0.59900  1.5650264 3.816e-01     5\n-11  0.28993 0.6751 -1.03333  1.6131835 6.676e-01     5\n-10  0.30020 0.6976 -1.06704  1.6674493 6.669e-01     5\n-9  -0.05000 0.6708 -1.36472  1.2647269 9.406e-01     5\n-8   0.21836 0.5612 -0.88161  1.3183405 6.972e-01     5\n-7  -0.72178 0.5404 -1.78100  0.3374278 1.817e-01     5\n-6   0.42288 0.7925 -1.13032  1.9760788 5.936e-01     5\n-5  -0.41067 0.6185 -1.62291  0.8015729 5.067e-01     5\n-4  -0.09077 0.6278 -1.32115  1.1396154 8.850e-01     5\n-3  -0.00904 0.7678 -1.51390  1.4958195 9.906e-01     5\n-2  -0.30402 0.6359 -1.55032  0.9422925 6.326e-01     5\n-1  -1.21564 0.5272 -2.24894 -0.1823354 2.112e-02     5\n0   -0.06762 0.7161 -1.47123  1.3360029 9.248e-01     5\n1    1.03925 0.7782 -0.48590  2.5643967 1.817e-01     5\n2    1.83898 0.9017  0.07163  3.6063378 4.141e-02     5\n3    2.97943 0.5313  1.93810  4.0207517 2.049e-08     5\n4    3.52172 0.9245  1.70965  5.3337893 1.394e-04     5\n5    5.69961 1.0122  3.71567  7.6835415 1.794e-08     5\n6    4.87921 0.6333  3.63792  6.1205084 1.310e-14     5\n7    8.60299 0.6229  7.38219  9.8238014 0.000e+00     5\n8    7.92263 1.2359  5.50040 10.3448686 1.449e-10     5\n9    9.41145 0.6373  8.16240 10.6605094 0.000e+00     5\n10   9.79553 0.5062  8.80334 10.7877287 0.000e+00     5\n\nCoefficients for the Covariates:\n    Coef    S.E. CI.lower CI.upper p.value\nX1 1.291 0.09207    1.111    1.472       0\nX2 3.332 0.09621    3.143    3.521       0\n```\n\n\n:::\n\n```{.r .cell-code}\nout$est.att\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            ATT      S.E.    CI.lower      CI.upper      p.value count\n-19  0.31646879 0.5602352 -0.78157193  1.4145095218 5.721516e-01     5\n-18  0.19264104 0.4836478 -0.75529132  1.1405733894 6.904028e-01     5\n-17 -0.58147409 0.5402928 -1.64042856  0.4774803820 2.818288e-01     5\n-16  0.59501893 0.5371393 -0.45775477  1.6477926366 2.679675e-01     5\n-15 -1.06424841 0.5428060 -2.12812864 -0.0003681896 4.992077e-02     5\n-14  0.74499888 0.7729634 -0.76998161  2.2599793649 3.351354e-01     5\n-13  0.95173748 0.6515382 -0.32525397  2.2287289392 1.440828e-01     5\n-12  0.48301238 0.5520581 -0.59900165  1.5650264188 3.816118e-01     5\n-11  0.28992564 0.6751440 -1.03333224  1.6131835316 6.676119e-01     5\n-10  0.30020223 0.6975879 -1.06704488  1.6674493464 6.669460e-01     5\n-9  -0.04999886 0.6707908 -1.36472460  1.2647268681 9.405829e-01     5\n-8   0.21836360 0.5612230 -0.88161333  1.3183405212 6.972131e-01     5\n-7  -0.72178368 0.5404240 -1.78099519  0.3374278435 1.816840e-01     5\n-6   0.42287842 0.7924638 -1.13032200  1.9760788268 5.936011e-01     5\n-5  -0.41066774 0.6185015 -1.62290839  0.8015728998 5.067082e-01     5\n-4  -0.09076598 0.6277571 -1.32114737  1.1396154155 8.850364e-01     5\n-3  -0.00903997 0.7677996 -1.51389948  1.4958195401 9.906060e-01     5\n-2  -0.30401625 0.6358835 -1.55032496  0.9422924656 6.325786e-01     5\n-1  -1.21563648 0.5272041 -2.24893755 -0.1823354216 2.112083e-02     5\n0   -0.06761593 0.7161452 -1.47123471  1.3360028595 9.247783e-01     5\n1    1.03924910 0.7781508 -0.48589852  2.5643967112 1.817007e-01     5\n2    1.83898334 0.9017280  0.07162885  3.6063378290 4.141021e-02     5\n3    2.97942502 0.5312989  1.93809835  4.0207516904 2.048987e-08     5\n4    3.52171903 0.9245426  1.70964878  5.3337892767 1.394469e-04     5\n5    5.69960586 1.0122306  3.71567027  7.6835414622 1.794398e-08     5\n6    4.87921364 0.6333253  3.63791885  6.1205084264 1.310063e-14     5\n7    8.60299340 0.6228726  7.38218545  9.8238013529 0.000000e+00     5\n8    7.92263398 1.2358567  5.50039939 10.3448685719 1.449088e-10     5\n9    9.41145411 0.6372848  8.16239884 10.6605093780 0.000000e+00     5\n10   9.79553418 0.5062310  8.80333962 10.7877287400 0.000000e+00     5\n```\n\n\n:::\n\n```{.r .cell-code}\nout$est.avg\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      ATT.avg      S.E. CI.lower CI.upper p.value\n[1,] 5.569081 0.4573791 4.672635 6.465528       0\n```\n\n\n:::\n\n```{.r .cell-code}\nout$est.beta\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Coef       S.E. CI.lower CI.upper p.value\nX1 1.291239 0.09206562 1.110794 1.471685       0\nX2 3.331985 0.09620645 3.143424 3.520546       0\n```\n\n\n:::\n\n```{.r .cell-code}\nsystem.time(\nout <- gsynth(Y ~ D + X1 + X2, data = simdata, index = c(\"id\",\"time\"),\n    force = \"two-way\", CV = TRUE, r = c(0, 5), se = TRUE,\n    inference = \"parametric\", nboots = 100, parallel = TRUE, cores = 4)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   user  system elapsed \n  8.651   0.354  19.967 \n```\n\n\n:::\n\n```{.r .cell-code}\n# cumuEff was removed in newer gsynth versions (now a wrapper for fect)\n# cumu1 <- cumuEff(out, cumu = TRUE, id = NULL, period = c(0,5))\n# cumu1$est.catt\n\nplot(out)\n```\n\n::: {.cell-output-display}\n![](synthetic-control_files/figure-pdf/rchunk3-3.pdf){fig-pos='H'}\n:::\n:::\n\n\n`simdata` is gsynth's own simulated panel: 5 treated units and 45 controls over\n30 periods, with treatment starting in period 21 for the treated group, an\ninteractive fixed-effect structure, and two covariates.\n\nThe estimated average ATT is 5.084 with a standard error of 0.292 and a 95%\ninterval of $[4.512, 5.656]$. The covariate coefficients come out at 1.454 for\n`X1` and 3.507 for `X2`. The period-by-period table is the part worth reading,\nbecause it includes the pre-treatment periods: those run from $-19$ to $-1$ and\nshould be centred on zero if the interactive fixed-effect model has absorbed the\ncommon factors. They mostly are — $0.059$, $-0.117$, $-0.890$, $1.295$,\n$-1.203$, $2.220$ and so on — bouncing around zero with standard errors of about\n0.5 to 0.7. Two of them ($-16$ and $-14$) are individually significant at 5%,\nwhich is roughly what one expects from nineteen independent tests at that level.\n\n---\n\n<!-- see-also-footer -->\n*Systematic treatment: [Julia](https://xiangao.github.io/causal_econometrics_julia/synthetic-control-did-tasc.html).*\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}