{
  "hash": "061c878462cdfcf131a3c7b2667862a6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"When is OLS coefficient the ATE\"\ndate: \"2021-11-03\"\n---\n\n\n\n\n## OLS cannot be ATE (most of the time)\n\n[Słoczyński](https://doi.org/10.1162/rest_a_01072) clarifies when the OLS coefficient on a treatment dummy can and cannot be read as the ATE.\n\nConsider the standard setup:\n\n$$ y = \\alpha + \\tau d + X \\beta $$ {#eq-ols-ate-1}\n\nHere $d$ is the treatment dummy and $X$ the covariates, under unconfoundedness. If the treatment effect is homogeneous, $\\tau$ is the ATE. Under heterogeneous effects, $\\tau$ is a convex combination of ATT and ATU — but with weights that are inversely proportional to the treatment shares. The more treated units there are, the less weight falls on ATT.\n\nBy definition,\n\n$$ \\tau_{ATE} = \\rho \\tau_{ATT} + (1- \\rho) \\tau_{ATU} $$ {#eq-ols-ate-2}\n\nThe main result from the paper is:\n\n$$ \\tau = (1- \\rho) \\tau_{ATT} + \\rho \\tau_{ATU} $$ {#eq-ols-ate-3}\n\n\nwhere $\\rho = P(d=1)$, the proportion of treated; $\\tau_{ATT} = E(y(1)-y(0) | d=1)$, $\\tau_{ATU} = E(y(1)-y(0) | d=0)$, and $\\tau_{ATE} = E(y(1)-y(0))$.\n\nFrom these two equations, we see that $\\tau$ and $\\tau_{ATE}$ are quite different, unless the weight on ATT happens to equal $\\rho$.  A caution on reading this too simply: the clean form $\\tau = (1-\\rho)\\tau_{ATT} + \\rho\\tau_{ATU}$ with $\\rho = P(d=1)$ is the **no-covariate special case** (or, with covariates, holds in terms of *covariate-adjusted* treatment-probability weights, not the raw marginal share).  In Słoczyński's general result the weights depend on the conditional treatment probabilities (the propensity score), so a 50/50 *marginal* treatment share alone does **not** guarantee that OLS recovers the ATE — what matters is the covariate-adjusted weighting.  With that caveat, the intuition stands: the more imbalanced the (conditional) treatment probabilities, the further OLS can be from the ATE.\n\nGiven the true propensity score, ATT, ATU, and ATE can be separated. In practice we use the estimated propensity score. Słoczyński provides the `hettreatreg` package in R and Stata.\n\nThe data are `nswcps`: the NSW experimental treatment group combined with a large\nCPS comparison sample, so the treated are a tiny fraction of the whole. The\noutcome is 1978 earnings and the covariates are age, its square, education, race,\nmarital status, degree status, and earnings in 1974 and 1975. This is the classic\nLaLonde setting, and its extreme treatment imbalance is exactly what makes the\nweighting result bite.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(hettreatreg)\ndata(\"nswcps\")\n\nsummary(lm(re78 ~ treated + age + age2 + educ + black + hispanic + married + nodegree  + re74 + re75, data = nswcps))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = re78 ~ treated + age + age2 + educ + black + hispanic + \n    married + nodegree + re74 + re75, data = nswcps)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-25130  -3601   1274   3668  55040 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 7634.34415  736.67074  10.363  < 2e-16 ***\ntreated      793.58704  548.25433   1.447  0.14778    \nage         -233.67749   41.18067  -5.674 1.42e-08 ***\nage2           1.81437    0.56099   3.234  0.00122 ** \neduc         166.84923   28.65984   5.822 5.94e-09 ***\nblack       -790.60856  213.24523  -3.708  0.00021 ***\nhispanic    -175.97512  218.99126  -0.804  0.42166    \nmarried      224.26599  149.84542   1.497  0.13450    \nnodegree     311.84453  178.51743   1.747  0.08068 .  \nre74           0.29534    0.01222  24.175  < 2e-16 ***\nre75           0.47064    0.01216  38.700  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7002 on 16166 degrees of freedom\nMultiple R-squared:  0.4762,\tAdjusted R-squared:  0.4758 \nF-statistic:  1469 on 10 and 16166 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\noutcome <- nswcps$re78\ntreated <- nswcps$treated\nour_vars <- c(\"age\", \"age2\", \"educ\", \"black\", \"hispanic\", \"married\", \"nodegree\", \"re74\", \"re75\")\ncovariates <- subset(nswcps, select = our_vars)\n\nhettreatreg(outcome, treated, covariates, verbose = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\"OLS\" is the estimated regression coefficient on treated. \n \n   OLS = 793.6 \n \nP(d=1) = 0.011 \nP(d=0) = 0.989 \n \n    w1 = 0.983 \n    w0 = 0.017 \n delta = -0.971 \n \n   ATE = -6751 \n   ATT = 928.4 \n   ATU = -6840 \n \nOLS = w1*ATT + w0*ATU = 793.6 \n \n```\n\n\n:::\n:::\n\n\nThe output is the theorem in numbers. OLS puts 793.6 on `treated`. Only 1.1% of\nthe sample is treated, $P(d=1) = 0.011$, and the implied OLS weights are\n$w_1 = 0.983$ on ATT and $w_0 = 0.017$ on ATU. Compare those with the ATE's own\nweights, which are $\\rho = 0.011$ on ATT and $0.989$ on ATU: they are very nearly\nreversed. The package prints the identity directly,\n$\\text{OLS} = w_1\\,\\text{ATT} + w_0\\,\\text{ATU} = 793.6$, which closes exactly.\n\nThe consequences are not subtle. ATT is 928.4, ATU is $-6840$, and ATE is\n$-6751$. So the OLS coefficient of 793.6 sits within 135 of the ATT and roughly\n7,500 away from the ATE — and on the *opposite side of zero*. Reading 793.6 as\n\"the effect of training on earnings\" would get the sign wrong for the population.\nThe `delta` of $-0.971$ that the package reports is the gap between the OLS\nweight on ATT and $\\rho$; it is close to $-1$, its extreme value.\n\nSłoczyński's paper itself is an algebraic decomposition of the OLS coefficient $\\tau$ in terms of ATT/ATU weights; it does not propose or endorse the propensity-score-as-covariate estimator below as a general-purpose way to recover ATT/ATU/ATE. What follows is our own illustrative exercise, done in three steps, to see how such an estimator would behave in practice: First, estimate the propensity score equation, basically\n\n$$ d = X \\gamma $$ {#eq-ols-ate-4}\n\nSecond, include the predicted propensity score as a covariate and estimate the model with treatment and control group separately. Note that regressing $Y$ linearly on the scalar propensity score $p(X)$ assumes $E[Y(d) \\mid p(X)]$ is linear in $p(X)$ — a strong and generally untested assumption, unlike matching/weighting directly on the propensity score, or regression adjustment on the covariates $X$ themselves, which are the standard approaches. Treat the numbers below as an exploratory illustration rather than a recommended estimator.\n\nThird, predict the counterfactuals for the full sample.  Then we get the ATE, ATT and ATU.\n\nOne more reason to treat this as illustration rather than method: the propensity score here comes from a linear probability model, and on these data it runs from $-0.034$ to $0.154$ --- some fitted \"probabilities\" are negative.  That is harmless when the score is used merely as a regressor, as it is here, but it would be fatal if the same score were used as an inverse-probability weight.\n\nLet's see with the same data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_propensity <- lm(treated ~ age + age2 + educ + black + hispanic + married + nodegree  + re74 + re75, data=nswcps)\nps <- predict(m_propensity)\ndf_combined <- data.frame(nswcps, ps)\ndf.1 <- df_combined[which(treated == 1),]\ndf.0 <- df_combined[which(treated == 0),]\nm_ot <- lm(re78 ~ ps, data = df.1)\not <- suppressWarnings(predict(m_ot, newdata = df_combined)) # add newdata option to predict for full sample\n\nm_oc <- lm(re78 ~ ps, data = df.0)\noc <- suppressWarnings(predict(m_oc, newdata = df_combined)) # add newdata option to predict for full sample\n\nte <- ot - oc\nate <- mean(te)\ndf_combined$te <- te\natt <- as.numeric(mean(df_combined[which(treated == 1),'te']))\natu <- as.numeric(mean(df_combined[which(treated == 0),'te']))\n\nprint(paste(\"ate=\", signif(ate, 4)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"ate= -6751\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(paste(\"att=\", signif(att, 4)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"att= 928.4\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(paste(\"atu=\", signif(atu, 4)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"atu= -6840\"\n```\n\n\n:::\n:::\n\nThis reproduces the package's decomposition exactly: ATE $-6751$, ATT 928.4, ATU\n$-6840$, the same three numbers to four significant figures.\n\nWe see in this case OLS coefficient is hugely different from ATE.  This is because $P(d=1)$ is only .01, about 1 percent; we have much larger control group than treatment group.  In this case, the OLS coefficient is far different from ATE; in fact, it's pretty close to ATT.\n\nNow, what's the intuition that OLS coefficient is just the opposite as the ATE in terms of weighting ATT and ATU?  The reason is that OLS is to predict actual outcome, not counterfactual outcome.  For calculating ATE, we need counterfactual outcome predicted.  Now suppose we have a lot of control observations, we'd much better predicting $(y(0)| d==0)$ rather than $(y(1) | d==1)$.  That is, we are better getting the slope of $(y(0) | d==0, X=x)$; therefore predicting $(y(0) | d==1, X=x)$.  Therefore although treatment group has less observations, but because the $(y(0) | d==1)$ is better predicted,  the ATT is better estimated, thus more weight.  If the opposite happens, then the ATU should be more heavily weighted.  Thus the counter-intuitive weighting.\n\n## Regression adjustment\n\nSłoczyński's method is to include propensity score as a covariate.  This propensity score serves as a proxy as all covariates.  As Rosenbaum and Rubin (1983) showed, the propensity score is a balancing score (treatment is independent of the covariates given the propensity score).  Another way to allow treatment effect to differ across all covariates is to allow interaction of treatment dummy with all covariates, then I am doing \"Regression Adjustment\" (see Stata's `teffects ra`, used in the [treatment effects and matching chapter](treatment-matching.qmd); note this is not `treatreg`, which was the old endogenous-treatment command, superseded by `etregress`).  We can calculate ATE, ATT, ATU after the linear model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlm1 <- lm(re78 ~ treated*(age + age2 +  educ + black + hispanic + married + nodegree  + re74 + re75), data = nswcps)\ny1 <- predict(lm1,newdata=nswcps %>% mutate(treated=1))\ny0 <- predict(lm1,newdata=nswcps %>% mutate(treated=0))\nate=mean(y1-y0) #ate\nprint(paste(\"ate=\",  signif(ate, 4)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"ate= -4930\"\n```\n\n\n:::\n\n```{.r .cell-code}\ny1.att <- predict(lm1,newdata=nswcps %>% filter(treated==1))\ny0.att <- predict(lm1,newdata=nswcps %>% filter(treated==1) %>% mutate(treated=0))\natt=mean(y1.att)-mean(y0.att) #att\nprint(paste('att=',  signif(att, 4)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"att= 796\"\n```\n\n\n:::\n\n```{.r .cell-code}\ny1.atu <- predict(lm1,newdata=nswcps %>% filter(treated==0) %>% mutate(treated=1))\ny0.atu <- predict(lm1,newdata=nswcps %>% filter(treated==0))\natu=mean(y1.atu)-mean(y0.atu) #atu\nprint(paste('atu=', signif(atu, 4)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"atu= -4996\"\n```\n\n\n:::\n:::\n\n\nRegression adjustment gives ATE $-4930$, ATT 796 and ATU $-4996$.\n\nWe see this is somewhat different from Słoczyński's method, which gave $-6751$,\n928.4 and $-6840$: the two agree on sign and order of magnitude but not on\nlevel, unsurprisingly, since one regresses on a scalar propensity score and the\nother interacts the treatment with all nine covariates. But the point is the original OLS coefficient 794 is nowhere close to ATE under either approach — $-4930$ or $-6751$, both far away and both negative.  In this case, it's very close to ATT (796 by regression adjustment, 928 by the propensity-score route), as the treatment group is very small.\n\n---\n\n<!-- see-also-footer -->\n*Systematic treatment: [R](https://xiangao.github.io/causal_econometrics_guide/estimation.html) · [Julia](https://xiangao.github.io/causal_econometrics_julia/estimation.html).*\n",
    "supporting": [
      "ols-ate_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}