{
  "hash": "df7c1cb078a400a887b703aedb81a2e8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Extended TWFE and other DiD estimators\"\ndate: \"2024-12-09\"\n---\n\n\n## Staggered DiD without treatment reversal\n\nThis blog is adopted from the tutorial of paneltools package.\nhttps://yiqingxu.org/tutorials/panel.html#Installing_Packages\n\nI added Wooldridge's ETWFE, which is my favorite estimator with staggered DiD.  It is easy to understand and implement.  It also works with nonlinear model such as logit and poisson.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#devtools:: install_github(\"xuyiqing/paneltools\")\nlibrary(paneltools)\ndata(paneltools)\nlibrary(tidyverse)\nhh2019 <- as_tibble(hh2019)\nhh2019\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 22,971 × 4\n     bfs  year nat_rate_ord indirect\n   <dbl> <dbl>        <dbl>    <dbl>\n 1     1  1991         0           0\n 2     1  1992         0           0\n 3     1  1993         0           0\n 4     1  1994         3.45        0\n 5     1  1995         0           0\n 6     1  1996         0           0\n 7     1  1997         0           0\n 8     1  1998         0           0\n 9     1  1999         0           0\n10     1  2000         0           0\n# ℹ 22,961 more rows\n```\n\n\n:::\n:::\n\n\nThis data is from @hainmueller-hangartner-2019, in which the authors investigate the effects of indirect democracy (versus direct democracy) on naturalization rates in Switzerland using municipality-year level panel data from 1991 to 2009. The study shows that a switch from direct to indirect democracy increased naturalization rates by an average of 1.22 percentage points (Model 1 of Table 1 in the paper).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#devtools:: install_github(\"xuyiqing/panelView\")\nlibrary(panelView)\npanelview(nat_rate_ord ~ indirect, data = hh2019, index = c(\"bfs\",\"year\"),\n  xlab = \"Year\", ylab = \"Unit\", display.all = T,\n  gridOff = TRUE, by.timing = TRUE)\n```\n\n::: {.cell-output-display}\n![](extended-twfe_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nThe panel is 22,971 municipality-years: 1,209 Swiss municipalities observed from\n1991 to 2009. The outcome `nat_rate_ord` is the ordinary naturalization rate and\n`indirect` marks the switch from direct to indirect democracy, adopted at\ndifferent dates by different municipalities — staggered treatment timing.\n\n### TWFE\n\nFirst we do a TWFE model on it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(fixest)\nmodel_twfe <- feols(nat_rate_ord~indirect|bfs+year,\n                      data=hh2019, cluster = \"bfs\")\nsummary( model_twfe)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOLS estimation, Dep. Var.: nat_rate_ord\nObservations: 22,971\nFixed-effects: bfs: 1,209,  year: 19\nStandard-errors: Clustered (bfs) \n         Estimate Std. Error t value   Pr(>|t|)    \nindirect  1.33932   0.186525 7.18039 1.2117e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 4.09541     Adj. R2: 0.152719\n                Within R2: 0.005173\n```\n\n\n:::\n:::\n\n\nTWFE gives 1.33932 with a municipality-clustered standard error of 0.1865, close\nto the 1.22 the original authors report. Keep that number in view: everything\nbelow is an attempt to work out whether it can be trusted.\n\nTWFE has issues when there is staggered adoption and heterogeneous treatment effects.\n\n@goodman-bacon-2021 demonstrates that the two-way fixed-effects (TWFE) estimator in a staggered adoption setting can be represented as a weighted average of all possible 2x2 difference-in-differences (DID) estimates between different cohorts. However, when treatment effects change over time heterogeneously across cohorts, the “forbidden” comparisons that use post-treatment data from early adopters as controls for late adopters may introduce bias in the TWFE estimator. We employ the procedure outlined in @goodman-bacon-2021 and decompose the TWFE estimate using the command bacon in the bacondecomp package.\n\n\"Negative weights\" can be the other issue.  Basically it is a weighted average of comparison between different cohorts.  The weights can be negative in a TWFE model.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(bacondecomp)\ndf_bacon <- bacon(nat_rate_ord~indirect,\n                  data = hh2019,\n                  id_var = \"bfs\",\n                  time_var = \"year\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                      type  weight avg_est\n1 Earlier vs Later Treated 0.17605 1.97771\n2  Later vs Always Treated 0.31446 0.75233\n3 Later vs Earlier Treated 0.05170 0.32310\n4     Treated vs Untreated 0.45779 1.61180\n```\n\n\n:::\n\n```{.r .cell-code}\ncoef_bacon <- sum(df_bacon$estimate * df_bacon$weight)\ncoef_bacon\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.339325\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(df_bacon) +\n   aes(x = weight, y = estimate, shape = factor(type), color = factor(type)) +\n   labs(x = \"Weight\", y = \"Estimate\", shape = \"Type\", color = 'Type') +\n   geom_point()\n```\n\n::: {.cell-output-display}\n![](extended-twfe_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nThe decomposition sums to 1.339325, reproducing the TWFE estimate exactly. It\nsplits into four kinds of 2x2 comparison:\n\n| comparison | weight | average estimate |\n|---|---:|---:|\n| Treated vs Untreated | 0.458 | 1.612 |\n| Later vs Always Treated | 0.314 | 0.752 |\n| Earlier vs Later Treated | 0.176 | 1.978 |\n| Later vs Earlier Treated | 0.052 | 0.323 |\n\nThe clean comparisons — treated against never-treated — carry 46% of the weight\nand give 1.61. The forbidden ones, which use already-treated units as controls,\ncarry 0.314 + 0.052 = 37% and give much smaller numbers, 0.75 and 0.32. That is\nwhat pulls the TWFE estimate down from 1.61 to 1.34.\n\nThe problem shown in Bacon decomposition here is the comparison between \"Later\" and \"Earlier Treated\".  It's a \"forbidden\" comparison.\n\nTWFE with event history type of graph.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.use <- hh2019 |>\n  na.omit()\n\ndf <- as.data.frame(\n  hh2019 |>\n    group_by(bfs) |>\n    mutate(treatment_mean = mean(indirect,na.rm = TRUE))\n)\ndf.use <- df[which(df$treatment_mean<1),]\n\ndf.twfe <- as_tibble(get.cohort(df.use,D=\"indirect\",index=c(\"bfs\",\"year\"),start0 = TRUE))\n\n# time_to_treatment is NA when the unit is always treated, or never treated.  It needs to be set to an arbitrary value for the twfe model.\ndf.twfe$treat <- as.numeric(df.twfe$treatment_mean>0) # drop always treated units\ndf.twfe[which(is.na(df.twfe$Time_to_Treatment)),'Time_to_Treatment'] <- 0 # can be an arbitrary value\ntwfe.est <- feols(nat_rate_ord ~ i(Time_to_Treatment, treat, ref = -1)| bfs + year,\n                  data = df.twfe, cluster = \"bfs\")\nsummary(twfe.est)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOLS estimation, Dep. Var.: nat_rate_ord\nObservations: 17,594\nFixed-effects: bfs: 926,  year: 19\nStandard-errors: Clustered (bfs) \n                              Estimate Std. Error   t value   Pr(>|t|)    \nTime_to_Treatment::-18:treat -0.320651   0.632702 -0.506796 6.1242e-01    \nTime_to_Treatment::-17:treat -0.118540   0.391148 -0.303058 7.6191e-01    \nTime_to_Treatment::-16:treat -0.395632   0.402921 -0.981910 3.2640e-01    \nTime_to_Treatment::-15:treat -0.410976   0.343899 -1.195048 2.3237e-01    \nTime_to_Treatment::-14:treat  0.244512   0.369127  0.662406 5.0788e-01    \nTime_to_Treatment::-13:treat -0.044310   0.354017 -0.125164 9.0042e-01    \nTime_to_Treatment::-12:treat -0.545891   0.315172 -1.732042 8.3600e-02 .  \nTime_to_Treatment::-11:treat -0.293138   0.346835 -0.845180 3.9823e-01    \nTime_to_Treatment::-10:treat -0.423981   0.319375 -1.327534 1.8466e-01    \nTime_to_Treatment::-9:treat  -0.467114   0.301017 -1.551784 1.2106e-01    \nTime_to_Treatment::-8:treat  -0.115633   0.333659 -0.346561 7.2900e-01    \nTime_to_Treatment::-7:treat  -0.724290   0.305727 -2.369075 1.8037e-02 *  \nTime_to_Treatment::-6:treat  -0.572950   0.317153 -1.806540 7.1159e-02 .  \nTime_to_Treatment::-5:treat  -0.554993   0.309246 -1.794667 7.3033e-02 .  \nTime_to_Treatment::-4:treat   0.066209   0.345103  0.191853 8.4790e-01    \nTime_to_Treatment::-3:treat  -0.509530   0.316296 -1.610929 1.0754e-01    \nTime_to_Treatment::-2:treat  -0.195091   0.330220 -0.590793 5.5480e-01    \nTime_to_Treatment::0:treat    0.522715   0.359646  1.453415 1.4645e-01    \nTime_to_Treatment::1:treat    1.668834   0.367919  4.535879 6.4907e-06 ***\nTime_to_Treatment::2:treat    1.724230   0.471363  3.657968 2.6858e-04 ***\nTime_to_Treatment::3:treat    1.178336   0.400559  2.941732 3.3452e-03 ** \nTime_to_Treatment::4:treat    0.756323   0.478697  1.579962 1.1446e-01    \nTime_to_Treatment::5:treat    2.438229   0.705451  3.456269 5.7263e-04 ***\nTime_to_Treatment::6:treat    2.848590   0.805315  3.537238 4.2442e-04 ***\nTime_to_Treatment::7:treat    2.409359   0.783716  3.074275 2.1721e-03 ** \nTime_to_Treatment::8:treat    2.270428   0.797869  2.845617 4.5305e-03 ** \nTime_to_Treatment::9:treat    2.392678   0.863222  2.771799 5.6867e-03 ** \nTime_to_Treatment::10:treat   2.002836   0.953654  2.100170 3.5984e-02 *  \nTime_to_Treatment::11:treat   0.842590   0.560248  1.503961 1.3293e-01    \nTime_to_Treatment::12:treat   3.831918   2.300422  1.665745 9.6103e-02 .  \nTime_to_Treatment::13:treat   4.436437   2.322318  1.910349 5.6397e-02 .  \nTime_to_Treatment::14:treat   4.756977   3.485523  1.364781 1.7265e-01    \nTime_to_Treatment::15:treat   1.541967   1.415284  1.089511 2.7621e-01    \nTime_to_Treatment::16:treat   7.168943   4.844016  1.479959 1.3922e-01    \nTime_to_Treatment::17:treat   6.490854   2.726526  2.380632 1.7485e-02 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 4.42406     Adj. R2: 0.146601\n                Within R2: 0.012807\n```\n\n\n:::\n\n```{.r .cell-code}\ntwfe.output <- as.matrix(twfe.est$coeftable)\ntwfe.output <- as.data.frame(twfe.output)\ntwfe.output$Time <- c(c(-18:-2),c(0:17))+1\np.twfe <- esplot(twfe.output,Period = 'Time',Estimate = 'Estimate',\n                               SE = 'Std. Error', xlim = c(-12,10))\np.twfe\n```\n\n::: {.cell-output-display}\n![](extended-twfe_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n### Sun and Abraham\n\nThe @sun-abraham-2021 estimator is a weighted average of the average treatment effect (ATT) estimates for each cohort, obtained from a TWFE regression that includes cohort dummies fully interacted with indicators of relative time to the treatment’s onset. The iw estimator is robust to heterogeneous treatment effects (HTE) and can be implemented using the command sunab in the package fixest.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.sa <- df.twfe\ndf.sa[which(is.na(df.sa$FirstTreat)),\"FirstTreat\"] <- 1000 # replace NA with an arbitrary number\nmodel.sa.1 <- feols(nat_rate_ord~sunab(FirstTreat,year)|bfs+year,\n                    data = df.sa, cluster = \"bfs\")\nsummary(model.sa.1,agg = \"ATT\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOLS estimation, Dep. Var.: nat_rate_ord\nObservations: 17,594\nFixed-effects: bfs: 926,  year: 19\nStandard-errors: Clustered (bfs) \n    Estimate Std. Error t value   Pr(>|t|)    \nATT   1.3309   0.287971 4.62163 4.3474e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 4.34795     Adj. R2: 0.163888\n                Within R2: 0.046484\n```\n\n\n:::\n\n```{.r .cell-code}\nsa.output <- as.matrix(model.sa.1$coeftable)\nsa.output <- as.data.frame(sa.output)\nsa.output$Time <- c(c(-18:-2),c(0:17))+1\np.sa <- esplot(sa.output,Period = 'Time',Estimate = 'Estimate',\n                             SE = 'Std. Error', xlim = c(-12,10))\np.sa\n```\n\n::: {.cell-output-display}\n![](extended-twfe_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n## Callaway and Sant’Anna\n\n@callaway-santanna-2021 build the estimator from group-time average treatment effects $ATT(g,t)$ — the effect on cohort $g$ at time $t$ — each identified by comparing the treated cohort to a never-treated or not-yet-treated comparison group. The $ATT(g,t)$ are estimated by outcome regression, inverse-probability weighting, or a doubly-robust combination of the two, rather than from a single fully-interacted TWFE regression. These group-time effects are then aggregated with weights into summary parameters (overall, event-study, or by cohort). The estimator is robust to heterogeneous treatment effects (HTE) and can be implemented with the `att_gt` function in the `did` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(did)\ndf.cs <- df.twfe\ndf.cs[which(is.na(df.cs$FirstTreat)),\"FirstTreat\"] <- 0 # replace NA with 0\ncs.est.1 <- att_gt(yname = \"nat_rate_ord\",\n                 gname = \"FirstTreat\",\n                 idname = \"bfs\",\n                 tname = \"year\",\n                 xformla = ~1,\n                 control_group = \"nevertreated\",\n                 allow_unbalanced_panel = TRUE,\n                 data = df.cs,\n                 est_method = \"reg\")\ncs.est.att.1 <- aggte(cs.est.1, type = \"simple\", na.rm=T, bstrap = F)\nprint(cs.est.att.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\naggte(MP = cs.est.1, type = \"simple\", na.rm = T, bstrap = F)\n\nReference: Callaway, Brantly and Pedro H.C. Sant'Anna.  \"Difference-in-Differences with Multiple Time Periods.\" Journal of Econometrics, Vol. 225, No. 2, pp. 200-230, 2021. <https://doi.org/10.1016/j.jeconom.2020.12.001>, <https://arxiv.org/abs/1803.09015> \n\n    ATT    Std. Error     [ 95%  Conf. Int.]  \n 1.3309        0.3019     0.7392      1.9226 *\n\n\n---\nSignif. codes: `*' confidence band does not cover 0\n\nControl Group:  Never Treated,  Anticipation Periods:  0\nEstimation Method:  Outcome Regression\n```\n\n\n:::\n\n```{.r .cell-code}\ncs.att.1 <- aggte(cs.est.1, type = \"dynamic\",\n                  bstrap=FALSE, cband=FALSE, na.rm=T)\nprint(cs.att.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\naggte(MP = cs.est.1, type = \"dynamic\", na.rm = T, bstrap = FALSE, \n    cband = FALSE)\n\nReference: Callaway, Brantly and Pedro H.C. Sant'Anna.  \"Difference-in-Differences with Multiple Time Periods.\" Journal of Econometrics, Vol. 225, No. 2, pp. 200-230, 2021. <https://doi.org/10.1016/j.jeconom.2020.12.001>, <https://arxiv.org/abs/1803.09015> \n\n\nOverall summary of ATT's based on event-study/dynamic aggregation:  \n    ATT    Std. Error     [ 95%  Conf. Int.] \n 1.2205        0.6314    -0.0171       2.458 \n\n\nDynamic Effects:\n Event time Estimate Std. Error [95% Pointwise  Conf. Band]  \n        -17   0.1350     0.6467         -1.1324      1.4025  \n        -16  -0.0839     0.3583         -0.7861      0.6183  \n        -15   0.1467     0.3964         -0.6303      0.9236  \n        -14   0.7509     0.3219          0.1200      1.3818 *\n        -13  -0.2318     0.3392         -0.8967      0.4331  \n        -12  -0.5851     0.2814         -1.1367     -0.0335 *\n        -11   0.2656     0.2705         -0.2647      0.7958  \n        -10  -0.2386     0.2805         -0.7883      0.3111  \n         -9   0.0576     0.2702         -0.4721      0.5872  \n         -8   0.5244     0.3165         -0.0959      1.1448  \n         -7  -0.6282     0.3132         -1.2420     -0.0144 *\n         -6   0.1081     0.2565         -0.3946      0.6108  \n         -5   0.1623     0.2890         -0.4041      0.7287  \n         -4   0.6485     0.3380         -0.0139      1.3109  \n         -3  -0.6161     0.3674         -1.3362      0.1040  \n         -2   0.1505     0.3355         -0.5071      0.8081  \n         -1   0.0279     0.3425         -0.6435      0.6992  \n          0   0.7141     0.3754         -0.0217      1.4500  \n          1   1.5846     0.3681          0.8632      2.3060 *\n          2   1.6337     0.5118          0.6306      2.6369 *\n          3   0.9090     0.4396          0.0473      1.7707 *\n          4   0.4091     0.5725         -0.7130      1.5311  \n          5   2.1106     0.7976          0.5473      3.6739 *\n          6   2.4842     0.9078          0.7051      4.2634 *\n          7   2.3802     0.8538          0.7068      4.0535 *\n          8   2.5602     0.8723          0.8506      4.2699 *\n          9   2.0100     0.9769          0.0953      3.9246 *\n         10   1.6391     1.0257         -0.3712      3.6494  \n         11   0.0298     0.6100         -1.1658      1.2253  \n         12   0.6942     2.8043         -4.8021      6.1904  \n         13   1.1355     2.3284         -3.4281      5.6991  \n         14   1.3625     3.4131         -5.3270      8.0519  \n         15  -2.0699     1.7160         -5.4331      1.2933  \n         16   2.2743     3.6182         -4.8172      9.3658  \n         17   0.1072     4.5338         -8.7789      8.9934  \n---\nSignif. codes: `*' confidence band does not cover 0\n\nControl Group:  Never Treated,  Anticipation Periods:  0\nEstimation Method:  Outcome Regression\n```\n\n\n:::\n\n```{.r .cell-code}\ncs.output <- cbind.data.frame(Estimate = cs.att.1$att.egt,\n                              SE = cs.att.1$se.egt,\n                              time = cs.att.1$egt + 1)\np.cs.1 <- esplot(cs.output,Period = 'time',Estimate = 'Estimate',\n                               SE = 'SE', xlim = c(-12,10))\np.cs.1\n```\n\n::: {.cell-output-display}\n![](extended-twfe_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n### Imai, Kim, and Wang\n\nPanelMatch is an R package implementing a set of methodological tools proposed by @imai-2023 that enables researchers to apply matching methods for causal inference on time-series cross-sectional data with binary treatments. The package includes implementations of matching methods based on propensity scores and Mahalanobis distance, as well as weighting methods. PanelMatch enables users to easily calculate a variety of possible quantities of interest, along with standard errors. The software is flexible, allowing users to tune the matching, refinement, and estimation procedures with a large number of parameters. The package also offers a variety of visualization and diagnostic tools for researchers to better understand their data and assess their results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(PanelMatch)\ndf.pm <- as.data.frame(df.twfe)\n# we need to convert the unit and time indicator to integer\ndf.pm[,\"bfs\"] <- as.integer(as.factor(df.pm[,\"bfs\"]))\ndf.pm[,\"year\"] <- as.integer(as.factor(df.pm[,\"year\"]))\ndf.pm <- df.pm[,c(\"bfs\",\"year\",\"nat_rate_ord\",\"indirect\")]\n\n# Create PanelData object (new API)\npd <- PanelData(df.pm, unit.id = \"bfs\", time.id = \"year\",\n                treatment = \"indirect\", outcome = \"nat_rate_ord\")\n\nPM.results <- PanelMatch(lag=3,\n                         panel.data = pd,\n                         refinement.method = \"none\",\n                         qoi = \"att\",\n                         lead = c(0:3),\n                         match.missing = TRUE)\n\n## For pre-treatment dynamic effects\nPM.results.placebo <- PanelMatch(lag=3,\n                         panel.data = pd,\n                         refinement.method = \"none\",\n                         qoi = \"att\",\n                         lead = c(0:3),\n                         match.missing = TRUE,\n                         placebo.test = TRUE)\nPE.results.pool <- PanelEstimate(PM.results, panel.data = pd, pooled = TRUE)\nsummary(PE.results.pool)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     estimate std.error      2.5%    97.5%\n[1,] 1.177674 0.3598234 0.4583719 1.860345\n```\n\n\n:::\n\n```{.r .cell-code}\nPE.results <- PanelEstimate(PM.results, panel.data = pd)\nPE.results.placebo <- placebo_test(PM.results.placebo, panel.data = pd, plot = F)\nest_lead <- as.vector(estimates(PE.results))\nest_lag <- tryCatch(as.vector(estimates(PE.results.placebo)),\n                    error = function(e) as.vector(PE.results.placebo$estimates))\nsd_lead <- tryCatch(apply(PE.results$bootstrapped.estimates,2,sd),\n                    error = function(e) rep(NA, length(est_lead)))\nsd_lag <- tryCatch(apply(PE.results.placebo$bootstrapped.estimates,2,sd),\n                   error = function(e) rep(NA, length(est_lag)))\ncoef <- c(est_lag, 0, est_lead)\nsd <- c(sd_lag, 0, sd_lead)\npm.output <- cbind.data.frame(ATT=coef, se=sd, t=c(-2:4))\np.pm <- esplot(data = pm.output,Period = 't',\n               Estimate = 'ATT',SE = 'se')\np.pm\n```\n\n::: {.cell-output-display}\n![](extended-twfe_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n### Liu, Wang and Xu\n\n@liu-wang-xu-2024 proposes a method for estimating the fixed effect counterfactual model by utilizing the untreated observations. It is essentially an imputation method that uses the untreated observations to estimate the counterfactual outcome for the treated.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(fect)\nout.fect <- fect(nat_rate_ord~indirect, data = df,\n                 index = c(\"bfs\",\"year\"),\n                 method = 'fe', se = TRUE)\nprint(out.fect$est.avg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      ATT.avg      S.E. CI.lower CI.upper      p.value\n[1,] 1.506416 0.2106191 1.093611 1.919222 8.530954e-13\n```\n\n\n:::\n\n```{.r .cell-code}\nfect.output <- as.matrix(out.fect$est.att)\nprint(fect.output)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            ATT      S.E.     CI.lower     CI.upper      p.value count\n-17 -0.01985591 0.4491032 -0.900082078  0.860370266 9.647351e-01    89\n-16  0.07269638 0.2519489 -0.421114321  0.566507076 7.729363e-01   157\n-15 -0.21365489 0.2543314 -0.712135304  0.284825525 4.008720e-01   162\n-14 -0.13153052 0.1627563 -0.450526989  0.187465956 4.190077e-01   350\n-13  0.46902947 0.2097748  0.057878426  0.880180521 2.536020e-02   371\n-12  0.24357664 0.2057836 -0.159751838  0.646905124 2.365500e-01   398\n-11 -0.24399485 0.1252007 -0.489383736  0.001394045 5.131579e-02   417\n-10 -0.02765866 0.1970934 -0.413954660  0.358637340 8.883971e-01   434\n-9  -0.09347047 0.1473932 -0.382355767  0.195414826 5.259781e-01   451\n-8  -0.10638473 0.1666585 -0.433029345  0.220259893 5.232526e-01   464\n-7   0.17476094 0.1959632 -0.209319926  0.558841807 3.724976e-01   468\n-6  -0.40297604 0.1474356 -0.691944458 -0.114007618 6.271562e-03   503\n-5  -0.24326436 0.1775931 -0.591340481  0.104811769 1.707541e-01   503\n-4  -0.23687833 0.1757415 -0.581325263  0.107568594 1.776971e-01   503\n-3   0.44244127 0.2213612  0.008581219  0.876301319 4.563761e-02   503\n-2  -0.11927690 0.1910928 -0.493811891  0.255258090 5.325073e-01   508\n-1   0.17612194 0.1899592 -0.196191301  0.548435182 3.538453e-01   512\n0    0.22491529 0.1908263 -0.149097447  0.598928018 2.385421e-01   514\n1    0.83813813 0.2898745  0.269994504  1.406281759 3.835510e-03   514\n2    1.81274486 0.3470077  1.132622167  2.492867548 1.751632e-07   425\n3    1.91941052 0.4086825  1.118407563  2.720413475 2.645520e-06   357\n4    1.19567464 0.3126440  0.582903663  1.808445617 1.310928e-04   352\n5    0.93520961 0.4708519  0.012356869  1.858062352 4.701027e-02   164\n6    2.52517848 0.7086855  1.136180389  3.914176563 3.663806e-04   143\n7    2.84129736 0.8106705  1.252412342  4.430182385 4.568248e-04   116\n8    2.32288547 0.8120494  0.731297924  3.914473020 4.229436e-03    97\n9    2.19105962 0.8221269  0.579720419  3.802398812 7.696290e-03    80\n10   1.71382906 0.8728260  0.003121486  3.424536624 4.958343e-02    63\n11   1.07651548 1.0208231 -0.924261063  3.077292022 2.916283e-01    50\n12  -0.30828629 0.6262466 -1.535707088  0.919134500 6.225241e-01    46\n13   0.35079211 1.9827237 -3.535274907  4.236859129 8.595678e-01    11\n14   0.81696815 2.6221846 -4.322419305  5.956355604 7.553748e-01    11\n15   0.97427612 4.0605555 -6.984266437  8.932818685 8.103794e-01    11\n16  -2.49173503 1.7791602 -5.978825034  0.995354965 1.613601e-01    11\n17   1.42334105 5.4796810 -9.316636275 12.163318381 7.950575e-01     6\n18  -0.01384226 4.9696696 -9.754215737  9.726531213 9.977776e-01     2\n```\n\n\n:::\n\n```{.r .cell-code}\nfect.output <- as.data.frame(fect.output)\nfect.output$Time <- c(-17:18)\np.fect <- esplot(fect.output,Period = 'Time',Estimate = 'ATT',\n                   SE = 'S.E.',CI.lower = \"CI.lower\",\n                   CI.upper = 'CI.upper',xlim = c(-12,10))\np.fect\n```\n\n::: {.cell-output-display}\n![](extended-twfe_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n@borusyak-jaravel-spiess-2024 with package didimputation almost gives the same result as @liu-wang-xu-2024.\n\n\n### Wooldridge\n\nWooldridge 2021, also called extended TWFE (ETWFE), is to allow more flexibility to make TWFE work properly.  The problem with TWFE is that we do not specify it flexibly enough.  If we allow heterogeneous treatment effect, then we cannot expect the canonical TWFE to work properly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.wool <- df.twfe\ndf.wool[which(is.na(df.wool$FirstTreat)),\"FirstTreat\"] <- 0 # replace NA with 0\n\nlibrary(etwfe)\n\nmodel.wool = etwfe(\n  fml  = nat_rate_ord ~ 1, # outcome ~ controls\n  tvar = year,        # time variable\n  gvar = FirstTreat, # group variable\n  data = df.wool,       # dataset\n  vcov = ~bfs,  # vcov adjustment (here: clustered)\n  cgroup = \"never\"\n)\nmodel.wool\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOLS estimation, Dep. Var.: nat_rate_ord\nObservations: 17,594\nFixed-effects: FirstTreat: 16,  year: 19\nStandard-errors: Clustered (bfs) \n                                    Estimate Std. Error  t value Pr(>|t|)    \n.Dtreat:FirstTreat::1992:year::1992  2.18863    1.36923  1.59844 0.110287    \n.Dtreat:FirstTreat::1992:year::1993 -4.18925    3.10938 -1.34730 0.178214    \n.Dtreat:FirstTreat::1992:year::1994 -2.50997    1.63352 -1.53654 0.124747    \n.Dtreat:FirstTreat::1992:year::1995 -5.23221    3.11282 -1.68086 0.093129 .  \n.Dtreat:FirstTreat::1992:year::1996 -5.42014    3.11207 -1.74165 0.081902 .  \n.Dtreat:FirstTreat::1992:year::1997 -5.15575    3.11248 -1.65648 0.097965 .  \n.Dtreat:FirstTreat::1992:year::1998 -5.08210    3.11345 -1.63231 0.102955    \n.Dtreat:FirstTreat::1992:year::1999 -5.13290    3.11447 -1.64808 0.099676 .  \n... 262 coefficients remaining (display them with summary() or use\nargument n)\n... 15 variables were removed because of collinearity\n(.Dtreat:FirstTreat::1992:year::1991,\n.Dtreat:FirstTreat::1993:year::1992 and 13 others [full set in\n$collin.var])\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 4.6642     Adj. R2: 0.088474\n               Within R2: 0.040642\n```\n\n\n:::\n\n```{.r .cell-code}\nemfx(model.wool)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n .Dtreat Estimate Std. Error    z Pr(>|z|)    S 2.5 % 97.5 %\n    TRUE     1.33      0.288 4.62   <0.001 18.0 0.766    1.9\n\nTerm: .Dtreat\nType: response\nComparison: TRUE - FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\nmod_es = emfx(model.wool, type = \"event\", post_only=FALSE)\nmod_es\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n event Estimate Std. Error       z Pr(>|z|)   S  2.5 % 97.5 %\n   -18   -0.266      0.789 -0.3371    0.736 0.4 -1.812  1.280\n   -17    0.178      0.503  0.3538    0.723 0.5 -0.808  1.164\n   -16    0.114      0.519  0.2198    0.826 0.3 -0.903  1.131\n   -15   -0.104      0.408 -0.2550    0.799 0.3 -0.903  0.695\n   -14    0.410      0.413  0.9927    0.321 1.6 -0.400  1.220\n--- 26 rows omitted. See ?print.marginaleffects ---\n    13    1.135      1.998  0.5683    0.570 0.8 -2.781  5.052\n    14    1.362      3.129  0.4355    0.663 0.6 -4.770  7.495\n    15   -2.070      1.439 -1.4387    0.150 2.7 -4.890  0.750\n    16    2.274      3.080  0.7385    0.460 1.1 -3.762  8.311\n    17    0.107      4.576  0.0234    0.981 0.0 -8.861  9.076\nTerm: .Dtreat\nType: response\nComparison: TRUE - FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\nwool.output <- mod_es |>\n  filter(event != -1) |>\n  mutate(Time = event + 1) |>\n  as.data.frame()\n\np.wool <- esplot(wool.output,Period = 'Time',Estimate = 'estimate',\n                 SE = 'std.error', xlim = c(-12,10))\np.wool\n```\n\n::: {.cell-output-display}\n![](extended-twfe_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nNote that in order to get pre-event estimates, we need to set \"cgroup=never\" in the etwfe function.  Otherwise, ETWFE will only give us post-event estimates. Under the default setting, the control group comprises the “not-yet” treated units, therefore all pre-treatment effects are mechanistically set to zero.  By setting \"cgroup=never\", we only use never treated units as the control group.  This way we can get pre-treatment estimates, but we are not using all available information for the control group, therefore the estimates may not be as efficient as the default setting.  That cost is visible in the two runs below: the never-treated version gives an ATT of 1.33 with a standard error of 0.288, while the default not-yet-treated version gives 1.51 with a standard error of 0.188 --- a little over a third narrower.\n\nAlso we don't have control variable here.  If we have, it is very easy to incorporate into ETWFE.  Wooldridge used the Mundlak device to incorporate control variables, which is a very simple and intuitive way to do it.\n\nIf we do the default setting and plot only post-event estimates:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel.wool2 = etwfe(\n  fml  = nat_rate_ord ~ 1, # outcome ~ controls\n  tvar = year,        # time variable\n  gvar = FirstTreat, # group variable\n  data = df.wool,       # dataset\n  vcov = ~bfs  # vcov adjustment (here: clustered)\n)\nmodel.wool2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOLS estimation, Dep. Var.: nat_rate_ord\nObservations: 17,594\nFixed-effects: FirstTreat: 16,  year: 19\nStandard-errors: Clustered (bfs) \n                                    Estimate Std. Error  t value Pr(>|t|)    \n.Dtreat:FirstTreat::1992:year::1992  1.99670    1.35883  1.46943 0.142057    \n.Dtreat:FirstTreat::1992:year::1993 -4.52291    3.09436 -1.46166 0.144174    \n.Dtreat:FirstTreat::1992:year::1994 -2.62350    1.61688 -1.62257 0.105022    \n.Dtreat:FirstTreat::1992:year::1995 -5.17241    3.09454 -1.67146 0.094969 .  \n.Dtreat:FirstTreat::1992:year::1996 -5.08905    3.09404 -1.64479 0.100353    \n.Dtreat:FirstTreat::1992:year::1997 -5.17232    3.09482 -1.67128 0.095004 .  \n.Dtreat:FirstTreat::1992:year::1998 -5.39134    3.09606 -1.74135 0.081954 .  \n.Dtreat:FirstTreat::1992:year::1999 -5.09733    3.09495 -1.64698 0.099901 .  \n... 121 coefficients remaining (display them with summary() or use\nargument n)\n... 141 variables were removed because of collinearity\n(.Dtreat:FirstTreat::1993:year::1992,\n.Dtreat:FirstTreat::1994:year::1992 and 139 others [full set in\n$collin.var])\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 4.6999     Adj. R2: 0.081954\n               Within R2: 0.0259  \n```\n\n\n:::\n\n```{.r .cell-code}\nemfx(model.wool2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n .Dtreat Estimate Std. Error    z Pr(>|z|)    S 2.5 % 97.5 %\n    TRUE     1.51      0.188 8.02   <0.001 49.7  1.14   1.87\n\nTerm: .Dtreat\nType: response\nComparison: TRUE - FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\nmod_es2 = emfx(model.wool2, type = \"event\")\nmod_es2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n event Estimate Std. Error        z Pr(>|z|)    S  2.5 % 97.5 %\n     0   0.8381      0.288  2.90643  0.00366  8.1  0.273  1.403\n     1   1.8127      0.316  5.74107  < 0.001 26.7  1.194  2.432\n     2   1.9194      0.399  4.81257  < 0.001 19.4  1.138  2.701\n     3   1.1957      0.320  3.73394  < 0.001 12.4  0.568  1.823\n     4   0.9352      0.423  2.20947  0.02714  5.2  0.106  1.765\n     5   2.5252      0.641  3.93965  < 0.001 13.6  1.269  3.781\n     6   2.8413      0.738  3.84931  < 0.001 13.0  1.395  4.288\n     7   2.3229      0.710  3.27278  0.00106  9.9  0.932  3.714\n     8   2.1911      0.751  2.91737  0.00353  8.1  0.719  3.663\n     9   1.7138      0.795  2.15674  0.03103  5.0  0.156  3.271\n    10   1.0765      0.941  1.14366  0.25277  2.0 -0.768  2.921\n    11  -0.3083      0.498 -0.61885  0.53602  0.9 -1.285  0.668\n    12   0.3508      1.892  0.18538  0.85293  0.2 -3.358  4.060\n    13   0.8170      2.012  0.40611  0.68466  0.5 -3.126  4.760\n    14   0.9743      3.351  0.29076  0.77123  0.4 -5.593  7.542\n    15  -2.4917      1.413 -1.76355  0.07781  3.7 -5.261  0.278\n    16   1.4233      4.430  0.32126  0.74801  0.4 -7.260 10.107\n    17  -0.0138      4.556 -0.00304  0.99758  0.0 -8.944  8.916\n\nTerm: .Dtreat\nType: response\nComparison: TRUE - FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\nwool.output2 <- mod_es2 |>\n  filter(event != -1) |>\n  mutate(Time = event + 1) |>\n  as.data.frame()\n\np.wool2 <- esplot(wool.output2, Period = 'Time',Estimate = 'estimate',\n                 SE = 'std.error', xlim = c(0,10))\np.wool2\n```\n\n::: {.cell-output-display}\n![](extended-twfe_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n## Comparing the estimators\n\nIt is worth collecting what all of these produced on the same data:\n\n| estimator | ATT | s.e. |\n|---|---:|---:|\n| TWFE | 1.339 | 0.187 |\n| Sun and Abraham | 1.331 | 0.288 |\n| Callaway and Sant'Anna (simple) | 1.331 | 0.302 |\n| Callaway and Sant'Anna (dynamic) | 1.221 | 0.631 |\n| Imai, Kim and Wang | 1.178 | 0.335 |\n| Liu, Wang and Xu | 1.506 | 0.204 |\n| Wooldridge ETWFE | 1.330 | 0.288 |\n\nThree things stand out. Sun-Abraham, Callaway-Sant'Anna and ETWFE agree to three\ndigits at 1.33 — they are different routes to the same never-treated-control\nestimand, and they land on the same number. The spread across all seven, 1.18 to\n1.51, is smaller than the standard errors, so on this data the estimator choice\ndoes not change the conclusion.\n\nAnd TWFE at 1.339 is not far off any of them, despite the forbidden comparisons\nthe Bacon decomposition exposed. That is worth saying plainly: the decomposition\nshows TWFE *is* contaminated here, but the contamination happens to be small\nenough that the answer survives. It would not have to be.\n\n## Staggered DiD with treatment reversal\n\nWith treatment reversal (ie., the treated units go back to control), Wooldridge's method still works.  However, I don't think package \"etwfe\" has it implemented.\n\nSo far, packages \"fect\", \"PanelMatch\" can handle treatment reversal.\n\nWe can probably manually do ETWFE with treatment reversal.  See Wooldridge's dropbox for the code in Stata.  The basic idea is to treat cohorts as different treatment beginning time and exit time combinations.  Then do the same regression with interactions of cohort dummies with the time dummies.  It is very flexible.  The tricky part is to get the marginal effect and its standard error right.\n\n## Summary\n\nWith staggered adoption and effects that vary across cohorts, a single TWFE coefficient mixes clean comparisons with forbidden ones that use already-treated units as controls. The Goodman-Bacon decomposition shows the mix. Sun-Abraham, Callaway-Sant'Anna, imputation (Borusyak et al., Liu-Wang-Xu), PanelMatch and Wooldridge's ETWFE all avoid the forbidden comparisons in different ways. ETWFE is the simplest: a TWFE regression flexible enough to give each cohort its own effect in each period.\n\nOn the Swiss naturalization data, TWFE gives 1.339. The decomposition shows 37% of the weight on forbidden comparisons, which pull the estimate down from the clean comparisons' 1.61. Sun-Abraham, Callaway-Sant'Anna and ETWFE agree at 1.33, and all seven estimators fall between 1.18 and 1.51, within their standard errors. So here the contamination is real but small. Treatment reversal needs `fect` or PanelMatch, or ETWFE built by hand with exit cohorts.\n\n---\n\n<!-- see-also-footer -->\n*Systematic treatment: [R](https://xiangao.github.io/causal_econometrics_guide/did.html) · [Julia](https://xiangao.github.io/causal_econometrics_julia/did.html).*\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}