{
  "hash": "a078041375c90bb38492b70baab1b2a3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Matching and Weighting - Part 2: weighting\"\ndate: \"2025-05-31\"\n---\n\n\nThis chapter follows R's `WeightIt` package (Greifer et al.). The assumptions — SUTVA, ignorability, and overlap — are the same as in the [matching chapter](matching-part1.qmd).\n\n## Weighting methods\n\nWeighting creates a pseudo-population in which $X$ is balanced across treatment and control. The most common approach is inverse probability of treatment weighting (IPTW), which uses the propensity score. Several alternatives are gaining traction.\n\n### Inverse probability of treatment weighting (IPTW)\n\nIPTW is the most common weighting method.  It uses the inverse of the propensity score as weights.  For the **ATE**, weight each treated unit by $1/p$ and each control unit by $1/(1-p)$, where $p$ is the propensity score.  For the **ATT** --- which is what the examples below request via `estimand = \"ATT\"` --- the treated units all get weight $1$ and the controls get $p/(1-p)$; you can see this in the weight summaries, where the treated range is exactly $1$ to $1$.  Either way the point is the same: create a pseudo population in which the distribution of $X$ is balanced between the groups.\n\n### Covariate balancing propensity score (CBPS)\n\nThe same idea, but with a different way to estimate the propensity score.  CBPS is a form of logistic regression where balance constraints are incorporated to a generalized method of moments estimation of the model coefficients.\n\n### Entropy balancing\n\nEntropy balancing involves the specification of an optimization problem, the solution to which is then used to compute the weights. The constraints of the primal optimization problem correspond to covariate balance on the means (for binary and multi-category treatments) or treatment-covariate covariances (for continuous treatments), positivity of the weights, and that the weights sum to a certain value.  Entropy balancing is doubly robust (for the ATT) in the sense that it is consistent either when the true propensity score model is a logistic regression of the treatment on the covariates or when the true outcome model for the control units is a linear regression of the outcome on the covariates, and it attains a semi-parametric efficiency bound when both are true. Entropy balancing will always yield exact mean balance on the included terms (not necessarily on the distribution of the covariates).\n\n### Energy balancing\n\nEnergy balancing is a method of estimating weights using optimization without a propensity score.\n\nThe primary benefit of energy balancing is that all features of the covariate distribution are balanced, not just means, as with other optimization-based methods like entropy balancing.\n\n### SuperLearner\n\nSuperLearner works by fitting several machine learning models to the treatment and covariates and then taking a weighted combination of the generated predicted values to use as the propensity scores, which are then used to construct weights.\n\n\n## Example\n\nHere is an example with Lalonde data, we are interested in the effect of treatment on \"re78\" (real earnings 1978).\n\n### IPW\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"WeightIt\")\nlibrary(cobalt)\ndata(lalonde)\nw.out1 <- weightit(treat ~ age + educ + race + married + nodegree + re74 + re75,\n                  data = lalonde, estimand = \"ATT\", method = \"glm\")\nw.out1 #print the output\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nA weightit object\n - method: \"glm\" (propensity score weighting with GLM)\n - number of obs.: 614\n - sampling weights: none\n - treatment: 2-category\n - estimand: ATT (focal: 1)\n - covariates: age, educ, race, married, nodegree, re74, re75\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(w.out1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  Summary of weights\n\n- Weight ranges:\n\n          Min                                 Max\ntreated 1.            ||                    1.   \ncontrol 0.009 |---------------------------| 3.743\n\n- Units with the 5 most extreme weights by group:\n                                    \n            5     4    3     2     1\n treated    1     1    1     1     1\n          597   573  381   411   303\n control 3.03 3.059 3.24 3.523 3.743\n\n- Weight statistics:\n\n        Coef of Var   MAD Entropy # Zeros\ntreated       0.    0.      0.          0\ncontrol       1.818 1.289   1.098       0\n\n- Effective Sample Sizes:\n\n           Control Treated\nUnweighted  429.       185\nWeighted     99.82     185\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(cobalt)\nbal.tab(w.out1, stats = c(\"m\", \"v\"), thresholds = c(m = .05))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBalance Measures\n                Type Diff.Adj         M.Threshold V.Ratio.Adj\nprop.score  Distance  -0.0205     Balanced, <0.05      1.0324\nage          Contin.   0.1188 Not Balanced, >0.05      0.4578\neduc         Contin.  -0.0284     Balanced, <0.05      0.6636\nrace_black    Binary  -0.0022     Balanced, <0.05           .\nrace_hispan   Binary   0.0002     Balanced, <0.05           .\nrace_white    Binary   0.0021     Balanced, <0.05           .\nmarried       Binary   0.0186     Balanced, <0.05           .\nnodegree      Binary   0.0184     Balanced, <0.05           .\nre74         Contin.  -0.0021     Balanced, <0.05      1.3206\nre75         Contin.   0.0110     Balanced, <0.05      1.3938\n\nBalance tally for mean differences\n                    count\nBalanced, <0.05         9\nNot Balanced, >0.05     1\n\nVariable with the greatest mean difference\n Variable Diff.Adj         M.Threshold\n      age   0.1188 Not Balanced, >0.05\n\nEffective sample sizes\n           Control Treated\nUnadjusted  429.       185\nAdjusted     99.82     185\n```\n\n\n:::\n:::\n\n\n### entropy balancing\n\n\n::: {.cell}\n\n```{.r .cell-code}\nw.out2 <- weightit(treat ~ age + educ + race + married + nodegree + re74 + re75,\n                  data = lalonde, estimand = \"ATT\", method = \"ebal\")\nsummary(w.out2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  Summary of weights\n\n- Weight ranges:\n\n          Min                                 Max\ntreated 1.           ||                     1.   \ncontrol 0.008 |---------------------------| 4.062\n\n- Units with the 5 most extreme weights by group:\n                                     \n             5     4    3     2     1\n treated     1     1    1     1     1\n           608   381  597   303   411\n control 3.073 3.235 3.45 3.897 4.062\n\n- Weight statistics:\n\n        Coef of Var   MAD Entropy # Zeros\ntreated       0.    0.      0.          0\ncontrol       1.834 1.287   1.101       0\n\n- Effective Sample Sizes:\n\n           Control Treated\nUnweighted  429.       185\nWeighted     98.46     185\n```\n\n\n:::\n\n```{.r .cell-code}\nbal.tab(w.out2, stats = c(\"m\", \"v\"), thresholds = c(m = .05))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBalance Measures\n               Type Diff.Adj     M.Threshold V.Ratio.Adj\nage         Contin.       -0 Balanced, <0.05      0.4096\neduc        Contin.       -0 Balanced, <0.05      0.6635\nrace_black   Binary        0 Balanced, <0.05           .\nrace_hispan  Binary        0 Balanced, <0.05           .\nrace_white   Binary       -0 Balanced, <0.05           .\nmarried      Binary       -0 Balanced, <0.05           .\nnodegree     Binary        0 Balanced, <0.05           .\nre74        Contin.       -0 Balanced, <0.05      1.3265\nre75        Contin.       -0 Balanced, <0.05      1.3351\n\nBalance tally for mean differences\n                    count\nBalanced, <0.05         9\nNot Balanced, >0.05     0\n\nVariable with the greatest mean difference\n Variable Diff.Adj     M.Threshold\n     re74       -0 Balanced, <0.05\n\nEffective sample sizes\n           Control Treated\nUnadjusted  429.       185\nAdjusted     98.46     185\n```\n\n\n:::\n:::\n\nSuppose we are satisfied with the balance, we can use the weights to estimate the treatment effect.  We can use the \"marginaleffects\" package to do that.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit outcome model\nfit <- lm_weightit(re78 ~ treat * (age + educ + race + married +\n                                     nodegree + re74 + re75),\n                   data = lalonde, weightit = w.out2)\n# G-computation for the treatment effect\nlibrary(\"marginaleffects\")\navg_comparisons(fit, variables = \"treat\",\n                newdata = subset(lalonde, treat == 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Estimate Std. Error    z Pr(>|z|)   S 2.5 % 97.5 %\n     1273        770 1.65   0.0983 3.3  -236   2783\n\nTerm: treat\nType: probs\nComparison: 1 - 0\n```\n\n\n:::\n:::\n\n\n### energy balancing\n\n\n::: {.cell}\n\n```{.r .cell-code}\nw.out3 <- tryCatch(\n  weightit(treat ~ age + educ + race + married +\n                  nodegree + re74 + re75, data = lalonde,\n                method = \"energy\", estimand = \"ATE\"),\n  error = function(e) { message(\"Energy balancing failed: \", e$message); NULL }\n)\nif (!is.null(w.out3)) summary(w.out3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  Summary of weights\n\n- Weight ranges:\n\n        Min                                  Max\ntreated   0 |---------------------------| 14.041\ncontrol   0 |---------------------|       11.065\n\n- Units with the 5 most extreme weights by group:\n                                        \n            10   179   125    137    124\n treated 5.984  6.23 6.758 13.202 14.041\n           537   553   573    420    608\n control 5.499 6.404 6.599  8.274 11.065\n\n- Weight statistics:\n\n        Coef of Var   MAD Entropy # Zeros\ntreated       1.821 1.054   0.92        0\ncontrol       1.264 0.866   0.579       0\n\n- Effective Sample Sizes:\n\n           Control Treated\nUnweighted  429.    185.  \nWeighted    165.42   43.04\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(w.out3)) {\n  fit <- lm_weightit(re78 ~ treat * (age + educ + race + married +\n                                       nodegree + re74 + re75),\n                     data = lalonde, weightit = w.out3)\n  # G-computation for the treatment effect\n  avg_comparisons(fit, variables = \"treat\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Estimate Std. Error       z Pr(>|z|)   S 2.5 % 97.5 %\n      -73       1085 -0.0672    0.946 0.1 -2200   2054\n\nTerm: treat\nType: probs\nComparison: 1 - 0\n```\n\n\n:::\n:::\n\n\nTwo things are worth noticing in that output rather than passing over it. First,\nthe estimand changed: `w.out3` requests the **ATE**, while the entropy-balancing\nfit above targeted the **ATT**, so the two numbers ($-73$ against $1273$) are not\ncompeting estimates of the same quantity. Second, look at the weight summary.\nEntropy balancing gives every treated unit a weight of exactly $1$, as the ATT\nrequires. Energy balancing spreads the treated weights from $0$ to $14.0$ --- one\ntreated unit is effectively discarded and another counts as fourteen --- and the\nresulting standard error ($1085$) is much larger than entropy balancing's ($770$).\nBalancing the whole covariate *distribution* rather than just its means is a\ngenuine advantage, but it is bought with weight variability, and that shows up\ndirectly in the precision of the estimate.\n\n## comparing matching and weighting\n\nMatching and weighting are popular in different fields.  We used to say matching involves discarding data therefore changing the estimand, but now with full matching and other methods, matching can be done without losing data.  We used to believe weighting can be unstable, as weights can be highly variable, but with CBPS, entropy balancing and energy balancing, weighting can perform much better.\n\nSo, in practice, we can try different methods, either matching or weighting, and see which one gives us better balance. Then use \"marginaleffects\" to get the treatment effect.\n\n---\n\n<!-- see-also-footer -->\n*Systematic treatment: [R](https://xiangao.github.io/causal_econometrics_guide/matching.html) · [Julia](https://xiangao.github.io/causal_econometrics_julia/matching.html).*\n",
    "supporting": [
      "weighting-part2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}