{
  "hash": "2abb49ad3bfe55c744661acd7870a131",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"G-computation (g-formula) with time varying covariates\"\ndate: \"2024-04-20\"\n---\n\n\n## The problem\n\nThe g-formula (g-computation algorithm) is a method to estimate the causal effect of a time varying treatment or covariates, developed by Robins (1986). Note this is distinct from **g-estimation** of structural nested models (Robins and Rotnitzky, 1992), a different g-methods estimator that uses instrumental-variable-like estimating equations and does not require modeling the joint distribution of all time-varying confounders. This chapter — and the `gfoRmula`/`gmethods` packages used below — implements the g-formula, not g-estimation.\n\nWe can imagine such a scenario.  Suppose $A0$ and $A1$ are time 0 and time 1 treatment, can be binary or continuous.  $L1$ is a time 1 covariate.  It can be some intermediate outcome.  Say HbA1c.  HbA1c can be a result of treatment $A0$.  Then it can be a cause for the next period treatment $A1$.   $Y$ is the outcome.  $U$ is the unmeasured confounder.  The causal diagram is shown below.  How do we estimate the effect of treatment?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dagitty)\nlibrary(ggdag)\nlibrary(ggplot2)\nlibrary(gfoRmula)\nlibrary(gmethods)\nlibrary(tidyverse)\n\ndag <- dagify(\n  Y ~ A1 + A0 + L1 ,\n  A1 ~ A0 + L1,\n  L1 ~ A0 ,\n  coords = time_ordered_coords()\n)\n\ndag %>%\n  ggplot(aes(x = x, y = y, xend = xend, yend = yend)) +\n  geom_dag_point() +\n  geom_dag_edges_arc() +\n  geom_dag_text() +\n  theme_dag()\n```\n\n::: {.cell-output-display}\n![](g-estimation_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n## Assumptions\n\nThere are four potential outcomes, with $A_0$ and $A_1$ can be 0 or 1.  The causal estimand is\n$$ \\tau_{a_0,a_1,a_0',a_1'} = E[Y^{a_0,a_1} - Y^{a_0',a_1'}]$$ {#eq-g-estimation-1}\n\n\nTo identify the effects, we need assumptions.\n\n1.  Sequential ignorability\n$$ Y^{a_0,a_1} \\perp A_0$$ {#eq-g-estimation-2}\n$$ Y^{a_0,a_1} \\perp A_1^{a_0} | A_0, L_1^{a_0}$$ {#eq-g-estimation-3}\n\nIn general, treatment at time $t$ is randomized with probabilities depending on the observed past (covariates and intermediate outcomes): at any time $t$, for every regime $\\bar a$,\n$$ Y^{\\bar a} \\perp A_t \\mid H_t $$ {#eq-g-estimation-4}\nwhere $H_t$ is the **observed** history of treatment and covariates up to time $t$,\n$$H_t=(A_0,  A_1, ..., A_{t-1}; L_1,..., L_{t}).$$ {#eq-g-estimation-5}\nRead this in terms of the *observed* treatment $A_t$ and the *observed* history $H_t$: conditional on what has actually happened up to time $t$, the next treatment is independent of the future potential outcome. The superscripted objects in the two-period statement above (e.g. $A_1^{a_0}$, $L_1^{a_0}$) denote the values that would arise under setting $A_0=a_0$; by consistency these equal the observed $A_1$, $L_1$ on the subset of units with $A_0=a_0$, which is what lets the conditional-independence statement be checked on observed data.\n\n2.  Positivity\n\n$$ 0 < P(A_0=1) < 1$$ {#eq-g-estimation-6}\n$$ 0 < P(A_1=1|A_0=1, L_1) < 1$$ {#eq-g-estimation-7}\n\nIn general,\n$$ 0 < P(A_t=1|H_t) < 1$$ {#eq-g-estimation-8}\n\n3. Consistency\n\n$$ Y^{a_0,a_1} = Y | (A_0=a_0,A_1=a_1)$$ {#eq-g-estimation-9}\n\n## Identifiability\n\n $$\n\\begin{aligned}\nE[Y^{a_0,a_1}] &= E[Y^{a_0,a_1} | A_0=a_0] \\\\\n&= E[Y^{A_0,a_1} | A_0=a_0] \\\\\n&= \\sum_{l=0,1}E[Y^{A_0,a_1} | A_0=a_0, L=l] P(L=l | A_0=a_0) \\\\\n&= \\sum_{l=0,1}E[Y^{A_0,a_1} | A_0=a_0, L=l, A_1=a_1] P(L=l | A_0=a_0) \\\\\n&= \\sum_{l=0,1}E[Y^{A_0,A_1} | A_0=a_0, L=l, A_1=a_1] P(L=l | A_0=a_0)\n\\end{aligned}\n$$ {#eq-g-estimation-10} \n\nThis can be expanded to the general case.  Basically start from the first period, then the second, based on the first, and so on.\n\n## Estimation\n\nThere are two types of components in the g-estimation.  The first is the outcome model, then there are models for time-varying covariates, or intermediate outcomes (confounders).\n\n## Parametric g-formula\n\nIn this simple case, if $Y$ is continuous, we can use a linear model.  If $Y$ is binary, we can use a logistic model.\n\n$$ E[Y | A_0, A_1, L_1] = \\beta_0 + \\beta_1 A_0 + \\beta_2 L_1 + \\beta_3 A_1$$ {#eq-g-estimation-11}\n\nSuppose $L_1$ is binary,\n\n$$P(L_1=1 | A_0) = logit^{-1}(\\gamma_0 + \\gamma_1 A_0)$$ {#eq-g-estimation-12}\n$$ L_1 | A_0 \\sim Bernoulli\\big(logit^{-1}(\\gamma_0 + \\gamma_1 A_0)\\big)$$ {#eq-g-estimation-13}\n\nWe may need to simulate the distribution of the time-varying covariates for the expected value of the potential outcomes.\n\n## an example\n\n\nI am following Christopher Boyer's example in his teaching page: https://christopherbboyer.com/about.\n\nThe first example is from his lab3 teaching page.\n\nFirst we set up a simulated data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# setting up the data -----------------------------------------------------\n\n# The code below creates the frequency table, and then turns it into long format\n# data. Read through the code carefully and run it.\n\n# re-create the frequency table for homework 3\nhw3_freq <- tribble(\n  ~A_0, ~L_1, ~A_1, ~N, ~Y_1,\n  0, 0, 0, 6000, 60,\n  0, 0, 1, 2000, 60,\n  0, 1, 0, 2000, 210,\n  0, 1, 1, 6000, 210,\n  1, 0, 0, 3000, 240,\n  1, 0, 1, 1000, 240,\n  1, 1, 0, 3000, 120,\n  1, 1, 1, 9000, 120\n)\n\n# expand the frequency table to 1 row per person\n# (first just assign everyone the average Y value)\ndat <- uncount(hw3_freq, N) %>%\n  # give those rows an id number\n  rowid_to_column(var = \"id\") %>%\n  # for each of the variables except for id, split it into two\n  # rows, one for each time point\n  pivot_longer(-id,\n               names_to = c(\".value\", \"time\"),\n               names_sep = \"_\"\n  ) %>%\n  # make sure that time is read as a number\n  mutate(time = parse_number(time),\n         # add some random error to Y\n         # (nrow(.) means a different value for each row of the dataset in use\n         Y = Y + rnorm(nrow(.), 0, 10))\n\n\n# create lagged variables\n# group_by(id) makes this robust to row order -- lag() would otherwise\n# silently lag across a different person's rows if dat were ever re-sorted\n# (e.g. by time first). Currently harmless here since dat is in id-major\n# order with exactly one row per id per time, but safer to be explicit.\nt1 <- dat %>%\n  group_by(id) %>%\n  mutate(lag_A = lag(A)) %>%\n  ungroup() %>%\n  filter(time == 1)\n```\n:::\n\n\nThen calculate the g-formula by hand.\n\nThe recipe is the same in both cases: fit a model for the time-1 covariate $L$\ngiven past treatment, fit a model for $Y$ given treatment, past treatment and\n$L$, then simulate 10,000 people forward with the treatments *fixed* at the\nregime's values, drawing $L$ from its fitted conditional distribution rather\nthan conditioning on the observed one.\n\nFirst for $E[Y^{1,1}]$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# fit models for covariate and outcome given past on t1\nL_mod <- glm(L ~ lag_A, data = t1, family = binomial())\nY_mod <- glm(Y ~ A * lag_A * L, data = t1)\n\n# create new data set with space for 10,000 simulated entries\nnsim <- 10000\nbaseline_pop <- tibble(id = 1:nsim)\n\n# fix intervention values in the new data set to be consistent with the regime\nnew_dat_11 <- baseline_pop %>%\n  mutate(lag_A = 1, A = 1)\n\n# predict covariate means at time 1\nnew_dat_11$pL <- predict(L_mod, newdata = new_dat_11, type = \"response\")\n\n# simulate covariate values at time 1\nnew_dat_11$L <- rbinom(nsim, 1, new_dat_11$pL)\n\n# predict outcome at time 1 based on simulated covariates and fixed treatments\nnew_dat_11$Ey <- predict(Y_mod, newdata = new_dat_11, type = \"response\")\n\n# take mean across all simulations to get g-formula estimate!\nmean(new_dat_11$Ey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 150.1166\n```\n\n\n:::\n:::\n\n\nThat gives $E[Y^{1,1}] = 150.12$.\n\nThen for $E[Y^{0,0}]$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# for 0, 0\nnew_dat_00 <- baseline_pop %>%\n  mutate(lag_A = 0, A = 0)\n\n# predict covariate means at time 1\nnew_dat_00$pL <- predict(L_mod, newdata = new_dat_00, type = \"response\")\n\n# simulate covariate values at time 1\nnew_dat_00$L <- rbinom(nsim, 1, new_dat_00$pL)\n\n# predict outcome at time 1 based on simulated covariates and fixed treatments\nnew_dat_00$Ey <- predict(Y_mod, newdata = new_dat_00, type = \"response\")\n\n# take mean across all simulations to get g-formula estimate!\nmean(new_dat_00$Ey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 134.7198\n```\n\n\n:::\n:::\n\n\nAnd $E[Y^{0,0}] = 134.72$, so always-treat versus never-treat is worth\n$150.12 - 134.72 = 15.40$ by hand.\n\nNow with the gfoRmula package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# running the g-formula ---------------------------------------------------\n\n# add your comments to the lines below\nid <- \"id\"\ntime_name <- \"time\"\ncovnames <- c(\"L\", \"A\")\noutcome_name <- \"Y\"\n#\noutcome_type <- \"continuous_eof\"\n#\nhistories <- c(lagged)\n#\nhistvars <- list(c(\"A\"))\n#\ncovtypes <- c(\"binary\", \"binary\")\ncovparams <- list(covmodels = c(\n  L ~ lag1_A,\n  A ~ lag1_A * L\n))\nymodel <- Y ~ A * L * lag1_A\n#\nintvars <- list(\"A\", \"A\", \"A\", \"A\")\n#\ninterventions <- list(\n  list(c(static, c(0, 0))),\n  list(c(static, c(0, 1))),\n  list(c(static, c(1, 0))),\n  list(c(static, c(1, 1)))\n)\nint_descript <- c(\n  \"0, 0\",\n  \"0, 1\",\n  \"1, 0\",\n  \"1, 1\"\n)\n\n# put it all together\n# (the warning \"obs_data was coerced to a data table\" is fine!)\ngform_res <- gfoRmula::gformula(\n  obs_data = dat,\n  id = id,\n  time_name = time_name,\n  covnames = covnames,\n  outcome_name = outcome_name,\n  outcome_type = outcome_type,\n  covtypes = covtypes,\n  covparams = covparams,\n  ymodel = ymodel,\n  intvars = intvars,\n  interventions = interventions,\n  int_descript = int_descript,\n  ref_int = 1,\n  histories = histories,\n  histvars = histvars,\n  sim_data_b = TRUE,\n  seed = 345636\n)\n# Use the following code to explore the results. (You can ignore Intervention 0,\n# the natural course intervention, for now.) How many models were fit? How can\n# you tell which of the data in the `sim_data` object was simulated or predicted\n# from a model? Does these results match your answers to the earlier questions,\ngform_res\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPREDICTED RISK UNDER MULTIPLE INTERVENTIONS\n\nIntervention \t Description\n0 \t\t Natural course\n1\t\t 0, 0\n2\t\t 0, 1\n3\t\t 1, 0\n4\t\t 1, 1\n\nSample size = 32000, Monte Carlo sample size = 32000\nNumber of bootstrap samples = 0\nReference intervention = 1\n\n \n\n     k Interv.  NP mean g-form mean Mean ratio Mean difference % Intervened On\n <num>   <num>    <num>       <num>      <num>           <num>           <num>\n     1       0 142.4572    141.5895  1.0523929       7.0489627         0.00000\n     1       1       NA    134.5405  1.0000000       0.0000000        74.87812\n     1       2       NA    134.5276  0.9999039      -0.0129268        75.12188\n     1       3       NA    150.3494  1.1175029      15.8088974        80.85625\n     1       4       NA    150.0516  1.1152895      15.5111169        69.14375\n Aver % Intervened On\n                <num>\n              0.00000\n             49.74531\n             50.25469\n             55.99375\n             44.00625\n```\n\n\n:::\n\n```{.r .cell-code}\ngform_res$coeffs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$L\n (Intercept)       lag1_A \n8.985178e-14 1.098612e+00 \n\n$A\n  (Intercept)        lag1_A             L      lag1_A:L \n-1.098612e+00 -2.273084e-13  2.197225e+00  2.983558e-14 \n\n$Y\n  (Intercept)             A             L        lag1_A           A:L \n  59.97804299    0.07788309  149.84611288  180.24000339   -0.18249806 \n     A:lag1_A      L:lag1_A    A:L:lag1_A \n  -0.37075696 -269.83091494    0.17594707 \n```\n\n\n:::\n\n```{.r .cell-code}\ngform_res$sim_data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$`Natural course`\n          id  time     L     A eligible_pt intervened lag1_A       Ey\n       <int> <num> <num> <num>      <lgcl>      <num>  <num>    <num>\n    1:     1     0    NA     0        TRUE          0      0       NA\n    2:     1     1     1     1        TRUE          0      0 209.7195\n    3:     2     0    NA     0        TRUE          0      0       NA\n    4:     2     1     1     1        TRUE          0      0 209.7195\n    5:     3     0    NA     0        TRUE          0      0       NA\n   ---                                                               \n63996: 31998     1     1     1        TRUE          0      1 119.9338\n63997: 31999     0    NA     1        TRUE          0      0       NA\n63998: 31999     1     1     1        TRUE          0      1 119.9338\n63999: 32000     0    NA     1        TRUE          0      0       NA\n64000: 32000     1     1     1        TRUE          0      1 119.9338\n\n$`0, 0`\n          id  time     L     A eligible_pt intervened lag1_A        Ey\n       <int> <num> <num> <num>      <lgcl>     <lgcl>  <num>     <num>\n    1:     1     0    NA     0        TRUE      FALSE      0        NA\n    2:     1     1     1     0        TRUE       TRUE      0 209.82416\n    3:     2     0    NA     0        TRUE      FALSE      0        NA\n    4:     2     1     1     0        TRUE       TRUE      0 209.82416\n    5:     3     0    NA     0        TRUE      FALSE      0        NA\n   ---                                                                \n63996: 31998     1     0     0        TRUE      FALSE      0  59.97804\n63997: 31999     0    NA     0        TRUE       TRUE      0        NA\n63998: 31999     1     0     0        TRUE      FALSE      0  59.97804\n63999: 32000     0    NA     0        TRUE       TRUE      0        NA\n64000: 32000     1     1     0        TRUE       TRUE      0 209.82416\n\n$`0, 1`\n          id  time     L     A eligible_pt intervened lag1_A        Ey\n       <int> <num> <num> <num>      <lgcl>     <lgcl>  <num>     <num>\n    1:     1     0    NA     0        TRUE      FALSE      0        NA\n    2:     1     1     1     1        TRUE      FALSE      0 209.71954\n    3:     2     0    NA     0        TRUE      FALSE      0        NA\n    4:     2     1     1     1        TRUE      FALSE      0 209.71954\n    5:     3     0    NA     0        TRUE      FALSE      0        NA\n   ---                                                                \n63996: 31998     1     0     1        TRUE       TRUE      0  60.05593\n63997: 31999     0    NA     0        TRUE       TRUE      0        NA\n63998: 31999     1     0     1        TRUE       TRUE      0  60.05593\n63999: 32000     0    NA     0        TRUE       TRUE      0        NA\n64000: 32000     1     1     1        TRUE      FALSE      0 209.71954\n\n$`1, 0`\n          id  time     L     A eligible_pt intervened lag1_A       Ey\n       <int> <num> <num> <num>      <lgcl>     <lgcl>  <num>    <num>\n    1:     1     0    NA     1        TRUE       TRUE      0       NA\n    2:     1     1     1     0        TRUE       TRUE      1 120.2332\n    3:     2     0    NA     1        TRUE       TRUE      0       NA\n    4:     2     1     1     0        TRUE       TRUE      1 120.2332\n    5:     3     0    NA     1        TRUE       TRUE      0       NA\n   ---                                                               \n63996: 31998     1     1     0        TRUE       TRUE      1 120.2332\n63997: 31999     0    NA     1        TRUE      FALSE      0       NA\n63998: 31999     1     1     0        TRUE       TRUE      1 120.2332\n63999: 32000     0    NA     1        TRUE      FALSE      0       NA\n64000: 32000     1     1     0        TRUE       TRUE      1 120.2332\n\n$`1, 1`\n          id  time     L     A eligible_pt intervened lag1_A       Ey\n       <int> <num> <num> <num>      <lgcl>     <lgcl>  <num>    <num>\n    1:     1     0    NA     1        TRUE       TRUE      0       NA\n    2:     1     1     1     1        TRUE      FALSE      1 119.9338\n    3:     2     0    NA     1        TRUE       TRUE      0       NA\n    4:     2     1     1     1        TRUE      FALSE      1 119.9338\n    5:     3     0    NA     1        TRUE       TRUE      0       NA\n   ---                                                               \n63996: 31998     1     1     1        TRUE      FALSE      1 119.9338\n63997: 31999     0    NA     1        TRUE      FALSE      0       NA\n63998: 31999     1     1     1        TRUE      FALSE      1 119.9338\n63999: 32000     0    NA     1        TRUE      FALSE      0       NA\n64000: 32000     1     1     1        TRUE      FALSE      1 119.9338\n```\n\n\n:::\n:::\n\n\nThe package agrees with the hand calculation. Intervention 4 (\"1, 1\", always\ntreat) gives a g-formula mean of 150.0516 against the 150.12 computed by hand,\nand intervention 1 (\"0, 0\", never treat) gives 134.5405 against 134.72 — the\nsmall gaps are Monte Carlo error, since both routes simulate rather than\nintegrate. The table's own contrast of the two, 15.51, matches the 15.40 from\nthe hand calculation.\n\nThe natural course is 141.59, sitting between the two regimes, and the\nnon-parametric mean of the observed data is 142.46, which is the check that the\nmodel-based natural course is not badly misspecified.\n\nThe other two regimes are worth a glance. Treating only at time 0 gives 150.35\nand treating only at time 1 gives 134.53 — so essentially all of the effect\ncomes from the first period's treatment, and the second period adds nothing.\n\nReading `gform_res$coeffs` shows why this needs the g-formula rather than a\nregression. The $L$ model has a coefficient of 1.0986 on lagged treatment, so\npast treatment moves the time-1 covariate; and the $Y$ model has 149.85 on $L$\nand $-269.83$ on the $L \\times \\text{lag}_1 A$ interaction, so that covariate\nin turn moves the outcome. $L$ is a time-varying confounder affected by past\ntreatment, which is exactly the configuration where conditioning on it blocks\npart of the effect and omitting it leaves confounding.\n\n## A second example\n\nChistopher Boyer has a package \"gmethods\" that can be used to estimate the g-formula.  To me it's a bit more intuitive than the gfoRmula package.  Here is an example in the \"gmethods\" package, with the same model in the \"gfoRmula\" package.\n\nThe example dataset continuous_eofdata again consists of 7,500 observations on 2,500 individuals with a maximum of 7 follow-up times, where the outcome corresponds to a characteristic only in the last interval (e.g., systolic blood pressure in interval 7). The variables in the dataset are:\nt0: The time index\nid: A unique identifier for each individual\nL1: A time-varying covariate; categorical\nL2: A time-varying covariate; continuous\nL3: A baseline covariate; continuous\nA: The treatment variable; binary\nY: The outcome of interest; continuous\n\nThe goal is to estimate the mean outcome at time $K + 1 = 7$ under ‘‘never treat’’ versus ‘‘always treat.’’\n\nThe DAG would be something like:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndag <- dagify(\n  Y ~ A + L1 + L2 + L3 + lag1_A + lag1_L1 + lag1_L2 ,\n  L1 ~ lag1_A + lag1_L1 + lag1_L2 + L3 ,\n  L2 ~ lag1_A + L1 + lag1_L1 + lag1_L2 + L3,\n  A ~ lag1_A + L1 + L2 + lag1_L1 + lag1_L2 + L3,\n  coords = time_ordered_coords()\n)\n\ndag %>%\n  ggplot(aes(x = x, y = y, xend = xend, yend = yend)) +\n  geom_dag_point() +\n  geom_dag_edges_arc() +\n  geom_dag_text() +\n  theme_dag()\n```\n\n::: {.cell-output-display}\n![](g-estimation_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n### gFormula results\n\nFirst use the gFormula package.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nid <- 'id'\ntime_name <- 't0'\ncovnames <- c('L1', 'L2', 'A')\noutcome_name <- 'Y'\ncovtypes <- c('categorical', 'normal', 'binary')\nhistories <- c(lagged)\nhistvars <- list(c('A', 'L1', 'L2'))\ncovparams <- list(covmodels = c(L1 ~ lag1_A + lag1_L1 + L3 + t0 +\n                                 lag1_L2,\n                                L2 ~ lag1_A + L1 + lag1_L1 + lag1_L2 + L3 + t0,\n                                A ~ lag1_A + L1 + L2 + lag1_L1 + lag1_L2 + L3 + t0))\nymodel <- Y ~ A + L1 + L2 + lag1_A + lag1_L1 + lag1_L2 + L3\nintvars <- list('A', 'A')\ninterventions <- list(list(c(static, rep(0, 7))),\n                      list(c(static, rep(1, 7))))\nint_descript <- c('Never treat', 'Always treat')\nnsimul <- 50000\n\ngform_cont_eof <- gformula_continuous_eof(obs_data = continuous_eofdata,\n                                          id = id,\n                                          time_name = time_name,\n                                          covnames = covnames,\n                                          outcome_name = outcome_name,\n                                          covtypes = covtypes,\n                                          covparams = covparams, ymodel = ymodel,\n                                          intvars = intvars,\n                                          interventions = interventions,\n                                          int_descript = int_descript,\n                                          histories = histories,\n                                          histvars = histvars,\n                                          model_fits = TRUE,\n                                          basecovs = c(\"L3\"),\n                                          nsimul = nsimul, seed = 1234)\ngform_cont_eof\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPREDICTED RISK UNDER MULTIPLE INTERVENTIONS\n\nIntervention \t Description\n0 \t\t Natural course\n1\t\t Never treat\n2\t\t Always treat\n\nSample size = 2500, Monte Carlo sample size = 50000\nNumber of bootstrap samples = 0\nReference intervention = natural course (0)\n \n\n     k Interv.   NP mean g-form mean Mean ratio Mean difference % Intervened On\n <num>   <num>     <num>       <num>      <num>           <num>           <num>\n     6       0 -4.414543   -4.363027  1.0000000       0.0000000           0.000\n     6       1        NA   -3.133081  0.7180981       1.2299454         100.000\n     6       2        NA   -4.602952  1.0549904      -0.2399248          74.038\n Aver % Intervened On\n                <num>\n              0.00000\n             82.35200\n             17.49571\n```\n\n\n:::\n:::\n\n\n### gmethods results\n\nNow use the gmethods package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf <- gmethods::gformula(\n  outcome_model = list(\n    formula = Y ~ A + L1 + L2 + lag1_A + lag1_L1 + lag1_L2 + L3,\n    link = \"identity\",\n    family = \"normal\"\n  ),\n  covariate_model = list(\n    \"L1\" = list(\n      formula = L1 ~ lag1_A + lag1_L1 + L3 + t0 + lag1_L2,\n      family = \"categorical\"\n    ),\n    \"L2\" = list(\n      formula = L2 ~ lag1_A + L1 + lag1_L1 + lag1_L2 + L3 + t0,\n      link = \"identity\",\n      family = \"normal\"\n    ),\n    \"A\" = list(\n      formula = A ~ lag1_A + L1 + L2 + lag1_L1 + lag1_L2 + L3 + t0,\n      link = \"logit\",\n      family = \"binomial\"\n    )\n  ),\n  data = continuous_eofdata,\n  survival = FALSE,\n  id = 'id',\n  time = 't0'\n)\n\ns <- simulate(\n  gf,\n  interventions = list(\n    \"Never treat\" = function(data, time) set(data, j = \"A\", value = 0),\n    \"Always treat\" = function(data, time) set(data, j = \"A\", value = 1)\n  ),\n  n_samples = 50000\n)\n\ns$results\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$means\n  intervention  estimate conf.low conf.high\n1            0 -4.360358       NA        NA\n2            1 -3.139260       NA        NA\n3            2 -4.602994       NA        NA\n\n$ratios\n  intervention  estimate conf.low conf.high\n1            0        NA       NA        NA\n2            1 0.7199547       NA        NA\n3            2 1.0556459       NA        NA\n\n$diffs\n  intervention  estimate conf.low conf.high\n1            0        NA       NA        NA\n2            1  1.221098       NA        NA\n3            2 -0.242636       NA        NA\n```\n\n\n:::\n:::\n\n\nBoth packages agree closely. `gfoRmula` gives a natural course of $-4.363$,\nnever-treat $-3.133$ and a mean difference of 1.230; `gmethods` gives $-4.360$,\n$-3.139$ and 1.221, with always-treat at $-4.603$ and a difference of $-0.243$.\nThe two implementations differ in the third decimal, which is Monte Carlo noise\nfrom the 50,000-draw simulation, not a disagreement about the estimand.\n\nNote the results are very close.  Also note that in the covariates and treatment models, there is a time variable t0.  This is because these models are pooled regression with all time points.  Therefore a time fixed effect is included.  In the outcome model, there is only the last period data, so the time variable is not included.\n\nStandard errors can be calculated with bootstrapping.\n\n---\n\n<!-- see-also-footer -->\n*Systematic treatment: [R](https://xiangao.github.io/causal_econometrics_guide/g-methods.html) · [Julia](https://xiangao.github.io/causal_econometrics_julia/g-methods.html).*\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}