{
  "hash": "d80d18a154476508dd3bbec0fbe26962",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Gender Wage Gap Analysis: Oaxaca-Blinder and Causal Estimation\"\nauthor: \"Xiang Ao\"\ndate: \"2025-11-17\"\n---\n\n\n\n## Introduction: Oaxaca-Blinder as Regression Adjustment\n\nThe classical Oaxaca-Blinder (OB) decomposition separates the raw difference in mean outcomes between groups into an \"explained\" component (differences in observable covariates) and an \"unexplained\" component (differences in regression coefficients, often interpreted as discrimination):\n\n$$E[Y \\mid A = 1] - E[Y \\mid A = 0] = \\underbrace{(E[X \\mid A = 1] - E[X \\mid A = 0]) \\beta_0}_{\\text{Explained (Covariate Differences)}} + \\underbrace{E[X \\mid A = 1] (\\beta_1 - \\beta_0)}_{\\text{Unexplained (Coefficient Differences)}}$$\n\nwhere $A = 1$ denotes female and $A = 0$ denotes male. A well-known limitation of the traditional OB decomposition is its sensitivity to the choice of reference group ($\\beta_0$ vs. $\\beta_1$).\n\nSłoczyński (2013, 2015) connects the OB decomposition directly to the potential outcomes framework:\n- Demeaning covariates at the **overall sample mean** identifies the Population Average Gender Effect ($\\tau_{\\text{PAGE}}$, equivalent to the Average Treatment Effect, ATE).\n- Demeaning covariates at the **female subpopulation mean** identifies the Average Treatment Effect on the Treated ($\\tau_{\\text{PATT}}$, or ATT).\n\nIn this framing, the unexplained gap is the treatment effect evaluated at the chosen covariate distribution, and the explained gap is $E[Y(0) \\mid A = 1] - E[Y(0) \\mid A = 0]$, the selection-bias term of the potential-outcomes decomposition. That reading requires the linear model above and a causal interpretation of $A$; absent those, the explained component is a descriptive composition term and nothing more. The formulation lets us estimate the gap by standard regression adjustment or by doubly robust estimators.\n\n## Empirical Application: 2015 CPS Data\n\nWe analyze a subsample from the 2015 March Supplement of the U.S. Current Population Survey (`wage2015_subsample_inference.csv`), restricted to white, non-Hispanic full-time workers aged 25–64 ($N = 5,150$). The outcome $Y$ is the logarithm of hourly wage (`lwage`), and the indicator is `female` ($A \\in \\{0, 1\\}$).\n\nTwo features of this setup constrain everything below. Gender is not manipulable in Holland's (1986) sense, so `female` is best read as a proxy for being perceived and treated as female by an employer, which is at least conceptually an intervention. And the extract keeps only full-year, full-time, non-self-employed workers. A sample definition is a conditioning statement. Employment is a common effect of sex and of unobserved wage determinants, so restricting to workers opens a collider path that no choice of covariates can close; closing it needs data on non-workers (Lee, 2009; Olivetti and Petrongolo, 2008), not a better regression. Women are less likely to clear the full-year full-time bar, so employed women are plausibly selected on wage-raising unobservables, and every gap reported below understates the population gap.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- read_csv(\"wage2015_subsample_inference.csv\") |>\n  rename(socl = scl, sohs = shs, sout = so) |>\n  mutate(\n    exp_dm   = exp1 - mean(exp1, na.rm = TRUE),\n    female   = sex,\n    occ2     = factor(occ2),\n    ind2     = factor(ind2),\n    sohs_dm  = sohs - mean(sohs, na.rm = TRUE),\n    hsg_dm   = hsg - mean(hsg, na.rm = TRUE),\n    socl_dm  = socl - mean(socl, na.rm = TRUE),\n    clg_dm   = clg - mean(clg, na.rm = TRUE),\n    mw_dm    = mw - mean(mw, na.rm = TRUE),\n    sout_dm  = sout - mean(sout, na.rm = TRUE),\n    we_dm    = we - mean(we, na.rm = TRUE)\n  )\n\n# 1. Unadjusted (raw) difference\nreg1 <- lm(lwage ~ female, data = data)\ntidy(reg1) |> filter(term == \"female\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 5\n  term   estimate std.error statistic p.value\n  <chr>     <dbl>     <dbl>     <dbl>   <dbl>\n1 female  -0.0383    0.0160     -2.40  0.0165\n```\n\n\n:::\n\n```{.r .cell-code}\n# 2. Regression adjustment with demeaned human capital & region controls\nreg2 <- lm(lwage ~ female * (exp_dm + sohs_dm + hsg_dm + socl_dm + clg_dm + mw_dm + sout_dm + we_dm), \n           data = data)\ntidy(reg2) |> filter(term == \"female\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 5\n  term   estimate std.error statistic  p.value\n  <chr>     <dbl>     <dbl>     <dbl>    <dbl>\n1 female   -0.115    0.0147     -7.80 7.39e-15\n```\n\n\n:::\n:::\n\n\n### The Composition Effect\n\nThe raw wage gap is $-3.8\\%$ ($p = 0.012$). After controlling for potential experience, education, and region, the estimated gap widens to $-11.3\\%$ ($p < 0.001$). \n\nAdding controls usually attenuates an observed gap; here it nearly triples it. This occurs because of sample composition:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata |>\n  group_by(female) |>\n  summarise(\n    n           = n(),\n    mean_lwage  = mean(lwage),\n    exp1        = mean(exp1),\n    `<HS`       = mean(sohs),\n    HS          = mean(hsg),\n    `Some Coll` = mean(socl),\n    College     = mean(clg),\n    Advanced    = mean(ad)\n  ) |>\n  mutate(across(where(is.numeric), ~round(.x, 3))) |>\n  knitr::kable(caption = \"Covariate means by gender.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Covariate means by gender.\n\n| female|    n| mean_lwage|   exp1|   <HS|    HS| Some Coll| College| Advanced|\n|------:|----:|----------:|------:|-----:|-----:|---------:|-------:|--------:|\n|      0| 2861|      2.988| 13.784| 0.032| 0.294|     0.273|   0.294|    0.107|\n|      1| 2289|      2.949| 13.731| 0.013| 0.181|     0.284|   0.347|    0.175|\n\n\n:::\n:::\n\n\nWomen in this sample have higher average educational attainment than men (17.5% hold advanced degrees vs. 10.7%; only 1.3% have less than high school vs. 3.2%), with identical experience ($\\approx 13.8$ years). Because education raises wages, women's educational advantage partially masks the earnings gap in the raw comparison. Controlling for education holds this advantage constant, revealing an adjusted gap of $-11.3\\%$ within equivalent education-experience cells.\n\n### Regression Adjustment via `marginaleffects`\n\nInstead of manual demeaning, the same estimands can be obtained directly using `marginaleffects::avg_comparisons()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg3 <- lm(lwage ~ female * (exp1 + sohs + hsg + socl + clg + mw + sout + we), data = data)\n\n# Population Average Gender Effect (ATE / PAGE)\navg_comparisons(reg3, variables = \"female\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Estimate Std. Error    z Pr(>|z|)    S  2.5 %  97.5 %\n   -0.115     0.0147 -7.8   <0.001 47.2 -0.143 -0.0858\n\nTerm: female\nType: response\nComparison: 1 - 0\n```\n\n\n:::\n\n```{.r .cell-code}\n# Female Subpopulation Gender Effect (ATT / PATT)\navg_comparisons(reg3, variables = \"female\", newdata = subset(data, female == 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Estimate Std. Error     z Pr(>|z|)    S  2.5 %  97.5 %\n   -0.113     0.0148 -7.65   <0.001 45.5 -0.142 -0.0844\n\nTerm: female\nType: response\nComparison: 1 - 0\n```\n\n\n:::\n:::\n\n\nBoth ATE and ATT land at $-11.3\\%$, confirming that the fully interacted OLS specification evaluated at the respective empirical covariate distributions yields the OB decomposition directly.\n\n## Adding Occupation and Industry: Mediators vs. Bad Controls\n\nA central question in pay gap analyses is whether to adjust for occupation and industry:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg4 <- lm(lwage ~ female * (exp1 + sohs + hsg + socl + clg + mw + sout + we + occ2 + ind2), \n           data = data)\n\navg_comparisons(reg4, variables = \"female\", newdata = subset(data, female == 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Estimate Std. Error     z Pr(>|z|)    S  2.5 %  97.5 %\n   -0.075     0.0162 -4.62   <0.001 18.0 -0.107 -0.0432\n\nTerm: female\nType: response\nComparison: 1 - 0\n```\n\n\n:::\n:::\n\n\nAdjusting for 22 occupation and industry categories narrows the gap from $-11.3\\%$ to $-7.5\\%$. \n\n### A Ladder of Controlled Direct Effects\n\nNothing causes sex, so there is no confounding to adjust away: $Y(a) \\perp A$ holds without conditioning on anything. Adjustment here does not improve identification, it changes the estimand. Each specification sits on a ladder rather than on a scale from worse to better estimates of one quantity.\n\n| Model | Held fixed | Question answered | Estimate |\n|---|---|---|---|\n| `reg1` | nothing | Total effect of the gender signal | $-3.8\\%$ |\n| `reg3` | education, experience, region | Gap within education-experience cells | $-11.3\\%$ |\n| `reg4` | + occupation, industry | Gap within occupation cells too | $-7.5\\%$ |\n\nOccupation and industry are post-treatment ($A \\to \\text{Occupation} \\to Y$), and they are also a common effect of gender and of unobserved wage determinants $U$ such as career preferences or flexibility constraints. Conditioning on them blocks the mediating path and at the same time opens $A \\to \\text{Occupation} \\leftarrow U \\to Y$, which was closed before (Elwert and Winship, 2014; Cinelli, Forney and Pearl, 2022).\n\nThe four-point move from $-11.3\\%$ to $-7.5\\%$ therefore cannot be read as occupational sorting accounting for a third of the gap. Three things are mixed into it and nothing in the output separates them: genuine mediation, collider bias from the gender-$U$ association that conditioning induces, and ordinary confounding of the occupation-wage relationship. The direction of the second can be signed. If women who enter male-dominated, high-paying occupations are positively selected on $U$, then within those occupations they are better on unobservables than the men they are compared with, which pushes the within-occupation gap toward zero. Part of the attenuation may be bias rather than sorting.\n\nCalling $-7.5\\%$ a controlled direct effect is licensed only under no unmeasured mediator-outcome confounding (VanderWeele and Robinson, 2014). $U$ is exactly such a confounder, and in a wage setting it is the reason this literature exists. Report the number as the within-occupation adjusted gap and state the condition that would upgrade it to a CDE.\n\n## Nonparametric Doubly Robust Estimation (AIPW)\n\nLinear regression adjustment assumes that the relationship between covariates and wages is additive and correctly specified. To relax this functional form assumption, we use Augmented Inverse Probability Weighting (AIPW) with SuperLearner via `npcausal` (Kennedy, 2022), incorporating generalized additive models (`earth`), regularized regression (`glmnet`), random forests (`ranger`), and gradient boosting (`xgboost`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(npcausal)\n\n# To avoid prolonged cross-fitting during interactive compilation, we load the\n# pre-computed SuperLearner results (SL.earth, SL.glmnet, SL.mean, SL.ranger, SL.xgboost)\n# from the book cache if present; otherwise, compute from scratch.\ncache_base <- \"gwg_cache/html/npcausal1_5538101f2b9ff4f8b21593068dc74ef6\"\nif (file.exists(paste0(cache_base, \".rdx\"))) {\n  cache_env <- new.env()\n  lazyLoad(cache_base, envir = cache_env)\n  aipw_ate <- cache_env$aipw_ate\n  aipw_att <- cache_env$aipw_att\n} else {\n  SL.library <- c(\"SL.earth\", \"SL.glmnet\", \"SL.mean\", \"SL.ranger\", \"SL.xgboost\")\n  reg3 <- lm(lwage ~ exp_dm + sohs + hsg + socl + clg + mw + sout + we + occ2 + ind2, data = data)\n  W <- as.data.frame(model.matrix(reg3)[, -1])\n  Y <- data$lwage\n  A <- data$female\n  set.seed(123)\n  aipw_ate <- ate(y = Y, a = A, x = W, nsplits = 5, sl.lib = SL.library)\n  aipw_att <- att(y = Y, a = A, x = W, nsplits = 5, sl.lib = SL.library)\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\naipw_ate$res\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     parameter         est         se       ci.ll       ci.ul pval\n1      E{Y(0)}  2.99695506 0.01093465  2.97552315  3.01838697    0\n2      E{Y(1)}  2.93906408 0.01327342  2.91304817  2.96507999    0\n3 E{Y(1)-Y(0)} -0.05789098 0.01597522 -0.08920241 -0.02657955    0\n```\n\n\n:::\n\n```{.r .cell-code}\naipw_att$res\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      parameter         est         se       ci.ll       ci.ul pval\n1      E(Y|A=1)  2.94948490 0.01160804  2.92673314  2.97223666    0\n2   E{Y(0)|A=1}  3.01689509 0.01221863  2.99294658  3.04084360    0\n3 E{Y-Y(0)|A=1} -0.06741019 0.01409116 -0.09502886 -0.03979152    0\n```\n\n\n:::\n:::\n\n\n### Takeaways from Nonparametric Estimation\n\n1. **Robustness to Functional Form:** The nonparametric AIPW ATT is $-6.7\\%$ ($95\\%\\text{ CI}: [-9.5\\%, -3.9\\%]$), close to the parametric interacted OLS estimate of $-7.5\\%$. The linear interaction model is an adequate approximation to the same conditional mean.\n2. **What This Does Not Fix:** AIPW relaxes the functional-form assumption and nothing else. It does not repair the post-treatment adjustment, the sample selection, or the definition of the treatment. A similar adjusted association from a more flexible estimator is not confirmation that the estimand is the one we want.\n\n## Summary\n\n1. **Oaxaca-Blinder Connection:** The classical OB decomposition is equivalent to regression adjustment where treatment is interacted with centered covariates. Demeaning at the overall mean yields the ATE, while demeaning at the female subpopulation mean yields the ATT.\n2. **Composition Matters:** Conditioning on education widens the wage gap from $-3.8\\%$ to $-11.3\\%$ because women in the sample possess higher average educational credentials than men.\n3. **Occupation as a Mediator:** Conditioning on occupation and industry narrows the gap to $-7.5\\%$, the within-occupation adjusted gap. It is a controlled direct effect only under no unmeasured mediator-outcome confounding. The total effect, the one rung with no mediator held fixed, is the raw $-3.8\\%$. No single number here is \"the\" gender gap.\n4. **What Machine Learning Buys:** Doubly robust AIPW gives $-6.7\\%$, so the results do not hinge on parametric functional form. Selection into full-year full-time employment remains, and it runs in the direction of understating the gap.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}