{
  "hash": "12f77a27eb727e41388f4fb424f57474",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Comparing Marginal effects with margins command\"\ndate: \"2019-04-22\"\n---\n\n\n## Comparing marginal effects\n\nA common practice is to plot marginal effects with `margins` and `marginsplot`, then conclude two effects differ whenever their confidence intervals do not overlap. This can be wrong — overlapping intervals do not imply no significant difference, because the test depends on the joint distribution of the two estimates, not on their marginal distributions separately.\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.stata .cell-code}\nwebuse nhanes2f, clear\nlogit diabetes i.female##c.age, nolog\nmargins female,  at(age=(20 30 40 50 60 70)) \nmarginsplot\ngraph export \"marginsplot1.svg\", as(svg) replace\nmargins r.female,  at(age=(20 30 40 50 60 70)) \nmarginsplot\ngraph export \"marginsplot2.svg\", as(svg) replace\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLogistic regression                                     Number of obs = 10,335\n                                                        LR chi2(3)    = 353.06\n                                                        Prob > chi2   = 0.0000\nLog likelihood = -1822.5393                             Pseudo R2     = 0.0883\n\n------------------------------------------------------------------------------\n    diabetes | Coefficient  Std. err.      z    P>|z|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n      female |\n     Female  |   1.404111   .4858776     2.89   0.004     .4518088    2.356414\n         age |   .0714166   .0063231    11.29   0.000     .0590235    .0838097\n             |\nfemale#c.age |\n     Female  |  -.0206572   .0078369    -2.64   0.008    -.0360172   -.0052972\n             |\n       _cons |  -7.041892   .3967299   -17.75   0.000    -7.819468   -6.264315\n------------------------------------------------------------------------------\n\n\nAdjusted predictions                                    Number of obs = 10,335\nModel VCE: OIM\n\nExpression: Pr(diabetes), predict()\n1._at: age = 20\n2._at: age = 30\n3._at: age = 40\n4._at: age = 50\n5._at: age = 60\n6._at: age = 70\n\n------------------------------------------------------------------------------\n             |            Delta-method\n             |     Margin   std. err.      z    P>|z|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n  _at#female |\n     1#Male  |   .0036348   .0009895     3.67   0.000     .0016953    .0055743\n   1#Female  |   .0097316   .0018436     5.28   0.000     .0061184    .0133449\n     2#Male  |    .007396   .0015622     4.73   0.000     .0043341    .0104579\n   2#Female  |   .0160637   .0023434     6.85   0.000     .0114706    .0206568\n     3#Male  |   .0149906   .0022831     6.57   0.000     .0105159    .0194653\n   3#Female  |    .026406   .0027757     9.51   0.000     .0209657    .0318462\n     4#Male  |   .0301469   .0029996    10.05   0.000     .0242677    .0360261\n   4#Female  |    .043115   .0030923    13.94   0.000     .0370543    .0491758\n     5#Male  |   .0596983   .0040248    14.83   0.000     .0518099    .0675867\n   5#Female  |    .069641   .0040284    17.29   0.000     .0617454    .0775366\n     6#Male  |   .1147889   .0089467    12.83   0.000     .0972536    .1323242\n   6#Female  |   .1106004   .0078699    14.05   0.000     .0951757     .126025\n------------------------------------------------------------------------------\n\n\nVariables that uniquely identify margins: age female\n\nfile marginsplot1.svg saved as SVG format\n\n\nContrasts of adjusted predictions                       Number of obs = 10,335\nModel VCE: OIM\n\nExpression: Pr(diabetes), predict()\n1._at: age = 20\n2._at: age = 30\n3._at: age = 40\n4._at: age = 50\n5._at: age = 60\n6._at: age = 70\n\n-------------------------------------------------------\n                    |         df        chi2     P>chi2\n--------------------+----------------------------------\n         female@_at |\n(Female vs Male) 1  |          1        8.49     0.0036\n(Female vs Male) 2  |          1        9.47     0.0021\n(Female vs Male) 3  |          1       10.09     0.0015\n(Female vs Male) 4  |          1        9.06     0.0026\n(Female vs Male) 5  |          1        3.05     0.0808\n(Female vs Male) 6  |          1        0.12     0.7252\n             Joint  |          4       40.48     0.0000\n-------------------------------------------------------\n\n---------------------------------------------------------------------\n                    |            Delta-method\n                    |   Contrast   std. err.     [95% conf. interval]\n--------------------+------------------------------------------------\n         female@_at |\n(Female vs Male) 1  |   .0060969   .0020923      .0019959    .0101978\n(Female vs Male) 2  |   .0086677   .0028164      .0031476    .0141878\n(Female vs Male) 3  |   .0114154    .003594      .0043712    .0184595\n(Female vs Male) 4  |   .0129682   .0043081      .0045244    .0214119\n(Female vs Male) 5  |   .0099427   .0056945     -.0012183    .0211037\n(Female vs Male) 6  |  -.0041885   .0119155     -.0275425    .0191654\n---------------------------------------------------------------------\n\n\nVariables that uniquely identify margins: age\n\nfile marginsplot2.svg saved as SVG format\n```\n\n\n:::\n:::\n\n\n![](marginsplot1.svg)\n\n![](marginsplot2.svg)\n\nWe fit a logit of diabetes on female, age, and their interaction, on 10,335 NHANES II respondents. The interaction is $-0.0207$ with a standard error of 0.0078, so the female-male gap narrows with age. The first `margins` call gives predicted probabilities by gender; the second (with `r.female`) gives the female-vs-male contrast at each age. (On the general question of marginal effects in nonlinear models, see the previous chapter — the coefficient on the link scale is usually more interpretable.)\n\nThose contrasts run $.0061$, $.0087$, $.0114$, $.0130$, $.0099$ and $-.0042$ at\nages 20 through 70, significant through age 50 and not thereafter — the gap\nwidens, peaks in middle age, then closes and reverses sign.\n\nNow the point of the chapter. The female effect at age 20 is $.0061$ with a 95%\ninterval of $[.0020, .0102]$, and at age 30 it is $.0087$ with an interval of\n$[.0031, .0142]$. Those intervals overlap across most of their length. It is\ntempting to conclude the two effects are not significantly different, but that conclusion does not follow. For two effects $x$ and $y$ from the same model,\n\n$$ \\text{Var}(x - y) = \\text{Var}(x) + \\text{Var}(y) - 2\\,\\text{Cov}(x, y). $$ {#eq-comparing-margins-1}\n\nWhen $x$ and $y$ are positively correlated — as they will be, coming from the same fit — the variance of their difference can be much smaller than either individual variance. So the difference can be significant even when the individual intervals overlap.\n\n\n\n::: {.cell}\n\n```{.stata .cell-code}\nwebuse nhanes2f, clear\nlogit diabetes i.female##c.age, nolog\nmargins r.female,  at(age=(20 30 40 50 60 70)) post\nlincom _b[r1vs0.female@2._at] - _b[r1vs0.female@1._at]\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLogistic regression                                     Number of obs = 10,335\n                                                        LR chi2(3)    = 353.06\n                                                        Prob > chi2   = 0.0000\nLog likelihood = -1822.5393                             Pseudo R2     = 0.0883\n\n------------------------------------------------------------------------------\n    diabetes | Coefficient  Std. err.      z    P>|z|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n      female |\n     Female  |   1.404111   .4858776     2.89   0.004     .4518088    2.356414\n         age |   .0714166   .0063231    11.29   0.000     .0590235    .0838097\n             |\nfemale#c.age |\n     Female  |  -.0206572   .0078369    -2.64   0.008    -.0360172   -.0052972\n             |\n       _cons |  -7.041892   .3967299   -17.75   0.000    -7.819468   -6.264315\n------------------------------------------------------------------------------\n\n\nContrasts of adjusted predictions                       Number of obs = 10,335\nModel VCE: OIM\n\nExpression: Pr(diabetes), predict()\n1._at: age = 20\n2._at: age = 30\n3._at: age = 40\n4._at: age = 50\n5._at: age = 60\n6._at: age = 70\n\n-------------------------------------------------------\n                    |         df        chi2     P>chi2\n--------------------+----------------------------------\n         female@_at |\n(Female vs Male) 1  |          1        8.49     0.0036\n(Female vs Male) 2  |          1        9.47     0.0021\n(Female vs Male) 3  |          1       10.09     0.0015\n(Female vs Male) 4  |          1        9.06     0.0026\n(Female vs Male) 5  |          1        3.05     0.0808\n(Female vs Male) 6  |          1        0.12     0.7252\n             Joint  |          4       40.48     0.0000\n-------------------------------------------------------\n\n---------------------------------------------------------------------\n                    |            Delta-method\n                    |   Contrast   std. err.     [95% conf. interval]\n--------------------+------------------------------------------------\n         female@_at |\n(Female vs Male) 1  |   .0060969   .0020923      .0019959    .0101978\n(Female vs Male) 2  |   .0086677   .0028164      .0031476    .0141878\n(Female vs Male) 3  |   .0114154    .003594      .0043712    .0184595\n(Female vs Male) 4  |   .0129682   .0043081      .0045244    .0214119\n(Female vs Male) 5  |   .0099427   .0056945     -.0012183    .0211037\n(Female vs Male) 6  |  -.0041885   .0119155     -.0275425    .0191654\n---------------------------------------------------------------------\n\n\n ( 1)  - r1vs0.female@1bn._at + r1vs0.female@2._at = 0\n\n------------------------------------------------------------------------------\n             | Coefficient  Std. err.      z    P>|z|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n         (1) |   .0025709   .0007946     3.24   0.001     .0010134    .0041283\n------------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\nThe test gives a difference of $.0025709$ with a standard error of $.0007946$,\n$z = 3.24$ and $p = 0.001$. The two effects are different, despite intervals\nthat overlap heavily.\n\nThe standard error is what makes the point. Each individual contrast carries a\nstandard error of $.0021$ and $.0028$, but their *difference* carries only\n$.00079$ — smaller than either. Solving\n$\\text{Var}(x-y) = \\text{Var}(x) + \\text{Var}(y) - 2\\text{Cov}(x,y)$ for the\ncorrelation gives about $0.99$: the two contrasts come from the same fitted\nmodel evaluated ten years apart, so they move together almost perfectly, and\nnearly all of their variance cancels in the difference.\n\nHad we ignored the covariance and used\n$\\sqrt{\\text{Var}(x)+\\text{Var}(y)} = .0035$, we would have got $z = 0.73$ and\n$p = 0.46$. Same data, same two numbers, opposite conclusion. That is the cost\nof reading overlap off a graph.\n\nWe can do this with native Stata syntax: `margins ..., post` posts the estimated contrasts as if they were regular coefficients (named `r1vs0.female@1._at`, `r1vs0.female@2._at`, etc. — check `matrix list e(b)` to see the exact names), so `lincom` can test any linear combination of them natively, without depending on a user-written command.\n\n`margins` can compute these differences directly with `contrast(atcontrast(r))`, which compares each evaluation point to the reference:\n\n\n::: {.cell}\n\n```{.stata .cell-code}\nwebuse nhanes2f, clear\nlogit diabetes i.female##c.age, nolog\nmargins r.female,  at(age=(20 30 40 50 60 70)) contrast(atcontrast(r))\nmarginsplot\ngraph export \"marginsplot3.svg\", as(svg) replace\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLogistic regression                                     Number of obs = 10,335\n                                                        LR chi2(3)    = 353.06\n                                                        Prob > chi2   = 0.0000\nLog likelihood = -1822.5393                             Pseudo R2     = 0.0883\n\n------------------------------------------------------------------------------\n    diabetes | Coefficient  Std. err.      z    P>|z|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n      female |\n     Female  |   1.404111   .4858776     2.89   0.004     .4518088    2.356414\n         age |   .0714166   .0063231    11.29   0.000     .0590235    .0838097\n             |\nfemale#c.age |\n     Female  |  -.0206572   .0078369    -2.64   0.008    -.0360172   -.0052972\n             |\n       _cons |  -7.041892   .3967299   -17.75   0.000    -7.819468   -6.264315\n------------------------------------------------------------------------------\n\n\nContrasts of adjusted predictions                       Number of obs = 10,335\nModel VCE: OIM\n\nExpression: Pr(diabetes), predict()\n1._at: age = 20\n2._at: age = 30\n3._at: age = 40\n4._at: age = 50\n5._at: age = 60\n6._at: age = 70\n\n--------------------------------------------------------------\n                           |         df        chi2     P>chi2\n---------------------------+----------------------------------\n                _at#female |\n(2 vs 1) (Female vs Male)  |          1       10.47     0.0012\n(3 vs 1) (Female vs Male)  |          1        9.28     0.0023\n(4 vs 1) (Female vs Male)  |          1        5.48     0.0192\n(5 vs 1) (Female vs Male)  |          1        0.50     0.4807\n(6 vs 1) (Female vs Male)  |          1        0.65     0.4203\n                    Joint  |          4       20.04     0.0005\n--------------------------------------------------------------\n\n----------------------------------------------------------------------------\n                           |            Delta-method\n                           |   Contrast   std. err.     [95% conf. interval]\n---------------------------+------------------------------------------------\n                _at#female |\n(2 vs 1) (Female vs Male)  |   .0025709   .0007946      .0010134    .0041283\n(3 vs 1) (Female vs Male)  |   .0053185    .001746      .0018964    .0087407\n(4 vs 1) (Female vs Male)  |   .0068713   .0029351      .0011187    .0126239\n(5 vs 1) (Female vs Male)  |   .0038458   .0054532     -.0068422    .0145339\n(6 vs 1) (Female vs Male)  |  -.0102854   .0127614     -.0352972    .0147264\n----------------------------------------------------------------------------\n\n\nVariables that uniquely identify margins: age\n\nfile marginsplot3.svg saved as SVG format\n```\n\n\n:::\n:::\n\n\n![](marginsplot3.svg)\n \n\nFrom this we see the difference of effects between point 2 and 1 is .0026, with\n$\\chi^2(1) = 10.47$ and $p = 0.0012$ — the same conclusion the `lincom` test\ngave above, and indeed the same test: $3.24^2 = 10.5$. The remaining rows compare\neach later age to age 20, and the widening gap is significant through age 50\n((4 vs 1): $\\chi^2 = 5.48$, $p = 0.019$) before losing precision.\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}