{
  "hash": "718f38157c418b6b59211da9b03c394e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Bartik Instrument and Rotemberg weights\"\ndate: \"2024-10-26\"\n---\n\n\n## Bartik Instrument\n\nThe Bartik instrument, or shift-share IV (Bartik 1991), combines initial local industry shares with national industry growth rates to construct an instrument for local economic conditions.\n\nWe follow Goldsmith-Pinkham, Sorkin, and Swift (2021) (GPSS). Consider the labor-supply elasticity:\n\n$$ y_{lt} = D_{lt} \\rho + \\beta_0 x_{lt} + \\epsilon_{lt}$$ {#eq-bartik-instrument-1}\n\nHere $y_{lt}$ is wage growth in location $l$, $x_{lt}$ is employment growth, and $\\beta_0$ is the inverse labor-supply elasticity. The challenge is that $x_{lt}$ is endogenous — unobserved factors may drive both wage and employment growth.\n\nTwo accounting identities underlie the instrument:\n\n$$ x_{lt} = Z_{lt} G_{lt} = \\sum_{k=1}^K z_{lkt} g_{lkt} $$ {#eq-bartik-instrument-2}\nand\n$$ g_{lkt} = g_{kt} + \\tilde{g}_{lkt} $$ {#eq-bartik-instrument-3}\n\nWith $K$ industries in location $l$, employment growth decomposes into industry-level growth rates $g_{lkt}$ weighted by industry shares $z_{lkt}$. The second identity separates each location-industry growth rate into a national component and a location-specific residual. The Bartik instrument uses initial shares and national growth rates:\n\n$$ B_{lt} = Z_{l0} G_{t} = \\sum_{k=1}^K z_{lk0} g_{kt} $$ {#eq-bartik-instrument-4}\n\nThe identifying argument is that initial shares are predetermined (a level, not a growth rate) and national industry growth is not driven by any single location.\n\n\n## Bartik Instrument in special cases\n\n### Two industries and one period\n\nGPSS goes through the simplest case: two industries and one period.\n\n$$ B_l = z_{l1} g_1 + z_{l2} g_2 $$ {#eq-bartik-instrument-5}\n\nSince there are only two industries, $z_{l1} = 1 - z_{l2}$.  Then we can rewrite the Bartik instrument as\n\n$$ B_l = g_2 + (g_1 - g_2) z_{l1} $$ {#eq-bartik-instrument-6}\n\nFrom this simplest case, we see that the instrument has only $z_{l1}$, that is related to location.  If the industry share can be considered exogenous, then the instrument is valid.  We have to argue that the industry share is exogenous. In this case, the instrument is a linear function of the industry share.  Therefore, the Bartik instrument is the same as using the industry share as an instrument.\n\nGPSS shows that just-identified two-stage least squares using a Bartik instrument can in fact be written as GMM with an overidentified set of instruments, where the weight matrix is the outer product of national growth rates.  That is, Bartik estimator is equivalent to a GMM estimator, with each location share as one instrument, and the weight matrix is the outer product of national growth rates.\n\nWith $K$ industries and $T$ time periods, it's basically using $K \\times T$ instruments. Still, Bartik instrument is the same as GMM with all these instruments.\n\n\n\n## Rotemberg weights\n\nGPSS decompose the Bartik estimator:\n\n$$ \\beta_{Bartik} = \\sum_{k} \\hat \\alpha_k \\hat \\beta_k$$ {#eq-bartik-instrument-7}\nwhere\n$$ \\hat \\beta_k = (Z'_k X^{\\perp})^{-1} Z'_k Y^{\\perp}$$ {#eq-bartik-instrument-8}\nand\n$$ \\hat \\alpha_k = \\frac{g_k Z'_k X^{\\perp}}{\\sum_{k'} g_{k'}  Z'_{k'} X^{\\perp}}$$ {#eq-bartik-instrument-9}\n\nHere $X^{\\perp}$ and $Y^{\\perp}$ are the residualized $X$ and $Y$,  from the regression of $X$ and $Y$ on all other variables (controls).\n\nRotemberg weights provide a measure of how important each share is.  Read the direction carefully: if industry $k$'s own just-identified estimate $\\hat\\beta_k$ is biased by 1 percent, the overall Bartik estimate inherits $\\alpha_k$ percent of that bias.  So a large $\\alpha_k$ means the overall answer is *sensitive* to that industry, not that the industry is itself badly biased.  This is what makes the weights useful: they tell you for which instruments the exogeneity assumption has to be defended hardest.  (The formal statement is GPSS Corollary D.1, given below.)\n\n## Simulations\n\nSimulations codes are adopted from Kohei Kawaguchi's lecture notes.  I modified slightly to fit different scenarios.\n\nHere we simulate a case with 4 industries and 4 periods.  We have 1000 locations, 4 periods, and 4 industries.  The true $\\beta$ (effect of $x$ on $y$) is 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(tidyverse)\nlibrary(modelsummary)\nlibrary(kableExtra)\nlibrary(estimatr)\nset.seed(6)\nL <- 1000\nT <- 4\nK <- 4\nbeta <- 1\nsigma <-c(1, 1, 1)\n\nz_lk0 <- expand_grid(\n    l = 1:L,\n    k = 1:K\n  ) |>\nmutate(z_lk0 = runif(length(l)))\n\ng_kt <-  expand_grid(\n    t = 1:T,\n    k = 1:K\n  ) |>\n  mutate(g_kt = rnorm(n(), 0, .1))\n\ndf <- expand_grid(\n    l = 1:L,\n    t = 1:T,\n    k = 1:K\n  ) |>\n  left_join(z_lk0, by = c(\"l\", \"k\")) |>\n  left_join(g_kt,  by = c(\"k\", \"t\")) |>\n  mutate(z_lkt = z_lk0 + sigma[1] * runif(length(l)),\n    g_lkt = g_kt + sigma[2] * rnorm(length(l),0, .1)\n  )\n\ndf <- df %>%\n  group_by(t, l) |>\n  mutate(\n    z_lk0 = z_lk0 / sum(z_lk0),\n    z_lkt = (z_lkt / sum(z_lkt)),\n    x_lt = sum(z_lkt * g_lkt)\n  )\n\ndf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 16,000 × 8\n# Groups:   t, l [4,000]\n       l     t     k z_lk0     g_kt z_lkt    g_lkt    x_lt\n   <int> <int> <int> <dbl>    <dbl> <dbl>    <dbl>   <dbl>\n 1     1     1     1 0.277  0.130   0.252  0.115    0.0400\n 2     1     1     2 0.428  0.146   0.302  0.291    0.0400\n 3     1     1     3 0.121 -0.165   0.321 -0.231    0.0400\n 4     1     1     4 0.174 -0.110   0.126 -0.0185   0.0400\n 5     1     2     1 0.277 -0.0289  0.160 -0.00619  0.0402\n 6     1     2     2 0.428 -0.00130 0.356  0.0560   0.0402\n 7     1     2     3 0.121  0.0433  0.272 -0.0590   0.0402\n 8     1     2     4 0.174  0.0840  0.212  0.176    0.0402\n 9     1     3     1 0.277 -0.101   0.237 -0.0361  -0.0738\n10     1     3     2 0.428 -0.152   0.367 -0.126   -0.0738\n# ℹ 15,990 more rows\n```\n\n\n:::\n:::\n\n\nThe simulation has $L = 1000$ locations, $T = 4$ periods and $K = 4$\nindustries, 16,000 location-industry-period rows. Baseline shares $z_{lk0}$ are\nuniform draws normalised to sum to one within each location, national industry\ngrowth is $g_{kt} \\sim N(0, 0.1^2)$, current shares add a uniform perturbation\nand are renormalised, and local industry growth is\n$g_{lkt} = g_{kt} + N(0, 0.1^2)$. Local employment growth is\n$x_{lt} = \\sum_k z_{lkt} g_{lkt}$. The true $\\beta$ is 1.\n\nThis assumes we observe the industry shares at time 0 ($z_{lk0}$), and the industry growth rates ($g_{kt}$).  We also observe the industry shares at time $t$ ($z_{lkt}$).  The employment growth rate at location $l$ and time $t$ ($g_{lkt}$) is a function of $g_{kt}$ plus some noise.  We can calculate the $x_{lt}$, which is the weighted sum of industry growth rates.\n\n\nNext we generate the outcome at $l$, $t$ level.  Outcome (wage growth) is a linear function of $x$ (employment growth) at $l$, $t$ level.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_lt <- df |>\n  mutate(g_tilde_lkt = g_lkt - g_kt) |>\n  group_by(l, t) |>\n  summarise(across(c(x_lt, g_tilde_lkt),  mean),  .groups = \"drop\") |>\n  ungroup() |>\n  mutate(y_lt = beta * x_lt + sigma[3] * g_tilde_lkt)\n```\n:::\n\n\nThe outcome is $y_{lt} = \\beta x_{lt} + \\sigma_3 \\tilde g_{lt}$, where\n$\\tilde g_{lt}$ is the location's mean deviation of local from national industry\ngrowth. That deviation also enters $x_{lt}$, which is the endogeneity: local\nshocks drive both employment growth and wage growth.\n\nIf we run OLS on raw data, we'll get biased results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresult_ols <-\n  df_lt |>\n  lm(formula = y_lt ~ x_lt)\n\nmodelsummary(result_ols)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_32o752ly8vozdeft9jll = TinyTable.createTableFunctions(\"tinytable_32o752ly8vozdeft9jll\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '12', j: 2 } ], css_id: 'tinytable_css_krnatzejbkf50uu3g95i',}, \n          { positions: [ { i: '4', j: 2 } ], css_id: 'tinytable_css_l4febg8h9ubm6o2fovqf',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 } ], css_id: 'tinytable_css_lh0qph6bpylh5tryvk3e',}, \n          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_ngo3eopd1y9inrdlv4lb',}, \n          { positions: [ { i: '12', j: 1 } ], css_id: 'tinytable_css_5kj0the3hxd064fmata5',}, \n          { positions: [ { i: '4', j: 1 } ], css_id: 'tinytable_css_ndt3op9nf0l3kjcwnz4x',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 } ], css_id: 'tinytable_css_gtytx8wjrk150rs9d3aj',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_1trj4rjq9zf8xhrqaz6r',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_32o752ly8vozdeft9jll.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_32o752ly8vozdeft9jll td.tinytable_css_krnatzejbkf50uu3g95i, #tinytable_32o752ly8vozdeft9jll th.tinytable_css_krnatzejbkf50uu3g95i {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_32o752ly8vozdeft9jll td.tinytable_css_l4febg8h9ubm6o2fovqf, #tinytable_32o752ly8vozdeft9jll th.tinytable_css_l4febg8h9ubm6o2fovqf {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_32o752ly8vozdeft9jll td.tinytable_css_lh0qph6bpylh5tryvk3e, #tinytable_32o752ly8vozdeft9jll th.tinytable_css_lh0qph6bpylh5tryvk3e { text-align: center }\n    #tinytable_32o752ly8vozdeft9jll td.tinytable_css_ngo3eopd1y9inrdlv4lb, #tinytable_32o752ly8vozdeft9jll th.tinytable_css_ngo3eopd1y9inrdlv4lb {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_32o752ly8vozdeft9jll td.tinytable_css_5kj0the3hxd064fmata5, #tinytable_32o752ly8vozdeft9jll th.tinytable_css_5kj0the3hxd064fmata5 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_32o752ly8vozdeft9jll td.tinytable_css_ndt3op9nf0l3kjcwnz4x, #tinytable_32o752ly8vozdeft9jll th.tinytable_css_ndt3op9nf0l3kjcwnz4x {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_32o752ly8vozdeft9jll td.tinytable_css_gtytx8wjrk150rs9d3aj, #tinytable_32o752ly8vozdeft9jll th.tinytable_css_gtytx8wjrk150rs9d3aj { text-align: left }\n    #tinytable_32o752ly8vozdeft9jll td.tinytable_css_1trj4rjq9zf8xhrqaz6r, #tinytable_32o752ly8vozdeft9jll th.tinytable_css_1trj4rjq9zf8xhrqaz6r {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_32o752ly8vozdeft9jll\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">(1)</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">-0.000</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.001)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">x_lt</td>\n                  <td data-row=\"3\" data-col=\"2\">1.336</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.008)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"5\" data-col=\"2\">4000</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\">R2</td>\n                  <td data-row=\"6\" data-col=\"2\">0.884</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">R2 Adj.</td>\n                  <td data-row=\"7\" data-col=\"2\">0.884</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\">AIC</td>\n                  <td data-row=\"8\" data-col=\"2\">-14059.9</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">BIC</td>\n                  <td data-row=\"9\" data-col=\"2\">-14041.0</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\">Log.Lik.</td>\n                  <td data-row=\"10\" data-col=\"2\">7032.945</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">F</td>\n                  <td data-row=\"11\" data-col=\"2\">30603.441</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\">RMSE</td>\n                  <td data-row=\"12\" data-col=\"2\">0.04</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nOLS gives 1.336 with a standard error of 0.008, against a true $\\beta$ of 1 —\nbiased upward by a third, and far outside any confidence interval. The\nendogenous $\\tilde g_{lt}$ is doing the damage.\n\nNow we generate the Bartik instrument.  We calculate the Bartik instrument as the weighted sum of $z_{lk0}$ and $g_{kt}$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb_lt <- df |>\n  group_by(l, t) |>\n  summarise(b_lt = sum(z_lk0 * g_kt)) |>\n  ungroup()\n\ndf_lt <- df_lt |>\n  left_join(b_lt, by = c(\"l\", \"t\"))\n\n\nresult_first_stage <-  lm(formula = x_lt ~ b_lt, data = df_lt)\n\nmodelsummary(result_first_stage)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_qh4z4ax1ode4se58kwsg = TinyTable.createTableFunctions(\"tinytable_qh4z4ax1ode4se58kwsg\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '12', j: 2 } ], css_id: 'tinytable_css_k9smzotr5eng2ospic7s',}, \n          { positions: [ { i: '4', j: 2 } ], css_id: 'tinytable_css_lqil7ng9l4ruisbll40k',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 } ], css_id: 'tinytable_css_f0ndtp57yqj11fzkw4h6',}, \n          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_vltpsc7vf7oi54cz1uuq',}, \n          { positions: [ { i: '12', j: 1 } ], css_id: 'tinytable_css_cfgov3tnuqtqqz8awe1h',}, \n          { positions: [ { i: '4', j: 1 } ], css_id: 'tinytable_css_lhnkziswerqe37c5kkfo',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 } ], css_id: 'tinytable_css_t5v4lihbimsh83z6htup',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_fct7ajlnvgowzk8j84ij',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_qh4z4ax1ode4se58kwsg.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_qh4z4ax1ode4se58kwsg td.tinytable_css_k9smzotr5eng2ospic7s, #tinytable_qh4z4ax1ode4se58kwsg th.tinytable_css_k9smzotr5eng2ospic7s {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_qh4z4ax1ode4se58kwsg td.tinytable_css_lqil7ng9l4ruisbll40k, #tinytable_qh4z4ax1ode4se58kwsg th.tinytable_css_lqil7ng9l4ruisbll40k {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_qh4z4ax1ode4se58kwsg td.tinytable_css_f0ndtp57yqj11fzkw4h6, #tinytable_qh4z4ax1ode4se58kwsg th.tinytable_css_f0ndtp57yqj11fzkw4h6 { text-align: center }\n    #tinytable_qh4z4ax1ode4se58kwsg td.tinytable_css_vltpsc7vf7oi54cz1uuq, #tinytable_qh4z4ax1ode4se58kwsg th.tinytable_css_vltpsc7vf7oi54cz1uuq {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_qh4z4ax1ode4se58kwsg td.tinytable_css_cfgov3tnuqtqqz8awe1h, #tinytable_qh4z4ax1ode4se58kwsg th.tinytable_css_cfgov3tnuqtqqz8awe1h {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_qh4z4ax1ode4se58kwsg td.tinytable_css_lhnkziswerqe37c5kkfo, #tinytable_qh4z4ax1ode4se58kwsg th.tinytable_css_lhnkziswerqe37c5kkfo {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_qh4z4ax1ode4se58kwsg td.tinytable_css_t5v4lihbimsh83z6htup, #tinytable_qh4z4ax1ode4se58kwsg th.tinytable_css_t5v4lihbimsh83z6htup { text-align: left }\n    #tinytable_qh4z4ax1ode4se58kwsg td.tinytable_css_fct7ajlnvgowzk8j84ij, #tinytable_qh4z4ax1ode4se58kwsg th.tinytable_css_fct7ajlnvgowzk8j84ij {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_qh4z4ax1ode4se58kwsg\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">(1)</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">-0.001</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.001)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">b_lt</td>\n                  <td data-row=\"3\" data-col=\"2\">0.919</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.013)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"5\" data-col=\"2\">4000</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\">R2</td>\n                  <td data-row=\"6\" data-col=\"2\">0.573</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">R2 Adj.</td>\n                  <td data-row=\"7\" data-col=\"2\">0.573</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\">AIC</td>\n                  <td data-row=\"8\" data-col=\"2\">-11638.5</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">BIC</td>\n                  <td data-row=\"9\" data-col=\"2\">-11619.6</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\">Log.Lik.</td>\n                  <td data-row=\"10\" data-col=\"2\">5822.262</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">F</td>\n                  <td data-row=\"11\" data-col=\"2\">5361.487</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\">RMSE</td>\n                  <td data-row=\"12\" data-col=\"2\">0.06</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n\n```{.r .cell-code}\nresult_tsls <- df_lt |>\n  estimatr::iv_robust(formula = y_lt ~ x_lt | b_lt)\n\nmodelsummary::modelsummary(result_tsls)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_sqfuec538xi0o4tq08oz = TinyTable.createTableFunctions(\"tinytable_sqfuec538xi0o4tq08oz\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '10', j: 2 } ], css_id: 'tinytable_css_eimrxe956yvsleg63fi4',}, \n          { positions: [ { i: '4', j: 2 } ], css_id: 'tinytable_css_ehfvt8pkfv9xizz2d2l4',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 } ], css_id: 'tinytable_css_qqsc75wo4y35b1yknjf6',}, \n          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_dzewyn03rop8pgjl8dv4',}, \n          { positions: [ { i: '10', j: 1 } ], css_id: 'tinytable_css_ox8jgdv5di8g9yjikcr5',}, \n          { positions: [ { i: '4', j: 1 } ], css_id: 'tinytable_css_to3zrttae22mq7vc23j8',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 } ], css_id: 'tinytable_css_b1va8btzxlnpagusx8df',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_q95iegji1hwc51tmmnig',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_sqfuec538xi0o4tq08oz.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_sqfuec538xi0o4tq08oz td.tinytable_css_eimrxe956yvsleg63fi4, #tinytable_sqfuec538xi0o4tq08oz th.tinytable_css_eimrxe956yvsleg63fi4 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_sqfuec538xi0o4tq08oz td.tinytable_css_ehfvt8pkfv9xizz2d2l4, #tinytable_sqfuec538xi0o4tq08oz th.tinytable_css_ehfvt8pkfv9xizz2d2l4 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_sqfuec538xi0o4tq08oz td.tinytable_css_qqsc75wo4y35b1yknjf6, #tinytable_sqfuec538xi0o4tq08oz th.tinytable_css_qqsc75wo4y35b1yknjf6 { text-align: center }\n    #tinytable_sqfuec538xi0o4tq08oz td.tinytable_css_dzewyn03rop8pgjl8dv4, #tinytable_sqfuec538xi0o4tq08oz th.tinytable_css_dzewyn03rop8pgjl8dv4 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_sqfuec538xi0o4tq08oz td.tinytable_css_ox8jgdv5di8g9yjikcr5, #tinytable_sqfuec538xi0o4tq08oz th.tinytable_css_ox8jgdv5di8g9yjikcr5 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_sqfuec538xi0o4tq08oz td.tinytable_css_to3zrttae22mq7vc23j8, #tinytable_sqfuec538xi0o4tq08oz th.tinytable_css_to3zrttae22mq7vc23j8 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_sqfuec538xi0o4tq08oz td.tinytable_css_b1va8btzxlnpagusx8df, #tinytable_sqfuec538xi0o4tq08oz th.tinytable_css_b1va8btzxlnpagusx8df { text-align: left }\n    #tinytable_sqfuec538xi0o4tq08oz td.tinytable_css_q95iegji1hwc51tmmnig, #tinytable_sqfuec538xi0o4tq08oz th.tinytable_css_q95iegji1hwc51tmmnig {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_sqfuec538xi0o4tq08oz\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">(1)</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">-0.000</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.001)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">x_lt</td>\n                  <td data-row=\"3\" data-col=\"2\">0.990</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.012)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"5\" data-col=\"2\">4000</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\">R2</td>\n                  <td data-row=\"6\" data-col=\"2\">0.825</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">R2 Adj.</td>\n                  <td data-row=\"7\" data-col=\"2\">0.825</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\">AIC</td>\n                  <td data-row=\"8\" data-col=\"2\">-12398.4</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">BIC</td>\n                  <td data-row=\"9\" data-col=\"2\">-12379.5</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\">RMSE</td>\n                  <td data-row=\"10\" data-col=\"2\">0.05</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\nThe Bartik instrument recovers the truth: 2SLS gives 0.990 with a standard error\nof 0.012, against $\\beta = 1$, where OLS gave 1.336. The instrument is built\nfrom baseline shares and *national* growth rates, neither of which contains the\nlocal shock $\\tilde g_{lt}$, which is what breaks the endogeneity.\n\n### Calculate Rotemberg weights\n\nLet's do IV using Bartik instruments.  No controls here.  We use matrix operation to recover the IV estimates, which is the same as the tsls function in R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nB = as.matrix(cbind(1,df_lt$b_lt))\nY = as.matrix(df_lt$y_lt)\nX = as.matrix(cbind(1,df_lt$x_lt))\n\niv = round(solve(t(B)%*%X)%*%t(B)%*%Y,3)\n\n## Label and organize results into a data frame\nbeta.hat = as.data.frame(cbind(c(\"Intercept\",\"x\"),iv))\nnames(beta.hat) = c(\"Coeff.\",\"Est\")\nbeta.hat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Coeff.  Est\n1 Intercept    0\n2         x 0.99\n```\n\n\n:::\n:::\n\n\nNow we calculate the Rotemberg weights.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# This code is the R version of Paul Goldsmith-Pinkham's R code for Rotemberg weights on\n# github; which is actually a call from a C++ code by jjchern.\n# bw.R calls ComputeAlphaBeta.cpp\n# dimensions:  G is KTx1, Z is LTxKT, Y is LTx1, X is LTx1\n# so B=ZG is LTx1\n# Here I learned the dimensions from the ADH example in Paul's github.\n# in ADH example, czone(L) is 722, year(T) is 2, ind(K) is 390.\n# so G is 780x1, Z is 1444x780, Y is 1444x1, X is 1444x1\ny_lt <- df_lt |>\n  select(l,t,y_lt)\n\nY <- as.matrix(y_lt[,3])\n\nx_lt <- df_lt |>\n  select(l,t,x_lt)\n\nX <- as.matrix(x_lt[,3])\n#X <- as.matrix(cbind(1,x_lt[,3]))\n\n# global is kt level data set\n# # g_data <- df |>\n# #   group_by(k,t) |>\n# #   summarise(g_kt=sum(g_lkt*z_lkt))\n#\n# G <- as.matrix(g_data[,3])\n\nG <- as.matrix(g_kt[,3])\n\n# generate wide Z matrix, LTxKT from df\n# z_data <- df |>\n#   select(l,t,k,z_lkt) |>\n#   pivot_wider(names_from = k, values_from = z_lkt) |>\n#   select(-l, -t)\n\n# this makes a wide Z data, which is LTxKT, KT variables are generated by the spread function.\n# basically expand the shares to KT variables, filled with 0 if there is no data.\n# Use z_lk0 (the INITIAL shares), not z_lkt: the Bartik instrument is B = Z_0 G,\n# so the Rotemberg decomposition has to be taken with respect to the same Z that\n# builds the instrument. Using z_lkt here would decompose a different estimator.\n# z_data <- df |>\n#   select(l,t,k,z_lkt) |>\n#   mutate(k = str_glue(\"t{t}_sh_ind_{k}\") ) |>\n#   spread(k, z_lkt, fill = 0)\n\nz_data <- df |>\n  select(l,t,k,z_lk0) |>\n  mutate(k = str_glue(\"t{t}_sh_ind_{k}\") ) |>\n  pivot_wider(names_from = k, values_from = z_lk0, values_fill = 0)\n\nZ <- as.matrix(z_data[,-c(1,2)])\n\n# Residualize Y and X on the controls before forming the weights. There are\n# no controls here other than the constant, so the residualization is just\n# demeaning; this is what makes the Rotemberg decomposition exact (GPSS).\nYp <- Y - mean(Y)\nXp <- X - mean(X)\nbeta = round((t(Z) %*% Yp)/(t(Z) %*% Xp), digits=3)\nalpha=(diag(as.numeric(G)) %*% t(Z)  %*% Xp) / as.numeric((t(G) %*% t(Z) %*% Xp))\n\nbw <- tibble(g_kt, alpha=as.numeric(alpha), beta=as.numeric(beta)) |>\n  mutate(product=alpha*beta)\n\nbw\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 16 × 6\n       t     k     g_kt     alpha  beta   product\n   <int> <int>    <dbl>     <dbl> <dbl>     <dbl>\n 1     1     1  0.130    0.0103   0.741  0.00760 \n 2     1     2  0.146    0.0188   1.19   0.0223  \n 3     1     3 -0.165    0.0103   0.771  0.00794 \n 4     1     4 -0.110    0.00760  1.04   0.00787 \n 5     2     1 -0.0289  -0.00789  0.886 -0.00699 \n 6     2     2 -0.00130 -0.000387 0.941 -0.000364\n 7     2     3  0.0433   0.0133   0.898  0.0119  \n 8     2     4  0.0840   0.0280   0.913  0.0256  \n 9     3     1 -0.101    0.138    0.987  0.136   \n10     3     2 -0.152    0.222    0.986  0.219   \n11     3     3 -0.0569   0.0758   0.984  0.0746  \n12     3     4 -0.0994   0.136    0.993  0.135   \n13     4     1  0.0266   0.0268   1.01   0.0272  \n14     4     2  0.139    0.155    0.984  0.152   \n15     4     3  0.0263   0.0267   1.01   0.0270  \n16     4     4  0.127    0.140    1.02   0.143   \n```\n\n\n:::\n\n```{.r .cell-code}\nsum(bw$product)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9894259\n```\n\n\n:::\n:::\n\n\nThe sum of the product of $\\alpha$ and $\\beta$ should be the same as the Bartik estimator, and it is: 0.9894 against the 2SLS estimate of 0.990. The\ndecomposition is exact, not approximate.\n\nReading the table, the weights are far from uniform across the sixteen\nindustry-period cells. Period 3 carries most of the weight — its four $\\alpha$\nvalues are 0.138, 0.222, 0.076 and 0.136, summing to 0.57 — while period 2\ncontributes almost nothing and even goes slightly negative\n($\\alpha = -0.008$ and $-0.0004$ for its first two industries). The\njust-identified $\\beta_k$ estimates are all near the true 1, ranging from 0.74\nto 1.19, which is what we should see in a simulation with a homogeneous effect.\n\n\nNote there is no restriction for $\\alpha$, other than the sum is 1.  Therefore it can be negative or positive, and individual weights can exceed 1, as long as they sum to 1.  In GPSS the Rotemberg weights routinely take negative values and values greater than 1; this is a feature used to flag problematic instruments.\n\n\n\n## Why is good to have Rotemberg weights?\n\nGPSS Corollary D.1. shows the interpretation of the Rotemberg weights.\n\nThe percentage of bias can be written as:\n\n$$ \\frac{E(\\tilde{\\beta})}{\\beta_0} = \\sum_k \\alpha_k \\frac{E(\\tilde \\beta_k)}{\\beta_0}$$ {#eq-bartik-instrument-10}\n\nThis is to say the $\\alpha_k$ is the share of the bias of the estimate of $\\beta$ that comes from the bias of the estimate of $\\beta_k$.  That is, how sensitive it is to the bias from industry $k$.\n\nIn my simulations, all the industries are random, therefore the weights are random too.  But in empirical studies, they are not random, most likely dominated by some industries.  This is why it is important to have Rotemberg weights.  It tells us which industries are important in the estimation of the effect of interest.\n\n## What if you are using a reduced form?\n\nIf you use the reduced form, something like:\n\n\n$$ y_{lt} = D_{lt} \\rho + \\beta_0 B_{lt} + \\epsilon_{lt}$$ {#eq-bartik-instrument-11}\n\nwhere $B_{lt}$ is the Bartik instrument, constructed in such as a way:\n\n$$ B_{lt} = Z_{l0} G_{t} = \\sum_{k=1}^K z_{lk0} g_{kt} $$ {#eq-bartik-instrument-12}\n\nThen I think the Rotemberg weights should be calculated as:\n\n$$ \\beta_{Bartik} = \\sum_{k} \\hat \\alpha_k \\hat \\beta_k$$ {#eq-bartik-instrument-13}\nwhere\n$$ \\hat \\beta_k = (Z'_k B^{\\perp})^{-1} Z'_k Y^{\\perp}$$ {#eq-bartik-instrument-14}\nand\n$$ \\hat \\alpha_k = \\frac{g_k Z'_k B^{\\perp}}{\\sum_{k'} g_{k'}  Z'_{k'} B^{\\perp}}$$ {#eq-bartik-instrument-15}\n\nwhere $B^{\\perp}$ and $Y^{\\perp}$ are residualized $B$ and $Y$.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresult_reduced <- df_lt |>\n  lm(formula = y_lt ~  b_lt)\n\nmodelsummary::modelsummary(result_reduced)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_rp2v9cl1hxlme7z7adop = TinyTable.createTableFunctions(\"tinytable_rp2v9cl1hxlme7z7adop\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '12', j: 2 } ], css_id: 'tinytable_css_0po9biq3ykmgz7fdw659',}, \n          { positions: [ { i: '4', j: 2 } ], css_id: 'tinytable_css_rkg2d1w296edri312mao',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 } ], css_id: 'tinytable_css_9ef62yaafp6asv1vpsiy',}, \n          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_fhz241cepy2e5o2o3x5c',}, \n          { positions: [ { i: '12', j: 1 } ], css_id: 'tinytable_css_zoznm0yj2stjjtye87jw',}, \n          { positions: [ { i: '4', j: 1 } ], css_id: 'tinytable_css_3s1p7e35hpclwhc19w50',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 } ], css_id: 'tinytable_css_hik0l2m6czkblli153xe',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_y2o0tg9c3xc57g3fraop',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_rp2v9cl1hxlme7z7adop.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_rp2v9cl1hxlme7z7adop td.tinytable_css_0po9biq3ykmgz7fdw659, #tinytable_rp2v9cl1hxlme7z7adop th.tinytable_css_0po9biq3ykmgz7fdw659 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_rp2v9cl1hxlme7z7adop td.tinytable_css_rkg2d1w296edri312mao, #tinytable_rp2v9cl1hxlme7z7adop th.tinytable_css_rkg2d1w296edri312mao {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_rp2v9cl1hxlme7z7adop td.tinytable_css_9ef62yaafp6asv1vpsiy, #tinytable_rp2v9cl1hxlme7z7adop th.tinytable_css_9ef62yaafp6asv1vpsiy { text-align: center }\n    #tinytable_rp2v9cl1hxlme7z7adop td.tinytable_css_fhz241cepy2e5o2o3x5c, #tinytable_rp2v9cl1hxlme7z7adop th.tinytable_css_fhz241cepy2e5o2o3x5c {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_rp2v9cl1hxlme7z7adop td.tinytable_css_zoznm0yj2stjjtye87jw, #tinytable_rp2v9cl1hxlme7z7adop th.tinytable_css_zoznm0yj2stjjtye87jw {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_rp2v9cl1hxlme7z7adop td.tinytable_css_3s1p7e35hpclwhc19w50, #tinytable_rp2v9cl1hxlme7z7adop th.tinytable_css_3s1p7e35hpclwhc19w50 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_rp2v9cl1hxlme7z7adop td.tinytable_css_hik0l2m6czkblli153xe, #tinytable_rp2v9cl1hxlme7z7adop th.tinytable_css_hik0l2m6czkblli153xe { text-align: left }\n    #tinytable_rp2v9cl1hxlme7z7adop td.tinytable_css_y2o0tg9c3xc57g3fraop, #tinytable_rp2v9cl1hxlme7z7adop th.tinytable_css_y2o0tg9c3xc57g3fraop {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_rp2v9cl1hxlme7z7adop\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">(1)</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">-0.001</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.002)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">b_lt</td>\n                  <td data-row=\"3\" data-col=\"2\">0.909</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.023)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"5\" data-col=\"2\">4000</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\">R2</td>\n                  <td data-row=\"6\" data-col=\"2\">0.278</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">R2 Adj.</td>\n                  <td data-row=\"7\" data-col=\"2\">0.278</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\">AIC</td>\n                  <td data-row=\"8\" data-col=\"2\">-6730.0</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">BIC</td>\n                  <td data-row=\"9\" data-col=\"2\">-6711.1</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\">Log.Lik.</td>\n                  <td data-row=\"10\" data-col=\"2\">3367.980</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">F</td>\n                  <td data-row=\"11\" data-col=\"2\">1538.779</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\">RMSE</td>\n                  <td data-row=\"12\" data-col=\"2\">0.10</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nNow we calculate the Rotemberg weights for the reduced form, for our simulated data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nB <- as.matrix(b_lt[,3])\n\n# Residualize Y and B on the controls (here only a constant ⇒ demean), as in\n# the GPSS reduced-form Rotemberg formula above, so the decomposition is exact.\nYp <- Y - mean(Y)\nBp <- B - mean(B)\nbeta = (t(Z) %*% Yp)/(t(Z) %*% Bp)\nalpha=(diag(as.numeric(G)) %*% t(Z)  %*% Bp) / as.numeric((t(G) %*% t(Z) %*% Bp))\n\nbw <- tibble(g_kt, alpha=as.numeric(alpha), beta=as.numeric(beta)) |>\n  mutate(product = alpha * beta)\n\nbw\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 16 × 6\n       t     k     g_kt     alpha  beta   product\n   <int> <int>    <dbl>     <dbl> <dbl>     <dbl>\n 1     1     1  0.130    0.0218   0.320  0.00698 \n 2     1     2  0.146    0.0285   0.720  0.0205  \n 3     1     3 -0.165    0.0322   0.226  0.00730 \n 4     1     4 -0.110    0.0141   0.514  0.00723 \n 5     2     1 -0.0289  -0.00628  1.02  -0.00642 \n 6     2     2 -0.00130 -0.000344 0.973 -0.000335\n 7     2     3  0.0433   0.0132   0.829  0.0110  \n 8     2     4  0.0840   0.0304   0.773  0.0235  \n 9     3     1 -0.101    0.128    0.978  0.125   \n10     3     2 -0.152    0.211    0.954  0.201   \n11     3     3 -0.0569   0.0687   0.998  0.0685  \n12     3     4 -0.0994   0.127    0.982  0.124   \n13     4     1  0.0266   0.0240   1.04   0.0250  \n14     4     2  0.139    0.152    0.917  0.140   \n15     4     3  0.0263   0.0238   1.04   0.0248  \n16     4     4  0.127    0.133    0.989  0.131   \n```\n\n\n:::\n\n```{.r .cell-code}\nsum(bw$product)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9090661\n```\n\n\n:::\n:::\n\n\n---\n\n<!-- see-also-footer -->\n*Systematic treatment: [R](https://xiangao.github.io/causal_econometrics_guide/shift-share-iv.html) · [Julia](https://xiangao.github.io/causal_econometrics_julia/shift-share-iv.html).*\n\nThe reduced-form decomposition sums to 0.9091 rather than 0.9894, and that is\nnot an error: it decomposes the reduced-form coefficient (the effect of the\ninstrument on the outcome), not the 2SLS coefficient. The two differ by the\nfirst stage, which is not exactly 1.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}